### ISSUE TITLE
iocage in python 3.x?

### ISSUE THREAD

**Issue by jungle-boogie** [iocage/iocage#1]
Hi All,

Is there a timetable when `iocage` will be available to run in python 3.x?

Thanks

**Comment by skarekrow** [comment]
The project was done in 2.7 for FreeNAS 9.10. When (or if!) we move it to Python 3, you can certainly expect iocage to make the jump!

Thanks for all the questions, it's been nice to see engagement so quickly.

**Comment by jungle-boogie** [comment]
Hi @skarekrow,

Gotcha, thank you! My suggestion would be to have a wiki and/or FAQ with your response.

**Comment by skarekrow** [comment]
https://github.com/iocage/iocage/wiki/Python-3-version%3F done!

**Comment by rspeed** [comment]
Is Python 3 not an available package in FreeNAS 9.10, or are you trying to limit dependencies?

**Comment by skarekrow** [comment]
@rspeed Python 3 is not available on FreeNAS 9.10, no. The new iocage was created with FreeNAS as a first class citizen (they did fund it after all :D) so until FreeNAS 9.10 is using python 3 by default (could be soon who knows? :P) iocage will not follow suite.

From my brisk look at ports, it would seem Python 2.7 vastly outnumbers the available ports compared with 3.x. I think I may make @bartekrutkowski life just a bit more difficult when Python 3 is the new target :D

**Comment by rspeed** [comment]
Oh, wait. I think it just clicked. Do you mean that FreeNAS uses Python 2.7 for its management tools?

**Comment by skarekrow** [comment]
Yes :) FreeNAS 9.10 currently targets Python 2.7 for all of its mechanisms.

**Comment by rspeed** [comment]
Okay, that makes waaaaaay more sense. Thanks!

**Comment by skarekrow** [comment]
Good news, I got the go ahead to look at 3 support for this. So stay tuned!

**Comment by jungle-boogie** [comment]
wow!

**Comment by skarekrow** [comment]
Hah, forgot to come back here and tell you gents that iocage is now officially Python 3 enabled. I messed with keeping both but decided I'd rather not have that headache down the road. So we are Python 3 only from now on \m/

**Comment by rspeed** [comment]
That makes things a lot easier for me, thanks!

**Comment by jungle-boogie** [comment]
I don't think the wiki page is needed anymore. ;)

The wiki seems to be read only or else I would have made this change myself.

**Comment by skarekrow** [comment]
Hmm I'll look at permissions on that, and yeah that's a good point :D

**Comment by skarekrow** [comment]
Ok it looks like you should be able to add pages in a PR? But just not remove them.

Can you send a test PR @jungle-boogie so we can validate that's the case?

**Comment by jungle-boogie** [comment]
I don't know how to submit a PR on something not in the repo.

I can (and you should be able as well) to edit this wiki on github.com directly.
https://github.com/alfredh/baresip/wiki

**Comment by skarekrow** [comment]
Hmm alright, let me make it public then. I wasn't sure if that public setting also restricted writes instead of just edits.
