### ISSUE TITLE
Fails when run on a system without at least one pool

### ISSUE THREAD

**Issue by wblock** [iocage/iocage#100]
Make sure to follow and check these boxes before submitting an issue! Thank you.

- [x] Supply `iocage --version`

iocage 0.9.7 2017/03/08

- [x] Supply the commands used, along with any steps to recreate it.

iocage help

- [x] Provide the output from the command you issues.

iocage help

Traceback (most recent call last):
  File "/usr/local/bin/iocage", line 10, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.6/site-packages/iocage/main.py", line 88, in main
    IOCCheck()
  File "/usr/local/lib/python3.6/site-packages/iocage/lib/ioc_check.py", line 15, in __init__
    self.pool = IOCJson().json_get_value("pool")
  File "/usr/local/lib/python3.6/site-packages/iocage/lib/ioc_json.py", line 292, in json_get_value
    "\"iocage activate\"".format(zpools[0]))
IndexError: list index out of range

- [x] Supply what you expected the result or output to be

No pools found

(Should always do bounds checking on input parameters.)

- [x] Checked that the problem has not already been fixed on `master` if using
 a stable release.

**Comment by skarekrow** [comment]
This isn't a input paramater, but rather the automatic activation of the first zpool. It's just naively expecting a user to have read the `REQUIREMENTS` at the bottom, will add a check :)

Thanks!

**Comment by wblock** [comment]
The number of pools is not directly supplied by the user, but certainly input to the program.

Actually, the **help** subcommand should work even without pools, like the --version option.

**Comment by skarekrow** [comment]
That should work like that currently. It's not a high priority issue if it doesn't but feel free to submit another issue or a PR.
