### ISSUE TITLE
ip4=inherit does not work

### ISSUE THREAD

**Issue by jyoung15** [iocage/iocage#101]
Creating a jail with ip4=inherit does not seem to work properly in iocage.  `jls -s` shows ip4=disable after starting the jail.  Manually creating a jail without iocage works as intended.

Traced problem to the way `jail -c` is called in ioc-rc.  Apparently if ip4.addr is set even with an empty string it will override the ip4=inherit setting.  I assume the same problem exists with ip6 as well.

This patch fixed the issue for me, but has not been tested thoroughly:

```
--- /usr/local/lib/iocage/ioc-rc.orig   2015-06-01 17:55:02.718039614 -0400
+++ /usr/local/lib/iocage/ioc-rc        2015-06-01 17:59:46.842025609 -0400
@@ -226,9 +226,15 @@
         ip6_addr=""
     fi

+    if [ "$ip4_addr" ]; then
+       ip4_addr_propline="ip4.addr=$ip4_addr"
+    else
+       ip4_addr_propline=""
+    fi
+
     if [ $ipv6 == "on" ] ; then
         jail -c \
-        ip4.addr="$ip4_addr" \
+        $ip4_addr_propline \
         ip4.saddrsel="$(__get_jail_prop ip4_saddrsel $name)" \
         ip4="$(__get_jail_prop ip4 $name)" \
         ip6.addr="$ip6_addr" \
@@ -269,7 +275,7 @@
         persist
     else
         jail -c \
-        ip4.addr="$ip4_addr" \
+        $ip4_addr_propline \
         ip4.saddrsel="$(__get_jail_prop ip4_saddrsel $name)" \
         ip4="$(__get_jail_prop ip4 $name)" \
         name="ioc-$(__get_jail_prop host_hostuuid $name)" \
```

Issue experienced on 10.1-RELEASE-p10 amd64

**Comment by pannon** [comment]
Confirmed, @jyoung15 would you mind to submit your PR against develop?

**Comment by jyoung15** [comment]
Sorry.  This appears related to [Bug 196474](https://bugs.freebsd.org/bugzilla/show_bug.cgi?id=196474).   When I run the iocage script with sh -x it calls jail as follows:

`jail -c ip4.saddrsel=1 ip4=inherit ip6.saddrsel=1 ip6=new ...`

I suspect the issue is because ip6=new but ip6.addr is not set.  I will see if I can modify my patch to work around this bug.

**Comment by pannon** [comment]
@jyoung15 inheritance should now work without panic.
