### ISSUE TITLE
behaviour when zpool is gone

### ISSUE THREAD

**Issue by shivno** [iocage/iocage#101]
iocage version is master from now.

i dont know if this usecase is too odd:
i have a server which provides offsite backups, drives are swapped in and out. jails should be on the drives. 
workflow: perform backup scripts (which should be untrusted). then snapshot it, send mail, admin removes drive and delivers to another location on rotation.

the problem with iocage: when a zpool is removed iocage prints on every invocation:
`cannot open 'hd-a3dafa': dataset does not exist`.
i dont know how to erase this information, there is no iocage deactivate or similar. dont know if you would support this. nothing else seems to be affected from that. iocage still works well. thanks

**Comment by shivno** [comment]
oh sorry when i destroy the zpool, its ok. never did that before because i reattached the drives later. but why does iocage iterate over zpools in the first place? i thought via activate i tell it explicitly which zpool to use.

**Comment by skarekrow** [comment]
It depends on what's being called, but it's likely the side effect of looking for the active pool when you invoke a command. You should be properly exporting this pool, not just removing the disks and leaving it's entry there.

There isn't anything I can see that `iocage` itself should change, as this is just a odd usecase ;)
