### ISSUE TITLE
Specific JID for Iocage

### ISSUE THREAD

**Issue by sachaz** [iocage/iocage#1010]
Make sure to follow and check these boxes before submitting an issue! Thank you.

- Version 1.2 RC

~~~
iocage list
+-----+----------------+-------+--------------+-----------------------------+
| JID |      NAME      | STATE |   RELEASE    |             IP4             |
+=====+================+=======+==============+=============================+
| 4   | prometheus     | up    | 12.0-RELEASE | XXX.XXX.XXX.XX              |
~~~
~~~
jls -N
 JID             IP Address      Hostname                      Path
 ioc-prometheus  185.233.100.77  prometheus                    /iocage/jails/prometheus/root
~~~

why the JID have a "ioc-" before the jail name it breaks the jexec $hostname 

Kind regards

**Comment by skarekrow** [comment]
That won't break jexec, you can just prepend ioc- to it. It's there to allow iocage jails to operate alongside any other jail managers, including `jail(8)`

**Comment by sachaz** [comment]
is a way to remove the ioc prefix in the JID name ?

**Comment by skarekrow** [comment]
It's hardcoded currently, @sonicaj do you see value in allowing that to be a default/per-jail property?

**Comment by sonicaj** [comment]
@skarekrow no. And i think we shouldn’t as well. @sachaz please add ioc as a prefix if you’re scripting.

**Comment by sachaz** [comment]
ok thanks for your help
