### ISSUE TITLE
Adjust pf firewall nat rules more properly when using multiple

### ISSUE THREAD

**Issue by Tsaukpaetra** [iocage/iocage#1011]
Referencing my attempt to fix multi nat_prefix setups when using the pf firewall:
https://github.com/freenas/iocage/pull/192/commits/c766f262110e0ea5fb6b250b894806ef0f6a61c1

I think it was just a little oversight when recreating the config. Currently it just erases all nat rules when it should just be looking for the one it's specifically creating for.

Make sure to follow and check these boxes before submitting an issue! Thank you.

- [x] Supply `iocage --version` : **Version 1.2 RC**
- [x] Supply the commands used, along with any steps to recreate it. **iocage start blah** against two jails that use different nat_prefix when using the pf firewall.
- [x] Provide the output from the command you issued. No output, just one jail isn't accessible on the network. This corresponds to whichever jail was started last, i.e. starting them in reverse order causes the other one to not work.
- [x] Supply what you expected the result or output to be: Works. ;)
- [x] Checked that the problem has not already been fixed on `master` if using
 a stable release. **Issue is present on Master.** 👍

**Comment by sonicaj** [comment]
@Tsaukpaetra we don't allow nat_prefixes to be on per jail basis ( or your case where a couple of jails are running with a different prefix and others are started with a different one - i am going to introduce validation which makes sure that this doesn't happen ).
However we understand your use case is basically ability to know for sure which jail will have which ip ( static ip's for NAT ) and we have a ticket for it in our tracker ( the one you made already ). I'm closing this in favor of that.
Thank you for letting us know about this case.
