### ISSUE TITLE
iocage create starts jail when boot="on"

### ISSUE THREAD

**Issue by Corvan** [iocage/iocage#1023]
Make sure to follow and check these boxes before submitting an issue! Thank you.

- [x] Supply `iocage --version`
- [x] Supply the commands used, along with any steps to recreate it.
- [ ] Provide the output from the command you issued.
- [x] Supply what you expected the result or output to be
- [x] Checked that the problem has not already been fixed on `master` if using
 a stable release.

Hey,

Using Version 1.1 RELEASE 2019/01, I realized that the property boot="on" automatically starts a jail on invoking  `iocage create -n test boot="on"`.

If this is intended behavior it is ok with me, but I was a bit confused and searching for a bug in my code, because I was not expecting this behaviour and it is not documented in iocage(8). While agreeing with the fact that most probably one wants a running jail somewhen when one turns boot="on", I can think of some use cases in which I want to have this property set for later, but still want to do some changes to the turned off jail, before starting it.

So I see two ways of dealing with this:

1. change the behaviour to not starting a jail when boot="on"
2. document that boot="on" starts the jail on creation

I would be willing sending in a PR with the chosen option, but wanted to ask before how it was intended.

Cheers
Lars

**Comment by skarekrow** [comment]
That’s expected :) I thought it was documented but a PR doing so would be great!
