### ISSUE TITLE
man page pkg py36-iocage-1.1

### ISSUE THREAD

**Issue by kitten77** [iocage/iocage#1025]
small issue with the man page.
Running:
FreeBSD 12.0-RELEASE FreeBSD r341666 GENERIC  amd64
iocage -v Version 1.1 RELEASE 2019

from man page:

     To enable all the features iocage supports, consider building a kernel
     with these options:

           options         VIMAGE
           options         RACCT
           options         RCTL

as far as I can tell these options is now in the GENERIC kernel. I think it has been for awhile now ?

**Comment by skarekrow** [comment]
VIMAGE only came to GENERIC in 12, the rest however have been around for some time.
