### ISSUE TITLE
No default gateway interface found

### ISSUE THREAD

**Issue by kitten77** [iocage/iocage#1026]
root@gaia:/home/l9 # ifconfig
bridge0: flags=8843<UP,BROADCAST,RUNNING,SIMPLEX,MULTICAST> metric 0 mtu 1500
        ether 02:a7:29:28:5a:00
        id 00:00:00:00:00:00 priority 32768 hellotime 2 fwddelay 15
        maxage 20 holdcnt 6 proto rstp maxaddr 2000 timeout 1200
        root id 00:00:00:00:00:00 priority 32768 ifcost 0 port 0
        member: vnet0.6 flags=143<LEARNING,DISCOVER,AUTOEDGE,AUTOPTP>
                ifmaxaddr 0 port 4 priority 128 path cost 2000
        member: em0 flags=143<LEARNING,DISCOVER,AUTOEDGE,AUTOPTP>
                ifmaxaddr 0 port 1 priority 128 path cost 2000000
        groups: bridge 
        nd6 options=9<PERFORMNUD,IFDISABLED>

root@gaia:/home/l9 # iocage -v 
Version 1.1 RELEASE 2019/01

root@gaia:/home/l9 # iocage get all test1
CONFIG_VERSION:17
vnet_default_interface:auto

root@gaia:/home/l9 # iocage start test1
* Starting test1
  + Started OK
  + Using devfs_ruleset: 5
No default gateway interface found

root@test1:/ # ifconfig
lo0: flags=8008<LOOPBACK,MULTICAST> metric 0 mtu 16384
        options=680003<RXCSUM,TXCSUM,LINKSTATE,RXCSUM_IPV6,TXCSUM_IPV6>
        groups: lo 
        nd6 options=21<PERFORMNUD,AUTO_LINKLOCAL>

root@gaia:/home/l9 # iocage stop test1
* Stopping test1
  + Executing prestop OK
  + Stopping services OK
  + Tearing down VNET FAILED
  ifconfig: interface vnet0.5 does not exist
  + Removing devfs_ruleset: 5 OK
  + Removing jail process OK
  + Executing poststop OK

root@gaia:/home/l9 # iocage set vnet_default_interface=bridge0 test1

root@gaia:/home/l9 # iocage start test1
* Starting test1
  + Started OK
  + Using devfs_ruleset: 5
  + Configuring VNET OK
  + Starting services OK
  + Executing poststart OK

root@gaia:/home/l9 # iocage list -l
+-----+-------+------+-------+------+-----------------+-------------------+-----+----------+----------+
| JID | NAME  | BOOT | STATE | TYPE |     RELEASE     |        IP4        | IP6 | TEMPLATE | BASEJAIL |
+=====+=======+======+=======+======+=================+===================+=====+==========+==========+
| 6   | test1 | on   | up    | jail | 12.0-RELEASE-p9 | vnet0|10.1.1.2/24 | -   | -        | no       |
+-----+-------+------+-------+------+-----------------+-------------------+-----+----------+----------+
root@gaia:/home/l9 # jexec 6
root@test1:/ # ifconfig
lo0: flags=8049<UP,LOOPBACK,RUNNING,MULTICAST> metric 0 mtu 16384
        options=680003<RXCSUM,TXCSUM,LINKSTATE,RXCSUM_IPV6,TXCSUM_IPV6>
        inet6 ::1 prefixlen 128 
        inet6 fe80::1%lo0 prefixlen 64 scopeid 0x1 
        inet 127.0.0.1 netmask 0xff000000 
        groups: lo 
        nd6 options=21<PERFORMNUD,AUTO_LINKLOCAL>
epair0b: flags=8843<UP,BROADCAST,RUNNING,SIMPLEX,MULTICAST> metric 0 mtu 1500
        options=8<VLAN_MTU>
        ether 60:a4:4c:35:09:17
        hwaddr 02:e4:b2:31:f8:0b
        inet6 fe80::62a4:4cff:fe35:917%epair0b prefixlen 64 scopeid 0x2 
        inet 10.1.1.2 netmask 0xffffff00 broadcast 10.1.1.255 
        inet 0.0.0.0 netmask 0xff000000 broadcast 255.255.255.255 
        groups: epair 
        media: Ethernet 10Gbase-T (10Gbase-T <full-duplex>)
        status: active
        nd6 options=21<PERFORMNUD,AUTO_LINKLOCAL>

Seems like there is an error in auto selection of vnet_default_interface

**Comment by sonicaj** [comment]
Can you please share the output of `netstat -nr` and also please use triple back ticks before/after of the output to format it properly. It's very hard to read otherwise.
```
like this is in triple back ticks
```
Also it would be nice if you could share the output of `ifconfig` again in backticks ( to make it more readable ).
Thank you @kitten77

**Comment by sonicaj** [comment]
Plus it seems you have suppressed output of `iocage get all`, please don't do that as diagnosis becomes difficult otherwise

**Comment by kitten77** [comment]
I normally do not use ipv4 so what i discovered now is that there wasn't a default ipv4 route out, so i am guessing the auto selection is based up on default route. and since there was no 0.0.0.0 route it could not determin the default interface... 
Yeah i surpressed it since it was not a full output

**Comment by sonicaj** [comment]
I would recommend trying master as lots of ipv6 changes have been committed since your version

**Comment by kitten77** [comment]
yeah I am on my way to master, was just testing the 1.1 for fun.
setting up a new working enviroment, and that is always a good time to test the pkg install

**Comment by kitten77** [comment]
but that error could have been clearer on what was missing and needed to be set manually took me sometime to actually figure out why it was crashing
