### ISSUE TITLE
Mention need to add zfs_enable to jail rc.conf when using jail_zfs_dataset

### ISSUE THREAD

**Issue by geoffgarside** [iocage/iocage#103]
I don't know if other people will miss this like I did, but it might be worth mentioning that when using the `jail_zfs_dataset` in a jail, after configuring the mount point, or possibly as a matter of course, that the `zfs_enable="YES"` needs to be set in `/etc/rc.conf` for the dataset to be mounted when the jail is started.

Hopefully this will help others to avoid feeling foolish like I did when I finally realised that I'd forgotten to do this.

**Comment by skarekrow** [comment]
AFAIK I only did ```allow_mount_zfs=1``` and ```jail_zfs=on``` when using ```jail_zfs_dataset```. It's been a little while since i've done it, so I may be forgetting something. But I don't think adding zfs_enable to the jail's rc.conf was necessary.
