### ISSUE TITLE
iocage create without args should display --help

### ISSUE THREAD

**Issue by shivno** [iocage/iocage#103]
master from now.

imho it would be better to display the full help like in --help when `iocage create` is done. now its `Must supply either template or release`. may be applicable to other commands as well.

**Comment by skarekrow** [comment]
The issue being that I have to set defaults for everything to `None` or something similar, and then do a lot of parsing. Which negates a lot of the benefits of using the click library for that purpose. If one day down the road I can, I will, but this is not on the table in the foreseeable future.

Thanks!
