### ISSUE TITLE
iocage sometimes segfaults

### ISSUE THREAD

**Issue by stratacast** [iocage/iocage#1037]
Make sure to follow and check these boxes before submitting an issue! Thank you.

- [x] Supply `iocage --version`
Version 1.1 RELEASE 2019/01
- [x] Supply the commands used, along with any steps to recreate it.
iocage list (seems more common after reboot)
- [x] Provide the output from the command you issued.
segfault (core dumped)
- [x] Supply what you expected the result or output to be
The list of jails running
- [x] Checked that the problem has not already been fixed on `master` if using
 a stable release.

It seems as of late, especially with FreeBSD 12.0 I have been having some very random iocage issues. Sometimes I get segfaults running a simple `iocage list`, in addition to that not all my jails start properly at boot. I need to manually start them. These jails have been upgraded from 11.2 -> 12.0...which, could very well be the issue. All of this is grabbed from the latest repo for pkg. Maybe it's just my hardware is old enough that it doesn't play nicely with FreeBSD? It's an old Intel Xeon X3430. These have been running fine for the last 7 months after being upgraded, I'd just get the boot issue. Now suddenly I'm getting issues with a simple `iocage list` at times, so it seems the issue is getting progressively worse. This isn't affecting another box I have that also has been upgraded from 11.2 -> 12.0 so maybe it is hardware. 

`FreeBSD 12.0-RELEASE-p9 GENERIC`

**Comment by igalic** [comment]
can you enable core dumps to see what may be causing the segfault?

**Comment by sonicaj** [comment]
@stratacast yes please as @igalic suggested. I have not seen that behavior on latest master. Once you have the core dump, can you please share it ? ( drive etc ? )

**Comment by stratacast** [comment]
Hi there, I do have a core dump. Are there any possible privacy/confidentiality issues with providing the core file? This is what I get when I load the core in a debugger:

```
(No debugging symbols found in python3.6)
(gdb) core python3.6.core 
[New LWP 101905]
warning: File "/usr/local/lib/libpython3.6m.so.1.0-gdb.py" auto-loading has been declined by your `auto-load safe-path' set to "$debugdir:$datadir/auto-load".
To enable execution of this file add
	add-auto-load-safe-path /usr/local/lib/libpython3.6m.so.1.0-gdb.py
line to your configuration file "/root/.gdbinit".
To completely disable this security protection add
	set auto-load safe-path /
line to your configuration file "/root/.gdbinit".
For more information about this security protection see the
"Auto-loading safe path" section in the GDB manual.  E.g., run from the shell:
	info "(gdb)Auto-loading safe path"
Core was generated by `/usr/local/bin/python3.6 /usr/local/bin/iocage list -h'.
Program terminated with signal SIGSEGV, Segmentation fault.
#0  0x00000008003c21bf in PyTuple_Pack () from /usr/local/lib/libpython3.6m.so.1.0
```

I Could install from master and check, but I really don't want to because I am running some services on this box that some folks depend on :)

**Comment by sonicaj** [comment]
@stratacast you need to have python debugging extensions so we can clearly figure out what is crashing and how we can correct that behavior. Here's a link https://wiki.python.org/moin/DebuggingWithGdb. You should be able to download it with pkg as well for python. Once you have done that, please regenerate the core dump and share it. I think it should be okay to share it privacy wise. You can email me a drive link perhaps at `waqar at ixsystems.com`.

**Comment by stratacast** [comment]
I couldn't find anything more on this, and it seems after updating to 1.1_1 on FreeBSD 12.0 the issue completely went away. So I think there was a specific issue to my system, and not iocage. At this point, I can't reproduce this anymore so I think it's likely a non-issue since only I reported it and can't reproduce after the update
