### ISSUE TITLE
Setting default value of property failed

### ISSUE THREAD

**Issue by bougie** [iocage/iocage#104]
I can't set a default value on my iocage installation (doc at http://iocage.readthedocs.org/en/latest/basic-use.html#system-wide-defaults)

An example :

    lucifer$ iocage set boot=on default
      ERROR: default not found

    lucifer$ iocage --version
    iocage 1.5.1 (2015/03/23)

**Comment by skarekrow** [comment]
Your version is out of date. Please update.

**Comment by bougie** [comment]
Not working on latest version:

    lucifer% iocage --version
    iocage 1.6.2 (2015/05/01)

    lucifer% sudo iocage set boot=on default
    lucifer% sudo iocage defaults | grep boot
    boot=off

**Comment by pannon** [comment]
@bougie can you verify this with `iocage get boot default` ? The `iocage defaults` is only for script defaults i.e. not the ones stored in ZFS. 

If you create a new jail `boot` should be set to `on` .

In the meanwhile I will patch defaults to display stored defaults too.

**Comment by bougie** [comment]
It works with your command :

    lucifer% sudo iocage set boot=on default
    lucifer% iocage get boot default
    on
    lucifer% sudo iocage create tag=toto
    lucifer% iocage get boot toto
    on

And, with defaults :

    lucifer% sudo iocage defaults | grep boot
    boot=off

**Comment by pannon** [comment]
@bougie please try with latest (1.6.3) from `develop` branch.
