### ISSUE TITLE
IP Validation blocks PTP interfaces

### ISSUE THREAD

**Issue by asomers** [iocage/iocage#1041]
PR #792 added validation for IP addresses.  However, it wrongly excluded assigning point-to-point addresses to jails.  The below commands worked on earlier versions of iocage, and resulted in a jail that directed all of its traffic over the ptp interface.  On the current version of iocage, this command fails.  Commenting out the check added in #792 fixes the problem.

```
$ iocage --version
Version	1.1 RELEASE 2019/01
$ iocage set ip4_addr="tun256|192.168.154.97 192.168.154.1" vpn
Please provide a valid ip: Expected 4 octets in '192.168.154.97 192.168.154.1'
```

**Comment by sonicaj** [comment]
Well that's a format which wasn't explicitly supported before i guess or at least as far as i am aware. Thank you for bringing this to our attention @asomers. @skarekrow please confirm if you have any objections for the above format ?

**Comment by skarekrow** [comment]
Nope I think it adds value
