### ISSUE TITLE
Request RELEASE iocage 1.2

### ISSUE THREAD

**Issue by araujobsd** [iocage/iocage#1044]
Hi all,

It is time to release a new iocage version, isn't it?
Do you guys have any plan?

Cheers,

**Comment by ghost** [comment]
I would certainly prefer to see more frequent releases. There are bug fixes nearly every day.

**Comment by sonicaj** [comment]
@araujobsd it has been released

**Comment by araujobsd** [comment]
Thank you all!!! I'm going to  update the FreeBSD ports right now.

Cheers.

**Comment by araujobsd** [comment]
It is done: https://svnweb.freebsd.org/changeset/ports/512999

Thanks @sonicaj
