### ISSUE TITLE
Only migrate command available after upgrade from 1.1 to 1.2

### ISSUE THREAD

**Issue by olenchenko** [iocage/iocage#1049]
Make sure to follow and check these boxes before submitting an issue! Thank you.

- [X] Supply `iocage --version`
# iocage -v
Version 1.2

- [X] Supply the commands used, along with any steps to recreate it.
 # iocage list

- [X] Provide the output from the command you issued.
 # iocage list
Usage: iocage [OPTIONS] COMMAND [ARGS]...
Try "iocage --help" for help.

Error: No such command "list".

- [X] Supply what you expected the result or output to be
Expected list of running jails

- [X] Checked that the problem has not already been fixed on `master` if using
 a stable release.

OS: FreeBSD 12.0-RELEASE-p10 GENERIC  amd64

# iocage --help
Usage: iocage [OPTIONS] COMMAND [ARGS]...

  A jail manager.

Options:
  -v, --version  Display iocage's version and exit.
  -f, --force    Allow iocage to rename datasets.
  -D, --debug    Log debug output to the console.
  --help         Show this message and exit.

Commands:
  migrate  Migrate all iocage_legacy develop basejails to new clonejails.
Only migrate command is available.

Iocage is installed from ports, ports were updated with portmaster.

**Comment by fuchst** [comment]
I had the same issue and it seems a dependency was not fulfilled.
All commands except "migrate" import iocage_lib.iocage. This in turn imports ioc_plugin.py which itself imports **git**. And that's where my problem came from since git was not installed.

Solution:
As a fix I installed the ports _py-gitpython_ and _git-lite_ and all the commands are recognized again.

**Comment by neelchauhan** [comment]
I have this issue also. @fuchst's solution works.

I sent a patch for the iocage port: https://bugs.freebsd.org/bugzilla/show_bug.cgi?id=240927

**Comment by vendion** [comment]
Just an FYI, `devel/git-lite` and `devel/git` conflict with each other but as long as either one is installed along with `devel/py-gitpython` iocage is able to recognize all of its commands again.

Not sure how this affects the patch that @neelchauhan submitted against the iocage port.

**Comment by olenchenko** [comment]
Hi guys.
Fix mentioned by fuchst worked.
And patch by neelchauhan has been merged and iocage FreeBSD port is updated now.

Great work.
Thanks!

**Comment by mtoftum** [comment]
The fix does indeed seem to make iocage work again, but this now forces git-lite and doesn't accept git.

**Comment by vendion** [comment]
@mtoftum I echoed my previous comment about the dependency conflict upstream to ticket in the FreeBSD bugzilla. https://bugs.freebsd.org/bugzilla/show_bug.cgi?id=240927#c3 feel free to also pitch in there if you have anything else worth adding.

Hopefully this is fixed before a binary package is built and copied up to the repos.
