### ISSUE TITLE
sshd ipv6 rc.conf startup

### ISSUE THREAD

**Issue by kitten77** [iocage/iocage#105]
muad@gaia:~ % iocage -v
Version 0.9.7 2017/03/08

root@gaia:/home/muad # iocage start irssi
* Starting a3cbb55a-2765-4033-9dba-3141ce2add17 (irssi)
  + Started OK
  + Starting services OK

iocage console irssi

/etc/rc.conf
  sshd_enable="YES"

/etc/ssh/sshd_config:
  #Port 22
  #AddressFamily any 
  ListenAddress 0.0.0.0
  ListenAddress 2a01:4f8:151:64a3::1
  #ListenAddress ::

root@irssi:~ # netstat -an
netstat: kvm not available: /dev/mem: No such file or directory
Active Internet connections (including servers)
Proto Recv-Q Send-Q Local Address          Foreign Address        (state)
tcp4       0      0 10.0.0.1.22            *.*                    LISTEN
Active UNIX domain sockets
Address          Type   Recv-Q Send-Q            Inode             Conn             Refs          Nextref Addr
fffff80013f942d0 dgram       0      0                0 fffff800c94c0b40                0 fffff80013feda50
fffff80013feda50 dgram       0      0                0 fffff800c94c0b40                0 fffff8004d00f2d0
fffff8004d00f2d0 dgram       0      0                0 fffff800c94c0b40                0                0
fffff800c94c0b40 dgram       0      0 fffff80144ebe1d8                0 fffff80013f942d0                0 /var/run/logpriv
fffff80013fed960 dgram       0      0 fffff800155a5760                0                0                0 /var/run/log
root@irssi:~ # cat /var/log/messages 
Apr 12 11:15:03 irssi newsyslog[79070]: logfile first created
Apr 12 11:15:03 irssi syslogd: kernel boot file is /boot/kernel/kernel
Apr 12 11:15:03 irssi sshd[79147]: error: Bind to port 22 on 2a01:4f8:151:64a3::1 failed: Can't assign requested address.

-- sshd ipv6 not working

root@irssi:~ # service sshd restart
Performing sanity check on sshd configuration.
Stopping sshd.
Waiting for PIDS: 79638.
Performing sanity check on sshd configuration.
Starting sshd.
root@irssi:~ # netstat -an 
netstat: kvm not available: /dev/mem: No such file or directory
Active Internet connections (including servers)
Proto Recv-Q Send-Q Local Address          Foreign Address        (state)
tcp4       0      0 10.0.0.1.22            *.*                    LISTEN
tcp6       0      0 2a01:4f8:151:64a.22    *.*                    LISTEN
Active UNIX domain sockets
Address          Type   Recv-Q Send-Q            Inode             Conn             Refs          Nextref Addr
fffff8004d00f2d0 dgram       0      0                0 fffff800c94c14b0                0 fffff8004d00f5a0
fffff8004d00f5a0 dgram       0      0                0 fffff800c94c14b0                0                0
fffff800c94c14b0 dgram       0      0 fffff801e9ef93b0                0 fffff8004d00f2d0                0 /var/run/logpriv
fffff800c94c0780 dgram       0      0 fffff800155a53b0                0                0                0 /var/run/log

now it works. what why how?

**Comment by skarekrow** [comment]
`ListenAddress 0.0.0.0` is likely your problem, but this is not an iocage issue. But a configuration one, will be closing :)

**Comment by kitten77** [comment]
https://gist.github.com/kitten77/c3159cd6fca61a02a551388a43426c0f

nope it runs fine from jail.conf.

**Comment by skarekrow** [comment]
Oh this totally spaced my mind, this may be the fun issue some of our users have found time to time. We have an entry for it in our old [documentation](http://iocage.readthedocs.io/en/latest/known-issues.html). It's entirely random, as I am sometimes able to trigger it.

Try this:
`sysctl net.inet6.ip6.dad_count=0` on the host, and `iocage restart JAIL`, and let me know how you make out. But do note since you're using IP aliases (the default) that you really should tell your host to listen on a specific address and each jail to as well, not just `0.0.0.0`.

**Comment by kitten77** [comment]
I will :)

**Comment by kitten77** [comment]
that solved it for me, i am working on a script that creates and starts iocage/jail i will add a tag into the sshd_config that tells sshd what ip it should listen too, but for now i have focused on getting iocage up and running and setting what i need there.
This is actually something that iocage could do also, would be a nice feature for iocage.

**Comment by skarekrow** [comment]
That's great news! I'm open to any PRs that makes life easier for people :)

**Comment by kitten77** [comment]
by the way i came over this

https://gist.github.com/wido/af7811113a5d1a9a2fe6448954839d33

iocage set ip6_addr="em0|ip6"
if ip6_addr == ip6 generate

Haven't been inside your code enough too know where it should go yet, I am still working on the sshd config. But is this something that makes sense too add? who really wanna type in a ip6 adresse, that is like the stone age

**Comment by skarekrow** [comment]
Yeah this was done in the shell version for `ip4` addresses, but the implementation hasn't been ported. This is much cleaner, I think this could be an excellent addition.

I would like the syntax to be `iocage set ip6_addr="em0|AUTOIP6"`so we can look for `AUTOIP6`, and then replace the property with the generated address.

I think the property for the subnet should be house in `auto_ip6_subnet` and `auto_ip4_subnet` respectively. The harder bit will be to validate that the IP isn't in use yet from any other jail. Sounds like you have 2 good PR's coming, very exciting!
