### ISSUE TITLE
fdescfs and devfs from within jail does not unmount on shutdown

### ISSUE THREAD

**Issue by vendion** [iocage/iocage#1050]
- [x] Supply `iocage --version`
Version	1.2
- [x] Supply the commands used, along with any steps to recreate it.
```
iocage stop hugo
mount
```
- [x] Provide the output from the command you issued.
output from stopping the jail
```
* Stopping hugo
  + Executing prestop OK
  + Stopping services OK
  + Removing devfs_ruleset: 7 OK
  + Removing jail process FAILED:
jail: ioc-hugo: mount.fdescfs: /iocage/jails/hugo/root/dev/fd: not a mount point
```
output from mount command
```
devfs on /iocage/jails/hugo/root/dev (devfs, local, multilabel)
fdescfs on /iocage/jails/hugo/root/dev/fd (fdescfs)
```
- [x] Supply what you expected the result or output to be
Both devfs and fdescfs should be unmounted when the jail is stopped.
- [x] Checked that the problem has not already been fixed on `master` if using
 a stable release.

Neather devfs and fdescfs are not present in the jails fstab config, and even though the output says that removing the jail process failed, `iocage list` shows it as being down and the jail is not present in `jls` output.

**Comment by BlueSpaceCanary** [comment]
I've had this happening the last several months as well, including on newly-created jails. I assume it's https://github.com/iocage/iocage/blob/405467e2a853de94d9c075b7c439c21001989105/iocage_lib/ioc_destroy.py#L125 causing the error, but I'm not sure why it's intermittent. If I do a restart and hit this, start the jail, then restart it again, I don't get the error.

**Comment by BlueSpaceCanary** [comment]
Sorry to bump an old issue, but I happened to notice just now that `mount | grep fdescfs` showed multiple entries for `/iocage/jails/$MYJAIL/root/dev/fd` some time after hitting this particular bug? misconfiguration?, which may be useful data. The jail has `mount_fdescfs:1`

**Comment by Mannekino** [comment]
I'm encountering this issue now also. I just tried updating a Jail of mine to the latest patch level and I encountered this error. Is there any way I can prevent this from happening? This is happening on a FreeNAS 11.3-U5 system.

```Installing updates... done.
umount: unmount of /mnt/system/iocage/jails/radarr2/root/dev failed: Device busy
release: 11.4-RELEASE-p4 -> 11.4-RELEASE-p6
Updated jail successfully.
  + Removing jail process FAILED:
jail: ioc-radarr2: mount.fdescfs: /mnt/system/iocage/jails/radarr2/root/dev/fd: not a mount point```

**Comment by sveeke** [comment]
I experience the same phenomenon right now. I wanted to get in to jails on FreeBSD so I just started with them yesterday on a fresh server with FreeBSD 13.0. Followed the documentation and created my first jail (clone jail with vnet). The jail seems to work fine and all, except for when I stop the jail:

```
root@fbsd13-test:~ # iocage stop test
* Stopping testjail
  + Executing prestop OK
  + Stopping services OK
  + Tearing down VNET OK
  + Removing devfs_ruleset: 1000 OK
  + Removing jail process FAILED:
jail: ioc-testjail: mount.fdescfs: /zroot/iocage/jails/testjail/root/dev/fd: not a mount point
```
Any idea what I could have done wrong or how I can fix the cause of this error?

**Comment by Mannekino** [comment]
> 



> I experience the same phenomenon right now. I wanted to get in to jails on FreeBSD so I just started with them yesterday on a fresh server with FreeBSD 13.0. Followed the documentation and created my first jail (clone jail with vnet). The jail seems to work fine and all, except for when I stop the jail:
> 
> ```
> root@fbsd13-test:~ # iocage stop test
> * Stopping testjail
>   + Executing prestop OK
>   + Stopping services OK
>   + Tearing down VNET OK
>   + Removing devfs_ruleset: 1000 OK
>   + Removing jail process FAILED:
> jail: ioc-testjail: mount.fdescfs: /zroot/iocage/jails/testjail/root/dev/fd: not a mount point
> ```
> 
> Any idea what I could have done wrong or how I can fix the cause of this error?

The issue resolved itself for me. I just looked at my posting history on the TrueNAS community where I made this thread. Nobody else replied and I see that it solved itself for me after I updated to 12.x

https://www.truenas.com/community/threads/umount-error-after-updating-jail-to-latest-patch-level.90086/#post-624577
