### ISSUE TITLE
IOCAGE Upgrade on 2019-09-01 remove commands

### ISSUE THREAD

**Issue by shithead** [iocage/iocage#1053]
Make sure to follow and check these boxes before submitting an issue! Thank you.

- [x] Supply `iocage --version`
Version	1.2
- [x] Supply the commands used, along with any steps to recreate it.
iocage list
- [x] Provide the output from the command you issued.
Try "iocage --help" for help.

Error: No such command "list"
- [x] Supply what you expected the result or output to be
+-----+---------------+-------+--------------+---------------------------+
| JID |     NAME      | STATE |   RELEASE    |            IP4            |
+=====+===============+=======+==============+===========================+
- [x] Checked that the problem has not already been fixed on `master` if using
 a stable release.

**Comment by shithead** [comment]
Output for:

iocage --help
Usage: iocage [OPTIONS] COMMAND [ARGS]...

  A jail manager.

Options:
  -v, --version  Display iocage's version and exit.
  -f, --force    Allow iocage to rename datasets.
  -D, --debug    Log debug output to the console.
  --help         Show this message and exit.

Commands:
  migrate  Migrate all iocage_legacy develop basejails to new clonejails.

**Comment by davefullard** [comment]
Can confirm. Same issue. Just rolled back 1.1 from my pkg cache and it's working now (FreeBSD 12.0).
`pkg install /var/cache/pkg/py36-iocage-1.1.txz`

**Comment by jdakhayman** [comment]
Same issue here as well. iocage 1.2 as well

root@fletcher-4:/home/jda # iocage console webhost
Usage: iocage [OPTIONS] COMMAND [ARGS]...
Try "iocage --help" for help.

Error: No such command "console".
root@fletcher-4:/home/jda #

**Comment by davefullard** [comment]
The release in ports seems to be functioning.

**Comment by shithead** [comment]
problem solved
