### ISSUE TITLE
iocage pkg (buildname) install (pkgname) hangs

### ISSUE THREAD

**Issue by jhfoo** [iocage/iocage#1056]
Make sure to follow and check these boxes before submitting an issue! Thank you.
- [x] Supply `iocage --version`
v1.2

- [x] Supply the commands used, along with any steps to recreate it.
(root) iocage pkg (buildname) install zsh

- [x] Provide the output from the command you issued.
```
All repositories are up to date.
The following 1 package(s) will be affected (of 0 checked):

New packages to be INSTALLED:
 zsh: 5.7.1_1

Number of packages to be installed: 1

The process will require 18 MiB more space.
4 MiB to be downloaded.
```

- [x] Supply what you expected the result or output to be
Complete pkg install and end

- [x] Checked that the problem has not already been fixed on `master` if using
 a stable release.
Not sure how to check?

**Comment by BlueSpaceCanary** [comment]
Try hitting y and then enter, there's been a known issue of the actual y/n prompt from pkg not appearing in the terminal but still correctly accepting input

**Comment by jhfoo** [comment]
That works with manual intervention. Any idea how to do this in an automated fashion?

**Comment by BlueSpaceCanary** [comment]
I just use `sudo iocage pkg "$jail" upgrade -y` in my jail update script, which should work for the automated usecase

**Comment by jhfoo** [comment]
I should have thought of '-y'. Thanks for the tip! Tested: works as expected!
