### ISSUE TITLE
Jailed datasets don't mount automatically

### ISSUE THREAD

**Issue by freqlabs** [iocage/iocage#106]
I have set `jail_zfs=on` and `jail_zfs_dataset=$a_dataset_for_the_jail` on a few jails. As documented, this automatically sets `allow_mount_zfs=1` `allow_mount=1` and `enforce_statfs=1` for the jails as well. I have then set the mountpoint property for these datasets inside the jails. 

When these jails start, the datasets are not mounted. What I expected was that the datasets would be mounted when I start the jails.

I can manually mount the datasets by running `zfs mount -a` inside the jails.
I have tried setting `zfs_enable="YES"` in the jails' rc.conf as well, with no effect.

**Comment by freqlabs** [comment]
Looking into this a bit, I noticed that the dataset isn't jailed until after the services in the jail have started, which doesn't make sense to me. My services depend on data in the dataset in order to start. Moving lines 147-149 in lib/ioc-rc to just before the services are started (line 137) seems to have fixed the original issue (though I don't have a good explanation why). After making that one change, my jails now start properly and have their datasets mounted as expected.

**Comment by pannon** [comment]
@freqlabs please could you submit a PR against our `develop` branch with your changes so we can include your fix? Thanks!

**Comment by freqlabs** [comment]
Fixed by https://github.com/iocage/iocage/pull/107
