### ISSUE TITLE
'nvpair.h' file not found

### ISSUE THREAD

**Issue by jungle-boogie** [iocage/iocage#106]
Hello,

I can't seem to build iocage from git's master.

I have all this installed and working correctly, I assume:
```
pkg install python36
python3.6 -m ensurepip
git clone --recursive https://github.com/iocage/iocage
pip3.6 install Cython
```

Then:
```
[sean@fixme] ~/bin/iocage/py-libzfs% sudo python3.6 setup.py build
running build
running build_py
creating build/lib.freebsd-12.0-CURRENT-amd64-3.6
copying nvpair.html -> build/lib.freebsd-12.0-CURRENT-amd64-3.6
copying libzfs.html -> build/lib.freebsd-12.0-CURRENT-amd64-3.6
copying converter.html -> build/lib.freebsd-12.0-CURRENT-amd64-3.6
copying libzfs.c -> build/lib.freebsd-12.0-CURRENT-amd64-3.6
running build_ext
skipping 'libzfs.c' Cython extension (up-to-date)
building 'libzfs' extension
cc -Wno-unused-result -Wsign-compare -Wunreachable-code -DNDEBUG -O2 -pipe -fstack-protector -fno-strict-aliasing -fPIC -I/usr/src/cddl/lib/libumem -I/usr/src/sys/cddl/compat/opensolaris/ -I/usr/src/sys/cddl/compat/opensolaris -I/usr/src/cddl/compat/opensolaris/include -I/usr/src/cddl/compat/opensolaris/lib/libumem -I/usr/src/cddl/contrib/opensolaris/lib/libzpool/common -I/usr/src/sys/cddl/contrib/opensolaris/common/zfs -I/usr/src/sys/cddl/contrib/opensolaris/uts/common/fs/zfs -I/usr/src/sys/cddl/contrib/opensolaris/uts/common/sys -I/usr/src/cddl/contrib/opensolaris/head -I/usr/src/sys/cddl/contrib/opensolaris/uts/common -I/usr/src/cddl/contrib/opensolaris/lib/libnvpair -I/usr/src/cddl/contrib/opensolaris/lib/libuutil/common -I/usr/src/cddl/contrib/opensolaris/lib/libzfs/common -I/usr/src/cddl/contrib/opensolaris/lib/libzfs_core/common -I/usr/local/include/python3.6m -c libzfs.c -o build/temp.freebsd-12.0-CURRENT-amd64-3.6/libzfs.o -DNEED_SOLARIS_BOOLEAN -D_XPG6 -g -O0
libzfs.c:432:10: fatal error: 'nvpair.h' file not found
#include "nvpair.h"
         ^~~~~~~~~~
1 error generated.
error: command 'cc' failed with exit status 1
```

This a brand new host install of trueOS, so what's happening here?

**Comment by skarekrow** [comment]
Do you have a `/usr/src` populated?

**Comment by jungle-boogie** [comment]
> Do you have a /usr/src populated?

nope! Just checkout freebsd -head or which branch? Would I need to update /usr/src ever?

**Comment by skarekrow** [comment]
There's your problem :D

You will have to keep `/usr/src` updated yeah. You'll need to grab it off their GitHub and not the normal svn mirrors. I believe the master branch will do. I don't use trueos for my testing anymore, so those directions may be wrong. If you figure them out please send a PR so we can append to the readme.

**Comment by drewja** [comment]
How do I populate /usr/src?

**Comment by skarekrow** [comment]
On [FreeBSD](https://www.freebsd.org/doc/handbook/svn.html) and TrueOS you just fetch the appropriate repo from their [GitHub](https://github.com/trueos/freebsd)

**Comment by drewja** [comment]
I have a fresh install of FreeBSD, Please tell me exactly how to fetch the appropriate repo?

**Comment by skarekrow** [comment]
I did.

`svnlite co http://svn.freebsd.org/base/releng/RELEASE/ /usr/src`

Make sure you have your install at the latest patch level as well with `freebsd-update fetch && freebsd-update install`
