### ISSUE TITLE
Why doesn't devfs_ruleset of a running jail match the default value?

### ISSUE THREAD

**Issue by zachfi** [iocage/iocage#1061]
Make sure to follow and check these boxes before submitting an issue! Thank you.

- [x] Supply `iocage --version`
Version	1.2
- [x] Supply the commands used, along with any steps to recreate it.
iocage get all default | grep devfs_
iocage get all myjail | grep devfs_
- [x] Provide the output from the command you issued.
$ iocage get all default | grep devfs_
devfs_ruleset:4
$ iocage get all myjail | grep devfs_
devfs_ruleset:15
- [ ] Supply what you expected the result or output to be
My expectation is that since I didn't change the devfs_ruleset, that it would match the default value.

**Comment by dlangille** [comment]
see also #952

**Comment by sonicaj** [comment]
@xaque208 I see that as a feature, iocage telling which devfs_ruleset the jail is using currently. As iocage dynamically creates rulesets, this correctly depicts which devfs_ruleset it is using currently.
