### ISSUE TITLE
import command takess all memory and excessive amounts of swap

### ISSUE THREAD

**Issue by hxw** [iocage/iocage#1072]
Make sure to follow and check these boxes before submitting an issue! Thank you.

- [x] Supply `iocage --version`
1.2
- [x] Supply the commands used, along with any steps to recreate it.
iocage import name
- [x] Provide the output from the command you issued.
~~~
# iocage import builder
Importing dataset: builder
Importing dataset: builder/data
Importing dataset: builder/root

Imported: builder
iocage import builder  65.21s user 77.09s system 2% cpu 1:55:41.85 total
~~~

- [x] Supply what you expected the result or output to be
that is the expected output, but almost 2 hours to import is very slow

- [x] Checked that the problem has not already been fixed on `master` if using
 a stable release.
looks like iocage_lib/ioc_image.py only has minor directory change which would not affect the problem.

When running iocage import the python process consumes all free memory and lots of swap.  As an example:
Size of Jail from zfs list: used=7.58G
the image sizes
~~~
-rw-------  1 root  wheel           64 2019-10-21 builder_2019-10-21.sha256
-rw-------  1 root  wheel   4084386806 2019-10-21 builder_2019-10-21.zip
~~~
monitoring the python process during the import I saw:
prior to start = 27GB free RAM (of 32GB)
during the run:
freeRAM = 500M
swap used = 30G
python size = 54G  and RES varied periodically from 0 to 14..16GB

I think the 2 hours to extract is simply the swapping.

A larger 16GB jail went even higher but as it took almost 10 hours to extract I am not sure of the exact values, but the 50GB of free swap was enough.

Is it possible that the import loop is keeping multiple copies of both compressed an uncompressed zip in memory?

Edit to add:
I just used zfs send/receive over ssh to transfer an 8GB jail over GB Ethernet, it took 10 minutes

**Comment by Oxyaxion** [comment]
I confirm I have the same problem.

I 'm trying to import a jail previously created in the same host and ... that just impossible 

the Iocage python process consume all my memory and swap and result kernel killing python process and loging :  "swap_page_getswapspace(32): failed"

Size of the jail 1.3G , host 4G RAM, FreeBSD 12.1

I can't restore my jail export ! That's very bad !

Edit : I have try with adding until 18G of SWAP but same problem ... impossible to import a jail archive ...

**Comment by s1dh** [comment]
I confirm I have the same problem.
I added 12G swap space , jail is 5.24GB
 impossible to import a jail archive

**Comment by igalic** [comment]
https://github.com/iocage/iocage/pull/1218 ⬅️ i think this may have addressed or even fixed the issue
