### ISSUE TITLE
default values for sysvmsg, sysvshm, and sysvsem properties: new or disabled?

### ISSUE THREAD

**Issue by dlangille** [iocage/iocage#1073]
The documentation does not agree with the code when it comes to `sysvmsg`, `sysvshm`, and `sysvsem` properties

```
$ iocage --version
Version	1.2
```

The documentation, from man iocage

```
Default: disable
```

To reproduce, create a new jail:

```
$ sudo iocage create -r 12.0-RELEASE --thickjail --name deleteme
deleteme successfully created!
```

Then examine the properties

```
$ iocage get all deleteme | grep sysv
allow_sysvipc:0
sysvmsg:new
sysvsem:new
sysvshm:new
```

The code seems to confirm this is intentional (from https://github.com/iocage/iocage/blob/1.2-RELEASE/iocage_lib/ioc_json.py#L980):

```
        # Version 2 keys
        if not conf.get('sysvmsg'):
            conf['sysvmsg'] = 'new'
        if not conf.get('sysvsem'):
            conf['sysvsem'] = 'new'
        if not conf.get('sysvshm'):
            conf['sysvshm'] = 'new'
```

**Comment by asomers** [comment]
Looks like a man page bug introduced when the man page was first added, in rev 3551150e72bfcf6dbab6c53ba9f166b9667a1bd1
