### ISSUE TITLE
Escape sequences in console output break my automated workflow

### ISSUE THREAD

**Issue by joachimmathes** [iocage/iocage#108]
Since I use the iocage output for further automated tasks, I need a clean output without escape sequences. Is there a way to turn them off?

**Comment by skarekrow** [comment]
Can you post examples?

**Comment by joachimmathes** [comment]
I use iocage in an ansible context. There is an ansible task where I loop over jail tags and run `iocage get host_hostuuid <tag>` on each of them. The problem is, that the results are no longer the shortened eight character uuids like `ab12cd34ef` but something like `\033[1;40;97mab12cd34ef\033[1;m`. 
IMHO command line tools on unix systems should always output plain text by default, since piping character sequences from CLI tool to CLI tool is such a fundamental part of these operating systems. Color is a nice additional feature and increases readability for humans. But it should be activated explicitly.

**Comment by skarekrow** [comment]
I totally agree. I'll think of something. The logging is a WIP since we just got colors going. Lots left to do.

**Comment by joachimmathes** [comment]
Thank you! I might as well have a look at it tomorrow (since its almost midnight here in Germany :)) if you like.

**Comment by skarekrow** [comment]
Totally feel free! It's a gnarley bit I warn you. But more eyes is a good thing on this.

**Comment by skarekrow** [comment]
Bah it still closed even though I used different wording. Ok @joachimmathes I did the least invasive thing I could think of, if that doesn't fix, feel free to rip it out and take a stab at it. Or report back if it does and I'll really close this.


EDIT:

Before
```
╰─ less test.out
ESC[1;31m
  tag: "test" in use by 28b0b6e1-e7d1-44ca-9a45-9b140f45f38b!
  Renaming a09f37fd-2765-460b-b716-64f4cf51a40e's tag to 2017-04-19@04:48:27:106050.
ESC[1;m
ESC[1;40;97ma09f37fd-2765-460b-b716-64f4cf51a40e (2017-04-19@04:48:27:106050) successfully created!ESC[1;m
```
After
```
╰─ less test.out

  tag: "test" in use by 28b0b6e1-e7d1-44ca-9a45-9b140f45f38b!
  Renaming b4b45720-5eab-4392-9239-546f74ec2374's tag to 2017-04-19@04:48:45:882588.

b4b45720-5eab-4392-9239-546f74ec2374 (2017-04-19@04:48:45:882588) successfully created!
```

**Comment by joachimmathes** [comment]
Great solution. Thank you!

One more question: My ansible tasks rely on `stdout` output. But, the `StreamHandler` uses `sys.stderr` by default. Are you going to keep this, or are there plans to set `logging.StreamHandler(sys.stdout)`?

**Comment by skarekrow** [comment]
I'm not sure to be honest. I would like them to be separate (out for info err for rest) but just haven't had time to delve into that.

**Comment by joachimmathes** [comment]
No problem, in either case I can adjust my tasks quite easily. Thanks again.

**Comment by skarekrow** [comment]
Hey @joachimmathes I pushed a change that I think also solves that issue, lemme know 👍

**Comment by joachimmathes** [comment]
Works like a charm! :+1: Thanks @skarekrow.

**Comment by skarekrow** [comment]
Woohoo! No problem :)
