### ISSUE TITLE
update starts stopped jails

### ISSUE THREAD

**Issue by dlangille** [iocage/iocage#1080]
```
$ iocage --version
Version	1.2

```

Why does an `iocage update` start a stopped jail?

Case in point:

```
[dan@r710-01:~/bin] $ sudo iocage update pkg02
Snapshot: tank_fast/iocage/jails/pkg02@ioc_update_12.0-RELEASE-p10_2019-10-25_19-37-57 created.
cannot mount 'tank_fast/poudriere': mountpoint or dataset is busy
[dan@r710-01:~/bin] $ 
```

`pkg02` is stopped by design. Why must it be started in order to update?

**Comment by skarekrow** [comment]
We need to have something to chroot into for the update process. Memory tells me we need a live devfs among other things, so that requires starting the jail.

**Comment by dlangille** [comment]
I believe this breaks POLA.

If I, the admin, stops a jail, I don't expect iocage to start it unless I say start.  Failing that, just tell me  : oi, I can't update this jail without starting it.  Starting a jail could have potentially serious repercussions.

**Comment by skarekrow** [comment]
I think a documentation blurb should be appropriate then? I don’t disagree with you at all.

**Comment by dlangille** [comment]
I think, ideally, the code would prompt for confirmation before upgrading a stopped jail.
