### ISSUE TITLE
unused jail_zfs_dataset unexpectedly mounted after clone

### ISSUE THREAD

**Issue by kcwu** [iocage/iocage#110]
How to reproduce:
```
# iocage create tag=test1 release=10.1-RELEASE
# iocage clone test1 tag=test2
# df /$(iocage get jail_zfs_dataset test2)
```
test2's /root/data is mounted.

**Comment by pannon** [comment]
@kcwu please can you check whether `jail_zfs` is set to `on` for clone test2?

**Comment by kcwu** [comment]
no, jail_zfs is off for both
```
# iocage get jail_zfs test1
off
# iocage get jail_zfs test2
off
```

zfs clone won't inherit mountpoint=none .
Maybe you have to 
```
zfs clone -o mountpoint=none $fs@$uuid $cfs
```

**Comment by pannon** [comment]
@kcwu please test with latest version from `develop`.

**Comment by pannon** [comment]
This is fixed now.
