### ISSUE TITLE
Some commands fail for ALL

### ISSUE THREAD

**Issue by freqlabs** [iocage/iocage#111]
Many commands do not work with the special UUID `ALL`, for example `iocage start ALL` `iocage stop ALL` `iocage export ALL` and surely others (I haven't checked them all yet). Here's a sample output of one such command:

```
# iocage stop ALL
[: system/iocage/jails/2c9a5625-0ce9-11e5-b42b-0025907cc3f4: unexpected operator
[: system/iocage/jails/2c9a5625-0ce9-11e5-b42b-0025907cc3f4: unexpected operator
[: system/iocage/jails/2c9a5625-0ce9-11e5-b42b-0025907cc3f4: unexpected operator
[: system/iocage/jails/2c9a5625-0ce9-11e5-b42b-0025907cc3f4: unexpected operator
* 2c9a5625-0ce9-11e5-b42b-0025907cc3f4
879b0704-0d70-11e5-b42b-0025907cc3f4
9e553f4d-0d55-11e5-b42b-0025907cc3f4
9ea25ab3-0db2-11e5-b42b-0025907cc3f4
a092e40b-0cbc-11e5-b42b-0025907cc3f4: is already down
```

There seems to be a pattern followed by the functions behind these commands that fails to recognize the possibility of `ALL` being passed as the jail identifier.

```
...
    local dataset="$(__find_jail $name)"

    if [ -z $dataset ] ; then
        echo "  ERROR: $name not found"
        exit 1
    fi

    if [ $dataset == "multiple" ] ; then
        echo "  ERROR: multiple matching UUIDs!"
        exit 1
    fi
...
```

`__find_jail ALL` will return a newline delimited list of all the jails, causing these functions to fail as shown above.

One possible solution might be to check for `ALL` at the start of these functions, and if the passed name is `ALL`, have the function call itself in a loop; otherwise, proceed normally.

**Comment by pannon** [comment]
@freqlabs ALL only makes sense for a limited number of sub-commands. For starting/stopping ALL for example use the rc* commands.

**Comment by freqlabs** [comment]
The rc* commands only affect jails with boot=on.

**Comment by hxw** [comment]
There is a similar effect when running `service iocage stop`
I just tried:
~~~
# iocage version
iocage 1.6.2 (2015/05/01)
~~~
~~~
# service iocage stop
* [I|O|C] shutting down jails... 
* Stopping b7b5d0dc-02af-11e5-9138-001bfc7e1e0f (jailhost1)
  + Running pre-stop         OK
  + Stopping services        OK
  + Removing jail process    OK
  + Running post-stop        OK
cannot open 'zroot/iocage/jails/4f7b8883-02af-11e5-9138-001bfc7e1e0f
zroot/iocage/jails/9d17f5e2-02af-11e5-9138-001bfc7e1e0f
zroot/iocage/jails/a5dd0e43-02af-11e5-9138-001bfc7e1e0f
zroot/iocage/jails/aed313c8-02af-11e5-9138-001bfc7e1e0f
zroot/iocage/jails/b7b5d0dc-02af-11e5-9138-001bfc7e1e0f
zroot/iocage/jails/c0e6093a-02af-11e5-9138-001bfc7e1e0f
zroot/iocage/jails/ca10acbe-02af-11e5-9138-001bfc7e1e0f
zroot/iocage/jails/f648244a-0389-11e5-9138-001bfc7e1e0f': invalid dataset name
[: ==: unexpected operator
~~~
It looks like the "newline separated list of jails" is being treated as a single argument .

**Comment by pannon** [comment]
@hxw please try with latest develop version and if it is still an issue open a separate issue as this is unrelated to the original topic on this thread.
