### ISSUE TITLE
iocage ansible module

### ISSUE THREAD

**Issue by Corvan** [iocage/iocage#1118]
Hello there,
This is not a bug report! I wanted to draw your attention to an ansible module I wrote to make iocage calls idempotent in our proServer-project. Addionally I kindly wanted to ask if you were willing to review this module, so that when I open a Pull Request towards the ansible project I would be able to say it has been reviewed by the iocage developers. I also asked Benedict Reuschling of the FreeBSD-Project at EuroBSDCon2019 if he were willing to, and replied he was, so if you choose to review, he will get a call as well afterwards. My hope is, that the module might be included quicker and with more affection, if I can state that key-project-people made a review and approved. So it would be very appreciated, if you could do it.

In this first step I am using the iocage cli with pythons subprocess. While this might not be the most elegant way, it was the easiest one to get started. In possible follow ups I might take the time to find the right entry points to add an implementation, which uses iocage's calls directly.

For reviewing the code, you can find a Pull Request opened https://github.com/Corvan/ansible/pull/2, where you can comment on things you notice or additional ideas you might have.

Additionally I created a testing repo, which helps you to set up a vagrant box and use ansible to try working with the module https://github.com/Corvan/ansible-iocage-test. This is how I tested, if the module is working and this will be the suggestion to the ansible project, bc they don't have automated testing of FreeBSD-Modules (at least I was not able to find any).

My colleague @fnkr at punkt.de already made a review and you can find that under https://github.com/Corvan/ansible/pull/1 

Thank you
Happy holidays with whatever you are celebrating, if you are celebrating at all.
Lars

**Comment by kpfleming** [comment]
This also exists, and might be worth comparison:

https://github.com/fractalcells/ansible-iocage

Finally, there is an `iocage` module in Ansible already, although its capabiiities are quite limited.

**Comment by Corvan** [comment]
As far as I could see the already existing module is only able to run commands inside iocage jails.
I'll have a look at your link, thank you.
