### ISSUE TITLE
Unable to import: cannot receive new filesystem stream: checksum mismatch or incomplete stream

### ISSUE THREAD

**Issue by jhfoo** [iocage/iocage#1124]
Make sure to follow and check these boxes before submitting an issue! Thank you.

- [X] Supply `iocage --version`
1.2_3

- [X] Supply the commands used, along with any steps to recreate it.
sudo iocage import <export file without .zip>

- [X] Provide the output from the command you issued.
Importing dataset: testjail
Importing dataset: testjail/root
zsh: killed     sudo iocage import testjail
%cannot receive new filesystem stream: checksum mismatch or incomplete stream

- [X] Supply what you expected the result or output to be
Some success message

- [X] Checked that the problem has not already been fixed on `master` if using
 a stable release.

**Comment by jhfoo** [comment]
More info: tested on thin and thick jails.

**Comment by jhfoo** [comment]
Any suggestions to try? If this is not an iocage problem please point me in the right direction, thanks!

**Comment by jhfoo** [comment]
Looks similar to https://github.com/iocage/iocage/issues/1086

**Comment by 2otherjobs** [comment]
@jhfoo 
see 1086
2otherjobs

**Comment by jhfoo** [comment]
Published workaround here: http://ihazcodez.kungfoo.info/2020/TipsNTricks1.html
