### ISSUE TITLE
Time to move to Python 3.7?

### ISSUE THREAD

**Issue by jsegaert** [iocage/iocage#1125]
It looks like FreeBSD now has Python version 3.7 as the default; the references to 3.6 will become an issue.

```
➜  iocage git:(master) sudo make install
pkg install -q -y py36-libzfs
pkg: No packages available to install matching 'py36-libzfs' have been found in the repositories
*** Error code 70

Stop.
```

**Comment by sonicaj** [comment]
@jsegaert you are correct. It is time to move to next python version :p Are you willing to do the honours ;) ? Else I can bump it :)

**Comment by jsegaert** [comment]
OK, will do!
