### ISSUE TITLE
'iocage update' should be able to run non-interactively

### ISSUE THREAD

**Issue by MarkMartinec** [iocage/iocage#113]
Using py3-iocage from ports, "Version 0.9.7 2017/03/08".

The `iocage update` command calls `freebsd-update fetch` internally, which in turn insists that such operation should only be done from an interactive session (checks for a tty). This is unfortunate, as it precludes the use of a `iocage update` command from automation tools (like SaltStack in my case, probably applies to Puppet, Chef and Ansible too).

Here is a result of such attempt from SaltStack:

```
Comment: Command "/usr/local/bin/iocage update xxx" run
...
  stdout:
                  
    * Updating 3ab4e355 (xxx) to the latest patch level... 
    src component not installed, skipped
    freebsd-update fetch should not be run non-interactively.
    Run freebsd-update cron instead.
    src component not installed, skipped
    No updates are available to install.
    Run '/usr/sbin/freebsd-update fetch' first.
```

The `freebsd-update` man page specifies option `--not-running-from-cron` that can be used to bypass such restriction:
```
  --not-running-from-cron
    Force freebsd-update fetch to proceed when there is no
    controlling tty.  This is for use by automated scripts and
    orchestration tools.  Please do not run freebsd-update
    fetch from crontab or similar using this flag, see:
    freebsd-update cron
```

I believe `iocage` should specify the `--not-running-from-cron` option to `freebsd-update` unconditionally, or at least provide a command line option for this purpose.

**Comment by skarekrow** [comment]
I actually do this for `upgrade`, not sure why it skipped my mind for `update`. Will fix.

**Comment by skarekrow** [comment]
And somewhere along the line must have removed it. D'oh. All fixed now, test and report back 👍
