### ISSUE TITLE
Feature request: provide flavours

### ISSUE THREAD

**Issue by omani** [iocage/iocage#113]
hi,

it would be very handy to have a flavour feature in iocage. I guess you know what I mean by flavour (see ezjails as reference).

can we implement this?

**Comment by omani** [comment]
the pkglist option is useful but a flavour would give much more options to configure a jail.

**Comment by skarekrow** [comment]
Do jail templates not fit your use case?

**Comment by omani** [comment]
a template is fine but it lacks the ability to have a dynamic setup at creation time. think of this flavour feature as a Dockerfile (docker) where I can put RUN commands and basically can spawn several machines with one or more flavours.

**Comment by pannon** [comment]
@omani as @skarekrow meantioned already we have templates and you could use the exec_prestart/exec_poststart properties to execute whatever you want.

**Comment by omani** [comment]
thanks I will check that out.

**Comment by skarekrow** [comment]
Closing. Feel free to respond if there's anything to add.
