### ISSUE TITLE
devfs_ruleset 6 does not exist! - Not starting jail

### ISSUE THREAD

**Issue by cjemorton** [iocage/iocage#1140]
Make sure to follow and check these boxes before submitting an issue! Thank you.

- [x] Supply `iocage --version`
`Version 1.2`
- [x] Supply the commands used, along with any steps to recreate it.
`iocage start sonarr`
- [x] Provide the output from the command you issued.
`* Starting sonarr
sonarr devfs_ruleset 6 does not exist! - Not starting jail`
- [x] Supply what you expected the result or output to be
`I expected the jail to start like normally.`

- [x] Checked that the problem has not already been fixed on `master` if using
 a stable release.

Any idea what's going on, I am a bit lost on this. Its not just the jail listed in the example that fails to start with the error "devfs_ruleset 6 does not exist! - Not starting jail" but others as well. Meanwhile some other jails seem to work fine.

**Comment by sonicaj** [comment]
@clem16 would you recall changing `devfs_ruleset` value for any of the jails which fail to start ?
If not, can you please email me a debug at `waqar at the rate of ixsystems.com` ? Debug will be generated via `iocage debug` command.

**Comment by cjemorton** [comment]
I don't recall changing anything devfs_ruleset

Where does `iocage debug` save the output. EDIT: Found it. Sending you a debug txt

**Comment by sonicaj** [comment]
@clem16 unfortunately that's not enough and can you please send it for all the files you find under the debug directory please ? ( maybe compress them and email ? )
While doing that, please also provide `/var/log/iocage.log` as well.

Would you recall doing something with the affected jails like update/upgrade or something else ? Please do mention if something comes to your mind wrt that. I am unable to reproduce this locally so far.

**Comment by cjemorton** [comment]
I did reinstall freebsd awhile ago on the boot SSD.
The jails that were working on the previous system just kept working after
tho.
I've been using the jails from the previous system for almost two months
without a problem.

That's the only thing I can think of that might have caused changed.

Recently I did reboot the host system, and since then I am getting that
error on several jails.

I'm at a loss trying to track down what's causing it.

**Comment by grembo** [comment]
> I did reinstall freebsd awhile ago on the boot SSD. The jails that were working on the previous system just kept working after tho. I've been using the jails from the previous system for almost two months without a problem. That's the only thing I can think of that might have caused changed. Recently I did reboot the host system, and since then I am getting that error on several jails. I'm at a loss trying to track down what's causing it.
> […](#)

Recently a bug was fixed that would make iocage ignore a missing ruleset and silently start with default rules anyway. So if you copied your configuration from a different system that had that ruleset 6 (potentially a long time ago) and now use a newer version of iocage, such a behavior is expected. So if you happy with the default ruleset, simply configure it explicitly (setting it to 4) or remove the config from config.json in those jails.

**Comment by cjemorton** [comment]
Bam!

Removed the line: `devfs_ruleset": "6",` from `config.json` and the jails start up fine. 

Thanks.
