### ISSUE TITLE
[feature] Backup command

### ISSUE THREAD

**Issue by xylle** [iocage/iocage#1141]
Hello,
I am replacing my LXC server with a jail server, there is just one command missing to save them without interruption of service.
Is it possible to add a command to do?
With a different export destination, for example a backup folder.

The export command is very useful for a migration, but less for a daily backup.

Thanks

**Comment by sporkman** [comment]
It would also be nice if we could opt to send it to STDOUT, which would then allow piping to ssh. Imagine backing up a large jail that might not even fit on the existing system, as one example or just wanting to backup and transfer in one step... Optionally disabling the zip would also be very nice.
