### ISSUE TITLE
Option around fetching RELEASE

### ISSUE THREAD

**Issue by rracb** [iocage/iocage#115]
During testing on a VM I find that I'm deleting my VM clone and starting over multiple times, requiring the re-fetching of the desired RELEASE and wasting a lot of bandwidth and server time.  Might there be an option to point to an existing temp directory say, into which the 4 .txz files needed can be found and decompressed/installed from there?  The rest of the installation could continue from there.

In ezjail it is done like so:

|# ezjail-admin install -sp -h file:///temp/

where the .txz files would have been placed in dir 'temp'.

Thanks!

**Comment by pannon** [comment]
@rracb you can point iocage to fetch from a custom server with: `iocage fetch [release=RELEASE | ftphost=ftp.hostname.org | ftpdir=/dir/]`

**Comment by rracb** [comment]
Excellent - thank you.  I was sure you had an as yet undocumented method already figured out.

If I can sneak another question in, which I'm having trouble with...

My host system has bash installed as the default shell.  When I do "iocage chroot UUID" I get a return of "chroot: /usr/local/bin/bash: No such file or directory" which I think is because there is not bash running in the root of the UUID jail I want to enter.  Is there a workaround for this?  The web is silent about it in re: iocage.

**Comment by pannon** [comment]
Example `iocage chroot www01 tcsh`

These are all documented, are you using the latest develop branch?

**Comment by rracb** [comment]
I read the entire manpage before I asked the questions today and the documentation yesterday.  Isn't version 1.6.2 current?  I think the documentation is quite good but also noticed that you said time is a bit of an issue for you presently, so presumed you may not have documented everything.

I'll look for the latest develop branch material...

Thank you.
