### ISSUE TITLE
Template jail got into corrupt state after updating FreeNAS to 11.3

### ISSUE THREAD

**Issue by lumaxis** [iocage/iocage#1150]
I'm running a FreeNAS installation that I recently upgraded to 11.3 (`FreeBSD 11.3-RELEASE-p6` specifically). Somewhere in the process, my template jail that I can't recall ever manually messing with got into a "Corrupted" state.

Now, when trying to `iocage fetch` the latest base release, I get this error:

<details>
  <summary>Full output of <code>icage fetch</code></summary>
  
FreeNAS# iocage fetch
[0] 11.2-RELEASE (EOL)
[1] 11.3-RELEASE
[2] 12.0-RELEASE (EOL)
[3] 12.1-RELEASE

Type the number of the desired RELEASE
Press [Enter] to fetch the default selection: (11.3-RELEASE)
Type EXIT to quit:
Fetching: 11.3-RELEASE

Downloading: MANIFEST [####################] 100%
Downloading: base.txz [####################] 100%
Downloading: lib32.txz [####################] 100%
Downloading: src.txz [####################] 100%
Extracting: base.txz...
Extracting: lib32.txz...
Extracting: src.txz...

* Updating 11.3-RELEASE to the latest patch level...
Looking up update.FreeBSD.org mirrors... 3 mirrors found.
Fetching public key from update1.freebsd.org... done.
Fetching metadata signature for 11.3-RELEASE from update1.freebsd.org... done.
Fetching metadata index... done.
Fetching 2 metadata files... done.
Inspecting system... done.
Preparing to download files... done.
Fetching 115 patches.....10....20....30....40....50....60....70....80....90....100....110.. done.
Applying patches... done.
The following files will be updated as part of updating to
11.3-RELEASE-p6:
/bin/freebsd-version
/boot/loader
/boot/loader.efi
/boot/loader_4th
/boot/loader_4th.efi
/boot/loader_lua
/boot/loader_lua.efi
/boot/loader_simp
/boot/loader_simp.efi
/boot/pxeboot
/boot/userboot.so
/boot/userboot_4th.so
/boot/userboot_lua.so
/boot/zfsloader
/lib/libc.so.7
/rescue/[
/rescue/atmconfig
/rescue/badsect
/rescue/bectl
/rescue/bsdlabel
/rescue/bunzip2
/rescue/bzcat
/rescue/bzip2
/rescue/camcontrol
/rescue/cat
/rescue/ccdconfig
/rescue/chflags
/rescue/chgrp
/rescue/chio
/rescue/chmod
/rescue/chown
/rescue/chroot
/rescue/clri
/rescue/cp
/rescue/csh
/rescue/date
/rescue/dd
/rescue/devfs
/rescue/df
/rescue/dhclient
/rescue/disklabel
/rescue/dmesg
/rescue/dump
/rescue/dumpfs
/rescue/dumpon
/rescue/echo
/rescue/ed
/rescue/ex
/rescue/expr
/rescue/fastboot
/rescue/fasthalt
/rescue/fdisk
/rescue/fsck
/rescue/fsck_4.2bsd
/rescue/fsck_ffs
/rescue/fsck_msdosfs
/rescue/fsck_ufs
/rescue/fsdb
/rescue/fsirand
/rescue/gbde
/rescue/geom
/rescue/getfacl
/rescue/glabel
/rescue/gpart
/rescue/groups
/rescue/gunzip
/rescue/gzcat
/rescue/gzip
/rescue/halt
/rescue/head
/rescue/hostname
/rescue/id
/rescue/ifconfig
/rescue/init
/rescue/ipf
/rescue/iscsictl
/rescue/iscsid
/rescue/kenv
/rescue/kill
/rescue/kldconfig
/rescue/kldload
/rescue/kldstat
/rescue/kldunload
/rescue/ldconfig
/rescue/less
/rescue/link
/rescue/ln
/rescue/ls
/rescue/lzcat
/rescue/lzma
/rescue/md5
/rescue/mdconfig
/rescue/mdmfs
/rescue/mkdir
/rescue/mknod
/rescue/more
/rescue/mount
/rescue/mount_cd9660
/rescue/mount_msdosfs
/rescue/mount_nfs
/rescue/mount_nullfs
/rescue/mount_udf
/rescue/mount_unionfs
/rescue/mt
/rescue/mv
/rescue/nc
/rescue/newfs
/rescue/newfs_msdos
/rescue/nos-tun
/rescue/pgrep
/rescue/ping
/rescue/ping6
/rescue/pkill
/rescue/poweroff
/rescue/ps
/rescue/pwd
/rescue/rcorder
/rescue/rcp
/rescue/rdump
/rescue/realpath
/rescue/reboot
/rescue/red
/rescue/rescue
/rescue/restore
/rescue/rm
/rescue/rmdir
/rescue/route
/rescue/routed
/rescue/rrestore
/rescue/rtquery
/rescue/rtsol
/rescue/savecore
/rescue/sed
/rescue/setfacl
/rescue/sh
/rescue/shutdown
/rescue/sleep
/rescue/spppcontrol
/rescue/stty
/rescue/swapon
/rescue/sync
/rescue/sysctl
/rescue/tail
/rescue/tar
/rescue/tcsh
/rescue/tee
/rescue/test
/rescue/tunefs
/rescue/umount
/rescue/unlink
/rescue/unlzma
/rescue/unxz
/rescue/vi
/rescue/whoami
/rescue/xz
/rescue/xzcat
/rescue/zcat
/rescue/zdb
/rescue/zfs
/rescue/zpool
/sbin/ipfw
/usr/bin/bunzip2
/usr/bin/bzcat
/usr/bin/bzip2
/usr/bin/bzip2recover
/usr/bin/fetch
/usr/bin/telnet
/usr/include/bzlib.h
/usr/include/machine/pmap.h
/usr/include/x86/specialreg.h
/usr/lib/libbsnmp.a
/usr/lib/libbsnmp.so.6
/usr/lib/libbsnmp_p.a
/usr/lib/libbz2.a
/usr/lib/libbz2.so.4
/usr/lib/libbz2_p.a
/usr/lib/libc.a
/usr/lib/libc_p.a
/usr/lib/libc_pic.a
/usr/lib/libfetch.a
/usr/lib/libfetch.so.6
/usr/lib/libfetch_p.a
/usr/lib32/libbsnmp.a
/usr/lib32/libbsnmp.so.6
/usr/lib32/libbsnmp_p.a
/usr/lib32/libbz2.a
/usr/lib32/libbz2.so.4
/usr/lib32/libbz2_p.a
/usr/lib32/libc.a
/usr/lib32/libc.so.7
/usr/lib32/libc_p.a
/usr/lib32/libc_pic.a
/usr/lib32/libfetch.a
/usr/lib32/libfetch.so.6
/usr/lib32/libfetch_p.a
/usr/sbin/bhyve
/usr/sbin/pkg
/usr/share/man/man1/bunzip2.1.gz
/usr/share/man/man1/bzcat.1.gz
/usr/share/man/man1/bzip2.1.gz
/usr/share/man/mandoc.db
/usr/share/zoneinfo/America/Detroit
/usr/share/zoneinfo/America/Edmonton
/usr/share/zoneinfo/America/Indiana/Tell_City
/usr/share/zoneinfo/America/Kentucky/Louisville
/usr/share/zoneinfo/America/Vancouver
/usr/share/zoneinfo/Asia/Hong_Kong
/usr/share/zoneinfo/Asia/Istanbul
/usr/share/zoneinfo/Asia/Seoul
/usr/share/zoneinfo/Europe/Brussels
/usr/share/zoneinfo/Europe/Istanbul
/usr/share/zoneinfo/Europe/Kaliningrad
/usr/share/zoneinfo/Europe/Vienna
/usr/share/zoneinfo/Pacific/Fiji
/usr/share/zoneinfo/Pacific/Norfolk
/usr/src/contrib/bsnmp/lib/asn1.c
/usr/src/contrib/bzip2/CHANGES
/usr/src/contrib/bzip2/LICENSE
/usr/src/contrib/bzip2/README
/usr/src/contrib/bzip2/README.COMPILATION.PROBLEMS
/usr/src/contrib/bzip2/blocksort.c
/usr/src/contrib/bzip2/bzip2.1
/usr/src/contrib/bzip2/bzip2.c
/usr/src/contrib/bzip2/bzip2recover.c
/usr/src/contrib/bzip2/bzlib.c
/usr/src/contrib/bzip2/bzlib.h
/usr/src/contrib/bzip2/bzlib_private.h
/usr/src/contrib/bzip2/compress.c
/usr/src/contrib/bzip2/crctable.c
/usr/src/contrib/bzip2/decompress.c
/usr/src/contrib/bzip2/huffman.c
/usr/src/contrib/bzip2/randtable.c
/usr/src/contrib/bzip2/spewG.c
/usr/src/contrib/bzip2/unzcrash.c
/usr/src/contrib/bzip2/words2
/usr/src/contrib/telnet/telnet/commands.c
/usr/src/contrib/telnet/telnet/telnet.c
/usr/src/contrib/telnet/telnet/utilities.c
/usr/src/contrib/tzdata/NEWS
/usr/src/contrib/tzdata/asia
/usr/src/contrib/tzdata/australasia
/usr/src/contrib/tzdata/backzone
/usr/src/contrib/tzdata/europe
/usr/src/contrib/tzdata/leap-seconds.list
/usr/src/contrib/tzdata/leapseconds
/usr/src/contrib/tzdata/leapseconds.awk
/usr/src/contrib/tzdata/northamerica
/usr/src/contrib/tzdata/southamerica
/usr/src/contrib/tzdata/theory.html
/usr/src/contrib/tzdata/version
/usr/src/lib/libc/secure/stack_protector.c
/usr/src/lib/libfetch/fetch.c
/usr/src/sbin/ipfw/ipfw2.c
/usr/src/sys/amd64/amd64/pmap.c
/usr/src/sys/amd64/include/pmap.h
/usr/src/sys/amd64/vmm/vmm_instruction_emul.c
/usr/src/sys/compat/freebsd32/freebsd32_ioctl.c
/usr/src/sys/conf/newvers.sh
/usr/src/sys/dev/cpuctl/cpuctl.c
/usr/src/sys/dev/sound/midi/midi.c
/usr/src/sys/kern/imgact_elf.c
/usr/src/sys/kern/tty.c
/usr/src/sys/kern/uipc_mbuf2.c
/usr/src/sys/kern/uipc_mqueue.c
/usr/src/sys/kern/uipc_usrreq.c
/usr/src/sys/kern/vfs_mount.c
/usr/src/sys/netinet6/mld6.c
/usr/src/sys/x86/include/specialreg.h
/usr/src/sys/x86/x86/cpu_machdep.c
/usr/src/usr.sbin/bhyve/pci_e82545.c
/usr/src/usr.sbin/bhyve/pci_xhci.c
Installing updates... done.
Traceback (most recent call last):
  File "/usr/local/bin/iocage", line 10, in <module>
    sys.exit(cli())
  File "/usr/local/lib/python3.7/site-packages/click/core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/click/core.py", line 717, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.7/site-packages/click/core.py", line 1137, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.7/site-packages/click/core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.7/site-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/iocage_cli/fetch.py", line 181, in cli
    ioc.IOCage().fetch(**kwargs)
  File "/usr/local/lib/python3.7/site-packages/iocage_lib/iocage.py", line 1078, in fetch
    **kwargs).fetch_release()
  File "/usr/local/lib/python3.7/site-packages/iocage_lib/ioc_fetch.py", line 215, in fetch_release
    rel = self.fetch_http_release(eol, _list=_list)
  File "/usr/local/lib/python3.7/site-packages/iocage_lib/ioc_fetch.py", line 476, in fetch_http_release
    self.fetch_update()
  File "/usr/local/lib/python3.7/site-packages/iocage_lib/ioc_fetch.py", line 960, in fetch_update
    props = _json.json_get_value('all')
  File "/usr/local/lib/python3.7/site-packages/iocage_lib/ioc_json.py", line 1680, in json_get_value
    return self.get_full_config()
  File "/usr/local/lib/python3.7/site-packages/iocage_lib/ioc_json.py", line 1329, in get_full_config
    conf, write = self.json_load()
  File "/usr/local/lib/python3.7/site-packages/iocage_lib/ioc_json.py", line 1660, in json_load
    os.path.join(self.location, 'config.json'),
  File "/usr/local/lib/python3.7/site-packages/iocage_lib/ioc_json.py", line 876, in backup_iocage_jail_conf
    location.rsplit('/', 1)[0], f'{dest}_backup.json'
  File "/usr/local/lib/python3.7/shutil.py", line 248, in copy
    copyfile(src, dst, follow_symlinks=follow_symlinks)
  File "/usr/local/lib/python3.7/shutil.py", line 121, in copyfile
    with open(dst, 'wb') as fdst:
OSError: [Errno 30] Read-only file system: '/mnt/data/iocage/templates/custom/config_backup.json'
</details>

So most notably, I've been running into the above `OSError` multiple times, too, when trying to execute other commands and I believe it is also the reason why my jails are not correctly auto-starting after a reboot anymore:
```shell
OSError: [Errno 30] Read-only file system: '/mnt/data/iocage/templates/custom/config_backup.json'
```

Looking at the output of `mount`, it seems that the `custom` template is indeed mounted as read-only, which for a template probably makes sense 🙂

```shell
FreeNAS# mount | grep custom
daten/iocage/templates/custom on /mnt/data/iocage/templates/custom (zfs, local, read-only, nfsv4acls)
daten/iocage/templates/custom/root on /mnt/data/iocage/templates/custom/root (zfs, local, read-only, nfsv4acls)
```

Is there a way to properly fix this? Any idea how I might have gotten into this state? Thanks for any help 🙏🏼

- [x] Supply `iocage --version`: `Version	1.2`
- [x] Supply the commands used, along with any steps to recreate it.
- [x] Provide the output from the command you issued.
- [x] Supply what you expected the result or output to be
- [x] Checked that the problem has not already been fixed on `master` if using
 a stable release.

**Comment by tehfink** [comment]
@lumaxis Did you find a solution?

**Comment by lumaxis** [comment]
@tehfink Unfortunately not, I ended up recreating the jails
