### ISSUE TITLE
Jails created from template did not inherit settings

### ISSUE THREAD

**Issue by vedadkajtaz** [iocage/iocage#1157]
Hello,

- [x] Supply `iocage --version`

Version 1.1 RELEASE 2019/01

- [x] Supply the commands used, along with any steps to recreate it.

The template has `allow_mount=1` and `allow_mount_zfs=1` properties set.

Creating a jail from template, ie:

`iocage create -t templatename -T --name jailname`

The newly created jail did not inherit the above properties:

`iocage get allow_mount jailname`

- [x] Provide the output from the command you issued.

`0`

- [x] Supply what you expected the result or output to be

`1`

- [ ] Checked that the problem has not already been fixed on `master` if using
 a stable release.

Sorry, couldn't do this at this time, need updating the whole system to be able to build a recent version.

**Comment by gdinolt** [comment]
I can confirm this problem.   I cloned iocage and installed. It exhibited the same problem as described above.  I would assume that a jail built from a template would "inherit" its configuration. Is there a reason it wouldn't?
