### ISSUE TITLE
Newline problems in plugin properties/settings in iocage fetch and get

### ISSUE THREAD

**Issue by RafalLukawiecki** [iocage/iocage#1163]
This affects iocage 1.2, and there are two, related issues:

- If a plugin defines a property value getter `serviceget` function and that function returns a value with an implied newline at its end, for example by means of `echo` then that value cannot be used as a `adminportal_placeholders` in its `ui.json` because the placeholder will emit the newline. For example, this ui.json:
```
{
    "adminportal": "%%S%%://%%IP%%:%%P%%/zm",
    "adminportal_placeholders": {
	"%%S%%": "adminprotocol",
	"%%P%%": "adminport"
    }
}
```
will generate admin portal value like:
```
Admin Portal:
http
://192.168.40.79:80
/zm
```
instead of everything being on one line.

- Conversely, changing the code of the `serviceget` function not to return any newlines, for example by using `printf` without a \n and instead of `echo` makes `iocage get -P property jail` return nothing even if `serviceget` returns a value.

As a result, it is not possible to consistently return property values for use both as placeholders and elsewhere. Ideally, `iocage get` would return a value even if there is no newline at the end of result returned by `serviceget`. Also, the placeholder replacing function should not add/pass newlines or extra spaces when forming the adminportal URL.

**Comment by jsegaert** [comment]
Thank you for reporting this.  I finally wanted to roll this functionality out for the MineOS plugin, but it'll have to wait a while longer...
