### ISSUE TITLE
2 pools marked active - deactive does not remove pool(s)

### ISSUE THREAD

**Issue by PeterSprague** [iocage/iocage#117]
Make sure to follow and check these boxes before submitting an issue! Thank you.

- [x] Supply `iocage --version`
Version 0.9.7 2017/03/08
- [x] Supply the commands used, along with any steps to recreate it.
$ iocage list
- [x] Provide the output from the command you issues.
Pools:
  raid2
  ssd2
You have 2 pools marked active for iocage usage.
Run "iocage deactivate ZPOOL" on 1 of the pools.

$ iocage deactivate ssd2
ssd2 successfully deactivated.

$ iocage deactivate raid2
raid2 successfully deactivated.

$ iocage activate raid2
ZFS pool 'raid2' successfully activated.

$ iocage list
Pools:
  raid2
  ssd2
You have 2 pools marked active for iocage usage.
Run "iocage deactivate ZPOOL" on 1 of the pools.

- [x] Supply what you expected the result or output to be
deactivate ssd2, activate raid2, be on my way back to iocage upgrade nirvana

- [x] Checked that the problem has not already been fixed on `master` if using
 a stable release.

Not reported in issues.  Haven't built from git master yet.

**Comment by skarekrow** [comment]
This *should* not be an issue in the latest git. Please try that first, make sure to do the `activate` command again though.

**Comment by PeterSprague** [comment]
Am I correct to assume that the current py-iocage port builds from git master?

**Comment by skarekrow** [comment]
No. The py3-iocage port is the up to date one. But even then there's been a lot of commits since. I recommend the git version.

**Comment by PeterSprague** [comment]
Building from git master throws error:

[root@xxxxxxxx] /usr/local/src/iocage/py-libzfs# python3.6 setup.py build
running build
running build_py
running build_ext
skipping 'libzfs.c' Cython extension (up-to-date)
building 'libzfs' extension
cc -Wno-unused-result -Wsign-compare -Wunreachable-code -DNDEBUG -O2 -pipe -fstack-protector -fno-strict-aliasing -fPIC -I/usr/src/cddl/lib/libumem -I/usr/src/sys/cddl/compat/opensolaris/ -I/usr/src/sys/cddl/compat/opensolaris -I/usr/src/cddl/compat/opensolaris/include -I/usr/src/cddl/compat/opensolaris/lib/libumem -I/usr/src/cddl/contrib/opensolaris/lib/libzpool/common -I/usr/src/sys/cddl/contrib/opensolaris/common/zfs -I/usr/src/sys/cddl/contrib/opensolaris/uts/common/fs/zfs -I/usr/src/sys/cddl/contrib/opensolaris/uts/common/sys -I/usr/src/cddl/contrib/opensolaris/head -I/usr/src/sys/cddl/contrib/opensolaris/uts/common -I/usr/src/cddl/contrib/opensolaris/lib/libnvpair -I/usr/src/cddl/contrib/opensolaris/lib/libuutil/common -I/usr/src/cddl/contrib/opensolaris/lib/libzfs/common -I/usr/src/cddl/contrib/opensolaris/lib/libzfs_core/common -I/usr/local/include/python3.6m -c libzfs.c -o build/temp.freebsd-12.0-CURRENT-amd64-3.6/libzfs.o -DNEED_SOLARIS_BOOLEAN -D_XPG6 -g -O0
libzfs.c:705:42: error: use of undeclared identifier 'ZFS_MAX_DATASET_NAME_LEN'
  __pyx_e_6libzfs_MAX_DATASET_NAME_LEN = ZFS_MAX_DATASET_NAME_LEN
                                         ^
libzfs.c:19645:73: warning: incompatible pointer to integer conversion passing 'PyObject *' (aka 'struct _object *') to parameter of type 'zfs_type_t'
      [-Wint-conversion]
  __pyx_v_handle = zfs_path_to_zhandle(__pyx_v_self->handle, __pyx_t_1, __pyx_t_3);
                                                                        ^~~~~~~~~
/usr/src/cddl/contrib/opensolaris/lib/libzfs/common/libzfs.h:700:79: note: passing argument to parameter here
extern zfs_handle_t *zfs_path_to_zhandle(libzfs_handle_t *, char *, zfs_type_t);
                                                                              ^
libzfs.c:50732:74: warning: passing 'const char *' to parameter of type 'char *' discards qualifiers [-Wincompatible-pointer-types-discards-qualifiers]
        __pyx_v_ret = zfs_destroy_snaps(__pyx_v_self->__pyx_base.handle, __pyx_v_c_name, 1);
                                                                         ^~~~~~~~~~~~~~
/usr/src/cddl/contrib/opensolaris/lib/libzfs/common/libzfs.h:563:52: note: passing argument to parameter here
extern int zfs_destroy_snaps(zfs_handle_t *, char *, boolean_t);
                                                   ^
2 warnings and 1 error generated.
error: command 'cc' failed with exit status 1

On TrueOS with newest update
Source updated
Performed steps as outlined in Readme.md

Solution?

**Comment by PeterSprague** [comment]
I'll continue down the rabbit hole of py3-libzfs non-building and post when I have some success

BTW - most recent py3-iocage port gives the same original problems as outlined above.

**Comment by skarekrow** [comment]
Interesting, I don't have any suggestions for the py-libzfs not building. I'd open it up on @jceel's tracker, he's very responsive and I'm sure he'd have an idea.

As for the original problem with the py3-iocage port, that's expected. It doesn't have the new behavior I was talking about, only git does right now.

**Comment by skarekrow** [comment]
Closing since this shouldn't be a problem in `master`. If it is still a problem we can reopen this.

**Comment by PeterSprague** [comment]
Still no response about py-libzfs not building on my TrueOS.

I have decided to move that TrueOS box to Fedora 25 with ZFS and Docker.  Numerous reasons led to this:
- Failed remote OS upgrade - completely locked up box, had to get on-site 1500mi away to repair
- After two days of fiddling, got operating OS but with "interrupt storm" if there was a call to audio in any program, no fix in sight
- Can't build iocage because of mismatch causing py-libzfs not to build
- Beadm environment now seems buggy - something has changed and the BE environments seem to be all intermixed, tried destroying failing BE using GUI, caused GRUB error
- TrueOS decision to create own repository of pkgs which to date is very limited

Sad to say been using FreeBSD and PCBSD variants for years, but the continued issues encountered with TrueOS since it inception caused me to say enough is enough

**Comment by skarekrow** [comment]
That's unfortunate to hear. Hopefully everything works out for you in the future. If not `iocage` and FreeBSD will still be here if you return :)

**Comment by PeterSprague** [comment]
No worries, plan to continue using FreeBSD with iocage on servers.  This was a 2nd office workstation.
