### ISSUE TITLE
IOCage jail fails to create VNET network with bhyve-mv bridge

### ISSUE THREAD

**Issue by marcinwisniowski** [iocage/iocage#1173]
On my FreeBSD box I'm trying to setup an environment when VMs are sharing the same network as jails. I'm using FreeBSD 12.1-RELEASE
```
root@freebsd121:~ # uname -a
FreeBSD freebsd121 12.1-RELEASE-p3 FreeBSD 12.1-RELEASE-p3 GENERIC  amd64
```
with installed both **iocage** and **bhyve-vm** using pkg

```
root@freebsd121:~ # pkg info |grep vm
vm-bhyve-1.4.2                 Management system for bhyve virtual machines
root@freebsd121:~ # pkg info |grep iocage
py37-iocage-1.2_5              FreeBSD jail manager written in Python3
root@freebsd121:~ # iocage --version
Version	1.2
```
I'm using bhyve-vm to manage bridges for the network as it provides a seamless functionality of 'virtual switches'

```
root@freebsd121:~ # vm switch create -a 192.168.10.0/24 jailnet

root@freebsd121:~ # vm switch info jailnet
------------------------
Virtual Switch: jailnet
------------------------
  type: standard
  ident: vm-jailnet
  vlan: -
  physical-ports: -
  bytes-in: 0 (0.000B)
  bytes-out: 0 (0.000B)
```
```
root@freebsd121:~ # ifconfig vm-jailnet
vm-jailnet: flags=8843<UP,BROADCAST,RUNNING,SIMPLEX,MULTICAST> metric 0 mtu 1500
	ether c6:fb:ad:f7:d2:94
	inet 192.168.10.0 netmask 0xffffff00 broadcast 192.168.10.255
	id 00:00:00:00:00:00 priority 32768 hellotime 2 fwddelay 15
	maxage 20 holdcnt 6 proto rstp maxaddr 2000 timeout 1200
	root id 00:00:00:00:00:00 priority 32768 ifcost 0 port 0
	groups: bridge vm-switch viid-aa12e@
	nd6 options=1<PERFORMNUD>
```
Once my bridged network is setup I'm creating a new iocage jail with VNET option enabled
```
root@freebsd121:~ # iocage create --name "TestJail" --release 12.1-RELEASE \
       interfaces="vnet0:vm-jailnet" ip4_addr="vnet0|192.168.10.100/24" \
       vnet_default_interface="vm-jailnet" vnet=on

TestJail successfully created!
```
Which goes smoothly. Then the **issue** arises when I'm trying to make my jail start.

```
root@freebsd121:~ # iocage start TestJail
```
```
No default gateway found for ipv6.
* Starting TestJail
  + Started OK
  + Using devfs_ruleset: 1000 (iocage generated default)
Traceback (most recent call last):
  File "/usr/local/bin/iocage", line 10, in <module>
    sys.exit(cli())
  File "/usr/local/lib/python3.7/site-packages/click/core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/click/core.py", line 717, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.7/site-packages/click/core.py", line 1137, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.7/site-packages/click/core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.7/site-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/iocage_cli/start.py", line 60, in cli
    ioc.IOCage(jail=jail, rc=rc).start(ignore_exception=ignore)
  File "/usr/local/lib/python3.7/site-packages/iocage_lib/iocage.py", line 1907, in start
    used_ports=used_ports,
  File "/usr/local/lib/python3.7/site-packages/iocage_lib/ioc_start.py", line 87, in __init__
    raise e
  File "/usr/local/lib/python3.7/site-packages/iocage_lib/ioc_start.py", line 84, in __init__
    self.__start_jail__()
  File "/usr/local/lib/python3.7/site-packages/iocage_lib/ioc_start.py", line 659, in __start_jail__
    vnet_err = self.start_network(vnet, nat)
  File "/usr/local/lib/python3.7/site-packages/iocage_lib/ioc_start.py", line 1010, in start_network
    err = self.start_network_interface_vnet(nic, net_configs, jid, nat)
  File "/usr/local/lib/python3.7/site-packages/iocage_lib/ioc_start.py", line 1126, in start_network_interface_vnet
    nic, bridge, membermtu, jid, nat_addr
  File "/usr/local/lib/python3.7/site-packages/iocage_lib/ioc_start.py", line 1157, in start_network_vnet_iface
    mac_a, mac_b = self.__start_generate_vnet_mac__(nic)
  File "/usr/local/lib/python3.7/site-packages/iocage_lib/ioc_start.py", line 1350, in __start_generate_vnet_mac__
    mac_a, mac_b = self.__generate_mac_address_pair(nic)
  File "/usr/local/lib/python3.7/site-packages/iocage_lib/ioc_start.py", line 1337, in __generate_mac_address_pair
    mac_b = hex(int(mac_a, 16) + 1)[2:].zfill(12)
ValueError: invalid literal for int() with base 16: 'tun0d78a7685'
```
The jail starts and i can log into it using `iocage console TestJail` command. However the network was not initialized so only lo0 interface si present.
```
root@freebsd121:~ # iocage list
+-----+----------+-------+--------------+----------------+
| JID |   NAME   | STATE |   RELEASE    |      IP4       |
+=====+==========+=======+==============+================+
| 2   | TestJail | up    | 12.1-RELEASE | 192.168.10.100 |
+-----+----------+-------+--------------+----------------+
```
Since the jail is up I'm trying to shut it down

```
root@freebsd121:~ # iocage stop TestJail
* Stopping TestJail
  + Executing prestop OK
  + Stopping services OK
  + Tearing down VNET FAILED
  ifconfig: interface vnet0.2 does not exist
  + Removing devfs_ruleset: 1000 OK
  + Removing jail process OK
  + Executing poststop OK
```
I'm expecting to be able to reuse bhyve-vm switches (bridges) to manage networks so I can use same network facility for hosts defined with virtualization and jails techniques. 
I found this idea in Michael's blog
https://blog.grem.de/pages/ayvn.html
This article is quite long but the section that I'm referring to can be found with **VNET Jails Using sysutils/iocage** subtitle

Make sure to follow and check these boxes before submitting an issue! Thank you.

- [x] Supply `iocage --version`
- [x] Supply the commands used, along with any steps to recreate it.
- [x] Provide the output from the command you issued.
- [x] Supply what you expected the result or output to be
- [x] Checked that the problem has not already been fixed on `master` if using
 a stable release.

**Comment by marcinwisniowski** [comment]
With a few more tests, I found that the root of this issue is generating a pair of mac addresses.
I proof this hypothesis by modifying `iocage create` command with adding the definition of `vnet0_mac`
```
root@freebsd121:~ # iocage create --name "TestJail" --release 12.1-RELEASE \
       interfaces="vnet0:vm-jailnet" ip4_addr="vnet0|192.168.10.100/24" \
       vnet_default_interface="vm-jailnet" vnet0_mac="00112233ff01,001122330001" vnet=on
```
This make a walkaround for the issue of creating a vnet interface however looks like the jail did not start without setting `defaultrouter` parameter.
```
root@freebsd121:~ # iocage start TestJail
No default gateway found for ipv6.
* Starting TestJail
  + Started OK
  + Using devfs_ruleset: 1000 (iocage generated default)
  + Configuring VNET FAILED
  route: writing to routing socket: Network is unreachable
add net default: gateway 10.16.0.0 fib 0: Network is unreachable

Stopped TestJail due to VNET failure
```
with both `vnet0_mac` and `defaultrouter` set properly I was able to start the jail

**Comment by marcinwisniowski** [comment]
With some deeper digging I found that the root cause of this issue was in `ioc_json.py` module with function `def get_mac_prefix()`

In my case, this function produces mac_prefix which is: **tun0**. This is not a valid hexadecimal value.
```python
>>> default_gw = netifaces.gateways()['default'][netifaces.AF_INET][1]
>>> default_mac = netifaces.ifaddresses(default_gw)[netifaces.AF_LINK]
>>> mac_prefix = default_mac[0]['addr'].replace(':', '')[:6]
>>> print(mac_prefix)
tun0
```
I tried patch that function with code from master branch however `iocage start` still takes the `tun0` as a prefix.

I'm guessing that if I would pull the master branch it might solve the issue, but I'm not sure.

**Comment by grembo** [comment]
> With some deeper digging I found that the root cause of this issue was in `ioc_json.py` module with function `def get_mac_prefix()`
> 
> In my case, this function produces mac_prefix which is: **tun0**. This is not a valid hexadecimal value.
> 
> ```python
> >>> default_gw = netifaces.gateways()['default'][netifaces.AF_INET][1]
> >>> default_mac = netifaces.ifaddresses(default_gw)[netifaces.AF_LINK]
> >>> mac_prefix = default_mac[0]['addr'].replace(':', '')[:6]
> >>> print(mac_prefix)
> tun0
> ```
> 
> I tried patch that function with code from master branch however `iocage start` still takes the `tun0` as a prefix.
> 
> I'm guessing that if I would pull the master branch it might solve the issue, but I'm not sure.

Could you try to apply this commit locally and test if it helps?

https://github.com/iocage/iocage/commit/5c1dcf9a92e7701c674b1312b41d3a549af6d768

If it does, I could patch the version in FreeBSD ports.
