### ISSUE TITLE
Allow getting property from multiple jails at once

### ISSUE THREAD

**Issue by darkain** [iocage/iocage#1179]
Make sure to follow and check these boxes before submitting an issue! Thank you.

- [x] Supply `iocage --version`
* machine 1:
Version 1.2
* machine 2:
c179f56f04de4c0c7bf2b872403ed15c20fa826d

- [x] Supply the commands used, along with any steps to recreate it.
iocage get boot *

- [x] Provide the output from the command you issued.
**Error: Got unexpected extra arguments ( ... list of file system files/dirs in cwd ... )**

- [x] Supply what you expected the result or output to be
A human readable table or json output (depending on option) showing the status of the particular variable on ALL available jails that match the wildcard pattern

- [x] Checked that the problem has not already been fixed on `master` if using
 a stable release.

**Comment by skarekrow** [comment]
This exists as `iocage get -r boot`

**Comment by darkain** [comment]
1) is this documented anywhere? On the iocage web site, I don't see this being mentioned. It looks like the only place this is ever mentioned is under "iocage get --help", which should probably also be the default output of "iocage get", but instead that displays an error message (not all that helpful)

2) What about json output to make this more easily scriptable? Looks like this was required three years ago with little involvement since? #402

**Comment by skarekrow** [comment]
I don't believe JSON output was ever added before I left iX. Most features that have been added since my departure are those that are (understandably) useful to iX. In both your examples I'd say a PR would be nice, as it's likely not a priority for them or myself.

It's almost been 3 years since that issue?! Man, time files!

- Brandon
