### ISSUE TITLE
IPv6: network services fail to bind at jail startup

### ISSUE THREAD

**Issue by moviuro** [iocage/iocage#119]
It takes time to leave "tentative" mode for interfaces with an IPv6 address.
As services are started when the IPv6 is still not available, they fail to bind and fail to start.
A much more detailled explanation is available on the [FreeBSD forums](https://forums.freebsd.org/threads/iocage-ipv6-jail-network-services-cant-bind-to-address.52096/).

I will try to setup a network service listening on IPv6 on the host and see if this issue can be repeated outside the jail.
ATM, the only solution is adding this to my ```rc.d``` scripts:
```sh
start_cmd() {
while ifconfig | grep tentative; do
     sleep 1
done
[...]
}
```

**Comment by skarekrow** [comment]
This seems like a ```jail(8)``` bug and not an ```iocage``` one. Have you tried replicating your setup manually using ```jail(8)```?

**Comment by moviuro** [comment]
@skarekrow no, not yet, didn't have enough time (and will be short on it too). However, if it's a ```jail(8)``` issue, it could be tested by anyone, I bet.
I'll do it this evening (UTC) but will certainly require assistance on IRC

**Comment by cactus** [comment]
@moviuro I ran [across this](https://lists.freebsd.org/pipermail/freebsd-jail/2013-July/002347.html) (be sure to click next thread to see that person's resolution). Might be worth a shot, especially if you are assigning statically, probably no need to wait around for duplicate address detection stuff.

**Comment by moviuro** [comment]
@cactus : you just saved me a lot of trouble :+1: thanks a lot!
(perhaps add this to the docs...?)
Add the following in `/etc/sysctl.conf`
```
## -- for jails
net.inet6.ip6.dad_count=0
```
