### ISSUE TITLE
iocage get stopped working

### ISSUE THREAD

**Issue by joachimmathes** [iocage/iocage#119]
`iocage get` stopped working in version 0.9.8 BETA (commit `5403f988e28ea1bafe10a8575518a218d11c6711`)

Example:
```
$ iocage get host_hostuuid <JAIL-ID>
$ 
```
=> no output

**Comment by skarekrow** [comment]
Well that's an easy one, I forgot to change all the commands after logging, I only did a few >_> whoops! I'll fix real quick here. Thanks for reporting.
