### ISSUE TITLE
iocage fetch give little feedback that the download is working

### ISSUE THREAD

**Issue by woodsb02** [iocage/iocage#12]
Rather than just "Downloading: base.txz...", it would be helpful if iocage fetch would also provide more console output showing the progress of the download if possible, or at least the current download rate and total amount downloaded so far.

This is important to me as I have a slow internet connection, and it can take some time before it moves onto the next file lib32.txz, so I am left wondering if it is working.

Ctrl-t (siginfo) does not provide any further confidence or details that the download is working.

```
# iocage fetch -h -s mirror.internode.on.net -r 11.0-RELEASE -d pub/freebsd/releases/amd64
Fetching: 11.0-RELEASE

Downloading: base.txz...
load: 0.30  cmd: python2.7 29007 [sbwait] 13.29r 1.55u 0.15s 5% 22220k
Extracting: base.txz...
Downloading: lib32.txz...
Extracting: lib32.txz...
Downloading: doc.txz...
Extracting: doc.txz...

* Updating 11.0-RELEASE to the latest patch level...
```

It would also be helpful if more details were provided when downloading/updating the release to the latest patch level - what is it currently doing, what patch level is it trying to get to, etc.

**Comment by skarekrow** [comment]
I originally hid updating progress to keep things clean. But I can understand if it takes a while that it's irritating. I'll have it show the information instead. 

Thanks for the feedback!

**Comment by skarekrow** [comment]
I have committed it here: https://github.com/iocage/iocage/commit/fbd3a46a2d66d6a0dd11277c6f1fc733423d0207

Please test and let me know 👍
