### ISSUE TITLE
I cannot use a a full jail created with tag=default

### ISSUE THREAD

**Issue by codeorcode** [iocage/iocage#120]
The the following commands.

root@web1:/home/john # iocage create tag=default ip4_addr="lo1|10.0.0.1/24"
[...]
root@web1:/home/john # iocage start default
  INFO: restoring jail mountpoint
cannot unmount '/iocage/jails/none': No such file or directory
  ERROR: none not found.

root@web1:/home/john # iocage destroy default
grep: jail: No such file or directory
grep: none: No such file or directory
grep: not: No such file or directory
grep: found!: No such file or directory

  WARNING: this will destroy jail none
  Dataset: sys/iocage/.defaults

  Are you sure ? y[N]: Y
  Destroying: none
[: ERROR:: unexpected operator

To solve the problem I've destroyed the jail using UUID. Then I've created a new machine with tag name different than "default".

**Comment by skarekrow** [comment]
Please read the documentation: http://iocage.readthedocs.org/en/latest/basic-use.html . We use the ```default``` tag to allow someone to set defaults that iocage honors. Just use a different TAG :+1:

**Comment by codeorcode** [comment]
I've read the documentation but it did not say I cannot use tag=default, just that I can set default options using default keyword. So I am suggesting to if is possible to disallow creating of a jail with tag=default.

I've figured out that is the problem so for me this is not an issue anymore but I am thinking maybe others could have this problem in the future.

Thank you for the quick feedback and best regards.
