### ISSUE TITLE
[feature] add option for machine readable output

### ISSUE THREAD

**Issue by baloan** [iocage/iocage#1200]
When listing all jails: `iocage list` the output contains lots of verbose ascii art to make the output more human readable.
As I want to parse the output with tools like `awk` or `python.split` the ascii art makes things much more difficult.
A switch to get rid of ascii art in output will be very helpful here.
Proposal: add `-m, --machine-readable` option, which removes all ascii art, instead adds field separators.
One workaround is to use `iocage --version | grep -v +` but that depends on the stability of the ascii art format. I am reluctant to assume the stability of human readable formatting output.

- [x] Supply `iocage --version`
```
root@nas1:~ # iocage --version
Version 1.2
```

- [x] Supply the commands used, along with any steps to recreate it.
```
root@nas1:~ # iocage list
```

- [x] Provide the output from the command you issued.
```
+-----+-----------------+-------+--------------+------+
| JID |      NAME       | STATE |   RELEASE    | IP4  |
+=====+=================+=======+==============+======+
| 1   | gitlab-runner-1 | up    | 11.3-RELEASE | DHCP |
+-----+-----------------+-------+--------------+------+
| 2   | gitlab-runner-2 | up    | 11.3-RELEASE | DHCP |
+-----+-----------------+-------+--------------+------+
```

- [x] Supply what you expected the result or output to be

```
root@nas1:~ # iocage list -m
# JID,NAME,STATE, RELEASE, IP4
1,gitlab-runner-1,up,11.3-RELEASE,DHCP
2,gitlab-runner-2,up,11.3-RELEASE,DHCP
```
Applies to `snaplist` as well. Other commands with ascii output shall be amended, too.

**Comment by skarekrow** [comment]
Does `iocage list -H` not do what you expect?

**Comment by baloan** [comment]
My bad, of course it does. `-H, --header` hides behind `-h` which usually codes for `-h, --help`. I stopped reading at `-h`. Item may be closed. 
Well, you might consider moving `-H, --header` away from `-h`!
