### ISSUE TITLE
iocage update overwrites jail's /etc/resolv.conf file

### ISSUE THREAD

**Issue by leManu** [iocage/iocage#1202]
We are using iocage version 1.2 on several hosts.

When issuing `iocage update <jail>` we noticed that the `/etc/resolv.conf` file of the jail is forcefully overwritten with the host's one, even if the `resolver` property of the jail is set to a value different of `none`.

The problem seems to be here in the `fetch_update` function defined in `iocage_lib/ioc_fetch.py` : https://github.com/iocage/iocage/blob/c3198327c892aad959fda1dbad64934f8f6fd63b/iocage_lib/ioc_fetch.py#L875

Maybe this this file copy should be conditioned to a test of the `resolver` property value ?

**Comment by dgeo** [comment]
After some tests, I think this line can be removed (I can't figure out when it would be needed)…
``iocage fetch`` works without it, ``iocage create`` also, and of course ``iocage update``

**Comment by stoklund** [comment]
I just hit this bug too. My host pulls an IPv6 nameserver from DHCP, but my jails only have IPv4 networking configured. This means that the jails no longer have working DNS after running `iocage update`.

The fact that the update succeeds with a defunct `resolve.conf` suggests that a working jail DNS configuration is not required to perform the update.
