### ISSUE TITLE
allow for optional usr/src 

### ISSUE THREAD

**Issue by cactus** [iocage/iocage#121]
It would be nice to make inclusion of usr/src optional for thick or thin jails somehow. Would this be possible?

I located the ftpfiles variable in ioc-globals, but I didn't see a way to override it like ftphost is done.

**Comment by skarekrow** [comment]
We currently do that for upgrading. We needed it for the etcupdate
operation. So personally,  I don't want this part optional.

**Comment by cactus** [comment]
No worries. I can always hack it locally if I end up feeling strongly enough about it. :)

**Comment by skarekrow** [comment]
Exactly :) I just think an option would end up confusing users when it came
time to upgrade. I can already picture the deluge of issues. It's a small
amount of space, so thankfully it's not a huge issue.

-Brandon

**Comment by pannon** [comment]
@cactus once FreeBSD base is transformed to PKG (ETA 11.0) this will be a non issue.

**Comment by cactus** [comment]
@pannon That is a great point! Looking forward to it. :D
