### ISSUE TITLE
Catch SIGINT for create

### ISSUE THREAD

**Issue by kasper5** [iocage/iocage#121]
Hi,

My iocage seems to have broken after I did Ctrl-C just after I executed iocage create. 

I did this: `iocage create tag=myjailname -r 11.0-RELEASE`. Just after I pressed enter I did Ctrl-C because i realized that I entered wrong tag. After this I can't stop, start, destroy etc jails...

My iocage version is: **Version 0.9.5 2017/02/15**

Here 's the error I get everytime I try to do start, stop, list etc:
![iocage_error](https://cloud.githubusercontent.com/assets/11734075/25474389/5cf0e7ce-2b33-11e7-913f-0d07e0ddb2a3.png)

It seems to complain about something in the config.json maybe? I tried to look but I can't see anything that's off.

**Comment by skarekrow** [comment]
You're using quite an old version (remember, this is a beta :P) please update your version to the latest git version. That will allow you to destroy that uuid, and then proceed with operations.

The readme has the directions for updating if you need them.

**Comment by kasper5** [comment]
Oh whops. Thank you for the fast answer :) I will get on and update my iocage :)

**Comment by skarekrow** [comment]
Hehe it's ok! Thinking on this more, I should catch SIGINT, so I'll mark this as an enhancement for one day down the road.

**Comment by skarekrow** [comment]
Ok this should be fixed, hopefully this doesn't get you in the future! 👍

**Comment by kasper5** [comment]
Awesome man, good work 👍
