### ISSUE TITLE
`iocage --destroy foo` also destroys foo-bar

### ISSUE THREAD

**Issue by mrpengy** [iocage/iocage#1226]
I'm experiencing this on Truenas 12.2
iocage version 1.2

Can easily be replicated with:

`iocage create -n foo -r latest`
`iocage create -n foo-bar -r latest`
`iocage list    #shows both 'foo' and 'foo-bar' jails`
`iocage destroy foo`
`iocage list    #both jails are now gone`

Expected behavior: Jail foo-bar does not get destroyed.

**Comment by sonicaj** [comment]
This should be fixed in upcoming TrueNAS 12 U1 Release
