### ISSUE TITLE
iocage update/upgrade fail to reach latest versions

### ISSUE THREAD

**Issue by itskando** [iocage/iocage#1227]
TrueNAS 12.0.
iocage version 1.2

**Background**:
There are 2 preexisting jails and 1 new test jail (syncthing — not yet setup).

**Issue**:
The preexisting jails were unable to `iocage update  <jail>` past their current version.
When they were 11.3-RELEASE, they only updated to 11.3-RELEASE.

The preexisting jails updated via `iocage upgrade <jail> -r 12.0-RELEASE` to 12.0.
They are now 12.0-RELEASE, but they only update to 12.0-RELEASE.

The preexisting jails are unable to `iocage upgrade <jail> -r [12.0|12.1|12.2]-RELEASE` past 12.0.
`iocage upgrade <jail> -r 12.2-RELEASE`, for example, updates to 12.0 (not 12.2).

New jails are able to be made in 12.2 without issue.

**Expectation**:
I was expecting to be able to update or manual upgrade to the 12.2 release.

**Commands and Outputs**:
```
root@Deetz:~ # iocage list
+-----+-----------+-------+--------------+---------------+
| JID |   NAME    | STATE |   RELEASE    |      IP4      |
+=====+===========+=======+==============+===============+
| 1   | media     | up    | 12.0-RELEASE | 192.168.86.10 |
+-----+-----------+-------+--------------+---------------+
| 2   | openVPN   | up    | 12.0-RELEASE | 192.168.86.8  |
+-----+-----------+-------+--------------+---------------+
| 3   | syncthing | up    | 12.2-RELEASE | DHCP          |
+-----+-----------+-------+--------------+---------------+



.



root@Deetz:~ # iocage update media
Snapshot: Lydia/iocage/jails/media@ioc_update_12.0-RELEASE-p13_2020-11-20_18-34-04 created.
Updating jail...

* Updating media to the latest patch level... 
Looking up update.FreeBSD.org mirrors... 3 mirrors found.
Fetching metadata signature for 12.0-RELEASE from update4.freebsd.org... done.
Fetching metadata index... done.
Inspecting system... done.
Preparing to download files... done.

No updates needed to update system to 12.0-RELEASE-p13.

WARNING: FreeBSD 12.0-RELEASE HAS PASSED ITS END-OF-LIFE DATE.
Any security issues discovered after Fri Feb 28 19:00:00 EST 2020
will not have been corrected.
No updates are available to install.
Run '/tmp/tmpq477w54n fetch' first.

release: 12.0-RELEASE-p13 -> 12.0-RELEASE-p13



.



root@Deetz:~ # iocage upgrade media -r 12.2-RELEASE
Looking up update.FreeBSD.org mirrors... 3 mirrors found.
Fetching metadata signature for 12.0-RELEASE from update4.freebsd.org... done.
Fetching metadata index... done.
Inspecting system... done.

The following components of FreeBSD seem to be installed:
src/src world/base world/doc world/lib32

The following components of FreeBSD do not seem to be installed:
world/base-dbg world/lib32-dbg

Does this look reasonable (y/n)? n
Command: /tmp/tmpgtqfw_3e -b /mnt/Lydia/iocage/jails/media/root -d /mnt/Lydia/iocage/jails/media/root/var/db/freebsd-update/ -f /mnt/Lydia/iocage/jails/media/root/etc/freebsd-update.conf --not-running-from-cron --currently-running 12.0-RELEASE -r 12.2-RELEASE upgrade failed!
root@Deetz:~ # 
```

- [x] Supply `iocage --version`
- [x] Supply the commands used, along with any steps to recreate it.
- [x] Provide the output from the command you issued.

- [x] Supply what you expected the result or output to be
- [ ] Checked that the problem has not already been fixed on `master` if using
 a stable release.

**Comment by itskando** [comment]
Cleaned up summary : j

**Comment by itskando** [comment]
Update doesn't work, but upgrade -r actually does if I keep going..

**Comment by igalic** [comment]
that behaviour sounds expected, and analogous to [freebsd-update(8)](https://man.freebsd.org/freebsd-update(8)) itself
