### ISSUE TITLE
term resets to 'xterm-256color' on iocage console

### ISSUE THREAD

**Issue by GunbleR** [iocage/iocage#1229]
i use putty, so my preferred term env variable is "putty" for home/end stock support.
when i enter jail via iocage console jail, it resets term to 'xterm-256color'.
suggest to pull term variable from host os, like lang variable.
file iocage_lib/iocage.py, line 828

**Comment by invario** [comment]
> i use putty, so my preferred term env variable is "putty" for home/end stock support. when i enter jail via iocage console jail, it resets term to 'xterm-256color'. suggest to pull term variable from host os, like lang variable. file iocage_lib/iocage.py, line 828

I'm getting the same problem  here. On TrueNAS Core 13 which is FreeBSD 13.1-RELEASE-p1, iocage version 1.2.

It's a minor annoyance that I have to manually set it to putty in order for my home/end keys to work.
