### ISSUE TITLE
snapshots copied to new thick jail

### ISSUE THREAD

**Issue by cactus** [iocage/iocage#123]
I had two thin provisioned jails, and then created a subsequent thick jail. The thick jail appears to have snapshots from the release dataset that the thick jail was copied from, carried over as part of the send/recv used to create the jail dataset.

Here is my release dataset:
```
xyz/iocage/releases/10.1-RELEASE                                                                 clones    -                                                             -
xyz/iocage/releases/10.1-RELEASE@656c2d68-1ea9-11e5-9ed8-0cc47a31451a                            clones    xyz/iocage/jails/656c2d68-1ea9-11e5-9ed8-0cc47a31451a       -
xyz/iocage/releases/10.1-RELEASE@5bf845ee-1ebd-11e5-9ed8-0cc47a31451a                            clones    xyz/iocage/jails/5bf845ee-1ebd-11e5-9ed8-0cc47a31451a       -
xyz/iocage/releases/10.1-RELEASE/root                                                            clones    -                                                             -
xyz/iocage/releases/10.1-RELEASE/root@656c2d68-1ea9-11e5-9ed8-0cc47a31451a                       clones    xyz/iocage/jails/656c2d68-1ea9-11e5-9ed8-0cc47a31451a/root  -
xyz/iocage/releases/10.1-RELEASE/root@5bf845ee-1ebd-11e5-9ed8-0cc47a31451a                       clones    xyz/iocage/jails/5bf845ee-1ebd-11e5-9ed8-0cc47a31451a/root  -
```

And here are the snapshots on the thick jail. At least it looks like it isn't referencing much.
```
xyz/iocage/jails/31013279-1ee7-11e5-9ed8-0cc47a31451a                                             825M   210G    96K  /iocage/jails/31013279-1ee7-11e5-9ed8-0cc47a31451a
xyz/iocage/jails/31013279-1ee7-11e5-9ed8-0cc47a31451a@656c2d68-1ea9-11e5-9ed8-0cc47a31451a          8K      -    96K  -
xyz/iocage/jails/31013279-1ee7-11e5-9ed8-0cc47a31451a@5bf845ee-1ebd-11e5-9ed8-0cc47a31451a          8K      -    96K  -
```

Perhaps after a create of a thick jail, remove any snapshots on the newly created jail after zfs receive?
Example:

```
# ioc-zfs
    else
        zfs snapshot -r $pool/iocage/releases/$release@$uuid
        zfs send     -R $pool/iocage/releases/$release@$uuid | \
        zfs recv        $pool/iocage/jails/$uuid
        zfs destroy  -r $pool/iocage/releases/$release@$uuid
        # zfs destroy  -r $pool/iocage/jails/$uuid@$uuid  # this could be removed
        snap_list=$(zfs list -H -d 1 -t snapshot -o name $pool/iocage/jails/$uuid)
        # remove any snapshots added as part of send/recv
        for snap_name in $snap_list; do
            zfs destroy -r $pool/iocage/jails/$uuid@$snap_name
        done
    fi
```

I can of course clean it up manually, but their appearance was somewhat unexpected.

**Comment by pannon** [comment]
@cactus yes those snapshot are from your active the clones. They are inherited with `zfs send -R` - will write a cleanup step to get rid of them.

The size is negligible 1K/snapshot - but it is better not to have those around.

**Comment by pannon** [comment]
@cactus this should be all good now. Please test when you can. Also the new `iocage snapremove UUID@ALL` will remove all snapshots now - if you need it.

**Comment by cactus** [comment]
This looks great. Thanks for the quick turn around!
Might be a couple of days until I am able to test. Will report back if I run into any issues.

**Comment by cactus** [comment]
I had a chance to test the `@ALL` syntax just a bit ago, with the freebsd patch that came out. I did an `iocage update`, and afterwards was able to use `snapremove jailname@ALL` to remove the update snapshot as expected.

**Comment by skarekrow** [comment]
:+1:
