### ISSUE TITLE
retrieve_cpu_sets fails with more than 10 cores

### ISSUE THREAD

**Issue by jyoung15** [iocage/iocage#1230]
Make sure to follow and check these boxes before submitting an issue! Thank you.

- [x] Supply `iocage --version`
- [x] Supply the commands used, along with any steps to recreate it.
- [x] Provide the output from the command you issued.
- [x] Supply what you expected the result or output to be
- [x] Checked that the problem has not already been fixed on `master` if using
 a stable release.

```
iocage --version
Version 1.2
```

Issue occurs when using `iocage create` with the `cpuset` option on a system with more than 10 cores.  For example `cpuset=0-5`

Actual Output:
```
Please make sure the provided cpus fall in the correct range of cpus.
For this system it is: 0,1
```

Expected Output:
`iocage create` continues normally

Issue appears to be with the regular expression in retrieve_cpu_sets.

On my system (FreeBSD 12.2), `cpuset -g -s 0` outputs the following:
```
cpuset 0 mask: 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11
cpuset 0 domain policy: first-touch mask: 0
```

I believe the fix is to adjust the regular expression at https://github.com/iocage/iocage/blob/82193949a14555ef17ab60f66ac180880c9fa20c/iocage_lib/ioc_json.py#L202

to:
`r'.*mask:.*?(\d+)$',`

Specifically changing the `.*` (greedy) after `mask:` to `.*?` (lazy) which causes the capturing group `(\d+)` to match more than a single digit.

**Comment by kevans91** [comment]
I'd recommend just rototilling that function to stop assuming the mask is contiguous, return a set of every cpu in the mask and let consumers work out what they want with it.
