### ISSUE TITLE
iocage get mountpoint returns "readonly"

### ISSUE THREAD

**Issue by bsdphk** [iocage/iocage#1231]
$ uname -a
FreeBSD norne.freebsd.dk 12.2-RELEASE FreeBSD 12.2-RELEASE r366954 GENERIC  amd64
$ iocage --version
Version 1.2 RC
$ iocage get mountpoint stow
readonly

**Comment by benoitc** [comment]
+1 any idea ?

**Comment by bsdphk** [comment]
Just tested on fresh current (main-n250192-5bb67f5f3f5-dirty) and fresh iocage (py38-iocage-devel-1.2.20211001,1), same result:

    root@ti:~ # iocage get mountpoint kodachrome
    readonly
