### ISSUE TITLE
TrueNAS upgrade, now: "cannot receive new filesystem stream: invalid backup stream"

### ISSUE THREAD

**Issue by hartzell** [iocage/iocage#1238]
Make sure to follow and check these boxes before submitting an issue! Thank you.

- [x] Supply `iocage --version`
  ```
  sable% iocage --version
  Version	1.2
  ```
- [x] Supply the commands used, along with any steps to recreate it.
  - see below
- [x ] Provide the output from the command you issued.
  - see below
- [x] Supply what you expected the result or output to be
- [?] Checked that the problem has not already been fixed on `master` if using
 a stable release.

### TL;DR

I seem to be unable to receive a stream in a jail.  It feels like there's some "capability" that I've not enabled, but I'm at a loss...

### Details

I have a FreeNAS box (named *sable*) that had been running `FreeNAS-11.3-U2`.  It has a jail that that was using `syncoid` to mirror `sanoid` managed snapshots of a remote box that's running `12.1-RELEASE-p7`.

Today I upgraded *sable* to `TrueNAS-12.0-U1`.  After I upgraded I noticed that the `syncoid` jobs weren't working and (*sigh*) hadn't been running for a while.

I dug into the commands that syncoid was running and discovered that `receive` was failing with `cannot receive new filesystem stream: invalid backup stream`.

In the course of debugging: 
- I ran `send` on the remote machine and saved the stream into a file, copied that file into the jail on *sable* and tried to `receive` it.  I got the same error.
- I tried to receive from the file directly on *sable* (not in a jail) and it worked.
- I tried a pair of `send` and `receive` in the jail, which fails
- I tried `send` in the jail and `receive` in host shell and it succeeds.
- I played with allowing various things via `zfs allow`.
- I *am* able to use `zfs create` in the jail.

I've ended up with the following test script:

```sh
sudo iocage create -r 12.2-RELEASE -n foo
sudo iocage set allow_mount=true allow_mount_zfs=true enforce_statfs=1 jail_zfs=1 jail_zfs_dataset=jailed-foo jail_zfs_mountpoint=/jailed-foo foo
sudo iocage start foo
sudo iocage exec foo 'zfs allow everyone allow,mount,create,receive,rollback,mountpoint storage/jailed-foo'
sudo iocage exec foo 'zfs allow storage/jailed-foo'
sudo iocage exec foo 'zfs snapshot storage/jailed-foo@foo'

# Running the receive in the jail fails
sudo iocage exec foo 'zfs send storage/jailed-foo@foo | zfs receive storage/jailed-foo/backups'

# Running the receive on the host system works....
sudo iocage exec foo 'zfs send storage/jailed-foo@foo' | sudo zfs receive storage/jailed-foo/backups

sudo iocage stop foo
sudo iocage destroy -f foo
sudo zfs destroy -r storage/jailed-foo
```

Which generates the following output:

```sh
sable% sudo iocage create -r 12.2-RELEASE -n foo
Default mac_prefix specified in defaults.json 'd06726' is invalid. Using 'd26726' mac prefix instead.
foo successfully created!
sable% sudo iocage set allow_mount=true allow_mount_zfs=true enforce_statfs=1 jail_zfs=1 jail_zfs_dataset=jailed-foo jail_zfs_mountpoint=/jailed-foo foo
allow_mount: 0 -> 1
allow_mount_zfs: 0 -> 1
enforce_statfs: 2 -> 1
jail_zfs: 0 -> 1
jail_zfs_dataset: iocage/jails/foo/data -> jailed-foo
jail_zfs_mountpoint: none -> /jailed-foo
sable% sudo iocage start foo
* Starting foo
  + Started OK
  + Using devfs_ruleset: 1002 (iocage generated default)
  + Using IP options: ip4.saddrsel=1 ip4=new ip6.saddrsel=1 ip6=new
  + Starting services OK
  + Executing poststart OK
sable% sudo iocage exec foo 'zfs allow everyone allow,mount,create,receive,rollback,mountpoint storage/jailed-foo'
sable% sudo iocage exec foo 'zfs allow storage/jailed-foo'
---- Permissions on storage/jailed-foo -------------------------------
Local+Descendent permissions:
	everyone allow,create,mount,mountpoint,receive,rollback
sable% sudo iocage exec foo 'zfs snapshot storage/jailed-foo@foo'
sable%
sable% # Running the receive in the jail fails
sable% sudo iocage exec foo 'zfs send storage/jailed-foo@foo | zfs receive storage/jailed-foo/backups'
cannot receive new filesystem stream: invalid backup stream
warning: cannot send 'storage/jailed-foo@foo': Broken pipe
Command: /bin/sh -c zfs send storage/jailed-foo@foo | zfs receive storage/jailed-foo/backups failed!
sable%
sable% # Running the receive on the host system works....
sable% sudo iocage exec foo 'zfs send storage/jailed-foo@foo' | sudo zfs receive storage/jailed-foo/backups
sable%
sable% sudo iocage stop foo
* Stopping foo
  + Executing prestop OK
  + Stopping services OK
  + Removing devfs_ruleset: 1002 OK
  + Removing jail process OK
  + Executing poststop OK
sable% sudo iocage destroy -f foo
Destroying foo
sable% sudo zfs destroy -r storage/jailed-foo
```

I feel like there's some switch that needs to be thrown, but I'm at a loss....

Suggestions?  **Thanks!**

**Comment by hartzell** [comment]
I have a second, older NAS, it's still running `FreeNAS-11.3-U2`.

I just ran through the test above, but using a jail based on `11.3-RELEASE` and the `send`/`receive` pair works when run in the jail.

Finally, I ran the test above on *sable*, which has been upgraded to TrueNAS, using an `11.3-RELEASE` jail and it fails as it does with the `12.2-RELEASE` jail.

**Comment by isometry** [comment]
@hartzell : it's not just you, I too am seeing exactly the same behaviour with TrueNAS 12.0-U1.1, as it appears is [Breit on the TrueNAS forums](https://www.truenas.com/community/threads/truenas-replication-task-option-to-prevent-auto-mount-after-replication-is-finished.90315/).

**Comment by isometry** [comment]
The root cause appears to be TrueNAS' early switch to OpenZFS 2.0, which isn't included within the standard 12.2-RELEASE basejail: https://jira.ixsystems.com/browse/NAS-108832. From the perspective of the `/sbin/zfs` in the 12.2-RELEASE jail, the error message is entirely accurate: it doesn't understand the feature flags on the source dataset.

A dirty workaround until an OpenZFS 2.0 compatible jail image is available:

```sh
ZFS2JAIL=backup-target
cp /usr/local/sbin/zfs /mnt/tank/iocage/jails/${ZFS2JAIL}/root/sbin/
for lib in $(ldd -f '%p\n' /usr/local/sbin/zfs | fgrep /local/); do
  cp -p $lib /mnt/tank/iocage/jails/${ZFS2JAIL}/root/lib/;
done
```

**Comment by hartzell** [comment]
@isometry -- Doh, of course.  Isn't there also a version of OpenZFS 2.0 in ports that I could install into the jail and be up to date?

**Comment by isometry** [comment]
@hartzell : indeed. A somewhat less dirty workaround:

```sh
iocage pkg ${ZFS2JAIL} install -y openzfs
iocage exec ${ZFS2JAIL} chmod -x /sbin/zfs
```

**Comment by hartzell** [comment]
Problem solved.  Thanks!
