### ISSUE TITLE
Jailed dataset left mounted when destroying jails

### ISSUE THREAD

**Issue by freqlabs** [iocage/iocage#124]
How to reproduce:

```
iocage create tag=foo
zfs create system/bar
iocage set jail_zfs_dataset=bar foo
iocage start foo
iocage exec foo zfs set mountpoint=/bar system/bar
iocage stop foo
iocage destroy foo
```

Result:
The dataset `system/bar` is still mounted after destroying the jail. I somehow managed to crash the system trying to unmount it after the fact but am unable to reproduce that part.

Expected result:
Unjail and unmount the dataset without destroying it. Any other filesystems mounted within the jail should be handled the same way, but I haven't tested how this behaves currently.

**Comment by pannon** [comment]
@freqlabs this is likely so because you are not setting `zfs jailed=on system/bar`.

**Comment by freqlabs** [comment]
I'm not, iocage does that when you start the jail.

**Comment by pannon** [comment]
@freqlabs this behaves correctly, once you destroy the jail your custom ZFS dataset is returned to the host. We are never destroying any datasets outside of the iocage jail itself - I believe this is the safest and the right choice in terms of data integrity.
