### ISSUE TITLE
Missing DNS resolver property

### ISSUE THREAD

**Issue by pos42** [iocage/iocage#1241]
Hi

I am doing a test on a FreeBSD 12.2-REELASE-p3 host with iocage 1.2.

I have set up several VLANSs with bridges on the iocage host. All VLANS works as it should.

Lab host is on lab LAN, which is 192.168.0.0/24. And  the host has 192.168.0.1 in its resolver as the lab networks gw AND dns is the same.

Now...

iocage create -T -r 12.2-RELEASE --name TESTLAN
iocage  set vnet=on interfaces="vnet0:LAN_BRIDGE" ip4_addr="vnet0|192.168.0.2/24" defaultrouter="192.168.0.1" TESTLAN
iocage start TESTLAN

iocage create -T -r 12.2-RELEASE --name TESTDMZ
iocage  set vnet=on interfaces="vnet0:DMZ1_BRIDGE" ip4_addr="vnet0|192.168.1.2/24" defaultrouter="192.168.1.1" TESTDMZ
iocage start TESTDMZ

Both jails works ok on their respectivly VLAN.

But....

The TESTDMZ jail gets the 192.168.0.1 dns server in the jails /etc/resolv.conf.... That is wrong. I want to be able to set it to 192.168.1.1 during the "iocage set" above...

I am looking for a dns property to set on the TESTDMZ jail when created to I don't manually have to change the jails /etc/resolv.conf afterwards

Ok this is my first VNET test. Have I missed anything important and obvious? Please enlighten me...

Tnx
Peo

**Comment by dgeo** [comment]
I do not see resolver property en pour command ?

**Comment by pos42** [comment]
What do you mean by your comment? Yes, I know that :) That is what I am posting....

Such property, as an option, is what probably should be there when creating a jail. Maybe a missing feature... If you have VLAN:s, the main hosts /etc/resolv.conf cannot be assumed by default for the jail, as the jail could be placed on another logical network, thus needing another /etc/resolv.conf.

Peo

**Comment by pos42** [comment]
Ok, I from the main host do:
echo "nameserver 192.168.1.1" > /iocage/jails/ATHENA/root/etc/resolv.conf

But I just wonder if it is possible to do directly with iocage commands... If not, maybe request a feature for it.

**Comment by pos42** [comment]
Ehhh. Sorry for causing noise on the line here...

I actually found an option for it. I guess "RTFM" is appropriate for me here :)

The solution is:
iocage  set vnet=on interfaces="vnet0:DMZ1_BRIDGE" ip4_addr="vnet0|192.168.1.12/24" **resolver="nameserver 192.168.1.1;search test.org"** defaultrouter="192.168.1.1" TESTDMZ

Which set a nice and correct resolv.conf...

[root@nuc ~]# iocage console TESTDMZ
Last login: Wed Feb  3 21:45:08 on pts/2
FreeBSD 12.2-RELEASE-p3 GENERIC 

rroot@TESTDMZ:~ # more /etc/resolv.conf 
nameserver 192.168.1.1
search test.org
root@TESTDMZ:~ #
