### ISSUE TITLE
Creating a jail with jail_zfs_dataset misbehaves

### ISSUE THREAD

**Issue by freqlabs** [iocage/iocage#125]
```
iocage create tag=foo jail_zfs_dataset=bar jail_zfs=on
```

When the jail is created, iocage tries to create the bar dataset rather than the default one, but sets the jail_zfs_dataset property to the default value.

**Comment by pannon** [comment]
@freqlabs supplying a custom jail_zfs_dataset at creation is not supported.
 
Why do you need a custom dataset other than the one created by default?

**Comment by freqlabs** [comment]
I want to use a dataset that already exists, for one example. I also have set up several jails that are related, and each jail has its own jailed dataset. The datasets for all the related jails are children of the same parent dataset, allowing me to adminster them as a group.

If it's not supported, this is an awfully bad way of not supporting it. A message "not supported" would make more sense than creating the dataset specified but not setting the property on the jail to that dataset. It would make even more sense to just set the property on the jail according to the property specified on the command line, but if it's too much trouble to support it, then I would suggest documenting this and any other unsupported properties in the man page under the `iocage create` section.

**Comment by pannon** [comment]
@freqlabs it think we could make this one work easily as the dataset is created automatically anyway and only the property needs to be set correctly.

**Comment by pannon** [comment]
@freqlabs please test with latest version in develop branch - should be all working now.

**Comment by freqlabs** [comment]
Thanks :)
