### ISSUE TITLE
Any ETA on a new release?

### ISSUE THREAD

**Issue by mvanbaak** [iocage/iocage#1251]
Make sure to follow and check these boxes before submitting an issue! Thank you.

- [X] Supply `iocage --version`
- [X] Supply the commands used, along with any steps to recreate it.
- [X] Provide the output from the command you issued.
- [X] Supply what you expected the result or output to be
- [X] Checked that the problem has not already been fixed on `master` if using
 a stable release.

```bash
$ iocage --version
Version 1.2
```

The iocage 1.2 tag/release is from Sept. 26 2019. If you look at the stats one can see:
```1913 commits to master since this release```

Please, pretty please, can a new version be released? The current FreeBSD port is already using a bunch of commits as patches to create a usable version. Would be so nice to update the port to use a new released version and get rid of all the cherry picking and monitoring commits.

Thanks

**Comment by untouchable** [comment]
Previously it worked fine with py37-iocage. But, right now after installing py38-iocage with pkg on FreeBSD 12.2-RELEASE-p6 I get just this.

```~ $ iocage
Usage: iocage [OPTIONS] COMMAND [ARGS]...

  A jail manager.

Options:
  -v, --version  Display iocage's version and exit.
  -f, --force    Allow iocage to rename datasets.
  -D, --debug    Log debug output to the console.
  --help         Show this message and exit.

Commands:
  migrate  Migrate all iocage_legacy develop basejails to new clonejails.
```

PS: A proper release would be great and surely merit a few cases of beer!

**Comment by mvanbaak** [comment]
@untouchable Yes, this has been reported to the FreeBSD port maintainer and already fixed:
https://bugs.freebsd.org/bugzilla/show_bug.cgi?id=255544

But a proper release ... Yes please

**Comment by nathanjrobertson** [comment]
I've been hand patching with patches from master for a while waiting for a release. I got sick of breakage from updates coming from ports (with some patches, but not others that I needed), so I locked the package from being updated. Not ideal.

Please could we have a release soon.

**Comment by stratacast** [comment]
Is there a good alternative to iocage?

**Comment by mvanbaak** [comment]
> Is there a good alternative to iocage?

There are a couple of alternatives yeah. Just run a duckduckgo search for 'freebsd jail management' and it will show you a bunch of them.
But since this is iocage, this is not the place to advertise them or anything.

What would help is an official statement from the maintainer(s) of iocage. Are they still supporting the FreeBSD community? or is this becoming an internal tool for freenas? What is the vision on the future of this project?

I'm starting to think the lack of interaction here from them is probably already an answer and shows that a fork that is actually active is the only way forward.

**Comment by kmoore134** [comment]
From the iX  side, we do not have ownership of iocage proper, we do use it in TrueNAS and contribute fixes back, but don't handle stand-alone releases or issues outside of using it in the FreeNAS/TrueNAS context.

**Comment by skarekrow** [comment]
From my side I just haven't had time. IRL have taken priorities for now. I'd love for somebody to step up to be a maintainer of this, I'd rather not let it rot or fork. But I just don't have the time right now. We have a couple guys who have submitted some great PR's, but I'm not sure if they'd be interested in shepherding iocage into the future.

**Comment by mvanbaak** [comment]
Thank you very much for answering. Basically this is what I was after with this issue to start with.
I mean, 'is there an eta?' 'no' <--- this is also a very valid answer!

I totally understand the time issue. We all have this problem. And specially the last 1.5 years have not been easy on any of us.

I totally agree with @skarekrow that rot or fork is the last option to consider, and if this can be avoided, it should be avoided.

I'll be here waiting patiently for the (new or current) maintainer(s) to have time to focus on it again. For the time being it is good to know that the intention is to continue, but that it's just a time issue.

**Comment by imp1sh** [comment]
Plz don't let iocage die, I love that tool.

**Comment by sporkman** [comment]
Please don't make MWL have to write a new edition of "FreeBSD Mastery: Jails" that showcases another jail management tool.

**Comment by munixsoft** [comment]
History repeating ;-) https://www.reddit.com/r/freebsd/comments/4fddvz/were_you_using_iocage_what_are_you_doing_now/

iocage already died once.
