### ISSUE TITLE
"No such command" after upgrade from py37-iocage to py38-iocage via ports

### ISSUE THREAD

**Issue by andros-ua** [iocage/iocage#1256]
- [x]  Supply `iocage --version`
`Version 1.2`

`FreeBSD 13.0-RELEASE amd64`
- [x] Supply the commands used, along with any steps to recreate it.
upgrade from py37-iocage to py38-iocage via ports
`iocage list`
`iocage --help`
- [x] Provide the output from the command you issued.
`Error: No such command 'list'.`
` `
`Commands:`
`  migrate  Migrate all iocage_legacy develop basejails to new clonejails.`

- [x] Supply what you expected the result or output to be
List of my jails and all commands in place.
- [ ] Checked that the problem has not already been fixed on `master` if using
 a stable release.

**Comment by Quux-NL** [comment]
Idem. Would really like a fix for this one (soon) since I thought it was really stable recently and use it on a production system... :-)

I'm still running FreeBSD 12.2, and just updated to Python 3.8, but this problem also occurred while running Python 3.7.

**Comment by olgeni** [comment]
Same here with 12.2 and 3.7 👀

**Comment by Quux-NL** [comment]
If you have not changed to Python 3.8 yet, you could fix this by removing the current version and installing the previous version, which should still be stored in /var/cache/pkg, using pkg add <packagename.txz>. You should sanity check the sanity afterwards by running pkg check -d and pkg check -B.

**Comment by Quux-NL** [comment]
Fixed by adding the following lines to /usr/ports/sysutils/iocage/Makefile

               ${PYTHON_PKGNAMEPREFIX}jsonschema>0:devel/py-jsonschema@${PY_FLAVOR} \
               ${PYTHON_PKGNAMEPREFIX}typing-extensions>0:devel/py-typing-extensions@${PY_FLAVOR} \

Just before the line:

                merge:devel/rcs57

See https://forums.freebsd.org/threads/iocage-all-subcommands-are-gone-after-upgraded-to-13-0-release.80151/ for more detailed instructions.

**Comment by olgeni** [comment]
> Fixed by adding the following lines to /usr/ports/sysutils/iocage/Makefile

Just committed a quick fix on the port 👀
