### ISSUE TITLE
document ftpfiles option for fetch?

### ISSUE THREAD

**Issue by robertbarabas** [iocage/iocage#126]
Would others be interested to see ftpfiles as a documented as an argument to iocage fetch?  

According to the documentation this is the current interface is:
```
fetch [release=RELEASE | ftphost=ftp.hostname.org | ftpdir=/dir/ ]
```
However, ftpfiles seems to be a viable override. 
```
$ grep -A2 fetch /usr/local/lib/iocage/ioc-cmd
            fetch)      __export_props "$@"
                        __fetch_release
                        exit
                ;;
```
The reason why this might be worth documenting and exposing as a feature is that for instance the 32 bit libraries (lib32.txz) are included by default in fetch/ftpfiles, however, perhaps not everyone wants to use them:
```
$ grep ^ftpfiles /usr/local/lib/iocage/ioc-globals
ftpfiles="base.txz doc.txz lib32.txz src.txz"
```
(I only noticed because we do have a custom release that excludes the 32 bit libs)

**Comment by pr1ntf** [comment]
:+1: I'm playing with some fetch stuff today as well.

**Comment by cactus** [comment]
I asked a similar question as part of #121, but it sounded like it was an intentional choice to not make it configurable -- likely so as to not break updating, as there have been a few issues with freebsd update and missing trees in the past.

**Comment by skarekrow** [comment]
@cactus yes but this is suggesting his own ftpfiles directory. Which if the user decides to do, would be fine. The default should still fetch what it needs too.

**Comment by cactus** [comment]
Thanks for clarifying @skarekrow.

**Comment by pannon** [comment]
@robertbarabas I think this is a good idea, if you have something already scripted up just make a PR or I can look at implementing this.

**Comment by robertbarabas** [comment]
It seems to work without modification. I just pass ftpfiles="..." and it works.

% grep ftpfiles roles/jailhost/tasks/release.yml
  shell: echo | iocage fetch release="{{ iocage.release }}" ftphost="{{ iocage.ftphost }}" ftpfiles="{{ iocage.ftpfiles }}"

% grep ftpfiles roles/jailhost/defaults/main.yml
  ftpfiles: "base.txz doc.txz src.txz"

**Comment by pannon** [comment]
Ah nice! So we just need to document it.
