### ISSUE TITLE
Not able to use IOcage name in jexec 

### ISSUE THREAD

**Issue by wjwithagen** [iocage/iocage#1275]
Lots of toosl in FreeBSD are able to execute and work in a jail from the Host environment.
`pkg` is such an example, also the ansible `pkgng` version understands that.
So by creating jail `bar` it is posible to user that name in the `pkgng` to load packages in the created jail.

BUT IOcage does not maintain a relation between the activated jail and the name that is registered with the regular tools.
Trying to fix that with `jail -m jid=<nr> name=<jailname>` fixes that for `jexec <jailname>` or `pkg -j <jailname>`.
THe IOcage tools then see the jail being downed, and the jail is no longer manageble with IOcage tools.

Is it possible to maintain coherency between what IOcage thinks and what is usuable for the regular jail tools??

```
root@zfstest:/usr/jails # iocage --version
Version 1.2
```
First we create an iocage jail
```
# iocage create -n bar -r 12.2-RELEASE
bar successfully created!
# iocage set "ip4_addr=re0|192.168.10.14/24" bar
ip4_addr: none -> re0|192.168.10.14/24
# iocage list
+-----+------+-------+--------------+---------------+
| JID | NAME | STATE |   RELEASE    |      IP4      |
+=====+======+=======+==============+===============+
| -   | bar  | down  | 12.2-RELEASE | 192.168.10.14 |
+-----+------+-------+--------------+---------------+
# jls
   JID  IP Address      Hostname                      Path
     1  192.168.11.78   ceph-ggate                    /usr/jails/ceph-ggate
# iocage start bar
* Starting bar
  + Started OK
  + Using devfs_ruleset: 1002 (iocage generated default)
  + Using IP options: ip4.addr=re0|192.168.10.14/24 ip4.saddrsel=1 ip4=new ip6.saddrsel=1 ip6=new
  + Starting services OK
  + Executing poststart OK
# jls
   JID  IP Address      Hostname                      Path
     4  192.168.10.14   bar                           /zroot/iocage/jails/bar/root
```
It works and is available.
But it cannot be used by name with the regular FreeBSD commands.
```
# jexec bar ls
jexec: jail "bar" not found
```
So we try to fix that:
```
# jail -m jid=`jls | grep bar | awk '{print $1}'` name=bar
# jexec bar ls
.cshrc          bin             etc             media           proc            sbin            usr
.profile        boot            lib             mnt             rescue          sys             var
COPYRIGHT       dev             libexec         net             root            tmp
# jexec 4 ls
.cshrc          bin             etc             media           proc            sbin            usr
.profile        boot            lib             mnt             rescue          sys             var
COPYRIGHT       dev             libexec         net             root            tmp
```
So the fix worked, but has some strange effects in the IOcage registration.
The bar jail seemingly has gone down??
```
# iocage list
+-----+------+-------+--------------+---------------+
| JID | NAME | STATE |   RELEASE    |      IP4      |
+=====+======+=======+==============+===============+
| -   | bar  | down  | 12.2-RELEASE | 192.168.10.14 |
+-----+------+-------+--------------+---------------+
 # iocage exec bar ls
bar is not running! Please supply --force (-f) or start the jail
```
But in reality it is still up:
```
# jls
   JID  IP Address      Hostname                      Path
     4  192.168.10.14   bar                           /zroot/iocage/jails/bar/root
# jexec bar ls
.cshrc          bin             etc             media           proc            sbin            usr
.profile        boot            lib             mnt             rescue          sys             var
COPYRIGHT       dev             libexec         net             root            tmp
```
Make sure to follow and check these boxes before submitting an issue! Thank you.

- [X] Supply `iocage --version`
- [X] Supply the commands used, along with any steps to recreate it.
- [X] Provide the output from the command you issued.
- [X] Supply what you expected the result or output to be
- [x] Checked that the problem has not already been fixed on `master` if using
 a stable release.

**Comment by freultwah** [comment]
Have you tried `jexec ioc-bar ls`?

**Comment by wjwithagen** [comment]
> Have you tried `jexec ioc-bar ls`?

No, I had not. That works.
But I then I guess that is sort of a hidden gem?

**Comment by freultwah** [comment]
I discovered it with `jls -v`. It also comes up in https://github.com/iocage/iocage/issues/1010

**Comment by wjwithagen** [comment]
Oke, thanx for pointing this out.
Need to read up on the `jls` options, i guess...
