### ISSUE TITLE
iocage fetch -r LATEST: 'LATEST' is not recognized

### ISSUE THREAD

**Issue by jhfoo** [iocage/iocage#1281]
Make sure to follow and check these boxes before submitting an issue! Thank you.

- [X] Supply `iocage --version`
```
%sudo iocage --version                                
Version 1.2
```
- [X] Supply the commands used, along with any steps to recreate it.
```
%sudo iocage fetch -r LATEST                          
```
- [X] Provide the output from the command you issued.
```
Please supply a valid entry.
```
- [X] Supply what you expected the result or output to be
Automatically fetches 13.1-RELEASE
- [X] Checked that the problem has not already been fixed on `master` if using
 a stable release.
Not reported since.

**Comment by tpltnt** [comment]
The documentation e.g. [basic usage](https://iocage.readthedocs.io/en/latest/basic-use.html) describes the expected behavior. I consider this a bug.

**Comment by germel** [comment]
I think it's a fluke. I've tried it on two servers and both worked, so my guess is it might have been something transient.

**Comment by jhfoo** [comment]
Feel free to close if it cannot be replicated.
