### ISSUE TITLE
Last Accepted Pull Reqest was Oct 2021

### ISSUE THREAD

**Issue by PythonLinks** [iocage/iocage#1289]
It makes this project look dead.  But in fact there were two pull requests in Sept 2022, and a few others in the last year all ignored. 

Is there any way to resurrect this project?  To get someone reviewing pull requests.  I would really like to use it.   Bastille looks more alive, but they are based on a NAT model.  Vutr.com gives multiple IPV6 addresses, and so this project, with multiple public ip addresses,  looks better for that use case.

**Comment by kmoore134** [comment]
From the iX side we no longer actively collaborate on this project. Don't believe other members are active as well though. We've mostly moved on to working directly on Linux native containers / Apps on TrueNAS.

**Comment by centromere** [comment]
@kmoore134 Are you planning on moving away from FreeBSD entirely? :(

**Comment by kmoore134** [comment]
For Apps / Plugin / VM workloads our recommendation is to use TrueNAS SCALE / Linux, it'll provide a much better experience overall.

For basic storage functionality (iSCSI/NFS/SMB) using CORE is perfectly fine :)

**Comment by PythonLinks** [comment]
I am very happy with Bastille BSD.  Here is a comparison with Docker

https://forestwiki.com/bastille-vs-docker

**Comment by jhgit** [comment]
> I am very happy with Bastille BSD. Here is a comparison with Docker
> 
> https://forestwiki.com/bastille-vs-docker

The link is currently https://forestwiki.com/bastillebsd-vs-docker

**Comment by nathanjrobertson** [comment]
See Issue #1251 - I'd say the project is dead, sadly. Quite a number of users, no maintainers.

There's not only a few open PRs, there's actually quite a large difference between the most recent released version and what's in `master` (ie. merged but unreleased updates). Some of these have been pulled in by the FreeBSD package maintainer (ie. cherry picked), but most have not.

**Comment by igalic** [comment]
So far, there's no viable fork.
and no viable drop-in replacement\*

so i think it's time people either start thinking about creating a fork, or migrating to an alternative that is actually alive and well

___________
\*I'm of the co-authors of (lib)ioc, which is also dead.

**Comment by sporkman** [comment]
Oof. I don't know much at all about python, but is there any gruntwork to be done on a project like this? Like testing out pulls, creating releases, etc. that a noob could do? I use IOC all over the place and for the most part it continues to "just work" - it seems like even a fork that just includes fixes for any issues brought on by underlying OS changes would be worthwhile.

The alternatives out there are OK, but none quite match up to this. I know Bastille was mentioned, but that feels more Docker-y (which is fine if that's what you want, but not everyone wants that).

**Comment by PythonLinks** [comment]
I am really happy with Bastille, and was quite unhappy with Docker. 
Docker is for large organizations, one person creates a container.  
Bastille is more for small organizations.  Both the original developer and I run a number of containers, with different things in them.   He, of course has a lot more of them, running on a lot more servers. 

Check it out.  I run very happily on Freebsd, on vultr.com.   I get a large stack of private IPV4 addresses, one for each bastile container.  Easy.

**Comment by william-gr** [comment]
A fork is not necessary. Anybody willing to do the work can be one of the owners of this project.

**Comment by skarekrow** [comment]
As I mentioned [here](https://github.com/iocage/iocage/issues/1251#issuecomment-854186775) , myself and @pannon also do not have the time to maintain this anymore. 

I’m open to somebody taking over as maintainer, anybody interested can email me at brandon (at) iocage.io

- Brandon
