### ISSUE TITLE
May I help ?

### ISSUE THREAD

**Issue by dgeo** [iocage/iocage#1296]
Using iocage here for years, may I help maintaining this ?
I see there is work to do, and I may work on this some hours per month…

Cheers,

Geoffroy

**Comment by pannon** [comment]
Hi Geoffroy, absolutely. What do you need to get started? Perhaps we could discuss outside this thread also if required.

**Comment by bravesirrobin81** [comment]
I can also offer some help. 

Leigh

**Comment by dgeo** [comment]
First i'd like some clarifications about roadmap and project's sponsoring from truenas (is it still used ant maintained by paid devs ?)
Then, I could help testing/integrating PR's here ?

**Comment by skarekrow** [comment]
@dgeo I haven't worked for iX for going on 4 years, we haven't had any communication about sponsoring the project. They are essentially running a fork of it at this point.

Help there would be greatly appreciated! We have rot in terms of a new release hasn't been cut for some time and lot's of PR's that need testing to be merged.

**Comment by sporkman** [comment]
So iX is running a private branch and not sharing? Is that correct?

**Comment by kmoore134** [comment]
We have a forked branch, (https://github.com/truenas/iocage) but these days we are not doing anything with Jails / Plugins on BSD anymore.

**Comment by skarekrow** [comment]
No, I'm not saying they won't share (it's open source) I'm just saying the relationship of opening pr's or merging the two forks changes is not happening, for a couple reasons as Kris mentions. They aren't doing anything with it anymore, I haven't had the time to do anything with this repo.

**Comment by dgeo** [comment]
Thank you both :)
We use iocage intensively here, and I may use some hours testing and merging PR's here

**Comment by dgeo** [comment]
Another wish would to make a new release available in ports (last release is far away !)

**Comment by dgeo** [comment]
So may I be part of iocage project ? I'd really love it to look a bit more alive ;)

**Comment by dgeo** [comment]
something blocking ? I'd love not to fork, but I think some people need more reactivity on this code

**Comment by arrowd** [comment]
As an another iocage user I'd love to see some movement on this.

**Comment by pannon** [comment]
@dgeo I would just fork it if I were you.

**Comment by arrowd** [comment]
If we decide to fork, we can look into forking into freebsd/iocage

**Comment by dgeo** [comment]
@arrowd I'd vote for that too :)

**Comment by arrowd** [comment]
> @dgeo I haven't worked for iX for going on 4 years, we haven't had any communication about sponsoring the project. They are essentially running a fork of it at this point.
> 
> Help there would be greatly appreciated! We have rot in terms of a new release hasn't been cut for some time and lot's of PR's that need testing to be merged.

@skarekrow So, is there any chance to avoid forking? Can you give push access to @dgeo ?

**Comment by arrowd** [comment]
The fork has been created at https://github.com/freebsd/iocage and @dgeo has been given maintainer rights for it.
