### ISSUE TITLE
iocage fetch performs download even if the release has been downloaded previously

### ISSUE THREAD

**Issue by woodsb02** [iocage/iocage#13]
iocage fetch re-downloads release files which have been downloaded previously.

I believe it would be better if it kept a copy of the previously downloaded release files, and skipped the download if they match the right filesize and checksum.

**Comment by skarekrow** [comment]
We actually already do that in the `/iocage/downloads/RELEASE` dataset. The logic hasn't been added yet to skip downloading if they exist. On my TODO :)

**Comment by skarekrow** [comment]
Alright all done, please test! 👍
