### ISSUE TITLE
List proppery one proppery for all jails

### ISSUE THREAD

**Issue by penetal** [iocage/iocage#130]
Could we have a way to list a property for all jails?
```
iocage get ip4_addr all
```
Could maybe return something like:
```
JID      UUID                                    TAG        ip4_addr
1        40335836-1cd4-11e5-8b8c-001e6758d14f    alpha      vnet0|10.0.0.1
2        6d8faa9d-0c73-11e5-8b8c-001e6758d14f    beta       vnet0|10.0.0.2
```

**Comment by pannon** [comment]
@penetal there is already a `show` subcommand for this.

`iocage show ip4_addr`

**Comment by skarekrow** [comment]
@pannon We don't have jid and TAG's being shown in the output though. I think we should add TAG atleast, jid isn't as relevant as this can show non-running jails too.
