### ISSUE TITLE
Changing a jails tag does not change it's /iocage/tags entry.

### ISSUE THREAD

**Issue by pr1ntf** [iocage/iocage#132]
In develop, changing a jail's tag property does not changes it's entry in the /iocage/tags directory. 

See below:

    root@DeltaFlyer:~ # iocage create tag=buttstag
    Configuring jail..
    ** interfaces=vnet0:bridge0,vnet1:bridge1
    ** vnet=off
    ** host_hostname=c76fa1f7-212b-11e5-baf2-002590c724d6
    ** hostname=c76fa1f7-212b-11e5-baf2-002590c724d6
    [etc etc etc...]
    root@DeltaFlyer:~ # ls /iocage/tags/
    2015-07-02@17:52:01     buttstag
    root@DeltaFlyer:~ # iocage set tag=butts c7
    root@DeltaFlyer:~ # iocage list
    JID   UUID                                  BOOT  STATE  TAG
    -     55390cd2-2115-11e5-baf2-002590c724d6  off   down   xzzyzx.xyz
    -     c76fa1f7-212b-11e5-baf2-002590c724d6  off   down   butts
    root@DeltaFlyer:~ # ls /iocage/tags/
    2015-07-02@17:52:01     buttstag
    root@DeltaFlyer:~ # iocage start buttstag
      ERROR: buttstag not found
    root@DeltaFlyer:~ # iocage start butts
    * Starting c76fa1f7-212b-11e5-baf2-002590c724d6 (butts)
      + Started (shared IP mode) OK
      + Starting services        OK
    root@DeltaFlyer:~ #

**Comment by skarekrow** [comment]
I can't replicate this. I assume that's because you were setting the ```tag=butts``` to the ```c7``` jail and not the ```buttstag``` jail.

**Comment by pr1ntf** [comment]
If utilizing a built in feature of iocage (UUID shortening) breaks the renaming, isn't that bad?
Will test what I tried above on another machine.

**Comment by pr1ntf** [comment]
Still have the same issue when not using UUID. 

    iocage set tag=butts buttstag

**Comment by skarekrow** [comment]
The issue did not occur for me with setting a tag on a tag but it did setting a new tag on a uuid. Reopening.
