### ISSUE TITLE
Update vs upgrade?

### ISSUE THREAD

**Issue by cconrad** [iocage/iocage#134]
Hi,

sorry for what is probably a stupid question, but I wanted to ask what
the  difference  between  the  "updating"  and  "upgrading"  of  jails
mentioned here is?
https://iocage.readthedocs.org/en/latest/advanced-use.html

By the way, the link to the mailing list "iocage@googlegroups.com" in the README does not work.

Thanks,
Claus

**Comment by pr1ntf** [comment]
No such thing as a stupid question. :wink:  From what I gather in the man page, update will update the jail to the latest patch level, kind of like freebsd-update. Upgrade will upgrade a jail to the host's release level, like from 9.3 -> 10.1. @pannon or @skarekrow would you like to elaborate more?

**Comment by skarekrow** [comment]
@cconrad Hello :)

@pr1ntf has nailed it in a nutshell. Our terminology is identical to freebsd-update's, which is what we use. (https://www.freebsd.org/cgi/man.cgi?freebsd-update(8))

**Comment by cconrad** [comment]
Thanks! :)
