### ISSUE TITLE
replace git shell commands with git library

### ISSUE THREAD

**Issue by gronke** [iocage/iocage#134]
I'd like to use a git library instead of forking processes and parsing stdout for git commands.

Is there any preference on the third-party library that can be used? Promising candidates are for example:
- https://github.com/gitpython-developers/GitPython
- https://github.com/libgit2/pygit2

**Comment by skarekrow** [comment]
I'd love to as well. No preference but GitPython seems like it might be dead? Or was? On phone and I'm not able to see commits for some reason currently. 

If GitPython wasn't dead I'd prefer it since it has a BSD license. I haven't checked ports for either of these either. So that may be a factor as well.

**Comment by gronke** [comment]
GitPython still has frequent commits - think that's a good sign. Will start with that library and in case we figure out it was the wrong choice, a migration should be straightforward.

**Comment by skarekrow** [comment]
Alright good! The blurb at the bottom in the README is what worried me :D
But hey if it's active, fantastic! The less subprocess I can use the better. There's a few more instances I can think of to replace right now but they're lower priority. 

For the curious, we can use py-bsd and py-netif to some effect right now. With some jail bindings added to the former we could essentially rip out all the subprocess calls. Or that's what my memory tells me. I'm usually wrong.

**Comment by skarekrow** [comment]
#136 has started to improve this courtesy of @gronke
