### ISSUE TITLE
Changing tag on a jail does not rename or add a symlink under iocage/tags

### ISSUE THREAD

**Issue by ramijebara** [iocage/iocage#135]
When changing the tag on a Jail, the tag is changed in the attributes but the symlink in the /iocage/tags is not renamed nor does it add a new symlink for the tag.

OS: 10.1-RELEASE-p14
iocage version: 1.6.2 installed with pkg

**Comment by pr1ntf** [comment]
Looks like this has been addressed in #132 where @skarekrow pushed a fix to the develop branch.

**Comment by ramijebara** [comment]
Thanks!
