### ISSUE TITLE
iocage create missing dnsresolver=8.8.8.8 setting

### ISSUE THREAD

**Issue by xmj** [iocage/iocage#136]
Hi,

working on [fractal cells](http://www.fractalcells.com) I've noticed that `iocage create` currently misses an option for setting a jail's dns server as specified in `/etc/resolv.conf` to arbitrary values.

Personally, I'm looking to set up a jail host that runs local_unbound, and with that I would like to specify the nameserver to be something like `10.1.0.1` in /etc/resolv.conf for all jails, and `127.0.0.1` for the host.

I'll gladly help testing once we have a -dev port in `FreeBSD ports`. :)

**Comment by pannon** [comment]
Resolved in https://github.com/iocage/iocage/commit/e634b5c07e53c15515df0b1acf1540991c8b16cb
