### ISSUE TITLE
Update timezone of jail

### ISSUE THREAD

**Issue by manfredu** [iocage/iocage#139]
It would be a good idea to copy /etc/localtime from the host when a jail is created. And maybe even update it on restart? Currently the jails use UTC independent from what the host is using.

**Comment by skarekrow** [comment]
I'm thinking a property called `host_time` and the user can set `on` or `off`. Setting to `on` will copy the `/etc/localtime` from the host on start and restart. Would that solve your usecase?

**Comment by manfredu** [comment]
Yes, that sounds good. Thanks! 

Am 15.05.2017 10:51, schrieb Brandon Schneider: 

> I'm thinking a property called host_time and the user can set true orfalse. Setting totruewill copy the/etc/localtime` from the host one tart and restart. Would that solve your usecase?

**Comment by skarekrow** [comment]
This is also implemented, please test and report back 👍

**Comment by manfredu** [comment]
Hi Brandon, 

I will, could you please let me know, when the changes are included with
FreeNAS 11 nightlies? 

Thanks
Manfred 

Am 16.05.2017 20:54, schrieb Brandon Schneider: 

> This is also implemented, please test and report back 👍 
> 
> --
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub [1], or mute the thread [2].

 

Links:
------
[1] https://github.com/iocage/iocage/issues/139#issuecomment-301880130
[2]

**Comment by skarekrow** [comment]
@manfredu It should be there now :)

Enjoy!

**Comment by kairu0** [comment]
Is this working with iocage 0.9.8.1? I have set host_time to "no" but my guest goes back to the host's timezone when I restart the jail.

Host is 11.1-RELEASE.
Jail was 11.0-RELEASE, had the problem, upgraded to 11.1-RELEASE, and still have the problem.
