### ISSUE TITLE
iocage destroy doesn't work in an automation context

### ISSUE THREAD

**Issue by xmj** [iocage/iocage#140]
I've been creating and destroying jails a lot today.

Here's what I noticed:

`iocage destroy -f $UUID` does not do anything, regardless of jailtype and whether there were any dependent datasets cloned off it, or not

`yes | iocage destroy $UUID` does not work, because yes gives a 'y' but not a "Y" I think.

I'm not sure where to find those two, otherwise I'd attach a patch.

I'll gladly help with testing!

**Comment by skarekrow** [comment]
This shouldn't be an issue in develop. Can you try that?

**Comment by skarekrow** [comment]
If develop doesn't solve your problem, please reopen :)

**Comment by xmj** [comment]
yes | iocage destroy $UUID does not work, because yes gives a 'y' but not a "Y" I think.

^^ still doesn't work, I think.

**Comment by skarekrow** [comment]
Test develop please. That should work there.

**Comment by xmj** [comment]
paging @kmoore134  for a new freebsd -devel release :-)
