### ISSUE TITLE
Need help! Can not make install!

### ISSUE THREAD

**Issue by ajschot** [iocage/iocage#141]
I tried to install the new iocage, but it won't work!

```
[root@fn11 /usr/src]# make install                                              
make: don't know how to make install. Stop                                      
                                                                                
make: stopped in /usr/src                                                       
[root@fn11 /usr/src]# 
```

Can somebody help me? i am logged in as root and am woring in /usr/src

**Comment by skarekrow** [comment]
You don't do make install in `/usr/src` you do it in the cloned directory of iocage. It requires the sources to be available as it builds a module that requires it.
