### ISSUE TITLE
iocage create does not add the jail's hostname to /etc/hosts

### ISSUE THREAD

**Issue by xmj** [iocage/iocage#144]
Creating a jail via iocage clone, the `/etc/hosts` file is left untouched.
This has the side effect of causing bugs with e.g. opensmtpd, cf this one:
https://github.com/OpenSMTPD/OpenSMTPD/issues/617

If it's trivial and easy to do, could you consider adding the jail's hostname (uuid) to the jail's  /etc/hosts ?

**Comment by pannon** [comment]
@xmj you just want a line with primary IP and UUID?

**Comment by xmj** [comment]
The one assigned to the interface on the host, and uuid, would be nice yep

**Comment by pannon** [comment]
@xmj I would rather leave this decision to the end user than iocage itself. Some might prefer it this way some might do their own abstraction - there is quite a few scenarios, options, variables, use cases with hosts records.

**Comment by skarekrow** [comment]
Agreed, closing this for now. If you still have other discussion that might change our POV xmj, please reopen :)
