### ISSUE TITLE
git2.h not found when building from source

### ISSUE THREAD

**Issue by ghost** [iocage/iocage#145]
Make sure to follow and check these boxes before submitting an issue! Thank you.

- [ ] Supply `iocage --version`
Git HEAD - not installed yet
- [ ] Supply the commands used, along with any steps to recreate it.
`sudo make install`
- [ ] Provide the output from the command you issues.
```
Installing collected packages: pygit2, iocage
  Running setup.py install for pygit2 ... error
    Complete output from command /usr/local/bin/python3.6 -u -c "import setuptools, tokenize;__file__='/tmp/pip-build-87d1buzc/pygit2/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-ook5v7op-record/install-record.txt --single-version-externally-managed --compile:
    running install
    running build
    running build_py
    creating build
    creating build/lib.freebsd-11.0-RELEASE-p1-amd64-3.6
    creating build/lib.freebsd-11.0-RELEASE-p1-amd64-3.6/pygit2
    copying pygit2/remote.py -> build/lib.freebsd-11.0-RELEASE-p1-amd64-3.6/pygit2
    copying pygit2/settings.py -> build/lib.freebsd-11.0-RELEASE-p1-amd64-3.6/pygit2
    copying pygit2/ffi.py -> build/lib.freebsd-11.0-RELEASE-p1-amd64-3.6/pygit2
    copying pygit2/credentials.py -> build/lib.freebsd-11.0-RELEASE-p1-amd64-3.6/pygit2
    copying pygit2/blame.py -> build/lib.freebsd-11.0-RELEASE-p1-amd64-3.6/pygit2
    copying pygit2/index.py -> build/lib.freebsd-11.0-RELEASE-p1-amd64-3.6/pygit2
    copying pygit2/py3.py -> build/lib.freebsd-11.0-RELEASE-p1-amd64-3.6/pygit2
    copying pygit2/_build.py -> build/lib.freebsd-11.0-RELEASE-p1-amd64-3.6/pygit2
    copying pygit2/utils.py -> build/lib.freebsd-11.0-RELEASE-p1-amd64-3.6/pygit2
    copying pygit2/errors.py -> build/lib.freebsd-11.0-RELEASE-p1-amd64-3.6/pygit2
    copying pygit2/_run.py -> build/lib.freebsd-11.0-RELEASE-p1-amd64-3.6/pygit2
    copying pygit2/py2.py -> build/lib.freebsd-11.0-RELEASE-p1-amd64-3.6/pygit2
    copying pygit2/config.py -> build/lib.freebsd-11.0-RELEASE-p1-amd64-3.6/pygit2
    copying pygit2/repository.py -> build/lib.freebsd-11.0-RELEASE-p1-amd64-3.6/pygit2
    copying pygit2/refspec.py -> build/lib.freebsd-11.0-RELEASE-p1-amd64-3.6/pygit2
    copying pygit2/__init__.py -> build/lib.freebsd-11.0-RELEASE-p1-amd64-3.6/pygit2
    copying pygit2/submodule.py -> build/lib.freebsd-11.0-RELEASE-p1-amd64-3.6/pygit2
    copying pygit2/decl.h -> build/lib.freebsd-11.0-RELEASE-p1-amd64-3.6/pygit2
    running build_ext
    generating cffi module 'build/temp.freebsd-11.0-RELEASE-p1-amd64-3.6/pygit2._libgit2.c'
    creating build/temp.freebsd-11.0-RELEASE-p1-amd64-3.6
    building '_pygit2' extension
    creating build/temp.freebsd-11.0-RELEASE-p1-amd64-3.6/src
    cc -Wno-unused-result -Wsign-compare -Wunreachable-code -DNDEBUG -O2 -pipe -fstack-protector -fno-strict-aliasing -fPIC -I/usr/local/include -I/usr/local/include/python3.6m -c src/blob.c -o build/temp.freebsd-11.0-RELEASE-p1-amd64-3.6/src/blob.o
    In file included from src/blob.c:30:
    src/blob.h:33:10: fatal error: 'git2.h' file not found
    #include <git2.h>
             ^
    1 error generated.
    error: command 'cc' failed with exit status 1

    ----------------------------------------
Command "/usr/local/bin/python3.6 -u -c "import setuptools, tokenize;__file__='/tmp/pip-build-87d1buzc/pygit2/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-ook5v7op-record/install-record.txt --single-version-externally-managed --compile" failed with error code 1 in /tmp/pip-build-87d1buzc/pygit2/
*** Error code 1

Stop.
make: stopped in /root/src/iocage
```

`libgit2` needs to be listed as a dependency.

**Comment by skarekrow** [comment]
Bah totally spaced that! Thanks, it's been fixed.

**Comment by kitten77** [comment]
root@firestar:/home/muad/iocage # make install .
echo -e "import os\ntry:\n  if not os.listdir('/usr/src'): exit('/usr/src must be populated!')\nexcept FileNotFoundError:\n  exit('/usr/src must be populated!')" | python3.6
git pull
Already up-to-date.
python3.6 -m ensurepip
Requirement already satisfied: setuptools in /usr/local/lib/python3.6/site-packages
Requirement already satisfied: pip in /usr/local/lib/python3.6/site-packages
pip3.6 install -U Cython
Requirement already up-to-date: Cython in /usr/local/lib/python3.6/site-packages
cd py-libzfs && python3.6 setup.py build && python3.6 setup.py install
running build
running build_py
running build_ext
skipping 'libzfs.c' Cython extension (up-to-date)
running install
running build
running build_py
running build_ext
skipping 'libzfs.c' Cython extension (up-to-date)
running install_lib
running install_egg_info
Removing /usr/local/lib/python3.6/site-packages/libzfs-1.0-py3.6.egg-info
Writing /usr/local/lib/python3.6/site-packages/libzfs-1.0-py3.6.egg-info
pip3.6 install -U .
Processing /usr/home/muad/iocage
Requirement already up-to-date: click in /usr/local/lib/python3.6/site-packages (from iocage==0.9.9a0)
Requirement already up-to-date: texttable in /usr/local/lib/python3.6/site-packages (from iocage==0.9.9a0)
Requirement already up-to-date: requests in /usr/local/lib/python3.6/site-packages (from iocage==0.9.9a0)
Requirement already up-to-date: tqdm in /usr/local/lib/python3.6/site-packages (from iocage==0.9.9a0)
Requirement already up-to-date: coloredlogs in /usr/local/lib/python3.6/site-packages (from iocage==0.9.9a0)
Collecting pygit2>=0.24.2 (from iocage==0.9.9a0)
  Using cached pygit2-0.25.1.tar.gz
Requirement already up-to-date: libzfs in /usr/local/lib/python3.6/site-packages (from iocage==0.9.9a0)
Requirement already up-to-date: idna<2.6,>=2.5 in /usr/local/lib/python3.6/site-packages (from requests->iocage==0.9.9a0)
Requirement already up-to-date: chardet<3.1.0,>=3.0.2 in /usr/local/lib/python3.6/site-packages (from requests->iocage==0.9.9a0)
Requirement already up-to-date: urllib3<1.22,>=1.21.1 in /usr/local/lib/python3.6/site-packages (from requests->iocage==0.9.9a0)
Requirement already up-to-date: certifi>=2017.4.17 in /usr/local/lib/python3.6/site-packages (from requests->iocage==0.9.9a0)
Requirement already up-to-date: humanfriendly>=3.2 in /usr/local/lib/python3.6/site-packages (from coloredlogs->iocage==0.9.9a0)
Requirement already up-to-date: cffi<1.10 in /usr/local/lib/python3.6/site-packages (from pygit2>=0.24.2->iocage==0.9.9a0)
Requirement already up-to-date: six in /usr/local/lib/python3.6/site-packages (from pygit2>=0.24.2->iocage==0.9.9a0)
Requirement already up-to-date: pycparser in /usr/local/lib/python3.6/site-packages (from cffi<1.10->pygit2>=0.24.2->iocage==0.9.9a0)
Installing collected packages: pygit2, iocage
  Running setup.py install for pygit2 ... error
    Complete output from command /usr/local/bin/python3.6 -u -c "import setuptools, tokenize;__file__='/tmp/pip-build-6mgdsuhj/pygit2/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-anu2e8yd-record/install-record.txt --single-version-externally-managed --compile:
    running install
    running build
    running build_py
    creating build
    creating build/lib.freebsd-11.0-RELEASE-p6-amd64-3.6
    creating build/lib.freebsd-11.0-RELEASE-p6-amd64-3.6/pygit2
    copying pygit2/py2.py -> build/lib.freebsd-11.0-RELEASE-p6-amd64-3.6/pygit2
    copying pygit2/py3.py -> build/lib.freebsd-11.0-RELEASE-p6-amd64-3.6/pygit2
    copying pygit2/config.py -> build/lib.freebsd-11.0-RELEASE-p6-amd64-3.6/pygit2
    copying pygit2/repository.py -> build/lib.freebsd-11.0-RELEASE-p6-amd64-3.6/pygit2
    copying pygit2/submodule.py -> build/lib.freebsd-11.0-RELEASE-p6-amd64-3.6/pygit2
    copying pygit2/ffi.py -> build/lib.freebsd-11.0-RELEASE-p6-amd64-3.6/pygit2
    copying pygit2/index.py -> build/lib.freebsd-11.0-RELEASE-p6-amd64-3.6/pygit2
    copying pygit2/refspec.py -> build/lib.freebsd-11.0-RELEASE-p6-amd64-3.6/pygit2
    copying pygit2/_build.py -> build/lib.freebsd-11.0-RELEASE-p6-amd64-3.6/pygit2
    copying pygit2/errors.py -> build/lib.freebsd-11.0-RELEASE-p6-amd64-3.6/pygit2
    copying pygit2/blame.py -> build/lib.freebsd-11.0-RELEASE-p6-amd64-3.6/pygit2
    copying pygit2/remote.py -> build/lib.freebsd-11.0-RELEASE-p6-amd64-3.6/pygit2
    copying pygit2/_run.py -> build/lib.freebsd-11.0-RELEASE-p6-amd64-3.6/pygit2
   copying pygit2/__init__.py -> build/lib.freebsd-11.0-RELEASE-p6-amd64-3.6/pygit2
    copying pygit2/credentials.py -> build/lib.freebsd-11.0-RELEASE-p6-amd64-3.6/pygit2
    copying pygit2/utils.py -> build/lib.freebsd-11.0-RELEASE-p6-amd64-3.6/pygit2
    copying pygit2/settings.py -> build/lib.freebsd-11.0-RELEASE-p6-amd64-3.6/pygit2
    copying pygit2/decl.h -> build/lib.freebsd-11.0-RELEASE-p6-amd64-3.6/pygit2
    running build_ext
    generating cffi module 'build/temp.freebsd-11.0-RELEASE-p6-amd64-3.6/pygit2._libgit2.c'
    creating build/temp.freebsd-11.0-RELEASE-p6-amd64-3.6
    building '_pygit2' extension
    creating build/temp.freebsd-11.0-RELEASE-p6-amd64-3.6/src
    cc -Wno-unused-result -Wsign-compare -Wunreachable-code -DNDEBUG -O2 -pipe -fstack-protector -fno-strict-aliasing -fPIC -I/usr/local/include -I/usr/local/include/python3.6m -c src/blob.c -o build/temp.freebsd-11.0-RELEASE-p6-amd64-3.6/src/blob.o
    In file included from src/blob.c:30:
    src/blob.h:33:10: fatal error: 'git2.h' file not found
    #include <git2.h>
             ^
    1 error generated.
    error: command 'cc' failed with exit status 1
    
    ----------------------------------------
Command "/usr/local/bin/python3.6 -u -c "import setuptools, tokenize;__file__='/tmp/pip-build-6mgdsuhj/pygit2/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-anu2e8yd-record/install-record.txt --single-version-externally-managed --compile" failed with error code 1 in /tmp/pip-build-6mgdsuhj/pygit2/
*** Error code 1

Stop.
make: stopped in /usr/home/muad/iocage

Freebsd 11.0-RELEASE i think it is the same

**Comment by skarekrow** [comment]
Yep same error @kitten77 just install that package he listed above and you should be good to go.
