### ISSUE TITLE
some potential ideas to simplify __find_mypool

### ISSUE THREAD

**Issue by cactus** [iocage/iocage#145]
I had two different ideas to that might possibly simplify __find_mypool a bit.

1. Changing the code for __find_mypool to something like this:

    ```
__find_mypool () {
    local _mypool

    _mypool="$(zpool get -H -o name,value comment | \
               awk '{if (index($2,"iocage")){print $1;exit;}}')"

    if [ -z "$_mypool" ] ; then
        if [ -n "$RC_PID" ]; then
            # RC_PID set means we are running from rc
            echo "ERROR: No pool for iocage jails found on boot ..exiting"
        else
            echo "No zpool configured for iocage..."
            echo "If you wish to configure a zpool, use 'iocage activate'"
        fi
        exit 1
    fi
    export pool=$_mypool
}
    ```

     This might be a bit faster than the current mechanism of listing all zpools then individually walking them to find one with a comment set. In addition, this would allow other things in the comment, as long as "iocage" was present. Things like `comment=iocage;pickles;bacon` should still work.

2. Use `sysrc -i -n iocage_zpool` and require the user to set `iocage_zpool` in rc.conf. This would go against the "no configuration files" ethos a bit. This might be acceptable since there is already iocage_enable for starting on boot though? Unsure. The two main benefits here are: a) if a user had many many pools, the code wouldn't have to iterate over them and the pool would just be known right away; b) If multiple pools are somehow accidentally marked as comment=iocage, Right now the first one (alphabetically) would be chosen. 

    ```
__find_mypool () {
    local _mypool

    _mypool="$(sysrc -i -n iocage_zpool)"

    if [ -z "$_mypool" ] ; then
        if [ -n "$RC_PID" ]; then
            # RC_PID set means we are running from rc
            echo "ERROR: No pool for iocage jails found on boot ..exiting"
            exit 1
        else
            echo "No zpool configured for iocage..."
            echo "If you wish to configure a zpool, set iocage_zpool to the desired pool in rc.conf"
            exit 1
        fi
    fi
    export pool=$_mypool
}
    ```

Feel free to write both ideas off as crazy as well. I won't take it personally.
:)

**Comment by skarekrow** [comment]
We talked about this and we both feel that it isn't very important. The current method is fast and I don't believe many people use so many zpools that walking it is not fast. Appreciate the idea though.

**Comment by cactus** [comment]
no problem. :)
