### ISSUE TITLE
Mac prefix error with vnet

### ISSUE THREAD

**Issue by telser** [iocage/iocage#148]
I seem to be getting an error about mac the mac prefix when creating/starting a vnet jail. Below are the traceback, /etc/rc.conf, and ifconfig output. 

- [x] Supply `iocage --version`
`Version 0.9.8 BETA` (built from head around 16:00 UTC 18th May)
- [x] Supply the commands used, along with any steps to recreate it.

> iocage create -t pkg_template tag="vnet.test" ip4_addr="vnet0|192.168.2.45" defaultrouter="192.168.2.1" host_hostname="vnet.test" vnet="on" boot="on"

- [x] Provide the output from the command you issues.

> Traceback (most recent call last):
  File "/usr/local/bin/iocage", line 10, in <module>
    sys.exit(cli())
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/iocage/cli/exec.py", line 67, in cli
    jail_user).exec_jail()
  File "/usr/local/lib/python3.6/site-packages/iocage/lib/ioc_exec.py", line 51, in exec_jail
    silent=True)
  File "/usr/local/lib/python3.6/site-packages/iocage/lib/ioc_start.py", line 35, in __init__
    self.__start_jail__()
  File "/usr/local/lib/python3.6/site-packages/iocage/lib/ioc_start.py", line 274, in __start_jail__
    self.start_network(vnet)
  File "/usr/local/lib/python3.6/site-packages/iocage/lib/ioc_start.py", line 370, in start_network
    self.start_network_interface_vnet(nic, net_configs, jid)
  File "/usr/local/lib/python3.6/site-packages/iocage/lib/ioc_start.py", line 409, in start_network_in
terface_vnet
    membermtu, jid)
  File "/usr/local/lib/python3.6/site-packages/iocage/lib/ioc_start.py", line 434, in start_network_vn
et_iface
    mac_a, mac_b = self.__start_generate_vnet_mac__(nic)
  File "/usr/local/lib/python3.6/site-packages/iocage/lib/ioc_start.py", line 547, in __start_generate
_vnet_mac__
    mac = _conf["mac_prefix"]
KeyError: 'mac_prefix'

From /etc/rc.conf

>  cat /etc/rc.conf
clear_tmp_enable="YES"
hostname="$SOME_HOST"
ifconfig_bce0="inet $SOME_IP netmask 255.255.255.0"
defaultrouter="$ANOTHER_IP"
sshd_enable="YES"
moused_enable="YES"
ntpd_enable="YES"
powerd_enable="YES"
dumpdev="AUTO"
zfs_enable="YES"
cloned_interfaces="lo1 bridge0"
gateway_enable="YES"
pf_enable="YES"
nginx_enable="YES"
iocage_enable="YES"
accounting_enable="YES"
clamav_freshclam_enable="YES"
clamav_clamd_enable="YES"
ifconfig_bridge0="addm bce0 up"

There are a few unused interfaces on the system so they've been excluded for brevity

>  ifconfig
bce0: flags=8943<UP,BROADCAST,RUNNING,PROMISC,SIMPLEX,MULTICAST> metric 0 mtu 1500
        options=c01bb<RXCSUM,TXCSUM,VLAN_MTU,VLAN_HWTAGGING,JUMBO_MTU,VLAN_HWCSUM,TSO4,VLAN_HWTSO,LINK
STATE>
        ether 44:1e:a1:5f:9f:04
        inet $SOME_IP netmask 0xffffff00 broadcast $BROADCAST_IP
        inet $ALIAS_IP netmask 0xffffffff broadcast $BROADCAST_IP
        inet 192.168.0.30 netmask 0xffffff00 broadcast 192.168.0.255
        nd6 options=29<PERFORMNUD,IFDISABLED,AUTO_LINKLOCAL>
        media: Ethernet autoselect (1000baseT <full-duplex>)
        status: active
lo0: flags=8049<UP,LOOPBACK,RUNNING,MULTICAST> metric 0 mtu 16384
        options=600003<RXCSUM,TXCSUM,RXCSUM_IPV6,TXCSUM_IPV6>
        inet6 ::1 prefixlen 128
        inet6 fe80::1%lo0 prefixlen 64 scopeid 0x5
        inet 127.0.0.1 netmask 0xff000000
        nd6 options=21<PERFORMNUD,AUTO_LINKLOCAL>
        groups: lo
lo1: flags=8008<LOOPBACK,MULTICAST> metric 0 mtu 16384
        options=600003<RXCSUM,TXCSUM,RXCSUM_IPV6,TXCSUM_IPV6>
        nd6 options=29<PERFORMNUD,IFDISABLED,AUTO_LINKLOCAL>
        groups: lo
bridge0: flags=8843<UP,BROADCAST,RUNNING,SIMPLEX,MULTICAST> metric 0 mtu 1500
        description: iohyve-bridge
        ether 02:47:54:e4:65:00
        nd6 options=1<PERFORMNUD>
        groups: bridge
        id 00:00:00:00:00:00 priority 32768 hellotime 2 fwddelay 15
        maxage 20 holdcnt 6 proto rstp maxaddr 2000 timeout 1200 
        root id 00:00:00:00:00:00 priority 32768 ifcost 0 port 0 
        member: bce0 flags=143<LEARNING,DISCOVER,AUTOEDGE,AUTOPTP>
                ifmaxaddr 0 port 1 priority 128 path cost 20000

Oh and I compiled the kernel with the option from the README, but if it helps I can get the diff from the GENERIC kernel and include that.

Presumably, I'm just doing something dumb here, thoughts?

**Comment by skarekrow** [comment]
What does `iocage get all vnet.test` return?

**Comment by telser** [comment]
Thanks for the quick reply.

It's pretty long, but here it goes

> CONFIG_VERSION:6
allow_chflags:0
allow_mount:0
allow_mount_devfs:0
allow_mount_nullfs:0
allow_mount_procfs:0
allow_mount_tmpfs:0
allow_mount_zfs:0
allow_quotas:0
allow_raw_sockets:0
allow_set_hostname:1
allow_socket_af:0
allow_sysvipc:0
available:readonly
basejail:no
boot:off
bpf:off
children_max:0
cloned_release:11.0-RELEASE
comment:none
compression:lz4
compressratio:readonly
coredumpsize:off
count:1
cpuset:off
cputime:off
datasize:off
dedup:off
defaultrouter:192.168.2.1
defaultrouter6:none
devfs_ruleset:4
dhcp:off
enforce_statfs:2
exec_clean:1
exec_fib:0
exec_jail_user:root
exec_poststart:/usr/bin/true
exec_poststop:/usr/bin/true
exec_prestart:/usr/bin/true
exec_prestop:/usr/bin/true
exec_start:/bin/sh /etc/rc
exec_stop:/bin/sh /etc/rc.shutdown
exec_system_jail_user:0
exec_system_user:root
exec_timeout:60
host_domainname:none
host_hostname:vnet.test
host_hostuuid:a7094e81-d340-4712-a8c9-e885f68d8e89
host_time:yes
hostid:32393735-3733-5355-4531-35314e584d50
interfaces:vnet0:bridge0
ip4:new
ip4_addr:vnet0|192.168.2.45
ip4_saddrsel:1
ip6:new
ip6_addr:none
ip6_saddrsel:1
jail_zfs:off
jail_zfs_dataset:iocage/jails/a7094e81-d340-4712-a8c9-e885f68d8e89/data
jail_zfs_mountpoint:none
last_started:none
login_flags:-f root
mac_prefix:02ff60
maxproc:off
memorylocked:off
memoryuse:off
mount_devfs:1
mount_fdescfs:1
mount_linprocfs:0
mount_procfs:0
mountpoint:readonly
msgqqueued:off
msgqsize:off
nmsgq:off
notes:none
nsemop:off
nshm:off
nthr:off
openfiles:off
origin:readonly
owner:root
pcpu:off
priority:99
pseudoterminals:off
quota:none
release:11.0-RELEASE-p5
reservation:none
resolver:/etc/resolv.conf
rlimits:off
securelevel:2
shmsize:off
stacksize:off
stop_timeout:30
swapuse:off
sync_state:none
sync_target:none
sync_tgt_zpool:none
sysvmsg:new
sysvsem:new
sysvshm:new
tag:vnet.test
template:no
type:jail
used:readonly
vmemoryuse:off
vnet:on
vnet0_mac:none
vnet1_mac:none
vnet2_mac:none
vnet3_mac:none
wallclock:off

**Comment by skarekrow** [comment]
Interesting, it throws a `KeyError` but you actually have the key. I'll do some digging here and see what's up, it used to work, maybe it regressed.

**Comment by skarekrow** [comment]
Hmm no still worked here:
```
root@iocage:~ # iocage create -r 11.0-RELEASE tag="test_mac" ip4_addr="vnet0|192.168.1.70" defaultrouter="192.168.1.1" host_hostname="vnet_mac" vnet="on" boot="on"
3af115a5-c588-4259-ad04-3f56647326cf (test_mac) successfully created!
* Starting 3af115a5-c588-4259-ad04-3f56647326cf (test_mac)
  + Started OK
  + Starting services OK
```

I wonder if it's template related, did you do anything specific with that you can remember?

**Comment by telser** [comment]
The template just switches the pkg repo to latest from quarterly. Got tired of doing that for every jail so I made the template. But just to be sure I changed the -t pkg_template to -r 11.0-RELEASE with the same result.

**Comment by skarekrow** [comment]
This is odd, I'd expect it to work looking at your configuration. I can throw a default value in there, but that's just masking the symptom. But in the interest of actually "solving" your issue, I'll do it and circle back to this if I ever figure out the root cause.

**Comment by telser** [comment]
Oh wow, okay thank you very much!

**Comment by skarekrow** [comment]
Thank you! Please test and make sure this solves it and something else fun doesn't fail further down. This little thing could be indicative of some other exotic issue I haven't thought about yet. 👍

**Comment by telser** [comment]
That solved it, thanks again!

**Comment by skarekrow** [comment]
That's good and bad news :D But glad it got you going.
