### ISSUE TITLE
Iocage should default to using one of fetched releases instead of OSVERSION

### ISSUE THREAD

**Issue by bartekrutkowski** [iocage/iocage#149]
I've noticed while testing iocage on latest 10-STABLE that happened to be 10.2-BETA2 currently, that iocage, even when only one release was fetched using `iocage fetch` (10.1-RELEASE in this case) doesnt try to default to it nor even propose available choices, but instead defaults to host OSVERSION, like that:

```
root@hub:~ # uname -r
10.2-BETA2
root@hub:~ # iocage create tag=test
  ERROR: Release 10.2-BETA2 not found locally, run fetch first.
root@hub:~ # iocage create release=10.1-RELEASE tag=test
** interfaces=vnet0:bridge0,vnet1:bridge1
[ ... output snipped ...]
** reservation=none
cat: /etc/resolv.conf: No such file or directory
root@hub:~ #
```

**Comment by pannon** [comment]
@bartekrutkowski iocage assumes the same RELEASE as the OS at creation, if you want to override this please specify the `release="10.1-RELEASE"` property.

**Comment by bartekrutkowski** [comment]
@pannon I am aware that this is the behaviour that can be overriden, but since iocage already defaults to -RELEASE OS versions for `iocage fetch` then it would make more sense for it to then default to what it already have fetched, instead of assuming its OSVERSION (because often its not).

**Comment by pannon** [comment]
What if you have multiple releases fetched or have custom releases - where do you default then?

**Comment by bartekrutkowski** [comment]
Just as with the `iocage fetch` I would expect the same behaviour to default to a list of available downloaded releases, with proposed the latest one available. Since you can't really download -STABLE or -CURRENT releases, it doesnt really make sense to default to host OSVERSION, because very often it will be -STABLE (people need to rebuild their kernel to get VNET goodies anyway).

**Comment by pannon** [comment]
I think the script is pretty specific on what the problem is `ERROR: Release 10.2-BETA2 not found locally, run fetch first.` - it could be clearer however and just list your available releases and tell you to rerun the command with the `release` property.

This could be done with minimal coding - In my opinion much better solution than listing releases and wait for an interactive selection, especially in the age of automation with Ansible/Salt/Puppet/etc.

Would you be OK with that?

**Comment by skarekrow** [comment]
Commit 850033e solves this in an automated fashion. If you don't want to run a RELEASE, then please specify the release for iocage. Compiling your kernel for VNET does not mean you have to run STABLE.
