### ISSUE TITLE
The data dataset isn't created in a new jail 

### ISSUE THREAD

**Issue by No9** [iocage/iocage#149]
Hi Again 
Pulled down todays revision and found the following issue 
FWIW I am using a zpool I have created instead of the default installed on with FreeBSD. 
Other than that everything else is the usual stuff. 
- [x] Supply `iocage --version`
Hi Again 
I pulled down the latest today and came across this issue. 

`Version 0.9.9 ALPHA`
- [x] Supply the commands used, along with any steps to recreate it.
` iocage create tag=gw -r 11.0-RELEASE`
`iocage list`
- [x] Provide the output from the command you issued.
```
 Traceback (most recent call last):
  File "/usr/local/bin/iocage", line 10, in <module>
    sys.exit(cli())
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/iocage/cli/set.py", line 22, in cli
    jails, paths = ioc_list.IOCList("uuid").list_datasets(set=True)
  File "/usr/local/lib/python3.6/site-packages/iocage/lib/ioc_list.py", line 53, in list_datasets
    conf = iocage.lib.ioc_json.IOCJson(jail).json_load()
  File "/usr/local/lib/python3.6/site-packages/iocage/lib/ioc_json.py", line 236, in json_load
    self.json_convert_from_zfs(uuid, skip=skip)
  File "/usr/local/lib/python3.6/site-packages/iocage/lib/ioc_json.py", line 106, in json_convert_from_zfs
    self.zfs_set_property(f"{dataset}/root/data", "jailed", "off")
  File "/usr/local/lib/python3.6/site-packages/iocage/lib/ioc_json.py", line 132, in zfs_set_property
    ds = self._zfs_get_properties(identifier)
  File "/usr/local/lib/python3.6/site-packages/iocage/lib/ioc_json.py", line 119, in _zfs_get_properties
    dataset = self.zfs.get_dataset(identifier)
  File "libzfs.pyx", line 566, in libzfs.ZFS.get_dataset (libzfs.c:18784)
libzfs.ZFSException: Dataset dozer/iocage/jails/af6d7a5a-b5be-4b4c-83a4-265155599aee/root/data not found
```
- [x] Supply what you expected the result or output to be
The newly created jail in down mode. 
Looks like the `data` dataset isn't being created
```
# df
Filesystem                                                    1K-blocks    Used      Avail Capacity  Mounted on
/dev/gpt/rootfs                                                20307196 5733720   12948904    31%    /
devfs                                                                 1       1          0   100%    /dev
dozer                                                        1007243457      19 1007243438     0%    /dozer
dozer/iocage                                                 1007243459      21 1007243438     0%    /iocage
dozer/iocage/download                                        1007243457      19 1007243438     0%    /iocage/download
dozer/iocage/images                                          1007243457      19 1007243438     0%    /iocage/images
dozer/iocage/jails                                           1007243457      19 1007243438     0%    /iocage/jails
dozer/iocage/log                                             1007243457      19 1007243438     0%    /iocage/log
dozer/iocage/releases                                        1007243457      19 1007243438     0%    /iocage/releases
dozer/iocage/templates                                       1007243457      19 1007243438     0%    /iocage/templates
dozer/iocage/download/11.0-RELEASE                           1007357487  114049 1007243438     0%    /iocage/download/11.0-RELEASE
dozer/iocage/releases/11.0-RELEASE                           1007243457      19 1007243438     0%    /iocage/releases/11.0-RELEASE
dozer/iocage/releases/11.0-RELEASE/root                      1007567079  323641 1007243438     0%    /iocage/releases/11.0-RELEASE/root
dozer/iocage/jails/af6d7a5a-b5be-4b4c-83a4-265155599aee      1007243457      19 1007243438     0%    /iocage/jails/af6d7a5a-b5be-4b4c-83a4-265155599aee
dozer/iocage/jails/af6d7a5a-b5be-4b4c-83a4-265155599aee/root 1007567079  323641 1007243438     0%    /iocage/jails/af6d7a5a-b5be-4b4c-83a4-265155599aee/root
```
- [x] Checked that the problem has not already been fixed on `master` if using
 a stable release.
Test performed on https://github.com/iocage/iocage/commit/200bb01ffde1a09d38ff750776b84a510df7ef25

**Comment by No9** [comment]
I reran this tonight and can't recreate ??? 
`# df` still does not show the `/dozer/iocage/jails/af6d7a5a-b5be-4b4c-83a4-265155599aee/root/data` folder but the error is not thrown
However I now have two additional lines which were not in the previous output
```
devfs                                                                        1       1          0   100%    /iocage/jails/69b5ece8-b4f3-462f-950b-0ef64997228c/root/dev
fdescfs                                                                      1       1          0   100%    /iocage/jails/69b5ece8-b4f3-462f-950b-0ef64997228c/root/dev/fd
```
Not quite sure why they are appearing as my ZFS foo isn't that good but this may be an error at my end.
Happy to close this if you are

**Comment by skarekrow** [comment]
Is that jail running? 

No you didn't do anything wrong! I ran across this as well last week but wasn't able to recreate it with identical steps. So I was in the same situation you are now.

I figured it was an artifact of all my testing of various changes, but since you hit the same bug I'm going to see if I can recreate it and get it properly fixed. 

Thanks for the bug!

**Comment by No9** [comment]
Yes the jail is running fine no issues at all 
Glad that you have hit the problem too and this has some use. 
FWIW I am using a virtualbox VM

**Comment by gronke** [comment]
Seems the dataset `<UUID>/root/data` does not exist when the `jailed` property is attempted to be set. 

The change was introduced in https://github.com/iocage/iocage/pull/137/files#diff-195933281e8aa34ad4090bec9c8bbd97R100, but I can't spot the difference to the previous implementation.

Would the correct behavior to check if the dataset exists before setting the property and renaming it one line later?

**Comment by skarekrow** [comment]
The behavioral difference is your change will now raise an exception, whereas before we didn't care the status of the commands. Just like we don't now. I don't see the need to spend more time checking if the dataset exists, it either does or doesn't. Either way is fine as we create them later on when required.

So I did the simple fix on this 👍
