### ISSUE TITLE
iocage breaks FreeBSD

### ISSUE THREAD

**Issue by walkr** [iocage/iocage#150]
Hello,

I'm using iocage compiled from sources on FreeBSD 11.0.

Upon setting the ip property on the jail, when I try to start the jail, the start operation will just hang and cause the system to misbehave. 

- [ ] Supply `iocage --version`

- [x] Supply the commands used, along with any steps to recreate it.

```shell
# Set ip
$ iocage set ip4_addr="vtnet0|my-public-ip" webapp

# Start
$ iocage start webapp
```

- [x] Provide the output from the command you issued.
```shell
# System hangs
```
- [x] Supply what you expected the result or output to be
Should start jail

- [x] Checked that the problem has not already been fixed on `master` if using
 a stable release.

**Comment by skarekrow** [comment]
You can't use the same IP as the system ;)

By doing so you will lose connectivity. Use a different IP address.

**Comment by walkr** [comment]
@skarekrow Okay! Thank you for your timely response!

**Comment by skarekrow** [comment]
No problem!
