### ISSUE TITLE
Unable to set systemwide defaults

### ISSUE THREAD

**Issue by johnramsden** [iocage/iocage#151]
- [x] iocage version: (Version 0.9.5 2017/02/15)
- [x] Supply the commands used, along with any steps to recreate it.
- [x] Provide the output from the command you issued.
- [x] Supply what you expected the result or output to be
- [ ] Checked that the problem has not already been fixed on `master` if using
 a stable release.

---

The [man page](https://www.freebsd.org/cgi/man.cgi?query=iocage&sektion=8) states that defaults can be set in the format `iocage set vnet=off default`. While I remember this working on the old shell script version, after installing the Python2.7 package, the command no longer worked for me.

```
iocage set vnet=off default
default not found!
```

```
iocage defaults
Usage: iocage [OPTIONS] COMMAND [ARGS]...

Error: No such command "defaults".
```
So either the documentation is wrong, or there is a bug. 

Before installing the new version, I ran iocage clean, and completely uninstalled the old version  removing all traces of iocage.

**Comment by skarekrow** [comment]
The python 2.7 version is incredibly old at this point, remember this is a beta ;)

Upgrade to the latest 0.9.8.1 from GitHub or wait for the port (py3-iocage not py27-iocage) to see an update. 

That being said, the documentation is just wrong. I haven't had time to go through the docs and clean them up properly. I'll mark this as an enhancement, as I'd like to port this behavior. But currently defaults for all jails are not configurable.

**Comment by johnramsden** [comment]
Oh, that's too bad. I don't like mixing ports and packages so I guess I'll either build from github or use this opportunity to set up a Pourdiere build machine. In the meantime other than the docs being wrong is there any reason I shouldn't be using the version I am currently? I realize it's beta but are there any serious deficiencies you know of the version I'm currently using?

By the way I'm a huge fan of iocage, keep up the good work!

**Comment by skarekrow** [comment]
There are many. There's been a tremendous amount of change since :)

Way too many to remember off the top of my head, but feel free to check the releases page, I try to keep the changelog thorough. 

Thanks for the kind words :+1: and a poudriere is always good for the soul ;)

**Comment by johnramsden** [comment]
@skarekrow I don't know if it's related to any bugs you might;ve fixed before, but jailed zfs datasets don't seem to be mounting properly.

I'm trying to mount: vault/data/jails/stratus/db with:

`iocage set jail_zfs_dataset='data/jails/stratus' stratus`

but in the jail it says the following when I try to mount it:

```
zfs set mountpoint=/var/db/mysql vault/data/jails/stratus
cannot open 'vault/data/jails/stratus': dataset does not exist
```

**Comment by skarekrow** [comment]
@johnramsden No that's working as intended. You haven't set `jail_zfs` to `on` ;)

**Comment by johnramsden** [comment]
No, I do have it on.

```
iocage get all stratus

openfiles:off
resolver:/etc/resolv.conf
nmsgq:off
memoryuse:8G:log
compressratio:readonly
allow_quotas:0
allow_mount_zfs:0
sync_tgt_zpool:none
istemplate:no
gitlocation:https://github.com
interfaces:vnet0:bridge0,vnet1:bridge1
login_flags:-f root
hostid:13757acc-3480-fba2-dc11-a3ab008ab736
ip4_autosubnet:none
bpf:off
notes:none
defaultrouter6:none
release:11.0-RELEASE-p10
nthr:off
coredumpsize:off
ip4_addr:sge0|172.20.0.100/32
allow_raw_sockets:0
allow_mount_tmpfs:0
ip4_autostart:none
exec_start:/bin/sh /etc/rc
allow_mount_procfs:0
mountpoint:readonly
sync_state:none
shmsize:off
dedup:off
jail_zfs_mountpoint:none
template:none
dhcp:off
hack88:0
available:readonly
pcpu:off
vmemoryuse:off
exec_clean:1
exec_prestop:/usr/bin/true
last_started:2017-05-27 06:47:50
exec_fib:0
allow_set_hostname:1
exec_system_jail_user:0
securelevel:2
allow_mount_devfs:0
origin:readonly
mount_fdescfs:1
allow_mount:0
rlimits:off
exec_system_user:root
reservation:none
owner:root
swapuse:off
compression:lz4
exec_poststart:mount lilan.ramsden.network:/mnt/tank/data/stratus/data /iocage/jails/030c5af2-a429-4e0e-b571-8c14c933f1c5/root/mnt/data; mount lilan.ramsden.network:/mnt/tank/data/syncthing/sync /iocage/jails/030c5af2-a429-4e0e-b571-8c14c933f1c5/root/mnt/sync
ip6_addr:none
exec_timeout:60
host_domainname:none
priority:99
maxproc:off
ip4_saddrsel:1
exec_stop:/bin/sh /etc/rc.shutdown
sysvmsg:new
stacksize:off
datasize:off
type:jail
allow_mount_nullfs:0
allow_chflags:0
cpuset:off
ipv6:off
allow_socket_af:0
ip6:new
ip4:new
sysvsem:new
mount_devfs:1
mount_procfs:0
count:1
memorylocked:off
host_hostuuid:030c5af2-a429-4e0e-b571-8c14c933f1c5
tag:stratus
mount_linprocfs:0
ip4_autoend:none
vnet0_mac:none
pseudoterminals:off
allow_sysvipc:0
cloned_release:11.0-RELEASE
vnet3_mac:none
mac_prefix:02ff60
jail_zfs:on
msgqsize:off
stop_timeout:30
nsemop:off
ip6_saddrsel:1
nshm:off
host_hostname:030c5af2-a429-4e0e-b571-8c14c933f1c5
boot:on
wallclock:off
sysvshm:new
exec_jail_user:root
used:readonly
defaultrouter:none
quota:none
exec_prestart:/usr/bin/true
enforce_statfs:2
jail_zfs_dataset:data/jails/stratus
cputime:off
exec_poststop:umount /iocage/jails/030c5af2-a429-4e0e-b571-8c14c933f1c5/root/mnt/data; umount /iocage/jails/030c5af2-a429-4e0e-b571-8c14c933f1c5/root/mnt/sync
CONFIG_VERSION:3
children_max:0
sync_target:none
vnet1_mac:none
msgqqueued:off
vnet2_mac:none
vnet:off
devfs_ruleset:4
```

**Comment by skarekrow** [comment]
Ok open a new issue so I can track it separately.

**Comment by skarekrow** [comment]
@johnramsden so if you update to the latest GitHub, you will find this feature is now present. Please test and report back 👍

**Comment by johnramsden** [comment]
Awesome! Thanks @skarekrow !
