### ISSUE TITLE
iocage's rc.d script doesn't start the jails properly

### ISSUE THREAD

**Issue by xmj** [iocage/iocage#151]
Upon server reboot, iocage's rc.d script takes care of starting the jails when `boot==on`.

However, I noticed that the jails so started do not have any IP addresses on the `lo1` device.

This makes running any daemon listening to TCP/IP ports inside the jails (especially those with fixed IP address listens) a bit of a futile exercise.

I can 'fix' everything by stopping every jail, and restarting them manually.

And having everything work properly on boot would be nice. :-)

**Comment by pannon** [comment]
@xmj some additional details like `iocage version` and relevant section from rc.conf would be helpful.

I have tested this and works with  `iocage 1.6.7 (2015/07/17)`.

My rc.conf:
```
cloned_interfaces="lo1"
```

After boot jails are up:
```
JID   UUID                                  BOOT  STATE  TAG
1     0ada9065-1f67-11e5-a33d-90b8d088c7a9  on    up     clone
2     3fc7542d-1f62-11e5-a33d-90b8d088c7a9  on    up     foo
```

IP config for jail named clone:
```
iocage get ip4_addr clone
lo1|10.1.1.1/24
```

IP config for jail foo
```
iocage get ip4_addr foo
lo1|10.1.1.2/24
```

ifconfig on host showing both IP's assigned to lo1:
```
ifconfig lo1
lo1: flags=8049<UP,LOOPBACK,RUNNING,MULTICAST> metric 0 mtu 16384
	options=600003<RXCSUM,TXCSUM,RXCSUM_IPV6,TXCSUM_IPV6>
	inet 10.1.1.1 netmask 0xffffff00 
	inet 10.1.1.2 netmask 0xffffff00 
	nd6 options=29<PERFORMNUD,IFDISABLED,AUTO_LINKLOCAL>
```

Jail clone can see its 10.1.1.1:
```
iocage exec clone ifconfig lo1
lo1: flags=8049<UP,LOOPBACK,RUNNING,MULTICAST> metric 0 mtu 16384
	options=600003<RXCSUM,TXCSUM,RXCSUM_IPV6,TXCSUM_IPV6>
	inet 10.1.1.1 netmask 0xffffff00
```

Jail clone can see its 10.1.1.2:
```
iocage exec foo ifconfig lo1
lo1: flags=8049<UP,LOOPBACK,RUNNING,MULTICAST> metric 0 mtu 16384
	options=600003<RXCSUM,TXCSUM,RXCSUM_IPV6,TXCSUM_IPV6>
	inet 10.1.1.2 netmask 0xffffff00
```

Please try with latest develop branch version and report back. For now I am closing this.
