### ISSUE TITLE
Milestone for 1.0

### ISSUE THREAD

**Issue by gronke** [iocage/iocage#155]
Hey @skarekrow, I wonder if you want to create a Milestone for the 1.0 release.

In my opinion the following achievements are necessary to call out a stable release:
- Automated Integration Tests on HardenedBSD and FreeBSD
- Full migration from forked ZFS commands to libzfs
- Basejail Upgrades/Migration #50

**Comment by skarekrow** [comment]
Hmm I thought I already did. But yeah those are the exact features I want done for 1.0. Resource control is going to be 0.9.9 and a complete API.

**Comment by skarekrow** [comment]
Ok so I added these to the milestone, will close the issue

**Comment by gronke** [comment]
Sorry, my fault. Obviously there was the 1.0 Milestone already.
