### ISSUE TITLE
Add support for encrypted jails

### ISSUE THREAD

**Issue by moviuro** [iocage/iocage#155]
Hi,

I know this sounds like a huge work to do (at least, it looks huge to me), but it might have some applications and would like to share with you. (And perhaps it won't even be this huge, given how easy it was to add `pkg`, see #153 )
### Why?
Because you have some (highly) sensitive stuff in one jail, e.g. it contains the root certificate of your CA.
### How?
Using `geli(8)` looks like the way to go
A new command must be used to create an encrypted jail (`iocage create -e`?) and the key must be stored somewhere (`/iocage/keys`?), then locked with a passphrase of the admin's choosing. (But I'm not familiar with device/partition/dataset encryption on FreeBSD).
Startup and shutdown will then require additional steps:
* startup
  * unlock the key,
  * decrypt the dataset,
  * continue startup as usual;
* stop
  * normal stop,
  * close the dataset.

That's it, folks.
Any input would be appreciated

**Comment by pannon** [comment]
@moviuro you can't use `geli(8)` to encrypt individual jails. `geli(8)` is for partition/disk encryption which is not possible with individual ZFS jails. You could however encrypt the whole disk underneath your zpool.

**Comment by moviuro** [comment]
@pannon oh, I thought you could encrypt a ZFS dataset :cry:

**Comment by pannon** [comment]
Not a dataset.., you could use PEFS but even then I don't see any benefit in jail encryption as your jails will need to be decrypted completely before you start them. For offsite backups you could export your jail and encrypt the image itself.
