### ISSUE TITLE
Feature Request: Fetch plugin using the "id" for it only

### ISSUE THREAD

**Issue by beanpole135** [iocage/iocage#158]
Please implement a new flag for the `iocage fetch` system whereby only the plugin ID may be used to fetch/install the plugin rather than requiring a path to a file within the iocage file heirarchy..

Example:
When remote plugins are listed you get something like this:
```
[0] GitLab - Powerful features for modern software development (gitlab)
```
Where the "(gitlab)" at the end refers to the "id" for that plugin ("gitlab" in this example).

I would like to be able to fetch a plugin with a syntax like this:
`iocage fetch -P --id gitlab ip4_addr="IF|IP"`
(or just skip the --id flag and scan/auto-complete the plugin file path as needed)

Rather than the current implementation which looks something like this:
`iocage fetch -P /iocage/.plugin_index/gitlab.json ip4_addr="IF|IP"`
Since the current implementation requires a lot more info about the internal placement of hidden files within the iocage file heirarchy (which most end-users will not know or care about). This should also make the implementation more forwards-compatible because it leaves the freedom to re-arrange the iocage file hierarchy around at a later date as needed without breaking the API.

**Comment by beanpole135** [comment]
Oh - that "ip4_addr=" syntax at the end of the commands needs to be added to the current documention for fetching plugins as well - right now you only find out about it by trying the syntax from the man page (or the --help text) and then seeing a warning/error and adjusting on the next try.

**Comment by skarekrow** [comment]
Also going to ping @Mrt134 so we can keep track of the next wave of doc updates.

**Comment by skarekrow** [comment]
I went with `--name` instead of `--id` as that syntactically made more sense to me, but this is now implemented, still requires doc changes.
