### ISSUE TITLE
iocage update <jail> don't work properly

### ISSUE THREAD

**Issue by bsduser** [iocage/iocage#159]
Hello
Example :
Host FreeBSD 10.1
Jail FreeBSD 9.3
iocage update jail
Jail is update from 10.1 snapshots ...

I've in every jail with 9.3 source I've uname -r 10.1-RELEASE-p16

Log from create a jail : 

/usr/home/mj # iocage create release=9.3-RELEASE tag=testw ip4_addr="lo1|172.20.20.1"
** interfaces=vnet0:bridge0,vnet1:bridge1
** vnet=off
** host_hostname=cde3cb79-402f-11e5-ab9a-0025907174f2
** hostname=cde3cb79-402f-11e5-ab9a-0025907174f2
** ip4_addr=lo1|172.20.20.1
** ip4_autostart=none
** ip4_autoend=none
** ip4_saddrsel=1
** ip4=new
** ip6_addr=none
** ip6_saddrsel=1
** ip6=new
** defaultrouter=none
** defaultrouter6=none
** resolver=none
** exec_fib=0
** vnet0_mac=none
** vnet1_mac=none
** vnet2_mac=none
** vnet3_mac=none
** devfs_ruleset=4
** mount_devfs=1
** exec_start=/bin/sh /etc/rc
** exec_stop=/bin/sh /etc/rc.shutdown
** exec_prestart=/usr/bin/true
** exec_prestop=/usr/bin/true
** exec_poststop=/usr/bin/true
** exec_poststart=/usr/bin/true
** exec_clean=1
** exec_timeout=60
** stop_timeout=30
** exec_jail_user=root
** exec_system_jail_user=0
** exec_system_user=root
** mount_fdescfs=1
** mount_procfs=0
** enforce_statfs=2
** children_max=0
** login_flags=-f root
** securelevel=2
** allow_set_hostname=0
** allow_sysvipc=0
** allow_raw_sockets=0
** allow_chflags=0
** allow_mount=0
** allow_mount_devfs=0
** allow_mount_nullfs=0
** allow_mount_procfs=0
** allow_mount_tmpfs=0
** allow_mount_zfs=0
** allow_quotas=0
** allow_socket_af=0
** host_hostuuid=cde3cb79-402f-11e5-ab9a-0025907174f2
** memoryuse=8G:log
** memorylocked=off
** vmemoryuse=off
** maxproc=off
** cputime=off
** pcpu=off
** datasize=off
** stacksize=off
** coredumpsize=off
** openfiles=off
** pseudoterminals=off
** swapuse=off
** nthr=off
** msgqqueued=off
** msgqsize=off
** nmsgq=off
** nsemop=off
** nshm=off
** shmsize=off
** wallclock=off
** tag=testw
** template=no
** rlimits=off
** boot=off
** notes=none
** owner=root
** priority=99
** last_started=none
** type=jail
** hostid=49434d53-0200-9071-2500-71902500f274
** cpuset=off
** jail_zfs=off
** jail_zfs_dataset=iocage/jails/cde3cb79-402f-11e5-ab9a-0025907174f2/root/data
** release=9.3-RELEASE
** hack88=0
** sync_target=none
** sync_tgt_zpool=none
** gitlocation=https://github.com
** compression=lz4
** quota=none
** dedup=off
** reservation=none

Update log :
iocage update testw
* Creating back-out snapshot.
* Updating jail..
Looking up update.FreeBSD.org mirrors... 5 mirrors found.
Fetching metadata signature for 10.1-RELEASE from update4.freebsd.org... done.
Fetching metadata index... done.
Fetching 2 metadata patches.. done.
Applying metadata patches... done.
Fetching 2 metadata files... done.
Inspecting system... done.
Preparing to download files... done.
Fetching 6 patches.... done.
Applying patches... done.
Fetching 1209 files...

pkg info -x iocage
iocage-devel-1.7.2

Regards

**Comment by skarekrow** [comment]
You're looking for `iocage upgrade`. :)

**Comment by bsduser** [comment]
Hey
I don't want upgrade my jail to 9.3 or 10.1, I want only get update for example FreeBSD 9.3-RELEASE
Something like : freebsd-update fetch insall (only security updates)
But now when I'm doing iocage update <jail with 9.3-RELASE> a fetch updates for FreeBSD 10.1 (because this is my host) 
Regards

**Comment by skarekrow** [comment]
Ah! I misunderstood. I see what you want to do now. Will fix this soon.
