### ISSUE TITLE
iocage missing manpage

### ISSUE THREAD

**Issue by woodsb02** [iocage/iocage#16]
After installing the new py-iocage, I wanted to check how the syntax matched iocage-legacy, so I went straight for "man iocage".

Unfortunately, no such man page exists yet.

**Comment by skarekrow** [comment]
This is more likely to be something the community will have to add as I simply don't have the time right now. There are features still missing, along with other things my job is requiring from me for this. `iocage COMMAND --help` is the best way to see syntax currently. Until a manpage can be created.

**Comment by jungle-boogie** [comment]
While a man page doesn't exist, there's some documentation here:
http://iocage.readthedocs.org/en/latest/index.html

That should be updated prior to a man page, IMO.

**Comment by drewja** [comment]
If someone could add the docs to the repo, I would be happy help with documentation.
As it is now when I try to contribute to these docs:
http://iocage.readthedocs.org/en/latest/index.html  the link to edit on github is broken.

**Comment by skarekrow** [comment]
Alright old docs have been fixed and put up here, that should allow the edit page to work. IIRC all you need to do is edit source/DOC.rst and it will automatically rebuild it on the RTD server.

**Comment by skarekrow** [comment]
So I'm going to close this as the excellent FreeNAS docs team (@dlavigne @wblock @Mrt134) will be handling a man page and a RTD Handbook :)
