### ISSUE TITLE
create -b does not create basejail or output of get type is wrong

### ISSUE THREAD

**Issue by cyb3rwr3ck** [iocage/iocage#161]
[x] 0.9.9-ALPHA
[x] iocage create tag=basejail_11_stable -b -r 11-STABLE
     iocage get type basejail_11_stable
[ x] Provide the output from the command you issued.
      b8685804-4b4b-4c4a-9432-bc2838f105ce (basejail_11_stable) successfully created!
      jail
[x ]  the `get type` command should state `basejail`. Either the jail created is a normal jail or the output of `get type` is wrong

**Comment by skarekrow** [comment]
Neither is correct, basejails are now noted by the property `basejail`. It does still work :)
