### ISSUE TITLE
unable to unset property (NIC driver name)

### ISSUE THREAD

**Issue by pcovello** [iocage/iocage#162]
When creating a jail, I accidently set an incorrect property (I set the ip address for bg0 when I meant bge0) so I retyped the command using bge0.  Now I have 2 nic properties set and the jail will not start due to bg0 not existing.  I am unable to clear this property so I will need to destroy the jail and re-create.

Perhaps as a feature request, have iocage refuse to set a property for a non existing device to prevent this?

**Comment by skarekrow** [comment]
Hello :)

You used the wrong command. Here I go through the order to fix a mistake, and verify it. I also start the jail to show that it does indeed function.

`brandon@micro:~ % sudo iocage create tag=test ip4_addr="bg0|192.168.1.205/24"`
`brandon@micro:~ % sudo iocage set ip4_addr="bge0|192.168.1.205/24" test`
`brandon@micro:~ % sudo iocage get ip4_addr test`
`bge0|192.168.1.205/24`
`brandon@micro:~ % sudo iocage start test`
`* Starting c7463f0d-432b-11e5-9d89-9cb654044df2 (test)`
`  + Started (shared IP mode) OK`
`  + Starting services        OK`
