### ISSUE TITLE
Can't update basejail using "iocage update <TAG>"

### ISSUE THREAD

**Issue by cyb3rwr3ck** [iocage/iocage#162]
[x] 0.9.9-ALPHA (HardenedBSD 11.1 PRERELEASE)
[x] iocage update basejail_11_stable
[x]tmp/tmp.UkfTTKVp/update.tar                  100% of  324 MB  893 kBps 06m12s
Warning: Could not find extra file script.sh.  Skipping validity checks for that file.
./lib/: Can't restore time
./rescue/: Can't restore time
./bin/: Can't restore time
./libexec/: Can't restore time
./sbin/: Can't restore time
./sbin/gcache: Can't unlink already-existing object
./sbin/rdump: Can't unlink already-existing object
./sbin/devfs: Can't unlink already-existing object
./sbin/ipfw: Can't unlink already-existing object
./sbin/gvinum: Can't unlink already-existing object
./sbin/ifconfig: Can't unlink already-existing object
./sbin/kldstat: Can't unlink already-existing object
[...] 

/lib/geom/geom_raid.so: Can't unlink already-existing object
./lib/geom/geom_part.so: Can't unlink already-existing object
./lib/geom/geom_mirror.so: Can't unlink already-existing object
./lib/geom/geom_raid3.so: Can't unlink already-existing object
./lib/geom/geom_journal.so: Can't unlink already-existing object
./lib/casper/libcap_grp.so.0: Can't unlink already-existing object
./lib/casper/libcap_sysctl.so.0: Can't unlink already-existing object
./lib/casper/libcap_dns.so.0: Can't unlink already-existing object
./lib/casper/libcap_pwd.so.0: Can't unlink already-existing object
./lib/casper/libcap_random.so.0: Can't unlink already-existing object
tar: Error exit delayed from previous errors.
#

[x] It is possible to upate jails created without -b without an problems. This should be the case for basejails too.

**Comment by skarekrow** [comment]
Please look for duplicates before filing issues, this is already noted in the [basejail features that aren't complete](https://github.com/iocage/iocage/issues/50).
