### ISSUE TITLE
ipfw breaks vnet jail networking

### ISSUE THREAD

**Issue by corv89** [iocage/iocage#166]
When I boot with ipfw enabled on the host, iocage vnet jails are unable to network.

*ping*, *fetch* and *host* fail within jails returning **sendto: Permission denied**

*nc 127.0.0.1 3232* is unable to connect to *nc -l 3232* within a jail although *lo0* appears to be up.

The problem persists after issuing *service ipfw stop* and when I remove *gateway_enable* and *natd_enable* from rc.conf

I've tried *firewall_type="open"* and *allow all from any to any* ipfw.rules.

I’ve already asked in the forums but haven’t been able to find a solution, the mailing list iocage@googlegroups.com doesn't let me post.

**Comment by pannon** [comment]
Make sure you test it with these tunables in `/etc/sysctl.conf`:

```
net.inet.ip.forwarding=1
net.link.bridge.pfil_onlyip=0
net.link.bridge.pfil_bridge=0
net.link.bridge.pfil_member=0
```

**Comment by corv89** [comment]
Thank you for your answer.

I've got these set in sysctl.conf:

net.inet.ip.fw.default_to_accept="1"
net.inet.ip.forwarding=1
net.link.bridge.pfil_onlyip=0
net.link.bridge.pfil_bridge=0
net.link.bridge.pfil_member=0

**Comment by pannon** [comment]
@corv89 could you share your ipfw config and rc.conf for both the jail and host?

Also an `iocage get all UUID` would be helpful.

**Comment by corv89** [comment]
Well, this is embarrassing. You just made me notice I forgot to open the firewall within the jail.

Thank you for your support.
