### ISSUE TITLE
Typo in export

### ISSUE THREAD

**Issue by Johanhen** [iocage/iocage#167]
In the file lib/ioc-image there is a typo.
This way it will tar the home dir of the user that invokes the command iocage export UUID

On line  200 in lib/ioc-image _mountpoint="$(__get-jail_prop mountpoint $_fulluuid)" must read
_mountpoint="$(__get_jail_prop mountpoint $_fulluuid)" 

the - must be a _ in get jail

regards
Johan

**Comment by skarekrow** [comment]
Thanks!

**Comment by skarekrow** [comment]
Next time you should send a PR, so your name gets shown in the commit history for fixing it. Plus, easier for all parties ;)

**Comment by Johanhen** [comment]
Ok I will do that in the future, I am not that well known with Github.

**Comment by skarekrow** [comment]
NP :)
