### ISSUE TITLE
iocage fetch: Release options shown are corrupted with -h for http

### ISSUE THREAD

**Issue by woodsb02** [iocage/iocage#167]
When running iocage fetch with the -h option, the available releases shown are corrupted. I would have expected options to be listed to have increases numerical options, and include 11.0-RELEASE.

iocage --version: Version 0.9.8.1 05/23/2017
```
# iocage fetch -h
[0] 1
[0] 1
[2] .
[3] 0

Which release do you want to fetch? (Not a RELEASE)
Type EXIT to quit: EXIT
```

**Comment by skarekrow** [comment]
Heh, must have changed again. Will fix next week
