### ISSUE TITLE
cannot mount datasets on different zfs pool

### ISSUE THREAD

**Issue by mlindgren80** [iocage/iocage#168]
If I try to specify a dataset that exists on a different dataset than what the jail is created on, it just prepends the original pool name to the command, eg

```bash
 iocage set jail_zfs_dataset=zfsraid2/data jail
```
tries to mount jail pool/zfsraid2/data

**Comment by skarekrow** [comment]
That is expected behavior.

https://github.com/iocage/iocage/blob/develop/lib/ioc-zfs#L234-L236. 

We don't support multiple pools yet.

**Comment by corv89** [comment]
I also ran into this problem. It's simple to workaround however.

In file ioc-rc on line 83 and 138 remove ${pool}/

Now jail_zfs_dataset will accept the full path including the zpool.

I would be happy to provide a PR that preserves default behavior if the owners are interested.

**Comment by skarekrow** [comment]
I'd be happy to review it @corv89 :)

**Comment by pannon** [comment]
We have a way to make this happen, will be committed soon.

**Comment by corv89** [comment]
Alright that's good to hear. I've been busy unfortunately.
