### ISSUE TITLE
iocage df does not show TAG column (1.7.1)

### ISSUE THREAD

**Issue by larsengels** [iocage/iocage#171]
Please add a TAG column to the iocage df output:

root@eddfbsd01:~ # iocage df
UUID                                  CRT     RES    QTA    USE    AVA
2ccff398-0f5a-11e5-9c44-436c0ba48365  1.59x   none   none   1.34G  87.3G
4448e560-13f0-11e4-9463-db544107b7d4  1.74x   none   15G    2.25G  12.8G
8debdb96-f3f8-11e4-92a2-b710dbc6b4c3  1.47x   none   none   1.02G  87.3G
b3788960-11ac-11e4-9463-db544107b7d4  1.70x   none   15G    94.8M  14.9G

**Comment by skarekrow** [comment]
This is in latest develop.

**Comment by moviuro** [comment]
See #158
