### ISSUE TITLE
iocage -b reclones from RELEASE and not from template

### ISSUE THREAD

**Issue by dch** [iocage/iocage#172]
I'm not sure whether this is a documentation bug or a code bug, but it should be possible to preserve customisations done in the template and still use `-b`.

# steps

```
export RELEASE=10.2-RELEASE
export BASE=base-$RELEASE
iocage set defaultrouter6='fe80::1%em0' default
iocage set resolver="nameserver 2a01:4f8:0:a0a1::add:1010;nameserver 2a01:4f8:0:a102::add:9999;nameserver 2a01:4f8:0:a102::add:9898;options edns0" default

echo tmux       > packages.lst

iocage create release=$RELEASE pkglist=packages.lst tag=$BASE

iocage chroot $BASE /bin/sh
# customise here
mkdir -p -m 0700 /usr/local/etc/pkg/repos/
echo 'FreeBSD: {enabled: yes}' > /usr/local/etc/pkg/repos/freebsd.conf
exit

iocage set notes=$RELEASE-`date -u +%Y%m%d-%H%M` $BASE
iocage set template=yes $BASE

# make a jail
iocage create -b $BASE \
    tag=wascal \
    ip6_addr='em0|2a01:4f8:200:12cf:0:0:0:7/64,lo0|::7/8'

# check customisations are present
iocage chroot wascal /bin/sh
# inherited from the template
cat /etc/resolv.conf
    nameserver 2a01:4f8:0:a0a1::add:1010
    nameserver 2a01:4f8:0:a102::add:9999
    nameserver 2a01:4f8:0:a102::add:9898
    options edns0
# custom files
cat: /usr/local/etc/pkg/repos/freebsd.conf: No such file or directory
tmux
tmux: not found
# exit
```

# expected

- cat shows the file
- tmux is found

Obviously for tmux it could be installed during creation by adding ` pkglist=packages.lst` to the create command, but I was expecting it to come from the template.

**Comment by dch** [comment]
So I realised that I should be using `clone` and not `create`. Might it make more sense to consolidate clone into create, and just have a `-t <template>` flag to do what clone does now?

**Comment by pannon** [comment]
@dch yes cloning is the only way to make use of templates. And agreed, we should make this a bit more transparent.

With the `clone` command you can clone any jail or template while `create` will deploy a vanilla RELEASE jail + your defaults.
