### ISSUE TITLE
iocage fetch does not see the host version first time  10.2-RELEASE

### ISSUE THREAD

**Issue by Johanhen** [iocage/iocage#173]
When setting up iocage for the first time on 10.2 it does not show the 10.2-RELEASE
If you select 10.2-RELEASE the first time it tells you Invalid release 10.2-RELEASE
If you then run iocage fetch again it will fill in 10.2-RELEASE and it will use it.

I would suspect to see 
Supported releases are:
   10.2-RELEASE
   10.1-RELEASE
    9.3-RELEASE

root@node_1:~ # iocage fetch
Setting up zpool [iocage] for iocage usage...
If you wish to change zpool, use 'iocage activate'
  INFO: Creating iocage/iocage
  INFO: Creating iocage/iocage/jails
  INFO: Creating iocage/iocage/.defaults
  INFO: Creating iocage/iocage/download
  INFO: Creating iocage/iocage/releases
Supported releases are:
   10.1-RELEASE
    9.3-RELEASE
Please select a release [-]: 10.2-RELEASE
Invalid release 10.2-RELEASE specified, exiting..
root@node_1:~ # iocage fetch
Supported releases are:
   10.1-RELEASE
    9.3-RELEASE
Please select a release [10.2-RELEASE]: <ENTER>
Please select a release [10.2-RELEASE]:
base.txz                                      100% of   64 MB 2201 kBps 00m30s
doc.txz                                       100% of 1398 kB 1839 kBps 00m01s

**Comment by pannon** [comment]
@Johanhen which version of iocage is this?

**Comment by Johanhen** [comment]
Op 19/08/15 om 22:39 schreef Peter Toth:
>
> @Johanhen <https://github.com/Johanhen> which version of iocage is this?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/iocage/iocage/issues/173#issuecomment-132775194>.
>


root@node_1:~ # pkg info
dialog4ports-0.1.5_2           Console Interface to configure ports
iocage-1.7.1                        Full featured, no dependency Jail
container manager
pkg-1.5.6                            Package manager
portmaster-3.17.7               Manage your ports without external
databases or languages
root@node_1:~ # uname -a
FreeBSD node_1 10.2-RELEASE FreeBSD 10.2-RELEASE #0 r286666: Wed Aug 12
15:26:37 UTC 2015    
root@releng1.nyi.freebsd.org:/usr/obj/usr/src/sys/GENERIC  amd64
root@node_1:~ #
regards
Johan

**Comment by pannon** [comment]
I think 10.2 was added after 1.7.1 - would you mind retesting with latest from our develop or if you keen on experimenting try the speed branch?

Thanks!

**Comment by Johanhen** [comment]
Op 19/08/15 om 22:48 schreef Peter Toth:
>
> I think 10.2 was added after 1.7.1 - would you mind retesting with
> latest from our develop or if you keen on experimenting try the speed
> branch?
>
> Thanks!
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/iocage/iocage/issues/173#issuecomment-132779198>.
>


I downloaded the zip file from githup and copied the file to the
propiate location.

root@node_1:/usr/home/beheer/iocage-develop # iocage version
iocage 1.7.3 (2015/08/13)
root@node_1:/usr/home/beheer/iocage-develop # iocage fetch
  INFO: Creating iocage/iocage
  INFO: Creating iocage/iocage/jails
  INFO: Creating iocage/iocage/.defaults
  INFO: Creating iocage/iocage/download
  INFO: Creating iocage/iocage/releases
Supported releases are:
   10.2-RELEASE
    9.3-RELEASE
Please select a release [-]: 10.2-RELEASE
base.txz                                      100% of   64 MB 3400 kBps
00m19s
doc.txz                                       100% of 1398 kB  863 kBps
00m02s
lib32.txz                                     100% of   16 MB 1974 kBps
00m08s

Things looks good this way.
The port version needs an update i guess!

Thanks you.

regards
Johan
