### ISSUE TITLE
Iocage does not correctly guess that a jail should have vnet=on

### ISSUE THREAD

**Issue by woodsb02** [iocage/iocage#173]
The manpage states that iocage will try to guess whether a jail should have vnet=on at the time it is created. On my system, even though I have vnet0 and vnet1 interfaces, iocage does not automatically set vnet=on.

If I manually set it, it works fine.

iocage --version: Version 0.9.8.1 05/23/2017

**Comment by skarekrow** [comment]
Old behavior :) I found it wasn't intuitive that every jail did that so I removed it.

**Comment by woodsb02** [comment]
Fair enough. I must say I kinda liked the old old behaviour... but the important thing is that the docs match the functionality :)

**Comment by skarekrow** [comment]
I did too, but given how unstable it is, I'm thinking of the TrueOS guys and such who "use" CURRENT, but aren't aware why every time they start a jail it takes their system lol. Until it's rock solid, it made sense to not do that behavior, but yeah the documentation matching is the important bit.
