### ISSUE TITLE
Missing comma

### ISSUE THREAD

**Issue by cwschulz** [iocage/iocage#174]
Make sure to follow and check these boxes before submitting an issue! Thank you.

- [ X] Supply `iocage --version`
- [ X] Supply the commands used, along with any steps to recreate it.
- [ X] Provide the output from the command you issued.
- [ X] Supply what you expected the result or output to be
- [ X] Checked that the problem has not already been fixed on `master` if using
 a stable release.

In the recent commit: 89a217a the setup.py is missing a comma after the verboselogs.

**Comment by skarekrow** [comment]
Bah brain fart.
