### ISSUE TITLE
Stray output in "iocage get all" [1.7.3]

### ISSUE THREAD

**Issue by olgeni** [iocage/iocage#176]
When running "iocage get all" without UUIDS or tags some warnings are produced:

    # iocage get all
    [: ==: argument expected
    [: ==: argument expected
      ERROR: missing UUID or property!

Just a cosmetic issue - no side effects.

**Comment by pannon** [comment]
Thanks @olgeni, please test with latest develop should be fine now.

**Comment by olgeni** [comment]
Looks ok - thanks!

**Comment by skarekrow** [comment]
Thanks for telling us so fast :)

**Comment by pannon** [comment]
@skarekrow you must have fixed it :) - I only smoke tested.

**Comment by skarekrow** [comment]
@pannon https://github.com/iocage/iocage/commit/a9286cc517048a80d11a516ee5a8ee6927edd53a is likely the fix?
