### ISSUE TITLE
Missing commands 'start' 'list' etc...

### ISSUE THREAD

**Issue by breyer** [iocage/iocage#177]
Running py36-iocage with freebsd 11.0-RELEASE with version from ports.

```
root@homeboy:/home/mono # iocage -v
Version 0.9.8.1 05/23/2017
```

Im missing some commands like 'list' or 'start' and 'stop':

```
root@homeboy:/home/mono # iocage list
Usage: iocage [OPTIONS] COMMAND [ARGS]...

Error: No such command "list".

```
There are just some commands and many missing ...

```
root@homeboy:/home/mono # iocage --help
Usage: iocage [OPTIONS] COMMAND [ARGS]...

  A jail manager.

Options:
  -v, --version  Display iocage's version and exit.
  --help         Show this message and exit.

Commands:
  df          Show resource usage of all jails.
  export      Exports a specified jail.
  fstab       Manipulate the specified jails fstab.
  get         Gets the specified property.
  import      Import a specified jail.
  migrate     Migrate all jails to the new jail format.
  pkg         Use pkg inside a specified jail.
  restart     Restarts the specified jails or ALL.
  rollback    Rollbacks the specified jail.
  set         Sets the specified property.
  snaplist    Show snapshots of a specified jail.
  snapremove  Remove specified snapshot of a jail.
  snapshot    Snapshots the specified jail.
  upgrade     Run freebsd-update to upgrade a specified...
```

Is this a freebsd ports problem or a general problem?
Anyone knows?

**Comment by skarekrow** [comment]
Would be a ports issue as those definitely exist :D

**Comment by araujobsd** [comment]
Hi,

I just built sysutils/py3-iocage from ports and it looks all fine:
root@src-dev:/usr/ports/sysutils/py3-iocage # iocage -v
Version	0.9.8.1 05/23/2017
root@src-dev:/usr/ports/sysutils/py3-iocage # iocage list
No zpools found! Please create one before using iocage.
root@src-dev:/usr/ports/sysutils/py3-iocage # uname -a
FreeBSD src-dev 12.0-CURRENT FreeBSD 12.0-CURRENT #0 r319641M: Wed Jun  7 05:43:30 CST 2017     araujo@src-dev:/usr/obj/usr/src/sys/GENERIC  amd64
root@src-dev:/usr/ports/sysutils/py3-iocage # 

So, there is no problem with ports, I would suggest you build and install it again.

Also, we will have py3-iocage package very soon, I do believe till this weekend you will be able to install:
pkg install py36-iocage.

Best,

**Comment by breyer** [comment]
See line: "No zpools found! Please create one before using iocage."
So please create a zpool first and then try it again. I have this issue on two different server.

If if compile source from github it works fine, from ports not.

Thanks
Mark

**Comment by araujobsd** [comment]
root@src-dev:/home/araujo # iocage 
root@src-dev:/home/araujo # zpool list tank
NAME   SIZE  ALLOC   FREE  EXPANDSZ   FRAG    CAP  DEDUP  HEALTH  ALTROOT
tank  49.8G   502K  49.7G         -     0%     0%  1.00x  ONLINE  -
root@src-dev:/home/araujo # iocage list
+-----+------+-------+-----+---------+-----+
| JID | UUID | STATE | TAG | RELEASE | IP4 |
+=====+======+=======+=====+=========+=====+
+-----+------+-------+-----+---------+-----+
root@src-dev:/home/araujo # iocage -v
Version	0.9.8.1 05/23/2017

I just built it from ports.

**Comment by breyer** [comment]
This is very strange:

```
root@lumpy:/usr/ports/sysutils/py3-iocage # iocage --help
Usage: iocage [OPTIONS] COMMAND [ARGS]...

  A jail manager.

Options:
  -v, --version  Display iocage's version and exit.
  --help         Show this message and exit.

Commands:
  df          Show resource usage of all jails.
  export      Exports a specified jail.
  fstab       Manipulate the specified jails fstab.
  get         Gets the specified property.
  import      Import a specified jail.
  migrate     Migrate all jails to the new jail format.
  pkg         Use pkg inside a specified jail.
  restart     Restarts the specified jails or ALL.
  rollback    Rollbacks the specified jail.
  set         Sets the specified property.
  snaplist    Show snapshots of a specified jail.
  snapremove  Remove specified snapshot of a jail.
  snapshot    Snapshots the specified jail.
  upgrade     Run freebsd-update to upgrade a specified...
```

```
root@lumpy:/usr/ports/sysutils/py3-iocage # iocage -v
Version 0.9.8.1 05/23/2017

```
