### ISSUE TITLE
Picking the first zpool makes iocage pick bootpool.

### ISSUE THREAD

**Issue by xmj** [iocage/iocage#178]
- [x] Supply `iocage --version`
`py27-iocage-0.9.5_1`
- [x] Supply the commands used, along with any steps to recreate it.
`sudo iocage list`
- [ ] Provide the output from the command you issued.
```
#  iocage list
Setting up zpool [bootpool] for iocage usage
If you wish to change please use "iocage activate"
Creating bootpool/iocage
Creating bootpool/iocage/download
Creating bootpool/iocage/images
Creating bootpool/iocage/jails
Creating bootpool/iocage/log
Creating bootpool/iocage/releases
Creating bootpool/iocage/templates
+-----+------+-------+-----+---------+-----+
| JID | UUID | STATE | TAG | RELEASE | IP4 |
+=====+======+=======+=====+=========+=====+
+-----+------+-------+-----+---------+-----+
```
- [x] Supply what you expected the result or output to be

Yell at me for not having run `iocage activate <ZPOOL>` first.

Assuming that the first pool in `zpool list` is the one I'd like to use is a bad idea, especially given FreeBSD / bsdinstall's defaulting to use separate pools for /boot with encrypted root on ZFS.

- [x] Checked that the problem has not already been fixed on `master` if using
 a stable release.

**Comment by skarekrow** [comment]
I won't be removing the behavior, but what is the name of the pool FreeBSD uses for encrypted install? I can just skip it if that's the first one found.

**Comment by rwestlund** [comment]
Prior to FreeBSD 11.0, encrypted root on ZFS creates `bootpool` for unencrypted `/boot/` and a primary encrypted pool (`zroot` by default).

For new FreeBSD 11.0 installs, `bootpool` is no longer required (Allan Jude added GELI support to the loader), so only one pool is created.

FWIW, I firmly believe a command like `iocage list` should never modify zpools; this is a POLA violation.  I was very surprised when trying to run `iocage help` started creating datasets, and came here to report the same issue.  Some of us have multiple zpools on our servers for other reasons, so hard-coding the name `bootpool` doesn't resolve this.

**Comment by skarekrow** [comment]
`iocage list` will not modify your zpool, unless run as root. `--help` will also not, that was a bug from a while back that was fixed. 

I would argue `iocage list` creating datasets is not a POLA violation, as why are you trying to list something you already know not to exist? 

This was the behavior in the shell version of iocage, and for users with just one zpool (many users, including FreeNAS) this automatic activation allows quicker usage of iocage.

IE:
`iocage create tag="foo" -r 11.0-RELEASE` on a fresh system that iocage was just installed on will activate the first pool, fetch that RELEASE and create the jail. This just saved the user 3 commands, and potentially a great deal of frustration if they decide to script it.

This is why the `activate` sub command exists. For those of you who wish to control *which* zpool gets activated, and for the rest they get to use the automatic activation. I don't plan to change this behavior. I'm not a user of encrypted roots with ZFS, so thank you for that information, but it sounds like it's not worth the effort to hardcode that name anyways as the behavior isn't even current.

@rwestlund I do wish to clarify, were you running the command `iocage help` or `iocage COMMAND --help`? If it's the former, please open a separate issue, as unsupported commands shouldn't create datasets either.


So I will close this as a `wontfix` in the meantime, thanks for the input guys 👍
