### ISSUE TITLE
There should be a direct way to test whether a particular jail is running

### ISSUE THREAD

**Issue by dneades** [iocage/iocage#179]
When automating iocage (e.g. using SaltStack), it’s extremely helpful to be able to test whether a jail is already in a desired state before blindly attempting to manipulate that state. For example, there’s no need to attempt to start a jail that is already running. Being able to test every aspect of a jail’s state in this way makes it possible to use iocage in an idempotent way – a jail is only ever modified if it isn’t already in the desired state. Dry-runs are also facilitated – for example, SaltStack is able to tell you what would change if you were to apply a particular state to a system.

While jail properties can be checked with `iocage get`, there doesn’t seem to be an elegant way to test whether or not a jail is running. (I may, of course, have missed something!) At the moment, therefore, I am checking the return code of the following to determine whether a jail with the tag MYTAG is running:

```
iocage list | grep '[[:space:]]up[[:space:]]*MYTAG$'
```

While that works, it’s rather clunky. It would be nice to have an elegant way to test whether or not a jail is running. For example, perhaps there could be a new read-only property `up` (or maybe `running`):

```
iocage get up MYTAG
```

Additional thoughts (perhaps for additional issues to be raised):

It may also be desirable to add a similar way of testing whether a jail with a given tag exists or, say, whether a jail is up-to-date with the latest (or perhaps a specified) patch level. (In the case of the former, checking the return code of `iocage get tag MYTAG` already seems to suffice, so a more direct method of checking for jail existence would merely be syntactic sugar.)

Finally, to extend the principle further, it would be great (where possible) to have a general way to determine (without actually applying any changes) whether any particular iocage command would modify the state of the system. For example, perhaps iocage could take a dry-run flag, and then indicate with its return code whether or not the given command would modify the system’s state in any way.

**Comment by pannon** [comment]
@dneades this is an easy change. Will be included very soon.

**Comment by dneades** [comment]
That’s super, thank you very much :-)

**Comment by moviuro** [comment]
`status` would be a good name, as we can add more than just yes/no if needed (`up`, `down`, `starting`, `shutting down`, etc.)

**Comment by dneades** [comment]
Perfect, thank you!
