### ISSUE TITLE
Defaultrouter, proper usage?

### ISSUE THREAD

**Issue by StarkJohan** [iocage/iocage#180]
iocage 0.9.8.1 05/23/2017 

This is probably not an issue but I can not figure out how to set the default gateway of jails on secondary NIC. "defaultrouter" does not seem to do much.

Setup is 2 NICS, igb0 and igb1. Jails on igb0 works fine. Jails on igb1.

ifconfig of host (freeness 11-RELEASE)
`igb0: flags=8843<UP,BROADCAST,RUNNING,SIMPLEX,MULTICAST> metric 0 mtu 1500
	options=6403bb<RXCSUM,TXCSUM,VLAN_MTU,VLAN_HWTAGGING,JUMBO_MTU,VLAN_HWCSUM,TSO4,TSO6,VLAN_HWTSO,RXCSUM_IPV6,TXCSUM_IPV6>
	ether 0c:c4:7a:34:24:84
	inet 10.10.10.11 netmask 0xffffff00 broadcast 10.10.10.255 
	inet 10.10.10.12 netmask 0xffffff00 broadcast 10.10.10.255 
	nd6 options=9<PERFORMNUD,IFDISABLED>
	media: Ethernet autoselect (1000baseT <full-duplex>)
	status: active
igb1: flags=8843<UP,BROADCAST,RUNNING,SIMPLEX,MULTICAST> metric 0 mtu 1500
	options=6403bb<RXCSUM,TXCSUM,VLAN_MTU,VLAN_HWTAGGING,JUMBO_MTU,VLAN_HWCSUM,TSO4,TSO6,VLAN_HWTSO,RXCSUM_IPV6,TXCSUM_IPV6>
	ether 0c:c4:7a:34:24:85
	inet 10.10.40.40 netmask 0xffffff00 broadcast 10.10.40.255 
	inet 10.10.40.41 netmask 0xffffff00 broadcast 10.10.40.255 
	nd6 options=9<PERFORMNUD,IFDISABLED>
	media: Ethernet autoselect (1000baseT <full-duplex>)
	status: active
lo0: flags=8049<UP,LOOPBACK,RUNNING,MULTICAST> metric 0 mtu 16384
	options=600003<RXCSUM,TXCSUM,RXCSUM_IPV6,TXCSUM_IPV6>
	inet6 ::1 prefixlen 128 
	inet6 fe80::1%lo0 prefixlen 64 scopeid 0x3 
	inet 127.0.0.1 netmask 0xff000000 
	nd6 options=21<PERFORMNUD,AUTO_LINKLOCAL>
	groups: lo `

Created a fresh jail
`sudo iocage create tag=testjail ip4_addr="igb1|10.10.40.41/24" -r 11.0-RELEASE`

and set defaultrouter=10.10.40.1 in this case. Pinging it works fine but I can't reach the WAN. Do i need to change something more than default gateway? Do I need to to something else to actually change the default gateway than to set "defaultrouter"?

**Comment by skarekrow** [comment]
It's only applicable for VNET jails, make sure to read the manpage ;)
```
defaultrouter=none | ipaddress
Setting this property to anything other than none configures a
default route inside a VNET jail.
```
