### ISSUE TITLE
Consolidate reboot & restart

### ISSUE THREAD

**Issue by moviuro** [iocage/iocage#180]
`iocage restart` should include a switch to run a ''hard'' restart of the jail, currently run by `iocage reboot`

**Comment by skarekrow** [comment]
I don't see the value in adding a flag to `restart` when `reboot` exists to do just that. `restart` as it implies is meant to keep the structure up and restart the jail without tearing it down. `reboot` is meant to signify "rebooting" the jail by stopping and starting it back up.

**Comment by moviuro** [comment]
The rationale for this was the same as #181 : reduce the number of commands...

**Comment by skarekrow** [comment]
In this case they should be separate. They serve 2 different purposes.
