### ISSUE TITLE
Setting sysctls with iocage jails?

### ISSUE THREAD

**Issue by StarkJohan** [iocage/iocage#182]
I can't seem to figure out how to set specific jail sysctls using iocage? Manpage didn't make me any wiser on this "issue" :-)

Version 0.9.8.1 05/23/2017 on FreeNAS 11-RELEASE

Trying to set:
kern.ipc.maxsockbuf=4194304 to fix this error in the jail

`Transmission transmission-daemon[96546]: UDP Failed to set receive buffer: requested 4194304, got 42080 (tr-udp.c:84)
`

**Comment by skarekrow** [comment]
You don't change sysctl's in a jail generally, instead you would change that specific one on the host. Any sysctl that you can set that affects a jail directly iocage exposes via the `allow_*` properties.
