### ISSUE TITLE
FreeBSD uses python3.6 by default

### ISSUE THREAD

**Issue by rwestlund** [iocage/iocage#183]
As of r439592 (2017-04-27), python 3.6 is the default python3 on FreeBSD.  The README is out of date.

**Comment by rwestlund** [comment]
FreeBSD PR for removing `NO_PACKAGE`: https://bugs.freebsd.org/bugzilla/show_bug.cgi?id=220098

**Comment by araujobsd** [comment]
Thanks for the PR and all contact that you made!
I just committed it few minutes ago, r443925.

br,
