### ISSUE TITLE
Use jail ftp settings for updates/upgrades

### ISSUE THREAD

**Issue by moviuro** [iocage/iocage#184]
Currently the same ftp settings are used for all jails unless overridden on the command line. The jails themselves keep the ftp settings as properties already, and using these as the source for these settings rather than the built-in global defaults would make updating jails that use unique ftp settings much easier.

see: https://github.com/iocage/iocage/blob/da44e96b25d5bd5d1a6e5c7d73a7f2f58233ccd7/lib/ioc-common#L256
(Imported from @freqlabs' issues)

**Comment by freqlabs** [comment]
Just to note one small difference here, the ftp settings are not currently stored in the jail properties in this repo, that's something I did in anticipation of this enhancement.

**Comment by skarekrow** [comment]
As @freqlabs has noted, we don't actually store that setting, as it has no relevance. It is used for the initial fetch, and afterwards all of our operations use that data, with no regard to where it came from. We cannot see the benefit of doing this, it just adds clutter. If you want to switch the data that `fetch` has grabbed to a different set of data from another ftp host, just rerun the command. But we won't be supporting that as an exposed feature.
