### ISSUE TITLE
Basejails should not duplicate nullfs-mounted files

### ISSUE THREAD

**Issue by rwestlund** [iocage/iocage#184]
From looking at HEAD (0fa6a85e48f):

Creating a basejail uses `zfs clone` on the release or template used as the base.  This results in a cloned copy of the base files which are then hidden by nullfs mounting the original base files on top of them.

This is unnecessary, and when the base is updated or the datasets are moved by `zfs send`, the unused copies in the basejails start taking up a lot of space (350 MB of waste per basejail).

Here's my use case:  I need to create a large number of similar basejails and `zfs send` them along with the template/release base out to prod servers.  The basejails may move from server to server for load balancing or failover, and I can deploy tested updates with zfs replication.  I'm working in a VPS environment where space is at a premium, so this wasted space is an issue for me.

My suggestion is to keep using `zfs clone` on the base, but then delete the contents of each directory that will be nullfs mounted over, i.e.:
```sh
rm -rf boot/* bin/* lib/* libexec/* rescue/* sbin/* usr/bin/* usr/include/* usr/lib/* usr/libexec/* usr/sbin/* usr/share/* usr/libdata/* usr/lib32/*
```
I also deleted `var/db/freebsd-update/` to save more space.  Together, this takes the basejail root dataset's `REFER` from 355 MB to 5 MB -- a 98.6% decrease in size!

I'm doing this manually now, but I think iocage should include this optimization.

**Comment by skarekrow** [comment]
Yeah the basejails have only had one pass on them, I'll mark this into the same milestone as the other basejail stuff, but I may get to this sooner since now it's bugging me after you have highlighted it :D

**Comment by skarekrow** [comment]
@rwestlund So unfortunately that slowed the creation process down a good deal, but I tried to keep it as performant as I could. Please test and let me know if this solves your issues 👍

**Comment by rwestlund** [comment]
That's a big improvement in size, thanks :)
