### ISSUE TITLE
Add support for `iocage snapremove ALL@ALL`

### ISSUE THREAD

**Issue by moviuro** [iocage/iocage#186]
Rationale: I don't use snapshots at the moment, hence my will to delete them all.

**Comment by pannon** [comment]
This is never going to be supported for a number of reasons. Number one being we heavily rely on snapshots for clones basejails etc.

**Comment by skarekrow** [comment]
https://github.com/iocage/iocage/issues/170 already had this answered.

**Comment by moviuro** [comment]
`ALL@ALL` doesn't have to be so stupid that it actually shoots itself in the foot. It could be something smarter like removing automatic snapshots of e.g. `iocage update`
