### ISSUE TITLE
Add finer support for snapshot management

### ISSUE THREAD

**Issue by moviuro** [iocage/iocage#187]
It may be an idea to add a property on snapshots: were they..
* automatic (`iocage update`)
* initiated by the admin (`iocage snapshot`)
* none of the above (`zfs snapshot`)

This will allow for more fined-grained snapshot listing/removal.
```sh
EXAMPLES:
iocage snapremove ALL@:automatic
iocage snapremove ALL@:cron,manual
```

**Comment by skarekrow** [comment]
AFAIK the snapshots are immutable, and thus this isn't possible. Closing this as we also don't see the benefit to actually separating the snapshots anyways. The user can do that via how they choose to name it. We want ours to have a different appearance so the user knows that it is being used.
