### ISSUE TITLE
Notes cannot contain the string "template"

### ISSUE THREAD

**Issue by gronke** [iocage/iocage#189]
```
root@freebsd:/usr/home/fnord # iocage set notes="foo" build
Property: notes has been updated to foo
root@freebsd:/usr/home/fnord # iocage set notes="foo-template" build
build (template) not found!
```

```
root@freebsd:/usr/home/fnord # uname -a
FreeBSD foo.example.org 11.0-RELEASE-p10 FreeBSD 11.0-RELEASE-p10 #0: Tue Jun 20 13:44:17 UTC 2017
```

Version: `0.9.9-ALPHA`
Commit: `6cb5dfbb4efbfb4113c930a12222de71f21640c7`

**Comment by skarekrow** [comment]
Yeah probably fallout from the last commit. Good catch!

**Comment by gronke** [comment]
Works after commenting out https://github.com/iocage/iocage/blob/4fc6836b534b6757f41f09c2b6db580d44245396/iocage/cli/set.py#L48

**Comment by skarekrow** [comment]
Yeah damn didn't test that commit enough apparently. Easy fix atleast

**Comment by skarekrow** [comment]
Ok pushed a commit, but this may require us to be more specific and switch to some good ol' regex.
