### ISSUE TITLE
changing IP address for stopped jail results in unwanted error

### ISSUE THREAD

**Issue by okapia** [iocage/iocage#19]
# iocage stop mail
    # iocage set ip4_addr="bge0|192.168.178.21" mail
    Property: ip4_addr has been updated to bge0|192.168.178.21
    ERROR: jail: jid: non-integer value "-"

A stopped jail has no jid. iocage probably doesn't need to run the command that is emitting that error.

**Comment by skarekrow** [comment]
Oops yep I forgot to check for that. Thanks!
