### ISSUE TITLE
Allow setting ip4_addr without the interface name

### ISSUE THREAD

**Issue by rwestlund** [iocage/iocage#193]
`iocage create` requires `ip4_addr` to contain both an interface name and an IP address, or nothing at all.    I believe it should not require the interface name.

Here's my use case:  I want jails that share the host machine's IP.  The jails need network access, but don't need to accept inbound connections.  I'm in a VPS environment where I can't allocate multiple IPs and I'd like to avoid the overhead and complexity of internal NAT.

The `ip4_addr` property is passed to `jail(8)` as `ip4.addr` on start.  From the `jail(8)` manpage:
> If an interface is given before the IP address, an alias for the address will be added to that interface, as it is with the interface parameter.

If the alias it tries to add is also the host's primary IP, it causes the host to drop off the network and not come back.  The only way to share the host's IP is to not tell `jail(8)` the interface name so that it doesn't try to add an alias.

If I edit a jail's `config.json` so that `ip4_addr` contains only an IP address, everything works as I expect: the jail starts, it has network access, and it shares the IP with the host.

I'm not positive that this is the best way to accomplish my goal, but this is what I used to do with `ezjail`.

**Comment by skarekrow** [comment]
I suppose I could relax that complication, but this is only applicable for the host's IP correct?

Let's say `host` has the IP `1.1.1.1`, and you give the jail `1.1.1.2` without an interface, that shouldn't work, but instead requires the jail have the IP `1.1.1.1` IIRC.

I could perhaps make using the hosts IP the default without an interface, and require the user to specify `none` if they truly don't want to share. Have you tried changing the `defaults.json` for your use case? That should have every jail inherit the IP without my syntax checking biting your head off.

EDIT: Tested and yes all of what I said works the way I thought. So changing your `defaults.json` by hand for now should do what you expect, I'll see to add some logic to allow sharing the hosts IP.

**Comment by rwestlund** [comment]
Sweet, I didn't notice `defaults.json` in the commit log.  That effectively bypasses the syntax check during create.  Setting the default like this doesn't complain:
```
root@legion ~# iocage set ip4_addr="192.168.1.254/32" default
Default Property: ip4_addr has been updated to 192.168.1.254/32
```

There's also this warning when stopping it:
```
root@legion ~# iocage stop test
* Stopping test (test)
  + Running prestop OK
  + Stopping services OK
  ! IP4 address is missing an interface, set ip4_addr to "INTERFACE|IPADDR"
  + Removing jail process OK
  + Running poststop OK
```

Defaulting to `none` is safer than defaulting to the host's IP; if you share the IP and start ssh in the jail, you can't ssh to the host :P

**Comment by skarekrow** [comment]
Yeah I had a derp moment on that one. Ok well that atleast gets you going! I'll get some support added to help alleviate the annoying messages and prevention of setting it per jail during creation.

**Comment by dgeo** [comment]
Another use case for IP without interface:
I'm actually using this too, with a carp IP address set/unset by preexec/postexec (and another IP with interface)
Thank you @rwestlund to catch this before I migrate this one ;)

**Comment by skarekrow** [comment]
@dgeo Well I was only thinking about relaxing that message and requirement if the IP matches the hosts, otherwise the interface would still be a requirement.

The requirement is meant to help when users find that the jail starts just fine but they still have no networking! Without specifying an interface, that's the experience. I could default to if no interface is supplied to use the hosts default interface, but I try not to make too many assumptions.

But that may be an OK compromise to allow your use case, @rwestlund's and others.
