### ISSUE TITLE
Abbreviated uuids cause issues with named jails

### ISSUE THREAD

**Issue by rwestlund** [iocage/iocage#194]
Testing the `-n` option you just added:
```
root@legion ~# iocage start test1
Multiple jails found for test1:
  test1 (test1)
  test11 (test11)
```
The call to `startsWith()` here is the culprit:
https://github.com/iocage/iocage/blob/ae370262bbb73a6d1d7fa14ae2e06304afc97c27/iocage/lib/iocage.py#L199

I've thought about it a bit, and my best suggestion is to make an exact uuid match "win" over a partial match.  This makes names like "test1" and "test11" work without breaking abbreviated uuids.  In pseudocode:

- iterate over jails
  - if a partial match is found by `startsWith()`, append to list
  - if an exact uuid match is found, set `list = [ item ]` and break

Sorry to keep pelting you with issues :/

**Comment by skarekrow** [comment]
Bah thought that was solved a while ago. No problem, glad you're finding so many! Well both glad and sad but hey it gets fixed so that's good haha.

**Comment by skarekrow** [comment]
So this will propogate to every command as soon as the rest are folded into the API properly, so for now you may experience some weirdness with `name` jails for now, those will be ironed out by 0.9.9
