### ISSUE TITLE
Giving Jail app name

### ISSUE THREAD

**Issue by xerovis** [iocage/iocage#195]
We use Jails very similarly to how Docker containers are used. We do not use Docker because we do not feel it is ready for production. One thing we would love to be able to do is bring up 10 jails with the same Tag/Name or something else. Tag is not optimal since it must be unique, I understand why - so manual command line stuff does not require the UUID. We do not use interact with Jails manually, its mostly automatic, so we like the UUID naming convention. We would love to be able to Tag each Jail with the App its running and be able to quickly and easy get a list of all the Jails running a particular App.

**Comment by skarekrow** [comment]
Have you tried not adding a tag? We then use a date for the tag, which *should* keep them unique.

**Comment by xerovis** [comment]
We would like to be able to label each jail with the same name. At the moment we are incrementing the tag but its a pain because we have to keep a record of the previous numbers used for all apps.

**Comment by skarekrow** [comment]
You could keep record by using `iocage set notes="NOTES" UUID|TAG` and using `iocage get notes UUID|TAG` to look up that information. Or to even store the name that you want it to have, and let iocage randomize the tag.

**Comment by xerovis** [comment]
Thanks mate, we will try that.

**Comment by skarekrow** [comment]
No problem, let me know how that works out for you.

**Comment by xerovis** [comment]
Sort of worked but a bit of a hack. We first needed to get a list of all Jails, then get the notes property for each of them, disregarding any that don't have that note.

What we are using this for is to get a list of all App Jails running a particular App and destroying them before creating a whole bunch of new App Jails running new code for the particular App.

**Comment by skarekrow** [comment]
How are you listing the jails? 

I would use a `for loop` like this:
```
for i in $(iocage show notes | grep "NOTE_VALUE" | awk '{print $1}') ; do 
iocage stop $i
iocage destroy -f $i
done
```

**Comment by skarekrow** [comment]
Closing until I have more information to accurately label this. Will label as a question for now, please come back and tell me if using that for loop works for your usecase.
