### ISSUE TITLE
Cannot create /etc/rc.conf: Read-only file system

### ISSUE THREAD

**Issue by xerovis** [iocage/iocage#196]
I created a jail using 'iocage create tag=testjail 'bce0|aaa.bbb.ccc.ddd'

The tag is the same as another jail but the code worked fine and changed the tag of the jail to the datetime. The next line after this was:

/usr/local/sbin/iocage: cannot create /iocage/jails/d8a7eaf9-5771-11e5-be82-d067e5eea9ef/root/etc/rc.conf: Read-only file system

I did pull and install the latest version from git, I was previous running the version from ports. Output of iocage --version is: iocage 1.7.3 (2015/08/13)

**Comment by xerovis** [comment]
When I run "zfs get all /iocage/jails/d8a7eaf9-5771-11e5-be82-d067e5eea9ef" readonly is set to off/inherited by zroot

**Comment by skarekrow** [comment]
This issue will be fixed in a few minutes.

**Comment by xerovis** [comment]
Hell, that is fast. Your a legend!

**Comment by skarekrow** [comment]
:) Small mistake on my part in my last commit. Thanks for the report!

**Comment by skarekrow** [comment]
@xerovis 
https://github.com/iocage/iocage/commit/8a43d6363355028d9a9f1274cee06f02988efe70

That should fix it for you :)
