### ISSUE TITLE
iocage destroy error message

### ISSUE THREAD

**Issue by xerovis** [iocage/iocage#198]
Pulled the latest version from git an hour or two ago. When running iocage destroy I get the below error.

cannot open 'zroot/iocage/base': dataset does not exist

**Comment by pannon** [comment]
Thanks for reporting. Yes, we had a major rewrite for basejails which landed today, so things will be a bit rough around the edges. Will be cleaned up soon, just keep reporting stuff you see.

Thanks again for testing/reporting, appreciated!

**Comment by skarekrow** [comment]
Same as #200, just an innocuous error :) Will fix though.
