### ISSUE TITLE
iocage exec <command> returns with error even if <command> returns with 0

### ISSUE THREAD

**Issue by joachimmathes** [iocage/iocage#198]
Commit c597e55 introduced error handling of `iocage exec` commands based on the output of `stderr`. The problem is, that despite the executed command's return code being `0`, iocage will throw an error, if `stderr` is filled. Example:
```
iocage exec myjail '/bin/echo Hello >&2'
```

I run into this issue, when executing `pkg install` for the first time in a freshly provisioned jail:
```
iocage exec  'env ASSUME_ALWAYS_YES=YES pkg install myspecialpackage'
```
`pkg` answers with
```
pkg: Repository FreeBSD load error: access repo file(/var/db/pkg/repo-FreeBSD.sqlite) failed: No such file or directory
...
```
The first line is output on `stderr`, but it's only a warning. `pkg` will create the repo databases anyway and continue until finally exiting with return code `0`. But the `iocage` run breaks, due to `stderr`.

I am currently running iocage 0.9.8.1.

**Comment by skarekrow** [comment]
`iocage` isn't actually exiting, it's returning the error the program supplied, the package will still be installed. But this can be a bit more intelligent :)

**Comment by joachimmathes** [comment]
Thanks!
