### ISSUE TITLE
Able to download unsupported release

### ISSUE THREAD

**Issue by xerovis** [iocage/iocage#201]
I was able to download 10.1-RELEASE, which is unsupported, while running iocage fetch. This required that I destroy the zfs pools associated with this release via command line. Not sure if this is behavior that should be supported.

**Comment by skarekrow** [comment]
It's considered a "feature" We don't want to remove the ability for others to download older RELEASEs that upstream doesn't consider production. But we also don't want to list them. Can you elaborate on what you mean by ```This required that I destroy the zfs pools associated with this release via command line. Not sure if this is behavior that should be supported.```?

**Comment by xerovis** [comment]
Ok, that is fine. I think it should be documented somewhere though. What RELEASE does and effects isn't immediately apparent when reading the docs for example - what RELEASE is used if I have multiple releases on my machine and I am not using a supported RELEASE?

To get rid of the unsupported release I had to destroy them on the command line. I did this because I didn't know how unsupported releases might effect iocage as I assumed Unsupported meant it was unsupported by iocage not unsupported by FreeBSD.

**Comment by skarekrow** [comment]
They don't do anything unless you specify `release=RELEASE` for the commands that accept them like create and fetch for example. So in your case, since you must not have specified `release=RELEASE` on jail creation, it will default to the hosts. All commands that accept that property also do this.

**Comment by xerovis** [comment]
Thanks mate.

**Comment by skarekrow** [comment]
No problem!
