### ISSUE TITLE
Explain what a base jail is

### ISSUE THREAD

**Issue by xerovis** [iocage/iocage#202]
I have been unable to find any explanation in the docs on what a base jail is or does. Coming from the perspective of just wanting to run containers, it seems like the base jail stuff is some kind of magic.

I think if iocage is creating a base jail for all other jails using that release to be based on, it should be dealt with or labelled differently to normal jails.

**Comment by skarekrow** [comment]
https://github.com/iocage/iocage/blob/develop/iocage.8.txt#L137

But seriously, they are just jails that share a common base. They are readonly clones and have their own /etc /var /root and /usr/(local,home). They only take up as much room as what is in them. It is precisely what you think of when you mention containers. It is very space efficient and that is why they are our default.

You can do a `iocage get type UUID|TAG` to find out the type of jail you created. But unless you specify `[-c,-t,-e]` to create, it is a basejail.

**Comment by xerovis** [comment]
I know these tickets are annoying but I promise I am not lodging them to be annoying. My job is productization and these are questions that some users of iocage will ask or at least not understand. I realize these sorts of questions can be frustrating when you are an expert in this area, which all you guys are. I only ask them because I think iocage has got a great future and want to make it accessible to as many people as possible.

**Comment by skarekrow** [comment]
Oh these aren't annoying :) They have been answered so I'm closing it. I'm labeling them so if anybody has a question they can search these out before asking.
