### ISSUE TITLE
iocage start

### ISSUE THREAD

**Issue by xerovis** [iocage/iocage#204]
I get a similar error message to the issue below when I simply run "iocage start" without UUID or tag

https://github.com/iocage/iocage/issues/197

**Comment by xerovis** [comment]
I think it would be better instead of this "ERROR: missing jail UUID or name!"

To say "Error: You must specify Jail UUID or Tag" or something like this.

**Comment by skarekrow** [comment]
Please update, that commit fixed start as well.
```
 ~% iocage list
JID   UUID                                  BOOT  STATE  TAG
 ~% iocage start test
  ERROR: test not found!
```
As for the enhancement request, we use capitals so the user can quickly see it from our standard messages. But I agree that it should say TAG and not name.
