### ISSUE TITLE
Allow multiple jails on the same IP

### ISSUE THREAD

**Issue by rwestlund** [iocage/iocage#204]
The following code prevents starting multiple jails on the same IP address:
https://github.com/iocage/iocage/blob/f0b9ab61f042b667a2ea866e673968a8de5b7eff/iocage/lib/ioc_start.py#L213-L217

My use case for having multiple jails on the same IP (the host's IP) is discussed in #193.

If multiple jails both share the same IP and contain an interface name in `ip4_addr`, it's possible that there would be issues when `jail(8)` adds an alias that already exists.  So this may be a good safety check if interface names are present.

**Comment by skarekrow** [comment]
So just to make sure I understand this request and #193, you want to allow setting any IP without an interface, and you wish to disable the IP address is in use check as well if there was no interface supplied with the IP address?

I'm fine adding these changes, just want to make sure that's what's being requested first.

**Comment by rwestlund** [comment]
Yes.  For my use case, the only IP I'm using is the host's.  For example, my dev server has `192.168.1.254/24` on the primary NIC, and I want to set `ip4_addr=192.168.1.254/32` on multiple jails.

**Comment by gronke** [comment]
@rwestlund How would you prevent the jails from using the same port twice?

**Comment by rwestlund** [comment]
@gronke by not binding to ports at all; I'm using unix sockets.  For example, I can run NGINX in each jail but bind it to `/tmp/nginx.sock` rather than `:80`.  NGINX on the host can reverse proxy for TLS, and `proxy_pass` to each jail at `unix:/iocage/jails/myjail/root/tmp/nginx.sock`.

I'm doing this for more than just NGINX; unix sockets let each jail be the same, but they're namespaced from the host's perspective.

**Comment by dgeo** [comment]
@gronke I'd say this is the sysadmin's problem ;) For the tools (like iocage), let's KISS (Keep It Simple Stupid) !
IMHO, iocage should not prevent bad things, just not create them.

I'm (sometimes) using the host's IP, and just "jail" some services without need for NAT nor routing.

**Comment by rwestlund** [comment]
@skarekrow would you accept a pull request that simply removes the "IP in use" check?

**Comment by skarekrow** [comment]
I'm fine with that as long as the IP is the same as the hosts. I think there's value with duplicate detection otherwise :)  I also think the interface check for the property should be removed then if the IP is the hosts. As that will conflict with setting the hosts IP otherwise.

**Comment by rwestlund** [comment]
How would you reliably determine which IP is the host's primary IP?  There may be multiple NICs for different network segments and multiple IPs assigned to each NIC -- some of which may be aliases added by other running jails.

Anyway, here's a reasonable use case for having duplicate IPs that are not the host's IP:  a sysadmin (perhaps at a university) may wish to provide multiple services for a network from a single dedicated IP (not used by the host).   To improve security, the sysadmin may with to segregate these services into multiple heterogeneous jails -- perhaps separating kerberos, samba, http, ssh, etc.  To users of these network services, everything would conveniently be available from one IP.

If I worked at a university or large company, I might do exactly that.

**Comment by skarekrow** [comment]
Hmm. Those are fair points. 

To be honest It was only added as @kmoore134 requested it. It may be as simple as a revert for the PR. As that used to be the behavior. 

If you do PR this make sure to remove the interface check from setting the properties as well. I'll likely try to rope Kris into a conversation in here to defend his POV and workshop ideas. As ultimately iocage needs to serve both interests. 

If I had it my way, I'd also remove this check globally for what it's worth   


EDIT: He's fine with it. So go ahead and PR or I can rip it out later :)

**Comment by kmoore134** [comment]
Yea, nuke it.
