### ISSUE TITLE
Error on starting first jail

### ISSUE THREAD

**Issue by xerovis** [iocage/iocage#205]
I am using a completely blank Dell R710 server with iocage code from yesterday. I create a Jail and then start it and get the following error message:

cannot open 'zroot/iocage/base': dataset does not exist
* d88b3cf9-580e-11e5-be82-d067e5eea9ef is a basejail, re-cloning jail..
mount_unionfs: /iocage/jails/d88b3cf9-580e-11e5-be82-d067e5eea9ef/etc: No such file or directory
mount_unionfs: /iocage/jails/d88b3cf9-580e-11e5-be82-d067e5eea9ef/root_home: No such file or directory
mount_unionfs: /iocage/jails/d88b3cf9-580e-11e5-be82-d067e5eea9ef/home: No such file or directory
* Starting d88b3cf9-580e-11e5-be82-d067e5eea9ef (2015-09-11@08:54:09)
jail: mount.fstab: /iocage/jails/d88b3cf9-580e-11e5-be82-d067e5eea9ef/fstab: No such file or directory
  ! Start                FAILED

**Comment by skarekrow** [comment]
Already fixed, please pull.

**Comment by xerovis** [comment]
Just did and its now fixed. Thank you!

**Comment by skarekrow** [comment]
No problem!
