### ISSUE TITLE
jail name auto complete

### ISSUE THREAD

**Issue by xerovis** [iocage/iocage#206]
I have no idea how painful this would be to implement, but it would be a really handy feature when using command line.

**Comment by skarekrow** [comment]
I believe this would require us to ship a autocomplete file for each shell, but I may be wrong. I'll talk this over with @pannon and see what he thinks. If it's something doable I will leave this open otherwise I will come back and close it.

Thanks for the request!

**Comment by skarekrow** [comment]
So how we feel right now is that our short hand completion should handle this fine already. You aren't required to type the full UUID, but if somebody has a good solution for the autocompletion, we would be glad to review it.

**Comment by xerovis** [comment]
It would be great to see a road map of where you want iocage to go. I would like to put some Sysadmin people onto contributing but its a little hard when I am not sure where you want to take iocage V2.

**Comment by skarekrow** [comment]
This won't be happening. Closing :)
