### ISSUE TITLE
ports in jail

### ISSUE THREAD

**Issue by xerovis** [iocage/iocage#207]
Is there any plans to allow ports in jails? I assume there is a reason for not putting ports in jails, if so could you tell me why please?

**Comment by skarekrow** [comment]
We don't have any plans to add flags to do that currently. You can use `portsnap fetch extract` in the jail just fine though. We wanted to leave it up to the user to keep their ports collection up to date. If you have a lot of jails, you're probably better off using `poudriere` and setting a custom freebsd mirror for `pkg` inside the jail.

If you have never used `poudriere` before, then you can follow this excellent tutorial : http://www.bsdnow.tv/tutorials/poudriere

**Comment by xerovis** [comment]
Thanks mate. Just asking the question so that others can find later.

**Comment by xerovis** [comment]
I ran "portsnap fetch extract" in the jail and got the error:

mkdir: /usr/ports: Read-only file system

**Comment by skarekrow** [comment]
No problem man, I appreciate you opening every issue. It helps clarify things for us on what users expect and keeps a record for those to lookup later.

That is expected with a basejail. My bad. I will fix that soon.

**Comment by skarekrow** [comment]
So the easiest solution to pick up this fix after pulling @xerovis would be to do a `iocage clean -r` and refetch the RELEASE, then create new basejails. If you need them, I can walk you through the (much) more complicated process of getting everything in order.

**Comment by xerovis** [comment]
Is this the process I should run when reinstalling iocage so its a completely fresh install?

1. Git pull
2. make install clean
3. iocage clean -r

**Comment by skarekrow** [comment]
Not quite :)

1 - Git pull
2 - make install clean
3 - iocage clean -a

That should make it all fresh.

**Comment by xerovis** [comment]
Your changes worked, thank you. I am currently compiling some ports to test this out.

I agree on your logic of having the jail deal with ports instead of mounting ports into the jail. Being able to mount a ports tree into the jail does save time and space but I think it would be better to document how to use poudriere in a jail and use pkgs from it.

**Comment by skarekrow** [comment]
That's great to hear. The documentation exists so we didn't want to
reinvent the wheel. That link stays updated and Google is also an excellent
resource.
