### ISSUE TITLE
Priority property valid values

### ISSUE THREAD

**Issue by xerovis** [iocage/iocage#208]
The man page does not specify what priority numbers are valid i.e. 0-99 or whatever is valid. Either that or I am blind.

I would have made the change and pushed back but don't want to be putting my nose into your code this early on.

**Comment by skarekrow** [comment]
https://github.com/iocage/iocage/blob/develop/iocage.8.txt#L917-L922 shows 99 being the cap. and http://iocage.readthedocs.org/en/latest/advanced-use.html?highlight=priority#boot-priority describes the behavior :)

**Comment by xerovis** [comment]
What is the minimum value?

**Comment by skarekrow** [comment]
0 I believe. @pannon wrote it, he can correct me if I'm wrong.

**Comment by pannon** [comment]
Yes 0, I believe. 99 is a special one, anything set to 99 will automatically background start in parallel with other jails set to 99. Anything less than 99 will start sequentially.

**Comment by xerovis** [comment]
Thanks!

I think it would be good to put this in the man page. I would do it but I don't want poke in your code yet.
