### ISSUE TITLE
Support for HardenedBSD

### ISSUE THREAD

**Issue by shivno** [iocage/iocage#21]
It would be nice to be able to use iocage in HardenedBSD. It is mostly compatible, only the fetch (and possible verify) part would have to be changed. https://github.com/shirkdog/hardenedBSD/blob/master/usr.sbin/hbsd-update/hbsd-update

**Comment by shivno** [comment]
wrong repo:
https://github.com/HardenedBSD/hardenedBSD/blob/hardened/current/master/usr.sbin/hbsd-update/hbsd-update

**Comment by skarekrow** [comment]
This looks very incompatible with `freebsd-update`. But it sounds cool, I'll mark this as an enhancement and see if I can't add proper support for @lattera's project! :)

I owe him for the couple cool blog posts he did ;)

**Comment by lattera** [comment]
Lemme know if you have any questions!

**Comment by skarekrow** [comment]
@shivno Ok, all pushed. Test and let me know 👍

**Comment by shivno** [comment]
worked! awesome patch.

starting does not though, i fetch 11-stable on an 11-stable host:

root@awary:/ # iocage start cool-af
* Starting bd8c519f-ed79-4d4e-81fa-28495f8b4a09 (cool-af)
mount: .: Operation not supported by device
jail: /sbin/mount -t fdescfs . /iocage/jails/bd8c519f-ed79-4d4e-81fa-28495f8b4a09/root/dev/fd: failed

@lattera had no idea about it

**Comment by skarekrow** [comment]
Weird starting worked for me. I'll take a look

**Comment by skarekrow** [comment]
Yeah it still works here:
```
bschneider@hard_pie:~ % iocage list -l
╒═════╤══════════════════════════════════════╤══════╤═══════╤══════╤══════╤═════╤═══════════╤══════════╕
│ JID │ UUID                                 │ BOOT │ STATE │ TAG  │ TYPE │ IP4 │ RELEASE   │ TEMPLATE │
╞═════╪══════════════════════════════════════╪══════╪═══════╪══════╪══════╪═════╪═══════════╪══════════╡
| -   | 24e11df5-21fe-4308-afc5-15bff4f416b0 | off  | down  | test | jail | -   | 11-STABLE | -        |
+-----+--------------------------------------+------+-------+------+------+-----+-----------+----------+
bschneider@hard_pie:~ % sudo iocage start test
* Starting 24e11df5-21fe-4308-afc5-15bff4f416b0 (test)
  + Started OK
  + Starting services OK
bschneider@hard_pie:~ % uname -a
FreeBSD hard_pie 11.0-STABLE-HBSD FreeBSD 11.0-STABLE-HBSD #0 [STABLE:HardenedBSD-11-STABLE-v46.13]: Thu Jan 12 02:40:02 UTC 2017     root@nyi-01.build.hardenedbsd.org:/usr/obj/usr/src/sys/HARDENEDBSD  amd64

bschneider@hard_pie:~ % mount
-- snip --
devfs on /iocage/jails/24e11df5-21fe-4308-afc5-15bff4f416b0/root/dev (devfs, local, multilabel)
fdescfs on /iocage/jails/24e11df5-21fe-4308-afc5-15bff4f416b0/root/dev/fd (fdescfs) <--- What's failing for you for some reason
```

Can you do a `iocage get all cool-af` and paste that here?

**Comment by shivno** [comment]
i am happy to test anything, freebsd jails with iocage-1.7.6 worked well on the same host. i did zfs destroy -r store1 before so there hopefully was no leftover. in doubt i will reinstall this box. thanks already!

 
root@awary:/ # iocage  get all cool-af
openfiles:off
resolver:/etc/resolv.conf
nmsgq:off
memoryuse:8G:log
compressratio:readonly
allow_quotas:0
allow_mount_zfs:0
sync_tgt_zpool:none
istemplate:no
gitlocation:https://github.com
interfaces:vnet0:bridge0,vnet1:bridge1
login_flags:-f root
hostid:5929d4f8-63f3-b84f-846c-e89a8fc1ceea
ip4_autosubnet:none
bpf:off
notes:none
defaultrouter6:none
release:11-STABLE
nthr:off
coredumpsize:off
ip4_addr:none
allow_raw_sockets:0
allow_mount_tmpfs:0
ip4_autostart:none
exec_start:/bin/sh /etc/rc
allow_mount_procfs:0
mountpoint:readonly
sync_state:none
shmsize:off
dedup:off
jail_zfs_mountpoint:none
template:none
dhcp:off
hack88:0
available:readonly
pcpu:off
vmemoryuse:off
exec_clean:1
exec_prestop:/usr/bin/true
last_started:none
exec_fib:0
allow_set_hostname:1
exec_system_jail_user:0
securelevel:2
allow_mount_devfs:0
origin:readonly
mount_fdescfs:1
allow_mount:0
rlimits:off
exec_system_user:root
reservation:none
owner:root
swapuse:off
compression:lz4
exec_poststart:/usr/bin/true
ip6_addr:none
exec_timeout:60
host_domainname:none
priority:99
maxproc:off
ip4_saddrsel:1
exec_stop:/bin/sh /etc/rc.shutdown
sysvmsg:new
stacksize:off
datasize:off
type:jail
allow_mount_nullfs:0
allow_chflags:0
cpuset:off
ipv6:off
allow_socket_af:0
ip6:new
ip4:new
sysvsem:new
mount_devfs:1
mount_procfs:0
count:1
memorylocked:off
host_hostuuid:bd8c519f-ed79-4d4e-81fa-28495f8b4a09
tag:cool-af
mount_linprocfs:0
ip4_autoend:none
vnet0_mac:none
pseudoterminals:off
allow_sysvipc:0
vnet3_mac:none
mac_prefix:02ff60
jail_zfs:off
msgqsize:off
stop_timeout:30
nsemop:off
ip6_saddrsel:1
nshm:off
host_hostname:bd8c519f-ed79-4d4e-81fa-28495f8b4a09
boot:off
wallclock:off
sysvshm:new
exec_jail_user:root
used:readonly
defaultrouter:none
quota:none
exec_prestart:/usr/bin/true
enforce_statfs:2
jail_zfs_dataset:iocage/jails/bd8c519f-ed79-4d4e-81fa-28495f8b4a09/data
cputime:off
exec_poststop:/usr/bin/true
CONFIG_VERSION:2
children_max:0
sync_target:none
vnet1_mac:none
msgqqueued:off
vnet2_mac:none
vnet:off
devfs_ruleset:4

**Comment by shivno** [comment]
created with "iocage create -r 11-STABLE"

**Comment by skarekrow** [comment]
Hmm our configurations are identical it seems. 

What's your `uname -a`? Just for funsies, I'd say try `iocage clean -af ; iocage fetch -r 11-STABLE; iocage create tag=cool-af -r 11-STABLE; iocage start cool-af`. 

Since that may not work, I'd also try installing HardenedBSD in a VM and replicating the same steps above. When I installed my machine, I didn't select any additional hardening options beyond the defaults. Perhaps you did? As you are getting `operation not supported`.

Also you may try comparing my /etc/sysctl.conf to yours to see if anything pops out:
```
bschneider@hard_pie:~ % cat /etc/sysctl.conf
# $FreeBSD$
#
#  This file is read when going to multi-user and its contents piped thru
#  ``sysctl'' to adjust kernel values.  ``man 5 sysctl.conf'' for details.
#

# Uncomment this to prevent users from seeing information about processes that
# are being run under another UID.
#security.bsd.see_other_uids=0
security.bsd.see_other_uids=0
security.bsd.see_other_gids=0
security.bsd.unprivileged_read_msgbuf=0
security.bsd.unprivileged_proc_debug=0
security.bsd.stack_guard_page=1
```

**Comment by shivno** [comment]
i selected all hardening options, i will figure this out hopefully, but it will take a few days. also to be clear: to install iocage i did git clone master and pip install as root

**Comment by skarekrow** [comment]
You did the right thing then ;)

I'm going to guess it is one of the hardening options, when you find out which one please report back so we can add it to the wiki 👍

**Comment by skarekrow** [comment]
Ok I spoke too soon. I can't replicate this on vanilla FreeBSD with all security hardening options enabled, or HardenedBSD with all security hardening options enabled. There must be something else you changed that is causing this. I hope you find it!

BTW, I would do `pip install -U .` if you are upgrading, otherwise it won't actually install the changes.

**Comment by shivno** [comment]
i will have a look when i have free time. i cant remember i changed anything substantial. sorry if this was a waste of time :/. i will diff the host with a new vanilla install

**Comment by skarekrow** [comment]
Take all the time you need and it's never a waste of time, something isn't working and it's important to know why. Any debugging and information you provide help any other user having this issue, I appreciate it!

**Comment by shivno** [comment]
i have another similar host, there it works. i already diffed sysctl -a and /etc, found nothing. i will see later.
on awary, the problematic host, i eradicated the whole zfs and redid the iocage setup, still the same.

**Comment by shivno** [comment]
i should have looked in the kernel log, sorry, i owe you one

KLD fdescfs.ko: depends on kernel - not available or version mismatch
so that is settled i guess

**Comment by skarekrow** [comment]
Ha, that would explain it. Thanks for getting back to me :)
