### ISSUE TITLE
Is this message necessary?

### ISSUE THREAD

**Issue by xerovis** [iocage/iocage#211]
When starting a jail I get the following message?

root@host4:/usr/ports # iocage start c8081e57
* c8081e57-5810-11e5-be82-d067e5eea9ef is a basejail, re-cloning jail..

I am not sure it adds any value other than confusing the user. The questions I was asked was "What is a basejail?" and "why is the jail being cloned?" and "where is the jail cloned to?"

**Comment by skarekrow** [comment]
I agree
