### ISSUE TITLE
iocage clone appends _1 to tag name

### ISSUE THREAD

**Issue by rwestlund** [iocage/iocage#212]
Using HEAD (cd9464527b3876157461631ea7ac3c89382b4de2):

`iocage clone` appends a number to the provided tag:
```
root@r2d2 /u/h/randy# iocage clone test tag=deleteme
872cf87a-1acd-4781-8624-6107dd1081c5 (deleteme_1) successfully cloned!
```

This makes sense for creating multiple clones at once, but not when a single clone is created.  I suggest that the sequence number only be added when `c > 1`.

**Comment by skarekrow** [comment]
Hmm shouldn't work this way. Probably fallout from the batch support added
