### ISSUE TITLE
Jail folder not mounted on start

### ISSUE THREAD

**Issue by xerovis** [iocage/iocage#212]
I have these folders 

zroot/iocage/jails/c8081e57-5810-11e5-be82-d067e5eea9ef/data         96K   396G    96K  none
zroot/iocage/jails/c8081e57-5810-11e5-be82-d067e5eea9ef/usr         192K   396G    96K  none

Neither show as mounted when the jail is started. Not sure if this is expected behavior or not.

**Comment by skarekrow** [comment]
Expected. `/usr` needs to exist for `/usr/local` to be a dataset and `/data` is if you decide to use jailed datasets.
