### ISSUE TITLE
iocage is VIMAGE, RACCT, RCT enabled?

### ISSUE THREAD

**Issue by xerovis** [iocage/iocage#213]
It would be great to know if the features that iocage requires to use all features were enabled by typing a command without having to do it the longer and more confusing FreeBSD kernel module check.

**Comment by skarekrow** [comment]
It reports errors when the kernel isn't compiled with the features. And with FreeBSD it's pretty easy, if you're using GENERIC, you don't have any of them :)

**Comment by dneades** [comment]
@skarekrow, just a point of information – [`RACCT` and `RCT` are enabled in the `GENERIC` kernel as of FreeBSD 10.2](https://www.freebsd.org/releases/10.2R/relnotes.html#kernel-sysctl). As stated in the release notes, they can be enabled by adding `kern.racct.enable=1` to `/boot/loader.conf` and rebooting.

**Comment by skarekrow** [comment]
That's great to hear,  I missed that. Regardless you need to explicitly
enable these things,  so showing the presence of the feature doesn't seem
necessary to me as a stock machine doesn't have these enabled.

**Comment by xerovis** [comment]
You do show if RACCT is enabled when a Jail is created though, there is a message that is shown, which does create a little confusion. I am not arguing for iocage to duplicate functionality available in the OS, I am just saying that iocage cannot operate to its full extent without these features enabled and iocage reiterates that when creating a jail and there is no way to check if these features are enabled using an iocage command.
