### ISSUE TITLE
iocage RELEASE options

### ISSUE THREAD

**Issue by xerovis** [iocage/iocage#214]
I noticed that I must type 10.2-RELEASE or 9.3-RELEASE to download a release. It would be much better if they were numbered, so I could just type 1 or 2 or 1,2 and have them both downloaded.

**Comment by xerovis** [comment]
I also notice with the latest code (pulled 30 seconds ago) there is no longer a default option. So I have to type one release or the other.

**Comment by xerovis** [comment]
I think it would also be good if once a release was select the terminal said something like "Downloading and installing FreeBSD 10.2-RELEASE"

**Comment by skarekrow** [comment]
With the latest code, I don't see that behavior. We could echo that we are fetching, but since we are also updating the RELEASE to the latest patch level after doing so, it's likely to get lost in the output. You have to specify the whole RELEASE at the fetch dialog for this reason. Or specify `release=RELEASE` on the cli.
```
[brandon@devbox] ~%sudo iocage fetch
Supported releases are:
   10.2-RELEASE
    9.3-RELEASE
Please select a release [10.2-RELEASE]:
```

**Comment by xerovis** [comment]
It happened after I ran:

1 - Git pull
2 - make install clean
3 - iocage clean -a

**Comment by skarekrow** [comment]
Are you running a RELEASE? Or STABLE/CURRENT?

**Comment by xerovis** [comment]
10.2-RELEASE

**Comment by skarekrow** [comment]
That's odd,  so is my machine. Can you try a fresh clone,  make install
clean,  and see what happens? I would throw in a iocage clean - a but you
may have jails and probably wouldn't help but always worth a shot.

**Comment by xerovis** [comment]
I get the same result again.
<img width="296" alt="screen shot 2015-09-13 at 10 27 33 am" src="https://cloud.githubusercontent.com/assets/3682121/9834551/2c6edb00-5a02-11e5-8a04-5e18d085162c.png">

**Comment by xerovis** [comment]
For all of this testing I am using a Dell R710 with 10.2-RELEASE built from source, with no other software installed other than vim-lite.

**Comment by skarekrow** [comment]
Do you have access to a VM installed with stock FreeBSD 10.2 from the
website? I cannot reproduce this. @pannonp or @pr1ntf can you guys?

**Comment by xerovis** [comment]
<img width="1129" alt="screen shot 2015-09-13 at 10 35 28 am" src="https://cloud.githubusercontent.com/assets/3682121/9834578/77d5bcac-5a03-11e5-873e-2e617c080036.png">

**Comment by xerovis** [comment]
The second time I run iocatch fetch I get the output expected.

**Comment by pr1ntf** [comment]
I can reproduce this on a fresh install of 10.2-RELEASE. 

I have the same exact output as @xerovis 

````
root@fetchtest:~/iocage # uname -a
FreeBSD fetchtest 10.2-RELEASE FreeBSD 10.2-RELEASE #0 r286666: Wed Aug 12 15:26:3
7 UTC 2015     root@releng1.nyi.freebsd.org:/usr/obj/usr/src/sys/GENERIC  amd64
root@fetchtest:~/iocage # iocage fetch
Setting up zpool [zroot] for iocage usage...
If you wish to change zpool, use 'iocage activate'
  INFO: Creating zroot/iocage
  INFO: Creating zroot/iocage/.defaults
  INFO: Creating zroot/iocage/download
  INFO: Creating zroot/iocage/jails
  INFO: Creating zroot/iocage/releases
Supported releases are: 
   10.2-RELEASE
    9.3-RELEASE
Please select a release [-]: 
fetch: http://ftp.freebsd.org/pub/FreeBSD/releases/amd64/-/base.txz: Not Found
Failed fetching base.txz..
````

**Comment by xerovis** [comment]
I think we might be on the wrong page, you are getting the same result as me:

<img width="219" alt="screen shot 2015-09-13 at 11 21 23 am" src="https://cloud.githubusercontent.com/assets/3682121/9834683/a431e450-5a09-11e5-98ce-e57bd7793100.png">

**Comment by pr1ntf** [comment]
Yes, like I stated, I can reproduce this. 
That's why I am reopening the issue and taking a look into why it doesn't auto complete to the host's version.

**Comment by xerovis** [comment]
Whoops, sorry, missed that.

**Comment by pr1ntf** [comment]
It's all good :+1: 

You're right, though, after it fails it auto completes again. I'm taking a look.

**Comment by xerovis** [comment]
This happened again on a fresh install of 10.2 today.

**Comment by skarekrow** [comment]
This could still be a lingering issue with the master version from ports. I have done a few fresh installs since this fix, and it has not reoccured. What does `iocage version` show you?

**Comment by xerovis** [comment]
Sorry forgot to reply to your last comment. Got this issue again today on a completely fresh system.

iocage version shows - iocage 1.7.3 (2015/08/13)

**Comment by skarekrow** [comment]
That's with the stable version of iocage, which never had this fix to begin with. Only the develop branch does.

**Comment by xerovis** [comment]
![screen shot 2015-11-13 at 10 50 35 am](https://cloud.githubusercontent.com/assets/3682121/11135795/715e675e-89f4-11e5-92ef-ff7db040e845.png)

**Comment by skarekrow** [comment]
You didn't do `make install clean`

**Comment by xerovis** [comment]
Nice one!

**Comment by skarekrow** [comment]
:)

**Comment by xerovis** [comment]
Any reason to believe I should not use this branch?

**Comment by skarekrow** [comment]
Like the front page of the repo says:
```
WARNING:

The develop branch may not be functional at any given point. This is where a lot of experimental work gets done. No guarantees for stability or migrations within the branch are given. Things can and do change rapidly. Please don't use it if you require stability.
```

If that criteria doesn't concern you, then no go ahead and use it.

**Comment by xerovis** [comment]
I guess ill know soon enough :-)
