### ISSUE TITLE
iocage list installed RELEASES

### ISSUE THREAD

**Issue by xerovis** [iocage/iocage#215]
It doesn't seem like there is an option for this. It would be good to know what the installed releases are.

**Comment by skarekrow** [comment]
Please read the manpage :)

https://github.com/iocage/iocage/blob/develop/iocage.8.txt#L243-L247

**Comment by xerovis** [comment]
That one is really hidden.

**Comment by skarekrow** [comment]
How would you make it more visible? It's on our GitHub,  manage, help and
command output. Not sure where else to put it.

**Comment by xerovis** [comment]
Not sure, sorry mate. I have read the man page many many times, plus searched it for "release" before I lodged this ticket to make sure and didn't see it. I am not sure you can make it more visible.

**Comment by skarekrow** [comment]
No sorry needed,  it's good to hear any suggestions on visibility when a
user misses it :)
