### ISSUE TITLE
Destroying a release should have a scarier warning

### ISSUE THREAD

**Issue by rwestlund** [iocage/iocage#217]
Using HEAD (cd9464527b3876157461631ea7ac3c89382b4de2):

Destroying a release prints the following warning:
```
root@r2d2 /u/h/randy# iocage destroy -r 11.0-RELEASE

This will destroy RELEASE: 11.0-RELEASE and any jail that was created with it.

Are you sure? [y/N]:
```
Considering that this could wipe out every jail you have, this warning should be a lot more scary.  Some ideas:
- Print the list of jails that would be destroyed.
- Require `--force` whenever `--release` is specified if there are dependent jails.

**Comment by skarekrow** [comment]
Those are good ideas, I may incorporate both :+1:
