### ISSUE TITLE
How to start jail on create

### ISSUE THREAD

**Issue by xerovis** [iocage/iocage#218]
I have had a look at the man page and it doesn't seem like I can start the jail on create. We don't want to set the UUID or Tag (for reasons available in other issues listed) so we are unable to do an && iocage start UUID|Tag. We would need to watch to the return of the create command and then start the Jail.

**Comment by skarekrow** [comment]
Add a boot=on during create then a iocage reboot afterwards. Does that work
for you?

**Comment by pannon** [comment]
@xerovis please try with `iocage create tag=foo start=1` (start= can be anything)

**Comment by xerovis** [comment]
Thanks pannon. I will test that out.

**Comment by xerovis** [comment]
![screen shot 2015-09-14 at 5 58 04 pm](https://cloud.githubusercontent.com/assets/3682121/9844889/4a2d6b8a-5b0a-11e5-8462-2f6216c01a62.png)

**Comment by pannon** [comment]
@xerovis my bad, please pull latest.
