### ISSUE TITLE
set/get CLI inconsistent

### ISSUE THREAD

**Issue by rwestlund** [iocage/iocage#223]
Using HEAD (25727df28a8711d4f8dd413f912f04a1f2a36dc0):

Setting a default property requires specifying `default`:
```
root@r2d2 /u/h/randy# iocage set ip4_addr="192.168.10.251/32"
ip4_addr=192.168.10.251/32 not found!

root@r2d2 /u/h/randy# iocage set ip4_addr="192.168.10.251/32" default
Default Property: ip4_addr has been updated to 192.168.10.251/32
```

But getting that property requires _not_ specifying `default`:
```
root@r2d2 /u/h/randy# iocage get ip4_addr default
default not found!

root@r2d2 /u/h/randy# iocage get ip4_addr
192.168.10.251/32
```

These two should be consistent, like it is for jails:
```
root@r2d2 /u/h/randy# iocage set comment="something" test
Property: comment has been updated to something

root@r2d2 /u/h/randy# iocage get comment test
something
```

**Comment by skarekrow** [comment]
Interesting, that shouldn't work at all. As get/set syntax are consistent when using them against jails. Likely a side effect of adding the defaults support a little while back.
