### ISSUE TITLE
Request to create a "CONTRIBUTING" file or readme section briefly outlining code conventions

### ISSUE THREAD

**Issue by cactus** [iocage/iocage#223]
See: https://github.com/iocage/iocage/pull/222/files#r39453495

Might be worthwhile to create a brief doc (README section or CONTRIBUTING file) to outline desired coding conventions and pull request requirements (update docs if needed, commit comment should describe change, squash commits before opening pull req so there is one commit, etc).

**Comment by skarekrow** [comment]
@cactus Added it in: https://github.com/iocage/iocage/commit/ac6c430763d7384bbf4dc13ae6a57dbc84d92764. Can you think of anything that you would like clarified that isn't in that file?

**Comment by cactus** [comment]
Looks good. I might reword the header a bit...

~~~
# Please follow these rules if you want to contribute to us by sending a pull request
~~~

Might be a bit better received by potential contributors rewording it as something like this...

~~~
# Contribution guidelines

Following the contribution guidelines saves everyone time, requires less back
and forth during the review process, and helps to ensures a consistent codebase.

----

<rest of text>
~~~

But other than that, it looks like a great start. Feel free to close this placeholder issue. :)

**Comment by skarekrow** [comment]
I like that much more. Thanks!
