### ISSUE TITLE
iocage exits 0 on errors

### ISSUE THREAD

**Issue by rwestlund** [iocage/iocage#224]
Using HEAD (25727df28a8711d4f8dd413f912f04a1f2a36dc0):

iocage exits with a 0 status even when there's an error.  Example:
```
# iocage create -t nonexistent
This may be a short UUID, template creation only supports TAGs

Proceed? [y/N]: y
Template: nonexistent not found!
Created Templates:

# echo $?
0
```

This and every other error should return a nonzero status; as it is my deploy scripts can't tell that there was an error.

**Comment by skarekrow** [comment]
We normally raise an error, so it will exit on 1. For some reason I forgot to add `exit(1)` on this, if you find others let me know. But exiting on 0 for errors isn't the general behavior.

**Comment by rwestlund** [comment]
Awesome, thanks 👍
