### ISSUE TITLE
‘iocage chroot’ should mount filesystems so that it works with basejails

### ISSUE THREAD

**Issue by dneades** [iocage/iocage#224]
See discussion on #216.

**Comment by skarekrow** [comment]
@dneades This is now in, please test and tell me if this suites your needs :)

**Comment by dneades** [comment]
@skarekrow Unfortunately, the new `iocage chroot` is reproducibly causing a kernel panic for me, at least when applied to a running jail. From my `ssh` session:

```
# iocage list
JID  UUID                                  BOOT  STATE  TAG              TYPE
1    0275dc21-5d10-11e5-9c89-0cc47a1da15a  on    up     elk.araxis.net   basejail
2    06942acb-5d10-11e5-9c89-0cc47a1da15a  on    up     int0.araxis.net  basejail
-    9028f1c4-5d0f-11e5-9c89-0cc47a1da15a  off   down   test             basejail
3    fe4067e8-5d0f-11e5-9c89-0cc47a1da15a  on    up     dmz0.araxis.net  basejail

# iocage chroot elk.araxis.net pkg install py27-salt
Write failed: Broken pipe
```

The `Broken pipe` is because of the kernel panic. From the system’s console:

```
panic: __lockmgr_args: downgrade a recursed lockmgr zfs @ /usr/src/sys/modules/unionfs/../../fs/unionfs/union_vnops
.c:1936

cpuid = 14
KDB: stack backtrace:
#0 0xffffffff80984e30 at kdb_backtrace+0x60
#1 0xffffffff809489e6 at vpanic+0x126
#2 0xffffffff809488b3 at panic+0x43
#3 0xffffffff8092738d at __lockmgr_args+0xe6d
#4 0xffffffff809db44c at vop_stdlock+0x3c
#5 0xffffffff80e7365b at VOP_LOCK1_APV+0xab
#6 0xffffffff81e50ced at unionfs_lock+0x3cd
#7 0xffffffff80e7365b at VOP_LOCK1_APV+0xab
#8 0xffffffff81e50c03 at unionfs_lock+0x2e3
#9 0xffffffff80e7365b at VOP_LOCK1_APV+0xab
#10 0xffffffff809f9ba3 at _vn_lock+0x43
#11 0xffffffff81e50508 at unionfs_readdir+0x148
#12 0xffffffff80e73217 at VOP_READDIR_APV+0xa7
#13 0xffffffff809f72bc at kern_getdirentries+0x21c
#14 0xffffffff809f7078 at sys_getdirentries+0x28
#15 0xffffffff80d4b3f7 at amd64_syscall+0x357
#16 0xffffffff80d30adb at Xfast_syscall+0xfb
Uptime: 7m44s
mps0: Sending StopUnit: path (xpt0:mps0:0:2:ffffffff):  handle 9
mps0: Incrementing SSU count
mps0: Sending StopUnit: path (xpt0:mps0:0:3:ffffffff):  handle 10
mps0: Incrementing SSU count
mps0: Sending StopUnit: path (xpt0:mps0:0:4:ffffffff):  handle 11
mps0: Incrementing SSU count
mps0: Sending StopUnit: path (xpt0:mps0:0:5:ffffffff):  handle 12
mps0: Incrementing SSU count
```

I’m guessing there is an underlying problem with `unionfs` that `iocage chroot` is triggering – you may wish to report that upstream to the FreeBSD devs if you are able to identify what you’re doing to reproduce that :-)

**Comment by skarekrow** [comment]
Will look when I wake up later. I imagine it's because I may not be
checking if the directory is already mounted. Can't remember off the top of
my head if I did,  will report back. Thanks for the heads up.

**Comment by dneades** [comment]
Thank you :-)

**Comment by dneades** [comment]
Here’s a little bit more information – the behaviour still seems (differently) problematic even with the jail stopped:

```
# iocage stop elk.araxis.net
* Stopping 0275dc21-5d10-11e5-9c89-0cc47a1da15a (elk.araxis.net)
  + Running pre-stop         OK
  + Stopping services        OK
  + Removing jail process    OK
  + Running post-stop        OK
# iocage chroot elk.araxis.net pkg install py27-salt
The package management tool is not yet installed on your system.
Do you want to fetch and install it now? [y/N]: y
Bootstrapping pkg from pkg+http://pkg.FreeBSD.org/FreeBSD:10:amd64/quarterly, please wait...
pkg: mkstemp(): Read-only file system
pkg: Error fetching http://pkg.FreeBSD.org/FreeBSD:10:amd64/quarterly/Latest/pkg.txz:
A pre-built version of pkg could not be found for your system.
Consider changing PACKAGESITE or installing it from ports: 'ports-mgmt/pkg'.
```

The `pkg: mkstemp(): Read-only file system` there seems to indicate an issue, and indeed the entire command fails because of that.

I tried it again, just to make sure, then used `Ctrl-C` at the `[y\N]` prompt:

```
[root@bhs-0 ~]# iocage chroot elk.araxis.net pkg install py27-salt
The package management tool is not yet installed on your system.
Do you want to fetch and install it now? [y/N]: ^C
```

Then I tried the third time, and provoked the kernel panic again:

```
[root@bhs-0 ~]# iocage chroot elk.araxis.net pkg install py27-salt
Write failed: Broken pipe
```

Perhaps the filesystem(s) were not unmounted when `iocage chroot` was interrupted by the `Ctrl-C`? Obviously, `iocage chroot` needs to be robust against termination in various ways.

It’s a little unfortunate that the consequences of an error here are so dire – assuming `iocage chroot` traps what signals it can, it still wouldn’t be good for users to risk a kernel panic in the event that they happen to be forced to `kill -9` an `iocage chroot` process! I guess that even this problem could be avoided if `iocage chroot` were to check to see whether the filesystems are already mounted before remounting them, as you are proposing. I suppose `iocage chroot` will also need to be intelligent about whether or not it unmounts the filesystems – perhaps it should always unmount them unless the jail is running?

**Comment by dneades** [comment]
(Heads-up that I have edited my comments above.)

**Comment by skarekrow** [comment]
All but the last one should be an easy fix. We haven't really done any trapping in the script mostly because to do it "right" would require more time then either of us has had. Since it requires us to cleanup, we can't just ignore the ctrl-c since that won't protect the children :( Will work on this here shortly.

**Comment by dneades** [comment]
Understood, thank you.

**Comment by skarekrow** [comment]
@dneades Ok, it all works here, please let me know.

**Comment by dneades** [comment]
Thank you @skarekrow, that does seem to have fixed the kernel panics. (I’m still having problems with the `chroot` commands I’m running actually doing what I want, but I haven’t spent any time looking into this yet, and suspect the fault is nothing to do with `iocage`. I’ll report any further problems if I run into them.)

Thanks again!

**Comment by skarekrow** [comment]
Great! Come back if it's us, I'd be glad to look at it and try to fix it.

**Comment by dneades** [comment]
Thank you!
