### ISSUE TITLE
‘freebsd-update ... fetch’ invocations should work when iocage is run non-interactively (i.e. without a tty/pty)

### ISSUE THREAD

**Issue by dneades** [iocage/iocage#225]
Commit 51e2816fc94ac96e398e7ab8161ddbe391498720 regressed #174.

Note that I have verified that the `freebsd-update` parameter `--not-running-from-cron` is supported on FreeBSD 9.3 (at least as of p20), so I suspect that all instances of `freebsd-update fetch` can simply be substituted with `freebsd-update --not-running-from-cron fetch`.

**Comment by skarekrow** [comment]
This was purposely removed as I switched to doing it in a chroot and it worked non-interactively.  Are you certain there's a problem? If so, it's an easy addition.

**Comment by dneades** [comment]
@skarekrow Yes, this presently fails when one is running iocage over an SSH session that does not have a pty, as is the case, for example, when run via `salt-ssh`. (It’s the lack of a pty that causes the problem, not the non-interactivity per se. I’ll tweak the issue title to make this clear.)

Thanks!

**Comment by skarekrow** [comment]
Ah! Ok then, will make that update. Thanks for the report.

**Comment by skarekrow** [comment]
@dneades Added it back in, thanks again :)

**Comment by dneades** [comment]
@skarekrow Thank you :-) I can confirm that this has solved the problem.

**Comment by skarekrow** [comment]
@dneades That's great to hear. I was under the (wrong) assumption that chrooting would fix it. Oh well, it  fixed a couple other uses like using the systems /usr/src and just generally cleaned the code up. So I appreciate you coming back. It's nice to have people testing these things in addition to us.
