### ISSUE TITLE
Create road map

### ISSUE THREAD

**Issue by xerovis** [iocage/iocage#227]
Myself and a couple of our other devs would like to start contributing to iocage. We have seen iocage V2 being mentioned a number of times but are not sure about the road map. It would be great to know where iocage is going so that we can contribute towards that goal. At the moment we sort of feel like it might be a good idea for iocage v2 to come out and then we can contribute.

**Comment by skarekrow** [comment]
We don't really have a roadmap. Just improving things as needed or suggested. iocage 2.0 will stand for a good bit unless something dire comes along and requires a bug fix. Otherwise, we don't plan on adding any additional features for a little while.

**Comment by xerovis** [comment]
I have seen references to you dropping support for any other jail other than basejails. For someone who wants to come along and contribute that information is almost impossible to find. Its these sorts of things that I think should be written down in a road map or future direction document.

**Comment by cactus** [comment]
> I have seen references to you dropping support for any other jail other than basejails.

Where was this discussed? I must have missed it.

I use thickjails, and it would certainly be unfortunate to lose support for them. I guess I could aways fork and/or just continue to use the current version (works pretty well!). Bummer if true though.

**Comment by xerovis** [comment]
https://github.com/iocage/iocage/issues/216

**Comment by cactus** [comment]
Ah bummer. Guess when it finally happens I will either end up forking for personal use, rewriting in Go or something, or just (most likely) being lazy and using an old version until it stops working well. I tend to prefer thickjails so I can update/upgrade individual jails on different schedules.
