### ISSUE TITLE
Inaccurate ERROR when selecting no with iocage destroy

### ISSUE THREAD

**Issue by xerovis** [iocage/iocage#228]
When I run this command and at the prompt put "n", I get an error message. Why do I have to type "N" why can I not type "n". I would understand if you wanted me to type "Y" as destroying a jail is a bigger deal than not destroying a jail.
<img width="537" alt="screen shot 2015-09-18 at 6 00 25 pm" src="https://cloud.githubusercontent.com/assets/3682121/9954822/6c5c532e-5e2f-11e5-9e18-9634d9f277b9.png">

**Comment by xerovis** [comment]
If I push enter at the prompt, to select the default option [N], I get the same error.

**Comment by skarekrow** [comment]
Did you read the error? It's doing exactly what you asked.

**Comment by xerovis** [comment]
But its not an ERROR and it says it is an ERROR.

**Comment by skarekrow** [comment]
Fair enough :)
