### ISSUE TITLE
iocage create "grep: /etc/devfs.rules: No such file or directory"

### ISSUE THREAD

**Issue by xerovis** [iocage/iocage#229]
I get this message when I try to create a jail. devfs.conf exists but it seems that devfs.rules does not on my system. None of my FreeBSD boxes seem to have devfs.rules

**Comment by skarekrow** [comment]
Hmm odd, that should exist AFAIK. Either way, harmless error, but will do a check for it.

**Comment by xerovis** [comment]
"Hmm odd, that should exist AFAIK."

That is what I thought, but it seems none of my 10.2-RELEASE servers have it.

**Comment by skarekrow** [comment]
My devbox which is 10.2-RELEASE had it. But that could be the result of some other random act. Either way, I now just create an empty one, it does no harm. Glad you caught this before it went primetime.
