### ISSUE TITLE
hbsd fetch verify fails

### ISSUE THREAD

**Issue by shivno** [iocage/iocage#23]
root@vako:~ # iocage fetch
[0] 10-STABLE
[1] 11-STABLE

Which release do you want to fetch? (EXIT) 1
Fetching: 11-STABLE

Downloading: MANIFEST: 100% 1.23Mbit/s Elapsed: 00:00 Remaining: 00:00
Downloading: base.txz:  12% 1.20Mbit/s Elapsed: 00:12 Remaining: 01:15^C
Aborted!
root@vako:~ # iocage fetch
[0] 10-STABLE
[1] 11-STABLE

Which release do you want to fetch? (EXIT) 1
Fetching: 11-STABLE

Traceback (most recent call last):
  File "/usr/local/bin/iocage", line 11, in <module>
    load_entry_point('iocage==0.9.3', 'console_scripts', 'iocage')()
  File "/usr/local/lib/python2.7/site-packages/iocage/main.py", line 89, in main
    cli(obj=MODULES)
  File "/usr/local/lib/python2.7/site-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python2.7/site-packages/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python2.7/site-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python2.7/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/iocage/cli/fetch.py", line 59, in fetch_cmd
    _file=_file, verify=verify, hardened=hardened).fetch_release()
  File "/usr/local/lib/python2.7/site-packages/iocage/lib/ioc_fetch.py", line 131, in fetch_release
    self.http_fetch_release(eol)
  File "/usr/local/lib/python2.7/site-packages/iocage/lib/ioc_fetch.py", line 277, in http_fetch_release
    missing = self.__check_download__(self.files)
TypeError: __check_download__() takes at least 3 arguments (2 given)

zfs destroy download resolves it

**Comment by shivno** [comment]
no it doesnt and i just looked at your last commit

**Comment by skarekrow** [comment]
~~That message is odd as it should read read `self.__check__download(self.files)`, so make sure after you follow the upgrade instructions on the front of the repo.~~

I see a bug though, will push, let me know if this fixes your issue.

EDIT: Derrr that's because you didn't use ``` ``` ``` code tags, so it actually was applying markdown to the post :D

**Comment by skarekrow** [comment]
I can confirm fetching and verification works, but if you `ctrl-c` it, the process will fail with my error message. I'll see what I can do about that.

```
bschneider@hard_pie:~ % sudo iocage fetch
[0] 10-STABLE
[1] 11-STABLE

Which release do you want to fetch? (EXIT) 0
Fetching: 10-STABLE

Downloading: MANIFEST: 100% 2.30Mbit/s Elapsed: 00:00 Remaining: 00:00
Downloading: base.txz:   8% 1.15Mbit/s Elapsed: 00:04 Remaining: 01:00^C
Downloading: base.txz:   8% 1.13Mbit/s Elapsed: 00:05 Remaining: 01:01
Aborted!
bschneider@hard_pie:~ % sudo iocage fetch
[0] 10-STABLE
[1] 11-STABLE

Which release do you want to fetch? (EXIT) 0
Fetching: 10-STABLE

base.txz failed verification, will redownload!
doc.txz missing, will download!
Too many failed verifications!
bschneider@hard_pie:~ % sudo zfs destroy -r zroot/iocage/download/10-STABLE
bschneider@hard_pie:~ % sudo iocage fetch
[0] 10-STABLE
[1] 11-STABLE

Which release do you want to fetch? (EXIT) 0
Fetching: 10-STABLE

Downloading: MANIFEST: 100% 2.09Mbit/s Elapsed: 00:00 Remaining: 00:00
Downloading: base.txz: 100% 1.16Mbit/s Elapsed: 01:04 Remaining: 00:00
Downloading: doc.txz: 100% 1.10Mbit/s Elapsed: 00:01 Remaining: 00:00
Extracting: base.txz...
Extracting: doc.txz...
```

**Comment by skarekrow** [comment]
Alright, I think this is all solved, please test and let me know 👍

**Comment by shivno** [comment]
sorry for not using code, i promise improvement.
works great! you rock.
little bit ot: why did you not use py3?

**Comment by skarekrow** [comment]
That's great to hear! The project is being done for FreeNAS, which currently uses Python 2. When they move to 3, so will iocage 👍
