### ISSUE TITLE
ERROR: unsupported property: pkglist!

### ISSUE THREAD

**Issue by xerovis** [iocage/iocage#230]
When I run "iocage create pkglist=/tmp/pkg.txt" command I get the error:

ERROR: unsupported property: pkglist!

pkglist is documented in the man page but does not show when you run command "iocage get all UUID|Tag".

**Comment by skarekrow** [comment]
@xerovis Please test and tell me if this fixes your issue :)

Thanks!

**Comment by xerovis** [comment]
Just confirmed the issue is fixed.
