### ISSUE TITLE
"iocage destroy -f ALL" does not work

### ISSUE THREAD

**Issue by xerovis** [iocage/iocage#231]
This command does not work, it only destroys the first jail in the list returned by "iocage list"

**Comment by skarekrow** [comment]
That is what `iocage clean -j` is for :)

**Comment by xerovis** [comment]
See iocage man page

The keyword "ALL" will destroy all jails and templates irreversibly!

**Comment by skarekrow** [comment]
D'oh! Thanks! Fixed.
