### ISSUE TITLE
"iocage destroy -f ALL" bad message

### ISSUE THREAD

**Issue by xerovis** [iocage/iocage#232]
When running this command while having no jails, I get the message "ERROR: ALL not found!"

It should really say something like "INFO: There are no jails to destroy"

**Comment by skarekrow** [comment]
This is because it is looking for a jail called ALL. There is no `destroy ALL`.

**Comment by xerovis** [comment]
That is not what the man page says "The keyword "ALL" will destroy all jails and templates irreversibly!"
