### ISSUE TITLE
iocage clean -a

### ISSUE THREAD

**Issue by xerovis** [iocage/iocage#233]
When running this command I get the message "WARNING: this will destroy zroot/iocage". I do not feel that this message describes accurately what is about to happen, i.e. the command is going to remove everything to do with iocage including all jails and all jail data.

The man page doesn't really describe the severity is going to happen either

**Comment by skarekrow** [comment]
It clearly tells you that it is destroying POOL/iocage. Which means everything under and including that dataset. Which means all children as well. The man page is also very clear. https://github.com/iocage/iocage/blob/develop/iocage.8.txt#L106-L112.

**Comment by xerovis** [comment]
The man page explains things in ZFS terms but I am not using ZFS, iocage is using ZFS. When I use iocage, I am expecting iocage to explain what it is doing, not what its doing with the underlying technology iocage is using.
