### ISSUE TITLE
iocage get all UUID|Tag

### ISSUE THREAD

**Issue by xerovis** [iocage/iocage#234]
It seems this does not return all properties. The "quota" property is not returned, have not checked that they all return.

**Comment by skarekrow** [comment]
That is because quota is a ZFS property. Use `iocage df` for this. If you want to use zfs, then do `zfs get POOL/iocage/jails/UUID`. The output below will happen:
```
[brandon@devbox] ~% zfs get -H all tank/iocage/jails/bbf26bee-5ef5-11e5-a368-d05099728dbf | grep quota
tank/iocage/jails/bbf26bee-5ef5-11e5-a368-d05099728dbf  quota   none    local
tank/iocage/jails/bbf26bee-5ef5-11e5-a368-d05099728dbf  refquota        none    default
tank/iocage/jails/bbf26bee-5ef5-11e5-a368-d05099728dbf  org.freebsd.iocage:allow_quotas 0       local
```
As you can see, the only thing labeled `iocage` is what `iocage get all` shows.

**Comment by xerovis** [comment]
I realise it is a property of ZFS but its a property I can set in iocage (and one I wouldn't set in ZFS), so I think its logical to return it in "iocage get all".
