### ISSUE TITLE
Performance and Statistics

### ISSUE THREAD

**Issue by gronke** [iocage/iocage#235]
One very important metric of iocage is the performance. I can imagine people to be using this tool in totally different ways than the developers, but in any way the execution time of any command is relevant.

Let's imagine you want to build a continuous integration service based on iocage. One might guess the most frequent commands would be `create`, `start` and `stop`, but `set` and `list` are as important. It would be nice to save some metrics among with the execution time of any command to figure out what takes the most time and where improvements have the most impact.

Such a metric I have in mind would contain
- Timestamp
- Number of Jails existing
- Number of Jails running
- Command
- Execution Time

Of course many more options can be taken into account as well:
- Execution flame graph
- Memory graph
- IOPS counter

I suggest to embed collection of metrics into iocage, so that it can be (optionally enabled) be used to track the system performance even in edge-case scenarios and on production systems.

```
root@localhost # iocage stats --order=avg_exec_time --show=command,avg_exec_time 

+------------+-----------+
| COMMAND    | AVG_TIME  |
+------------+-----------+
| start      | 1.39s     |
+------------+-----------+
| list       | 0.5s      |
+------------+-----------+
| stop       | 0.4s      |
+------------+-----------+
```

But first of all my question is if others would like to have such a feature and there are if there are any general concerns or requirements.

**Comment by skarekrow** [comment]
Sounds cool! Not something I'd be doing anytime soon, but I don't think that was the point of this ticket. 

Regardless I'll label accordingly :)

**Comment by gronke** [comment]
This has not the highest priority, indeed :)

I was just playing with DTRACE and wondering how I could compare the results with others. For example my development setup does not have tons of Jails running, so I would not notice the impact of changes for large setups. On the other hand it could point us to the lowest hanging fruits for improvement.

**Comment by skarekrow** [comment]
Closing in favor of libiocage handling this.
