### ISSUE TITLE
start rtsold when ip6_addr contains accept_rtadv

### ISSUE THREAD

**Issue by gronke** [iocage/iocage#236]
Enabling and starting rtsold speeds up the time it takes to obtain an IPv6 address after startup. Should we set `rtsold_enable="YES"` in rc.conf when we see accept_rtadv in the `ip6_addr` line?

**Comment by skarekrow** [comment]
I don't see why not. But I'm also not terribly versed in IPv6, so perhaps there's a downside?

**Comment by gronke** [comment]
- There is one more service running in the Jail (Memory usage, more attack surface ...)
- Maybe somebody wants to run another/custom daemon?
- When is the right time to manipulate rc.conf? When setting `ip6_addr` containing `accept_rtadv` or when starting a Jail that has this configuration? If the latter, how do we ensure users can disable rtsold on purpose?

@skarekrow what's best-practice to manipulate a jails rc.conf file? Editing /iocage/jails/.../root/etc/rc.conf?

**Comment by skarekrow** [comment]
Those are fair, but I assume the risk is acceptable, and for those who care they can disable it manually in the jail.

The right time we want to do this is during `set` I believe. That way if the user *does* want to disable it, they don't have to fight it each boot of the jail.

Also yes, that is the best place to manipulate the `rc.conf`.

**Comment by gronke** [comment]
A little comment why this is important: Using IPv6 does not require manually setting an IP address per jail. So for the lazy ones of us, a jail with working network can be forked a static script without having to calculate IPv4 addressed. (DHCP would be neat, but requires access to /dev/bpf, which is a bad idea for many reasons)
