### ISSUE TITLE
portabilitiy of pkglist property

### ISSUE THREAD

**Issue by xerovis** [iocage/iocage#237]
I really like how you have made the properties of a jail portable by making them ZFS properties, its a really cool idea. The pkglist property is linked to a text file and I wonder if that property is portable? If it isn't then why isn't the pkglist property part of a ZFS property instead of linked to a text file?

**Comment by skarekrow** [comment]
It *is* linked to a ZFS property. That property's value is the location to the text file. It is not portable, it's only used for jail creation.
