### ISSUE TITLE
zfs gets REALLY slow when there are 100's of jails. iocage needs a cache layer

### ISSUE THREAD

**Issue by salcedo** [iocage/iocage#238]
iocage would benefit greatly if it had a simple caching layer for all the zfs properties and possibly an as-up-to-date-as-possible status of jails. I have a host currently running over 1000 jails. iocage console, iocage get, iocage list, etc. all take about 20 seconds to complete - and the bottleneck appears to be iocage's reliance on zfs properties which are very expensive operations when one has thousands of datasets.

A solution for this would be to create a default property/global setting that allows one to enable a caching layer based on simple csv's or .db files or whatever is the most trivial to work with via shell scripts. This cache would have to be kept as in-sync with the system as possible without completely invalidating it any time a new jail is created or destroyed - started or stopped.

**Comment by skarekrow** [comment]
This isn't something likely to happen,  but will think on this a bit. Have you tried the latest develop changes? We have made large speed improvements.

**Comment by skarekrow** [comment]
I should clarify not in the immediate future. This would require a daemon of some sort as otherwise we are just moving the bottleneck to checking with the database.

**Comment by salcedo** [comment]
Yep. I'm using iocage-devel from ports - which I understand isn't latest git. The latest ports version I have is 9/18.

The "bottleneck to checking with the database" would not be nearly as expensive as the "zfs get" operations. I'm going to go ahead and fork this and add redis caching to it then. You're welcome to cherry pick later on.

**Comment by skarekrow** [comment]
Interesting. Good luck with that :) Would be great to see a PR if you make progress with this, as this feature certainly has merit. It's just a time problem.

**Comment by Johanhen** [comment]
With third party software iocage will no longer be a zero dependency tool. That is one of the main selling points now. Also Redis is not a standard tool that most of us know, mysql, postgre or sqlite is what the average joe like me know.  so we need to be careful selecting the right backend, and not scare people with a backend that they feel uncomfortable with. ( good documentation and tools will help )
I think however with a database backend iocage will be able to overcome problems mentioned above, and maybe more things are possible like nodes and so on.
Also redis seems like a fast, secure and valid option.

**Comment by pirogoeth** [comment]
@Johanhen imo, Redis is an extremely good choice for a caching layer like this, especially if utilized correctly. It is extremely light, especially compared to mysql or postgres, and remains quick with large datasets, especially compared to sqlite. Also, with some work, the caching layer can be pluggable so that Redis could be optional instead of a hard dependency (which would keep iocage a zero-dependency tool \o/).

**Comment by pr1ntf** [comment]
I agree with @pirogoeth redis is designed for stuff like this. If a regular Joe or Jane can wrap their head around a relational database, they can definitely get started with redis. They have some wonderful [documentation](http://redis.io/documentation) that I keep bookmarked for other projects. 

I'm also on board with this being a "plug in" or extra library or something. "Out of the box" iocage should not require a dependency.

**Comment by pirogoeth** [comment]
@pr1ntf this is where having a plugin/hooking system would really shine, especially if we could provide pluggable pieces as caching layers (redis, riak, w/e), metadata stores (so we don't rely on ZFS properties as heavily; could be redis again, or even a relational store), etc.

**Comment by pr1ntf** [comment]
As far as I know, I think the adding of a library for an external plugin as the way we were heading with that. For instance, I began working on bhyve + iocage integration so I created the `ioc-vmm` library in the `vmm-dev` branch. I If a "redis ninja/hacker/user" wants to start an `ioc-redis` library, I think the iocage team would seriously consider it's use.

**Comment by sean-** [comment]
Suggestion: cache the properties in a shell script that can be slurped in as a single include file and avoid the external dependency on a running binary for as long as possible.  Make the shell cache file a tunable that can be enabled or disabled based on an admins preferences.

**Comment by kreynolds** [comment]
I don't think this is a ZFS problem as much as its a coding inefficiency. If you look at https://github.com/iocage/iocage/blob/develop/lib/ioc-info#L126-L130 you can see where for each jail, it runs 5 zfs command. Altering the script to get all of the properties in one command would make it about 5 times faster. A few other optimizations one could make:

* Get all of the properties for all datasets in one command and use scripting to sort through them (benchmark to see if its worth it)
* Same thing here: https://github.com/iocage/iocage/blob/develop/lib/ioc-info#L71
* Run jls once instead of N times and use scripting both in _find_jail and in _list_jails (benchmark to see if its worth it
* Use -t filesystem to skip poking through snaps

Unless this is changed, using redis won't really help much .. in fact it could be slower.

**Comment by pirogoeth** [comment]
Plus, using Redis (or any other caching mechanism, really), we would have to worry about cache invalidation. How do we determine when data that's cached from the ZFS props is out of date or invalid? This would almost require a daemon to monitor the props and update accordingly (bad).

**Comment by cactus** [comment]
Quite a few things can probably just be done more efficiently in bash/shell as well... for example, this can speed up `df` by quite a bit just by avoiding excessive shellouts.

```
diff --git a/lib/ioc-info b/lib/ioc-info
index e3c9a8e..26fff30 100644
--- a/lib/ioc-info
+++ b/lib/ioc-info
@@ -238,20 +238,16 @@ __list_jails_warden () {
 __print_disk () {
     local jails=$(__find_jail ALL)
 
-    printf "%-36s  %-6s  %-5s  %-5s  %-5s  %-5s %-20s\n" \
+    printf "%-36s  %-6s  %-5s  %-5s  %-5s  %-5s %s\n" \
            "UUID" "CRT" "RES" "QTA" "USE" "AVA" "TAG"
 
-    for jail in $jails ; do
-        uuid=$(zfs get -H -o value org.freebsd.iocage:host_hostuuid $jail)
-        crt=$(zfs get -H -o value compressratio $jail)
-        res=$(zfs get -H -o value reservation $jail)
-        qta=$(zfs get -H -o value quota $jail)
-        use=$(zfs get -H -o value used $jail)
-        ava=$(zfs get -H -o value available $jail)
-        tag=$(zfs get -H -o value org.freebsd.iocage:tag $jail)
-
-        printf "%-36s  %-6s  %-5s  %-5s  %-5s  %-5s %-20s\n" \
-               "$uuid" "$crt" "$res" "$qta" "$use" "$ava" "$tag"
+    for jail in $jails; do
+        zfs list -H \
+            -o org.freebsd.iocage:host_hostuuid,compressratio,reservation,quota,used,available,org.freebsd.iocage:tag \
+            $jail | awk -F '\t' '{
+                if($1!="-")
+                  printf "%-36s  %-6s  %-5s  %-5s  %-5s  %-5s %s\n", $1, $2, $3, $4, $5, $6, $7
+            }'
     done
 }
```

```
# before
$ time iocage df > /dev/null
real	0m0.122s
user	0m0.081s
sys 	0m0.048s

# after
$ time iocage df > /dev/null 
real	0m0.064s
user	0m0.012s
sys 	0m0.062s
```

and that is with only 3 jails.

**Comment by skarekrow** [comment]
@cactus That's a great patch. If you can test it against `develop` and submit a PR, I would happily merge it.

Thanks!

**Comment by kreynolds** [comment]
@cactus precisely!

**Comment by skarekrow** [comment]
@cactus I actually pushed a combination of your and @kreynolds suggested changes just now. The only caveat @kreynolds approach had was a useless first row, which sed is kind enough to remove for us :D. Thanks for the suggestions guys. But PR's are much more useful in this case as we don't always have the time to implement comment suggestions and test them ourselves. Thankfully this one is much more innocuous. Just a note in the future :)

**Comment by skarekrow** [comment]
This won't be happening in the current shell version by us. We would happily look at a PR, but as we don't have any plans for this, I will be closing it.

**Comment by cactus** [comment]
I have been playing around with a Go psuedo-iocage implementation (also wrapping zfs utils). It currently only supports info commands and is super alpha (not even going to link to it). The point is that it is quite a bit faster on some of the informational commands (list, get, etc) with larger jail counts. 

While keeping the main parts of the codebase in shell, it might be worthwhile to add a few "helper utils" in some non-shell language (C or perl maybe to avoid non-base deps) that can better handle string parsing and arrays, to optionally speed up some of the especially slow parts.

Timings..

~~~
$ time iocage  list|wc -l
     188

real	0m3.819s
user	0m0.991s
sys	    0m2.811s

$ time iocage df > /dev/null 

real	0m1.286s
user	0m0.468s
sys    	0m0.965s
~~~

vs 

~~~
$ time not-iocage list|wc -l
     188

real	0m0.332s
user	0m0.137s
sys	    0m0.205s

$ time not-iocage df > /dev/null 

real	0m0.330s
user	0m0.097s
sys    	0m0.234s


~~~

**Comment by salcedo** [comment]
Will be on the look-out for better (and working) jail management solutions. @cactus thanks for sharing!
Wish i had time to help with iocage but it seems to be going in all the wrong directions - glad I cut my losses.

**Comment by pr1ntf** [comment]
@salcedo We wish you the best of luck in the direction you are headed. Have a good one! :smile:
