### ISSUE TITLE
ip4 and ip6 inherit has no effect

### ISSUE THREAD

**Issue by salcedo** [iocage/iocage#239]
Edit: those aren't commit references. it's timestamps.

candykush :: ~ % iocage get all default | grep inherit                         
ip4:inherit
ip6:inherit
candykush :: ~ % iocage get all _wordpress | grep inherit                      
ip4:inherit
ip6:inherit
candykush :: ~ % ck wordpress add <REDACTED>
[iocage@20150921190716]: cloning wordpress jail ...
[iocage@20150921190726]: executing: /usr/local/sbin/iocage clone _wordpress tag='topgrade94fd6d90'
  Successfully created: f98c3d0c-6093-11e5-aff2-0cc47a711c0a (topgrade94fd6d90)

finished ...
[iocage@20150921190726]: setting hostname to <REDACTED> ...
[iocage@20150921190736]: executing: /usr/local/sbin/iocage set hostname='<REDACTED>' 'topgrade94fd6d90'

finished ...
[iocage@20150921190736]: setting boot=on ...
[iocage@20150921190747]: executing: /usr/local/sbin/iocage set boot=on 'topgrade94fd6d90'

finished ...
[iocage@20150921190747]: getting host uuid ...
[iocage@20150921190757]: creating jail fstab ...
[iocage@20150921190757]: creating php-fpm config ...
[iocage@20150921190757]: bringing up the jail ...
[iocage@20150921190809]: executing: /usr/local/sbin/iocage start 'topgrade94fd6d90'
* Starting f98c3d0c-6093-11e5-aff2-0cc47a711c0a (topgrade94fd6d90)
  + Started (shared IP mode) OK
  + Starting services        OK

finished ...
candykush :: ~ % iocage get all topgrade94fd6d90 | grep inherit                
candykush :: ~ % sudo iocage exec topgrade94fd6d90 telnet 127.0.0.1 3306       
Trying 127.0.0.1...
telnet: socket: Protocol not supported
candykush :: ~ % sudo iocage exec topgrade94fd6d90 ifconfig                    
igb0: flags=8843<UP,BROADCAST,RUNNING,SIMPLEX,MULTICAST> metric 0 mtu 1500
	options=403bb<RXCSUM,TXCSUM,VLAN_MTU,VLAN_HWTAGGING,JUMBO_MTU,VLAN_HWCSUM,TSO4,TSO6,VLAN_HWTSO>
	ether <REDACTED>
	media: Ethernet autoselect (1000baseT <full-duplex>)
	status: active
igb1: flags=8c02<BROADCAST,OACTIVE,SIMPLEX,MULTICAST> metric 0 mtu 1500
	options=403bb<RXCSUM,TXCSUM,VLAN_MTU,VLAN_HWTAGGING,JUMBO_MTU,VLAN_HWCSUM,TSO4,TSO6,VLAN_HWTSO>
	ether <REDACTED>
	media: Ethernet autoselect
	status: no carrier
lo0: flags=8049<UP,LOOPBACK,RUNNING,MULTICAST> metric 0 mtu 16384
	options=600003<RXCSUM,TXCSUM,RXCSUM_IPV6,TXCSUM_IPV6>

Yep. Definitely forking once this gets fixed.

**Comment by pannon** [comment]
@salcedo inherit is working in latest develop.

**Comment by salcedo** [comment]
root@candykush:~/iocage # git checkout develop
Switched to branch 'develop'
Your branch is up-to-date with 'origin/develop'.
root@candykush:~/iocage # git pull
remote: Counting objects: 12, done.
remote: Compressing objects: 100% (6/6), done.
remote: Total 12 (delta 10), reused 8 (delta 6), pack-reused 0
Unpacking objects: 100% (12/12), done.
From https://github.com/iocage/iocage
   881cd98..0099364  develop    -> origin/develop
Updating 881cd98..0099364
Fast-forward
 lib/ioc-cmd       |  3 ++-
 lib/ioc-configure | 25 +++++++++++++------------
 lib/ioc-git       | 25 +++++++++++++++++++++++--
 lib/ioc-zfs       |  9 ++++-----
 4 files changed, 42 insertions(+), 20 deletions(-)
root@candykush:~/iocage # make install
Warning: Object directory not changed from original /root/iocage
gzip -cn iocage.8 > iocage.8.gz
mkdir -p /usr/local/sbin
mkdir -p /usr/local/lib/iocage
install -c -m 555 /root/iocage/iocage /usr/local/sbin/
install -c /root/iocage/lib/* /usr/local/lib/iocage/
install -c /root/iocage/rc.d/* /usr/local/etc/rc.d/
install -c iocage.8.gz /usr/local/man/man8/
root@candykush:~/iocage # cd
root@candykush:~ # iocage clone _wordpress tag=testjail
  Successfully created: 2a56e704-60b7-11e5-aff2-0cc47a711c0a (testjail)
root@candykush:~ # iocage get all testjail | grep inherit
root@candykush:~ # iocage start testjail
cannot create 'zroot/iocage/jails/2a56e704-60b7-11e5-aff2-0cc47a711c0a/root': dataset already exists
mount_unionfs: /iocage/jails/2a56e704-60b7-11e5-aff2-0cc47a711c0a/_: No such file or directory
mount_unionfs: /iocage/jails/2a56e704-60b7-11e5-aff2-0cc47a711c0a/_: No such file or directory
mount_unionfs: /iocage/jails/2a56e704-60b7-11e5-aff2-0cc47a711c0a/_: No such file or directory
mount_unionfs: /iocage/jails/2a56e704-60b7-11e5-aff2-0cc47a711c0a/_: No such file or directory
mount_unionfs: /iocage/jails/2a56e704-60b7-11e5-aff2-0cc47a711c0a/_: No such file or directory
mkdir: /iocage/jails/2a56e704-60b7-11e5-aff2-0cc47a711c0a/_/usr: No such file or directory
mount_unionfs: /iocage/jails/2a56e704-60b7-11e5-aff2-0cc47a711c0a/_: No such file or directory
* Starting 2a56e704-60b7-11e5-aff2-0cc47a711c0a (testjail)
  + Started (shared IP mode) OK
  + Starting services        OK
root@candykush:~ # iocage console testjail
Last login: Mon Sep 21 17:05:37 on pts/2
FreeBSD 10.2-RELEASE (GENERIC) #0 r286666: Wed Aug 12 15:26:37 UTC 2015

Welcome to FreeBSD!

Release Notes, Errata: https://www.FreeBSD.org/releases/
Security Advisories:   https://www.FreeBSD.org/security/
FreeBSD Handbook:      https://www.FreeBSD.org/handbook/
FreeBSD FAQ:           https://www.FreeBSD.org/faq/
Questions List: https://lists.FreeBSD.org/mailman/listinfo/freebsd-questions/
FreeBSD Forums:        https://forums.FreeBSD.org/

Documents installed with the system are in the /usr/local/share/doc/freebsd/
directory, or can be installed later with:  pkg install en-freebsd-doc
For other languages, replace "en" with a language code like de or fr.

Show the version of FreeBSD installed:  freebsd-version ; uname -a
Please include that output and any error messages when posting questions.
Introduction to manual pages:  man man
FreeBSD directory layout:      man hier

Edit /etc/motd to change this login announcement.
root@2a56e704-60b7-11e5-aff2-0cc47a711c0a:~ # ifconfig
igb0: flags=8843<UP,BROADCAST,RUNNING,SIMPLEX,MULTICAST> metric 0 mtu 1500
	options=403bb<RXCSUM,TXCSUM,VLAN_MTU,VLAN_HWTAGGING,JUMBO_MTU,VLAN_HWCSUM,TSO4,TSO6,VLAN_HWTSO>
	ether 0c:c4:7a:71:1c:0a
	media: Ethernet autoselect (1000baseT <full-duplex>)
	status: active
igb1: flags=8c02<BROADCAST,OACTIVE,SIMPLEX,MULTICAST> metric 0 mtu 1500
	options=403bb<RXCSUM,TXCSUM,VLAN_MTU,VLAN_HWTAGGING,JUMBO_MTU,VLAN_HWCSUM,TSO4,TSO6,VLAN_HWTSO>
	ether 0c:c4:7a:71:1c:0b
	media: Ethernet autoselect
	status: no carrier
lo0: flags=8049<UP,LOOPBACK,RUNNING,MULTICAST> metric 0 mtu 16384
	options=600003<RXCSUM,TXCSUM,RXCSUM_IPV6,TXCSUM_IPV6>
root@2a56e704-60b7-11e5-aff2-0cc47a711c0a:~ # telnet 127.0.0.1 80
Trying 127.0.0.1...
telnet: socket: Protocol not supported
root@2a56e704-60b7-11e5-aff2-0cc47a711c0a:~ # exit
logout


gg fellerz.
