### ISSUE TITLE
pkglist string instead of file location

### ISSUE THREAD

**Issue by xerovis** [iocage/iocage#240]
We already have the pkgs we want installed in a larger text file, seems a little silly to create a text file from this and then we tell iocage to read the text file. We would like to be able to send through a string with the pkgs we want installed in the jail.

**Comment by pr1ntf** [comment]
The pkg system as it stands right now, works just fine. When dealing with many many packages, it's easier to put them in a text file rather than a large and very long property value.

**Comment by xerovis** [comment]
I asked this because the main use of containers is to have a container per service. This means that the pkglist could/should be quite small. Sure, there are use cases where the pkglist could be large but I would argue that that would be a non standard use of containers.

**Comment by skarekrow** [comment]
Well good thing these are jails ;)
