### ISSUE TITLE
What is the purpose of the blank fstab file?

### ISSUE THREAD

**Issue by xerovis** [iocage/iocage#241]
I noticed my jails have a blank fstab file in the UUID folder. I cannot see anywhere in the man page where it is referenced. Could you tell me what it is used for please?

**Comment by skarekrow** [comment]
It is used as an fstab file. No different then the hosts. When the jail starts, it reads the mounts from that file and mounts them into the jail.

**Comment by xerovis** [comment]
Thanks, now documented somewhere.
