### ISSUE TITLE
iocage set notes="Blah=cheese" "=cheese" not set

### ISSUE THREAD

**Issue by xerovis** [iocage/iocage#243]
I can do the following iocate create notes="Blah=cheese" and the notes property equals "Blah=cheese" but when using set notes="Blah=cheese" the notes property equals "Blah"

**Comment by pointybeard** [comment]
I too am getting this problem.

#### Steps to reproduce:

Create a container, then run the following

`iocage set notes="xxx=yyy" UUID`
`iocage get notes UUID`

#### Expected Output:
`xxx=yyy`

#### Actual Output:
`xxx`

Setting `notes`  during `iocage create ...` works as expected. e.g. `iocage create notes="xxx=yyy"`

**Comment by pointybeard** [comment]
Looks like this problem exists for other properties too.

e.g. `iocage set exec_poststart="aaa=bbb" UUID` exhibits the same problem. It appear to works fine when set during `iocage create ..`

the other `exec_*` properties also exhibit this behaviour.

**Comment by skarekrow** [comment]
This is because we look for the `=` to split our properties. Every property besides `notes` will exhibit this behavior. What is the usecase for `exec_poststart="aaa=bbb"`?

**Comment by pointybeard** [comment]
I figured as much. The use case would be something like:

`echo nginx_enable=YES >> /etc/rc.conf`

There are other ways to solve this, for example in the `iocage create` command or in a separate script, so perhaps it's just a known limitation and doesn't require fixing. It was mainly that the behaviour between `set` and `create` is inconsistent.
