### ISSUE TITLE
Typo in man page: ip6.addr and ip4.addr (dot instead of underscore)

### ISSUE THREAD

**Issue by orichoni** [iocage/iocage#245]
Make sure to follow and check these boxes before submitting an issue! Thank you.

- [x] Supply `iocage --version`

`0.9.9-ALPHA`

- [x] Supply the commands used, along with any steps to recreate it.

`man iocage`

- [x] Provide the output from the command you issued.

` ip6.addr, ip6.saddrsel, ip6`
`                   A set of IPv6 options for the prison, the counterparts to
                   ip4.addr, ip4.saddrsel and ip4 above.
`

 `ip4=new | disable | inherit`
`                   Only applies when vnet=off.  Control the availability of
                   IPv4 addresses.  Possible values are "inherit" to allow
                   unrestricted access to all system addresses, "new" to
                   restrict addresses via ip4.addr above, and "disable" to
                   stop the jail from using IPv4 entirely.  Setting the
                   ip4.addr parameter implies a value of "new".`

- [x] Supply what you expected the result or output to be

` ip6_addr, ip6_saddrsel, ip6`
`                   A set of IPv6 options for the prison, the counterparts to
                   ip4_addr, ip4_saddrsel and ip4 above.
`

 `ip4=new | disable | inherit`
`                   Only applies when vnet=off.  Control the availability of
                   IPv4 addresses.  Possible values are "inherit" to allow
                   unrestricted access to all system addresses, "new" to
                   restrict addresses via ip4_addr above, and "disable" to
                   stop the jail from using IPv4 entirely.  Setting the
                   ip4_addr parameter implies a value of "new".`
- [x] Checked that the problem has not already been fixed on `master` if using
 a stable release.

**Comment by skarekrow** [comment]
@Mrt134 both `ip6_*` and `ip4_*` have the `jail` naming not `iocage`'s which are `_` instead of `.`
