### ISSUE TITLE
iocage clean -j output is broken

### ISSUE THREAD

**Issue by xerovis** [iocage/iocage#246]
I ran git pull  and a iocage clean -a this morning.

I created a script that creates 10 jails in a loop. The jails were created successfully. I range iocage clean -j and the output I got was 10 0's.
<img width="554" alt="screen shot 2015-09-29 at 12 51 37 pm" src="https://cloud.githubusercontent.com/assets/3682121/10154301/dbf944fe-66a8-11e5-9174-bd9d513d5d90.png">

**Comment by skarekrow** [comment]
Please make sure it completed the pull. That output is debug I had in which listed the exit code of the snapshot routine. That was removed in https://github.com/iocage/iocage/commit/88bdb2560b4920a07d75e70448ff763cd5189f33#diff-168db502ffb63d7bfbe72b5476c10104R125 which was 4 days ago.

**Comment by xerovis** [comment]
Yes, you are correct. Forgot to make install clean. Sorry!

**Comment by skarekrow** [comment]
Also I should add thank you for how you changed with filing this issue. The title and the body are precisely what I was angling at!

So thanks again :)
