### ISSUE TITLE
can not reach host ipv6 addresses from jail when using vnet

### ISSUE THREAD

**Issue by antxxxx** [iocage/iocage#246]
I have created a jail with iocage using vnet and assigned ipv4 and ipv6 addresses and default gateways.   

Host ipv4 address: 192.168.1.2
Host ipv6 address: 2001:xxxx:xxxx::2
Jail ipv4 address: 192.168.1.42
Jail ipv6 address: 2001:xxxx:xxxx::42

From the jail I can reach the host and the internet using ipv4 
```
ping 192.168.1.2
PING 192.168.1.2 (192.168.1.2): 56 data bytes
64 bytes from 192.168.1.2: icmp_seq=0 ttl=64 time=0.029 ms
64 bytes from 192.168.1.2: icmp_seq=1 ttl=64 time=0.039 ms
^C
--- 192.168.1.2 ping statistics ---
2 packets transmitted, 2 packets received, 0.0% packet loss

ping 8.8.8.8
PING 8.8.8.8 (8.8.8.8): 56 data bytes
64 bytes from 8.8.8.8: icmp_seq=0 ttl=64 time=0.030 ms
64 bytes from 8.8.8.8: icmp_seq=1 ttl=64 time=0.030 ms
^C
--- 8.8.8.8 ping statistics ---
2 packets transmitted, 2 packets received, 0.0% packet loss
round-trip min/avg/max/stddev = 0.030/0.030/0.030/0.000 ms
```

From the jail using ipv6, I can not reach the host, but I can reach the internet
```
ping6 2001:xxxx:xxxx::2
PING6(56=40+8+8 bytes) 2001:xxxx:xxxx::42 --> 2001:xxxx:xxxx::2
^C
--- 2001:xxxx:xxxx::2 ping6 statistics ---
3 packets transmitted, 0 packets received, 100.0% packet loss

ping6 2001:4860:4860:0:0:0:0:8844
PING6(56=40+8+8 bytes) 2001:xxxx:xxxx::42 --> 2001:4860:4860::8844
16 bytes from 2001:4860:4860::8844, icmp_seq=0 hlim=59 time=16.795 ms
16 bytes from 2001:4860:4860::8844, icmp_seq=1 hlim=59 time=18.984 ms
^C
--- 2001:4860:4860:0:0:0:0:8844 ping6 statistics ---
2 packets transmitted, 2 packets received, 0.0% packet loss
round-trip min/avg/max/std-dev = 16.795/17.890/18.984/1.095 ms

```

Doing some investigation, it appears that ndp entries are not created in the jail for ipv6 addresses on the host.
This can be fixed by doing the following
For each interface on the host, get the mac address and all ipv6 addresses on the interface (there may be multiple ipv6 addresses on an interface)
```
ifconfig re0 ether|grep ether|  awk '{ print $2 }'
ifconfig re0 inet6 |grep inet6 | grep -v scope | awk '{ print $2 }'
```
For each ipv6 address, run this on the jail
```
ndp -s "${ip6}" "${mac}"
```

Once this is run, I can reach the host using ipv6 from the jail

This is all using iocage version 0.9.8.1
```
iocage --version
Version 0.9.8.1 05/23/2017
```
Make sure to follow and check these boxes before submitting an issue! Thank you.

- [x] Supply `iocage --version`
- [x] Supply the commands used, along with any steps to recreate it.
- [x] Provide the output from the command you issued.
- [x] Supply what you expected the result or output to be
- [x] Checked that the problem has not already been fixed on `master` if using
 a stable release.

**Comment by skarekrow** [comment]
I don't have an IP6 capable host anymore, but surely adding all the hosts IP addresses is Not Good™? Does `allow_raw_sockets` at `1` fix this issue as well?
