### ISSUE TITLE
"iocage clean -j" output is too silent.

### ISSUE THREAD

**Issue by xerovis** [iocage/iocage#248]
I created 100 jails and then ran "iocage clean -j" I got no output for quite some time. I think it would be better to give some indication that things are progressing. Maybe output for each jail destroyed or something like that?

**Comment by skarekrow** [comment]
I took a closer look and the problem with this is that we are just destroying the `POOL/iocage` dataset and thus it isn't actually going per jail. If we instead went jail by jail, it would slow things down significantly. You can do a `iocage clean -b` to do just that though. Will think on this one a bit more.

**Comment by skarekrow** [comment]
@xerovis So I added spinners to `iocage clean -j` and `iocage clean -a`. I know it's not incredibly helpful, but it does tell you that something is at least happening. Adding a progress bar for an operation that doesn't normally take too long would have been a lot of effort for little gain.

**Comment by xerovis** [comment]
That is fantastic. I agree that progress would have been too much work. Just want to know something is happening.

**Comment by skarekrow** [comment]
Great! Thanks for bringing this one up.
