### ISSUE TITLE
iocage lightweight jail (clone) switch missing? ip4/ip6_addr=inherit has no effect. Failure to mount unionfs when starting jails?

### ISSUE THREAD

**Issue by salcedo** [iocage/iocage#249]
root@candykush:~ # iocage create -c tag=_wordpress2
  ERROR: invalid switch -c

This is core functionality. By the way, when you're running non-RELEASE base, the argument handling logic is flawed and will not allow one to specify anything other than a basejail when using the pointless "-e" switch. If base default/global option is set to non-RELEASE, iocage is better off allowing it instead of forcing the user to use an asinine "-e" switch. But back to the 1st issue at hand: the -c switch no longer appears to work. Wonderful.

 # iocage start testjail
cannot create 'zroot/iocage/jails/8a813daf-66df-11e5-aff2-0cc47a711c0a/root': dataset already exists
mount_unionfs: /iocage/jails/8a813daf-66df-11e5-aff2-0cc47a711c0a/_: No such file or directory
mount_unionfs: /iocage/jails/8a813daf-66df-11e5-aff2-0cc47a711c0a/_: No such file or directory
mount_unionfs: /iocage/jails/8a813daf-66df-11e5-aff2-0cc47a711c0a/_: No such file or directory
mount_unionfs: /iocage/jails/8a813daf-66df-11e5-aff2-0cc47a711c0a/_: No such file or directory
mount_unionfs: /iocage/jails/8a813daf-66df-11e5-aff2-0cc47a711c0a/_: No such file or directory
mkdir: /iocage/jails/8a813daf-66df-11e5-aff2-0cc47a711c0a/_/usr: No such file or directory
mount_unionfs: /iocage/jails/8a813daf-66df-11e5-aff2-0cc47a711c0a/_: No such file or directory

Jail still starts though. Guess it's now a fact iocage is switching to an inferior experimental file-system for no apparent reason other than to continue a trend of constant foobar?

root@candykush:~ # iocage get all default | grep inherit
ip4:inherit
ip6:inherit

root@candykush:~ # iocage console testjail
root@8a813daf-66df-11e5-aff2-0cc47a711c0a:~ # ifconfig
igb0: flags=8843<UP,BROADCAST,RUNNING,SIMPLEX,MULTICAST> metric 0 mtu 1500
	options=403bb<RXCSUM,TXCSUM,VLAN_MTU,VLAN_HWTAGGING,JUMBO_MTU,VLAN_HWCSUM,TSO4,TSO6,VLAN_HWTSO>
	ether 0c:c4:7a:71:1c:0a
	media: Ethernet autoselect (1000baseT <full-duplex>)
	status: active
igb1: flags=8c02<BROADCAST,OACTIVE,SIMPLEX,MULTICAST> metric 0 mtu 1500
	options=403bb<RXCSUM,TXCSUM,VLAN_MTU,VLAN_HWTAGGING,JUMBO_MTU,VLAN_HWCSUM,TSO4,TSO6,VLAN_HWTSO>
	ether 0c:c4:7a:71:1c:0b
	media: Ethernet autoselect
	status: no carrier
lo0: flags=8049<UP,LOOPBACK,RUNNING,MULTICAST> metric 0 mtu 16384
	options=600003<RXCSUM,TXCSUM,RXCSUM_IPV6,TXCSUM_IPV6>

No inheritance...

root@8a813daf-66df-11e5-aff2-0cc47a711c0a:~ # ping 127.0.0.1
ping: socket: Protocol not supported

The above was already an issue but was closed and considered invalid. I'll include it again in hopes somebody will actually confirm it. However, I will not be surprised if this issue is closed pre-maturely.

**Comment by skarekrow** [comment]
Let me refund you what you paid. Also next time, don't be so hostile and you will find your issues hopefully getting solved.
