### ISSUE TITLE
iocage create exec_start="/bin/sh /etc/rc && touch /var/hi.txt && touch /var/hello.txt" files not created

### ISSUE THREAD

**Issue by xerovis** [iocage/iocage#250]
As the heading says, when I start the jail the files are not created. Should they be created or should I be creating these files using a different property?

**Comment by skarekrow** [comment]
You are using `&&` which waits for an exit code from `rc`. Which I don't believe happens until the jail is shutdown. The property you are looking for is `exec_poststart` https://github.com/iocage/iocage/blob/develop/iocage.8.txt#L595-L601 :)

**Comment by xerovis** [comment]
legend!

**Comment by xerovis** [comment]
I tried iocage create exec_poststart="touch /var/hi-there.txt" start=1 and the file is not created.
