### ISSUE TITLE
Cannot create new user inside jail

### ISSUE THREAD

**Issue by wunki** [iocage/iocage#252]
Hi,

Not sure if this is a bug or something which is wrong with my setup. However, after creating a new jail: `iocage create tag=<tag>` I get the following when inside the jail and adding a user:

    pw: mkdir '/home': Read-only file system
    adduser: ERROR: There was an error adding user (foo).

The difference with my local fs is that I have a symlink from `/home` to `/usr/home`. In the jail this symlink is absent.

Is there a way to fix this so I can freely add new users inside a jail?

_ps: running latest iocage-devel from ports_

Thanks!

**Comment by skarekrow** [comment]
Hello, that means you fetched with a much older version of `develop`.  What you can do is create the symlink yourself in the release datasets root (`/iocage/base/RELEASE/root`) or you can just refetch that RELEASE and it should do it for you :)

**Comment by wunki** [comment]
Problem persists with the latest `iocage-devel` from the ports tree. Version: iocage 1.7.3 (2015/08/13). Did you mean I should compile myself from Github?

**Comment by skarekrow** [comment]
Yes I'm sorry, the ports version is not up to date. Make sure to do this:
```
git clone https://github.com/iocage/iocage
sudo make -C iocage install clean
```
You should now be able to restart that jail and it should create that symlink for you.
