### ISSUE TITLE
jail: ip4.addr: not an IPv4 address: 10.0.0.0.1

### ISSUE THREAD

**Issue by xerovis** [iocage/iocage#254]
When I create a jail, I can set the address to a non ipv4 address without issue. What I cannot do is start a jail without an ipv4 address, I get the above error. Is there a reason I can create a jail without an ipv4 address but not start one?

**Comment by skarekrow** [comment]
You are specifying an ip address, so it is rightly trying that. That is why you are getting this error. If you don't want an ip address just do `iocage create` and that's it. You can then start that jail without an ip address :)

**Comment by xerovis** [comment]
Thanks scarekrow.
I am not asking if I can create a jail without an ip address, I am asking why I can create a jail with an ip4_addr that isn't an ip4_addr but I am not stopped from creating it, I am only stopped from starting it?

**Comment by skarekrow** [comment]
Ah! That is because we don't validate anything you enter for a property value. The error you are getting is from `jail` itself, not iocage.

**Comment by xerovis** [comment]
Awesome thanks for answering.

**Comment by skarekrow** [comment]
No problem :)
