### ISSUE TITLE
Bug #11893 from PC-BSD: iocage causing system reboot instantly

### ISSUE THREAD

**Issue by TheDharc** [iocage/iocage#258]
Hi, I'm reporting here this bug https://bugs.freenas.org/issues/11893#change-58784 still happening even with the last instrctions done.

I'm just a desktop user, so I don't know how I can give more detailed instructions. Another message I see is when stopping a jail: "rctl: RACCT/RCTL present, but disabled; enable using kern.racct.enable=1 tunable".

Please, give me instructions on how I can help you to detect the problem.

**Comment by TheDharc** [comment]
Now when I stop the jail the system does not crash anymore, but the apache daemon in jail keeps running, then when I start the jail again system crashes.

**Comment by skarekrow** [comment]
Interesting. It doesn't say anything on the command line when you run it? Try this:
```
git clone https://github.com/iocage/iocage
cd /that/folder
sudo make install clean
iocage clean -a
iocage fetch release=10.2-RELEASE
iocage create tag=apache24 vnet=off
```

That should put you on the latest and greatest right from this repo. Which I can confirm does not suffer from those problems.

**Comment by TheDharc** [comment]
Same problem. Stopping the jail the service fails to stop, then starting jail again = crash.

**Comment by skarekrow** [comment]
Something is keeping that apache daemon spinning, you will have to find out why. It's odd that the jail is allowing you to start it again, so everything else is shutting down in the jail just fine. Can you lay out the steps you are taking exactly so I can try to reproduce this myself?

**Comment by TheDharc** [comment]
exactly these:

iocage start apache
iocage chroot apache
service apache24 start
Ctrl+D to exit the chroot
iocage stop apache (here the service keeps running)
iocage start apache (here the system reboots)

**Comment by skarekrow** [comment]
Ok, so no configuration has been done on apache? This is just a `pkg install apache24` and those steps, correct?

**Comment by TheDharc** [comment]
correct.

**Comment by skarekrow** [comment]
Just commenting to let you know I have been able to replicate this. Quite weird. Thanks for the report!

**Comment by skarekrow** [comment]
So in your case you will want to be using `iocage console` or `iocage exec` since the jail was running.

```
iocage start apache24
iocage console apache24 OR iocage exec apache24 service apache24 start
iocage stop apache24
```
