### ISSUE TITLE
iocage get all default no longer works

### ISSUE THREAD

**Issue by igalic** [iocage/iocage#259]
on iocage version 0.9.9-ALPHA, when running trying to get all default properties, we see the following error message:

```
~ # iocage get all default
all is not a valid property!
all is not a valid property!
```

same when using `-a` instead of `all`:

```
~ # iocage get -a default
all is not a valid property!
all is not a valid property!
```

**Comment by rwestlund** [comment]
I can confirm this is an issue on HEAD (cc2f932b38f53b174a208288979f4e251129d1cd).
