### ISSUE TITLE
(optionally) skip using freebsd-update for updating (feature/enhancement)

### ISSUE THREAD

**Issue by ekollof** [iocage/iocage#259]
FreeBSD-update can be a bit braindead when it comes to merging files in /etc. Why not copy the base files which don't change (anything except /etc, really) from the releases directory and do a mergemaster afterwards (you need /usr/src for that). FreeBSD-update does not use mergemaster, so sometimes it may ask you to manually merge hundreds of files for /etc, of which most only the rcsid/header changed.

What also would be nice if iocage could do a make installworld into a jail basedir so people can use iocage with HEAD/CURRENT. Currently there is no way.

**Comment by skarekrow** [comment]
We use `etcupdate` to merge the files for thick jails. As those are now deprecated, we are focused on supporting binary only jails. If you want to use installworld, you can create an empty jail with `iocage create -e` and use it there.
