### ISSUE TITLE
base jail support

### ISSUE THREAD

**Issue by MrClayPole** [iocage/iocage#26]
- [0.9.3_1] Supply `iocage version`
- [ iocage create -b tag=cn-jail-wifi-01] Supply the commands used, along with any steps to recreate it.
- [Error: no such option: -b ] Provide the output from the command you issues.
- [ create a base jail with tag cn-jail-wifi-01] Supply what you expected the result or output to be
- [ No ] Checked that the problem has not already been fixed on `master` if using
 a stable release.

Hi, Just wonder if there are plans to support base jails with the python rewrite of iocage?

**Comment by skarekrow** [comment]
There are not sorry. It was just a huge PITA for me. The closest you can get is with templates. They serve a lot of the same functionality.

**Comment by skarekrow** [comment]
I should also point out that we don't use what you knew as `thickjails` with `iocage_legacy` which used a lot of space. We now only use `clonejails`. They're very fast and are essentially a basejail until the systems diverge. Hopefully that helps you!
