### ISSUE TITLE
Unable to set properties at jail creation

### ISSUE THREAD

**Issue by brwilson** [iocage/iocage#260]
Hi, I'm unable to set some properties of jails at creation.

To reproduce:

    $ freebsd-version
    10.2-RELEASE-p5
    $ iocage version
    iocage 1.7.3 (2015/08/13)
    $ iocage create -c tag=bugreport hostname=bugreport allow_raw_sockets=1 ip4_addr="hn0|172.22.222.13"
    $ iocage get hostname bugreport
    713f8fab-72a8-11e5-b7fb-00155dde0905
    $ iocage get allow_raw_sockets bugreport
    0

After the jail is created, I can set the hostname without problems using `iocage set`. Things like the IP address and tag are set successfully, so it's not all properties.

Thanks for writing iocage. I love it!

**Comment by brwilson** [comment]
I checked out the develop branch and the `allow_raw_sockets` property was set correctly and I got an error about `hostname` being an unsupported property, so I guess this isn't an issue anymore. I do have two questions about where you're going with these changes:

Are you permanently removing the hostname property?

The dev version only seems to support base jails. Is support for clones/thick jails being removed?

Thanks!

**Comment by skarekrow** [comment]
The `hostname` property was being misused. You should be using `host_hostname` instead :) As for your other question, thick jails are gone yes. Clones are being tweaked and may or may not make the cut as there is an awful bug with them currently that we can't fix. I'm asking around, but it may not be hopeful to see a resolution for that quickly.

Thanks for the kind words!
