### ISSUE TITLE
rfc: iocage fstab --list <jail>

### ISSUE THREAD

**Issue by igalic** [iocage/iocage#260]
For automation purposes it would be convenient to have a `list` functionality for `iocage fstab`

This could just be the default action, and for jails with an empty (no) fstab file, it could simply print nothing.

**Comment by igalic** [comment]
(btw, i was gonna submit this as PR, but i think i'm too tired to logic right now…)

**Comment by rwestlund** [comment]
You can use `iocage get fstab $JAIL`, but `iocage fstab -l $JAIL` would probably be more intuitive.

**Comment by skarekrow** [comment]
Yeah likely will move this to the `list` function after the major tag change. Too much stuff on the floor to cleanup before that ;)

**Comment by skarekrow** [comment]
@Mrt134 This needs docs now, it added the `-l` and `-h` flags to `fstab`. I put a short example in the commit, if you need more let me know 👍
