### ISSUE TITLE
iocage destroy -f "partialUUID" = ERROR: c9265da1 not found!

### ISSUE THREAD

**Issue by xerovis** [iocage/iocage#261]
Its been a while since I did a git pull but noticed partial UUIDs are not supported on iocage destroy. Is this to be expected.

**Comment by xerovis** [comment]
I noticed that you cannot do partial UUIDs with iocage start either.

**Comment by skarekrow** [comment]
This was removed, and I clarified the docs earlier today : https://github.com/iocage/iocage/commit/ee9db12a9df54f3447229d42e3bf8d5c1e4766fe
