### ISSUE TITLE
rfc: allow `iocage set` to set an arbitrary amount of properties at once

### ISSUE THREAD

**Issue by igalic** [iocage/iocage#262]
Currently (dd0ff99a2d7de96c2be5321855894873fcea54e4), `iocage set` only allows only setting one property at a time.
If it is trivial to extend it to an arbitrary amount, i suggest doing that, for the sake of automation tools, which otherwise would have to call it …many times.

We could also add an `--name` option here, to distinguish the jail's name from the rest of the command line options.

**Comment by skarekrow** [comment]
@Mrt134 This needs to be reflected in the manpage now 👍
