### ISSUE TITLE
Allow an option for no colors

### ISSUE THREAD

**Issue by damnjails** [iocage/iocage#263]
Version 0.9.8.1 05/23/2017

Please add a universal switch to suppress any colorized output. I tend to use different terminal background colors managing several servers. On anything else than standard black iocage's light colorized output is pretty much invisible, e.g. iocage list. So far iocage in mono has been just fine. Or at least make the colors universally visible, e.g. dark blue or green instead of white/light gray (i.e. the way colorized ls output works). Thanks.

**Comment by skarekrow** [comment]
The colors are that way. Your terminal or color scheme are interpreting them differently. I'll see what I can do, but in the meantime I recommend solarized dark.
