### ISSUE TITLE
Stray text in output of "stop" command

### ISSUE THREAD

**Issue by olgeni** [iocage/iocage#263]
Hi,

A very minor cosmetic issue: some extra output is shown when stopping a jail ("processioc-4d5c07cb-5628-11e5-a85b-44a8422dc14d: removed" in this case)

    # iocage stop test 
    * Stopping 4d5c07cb-5628-11e5-a85b-44a8422dc14d (test)
      + Running pre-stop         OK
      + Stopping services        OK
      + Removing jail processioc-4d5c07cb-5628-11e5-a85b-44a8422dc14d: removed
        OK
      + Running post-stop        OK

I have d7b3ff1 from FreeBSD ports.

**Comment by skarekrow** [comment]
I'm unable to replicate this. Can you share how you created that jail please?

**Comment by olgeni** [comment]
I started from scratch after resetting my rpool/iocage and fetching 10.2-RELEASE:

    $ sudo iocage create base=10.2-RELEASE                    
      Successfully created: ddac10d2-7c90-11e5-839a-080027af0e2a (2015-10-27@10:55:34)

I got this:

    $ sudo iocage list                                        
    JID  UUID                                  BOOT  STATE  TAG                  TYPE
    -    ddac10d2-7c90-11e5-839a-080027af0e2a  off   down   2015-10-27@10:55:34  basejail

The I start...

    $ sudo iocage start ddac10d2-7c90-11e5-839a-080027af0e2a
    * Starting ddac10d2-7c90-11e5-839a-080027af0e2a (2015-10-27@10:55:34)
      + Started (shared IP mode) OK
      + Starting services        OK

And stop...

    $ sudo iocage stop ddac10d2-7c90-11e5-839a-080027af0e2a
    * Stopping ddac10d2-7c90-11e5-839a-080027af0e2a (2015-10-27@10:55:34)
      + Running pre-stop         OK
      + Stopping services        OK
      + Removing jail processioc-ddac10d2-7c90-11e5-839a-080027af0e2a: removed
        OK
      + Running post-stop        OK

This is the FS layout at the end, just in case.

    $ zfs list | grep iocage
    rpool/iocage                                                   325M  57.0G    24K  /iocage
    rpool/iocage/.defaults                                          19K  57.0G    19K  /iocage/.defaults
    rpool/iocage/base                                              243M  57.0G    19K  /iocage/base
    rpool/iocage/base/10.2-RELEASE                                 242M  57.0G    19K  /iocage/base/10.2-RELEASE
    rpool/iocage/base/10.2-RELEASE/root                            242M  57.0G   242M  /iocage/base/10.2-RELEASE/root
    rpool/iocage/download                                         82.1M  57.0G    19K  /iocage/download
    rpool/iocage/download/10.2-RELEASE                            82.1M  57.0G  82.1M  /iocage/download/10.2-RELEASE
    rpool/iocage/jails                                            56.5K  57.0G    19K  /iocage/jails
    rpool/iocage/jails/ddac10d2-7c90-11e5-839a-080027af0e2a       37.5K  57.0G  36.5K  /iocage/jails/ddac10d2-7c90-11e5-839a-080027af0e2a
    rpool/iocage/jails/ddac10d2-7c90-11e5-839a-080027af0e2a/root     1K  57.0G   242M  /iocage/jails/ddac10d2-7c90-11e5-839a-080027af0e2a/root

**Comment by skarekrow** [comment]
Interesting. I still cannot reproduce calling stop via the UUID like you have. 

```
[brandon@devbox] ~% sudo iocage create base=10.2-RELEASE
  Successfully created: 8fe8dce5-7cf8-11e5-be88-d05099728dbf (2015-10-27@17:17:51)
[brandon@devbox] ~% sudo iocage start 8fe8dce5-7cf8-11e5-be88-d05099728dbf
* Starting 8fe8dce5-7cf8-11e5-be88-d05099728dbf (2015-10-27@17:17:51)
  + Started (shared IP mode) OK
  + Starting services        OK
[brandon@devbox] ~% sudo iocage stop 8fe8dce5-7cf8-11e5-be88-d05099728dbf
* Stopping 8fe8dce5-7cf8-11e5-be88-d05099728dbf (2015-10-27@17:17:51)
  + Running pre-stop         OK
  + Stopping services        OK
  + Removing jail process    OK
  + Running post-stop        OK
```

The only difference I can see is that I'm using my latest development from GitHub and you are using ports. Maybe something went wrong packaging the port? What is the version of FreeBSD that your host is using? If you don't mind, can you try to replicate this just one more time using the develop branch from GitHub

```
git clone https://github.com/iocage/iocage -b develop
sudo make -C iocage install clean
iocage clean -a
----------------------
REPEAT YOUR STEPS FROM BEFORE
----------------------
```

Thanks!

**Comment by olgeni** [comment]
I got it - I have 10.2-STABLE at r290013, and it has this line in command.c:

    jail_note(j, "removed\n");

It shows the same message when running `jail -r`, so `jail -r "ioc-${_fulluuid}"` in `lib/ioc-rc` is probably the cause.

**Comment by skarekrow** [comment]
I would agree, except this doesn't occur on 9.3-RELEASE+, and I'm on 11-CURRENT and am also unable to reproduce it. But regardless, will just silence the output from it as we certainly don't need to see anything but an error. Will commit this later today, will update this issue when I have, if you would be so kind to test and see if that helps you :)

**Comment by skarekrow** [comment]
@olgeni Ok it has been committed in https://github.com/iocage/iocage/commit/63ccfbe5d7cacf4094835daa4f085b9201e92433, so please pull the latest changes. This should solve your problem.

**Comment by olgeni** [comment]
Fixed - it went away :+1: 

Thanks!

**Comment by skarekrow** [comment]
Awesome! Thanks for the report.
