### ISSUE TITLE
Support for `limits` and `cap` commands

### ISSUE THREAD

**Issue by urosgruber** [iocage/iocage#264]
Are there any plans to support `limits` and `cap` commands in the near future? I began planing moving from legacy version to this but running `iocate limits`gives **Error: No such command "limits"**

**Comment by skarekrow** [comment]
Yes this has been asked before and is set for the 1.0 milestone :)

**Comment by urosgruber** [comment]
@skarekrow do you have timeframe for 1.0 milestone?

**Comment by skarekrow** [comment]
Not currently. Focused on 0.9.9, but shouldn't be too much later than 0.9.9 if I were to guess
