### ISSUE TITLE
iocage destroy -j = lots of lines of errors with grep mentioned

### ISSUE THREAD

**Issue by xerovis** [iocage/iocage#266]
I get about 30 of the below returned to console.

grep: invalid option -- j
Usage: grep [OPTION]... PATTERN [FILE]...
Try `grep --help' for more information.

**Comment by skarekrow** [comment]
That's because there is no `iocage destroy`. It's `iocage clean`.

**Comment by skarekrow** [comment]
But you brought up a fun bug in the process, so fixed that. Thanks!

**Comment by xerovis** [comment]
That is the bug I was referring to :-)
