### ISSUE TITLE
iocage console template fails poorly

### ISSUE THREAD

**Issue by cedwards** [iocage/iocage#269]
Trying to console into a non-running template jail (I realize this may not be supported; accidentally ran into this) results in the following error output. It could probably use a little cleanup.

```
saturn ~ # iocage list -t
JID  UUID                                  BOOT  STATE  TAG     TYPE
-    15dbe7ba-7e8e-11e5-a5be-3417ebb13845  off   down   salted  template
saturn ~ # iocage console salted
cannot open 'zroot/iocage/jails/15dbe7ba-7e8e-11e5-a5be-3417ebb13845': dataset does not exist
cannot open 'zroot/iocage/jails/15dbe7ba-7e8e-11e5-a5be-3417ebb13845': dataset does not exist
[: -ne: unexpected operator
  ERROR: jail: salted is not running!
```

**Comment by skarekrow** [comment]
What version? This should have been fixed in the develop branch.

- Brandon

**Comment by cedwards** [comment]
I'm running a checkout from maybe 2-3 hours ago..

saturn ~ # iocage version
iocage DEVELOP (2015-10-29)

**Comment by skarekrow** [comment]
Odd, was able to reproduce. Will fix, thanks!

**Comment by skarekrow** [comment]
This should be fixed @cedwards, thanks again for the report :)
