### ISSUE TITLE
rc.conf customizations lost when creating from template

### ISSUE THREAD

**Issue by cedwards** [iocage/iocage#270]
Hate to be _that guy_ filing bug after bug but I just discovered another one...

```
saturn ~ # iocage set template=yes salted
saturn ~ # iocage list
JID  UUID  BOOT  STATE  TAG  TYPE
saturn ~ # iocage list -t
JID  UUID                                  BOOT  STATE  TAG     TYPE
-    73bf4d5c-7e91-11e5-8812-3417ebb13845  off   down   salted  template
saturn ~ # iocage create tag=test base=salted host_hostname=test ip4_addr="lo1|10.0.0.20"
```

I'm guessing the ``host_hostname`` argument clobbers any customizations within the ``rc.conf``. My template included some custom packages, configs and enabled services in ``rc.conf``, but any jail created from that template base loses the ``rc.conf`` customizations (but *does* set the hostname)

**Comment by skarekrow** [comment]
Interesting, it's good to be _that guy_ when you have real bugs. I appreciate hearing about them. Will take a look at this.

**Comment by skarekrow** [comment]
@cedwards This should fix your problems. Please report back if it does not :)
