### ISSUE TITLE
/iocage/tags/newtag is not created on first clone

### ISSUE THREAD

**Issue by johnko** [iocage/iocage#272]
I think my version has an issue where `__link_tag` is not called to create the tags shortcut under `/iocage/tags` when cloning from template (which is why I didn't notice this useful feature).

I create my jails using a cloned template, like so:

```
iocage clone $TEMPLATE tag=$JAILNAME ip4_addr="$NICNET"
```

Here's an example of my existing jails and iocage version:

```
# iocage --version                                                                                                                                                                                                      
iocage 1.7.3 (2015/08/13)

# iocage list
JID   UUID                                  BOOT  STATE  TAG
-     36009013-7d5e-11e5-9f97-a0369f2a499e  off   down   buildersquidpkg
4     d4eec6ed-7d5e-11e5-9f97-a0369f2a499e  on    up     squid

# ls -l /iocage/tags/                                                                                                                                                                                                   
total 1
lrwxr-xr-x  1 root  wheel  17 Oct 28 02:43 - -> /iocage/.defaults
```

Workaround: Set the tag property again

```
# iocage set tag=squid d4eec6
# ls -l /iocage/tags/ 
total 1
lrwxr-xr-x  1 root  wheel  17 Oct 28 02:43 - -> /iocage/.defaults
lrwxr-xr-x  1 root  wheel  50 Nov  3 03:05 squid -> /iocage/jails/d4eec6ed-7d5e-11e5-9f97-a0369f2a499e
```

**Comment by johnko** [comment]
What's the `_configured="1"` variable for on
https://github.com/iocage/iocage/blob/master/lib/ioc-zfs#L206

Do we need one on after
https://github.com/iocage/iocage/blob/master/lib/ioc-zfs#L212

**Comment by johnko** [comment]
Maybe it's this commented out `#__configure_jail $pool/iocage/jails/$uuid`
https://github.com/iocage/iocage/blob/master/lib/ioc-zfs#L295

**Comment by skarekrow** [comment]
Nope, we changed how configuration worked and that was left over from testing. This is an odd issue, and one that cannot be replicated currently in the `develop` branch. All my focus is on the new version, so this won't be getting triaged for 1.7.3. Thanks for the issue report though.

**Comment by johnko** [comment]
:ok_hand:
