### ISSUE TITLE
Add --recursive flag to iocage destroy

### ISSUE THREAD

**Issue by rwestlund** [iocage/iocage#275]
Using HEAD (1f72cf04dd584ab8eaeba93576b5784b4f868687).
Related to: #216 silently destroying clones.

I propose adding a `--recursive` flag to `iocage destroy` rather than using `--force` to destroy children.  Consider the following use case:

I want to use `iocage destroy` in a script, but I want it to return with an error if it would destroy multiple jails.  This is currently not possible: I have to supply `--force` to prevent it from asking me whether I'm sure, but then it will proceed to delete cloned child jails whether I want it to or not.

The usage would then be:
```sh
# Only destroy this jail, or exit if it would destroy more than one.
iocage destroy -f test

# Destroy this jail and anything that was cloned from it.
iocage destroy -rf test
```

I think this mirrors `rm -rf` nicely.

**Comment by skarekrow** [comment]
This would then replace the flag for RELEASEs which I suppose we can do. Or we can make this `-R`

**Comment by rwestlund** [comment]
Alternatively, you could keep `--force` for recursively destroying and just not ask for confirmation in the first place; UNIX utilities generally don't.

**Comment by skarekrow** [comment]
Yeah that was the behavior before the last few commits. I may just keep the message and drop the proceed.

**Comment by rwestlund** [comment]
To be clear, the previous behavior was to ask for confirmation to run a destroy operation and then silently destroy any clones.  My suggestion was that it could not ask for confirmation unless it would destroy multiple jails.  So then `iocage destroy test` would "just work" without interaction -- _unless_ there are dependent clones, in which case it would ask or require `--force`.

Regardless of how you decide to do it, I'll be happy so long as I can use `iocage destroy` in such a way that I can be absolutely sure that it will never destroy more than one jail.
