### ISSUE TITLE
When is "underscore" folder mounted in Jail?

### ISSUE THREAD

**Issue by xerovis** [iocage/iocage#276]
We noticed that some jails don't have the folders we created in them. At what stage is the _ folder mounted?

**Comment by pr1ntf** [comment]
Can you please be a bit more specific?

Please take a second to look over the "Raising an issue" section in the [readme](https://github.com/iocage/iocage#raising-an-issue).

Thank you.

**Comment by xerovis** [comment]
I am not exactly sure what more to say.

As I am aware, the "underscore" folder is the read write portion of the jail. Currently on the system I am using, after starting the jail, some folders are created by a script from the Host. These folders are created in the "/iocage/jails/c1216218-89db-11e5-ad54-bc305be3bc90/_" folder. These new folders/files do not show up in the Jail. A previous version of the script worked and now it doesn't, so I would like to know when the "underscore" folder is mounted or put or whatever inside the jail.

**Comment by xerovis** [comment]
Referencing a previous issue I raised - https://github.com/iocage/iocage/issues/242

**Comment by xerovis** [comment]
I am using the Master branch of iocage

**Comment by pr1ntf** [comment]
Okay, so to clarify:

-You create a jail 
-You start the jail 
-You add files into the `/iocage/jails/c1216218-89db-11e5-ad54-bc305be3bc90/_` dataset
-You console into the jail
-You run `ls /mynewfolder/`
-The files are not there

Is that correct?

**Comment by xerovis** [comment]
Yes, this is correct.

**Comment by xerovis** [comment]
I am no longer using the Master branch as I need the jail shutdown feature of "iocage clean -j". Not sure why I have been using the Master branch (mistake in my docs and creating/destroying lots of new hosts), so sorry about this.

**Comment by pr1ntf** [comment]
If you are still reproducing this error when you switch to the `develop` branch, please feel free to let us know in this issue. If we can reproduce this, then we will reopen. 

Thank you for the clarification, by the way. :+1:
