### ISSUE TITLE
How to shutdown and delete all jails?

### ISSUE THREAD

**Issue by xerovis** [iocage/iocage#277]
As I am doing a lot of testing, I need to create, test then shutdown and delete lots of jails. I used to use "iocage clean -j" which used to shutdown and then delete all jails. It does not seem to do this anymore. Is there a way to bulk shutdown all iocage jails?

**Comment by pr1ntf** [comment]
If you are running on branch `master` this is expected. 

`iocage clean -j` will stop jails on the `develop` branch. 

If you are using the `master` branch, you can try using `iocage rcshutdown` to shut down all jails before you run `iocage clean -j`
