### ISSUE TITLE
jexec 1 sh -c "npm install forever -g && cd /usr/local/nodejs/www && npm start" produces kernel panic in 10.2-RELEASE p7

### ISSUE THREAD

**Issue by xerovis** [iocage/iocage#278]
I am trying to track down why running this command results in a kernel panic. We create the iocage jail and then run a command after it has started via a script.

If I run the command manually "npm install forever -g && cd /usr/local/nodejs/www && npm start" on the host there is no kernel panic.

If I run the command manually "npm install forever -g && cd /usr/local/nodejs/www && npm start" from within the jail the same kernel panic issue occurs.

We have not had this issue on Master (which I was mistakenly using for a while).

**Comment by xerovis** [comment]
<img width="272" alt="screen shot 2015-11-14 at 12 40 59 pm" src="https://cloud.githubusercontent.com/assets/3682121/11161609/439e8cac-8acd-11e5-8a7c-f18394b2f812.png">
<img width="668" alt="screen shot 2015-11-14 at 12 33 51 pm" src="https://cloud.githubusercontent.com/assets/3682121/11161608/439e8a54-8acd-11e5-867f-9a4a93e2864a.png">

**Comment by xerovis** [comment]
I should mention that I have no problem running other jexec commands in other iocage jails using the same develop branch. It just seems to be this particular command.

**Comment by skarekrow** [comment]
I would open this on the node and/or the npm issue trackers. As this is the only package I've seen do it. Maybe it needs something particular? I've had lots of weird node issues in and outside of jails with FreeBSD. I tested this by doing `pkg install npm` and then issuing `npm install -g forever`. That seems to randomly work or bring the system down. I'm actually using `-CURRENT`, so this issue at least exists on `10.2-RELEASE` and up. I do not see a `/usr/local/nodejs` directory, so I'm not sure if that's something you have done custom. I'll mark this as a bug for now, so you can easily reference it from the node or npm trackesr. Maybe they will have an idea?

I'm not an avid user of it. So I can't help troubleshoot this further, it just doesn't _seem_ to be an iocage issue, but I may be wrong!

**Comment by xerovis** [comment]
Thanks mate. Told the Node devs to lodge a ticket. Hasn't happened before, must have created 200-300 jails with exact the same config and commands, first time I have seen this issue, though I have been running 10.2-RELEASE p5 and not p7 on the host.

/usr/local/nodejs is a custom folder.

**Comment by skarekrow** [comment]
Interesting. Yeah this is the first time I've seen something like this. Please report back and keep me in the loop, I'm quite curious :)

**Comment by xerovis** [comment]
We did further testing on this issue and its not reproducible on Master but does occur on Develop. We will continue to test this issue.

**Comment by xerovis** [comment]
A change to the jexec command we are running stopped the issue from occurring.
jexec 1 sh -c "npm install npm -g && npm install forever -g && cd /usr/local/nodejs/www && npm start"
Instead of
jexec 1 sh -c "npm install forever -g && cd /usr/local/nodejs/www && npm start"

**Comment by xerovis** [comment]
It seems the guys have narrowed it down to the interaction between npm and zfs permissions used in iocage.

**Comment by skarekrow** [comment]
Any further updates? I was hoping the changes that fixed cloning helped this, but I just had it reoccur. I'm not clear on what you mean with zfs permissions? We don't do anything special to the datasets besides enable `compression`, set `readonly` and our own properties.

Would you be able to share more information?

**Comment by xerovis** [comment]
We do not have any further updates as the change to our npm install command fixed the issue. We will probably come back to this issue at a later date to see if the old command still crashes the host. At the moment we are trying to solve a couple other issues with scaling our infrastructure (hopefully sorted in the next week or so) and then we will come back to this issue.

**Comment by skarekrow** [comment]
Ok, thanks for the heads up.

**Comment by PeterSprague** [comment]
Same issue.  
# npm install -g npm seems to have fixed it.
CouchDB 2.0 now builds

**Comment by xerovis** [comment]
We are getting this issue again with the iocage DEVELOP (2016-01-14) version. We are still running the command that fixed the issue last time but this time it doesn't seem to have fixed the issue.

**Comment by skarekrow** [comment]
I am unable to reproduce this on a fresh pool with the latest `develop` changes. The previous behavior that we were experiencing was unionfs crashing. I would make sure you do a `iocage clean -a` and make sure you are using the latest code.

```
bschneider@iocage-dev:~ % sudo iocage create tag=test vnet=off ip4_addr="vtnet0|192.168.1.75/24"
  INFO: creating zroot/iocage/jails
  Successfully created: 53e4a05b-c3a4-11e5-b869-00a098690e88 (test)
bschneider@iocage-dev:~ % sudo iocage start test
* Starting 53e4a05b-c3a4-11e5-b869-00a098690e88 (test)
  + Started (shared IP mode) OK
  + Starting services        OK
root@53e4a05b-c3a4-11e5-b869-00a098690e88:~ # pkg install -y npm
-- snip --
root@53e4a05b-c3a4-11e5-b869-00a098690e88:~ # npm install -g forever
npm WARN optional dep failed, continuing fsevents@1.0.6
/usr/local/bin/forever -> /usr/local/lib/node_modules/forever/bin/forever
forever@0.15.1 /usr/local/lib/node_modules/forever
├── object-assign@3.0.0
├── path-is-absolute@1.0.0
├── clone@1.0.2
├── colors@0.6.2
├── timespan@2.3.0
├── optimist@0.6.1 (wordwrap@0.0.3, minimist@0.0.10)
├── cliff@0.1.10 (eyes@0.1.8, colors@1.0.3)
├── nssocket@0.5.3 (eventemitter2@0.4.14, lazy@1.0.11)
├── prettyjson@1.1.3 (colors@1.1.2, minimist@1.2.0)
├── winston@0.8.3 (cycle@1.0.3, eyes@0.1.8, async@0.2.10, stack-trace@0.0.9, isstream@0.1.2, pkginfo@0.3.1)
├── nconf@0.6.9 (ini@1.3.4, async@0.2.9, optimist@0.6.0)
├── utile@0.2.1 (async@0.2.10, deep-equal@1.0.1, i@0.3.4, ncp@0.4.2, mkdirp@0.5.1, rimraf@2.5.1)
├── shush@1.0.0 (strip-json-comments@0.1.3, caller@0.0.1)
├── flatiron@0.4.3 (director@1.2.7, optimist@0.6.0, prompt@0.2.14, broadway@0.3.6)
└── forever-monitor@1.6.0 (minimatch@2.0.10, ps-tree@0.0.3, broadway@0.3.6, chokidar@1.4.2)
root@53e4a05b-c3a4-11e5-b869-00a098690e88:~ #
```

As you can see it returns to the prompt in the jail instead of crashing now :)

**Comment by xerovis** [comment]
@skarekrow. Yeah, the issue we are seeing here and the unionfs bug are not related as far as our testing is concerned - I have created several hundred jails on the DEVELOP (2016-01-14) version and have had no issues except the weird /tmp permission issue that I reported earlier. We have no idea why we are seeing the nodejs issue again, we are only seeing it on approx 5% of jails created with nodejs.
