### ISSUE TITLE
Variable typo in commit 261c460

### ISSUE THREAD

**Issue by stewiem2000** [iocage/iocage#280]
In ioc-common (line 95) and ioc-rc (line 494), _jzfs_dataset_nlen is set to "${#_jzfs_dataset}" rather than the correct "${#_jail_zfs_dataset}".  Presumably this came about from the shorter variable names introduced in the commit's changes to ioc-rc?

I can supply a pull-request, but in my fork, I've expanded all occurrences of _jzfs_foo to _jail_zfs_foo for clarity rather than just fixing the two typos.  Let me know if you're interested.

Stewart.

**Comment by skarekrow** [comment]
Hello Stewart,

I took a look at your changes, and I would certainly welcome a PR from you :) These were indeed typos from a clipboard, bah!

**Comment by stewiem2000** [comment]
3c16280 directly addresses the issue -- having wrestled children to sleep, I've (hopefully) separated it out and submitted a pull-request.

87aa0cc fixes unmounting all descendant datasets when stopping a jail; which I noticed when I created a jail for Poudriere that wouldn't stop+restart properly. I can split that out into a pull-request too if it helps?

Stewart.

**Comment by skarekrow** [comment]
Yes splitting that out would be fantastic. It was a small mistake on my part assuming ZFS would actually unmount the children properly. I guess not hah.

Thanks for the fixes Stewart!

**Comment by stewiem2000** [comment]
Yeah, I was looking for a 'zfs umount -r ...', but alas not.  Right, I've added that commit to the branch and created a second PR.

You're welcome to the fixes -- glad they're appreciated (/me new to this ;)).

**Comment by skarekrow** [comment]
:+1: We all start that way!
