### ISSUE TITLE
iocage snapshot doesn't do exact match

### ISSUE THREAD

**Issue by rwestlund** [iocage/iocage#281]
Using HEAD (9a1633aabfe3e84aa1f7861b14741203ff1f7f59):

```
root@r2d2 /u/h/r/a/s/jails# iocage snapshot -n mysnap test
Multiple jails found for test:
  test (/iocage/jails/test)
  test2 (/iocage/jails/test2)
```

This is one of those single-jail commands that shouldn't enumerate all jails unless there's no exact name match.

**Comment by skarekrow** [comment]
This hasn't been converted to using the library, so it doesn't have the same improvements the other commands have yet. There are a few like this.
