### ISSUE TITLE
Consider making templates readonly

### ISSUE THREAD

**Issue by rwestlund** [iocage/iocage#284]
Using HEAD (9a1633aabfe3e84aa1f7861b14741203ff1f7f59):

iocage currently allows templates to be modified through the filesystem.  Given that iocage seems to think about templates as frozen images, does it make sense to make templates readonly?

I'm manually setting the ZFS property `readonly=on` for these templates to protect myself from accidental modification.  I can't think of a reason why anyone would need a template to be writable (aside from setting `template=no`).

**Comment by skarekrow** [comment]
Yeah I think I just forgot to port that behavior if I'm honest. Or I did it manually like you are and forgot I did. Either way, definitely a feature I'll do.

**Comment by gronke** [comment]
@rwestlund I was considering the option to allow creating base-, clone- or standalone-jails from every other existing jail. Thus a template would just be an untouched release jail that might or might not be modified.

I like the idea of locking jails entirely by setting `readonly=on`. That would make sure a certain template does not change at all.

**Comment by rwestlund** [comment]
@gronke I like that idea.  If it were me, I'd get rid of template jails entirely and replace it with "templates" that are only distinguished by having `readonly=on`.  There's currently a lot of complexity with moving datasets around and needing to check both `/iocage/jails/` and `/iocage/templates/` when looking for a jail name.  That complexity could go away.

**Comment by igalic** [comment]
having recently worked thru ***half*** of ioc_create https://github.com/iocage/iocage/pull/293#pullrequestreview-51645449, i would be inclined to agree

**Comment by skarekrow** [comment]
They were only kept this way as historically it was done the same way. The idea was not to completely change the paradigm. You would still need to check for both as legacy and the new templates will exist in that location. 

It would likely require a migration of moving these datasets.

**Comment by igalic** [comment]
meta commentary: `template=yes` is saying a lot more than `readonly=on`
but that does _not_ necessitate that template jails be held in a separate directory.

**Comment by skarekrow** [comment]
Not strictly true, this can be simplified now thanks the removal of TAGs. It was meant to make **using** templates easier by renaming them into an obvious location. I see little benefit to keep the template system at all when we have `clone`. So I'll likely be purging it with some sort of migration.

Nothing will happen in the immediate future, as I'm swamped. But that's my thinking on this right now.

**Comment by gronke** [comment]
> meta commentary: template=yes is saying a lot more than readonly=on

@igalic What is your understanding of a template and what makes it different from a read only jail?

**Comment by igalic** [comment]
a template isn't something that would be started and ran

the word template also implies some holes that need to be filled

**Comment by igalic** [comment]
@skarekrow have we discussed how that interacts with `--pkg=`?

**Comment by skarekrow** [comment]
@igalic No we haven't. But I handled that in `create`. Everything works just the way it did before :+1:
