### ISSUE TITLE
iocage create ip4_addr="vnet0|10.0.0.2" -> iocage get interfaces UUID

### ISSUE THREAD

**Issue by xerovis** [iocage/iocage#288]
When I create the jail I use `iocage create ip4_addr="vnet0|10.0.0.2"` but once created if I run `iocage get interfaces UUID` I get the following returned `vnet0:bridge0,vnet1:bridge1`. I don't even have a bridge1 configured on the host (rc.conf) but iocage creates the extra bridge and extra vnet without any request to do so, not sure why.

I am using the latest develop version as of approx 10 minutes ago.

**Comment by xerovis** [comment]
When starting the example jail above I get the following error from iocage:
`  + Configuring VNETifconfig: create: bad value`

**Comment by xerovis** [comment]
This issue should be considered alongside this question - https://github.com/iocage/iocage/issues/279 My networking configuration is (from what I can gather) slightly different to the official version.

**Comment by skarekrow** [comment]
You're missing the subnet mask in that create command :)

**Comment by skarekrow** [comment]
As for why iocage creates the bridge, it's just an easy solution to a problem we have on the upcoming FreeNAS 10 and this is a solution. It will destroy the bridges when no more jails are running.

**Comment by xerovis** [comment]
So does this mean that there is no need to create the bridges in rc.conf?

**Comment by skarekrow** [comment]
Correct, you shouldn't need to worry about that anymore. I have it doing some auto detection. It should work for simple networking setups, but won't for more advanced ones.
