### ISSUE TITLE
Quick Howto on Github page incorrect

### ISSUE THREAD

**Issue by bobk48** [iocage/iocage#289]
On the main iocage Github  page, there's a Quick Howto section that shows 3 steps-
iocage fetch
iocage create tag=myjail ip4_addr="em0|192.168.1.10/24"
Iocage start myjail
I tested these commands on both PCBSD 10.2 desktop, and TrueOS using RELEASE 10.2, version 1.7.3.
If em0 is the network interface that exists on the host (as determined by an ifconfig on the host) before you give these 3 commands, then the start command does NOT give myjail a reachable IP address, from the host or the network. As I noted in my previous issue post, the 3 commands shown above only allow host or network connections to the host IP address, not to myjail.
My issue is that if someone at iocage could replace that 3 step procedure with something that actually works for a shared IP networked jail (NOT VNET!) so that myjail is reachable from the host or the network, your documentation would benefit TREMENDOUSLY, IMHO.
Also, then I could actually advertise iocage more effectively to a larger audience in my capacity to do so.
Thanks!

**Comment by skarekrow** [comment]
Those steps do work for shared IP networking. It is there as an example, not to be blindly copied and pasted. You need to make sure that you replace `em0` with whatever your host interface is, and `192.168.1.10/24` with the proper IP address/subnet mask. We are including it just so you know how it likes to be formatted, nothing more.
