### ISSUE TITLE
How to handle discrepancy of what release means?

### ISSUE THREAD

**Issue by igalic** [iocage/iocage#294]
iocage fetch takes an argument that's called release, but does not contain the `-patch`.
As soon as a template / jail is created, `iocage list` will report the full freebsd-release *with* the  `-patch`.

What's a sensible way to deal with this discrepancy?

**Comment by skarekrow** [comment]
It's only relevant to the directory FreeBSD has in its mirror and what the user types. The patch isn't user friendly. There is no discrepancy :)

You're seeing that for completion sake, but the `cloned_release` property has the same value.
