### ISSUE TITLE
nameserver="10.0.0.1" and resolv.conf inside jail issue

### ISSUE THREAD

**Issue by xerovis** [iocage/iocage#296]
I know its a crap heading but I am not sure what else to put....

We are creating jails via a script.
The script creates the jail and installs pkg's in the jail. We are finding that the 13th jail created fails to use resolv.conf as set by the property nameserver="10.0.0.1". It uses its own ip 10.0.0.13 (we can see the traffic in tcpdump).

The reason I am asking the question here is:
1. From memory when a jail tries to communicate with 127.0.0.1 the traffic goes to its own IP, which in this case is 10.0.0.13. This would point to resolv.conf not being set at the time we try install pkg's
2. We think this issue might be from a slowdown in ZFS, which is producing the problem.
3. Once the jail is created DNS works perfectly again.

We are going to put a 5 second sleep in our script to see if this fixes the issue. I will report back once its done.

**Comment by xerovis** [comment]
We added a 5 second delay:
1. after reloading pf.conf and before starting the Jail and
2. after starting the jail and when we started to install packages

This resolved the issue. iocage must not be waiting for a return from a command before reporting that the command was successful to the user.

**Comment by xerovis** [comment]
I should say that we are unable to replicate this issue on SSD drives but can replicate the issue using 15K SAS drives.

**Comment by xerovis** [comment]
We dropped the delay down to 1 second and our scripts still work.

**Comment by skarekrow** [comment]
Interesting. I only test using SSD's, so haven't caught this myself. Can you post your script so I can try to reproduce it here? I'd hate to add a blanket sleep as that just makes everything slower when you start creating many, many jails. But I also want it to work :P So will do what's necessary here.

**Comment by xerovis** [comment]
One of our guys is going to look into this issue tomorrow in the hopes we can fix the bug.

The script isn't complex, it just creates some pf rules, starts the jail and then installs some pkg's. It seems that when starting a jail something isn't waiting until things like /etc/resolv.conf is updated before returning that the jail started successfully.

**Comment by skarekrow** [comment]
Interesting. Well I'm looking forward to what he finds/his fix.

**Comment by xerovis** [comment]
This is what I got back from the guys:

lib/ioc-rc: line 251 - removed the & from the end of the line which causes that line to fork into its own process, running in parallel to the main iocage script

**Comment by skarekrow** [comment]
Yeah that was something @pannon did and I believe he had a reason to make it fork out. Maybe not. I'm going to remove it for now, and if something comes up we can add it back and make it sleep. Thanks for helping!
