### ISSUE TITLE
Permissions problem in base

### ISSUE THREAD

**Issue by Peter2121** [iocage/iocage#299]
I'm trying to install iRedMail into iocage jail (FreeBSD 10.2) on PCBSD 10.2.
There is nothing special with iRedMail, it's just several ports with additional Python software.
The install is finished, but some services don't start. After some investigations I've found the following permissions issues:
1. /lib/libgcc_s.so.1 has -rwxrwx--x permissions, owned by root:wheel. Adding a+r (-rwxrwxr-x) solved the problem of starting sogod service
2. /usr/lib/libssl.so.7 has -rwx------ permissions, owned by root:wheel. Adding a+rx (-rwxr-xr-x) was necessary to start amavisd service
3. /lib/libcrypto.so.7 has -rwx------ permissions, owned by root:wheel. Adding a+rx (-rwxr-xr-x) was necessary to start amavisd service

It seems that these files are in the iocage base. How should I configure iocage to put the correct permissions? 

PS Maybe there are other issues with other files, I did not check the whole config...

**Comment by skarekrow** [comment]
What is your version that you have installed?

`iocage --version`

This was an bug introduced and fixed shortly after.

**Comment by Peter2121** [comment]
% iocage --version
iocage DEVELOP (2015-12-07)

**Comment by skarekrow** [comment]
Ok that's what I suspected. Do you have any jails you care about on there?

**Comment by Peter2121** [comment]
i can destroy my jail, but it woul be nice to know if there are other ways ;)

**Comment by skarekrow** [comment]
Well it's just easiest. This is `develop` there will be those kinds of changes happening ;) I wouldn't but any important data on it.

So with that in mind:
```
git clone -b develop https://github.com/iocage/iocage
make -C iocage install clean
iocage clean -a
iocage fetch release=10.2-RELEASE
```
Should get you going. Like I said though, this is the develop branch, caveat emptor! Good luck :)
