### ISSUE TITLE
iocage list = cannot open 'zroot/iocage/jails/UUID': dataset does not exist

### ISSUE THREAD

**Issue by xerovis** [iocage/iocage#301]
When doing a bulk destroy in one terminal window AND doing a iocage list in another window, I get this error, multiple times. I would expect that this error would not show as it comes across as a large issue when in fact its no issue at all.

**Comment by pr1ntf** [comment]
I hate to be a stickler about things like this, but in the future can you put error codes in the *BODY* of your issue? This helps keep things better organized and easier to read. 

Something like:
```
% iocage list
cannot open 'zroot/iocage/jails/UUID': dataset does not exist
```

You can check out our guide on raising an issue [in the readme](https://github.com/iocage/iocage/tree/develop#raising-an-issue). 

We will see if we can reproduce this error. Again, sorry to be a pain about things like this.

**Comment by skarekrow** [comment]
I'm able to reproduce this. I *would* say don't do these things concurrently, but at the same time this is a harmless list. I'll look into silencing it.

**Comment by skarekrow** [comment]
Should be good to go now @xerovis :)
