### ISSUE TITLE
Trying to upgrade a running jail fails silently

### ISSUE THREAD

**Issue by asomers** [iocage/iocage#301]
Make sure to follow and check these boxes before submitting an issue! Thank you.

- [x] Supply `iocage --version`
- [x] Supply the commands used, along with any steps to recreate it.
- [x] Provide the output from the command you issued.
- [x] Supply what you expected the result or output to be
- [x] Checked that the problem has not already been fixed on `master` if using
 a stable release.

If you try to upgrade a clone jail that's already running, nothing will happen.  I believe that cli/upgrade.py has an indentation error at line 62.  If that line were deindented, then iocage would attempt to upgrade the jail whether or not it had already been started.  As is, `iocage upgrade` does nothing for jails that are already running.  I haven't tried using master, but I've verified that the source code looks the same.

```
>iocage --version
Version 0.9.8.1 05/23/2017
> iocage upgrade -r 11.1-RELEASE buildmaster
>
```

**Comment by skarekrow** [comment]
@asomers Spot on! Thanks, it's fixed 👍
