### ISSUE TITLE
Strange issue with MySQL permissions

### ISSUE THREAD

**Issue by Peter2121** [iocage/iocage#302]
I installed sogo in iocage jail.
The daemon cannot connect to MySQL server installed in the same jail.

When I test manually - it works for localhost connection:

root@mail:~ # mysql -h localhost -u sogo -p
Enter password:
Welcome to the MySQL monitor.  Commands end with ; or \g.

...but it does not work for 127.0.0.1 connection:

root@mail:~ # mysql -h 127.0.0.1 -u sogo -p
Enter password:
ERROR 1130 (HY000): Host 'mail' is not allowed to connect to this MySQL server

In my /etc/hosts (inside jail) I have the following lines:
127.0.0.1		localhost localhost.localdomain
192.168.101.121		mail mail.domain.com

ifconfig is as follows:
root@mail:~ # ifconfig
em0: flags=8843<UP,BROADCAST,RUNNING,SIMPLEX,MULTICAST> metric 0 mtu 1500
	options=9b<RXCSUM,TXCSUM,VLAN_MTU,VLAN_HWTAGGING,VLAN_HWCSUM>
	ether 00:50:56:b0:70:89
	inet 192.168.101.121 netmask 0xffffffff broadcast 192.168.101.121
	media: Ethernet autoselect (1000baseT <full-duplex>)
	status: active
lo0: flags=8049<UP,LOOPBACK,RUNNING,MULTICAST> metric 0 mtu 16384
	options=600003<RXCSUM,TXCSUM,RXCSUM_IPV6,TXCSUM_IPV6>

Obviously, in sogo.conf the database server is mentioned as 127.0.0.1 (so it cannot connect).

I don't understand the behavior of MySQL and it seems to be difficult to adjust all config files to replace 127.0.0.1 by localhost. Is there any way to get it working with 127.0.0.1 without modifying MySQL permissions?

**Comment by skarekrow** [comment]
We aren't support for other software ;) But it seems [this](http://stackoverflow.com/questions/19101243/error-1130-hy000-host-is-not-allowed-to-connect-to-this-mysql-server) can help you. This isn't an iocage bug.

**Comment by Peter2121** [comment]
I understand that it is not bug of iocage. Neither of MySQL.
I just want to understand (sorry, there is no doc about it) how does iocage manage loopback interface.
There is no 127.0.0.1 address visible inside jail at the ifconfig level, but network services are bound to this address, I can connect to open ports on 127.0.0.1, BUT source address of these connections is NOT from 127.0.0.0/8 network. 
I opened this issue as I suppose that other people could have the same problem, so a small explanation from iocage developers would be interesting.

**Comment by skarekrow** [comment]
With shared networking (the default) there isn't a loopback device because your jail's IP is an alias on the hosts NIC. If you want/need a loopback device, then I would suggest using VNET. Otherwise, you can set up a new lo1(cloned interfaces) and give the jail an additional IP during jail creation or afterwards with `iocage set`.

**Comment by Peter2121** [comment]
I understand using cloned interfaces for jail loopback. 
I'm trying to understand where are the network services, configured with 127.0.0.1 address bound in iocage jail? And how can I connect to these services from the jail who has no 127.0.0.1 address configured?
The question is really important for me as redistributing of iocage jails with network services (jail internals) configured to bind to 127.0.0.1 is much more simple that redistributing of jails with services configured to bind to real IPs.

**Comment by skarekrow** [comment]
Inside a shared ip jail `127.0.0.1` redirects to the first IP a jail has been given. So like I said previously, either use the cloned interfaces if you want a true loopback device that doesn't speak on the network, or use VNET. Really no other proper solution.

**Comment by Peter2121** [comment]
> Inside a shared ip jail 127.0.0.1 redirects to the first IP a jail has been given.
This IS the answer I was waiting for! Thank you very much!
I think that this information is really merits to be in iocage docs.
