### ISSUE TITLE
Attributes not preserved across export/import?

### ISSUE THREAD

**Issue by wkatsak** [iocage/iocage#304]
Hello,

I am not sure if I am misunderstanding an intention, or if it hasn't been implemented yet. I read somewhere (can't find it again now!) that iocage uses ZFS attributes for settings, so the settings can be preserved when the jails are moved around, etc. without any config files. I sort of expected this to be the case across an export/import.

I just did this, and it didn't transfer my attributes, so I looked further and realized that we only tar up the jail to archive it, not use zfs send. Should we be using zfs send? Is this not even supposed to be a feature? Just curious, as it sounded like a really cool idea.

-Bill

**Comment by skarekrow** [comment]
This is the current behavior of `develop` :)
