### ISSUE TITLE
iocage create command sanity check

### ISSUE THREAD

**Issue by kairu0** [iocage/iocage#305]
On iocage 0.9.8.1 (FreeBSD 11.1-RELEASE), if I run a certain incorrect "create" command, such as:

> iocage create -e greatjail1

which I understand isn't the correct syntax but I digress, then iocage creates the ZFS datasets but an incomplete list of attributes for the jail. Having this incomplete jail there will break commands such as "iocage list" because iocage can't retrieve all the attributes of the new jail.

I'd like to request more sanity checks for syntax of the create command.

**Comment by skarekrow** [comment]
This isn't valid on 0.9.9, please follow the checkboxes before filing an issue, thanks!

```
╰─ iocage create -e test
test is not a valid property!
╰─ iocage --version
0.9.9 07/28/2017
```
