### ISSUE TITLE
0.9.9:  No module named 'verboselogs'

### ISSUE THREAD

**Issue by AK107** [iocage/iocage#306]
On each command i've got: 
> "ModuleNotFoundError: No module named 'verboselogs'"

For example:
> % iocage --version                                                                                                                        
> Traceback (most recent call last):
>   File "/usr/local/bin/iocage", line 6, in <module>
>     from iocage.main import cli
>   File "/usr/local/lib/python3.6/site-packages/iocage/main.py", line 36, in <module>
>     import iocage.lib.ioc_check as ioc_check
>   File "/usr/local/lib/python3.6/site-packages/iocage/lib/ioc_check.py", line 30, in <module>
>     import iocage.lib.ioc_common
>   File "/usr/local/lib/python3.6/site-packages/iocage/lib/ioc_common.py", line 37, in <module>
>     import iocage.lib.ioc_logger
>   File "/usr/local/lib/python3.6/site-packages/iocage/lib/ioc_logger.py", line 31, in <module>
>     import verboselogs
> ModuleNotFoundError: No module named 'verboselogs'

But:
> ===>  Installing for py27-verboselogs-1.6
> ===>  Checking if py27-verboselogs already installed
> ===>   Registering installation for py27-verboselogs-1.6 as automatic
> Installing py27-verboselogs-1.6...
> 
> ===>>> Re-installation of py27-verboselogs-1.6 complete

Or it needs any other dependencies?

**Comment by kdbruin** [comment]
The dependencies have been updated. It should install py36-verboselogs-1.6 now. I did the upgrade about an hour ago.

**Comment by AK107** [comment]
Oh, thx!
Found it as: http://www.freshports.org/devel/py3-verboselogs

one more (bug?):

% iocage fetch
...

No updates needed to update system to 11.1-RELEASE-p0.
No updates are available to install.
Run '**/tmp/tmpgbxpcvtt** fetch' first.

**Comment by skarekrow** [comment]
That's not a bug ;) that's the update at the end of fetch.
