### ISSUE TITLE
Jails Lose Network After a While

### ISSUE THREAD

**Issue by maaatts** [iocage/iocage#308]
First of all, the versions of FreeBSD and iocage.

    root@puter:~ # uname -ro
    FreeBSD 10.2-RELEASE-p7
    root@puter:~ # iocage version
    iocage 1.7.3 (2015/08/13)

After a few hours of operation, the services running in jails fail to start.

I create the jails with command `iocage create tag=somejail ip4_addr="re0|192.168.1.xxx"`, after I created more jails and installed some services in each of them (Apache, ZNC, MySQL).

However, after a few hours, the services stop working. If I try to restart them, I get an error along the lines of `Can't assign requested address`.

Trying to restart ZNC bouncer:

~~~
root@puter:~ # iocage console znc
root@znc:~ # service znc start
Starting znc.
[ .. ] Checking for list of available modules...
[ >> ] ok
[ .. ] Opening config [/usr/local/etc/znc/configs/znc.conf]...
[ >> ] ok
[ .. ] Loading global module [webadmin]...
[ >> ] [/usr/local/lib/znc/webadmin.so]
[ .. ] Binding to port [1025] using ipv4...
[ !! ] Unable to bind [Can't assign requested address]
[ ** ] Unrecoverable config error.
~~~

If I stop a jail using `iocage stop somejail`, I get the same error

~~~
# iocage stop apache
* Stopping 904a6c7e-acf9-11e5-a1bc-1c872c60d5f1 (apache)
  + Running pre-stop         OK
  + Stopping services        OK
ifconfig: ioctl (SIOCDIFADDR): Can't assign requested address
  + Removing jail process    OK
  + Running post-stop        OK
~~~

When I restart iocage with `service iocage restart`, everything starts working again (for a few hours).

I don't even know where to start with solving this issue and so any help would be greatly appreciated.

Thanks

**Comment by xerovis** [comment]
We have approximately 200 jails running on iocage at the moment, all with their own IP and have never seen this issue. I would look to see if there is a problem with your Host network card.

**Comment by skarekrow** [comment]
Hello @maaatts, like @xerovis said it's likely a host issue. You must have faulty hardware. Good luck!

**Comment by maaatts** [comment]
Yeah, you're right; this doesn't really seem like a bug with iocage.

However could you help me with trying to fix this? I am just using the onboard gigabit NIC on my motherboard, and the host computer seems to stay up even while the jails are down.

Thanks again

**Comment by skarekrow** [comment]
I really don't have a ton of time to help you troubleshoot your hardware :)

But here's what I would check:
```
- Try another network port
- Check the ethernet cable
- Make sure no other device on the network is using that IP address (probably this)
```

Good luck!
