### ISSUE TITLE
iocage wont upgrade properly

### ISSUE THREAD

**Issue by johnramsden** [iocage/iocage#309]
When I run ```iocage upgrade -r 11.1-RELEASE  <jail>``` i get an upgrade that appears successful but afterwards the jail appears to still be 11.0-RELEASE.

After the upgrade if I run update it appears to think its still on 11.0.

If I check the userland in the jail:

```
freebsd-version
11.0-RELEASE-p11
```

If I try to update

```
iocage update stratus

* Updating stratus to the latest patch level... 
Looking up update.FreeBSD.org mirrors... 4 mirrors found.
Fetching metadata signature for 11.0-RELEASE from update6.freebsd.org... done.
Fetching metadata index... done.

...
```

I would have expected to see:

```
Looking up update.FreeBSD.org mirrors... 4 mirrors found.
Fetching metadata signature for 11.1-RELEASE from update4.freebsd.org... done.
Fetching metadata index... done.
```

If I give it time it appears to do the 11.0 update.

If I try the upgrade again:

```
iocage upgrade -r 11.1-RELEASE stratus

Jail: stratus is already at version 11.1-RELEASE!
```

- [x] iocage --versio: 0.9.9.1 08/01/2017
- [x] Supply the commands used, along with any steps to recreate it.
- [x] Provide the output from the command you issued.
- [x] Supply what you expected the result or output to be
- [x] Checked that the problem has not already been fixed on `master` if using
 a stable release.

**Comment by skarekrow** [comment]
Ok so this was actually `update` using `cloned_release` which it shouldn't have been. I fear that's what reverted your `freebsd-version` back to 11.0. I couldn't replicate that behavior, and after this patch everything seems to work correctly.

Lemme know 👍

**Comment by johnramsden** [comment]
Thanks! I'll give it a shot and let you know.

**Comment by skarekrow** [comment]
Do note that this particular jail will likely have issues until it's upgraded properly, but any other jails you haven't done this on should be good to go

**Comment by johnramsden** [comment]
What version will I likely have to be on to see this change? Until then is there a way to change ```cloned_release``` to `release`?

**Comment by skarekrow** [comment]
HEAD. It's not in a release.  But will be in the next. Do not change that property, its important and unrelated to this fix. Your best bet is to snapshot and then try updating or upgrading and hope it replaces those old binaries. Or change your release property to the 11.0-R and try to upgrade again.

**Comment by johnramsden** [comment]
I tried changing release and I get:

```
iocage set release=11.0-RELEASE stratus

release cannot be changed by the user.
```

Should I try changing it with `zfs set`?

---

When/if I can change it how do I upgrade? Won't it do the same thing?

**Comment by skarekrow** [comment]
You would want the `config.json` at `/iocage/jails/stratus`. Yeah you'll get this same issue if you don't manually install from git. Or you can wait until the tagged release. :+1:

**Comment by johnramsden** [comment]
@skarekrow So I was getting tired of waiting and went ahead and installed from git. I don't know if it's at all related to the fact that I'm running in a venv, I shouldn't think it would make a difference, but I'm not able to download updates from any mirrors. 

```
iocage update stratus                                                    john@wrath

* Updating stratus to the latest patch level... 
Looking up update.FreeBSD.org mirrors... 4 mirrors found.
Fetching metadata signature for 11.1 from update5.freebsd.org... failed.
Fetching metadata signature for 11.1 from update6.freebsd.org... failed.
Fetching metadata signature for 11.1 from update4.freebsd.org... failed.
Fetching metadata signature for 11.1 from update3.freebsd.org... failed.
No mirrors remaining, giving up.
```

I'm able to download updates fine on my machine so I don't see why it would be any different for iocage. Other than the mirror problem everything seems to be running fine.

**Comment by skarekrow** [comment]
@johnramsden I suspect that’s because it’s actually using the older version still. You can see the release red looking for is 11.1 and not 11.1-RELEASE. Perhaps a bug crept in though as well. 

I’ll look tomorrow and see what’s going on :)

**Comment by johnramsden** [comment]
@skarekrow So I got it to start the upgrade by changing `cloned_release` and `release` in the `config.json` to `11.0-RELEASE`. I tried just changing release, but because `cloned_release` was still at `11.1 -RELEASE ` it wouldn't work and gave me the error message:

```
iocage upgrade -r 11.1-RELEASE  stratus                                  john@wrath 
tmprwmg4p1d: Cannot upgrade from 11.1-RELEASE to itself                                                    
Traceback (most recent call last):                   
  File "/usr/local/bin/iocage", line 10, in <module> 
    sys.exit(cli())       
  File "/usr/local/opt/iocage/iocage/venv/lib/python3.6/site-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)                
  File "/usr/local/opt/iocage/iocage/venv/lib/python3.6/site-packages/click/core.py", line 697, in main    
    rv = self.invoke(ctx) 
  File "/usr/local/opt/iocage/iocage/venv/lib/python3.6/site-packages/click/core.py", line 1066, in invoke 
    return _process_result(sub_ctx.command.invoke(sub_ctx))                                                
  File "/usr/local/opt/iocage/iocage/venv/lib/python3.6/site-packages/click/core.py", line 895, in invoke  
    return ctx.invoke(self.callback, **ctx.params)   
  File "/usr/local/opt/iocage/iocage/venv/lib/python3.6/site-packages/click/core.py", line 535, in invoke  
    return callback(*args, **kwargs)                 
  File "/usr/local/opt/iocage/iocage/venv/lib/python3.6/site-packages/iocage/cli/upgrade.py", line 115, in cli                       
    root_path).upgrade_jail()                        
  File "/usr/local/opt/iocage/iocage/venv/lib/python3.6/site-packages/iocage/lib/ioc_upgrade.py", line 90, in upgrade_jail           
    raise RuntimeError("Error occured, jail not upgraded!")                                                
RuntimeError: Error occured, jail not upgraded!
```

Now I have another problem though. I'm getting the following output from the upgrade:

```
iocage upgrade -r 11.1-RELEASE  stratus                                  john@wrath 
Looking up update.FreeBSD.org mirrors... 4 mirrors found.                                                  
Fetching metadata signature for 11.0-RELEASE from update5.freebsd.org... done.                             
Fetching metadata index... done.                     
Fetching 2 metadata patches.. done.                  
Applying metadata patches... done.                   
Fetching 2 metadata files... done.                   
Inspecting system... done.

The following components of FreeBSD seem to be installed:                                                  
kernel/generic world/base world/doc world/lib32      

The following components of FreeBSD do not seem to be installed:                                           
kernel/generic-dbg src/src world/base-dbg world/lib32-dbg                                                  


Fetching metadata signature for 11.1-RELEASE from update5.freebsd.org... done.                             
Fetching metadata index... done.                     
Fetching 1 metadata patches. done.                   
Applying metadata patches... done.                   
Fetching 1 metadata files... done.                   
Inspecting system... done.
Fetching files from 11.0-RELEASE for merging... done.
Preparing to download files... done.
/tmp/tmp6smsyput: cannot open files/.gz: No such file or directory
/tmp/tmp6smsyput: cannot open files/.gz: No such file or directory
...
...
/tmp/tmp6smsyput: cannot open files/.gz: No such file or directory
/tmp/tmp6smsyput: cannot open files/.gz: No such file or directory
Attempting to automatically merge changes in files... done.

The following file will be removed, as it no longer exists in
FreeBSD 11.1-RELEASE: /boot/device.hints
Does this look reasonable (y/n)?
```

That doesn't really look reasonable, no. Do I have a problem? Sorry for all the questions. I haven't accepted yes or no yet.

---

I know you said not to try changing the zfs property, how about in `config.json`? I took snapshots in case it caused a problem, so I figured I could always roll back. Could I screw anything up by changing `cloned_release` in the `config.json`?

**Comment by skarekrow** [comment]
@johnramsden no don’t change that property anywhere :) it is internal bookkeeping. If that fixed your problem then it’s likely you are still using older code. I promise a release will be out this week :D

As for that issue, it’s very similar to another @fliiiix has opened. I haven’t been able to replicate it, and my resident freebsd-update expert @kmoore134 also has never seen it. So not sure yet ok the resolution for that issue yet. 

Any steps you have that can recreate it or anything you may have changed in your host regarding that program would be appreciated in that issue @fliiiix filed. More information the better!

**Comment by johnramsden** [comment]
@skarekrow I uninstalled, then cloned and installed from the master branch.

I get:

```
iocage --version
Version 0.9.9.2 RC
```

Is that not up to date?

---

So, I assume I should set the property back, and not attempt updating until a release comes out?

**Comment by skarekrow** [comment]
Yes to all three questions. If you are so inclined, you can take snapshots and a backup and keep trying. Really any additional debugging is useful. 

If not, I hope to figure it out this week before I release.

**Comment by johnramsden** [comment]
Thanks, I'll report back if I find anything out.

**Comment by johnramsden** [comment]
@skarekrow So I upgraded to the new iocage release hoping the problem would be fixed. Unfortunately I'm having the same issue. When I attempt to upgrade I get the following message:

```
iocage upgrade -r 11.1-RELEASE  stratus
Jail: stratus is already at version 11.1!
```

But if I check jail the version it's running in the jail:

```
freebsd-version
11.0-RELEASE-p11 
```

At this point I can't figure out how to upgrade, do you have any advice? Is there any information I could give you to help figure the problem out? If you think the only fix is to re-create the entire jail I could do that, but obviously I'd prefer not to.

**Comment by skarekrow** [comment]
I'm thinking you left your modifications to the cloned_release and release properties in tact? It should work now for you, so make sure those are set back to the right values in the config.json.

**Comment by johnramsden** [comment]
@skarekrow No, I set then back after I change them last time. They're currently set to 11.1-RELEASE. If I try only changing release, it doesn't let me upgrade. If I change cloned, and release, it lets me start the upgrade but I have the same problem I had in the [comment](https://github.com/iocage/iocage/issues/309#issuecomment-331681380) I mentioned above.

I get the following output, which doesn't look right to me.

```
iocage upgrade -r 11.1-RELEASE  stratus                                  john@wrath 
Looking up update.FreeBSD.org mirrors... 4 mirrors found.                                                  
Fetching metadata signature for 11.0-RELEASE from update5.freebsd.org... done.                             
Fetching metadata index... done.                     
Fetching 2 metadata patches.. done.                  
Applying metadata patches... done.                   
Fetching 2 metadata files... done.                   
Inspecting system... done.

The following components of FreeBSD seem to be installed:                                                  
kernel/generic world/base world/doc world/lib32      

The following components of FreeBSD do not seem to be installed:                                           
kernel/generic-dbg src/src world/base-dbg world/lib32-dbg                                                  


Fetching metadata signature for 11.1-RELEASE from update5.freebsd.org... done.                             
Fetching metadata index... done.                     
Fetching 1 metadata patches. done.                   
Applying metadata patches... done.                   
Fetching 1 metadata files... done.                   
Inspecting system... done.
Fetching files from 11.0-RELEASE for merging... done.
Preparing to download files... done.
/tmp/tmp6smsyput: cannot open files/.gz: No such file or directory
/tmp/tmp6smsyput: cannot open files/.gz: No such file or directory
...
...
/tmp/tmp6smsyput: cannot open files/.gz: No such file or directory
/tmp/tmp6smsyput: cannot open files/.gz: No such file or directory
Attempting to automatically merge changes in files... done.

The following file will be removed, as it no longer exists in
FreeBSD 11.1-RELEASE: /boot/device.hints
Does this look reasonable (y/n)?

```

**Comment by skarekrow** [comment]
> @skarekrow No, I set then back after I change them last time. They're currently set to 11.1-RELEASE. If 

Is that a typo? You want them set to `11.0-RELEASE`. So the `release` property should be `11.0-RELEASE-p11` and the `cloned_release` property should be `11.0-RELEASE`

**Comment by johnramsden** [comment]
When I had my original problem it was set to 11.1, so that's what I said it back to.

I have tried setting it to 11.0 and the upgrade does start, but I get a large stream of the message:

`/tmp/tmp6smsyput: cannot open files/.gz: No such file or directory`

That makes me wonder if I should go ahead with the upgrade. I haven't seen that before in normal FreeBSD upgrades, should I tell it to go ahead?

**Comment by skarekrow** [comment]
The gz one is normal but the boot one is odd. I’d take a backup and proceed just to see. It’s certainly easier then recreating the jails. I haven’t personally seen these issues :/ they are all red herrings it seems.

**Comment by johnramsden** [comment]
Not it wants to remove a lot:

```
The following file will be removed, as it no longer exists in
FreeBSD 11.1-RELEASE: /boot/device.hints
Does this look reasonable (y/n)? y

The following file will be removed, as it no longer exists in
FreeBSD 11.1-RELEASE: /etc/amd.map
Does this look reasonable (y/n)? y

The following file will be removed, as it no longer exists in
FreeBSD 11.1-RELEASE: /etc/apmd.conf
Does this look reasonable (y/n)? y

The following file will be removed, as it no longer exists in
FreeBSD 11.1-RELEASE: /etc/auto_master
Does this look reasonable (y/n)? y
```

It just keeps going... Should I re-install?

**Comment by fliiiix** [comment]
@johnramsden I had the same Issue but didn't had the time to find a way to reproduce it so I reinstalled all my jails

**Comment by johnramsden** [comment]
@fliiiix Ouch. Thanks, guess i'll do that.

**Comment by skarekrow** [comment]
@johnramsden Yeah it's a big ouch. Poor @fliiiix had this too, but I haven't been able to replicate this heisenbug. Makes it very difficult to fix :(

**Comment by tholu** [comment]
I have the same problem trying to upgrade a jail from 11.1 to 11.2:

`iocage upgrade server -r 11.2-RELEASE`

Same stream of

```
/tmp/tmp6asdfas: cannot open files/.gz: No such file or directory

The following file will be removed, as it no longer exists in
FreeBSD 11.1-RELEASE: /boot/device.hints
Does this look reasonable (y/n)? n
```

**Comment by skarekrow** [comment]
That's expected, just some freebsd-update weirdness, it isn't fatal. 

EDIT: Unless you're saying the removal continues asking for all files?

**Comment by tholu** [comment]
@skarekrow After I answer `n`, the upgrade fails. It keeps asking though to remove files from `/etc/`, which indeed is NOT reasonable at all... something is really broken there.

**Comment by skarekrow** [comment]
@tholu Agreed, what iocage version is this? And when were the jails created? I haven't been able to reproduce this since the changes above for quite some time.

**Comment by tholu** [comment]
```
FreeBSD 11.2-STABLE (FreeNAS.amd64)

root@nas:~ # iocage --version
Version	1.0 ALPHA 1
root@nas:~ # iocage list
+-----+--------+-------+--------------+------+
| JID |  NAME  | STATE |   RELEASE    | IP4  |
+=====+========+=======+==============+======+
| 4   | server | up    | 11.1-RELEASE | DHCP |
+-----+--------+-------+--------------+------+
```

If I remember correctly, the jail was initially created with FreeBSD 10 and upgraded last with 11.1-RELEASE, which worked just fine back then.

**Comment by tholu** [comment]
I also had the following problem first:

```
root@nas:~ # iocage console server
Traceback (most recent call last):
  File "/usr/local/bin/iocage", line 10, in <module>
    sys.exit(cli())
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/iocage_cli/console.py", line 41, in cli
    silent=True).exec("", console=True)
  File "/usr/local/lib/python3.6/site-packages/iocage_lib/iocage.py", line 822, in exec
    su_env=su_env).exec_jail()
  File "/usr/local/lib/python3.6/site-packages/iocage_lib/ioc_exec.py", line 106, in exec_jail
    self.uuid, self.path, conf, silent=True)
  File "/usr/local/lib/python3.6/site-packages/iocage_lib/ioc_start.py", line 66, in __init__
    self.__start_jail__()
  File "/usr/local/lib/python3.6/site-packages/iocage_lib/ioc_start.py", line 415, in __start_jail__
    vnet_err = self.start_network(vnet)
  File "/usr/local/lib/python3.6/site-packages/iocage_lib/ioc_start.py", line 598, in start_network
    err = self.start_network_interface_vnet(nic, net_configs, jid)
  File "/usr/local/lib/python3.6/site-packages/iocage_lib/ioc_start.py", line 624, in start_network_interface_vnet
    membermtu = self.find_bridge_mtu(bridge)
  File "/usr/local/lib/python3.6/site-packages/iocage_lib/ioc_start.py", line 975, in find_bridge_mtu
    su.check_call(bridge_cmd, stdout=su.PIPE, stderr=su.PIPE)
UnboundLocalError: local variable 'bridge_cmd' referenced before assignment
```

I solved this with the zfs commands from your comment here: https://redmine.ixsystems.com/issues/31056

**Comment by skarekrow** [comment]
Sorry I meant iocage version when they were created. That's very old, and I don't believe this fix is in that version. You should update to the latest 1.1 and see if that resolves your issues.

**Comment by skarekrow** [comment]
I see you're on FreeNAS, I would suggest waiting for U3. I believe that has these fixes.

**Comment by tholu** [comment]
I'm on FreeNAS, right - thanks for the hint, will wait for U3 and see if it works again. 👍

**Comment by tholu** [comment]
@skarekrow Same problem after the upgrade:

```
root@nas:~ # iocage --version
Version	FreeNAS 11.2-U3
root@nas:~ # freebsd-version
11.2-STABLE
root@nas:~ # iocage upgrade server -r 11.2-RELEASE
src component not installed, skipped
Looking up update.FreeBSD.org mirrors... 3 mirrors found.
Fetching metadata signature for 11.1-RELEASE from update2.freebsd.org... done.
Fetching metadata index... done.
Fetching 1 metadata patches. done.
Applying metadata patches... done.
Fetching 1 metadata files... done.
Inspecting system... done.

The following components of FreeBSD seem to be installed:
world/base world/doc world/lib32

The following components of FreeBSD do not seem to be installed:
world/base-dbg world/lib32-dbg


Fetching metadata signature for 11.2-RELEASE from update2.freebsd.org... done.
Fetching metadata index... done.
Fetching 1 metadata patches. done.
Applying metadata patches... done.
Fetching 1 metadata files... done.
Inspecting system... done.
Fetching files from 11.1-RELEASE for merging... done.
Preparing to download files... done.
/tmp/tmpdm63nz9z: cannot open files/.gz: No such file or directory
....
/tmp/tmpdm63nz9z: cannot open files/.gz: No such file or directory
Attempting to automatically merge changes in files... done.

The following file will be removed, as it no longer exists in
FreeBSD 11.2-RELEASE: /boot/device.hints
Does this look reasonable (y/n)? n
Traceback (most recent call last):
  File "/usr/local/bin/iocage", line 10, in <module>
    sys.exit(cli())
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/iocage_cli/upgrade.py", line 39, in cli
    ioc.IOCage(jail=jail, skip_jails=True).upgrade(release)
  File "/usr/local/lib/python3.6/site-packages/iocage_lib/iocage.py", line 1838, in upgrade
    root_path).upgrade_jail()
  File "/usr/local/lib/python3.6/site-packages/iocage_lib/ioc_upgrade.py", line 116, in upgrade_jail
    raise RuntimeError("Error occured, jail not upgraded!")
RuntimeError: Error occured, jail not upgraded!
```

**Comment by skarekrow** [comment]
Hmm I think this jail may have been permanently bitten by the same bug. Can you try to create another 11.1-RELEASE jail and see if upgrading to 11.2-RELEASE with that succeeds?

**Comment by tholu** [comment]
@skarekrow You're right, creating another 11.1-RELEASE jail and upgrading to 11.2-RELEASE worked without any hassle. How can we investigate further what's going wrong with the other jail?

**Comment by lgrahl** [comment]
If there's still a chance to investigate this, all five jails I have are affected by this. No idea which version of iocage it was when I created these but it was FreeNAS 11.2-RELEASE-U1. Otherwise, I'll have to recreate them. :expressionless:

**Comment by dgeo** [comment]
I've been hit by this same bug on real machines too, I think this is a freebsd-update problem. I'd love to find the root too, but this is not an iocage problem IMHO :/
