### ISSUE TITLE
No dots allowed in jail name

### ISSUE THREAD

**Issue by joachimmathes** [iocage/iocage#310]
We have used domains like `foo.bar.baz.de` as tags so far. But as of iocage version `0.9.9` this is no longer possible, since dots (`.`) are not allowed in jail names. (https://github.com/iocage/iocage/blob/master/iocage/cli/create.py#L85). Is it possible to allow dots again or does this have any side effects. Domains make great jail names (uuids), since they are part of a URI and thus sufficiently unique. 

```
$ iocage --version
0.9.9 07/28/2017
```

**Comment by skarekrow** [comment]
I can't remember there being a side effect. I'll make sure before I implement it, but it's likely because I forgot dots as being valid :P

**Comment by joachimmathes** [comment]
Phew, I hoped so. :smiley:

**Comment by igalic** [comment]
we should pull name validation code a little higher up in the libraries, and make it explicit (a function?), rather than repeating the same regex every time.

**Comment by skarekrow** [comment]
I'm not sure that much work is necessary. It only matters during creation. Any other call would require that jail to exist. It can't without being created ;)

**Comment by igalic** [comment]
*something something easier testing something something*

**Comment by joachimmathes** [comment]
:disappointed: Could not start jails with a dot in their name:
```
iocage start master.dev                               
* Starting master.dev
  + Start FAILED
jail: jail "ioc-master" not found
```

Most probably due to the `jail` command, since the man page says:

>      name    The jail name.  This is an arbitrary string that identifies a
>              jail (except it may not contain a ‘.’).  Like the jid, it can be...

So, the commit "fixing" this issue should be reverted.

**Comment by skarekrow** [comment]
Bah I thought I started it fine. I'll revert this then. Or find some other compromise.

**Comment by skarekrow** [comment]
Solved! https://github.com/iocage/iocage/commit/dfc253f0e1a156f3f2eacf7848c210fe9079522b
```
root@iocage:~ # iocage create -n foo.bar -r 11.1-RELEASE
foo.bar successfully created!
root@iocage:~ # iocage start foo.bar
* Starting foo_bar
  + Started OK
  + Starting services OK
root@iocage:~ # jls
   JID  IP Address      Hostname                      Path
    20                  foo.bar                       /iocage/jails/foo.bar/root
```

**Comment by joachimmathes** [comment]
:tada: You made my day! :+1:
