### ISSUE TITLE
Iocage commands very slow response

### ISSUE THREAD

**Issue by Msaita** [iocage/iocage#311]
I have updated our iocage version from previous 1.7.4 to new python iocage.

Current version 0.9.8.1
After the update Iocage list is taking 13seconds to show the results.

real	0m13.109s
user	0m2.948s
sys	0m10.172s

On previous non-python iocage we were used to instant response as we still have a machine running the previous 1.7.4
time iocage list is executed in:

real	0m0.261s
user	0m0.056s
sys	0m0.238s

I've checked the previous issues, however i couldn't find no mention of similar problem, is this something that happened due to our upgrade or something that someone experienced before?

**Comment by joachimmathes** [comment]
This should be fixed by
* https://github.com/iocage/iocage/issues/230
* https://github.com/iocage/iocage/issues/244

in the current 0.9.9 release.

**Comment by skarekrow** [comment]
I'd also recommend mounting `/dev/fd` like I recommend in the README if you haven't. I'll reopen this if your problem persists and we can track it down to something.
