### ISSUE TITLE
jail_zfs_dataset lists a non-existant zfs dataset

### ISSUE THREAD

**Issue by Terhands** [iocage/iocage#312]
Running on freebsd 10.3-RELEASE  
iocage version = 0.9.5 2017/02/15

After creating a release jail using iocage I am trying to adjust the zfs recordsize using `/zroot/<iocage get jail_zfs_dataset myjail>` as the dataset location. I would expect the dataset returned by iocage to be one that can be used with the zfs command to adjust properties. Instead it appears to be pointing to a non-existant dataset and fails when trying to use it with zfs.

Running `zfs set recordsize=16K zroot/'iocage get jail_zfs_dataset myjail'` outputs:
> cannot open 'iocage/jails/7746ae30-d5a6-46fe-8e85-418817639e82/data': dataset does not exist

Running zfs list outputs the following iocage datasets:
```
zroot/iocage                                                   291M  3.48T  62.5K  /iocage
zroot/iocage/download                                         85.4M  3.48T  57.5K  /iocage/download
zroot/iocage/download/10.3-RELEASE                            85.3M  3.48T  85.3M  /iocage/download/10.3-RELEASE
zroot/iocage/images                                           57.5K  3.48T  57.5K  /iocage/images
zroot/iocage/jails                                             261K  3.48T  62.5K  /iocage/jails
zroot/iocage/jails/7746ae30-d5a6-46fe-8e85-418817639e82        198K  3.48T    62K  /iocage/jails/7746ae30-d5a6-46fe-8e85-418817639e82
zroot/iocage/jails/7746ae30-d5a6-46fe-8e85-418817639e82/root   136K  3.48T   205M  /iocage/jails/7746ae30-d5a6-46fe-8e85-418817639e82/root
zroot/iocage/log                                              77.5K  3.48T  77.5K  /iocage/log
zroot/iocage/releases                                          205M  3.48T  57.5K  /iocage/releases
zroot/iocage/releases/10.3-RELEASE                             205M  3.48T  57.5K  /iocage/releases/10.3-RELEASE
zroot/iocage/releases/10.3-RELEASE/root                        205M  3.48T   205M  /iocage/releases/10.3-RELEASE/root
zroot/iocage/templates                                        57.5K  3.48T  57.5K  /iocage/templates
```

Steps to reproduce:
* Use iocage to create a jail with the following properties set: ip4_addr, pkglist, -r 10.3-RELEASE, myjail as the jail's tag
* Run `iocage get jail_zfs_dataset myjail`
* Try to use the output dataset value for any zfs commands

At the moment I am working around this by using the path: `zroot/iocage/jails/'iocage get host_hostuuid myjail'/root` based on the output of `zfs list`.

**Comment by Terhands** [comment]
Just a note - I'm seeing the same behaviour in version 0.9.8.1.

**Comment by skarekrow** [comment]
We don't create the jailed dataset anymore on creation. If you need it I suggest using your UUID method and creating one with the record size you wish to have.

**Comment by Terhands** [comment]
@skarekrow Then wouldn't it be more appropriate to simply not populate that field when creating a jail? Giving jail_zfs_dataset a value on jail creation implies that it has been created, and could easily be a source of confusion.
