### ISSUE TITLE
INFO output should go to stderr

### ISSUE THREAD

**Issue by olgeni** [iocage/iocage#313]
If you run "iocage create" and parse the output to retrieve the jail UUID, you'll sometimes see stray INFO messages:

    # iocage create -e > LOG
    # cat LOG 
      INFO: creating rpool/iocage/jails
    2b42f973-bfaa-11e5-b507-bcaec55be5e5

INFO messages should probably be redirected to stderr :)

    % iocage version
    iocage DEVELOP (2015-12-07)

(that's e4f390f from FreeBSD ports)

**Comment by skarekrow** [comment]
I agree :)

**Comment by olgeni** [comment]
Thanks!
