### ISSUE TITLE
"iocage create -e" looking for missing releases

### ISSUE THREAD

**Issue by olgeni** [iocage/iocage#314]
Running commit fbef24a (from FreeBSD ports) without any downloaded release, I create a new emptyjail and get the following output:

    # iocage create -e     
    cd: /iocage/releases/10.2-STABLE/root/etc: No such file or directory
    cd: /iocage/releases/10.2-STABLE/root/root: No such file or directory
    4e903eee-c126-11e5-9876-080027af0e2a

The jail is created successfully and I see no side effects, but the output is a bit puzzling as `-e` is not supposed to look for releases (as far as I understand!)

FreeBSD is 10.2-STABLE #0 r293912.

**Comment by skarekrow** [comment]
I can't reproduce this.

```
bschneider@iocage-dev:~ % sudo iocage clean -af
  INFO: destroying scratch/iocage: done!
bschneider@iocage-dev:~ % sudo iocage create -e tag=test vnet=off
  INFO: creating scratch/iocage
  INFO: creating scratch/iocage/.defaults
  INFO: creating scratch/iocage/download
  INFO: creating scratch/iocage/jails
  INFO: creating scratch/iocage/releases
  INFO: creating scratch/iocage/templates
7a7bf518-c137-11e5-af97-00a098690e88
bschneider@iocage-dev:~ % iocage list
JID  UUID                                  BOOT  STATE  TAG   TYPE
-    7a7bf518-c137-11e5-af97-00a098690e88  off   down   test  emptyjail
bschneider@iocage-dev:~ % iocage version
iocage DEVELOP (2016-01-21)
```

What does `iocage version` show? It could be a stale install somehow?

**Comment by olgeni** [comment]
I made a test on a fresh install in a VM.

    # iocage create -e
    Setting up zpool [rpool] for iocage usage...
    If you wish to change zpool, use 'iocage activate'
      INFO: creating rpool/iocage
      INFO: creating rpool/iocage/.defaults
      INFO: creating rpool/iocage/download
      INFO: creating rpool/iocage/jails
      INFO: creating rpool/iocage/releases
      INFO: creating rpool/iocage/templates
    cd: /iocage/releases/10.2-RELEASE/root/etc: No such file or directory
    cd: /iocage/releases/10.2-RELEASE/root/root: No such file or directory
    dac6b574-c147-11e5-9fa6-080027022244
    # iocage clean -af
      INFO: destroying rpool/iocage: done!
    # iocage create -e
      INFO: creating rpool/iocage
      INFO: creating rpool/iocage/.defaults
      INFO: creating rpool/iocage/download
      INFO: creating rpool/iocage/jails
      INFO: creating rpool/iocage/releases
      INFO: creating rpool/iocage/templates
    cd: /iocage/releases/10.2-RELEASE/root/etc: No such file or directory
    cd: /iocage/releases/10.2-RELEASE/root/root: No such file or directory
    e59ca897-c147-11e5-9fa6-080027022244

So I ran iocage with the `-x` flag of `/bin/sh`, and got this:

    # sh -x /usr/local/sbin/iocage create -e
    [...snip...]
    + zfs create -p rpool/iocage/jails/0816d663-c148-11e5-9fa6-080027022244/root
    + _configured=1
    + mkdir -p /iocage/jails/0816d663-c148-11e5-9fa6-080027022244/root/bin
    + mkdir -p /iocage/jails/0816d663-c148-11e5-9fa6-080027022244/root/boot
    + mkdir -p /iocage/jails/0816d663-c148-11e5-9fa6-080027022244/root/lib
    + mkdir -p /iocage/jails/0816d663-c148-11e5-9fa6-080027022244/root/libexec
    + mkdir -p /iocage/jails/0816d663-c148-11e5-9fa6-080027022244/root/rescue
    + mkdir -p /iocage/jails/0816d663-c148-11e5-9fa6-080027022244/root/sbin
    + mkdir -p /iocage/jails/0816d663-c148-11e5-9fa6-080027022244/root/etcupdate
    + mkdir -p /iocage/jails/0816d663-c148-11e5-9fa6-080027022244/root/usr/bin
    + mkdir -p /iocage/jails/0816d663-c148-11e5-9fa6-080027022244/root/usr/include
    + mkdir -p /iocage/jails/0816d663-c148-11e5-9fa6-080027022244/root/usr/lib
    + mkdir -p /iocage/jails/0816d663-c148-11e5-9fa6-080027022244/root/usr/libexec
    + mkdir -p /iocage/jails/0816d663-c148-11e5-9fa6-080027022244/root/usr/ports
    + mkdir -p /iocage/jails/0816d663-c148-11e5-9fa6-080027022244/root/usr/sbin
    + mkdir -p /iocage/jails/0816d663-c148-11e5-9fa6-080027022244/root/usr/share
    + mkdir -p /iocage/jails/0816d663-c148-11e5-9fa6-080027022244/root/usr/src
    + mkdir -p /iocage/jails/0816d663-c148-11e5-9fa6-080027022244/root/usr/libdata
    + mkdir -p /iocage/jails/0816d663-c148-11e5-9fa6-080027022244/root/usr/lib32
    + mkdir -p /iocage/jails/0816d663-c148-11e5-9fa6-080027022244/root/dev
    + mkdir -p /iocage/jails/0816d663-c148-11e5-9fa6-080027022244/root/tmp
    + mkdir -p /iocage/jails/0816d663-c148-11e5-9fa6-080027022244/root/var
    + mkdir -p /iocage/jails/0816d663-c148-11e5-9fa6-080027022244/root/etc
    + mkdir -p /iocage/jails/0816d663-c148-11e5-9fa6-080027022244/root/root
    + mkdir -p /iocage/jails/0816d663-c148-11e5-9fa6-080027022244/root/proc
    + mkdir -p /iocage/jails/0816d663-c148-11e5-9fa6-080027022244/root/mnt
    + mkdir -p /iocage/jails/0816d663-c148-11e5-9fa6-080027022244/root/var/run
    + cd /iocage/releases/10.2-RELEASE/root/etc
    cd: /iocage/releases/10.2-RELEASE/root/etc: No such file or directory
    + cd /iocage/releases/10.2-RELEASE/root/root
    cd: /iocage/releases/10.2-RELEASE/root/root: No such file or directory
    + [ -e /etc/localtime ]
    + cp /etc/localtime /iocage/jails/0816d663-c148-11e5-9fa6-080027022244/root/etc/
    [...snip...]

It seems that `create -e` is not really creating an emptyjail, because the basic directory structure is there. It then looks for /etc/ and /root/ in the release (ioc-zfs:436) but there is none installed, which explains the `cd` error.

I have `iocage DEVELOP (2016-01-21)` (fbef24a).

Is your `emptyjail` actually empty? :)

**Comment by skarekrow** [comment]
Heh it turned out not to be! I pushed a commit that should fix this @olgeni, please test :)

**Comment by olgeni** [comment]
Looks good! \o/

**Comment by skarekrow** [comment]
\m/ great!
