### ISSUE TITLE
Cannot upgrade to 0.99.1 from 0.98.x without restarting all my cages! Really? :(

### ISSUE THREAD

**Issue by Infiniverse** [iocage/iocage#314]
We are running iocage in production across many hundreds of cages. We've just upgraded to the python version of iocage from 1.74 to 0.98.x with no disruption to services.

We are now upgrading to 0.99.1 because of a performance issue that has just been solved (taking too long to do 'iocage list' for example).

I'm very surprised to find that I need to shutdown all of my cages to do the migration - is that _really_ necessary? What is it in the running configuration that prevents the meta data from just being updated (or is iocage really needing to refactor all of the filesystems.... is that documented? We rely on the layout!)

For those of us that use iocage extensively having an upgrade that requires a complete reboot of our live system is highly undesirable :(. Can this not be achieve in a lighter touch way? (Happy to help! What's the plan stan?)

    fatal: [s1]: FAILED! => {"changed": false, "failed": true, "msg": "_get_iocage_facts():\ncmd:
     '/usr/local/bin/iocage list -hl' return 1\nstdout: ''\nstderr: 'Traceback (most recent call last):\n
    File \"/usr/local/bin/iocage\", line 10, in <module>\n    sys.exit(cli())\n  File
    \"/usr/local/lib/python3.6/site-packages/click/core.py\", line 722, in __call__\n
    return self.main(*args, **kwargs)\n  File \"/usr/local/lib/python3.6/site-packages/click/core.py\",
    line 697, in main\n    rv = self.invoke(ctx)\n  File \"/usr/local/lib/python3.6/site-packages/click/core.py\",
    line 1066, in invoke\n    return _process_result(sub_ctx.command.invoke(sub_ctx))\n  File
    \"/usr/local/lib/python3.6/site-packages/click/core.py\", line 895, in invoke\n
    return ctx.invoke(self.callback, **ctx.params)\n  File \"/usr/local/lib/python3.6/site-packages/click/core.py\",
    line 535, in invoke\n    return callback(*args, **kwargs)\n  File
    \"/usr/local/lib/python3.6/site-packages/iocage/cli/list.py\", line 74, in cli\n
    plugin=plugins, quick=quick)\n  File \"/usr/local/lib/python3.6/site-packages/iocage/lib/iocage.py\", line 889, in list\n
    plugin=plugin, quick=quick).list_datasets()\n  File \"/usr/local/lib/python3.6/site-packages/iocage/lib/ioc_list.py\",
     line 72, in list_datasets\n    _all = self.list_all(ds)\n 
    File \"/usr/local/lib/python3.6/site-packages/iocage/lib/ioc_list.py\", line 150, in list_all\n
    conf = iocage.lib.ioc_json.IOCJson(mountpoint).json_load()\n  File
    \"/usr/local/lib/python3.6/site-packages/iocage/lib/ioc_json.py\", line 292, in json_load\n
    conf = self.json_check_config(conf)\n  File \"/usr/local/lib/python3.6/site-packages/iocage/lib/ioc_json.py\", line
    715, in json_check_config\n    silent=self.silent)\n  File \"/usr/local/lib/python3.6/site-packages/iocage/lib/ioc_common.py\",
    line 78, in logit\n    _callback({\"level\": level, \"message\": msg})\n 
    File \"/usr/local/lib/python3.6/site-packages/iocage/lib/ioc_common.py\", line 61,
    in callback\n    raise
    **RuntimeError(log['message'])\nRuntimeError: ddinvite is running, all jails must be stopped before iocage will continue migration\n')"**}

**Comment by skarekrow** [comment]
If it wasn't necessary, I wouldn't have you do it ;) The code doesn't write itself after all. Yes it was documented in the changelog, which you should read before upgrading since this is still *Beta*, which is not recommended for production.

We dropped functionality, and the only way to migrate you guys properly is to move the datasets, and unless you want to do it by hand once it goes disastrous for you later like #307, then I suggest you take the small moment of downtime. In the meantime, if you can't do so, stick to 0.9.8.1 until you can migrate.

**Comment by Infiniverse** [comment]
I looked for a change log, but didn't see one. There was a long list of single line commits, but nothing like a change log that I could evaluation.

We're happy to help maintain this as we have been using it a lot in production (and we already contribute to the ansible-iocage module).

What is your focus of development? Have you got a published roadmap?

**Comment by skarekrow** [comment]
The focus of my development is FreeNAS, and any features I'm still trying to currently port from the legacy version. But that hasn't gone as I'd like, as we have added a ton of new features in the meantime. Which is good too!

I do not have a roadmap.


Thanks for the interest 👍
