### ISSUE TITLE
-v not supported in 0.9.9

### ISSUE THREAD

**Issue by francisco1844** [iocage/iocage#317]
Make sure to follow and check these boxes before submitting an issue! Thank you.

- [X] Supply `iocage --version
iocage --version
0.9.9.1 08/01/2017

- [X] Supply the commands used, along with any steps to recreate it.
iocage -v

- [X] Provide the output from the command you issued.
#iocage -v
Error: no such option: -v

- [X] Supply what you expected the result or output to be
0.9.9.1 08/01/2017

**Comment by skarekrow** [comment]
Very low priority enhancement, but I'll add a `-v` flag if It's possible with the library 👍
