### ISSUE TITLE
Upgrading uses "cloned_release" and doesn't update it

### ISSUE THREAD

**Issue by slohse** [iocage/iocage#318]
I just upgraded a Jail from 11.0-RELEASE to 11.1-RELEASE. The jail was initially created as a 10.3-RELEASE with the old iocage and upgraded to 11.0 some time ago - I don't remember if it was with the old iocage or with the python-iocage.
Now during the upgrade process to 11.1 I had

```
The following file could not be merged automatically: $FILE
Press Enter to edit this file in $EDITOR and resolve the conflicts                 
manually...
```

with what felt like and could quite literally have been *every* file in `/etc` and `/boot`. For almost all of them the difference was the comment line at the top, which states the origin of the file in the source tree:

```
<<<<<<< current version
# $FreeBSD: releng/11.0/etc/rc.d/ftpd 298514 2016-04-23 16:10:54Z lme $
=======
# $FreeBSD: releng/11.1/etc/rc.d/ftpd 298514 2016-04-23 16:10:54Z lme $
>>>>>>> 11.1-RELEASE
```

This shouldn't happen, right?

I looked around a bit and noticed that `freebsd-update` compared to `10.3-RELEASE` for merging

```
root@ploek:~> iocage upgrade -r 11.1-RELEASE irssi
Looking up update.FreeBSD.org mirrors... 4 mirrors found.                        
Fetching metadata signature for 10.3-RELEASE from update5.freebsd.org... done.   
Fetching metadata index... done.                                                 
Fetching 1 metadata patches. done.                                               
Applying metadata patches... done.                                               
Fetching 1 metadata files... done.                                               
Inspecting system... done.                                        
                                                                  
The following components of FreeBSD seem to be installed:         
kernel/generic src/src world/base world/doc world/games world/lib32              
                                                                  
The following components of FreeBSD do not seem to be installed:                 
                                                                                 
                                                                                 
Fetching metadata signature for 11.1-RELEASE from update5.freebsd.org... done.   
Fetching metadata index... done.                                                 
Fetching 1 metadata patches. done.                                               
Applying metadata patches... done.
Fetching 1 metadata files... done.
Inspecting system... done.
Fetching files from 10.3-RELEASE for merging... done.
Preparing to download files... done.
/tmp/tmpkzxnrq2n: cannot open files/.gz: No such file or directory
Attempting to automatically merge changes in files... done.                      
                                                                                 
The following file could not be merged automatically: /boot/device.hints         
Press Enter to edit this file in emacs and resolve the conflicts                 
manually...

[and many, many more of those]
```

This happens, even though the jail is 11.0, as shown by `freebsd-version` when executed in the jail and `iocage list`:

```
root@redacted:~> iocage list
+-----+----------+-------+----------+--------------+-----------------+
| JID |   UUID   | STATE |   TAG    |   RELEASE    |       IP4       |
+=====+==========+=======+==========+==============+=================+
...
+-----+----------+-------+----------+--------------+-----------------+
| 1   | 65dd2ac5 | up    | irssi    | 11.0-RELEASE | redacted        |
+-----+----------+-------+----------+--------------+-----------------+
...
root@redacted:~> iocage console irssi
root@irssi:~ # freebsd-version                                                   
11.0-RELEASE-p10
```

Wondering where the 10.3 comes from I looked at the iocage source code a bit and found `IOCUpgrade.__init()__` gets it from the `cloned_release` property. And sure enough, all of my jails look like this:

```
root@redacted:~> iocage get release irssi
11.0-RELEASE-p10
root@redacted:~> iocage get cloned_release irssi
10.3-RELEASE
```

I don't know exactly what the `cloned_release` property implies, but as far as I can tell it's not updated after a jail is upgraded, so from my understanding the problem should arise whenever someone upgrades a jail more than once.

Make sure to follow and check these boxes before submitting an issue! Thank you.

- [X] Supply `iocage --version`: 0.9.8.1 05/23/2017
- [X] Supply the commands used, along with any steps to recreate it.
- [X] Provide the output from the command you issued.
- [X] Supply what you expected the result or output to be
- [X] Checked that the problem has not already been fixed on `master` if using
 a stable release.

**Comment by skarekrow** [comment]
A (very thorough) dup of #309, closing

**Comment by skarekrow** [comment]
As for the upgrade questions:
1 - No you shouldn't be prompted just for those headers, but that's likely something funky happening since you're jumping quite a distance
2 - The `cloned_release` property is exactly what it sounds like. It's the release you cloned the jail from. It's just used as book keeping, and `upgrade` likely got hit by the major swathe of changes I did a few times in this cycle.
