### ISSUE TITLE
basejails no longer suported

### ISSUE THREAD

**Issue by woodsb02** [iocage/iocage#32]
I migrated all of my jails to the new python based iocage, and have only recently realised that basejails are seemingly no longer supported, and are migrated to clone jails with the "iocage migrate" command.

This is problematic as I believed I was installing security updates by updating the release, as per the method used in iocage-legacy.

I would really like to see basejails still supported in the new iocage, as it only requires a single upgrade to apply security updates to all jails.

Failing that, the "iocage migrate" command should warn the user that the basejail is being converted to a clone jail, and that the process for install security updates will therefore differ.

**Comment by skarekrow** [comment]
Ah, yeah I forgot to put it in the warning at the start, but it is available in the help for that command. Sorry about that!  

~~I do not plan to support basejails again, unless ZFS gets an excellent overlay feature down the road or unionfs gets the love it needs. I will have a `update ALL` and `upgrade ALL` command as well though, to help automate this process.~~

EDIT: I will be adding in the old basejails from the `master` branch of iocage_legacy. Or something close. So much for planning! Hah.

**Comment by skarekrow** [comment]
The prompt for the migration has been updated, basejails are a WIP.

**Comment by tykling** [comment]
looking forward to basejail support :+1:

**Comment by skarekrow** [comment]
Alright guys, it's been added! `iocage create -b` which should feel familiar :)

Upgrading hasn't been started yet, so for now it's just for creation, I'll hopefully get that part nailed before you have to do it ;)

**Comment by woodsb02** [comment]
skarekrow - thank you. I feel this is a very important feature, and I am glad you have added it!

Am I correct that if people switch from iocage-legacy to the new iocage today, their basejails will still be migrated to clone jails?

If so, perhaps the migration script could be updated to migrate from the iocage-legacy basejail to a new iocage basejail?

**Comment by skarekrow** [comment]
You are correct. I made a umbrella issue to track this feature. I'm sure there will be more iteration as it's the first one and is different then either implementation I did before.
