### ISSUE TITLE
`bpf` property defaults to `off` (should be `no`) on virgin jails

### ISSUE THREAD

**Issue by rexpo** [iocage/iocage#322]
The `bpf` property has legal values of `yes` or `no`, but defaults to `off` on a freshly created jail.

- [x] Supply `iocage --version`
0.9.9.2 ALPHA
74daaa9 (cloned this morning after DHCP support was added last night)
- [x] Supply the commands used, along with any steps to recreate it.
```
# iocage create --empty --name newjail
# iocage get bpf newjail
```
- [x] Provide the output from the command you issued.
```
off
```
- [x] Supply what you expected the result or output to be
```
no
```
- [x] Checked that the problem has not already been fixed on `master` if using
 a stable release.

**Comment by skarekrow** [comment]
You have a stale `defaults.json` :) Just nuke that, and it will be how you expect.
