### ISSUE TITLE
Questions about basejails and thin jails

### ISSUE THREAD

**Issue by bax-** [iocage/iocage#323]
Coming from ezjail I have questions about iocage's basejail, thin jails and clones.
I hope they don't sound too stupid.
What would I setup if I wanted to copy ezjails behavior? (1 basejail whose base files are used by all the other jails to make updates and upgrade easy and fast and safe disk space).

Would I setup a basejail (`iocage create -b`) and clone it?

Or would I just create thin jails (`iocage create -c`)? But how would I update all of them at once?

I hope you can help me and clarify for me what the differences and dependencies are.

Thank you!

**Comment by skarekrow** [comment]
If you used clone jails (`iocage create -c`) then they would not be updatable all at once. They are essentially independent jails but are tied to one common parent. Which means that even as they upgrade releases, they are still dependent on that parent being around. Upgrading these is not supported in the latest `develop` changes for iocage for this reason. It causes user confusion.

Basejails (`iocage create -b` in the stable, and the default for `develop`) also use a common parent but are not tied to it. So you would be able to update them all at once by changing the parent, or individually as you saw fit.

So to answer your question, you would want to use `iocage create -b` to mimic ezjail's configuration. This is only valid for 1.7.3 and under. Once I release 2.0, you then will just use `iocage create`.

Hopefully this helps! :)

**Comment by bax-** [comment]
Help you VERY much!
I'm exited as to what 2.0 will offer.

**Comment by skarekrow** [comment]
You're very welcome!
