### ISSUE TITLE
Mixing VIMAGE and non-VIMAGE jails?

### ISSUE THREAD

**Issue by stratacast** [iocage/iocage#325]
iocage version - 0.9.9.1 (from ports)
OS - FreeBSD 11.1

I have a handful of jails that currently exist, some I'm setting up (finding they need their own networking stack) and others that are currently running and fully functioning. Is it possible with iocage to keep my existing, functioning jails as non-VIMAGE jails, but then create new jails that either do/do not use that functionality? If I have to make my jails all or nothing, would it be problematic to do:

`iocage set ip4_addr="vnet0|192.168.1.10/24" jail_name`

or would this cause problems?

**Comment by skarekrow** [comment]
You can certainly mix and match with no issues :)
