### ISSUE TITLE
`iocage list --long` only shows the first VNET adapter when DHCP enabled

### ISSUE THREAD

**Issue by rexpo** [iocage/iocage#326]
Make sure to follow and check these boxes before submitting an issue! Thank you.

- [x] Supply `iocage --version`
0.9.9.2 ALPHA
97c3329
- [x] Supply the commands used, along with any steps to recreate it.
Create 2 VNET jails, each with 2 interfaces, one with fixed IPs on both interfaces, one with DHCP on both interfaces:

```
# iocage create --name jail1 --release 10.3-RELEASE vnet=on devfs_ruleset=4 interfaces='vnet0:bridge0,vnet1:bridge1' ip4_addr='vnet0|10.1.2.100/26,vnet1|10.1.3.20/27' defaultrouter=10.1.2.1 host_hostname=jail1
jail1 successfully created!
# iocage create --name jail2 --release=10.3-RELEASE vnet=on devfs_ruleset=5 interfaces='vnet0:bridge0,vnet1:bridge1' dhcp=on bpf=yes host_hostname=jail2
jail2 successfully created!
```

Start the jails, then check the list:

```
# iocage list --long
```
- [x] Provide the output from the command you issued.
```
+-----+-------+------+-------+------+------------------+----------------------------------------+-----+----------+
| JID | NAME  | BOOT | STATE | TYPE |     RELEASE      |                  IP4                   | IP6 | TEMPLATE |
+=====+=======+======+=======+======+==================+========================================+=====+==========+
| 42  | jail1 | off  | up    | jail | 10.3-RELEASE-p20 | vnet0|10.1.2.100/26,vnet1|10.1.3.20/27 | -   | -        |
+-----+-------+------+-------+------+------------------+----------------------------------------+-----+----------+
| 43  | jail2 | off  | up    | jail | 10.3-RELEASE-p20 | vnet0|10.1.2.91                        | -   | -        |
+-----+-------+------+-------+------+------------------+----------------------------------------+-----+----------+
```
`vnet1`'s IP4 address info should have been displayed here. (checking `iocage console jail2` shows that it successfully got an address from DHCP)
- [x] Supply what you expected the result or output to be
```
+-----+-------+------+-------+------+------------------+----------------------------------------+-----+----------+
| JID | NAME  | BOOT | STATE | TYPE |     RELEASE      |                  IP4                   | IP6 | TEMPLATE |
+=====+=======+======+=======+======+==================+========================================+=====+==========+
| 42  | jail1 | off  | up    | jail | 10.3-RELEASE-p20 | vnet0|10.1.2.100/26,vnet1|10.1.3.20/27 | -   | -        |
+-----+-------+------+-------+------+------------------+----------------------------------------+-----+----------+
| 43  | jail2 | off  | up    | jail | 10.3-RELEASE-p20 | vnet0|10.1.2.91,vnet1|10.1.3.18        | -   | -        |
+-----+-------+------+-------+------+------------------+----------------------------------------+-----+----------+
```
One could also pick nits and point out that the IP4 information shown for jail1 is the "desired setting", not necessarily the "actual values", whereas the IP4 information shown for jail2 is the "actual values", nothing about desired setting (no hint that DHCP did that, unless you do a short `iocage list`). I wouldn't lose sleep over this, I believe this is how iocage_legacy and The Warden behave already. (though The Warden shows that the IP4 address came from DHCP) Would also be nice to see the network mask included in the IP4 info for the DHCP jail, but that might be more of a pain to implement than it's worth.

**Comment by skarekrow** [comment]
I purposely only use the first interface to keep clutter low.

**Comment by rexpo** [comment]
Well I can certainly live with that! (and it keeps that can of worms nicely closed ;)
