### ISSUE TITLE
gitlocation documentation?

### ISSUE THREAD

**Issue by DadAtH-me** [iocage/iocage#326]
The docs don't turn up anything: http://iocage.readthedocs.org/en/latest/search.html?q=gitlocation&check_keywords=yes&area=default and it didn't seem to get answered here: https://groups.google.com/forum/#!topic/iocage/rb0I3cU6q-k

I want to make sure I'm not reinventing a wheel someone else is already working on.

Is there any documentation on creating a 'cage'?

**Comment by skarekrow** [comment]
Thanks for asking! We don't have anything in our official docs quite yet, but all the work actually happens over [here] (https://github.com/pbi-cages/pbicage-index). The actual cages repo is a placeholder if we want to have things which that repo I just linked doesn't.
