### ISSUE TITLE
"Configuring VNET" status when starting a VNET jail?

### ISSUE THREAD

**Issue by rexpo** [iocage/iocage#329]
When starting and stopping VNET jails, there used to be status messages about VNET (in `iocage_legacy`). I miss them.

- [x] Supply `iocage --version`
0.9.9.2 ALPHA at 97c3329
- [x] Supply the commands used, along with any steps to recreate it.

```
# iocage create --name billy --release 10.3-RELEASE vnet=on
billy successfully created!
# iocage start billy
```
- [x] Provide the output from the command you issued.
```
* Starting billy
  + Started OK
  + Starting services OK
```
- [x] Supply what you expected the result or output to be

`iocage_legacy` showed `+ Configuring VNET OK` upon startup:
```
* Starting billy
  + Started OK
  + Configuring VNET OK
  + Starting services OK
```
and `Tearing down VNET OK` upon shutdown:
```
* Stopping billy
  + Running prestop OK
  + Stopping services OK
  + Tearing down VNET OK
  + Removing jail process OK
  + Running poststop OK
```

**Comment by skarekrow** [comment]
You really miss them? I removed them to reduce noise during startup. It doesn't effect what errors you will see during VNET startup.

**Comment by rexpo** [comment]
Yeah I kind of do :/

On my host at least (a groovy old HP ML350 G5) there is a a delay of a few seconds after `+ Started OK` and `Starting services OK`, while the epair is created and bridged up. A bit more delay if DHCP is enabled. A very long delay if the DHCP server isn't responding. I just liked the reminder that the reason for the delay was that it was busy setting up (or tearing down) the VNET stuff.
