### ISSUE TITLE
Shortened UUIDs do not seem to work as expected

### ISSUE THREAD

**Issue by olgeni** [iocage/iocage#331]
Testing shortened UUIDs on iocage-devel-20160206 from FreeBSD ports:

    # iocage version
    iocage DEVELOP (2016-02-05)

    # iocage create release=10.2-RELEASE
      Successfully created: b2cd84de-d046-11e5-8e9b-bcaec55be5e5 (2016-02-10@23:36:16)

    # iocage start b2cd84de-d046-11e5-8e9b-bcaec55be5e5
    * Starting b2cd84de-d046-11e5-8e9b-bcaec55be5e5 (2016-02-10@23:36:16)
      + Started (shared IP mode) OK
      + Starting services        OK

    # iocage stop b2cd84de-d046-11e5-8e9b-bcaec55be5e5
    * Stopping b2cd84de-d046-11e5-8e9b-bcaec55be5e5 (2016-02-10@23:36:16)
      + Running pre-stop         OK
      + Stopping services        OK
      + Removing jail process    OK
      + Running post-stop        OK

    # iocage start b2cd84de
      ERROR: b2cd84de not found!

Perhaps they are just not enabled in every command?

**Comment by skarekrow** [comment]
You can not use shortened UUID's for any command anymore. It's simply meant to shorten their mountpoint. If you want an easier way to command  a jail, I recommend using `tag`.

**Comment by olgeni** [comment]
Help says:

    Hint:  you can use shortened UUIDs or TAGs interchangeably!

    e.g. for  adae47cb-01a8-11e4-aa78-3c970ea3222f
      use  adae47cb or just adae

So it should probably be removed at this point :)

**Comment by skarekrow** [comment]
I don't see that in the `develop` branch. Where are you seeing it?

**Comment by olgeni** [comment]
I'm looking at `3ffbc87` and see it in `__usage`, in `lib/ioc-help`. `git blame` says it comes from `ab0014c5`.

**Comment by skarekrow** [comment]
Haha wow, well that is now fixed :D

**Comment by olgeni** [comment]
Thanks :)
