### ISSUE TITLE
Destroy jail does not honour "Procede"

### ISSUE THREAD

**Issue by urosgruber** [iocage/iocage#333]
Make sure to follow and check these boxes before submitting an issue! Thank you.

- [x] Supply `iocage --version`
- [x] Supply the commands used, along with any steps to recreate it.
- [x] Provide the output from the command you issued.
- [x] Supply what you expected the result or output to be
- [ ] Checked that the problem has not already been fixed on `master` if using
 a stable release.

Iocage 0.9.9.1 08/01/2017

`iocage list -l`

```
+-----+------+------+-------+------+------------------+--------------------+-----+------------+
| JID | NAME | BOOT | STATE | TYPE |     RELEASE      |        IP4         | IP6 |  TEMPLATE  |
+=====+======+======+=======+======+==================+====================+=====+============+
| 108 | m1   | off  | up    | jail | 11.0-RELEASE-p12 | em0|192.168.168.80 | -   | mytemplate |
+-----+------+------+-------+------+------------------+--------------------+-----+------------+
| 104 | m2   | on   | up    | jail | 11.0-RELEASE-p12 | em0|192.168.168.81 | -   | mytemplate |
+-----+------+------+-------+------+------------------+--------------------+-----+------------+
| 105 | m3   | off  | up    | jail | 11.0-RELEASE-p12 | em0|192.168.168.82 | -   | mytemplate |
+-----+------+------+-------+------+------------------+--------------------+-----+------------+
| 106 | m4   | on   | up    | jail | 11.0-RELEASE-p12 | em0|192.168.168.83 | -   | mytemplate |
+-----+------+------+-------+------+------------------+--------------------+-----+------------+
| -   | m5   | off  | down  | jail | 11.0-RELEASE-p12 | em0|192.168.168.84 | -   | mytemplate |
+-----+------+------+-------+------+------------------+--------------------+-----+------------+
| -   | m6   | off  | down  | jail | 11.0-RELEASE-p12 | em0|192.168.168.85 | -   | mytemplate |
+-----+------+------+-------+------+------------------+--------------------+-----+------------+
| 109 | m7   | on   | up    | jail | 11.0-RELEASE-p12 | em0|192.168.168.86 | -   | mytemplate |
+-----+------+------+-------+------+------------------+--------------------+-----+------------+
| 110 | m8   | on   | up    | jail | 11.0-RELEASE-p12 | em0|192.168.168.87 | -   | mytemplate |
+-----+------+------+-------+------+------------------+--------------------+-----+------------+
| 111 | m9   | on   | up    | jail | 11.0-RELEASE-p12 | em0|192.168.168.88 | -   | mytemplate |
+-----+------+------+-------+------+------------------+--------------------+-----+------------+
```

`iocage list -lt`
```
+-----+------------+------+-------+----------+------------------+-----+-----+----------+
| JID |    NAME    | BOOT | STATE |   TYPE   |     RELEASE      | IP4 | IP6 | TEMPLATE |
+=====+============+======+=======+==========+==================+=====+=====+==========+
| -   | mytemplate | off  | down  | template | 11.0-RELEASE-p12 | -   | -   | -        |
+-----+------------+------+-------+----------+------------------+-----+-----+----------+
```

`iocage destroy mytemplate`

```
This will destroy jail mytemplate

Are you sure? [y/N]: y
Partial UUID/NAME supplied, cannot check for dependant jails.

Proceed? [y/N]: n
Destroying mytemplate
```

`iocage list`
```
+-----+------+-------+---------+-----+
| JID | NAME | STATE | RELEASE | IP4 |
+=====+======+=======+=========+=====+
+-----+------+-------+---------+-----+
```

First of all I would expect to Alert the user that all the jails created from template will be destroyed and second of all I use **N** on Proceed and it still destroyed everything. I'm a bit scared of using this tool in production. 

And if I can ask here while discussion is about templates. Could be I'm missing something but creating a template snapshot does not allow me to create new jail from this snapshot, right? Let me explain my scenario. 

1. create a template and make specific changes
2. somehow mark a version of this template
3. automated process is creating jails on demand from a specific template
4. there are some updates needed for this template, so start template, do changes, test if all good etc.
5. create new version (snapshot)
6. update automated process to use new version, upgrade old jails to use latest version
7. destroy old version

I believe this was possible with clones on legacy iocage so I tried with clones as well and it doesn't work either.

**Comment by skarekrow** [comment]
Yikes. I'll look into it. You can create a feature request for that other one, we can add a snapshot flag to `clone`. 

You _should_ be scared to use it in production. It's not 1.0, and I've labeled it a beta project on the readme ;)

In addition each release on GitHub is marked prerelease. So for anybody following this project via email and happen to read my reply -- *iocage is a beta*

Not hating on you personally @urosgruber, but I'm seeing this sentiment repeated often. Trying to make it crystal clear for people. I may have to make the beta text on the readme larger.

**Comment by urosgruber** [comment]
@skarekrow I'm aware of Beta state. I was just that feeling "WTF, did I mistype something". And that is why I'm doing thorough testing to evaluate if this tool will work for my specs ;)

**Comment by skarekrow** [comment]
@urosgruber I appreciate it! Just trying to make it more clear for all. Promise you aren't the last straw or the reason ;) but this was as good a place as any to have my bitch fit haha. 

It's indeed a WTF moment as I don't remember it doing that during testing. I'll circle back to you next week.

**Comment by urosgruber** [comment]
@skarekrow I'll probably issue some other bugs that I noticed during my testing. And if you need any more details for this use case. I guess it's better to issue one ticket per bug?

**Comment by urosgruber** [comment]
@skarekrow one side affect 
`jls`
```
 104  192.168.168.82  m2                            /iocage/jails/m2/root
   105  192.168.168.83  m3                            /iocage/jails/m3/root
   106  192.168.168.84  m4                            /iocage/jails/m4/root
   108  192.168.168.80  m1                            /iocage/jails/m1/root
   109  192.168.168.86  m7                            /iocage/jails/m7/root
   110  192.168.168.87  m8                            /iocage/jails/m8/root
   111  192.168.168.88  m9                            /iocage/jails/m9/root
```

**Comment by skarekrow** [comment]
@urosgruber yes one ticket per issue please. And that's likely because it wasn't expected to tear all those jails down and thus didn't do the nice `stop` routine on them.

**Comment by rwestlund** [comment]
@urosgruber Sounds like we have a similar setup.  Here's how I'm doing it:

I think of templates as immutable.  I have a jail that I use as my HEAD for development of code and packages.  When I want to start using it, I clone it with a version number in the name, then convert that clone to a template.

This gives me a jail called `base-head` and a series of immutable templates like `base-v1.2.3`, `base-v1.2.4`, `base-v2.0.0`, etc.

I create thin "basejails" that mount directories (and share ports) from the template version they're using, like this:
```
iocage create -n $DEPLOY_NAME -t base-v1.2.3 -b
iocage fstab -a $DEPLOY_NAME "/iocage/templates/base-v1.2.3/root/usr/local /usr/local nullfs ro 0 0"
```

When I want to upgrade a deployed jail, I update `base-head`, clone a new template from it, then run a command like:
```
sed -i'' -e "s/base-v1.2.3/base-v2.0.0/g" "/iocage/jails/$DEPLOY_NAME/fstab"
```

This changes which template version the jail uses, effectively updating it in a deterministic way.  The only data that actually lives in each jail is my customer-specific data.

I'll do a full writeup on this strategy at some point, but iX is rewriting iocage _yet again_ in that library PR and I'm waiting at least until that merge before any of this touches my prod servers.

**Comment by skarekrow** [comment]
@rwestlund You misunderstand. iX is not rewriting anything. I rewrote iocage, and @gronke started with a small commit and it snowballed into something large. He's not affiliated with iX nor is this a sponsored project by it. 

I'm only clarifying as gronke deserves the credit he's due. It's a massive undertaking for an outside contributor to come in and do. I simply asked some of my iX friends to help review the PR. 

EDIT: But that's a fantastic write up on your setup. Thanks!

**Comment by rwestlund** [comment]
@skarekrow Oh, thanks for the clarification.  I didn't mean to step on any toes; the PR is a great improvement.  I'm just eager to actually deploy this because it will make my life much easier :)

**Comment by skarekrow** [comment]
The rest of this issue is the same as https://github.com/iocage/iocage/issues/285, so I will close this one.
