### ISSUE TITLE
Jails with IPs that are very similar claim to conflict on startup

### ISSUE THREAD

**Issue by Terhands** [iocage/iocage#334]
FreeBSD Version 10.3-RELEASE
iocage Version 0.9.8.1 05/23/2017

Creating two jails with similar IPv4 addresses and trying to start both jails results in a IP already in use error.

The list of jails via `iocage list`:
```
+-----+----------+-------+-----------+--------------+-------------+
| JID |   UUID   | STATE |    TAG    |   RELEASE    |     IP4     |
+=====+==========+=======+===========+==============+=============+
| 30  | 84954474 | up    | A          | 10.3-RELEASE | 172.24.1.2  |
+-----+----------+-------+-----------+--------------+-------------+
| -   | c5c50736 | down  | myjail     | 10.3-RELEASE | 172.24.1.96 |
+-----+----------+-------+-----------+--------------+-------------+
| 32  | 045b8f95 | up    | B          | 10.3-RELEASE | 172.24.1.6  |
+-----+----------+-------+-----------+--------------+-------------+
| 34  | 54a55b91 | up    | C          | 10.3-RELEASE | 172.24.1.8  |
+-----+----------+-------+-----------+--------------+-------------+
| 31  | b078a70e | up    | D          | 10.3-RELEASE | 172.24.1.5  |
+-----+----------+-------+-----------+--------------+-------------+
| 33  | 4a234c0c | up    | E          | 10.3-RELEASE | 172.24.1.7  |
+-----+----------+-------+-----------+--------------+-------------+
| 29  | a22e1d3c | up    | F          | 10.3-RELEASE | 172.24.1.9  |
+-----+----------+-------+-----------+--------------+-------------+
```

With this state running `iocage start myjail` results in the error: `IP is in use. Please change c5c50736-1de4-4ba7-baa8-da1ac4ca4bf1 (myjail)'s IP.`

`myjail` with IP 172.24.1.96 is conflicting with `F`. 

If `F` is stopped `myjail` is able to start successfully, and then likewise trying to start `F` while `myjail` is up results in the same error.

**Comment by rwestlund** [comment]
Update iocage to the current version.  That's an old bug.

**Comment by skarekrow** [comment]
One of the check boxes says to check `master` before filing an issue and to search for an existing one . Please read them next time :+1:
