### ISSUE TITLE
Services don't start on basejail startup

### ISSUE THREAD

**Issue by zilti** [iocage/iocage#335]
I noticed services I've activated in the jail's `/etc/rc.conf` don't get started when starting the jail. Is this not the intended way to start services in a jail?

**Comment by skarekrow** [comment]
Yes that is how you enable and disable services in a jail. Can you show your `rc.conf` please?

**Comment by skarekrow** [comment]
If you

**Comment by zilti** [comment]
Here is one of my jail's rc.conf:

```
hostname="32d792b1-d372-11e5-a5f2-d1eb9e29ef55"

cron_flags=" -J 15"

# Disable Sendmail by default
sendmail_enable="NONE"
sendmail_submit_enable="NO"
sendmail_outbound_enable="NO"
sendmail_msp_queue_enable="NO"

# Run secure syslog
syslogd_flags="-c -ss"

# Enable IPv6
ipv6_activate_all_interfaces="YES"

svscan_enable="YES"
```

It's almost the same with my mailserver jail - except that there, postfix gets started properly, but neither dovecot nor spamd.

**Comment by skarekrow** [comment]
Have you tried running `service svscan start` in the jail? I'm going to assume that you did not do the rest of the post install steps needed for that service.

I followed this [website](http://www.cyberciti.biz/faq/freebsd-configure-djbdns-tinydns-server/) and it does indeed function on jail start.

```
root@a4e8cd05-e03c-11e5-b0bc-00a098690e88:~ # echo 'svscan_enable="YES"' >> /etc/rc.conf
root@a4e8cd05-e03c-11e5-b0bc-00a098690e88:~ # pkg install daemontools
Updating FreeBSD repository catalogue...
FreeBSD repository is up-to-date.
All repositories are up-to-date.
Updating database digests format: 100%
The following 1 package(s) will be affected (of 0 checked):

New packages to be INSTALLED:
        daemontools: 0.76_17

The process will require 256 KiB more space.
51 KiB to be downloaded.

Proceed with this action? [y/N]: y
[a4e8cd05-e03c-11e5-b0bc-00a098690e88] Fetching daemontools-0.76_17.txz: 100%   51 KiB  52.7kB/s    00:01
Checking integrity... done (0 conflicting)
[a4e8cd05-e03c-11e5-b0bc-00a098690e88] [1/1] Installing daemontools-0.76_17...
[a4e8cd05-e03c-11e5-b0bc-00a098690e88] [1/1] Extracting daemontools-0.76_17:
--snip--
root@a4e8cd05-e03c-11e5-b0bc-00a098690e88:~ # service svscan start
/usr/local/etc/rc.d/svscan: WARNING: /var/service is not a directory.
root@a4e8cd05-e03c-11e5-b0bc-00a098690e88:~ # service svscan status
svscan is not running.
root@a4e8cd05-e03c-11e5-b0bc-00a098690e88:~ # pw groupadd dnsusers
root@a4e8cd05-e03c-11e5-b0bc-00a098690e88:~ # pw useradd tinydns -s /bin/nologin -G dnsusers
root@a4e8cd05-e03c-11e5-b0bc-00a098690e88:~ # pw useradd dnslog -s /bin/nologin -G dnsusers
root@a4e8cd05-e03c-11e5-b0bc-00a098690e88:~ # pw useradd axfrdns -s /bin/nologin -G dnsusers
root@a4e8cd05-e03c-11e5-b0bc-00a098690e88:~ # mkdir /var/service/
root@a4e8cd05-e03c-11e5-b0bc-00a098690e88:~ # service svscan start
Starting svscan.
root@a4e8cd05-e03c-11e5-b0bc-00a098690e88:~ # service svscan status             svscan is running as pid 74081.
root@a4e8cd05-e03c-11e5-b0bc-00a098690e88:~ # exit
logout
bschneider@iocage-dev:~ % sudo iocage reboot test1
* Stopping a4e8cd05-e03c-11e5-b0bc-00a098690e88 (test1)
  + Running pre-stop         OK
  + Stopping services        OK
  + Removing jail process    OK
  + Running post-stop        OK
* Starting a4e8cd05-e03c-11e5-b0bc-00a098690e88 (test1)
  + Started (shared IP mode) OK
  + Starting services        OK
bschneider@iocage-dev:~ % sudo iocage console test1
root@a4e8cd05-e03c-11e5-b0bc-00a098690e88:~ # service svscan status
svscan is running as pid 74904.
```
<b>rc.conf</b>
```
root@a4e8cd05-e03c-11e5-b0bc-00a098690e88:~ # cat /etc/rc.conf
hostname="a4e8cd05-e03c-11e5-b0bc-00a098690e88"

cron_flags=" -J 15"

# Disable Sendmail by default
sendmail_enable="NONE"
sendmail_submit_enable="NO"
sendmail_outbound_enable="NO"
sendmail_msp_queue_enable="NO"

# Run secure syslog
syslogd_flags="-c -ss"

# Enable IPv6
ipv6_activate_all_interfaces="YES"
svscan_enable="YES"
```

**Comment by zilti** [comment]
Yes, I did `iocage chroot` into the jail and ran this. It works after running `service svscan start`. Same goes for dovecot and sa-spamd in the mailserver jail.

**Comment by skarekrow** [comment]
I'm not sure what else to suggest, as it works for me. Along with any other service I've ever tried in a jail. There is something in your configuration that isn't functioning. Have you tried something simple like a jail with just `nginx_enable="YES"` after you've installed nginx for a test?

There are a lot of factors that can go wrong with the other services you're trying that are likely the problem.

**Comment by zilti** [comment]
I'm not sure if maybe my whole install has gone wrong somewhere? As I said, with some services, like postfix, it works, and with others, like dovecot, it doesn't. I also noticed that stopping a jail doesn't necessarily fully terminate everything inside.

**Comment by skarekrow** [comment]
Well beyond the [exec_start](https://github.com/iocage/iocage/blob/develop/lib/ioc-globals#L44) line, we doing nothing extra for rc.conf. It's the responsibility of `jail`. So if one service works and the other doesn't, that points at something being misconfigured. Unfortunately I couldn't tell you what, but that's a fun learning exercise anyways :D

Like I said, every service I've tried works including the `svscan` one you are having troubles with. I would suggest auditing your setup and trying many things. But there is nothing for iocage to fix here, sorry.

As for the jail not fully terminating everything, that is a sympom of you using `iocage exec` to start a service with a basejail. If that's the case, then it indeed will not terminate everything. It's been removed from the `develop` branch for that reason among others.

It may be beneficial to try another pool or a VM on a machine and replicate your setup using `iocage stable` and `iocage develop` to see exactly which piece of the puzzle is the problem.

Good luck!

**Comment by zilti** [comment]
I tried it with another server now. Installed FreeBSD 10.2, recompiled kernel for VNET, installed iocage. After running `iocage fetch` I created a jail with `iocage create -b tag=test`. 
This is my rc.conf:

```
hostname="5a5ba05a-e875-11e5-8209-3ca82a9f584c"

cron_flags=" -J 15"

# Disable Sendmail by default
sendmail_enable="NONE"
sendmail_submit_enable="NO"
sendmail_outbound_enable="NO"
sendmail_msp_queue_enable="NO"

# Run secure syslog
syslogd_flags="-c -ss"

# Enable IPv6
ipv6_activate_all_interfaces="YES"
local_enable="YES"
svscan_enable="YES"
```

I added a line in rc.local to install daemontools and then start svscan and delete itself. I then ran the jail with `iocage start test`. Guess what? rc.local wasn't started. So I chrooted into the jail with `iocage chroot test` and ran it myself which worked fine. I then tested if svscan would get started at next jail startup. So I did `iocage stop test && iocage start test` (I don't trust restart). Svscan wasn't running. Again, I chrooted into the jail and had to run `service svscan start`. It reliably never starts on jail startup. If it's of any use, this is the host system's rc.conf:

```
hostname="<redacted>"
cloned_interfaces="bridge0 bridge1"
ifconfig_bridge0="addm bge0 up"
ifconfig_bge0="DHCP"

zfs_enable="YES"
cron_enable="YES"
sshd_enable="YES"
local_enable="YES"
ntpd_enable="YES"
```

So I definitely don't see how this could be my fault at this point. I'm using the iocage distributed in ports.

**Comment by skarekrow** [comment]
It's `rc.conf.local` not `rc.local`. That is likely your issue.

**Comment by zilti** [comment]
No, that's not my issue - my issue is, as it turns out, that there's absolutely no network connectivity inside the jail itself. Of course everything worked when I called my scripts inside the jail via "iocage chroot", but e.g. dovecot terminates when there's no network connection.

And I have none despite doing everything as described in the docs. It doesn't make a difference if I try it with or without VNET.

**Comment by skarekrow** [comment]
How are you setting the `ip4_addr` property for the jails? It should make quite a difference between VNET or shared networking, as they are very different. At-least we know this is a problem that can be easily solved!

**Comment by zilti** [comment]
Well, I figured it out for shared ip. As for VNET, I'm totally clueless. The iocage.readthedocs-documentation is either wrong or very incomplete, I cannot tell, but it doesn't work. Also I didn't find anything else online, and currently I'm asking on the FreeBSD subreddit, but I think I'll let it be, as no one could help me so far. I wasted enough time on VNET already. But thanks!
