### ISSUE TITLE
"[: -gt: unexpected operator" in inuse operation when jails are stopped

### ISSUE THREAD

**Issue by olgeni** [iocage/iocage#336]
Something weird is going on with the "inuse" operation.

    # iocage version
    iocage DEVELOP (2016-02-05)

But it is the same on today's develop branch.

I have some jails running:

    # iocage list 
    JID  UUID                                  BOOT  STATE  TAG     TYPE       IP4
    5    608d1dc1-cffd-11e5-9a8d-080027af0e2a  off   up     pgsql   emptyjail  172.20.0.1
    4    853c5a30-cffe-11e5-9a8d-080027af0e2a  off   up     redis   emptyjail  172.20.0.2
    3    b6011e03-d3eb-11e5-906e-080027af0e2a  off   up     kibana  emptyjail  172.20.0.3

And inuse works fine:

    # iocage inuse
    UUID,TAG,cputime,datasize,stacksize,coredumpsize,memoryuse,memorylocked,maxproc,openfiles,vmemoryuse,pseudoterminals,swapuse,nthr,msgqqueued,msgqsize,nmsgq,nsem,nsemop,nshm,shmsize,wallclock,pcpu
    608d1dc1-cffd-11e5-9a8d-080027af0e2a,pgsql,0,56K,264K,0,8380K,0,2,80,74M,0,0,2,0,0,0,0,0,0,0,387,0
    853c5a30-cffe-11e5-9a8d-080027af0e2a,redis,0,56K,264K,0,8388K,0,2,80,74M,0,0,2,0,0,0,0,0,0,0,412,0
    b6011e03-d3eb-11e5-906e-080027af0e2a,kibana,2653,828K,8840K,0,363M,0,17,896,3678M,1,21G,72,0,0,0,0,0,0,0,32K,0

I stop one jail:

    # iocage stop kibana
    * Stopping b6011e03-d3eb-11e5-906e-080027af0e2a (kibana)
      + Running pre-stop         OK
      + Stopping services        OK
      + Removing jail process    OK
      + Running post-stop        OK

And inuse emits a warning:

    # iocage inuse      
    UUID,TAG,cputime,datasize,stacksize,coredumpsize,memoryuse,memorylocked,maxproc,openfiles,vmemoryuse,pseudoterminals,swapuse,nthr,msgqqueued,msgqsize,nmsgq,nsem,nsemop,nshm,shmsize,wallclock,pcpu
    608d1dc1-cffd-11e5-9a8d-080027af0e2a,pgsql,0,56K,264K,0,8380K,0,2,80,74M,0,0,2,0,0,0,0,0,0,0,415,0
    853c5a30-cffe-11e5-9a8d-080027af0e2a,redis,0,56K,264K,0,8388K,0,2,80,74M,0,0,2,0,0,0,0,0,0,0,438,0
    [: -gt: unexpected operator

I stop another jail:
       
    # iocage stop redis
    * Stopping 853c5a30-cffe-11e5-9a8d-080027af0e2a (redis)
      + Running pre-stop         OK
      + Stopping services        OK
      + Removing jail process    OK
      + Running post-stop        OK

You get the point :)
      
    # iocage inuse     
    UUID,TAG,cputime,datasize,stacksize,coredumpsize,memoryuse,memorylocked,maxproc,openfiles,vmemoryuse,pseudoterminals,swapuse,nthr,msgqqueued,msgqsize,nmsgq,nsem,nsemop,nshm,shmsize,wallclock,pcpu
    608d1dc1-cffd-11e5-9a8d-080027af0e2a,pgsql,0,56K,264K,0,8380K,0,2,80,74M,0,0,2,0,0,0,0,0,0,0,438,0
    [: -gt: unexpected operator
    [: -gt: unexpected operator

**Comment by skarekrow** [comment]
All fixed :)

**Comment by olgeni** [comment]
Thanks! \o/

**Comment by skarekrow** [comment]
Np \m/
