### ISSUE TITLE
Export in 1.7.3 does not properly export thickjails.

### ISSUE THREAD

**Issue by MrClayPole** [iocage/iocage#337]
Hi, I'm currently running DEVELOP (2016-02-05) version of iocage. I exported a jail from one FreeBSD 10.2 to another FreeBSD 10.2. The jail was created using an earlier version of iocage. Once imported to the new system I got the following error 3 times when running "iocage start <tag>". The jail runs without issue.

/usr/local/sbin/iocage: cannot create /iocage/jails/9c9d526f-7330-11e5-b090-f46d04d89d61/root/etc/rc.conf: No such file or directory

I think it maybe due to the hack88 feature as the correct path to rc.conf in the jail from outside the jail would be iocage/jails/9c9d526f/root/etc/rc.conf rather than iocage/jails/9c9d526f-7330-11e5-b090-f46d04d89d61/root/etc/rc.conf

**Comment by skarekrow** [comment]
Interesting. I fixed some hack88 weirdness on the 2nd. Are you able to lay out your steps a bit more clearly so I can try to replicate please?

**Comment by MrClayPole** [comment]
The jail was created of first system using iocage 1.6.x or 1.7.x (sorry can't remember which version). I then upgrade to iocage dev (2016-02-05) as the import function in iocage 1.7.3 just hung and I could see there bug fix for this in the dev version. Below is the "iocage get all" for jail that is still registered on source server. it was then export using "iocage export cn-jail-web-01"

> interfaces:vnet0:bridge0,vnet1:bridge1
vnet:off
host_domainname:-
host_hostname:cn-jail-web-01
ip4_addr:re0|172.28.182.24
ip4_autostart:none
ip4_autoend:none
ip4_autosubnet:none
ip4_saddrsel:1
ip4:new
ip6_addr:none
ip6_saddrsel:1
ip6:new
defaultrouter:none
defaultrouter6:none
resolver:search clarkesnet.local;nameserver 172.28.182.254
exec_fib:0
vnet0_mac:none
vnet1_mac:none
vnet2_mac:none
vnet3_mac:none
devfs_ruleset:4
mount_devfs:1
exec_start:/bin/sh /etc/rc
exec_stop:/bin/sh /etc/rc.shutdown
exec_prestart:/usr/bin/true
exec_prestop:/usr/bin/true
exec_poststop:/usr/bin/true
exec_poststart:/usr/bin/true
exec_clean:1
exec_timeout:60
stop_timeout:30
exec_jail_user:root
exec_system_jail_user:0
exec_system_user:root
mount_fdescfs:1
mount_procfs:0
mount_linprocfs:-
enforce_statfs:2
children_max:0
login_flags:-f root
securelevel:2
allow_set_hostname:0
allow_sysvipc:0
allow_raw_sockets:0
allow_chflags:0
allow_mount:0
allow_mount_devfs:0
allow_mount_nullfs:0
allow_mount_procfs:0
allow_mount_tmpfs:0
allow_mount_zfs:0
allow_quotas:0
allow_socket_af:0
host_hostuuid:5b92490c-587c-11e5-9a22-f46d04d89d61
memoryuse:8G:log
memorylocked:off
vmemoryuse:off
maxproc:off
cputime:off
pcpu:off
datasize:off
stacksize:off
coredumpsize:off
openfiles:off
pseudoterminals:off
swapuse:off
nthr:off
msgqqueued:off
msgqsize:off
nmsgq:off
nsemop:off
nshm:off
shmsize:off
wallclock:off
tag:cn-jail-web-01
template:no
istemplate:-
rlimits:off
bpf:-
boot:off
dhcp:-
notes:none
owner:root
priority:99
pkglist:-
last_started:2016-02-08_18:16:33
type:thickjail
hostid:1e002e60-008c-4300-24d4-f46d04d89d61
cpuset:off
jail_zfs:off
jail_zfs_dataset:iocage/jails/5b92490c-587c-11e5-9a22-f46d04d89d61/root/data
jail_zfs_mountpoint:-
release:10.2-RELEASE
hack88:1
start:-
count:-
sync_stat:-
sync_target:none
sync_tgt_zpool:none
ftphost:-
ftpfiles:-
ftpdir:-
ftplocaldir:-
gitlocation:https://github.com
branch:-
compression:off
origin:-
quota:none
mountpoint:/iocage/jails/5b92490c
compressratio:2.04x
available:1.29T
used:1.23G
dedup:off
reservation:none

> 

I then SCP the image to a new server. It was then import on the target system using "iocage import 5b92490c-587c-11e5-9a22-f46d04d89d61". This server is also running iocage dev (2016-02-05).

the diff of the "iocage get all cn-jail-web-01" on the target server is shown below

> 
ip4_addr:em0|172.28.182.24
exec_prestart:/iocage/scripts/cn-jail-web-01-pre.sh
last_started:2016-02-15_16:27:44
hostid:00000000-0000-0000-0000-0025908675f8
compressratio:2.05x
available:209G
used:1.00G

>

**Comment by skarekrow** [comment]
Did you specify hack88=1 during the import procedure? Because if you didn't, that wouldn't have been set. Just trying to nail down how you did this :) hack88 should have no effect on import :/

**Comment by skarekrow** [comment]
Ok, I've been able to reproduce it. So far it looks fairly nasty, as it doesn't seem to be importing any data. Will fix :)

**Comment by skarekrow** [comment]
I believe I fixed it, will test and commit to the `master` branch as this is technically 1.7.4 then. You will have to update your iocage on the source side to 1.7.4 release and re-export your jail before trying to import with `develop` again.

Thanks for the report!

**Comment by skarekrow** [comment]
Confirmed, this fixes it. Committing now.
