### ISSUE TITLE
iocage fetch ignores --server option

### ISSUE THREAD

**Issue by rexpo** [iocage/iocage#338]
I used to be able to specify an alternate FTP server location for `iocage fetch`. Now it seems to be ignored and hardcoded to `ftp.freebsd.org`. Has this feature been disabled for some reason?

I just tested all the tagged releases from 0.9.7 through 0.9.9.1, and the `fetch --server` command is working as expected, fetching from the specified server. ***The problem seems to have been introduced sometime after 0.9.9.1***.

- [x] Supply `iocage --version`

Version	0.9.9.2 ALPHA
HEAD is now at 1378511 Only specify ip[46].addr on jail command line if set (#336)

- [x] Supply the commands used, along with any steps to recreate it.

```
iocage clean --all
(it cleans...)
iocage list
(it creates missing datasets...)
iocage fetch --release 10.3-RELEASE --server localhost
(or else it gets the hose again...)
```

- [x] Provide the output from the command you issued.

```
Fetching: 10.3-RELEASE

Downloading: MANIFEST: 100% 3.29Kbit/s Elapsed: 00:00 Remaining: 00:00
Downloading: base.txz:  65% 5.10Mbit/s Elapsed: 00:10 Remaining: 00:04
...
```

Note that the download speed is maxing out at ***5.10 Mb/s***, which is the limit of my broadband connection...

- [x] Supply what you expected the result or output to be

```
Fetching: 10.3-RELEASE
                                                                                  
Downloading: MANIFEST: 100% 1.69Mbit/s Elapsed: 00:00 Remaining: 00:00
Downloading: base.txz: 100% 541Mbit/s Elapsed: 00:00 Remaining: 00:00
...
```

...but I have a local FTP server running on my host, populated with 9.3, 10.3, and 11.0-RELEASE. I should be seeing (on this host, anyway) speeds in the hundreds of Mb/s, as was the case until sometime after version 0.9.9.1.

**Comment by skarekrow** [comment]
I use this functionality often, surprising to see it's not working. I'll look into it next week to see what happened.

**Comment by rexpo** [comment]
Yeah I was using it a lot myself a couple months ago, when I was working on all that "setting up a full iocage development environment with PyCharm" stuff, specifically because it sped up the pytest stuff so nicely. I hadn't tried it in quite a while, then today I decided to bring my second test server up to the latest & greatest iocage at 1378511 (it has way more RAM and disk space), wiping away the old crud that used to be there. This is when I noticed the fetch speeds exactly matching my broadband max-out speed.

Just to be sure, I wiped my PyCharm venvs, created fresh ones, installed dependencies anew, wiped my iocage source dir, and git clone --recursive'd them, but same deal.

Now maybe I'm gitting wrong, but the way I tested the older versions was to do a:

```
git fetch origin
```

Which probably wasn't necessary after having just freshly cloned, but anyway. Then to test 0.9.7:

```
git reset --hard 0.9.7
```

and so on for the other versions up to 0.9.9.1. To get back to the latest & greatest, I used:

```
git reset --hard origin/master
```

It's right? (I'm still trying to get my head around git - after so many years of using svn it's still confusing me!)

Anyway, I just tested this again on my other test server (the one I have been using actively for testing the boss new DHCP stuff over the past couple weeks) and it exhibits the same behaviour.

I was poking around in the source code earlier today, but I can't see that there are any changes to how `server` is handled in the fetch routines. Makes me wonder if the problem lies elsewhere, for example in hostname lookup for `localhost` or in the FTP routines. If I get time tomorrow morning, I'll try to step through a fetch with 0.9.9.1 in my fabulous PyCharm debugger ;)

**Comment by rexpo** [comment]
`git bisect`! wow!

I still don't know why it's broken, but the problem was introduced in 97defc5

```
97defc51bb309366fff5ed20f6f564d18fe1cdc4 is the first bad commit
commit 97defc51bb309366fff5ed20f6f564d18fe1cdc4
Author: Brandon Schneider <brandon@ixsystems.com>
Date:   Fri Aug 11 01:39:04 2017 -0500

    Log to stderr if calling from the CLI.

    Also logging to stderr for anything WARNING and above.

:040000 040000 da6ea110fd3c5a49f1909f2528dcc864f91b02b4 d07fdfccd1ec4217df29d110c5d814071164a9a3 M	iocage
```

**Comment by rexpo** [comment]
One thing that bothers me, is how the `server` information gets passed from the `fetch` routine in `lib/iocage.py` to the `IOCFetch` object in `lib/ioc_fetch.py`.

Ah! It is (well, was) done via the `**kwargs` stuff - but you (inadvertently?) removed that in commit 97defc5 in several places in the `fetch` routine in `lib/iocage.py`. I've left a comment in the commit thingy at one such place.

Putting the `**kwargs` guy back in the parameter list fixes this for me.
