### ISSUE TITLE
Using pkg wrapper with tag gives error not found

### ISSUE THREAD

**Issue by urosgruber** [iocage/iocage#338]
I have one jail available 

```
JID  UUID                                  BOOT  STATE  TAG    TYPE      IP4
245  2f0bc526-d4f7-11e5-b2a3-7071bca7c826  off   up     xtest  basejail  -
```

Then after I try the command `iocage -v pkg xtest list` based on man page It return back **ERROR: xtest not found.**
Flag -v shows also this

```
+ jls -h jid host.hostname
+ grep -w xtest
+ cut -w -f 1
```

and jls is clearly wrong because neither jid nor hostname is the same as a TAG. Am I doing something wrong or it's just devel version that I'm using broken and this is already fixed in the latest version?

**Comment by skarekrow** [comment]
Sorry about that! Somebody committed that function a little while back and I glanced at it. It seemed fine, but I obviously missed the problems at that point ;) 

It's fixed now, thanks for reporting!
