### ISSUE TITLE
Switching templates

### ISSUE THREAD

**Issue by ari** [iocage/iocage#339]
I have a use case for iocage and I'm not understanding the options available with 'packaging' and 'templates'.

I have an application which needs to be upgraded regularly (roughly once a month). About 30-50 jails needs to each be running some version of the application (and nothing else).

It appears that I can install my application into a template or a package. And then use that to create all the jails. Since packages use unionfs which might not be reliable, I'm guessing that isn't the approach I should take.

When upgrading a jail from one application version to another does the template act as an 'overlay' so I  I can change the template from which it is cloned, keeping any other files added to the jail? Or do I effectively need to delete the jail, create it again with the updated template and then replace any custom files in the jail?

**Comment by skarekrow** [comment]
So the current approach works like this:
- Create a template (set a jail's `istemplate` to `yes`)
- Then clone from that template (`iocage clone TEMPLATE key=val key=val`) Of note to you may be the `count` property which will automatically create X number of jails with the naming scheme of `jailtag_1, jailtag_2, etc`.

This approach will require you to update the template if a new version of the application is desired or any other modification to the template is done and reclone all the jails like you did in Step 2. Right now it's actually under a fair amount of refactoring so this may or may not change. We're playing with union templates in https://github.com/iocage/iocage/issues/334 but that is likely not to come to complete fruition currently.

These steps all assume you were using the `develop` branch. If you are using the `master` branch, then you just need to set `template=yes` to convert a jail to a template and then call clone with the uuid of the template (`iocage clone UUIDOFTEMPLATE key=val key=val`).

**Comment by ari** [comment]
Thanks. So I assume there is no mechanism to switch an existing jail from one template to another template? The process would be to destroy the jail and start again?

**Comment by skarekrow** [comment]
Correct that is the current behavior.

**Comment by ari** [comment]
Thank you. I suggest you could add a bit more to the documentation to explain these processes more clearly, but I'll close this issue.

**Comment by skarekrow** [comment]
Have been avoiding adding extra documentation as this particular feature has seen a lot of churn. Right now the documentation is essentially what we have in the stable version.
