### ISSUE TITLE
tag not considered a valid property

### ISSUE THREAD

**Issue by mpounsett** [iocage/iocage#339]
Using iocage 0.9.9.1 08/01/2017 from ports on FreeBSD 11.1-RELEASE.

Following the examples from the readme, 'tag' is reported as not being a valid property.
```
% sudo iocage create tag=myjail -r 11.1-RELEASE
tag is not a valid property!

```
I searched the issues db but don't see anything related.

- [x] Supply `iocage --version`
- [x] Supply the commands used, along with any steps to recreate it.
- [x] Provide the output from the command you issued.
- [x] Supply what you expected the result or output to be
- [x] Checked that the problem has not already been fixed on `master` if using
 a stable release.

**Comment by skarekrow** [comment]
`tag` was replaced by `--name (-n)` in the latest release.

**Comment by mpounsett** [comment]
In that case it looks like there is a problem with the documentation.  The README and the man pages both talk about `tag` rather than `--name`.

**Comment by skarekrow** [comment]
Oh? I'll ping @Mrt134 on that

**Comment by mpounsett** [comment]
Yeah.  Looks like the man pages were inconsistently updated.  There's a mix of `tag=foo` and `TAG` for some commands and `--name` and `NAME` for others.
