### ISSUE TITLE
iocage update <JAIL> removes /etc/resolv.conf from the jail

### ISSUE THREAD

**Issue by cpforbes** [iocage/iocage#34]
The iocage update command removes the /etc/resolv.conf file from the jail after running the update.

This breaks DNS resolution in the jail. Restarting the jail or recreating the file by hand fixes the problem.

iocage version:  master branch commit 058df84-- reported as Version 0.9.4.1 2017/01/29

**Comment by skarekrow** [comment]
Please test this commit and tell me if that fixed things 👍
