### ISSUE TITLE
`iocage list` shows empty jail

### ISSUE THREAD

**Issue by ikanobori** [iocage/iocage#343]
Currently when I list my jails on one of my hosts I have an 'empty' jail. One without a UUID, tag, or other associated information. I'd like to know how to clean it up (I have replaced the tags with xxx's).

```
root@xxx:~ # iocage list
JID   UUID                                  BOOT  STATE  TAG
5     2b5bd007-e792-11e5-8084-0cc47ac3416c  on    up     xxx
1     2cad6e15-dbb7-11e5-ac7b-0cc47ac3416c  on    up     xxx
-     -  -     down   -
6     5182e842-e792-11e5-8084-0cc47ac3416c  on    up     xxx
2     536d3a66-dbb7-11e5-ac7b-0cc47ac3416c  on    up     xxx
4     7c66471d-e790-11e5-8084-0cc47ac3416c  on    up     xxx
3     a6bbb071-e07d-11e5-bc4a-0cc47ac3416c  on    up     xxx
```
My iocage version is iocage 1.7.4 (2016/02/17) as installed from FreeBSD ports and the issue is also present when using iocage list from a source checkout version.

**Comment by skarekrow** [comment]
You can do a `zfs list -d1 POOL/iocage | egrep -v '2b5bd007-e792-11e5-8084-0cc47ac3416c|2cad6e15-dbb7-11e5-ac7b-0cc47ac3416c|5182e842-e792-11e5-8084-0cc47ac3416c|536d3a66-dbb7-11e5-ac7b-0cc47ac3416c|7c66471d-e790-11e5-8084-0cc47ac3416c|a6bbb071-e07d-11e5-bc4a-0cc47ac3416c'`and then do a `zfs destroy -r POOL/iocage/jails/JAILUUID` on the result it gives you to remove the defunct jail.

I'd then check the `/iocage/tags` directory with `ls -lah` and `rm` any symlinks that were pointing to that UUID.

I'd also recommend that next time you send the jail to a different system you use `-R` or `-P` as iocage relies on the properties to also be sent ;)
