### ISSUE TITLE
jail resource limits

### ISSUE THREAD

**Issue by joachimmathes** [iocage/iocage#343]
Hi @skarekrow,

do you have any plans for implementing jail resource limits? I would like to offer my support. But I won't be able to provide a pull request until about two or three weeks from now.

Greets
Jo

**Comment by gronke** [comment]
Closing this in favor of https://github.com/iocage/libiocage/issues/21 where we will talk about implementation details. @joachimmathes thanks for mentioning it and reminding me to create a ticket :) I want this feature!
