### ISSUE TITLE
Removing /usr/src from jails

### ISSUE THREAD

**Issue by rmelcer** [iocage/iocage#344]
Make sure to follow and check these boxes before submitting an issue! Thank you.

- [x] Supply `iocage version` 
- `iocage 1.7.4 (2016/02/17)`
- [x] Supply the commands used, along with any steps to recreate it. 
- `iocage fetch release=10.1-RELEASE`
- [x] Provide the output from `iocage`
```
[ipsix ~]# du -sh /iocage/releases/10.1-RELEASE/root /iocage/releases/10.1-RELEASE/root/usr/src
850M    /iocage/releases/10.1-RELEASE/root
521M    /iocage/releases/10.1-RELEASE/root/usr/src
```
- [x] Supply what you expected the result or output to be
```
[ipsix ~]# rm -r /iocage/releases/10.1-RELEASE/root/usr/src && du -sh /iocage/releases/10.1-RELEASE/root
329M    /iocage/releases/10.1-RELEASE/root
```
- [ ] Checked that the problem has not already been fixed on `develop` if using the stable release or `master` branch.

Does iocage use /usr/src within jails for anything? It takes up 60+% of 'empty' jails. My end result will involve copying jails and/or jail packages over the network, and size plays an important part in deployment time.

Thanks for your work!

**Comment by skarekrow** [comment]
It's currently being used for `etcupdate` as it requires access to that. I agree, I would like to remove it. At one point I did and that proved futile. 

Appreciate the thanks!
