### ISSUE TITLE
Attempt to migrate jails ends with "<jail-uuid> has a corrupt configuration,please destroy the jail."

### ISSUE THREAD

**Issue by apburgess** [iocage/iocage#344]
When migrating jails from iocage-1.7.6 (iocage_legacy) to iocage using `iocage list`, the migration failed with

`569bb42c-d9a5-11e6-9c7b-000c293ec4d5 has a corrupt configuration,please destroy the jail.`

This seems to be a problem with all the jails on this machine as I got the same error message for another (unimportant) jail, which I *did* delete, but then got the same error message on the next jail it hit.

Both versions of iocage were built from ports, and the machine is FreeBSD 11.1 as of yesterday and was FreeBSD 11.0 prior to that.

Prior to the attempt to migrate the jails, the only command I'd run on the new iocage was `iocage activate zroot` to make sure it used the current jail data.

**Possibly Useful**
Looking at the cause of the error in the source code it looks like it will be output if either of the 'release' or 'cloned_release' keys are missing from the configuration, and the 'cloned_release' key is indeed missing from the generated config.json; checking the original ZFS properties with

`zfs list -o name,org.freebsd.iocage:release,org.freebsd.iocage:cloned_release `

shows the 'cloned_release' property is missing there too.

I imported another jail (on a different VM, FreeBSD 11.0) using an earlier version of py3-iocage a few weeks ago, and had no problems, I've just checked and the 'cloned_release' property is missing on the ZFS datasets there too, but that import/migration worked (it looks like py3-iocage added the relevant key there).

Make sure to follow and check these boxes before submitting an issue! Thank you.

- [X] Supply `iocage --version`
- [X] Supply the commands used, along with any steps to recreate it.
- [X] Provide the output from the command you issued.
- [X] Supply what you expected the result or output to be
- [ ] Checked that the problem has not already been fixed on `master` if using
 a stable release.

**Comment by skarekrow** [comment]
@apburgess Ok in the next release (or master if you're feeling frisky) will have you covered 👍
