### ISSUE TITLE
Allow dataset from different pool in jail_zfs_dataset

### ISSUE THREAD

**Issue by rexpo** [iocage/iocage#345]
iocage is activated on one (for example small, SSD-backed) zpool, and I want to be able to mount datasets from a second (for example massive, but slow HDD-backed) zpool.

This isn't currently possible, as iocage can only mount a dataset from the same pool that iocage is activated on.

I know that I should just shut up, activate the big slow pool, throw lots of RAM at the host, and take comfort in the fact that the ZFS ARC will eventually speed things up. There are, however, other use cases that benefit from the ability to mount a dataset from another pool, especially when it comes to maintenance and migration.

As far as I can tell, work was done on iocage_legacy to implement just such a feature, but that it never made it to prime time. I'm sure this has already been discussed before, but I couldn't find any closed issues about it. Has this already been considered?

**Comment by skarekrow** [comment]
Open this on libiocage Jamie, I think it's a good suggestion but is unlikely to happen in this repo.

**Comment by skarekrow** [comment]
https://github.com/iocage/libiocage/issues/23 I did it for ya :D

**Comment by rexpo** [comment]
ah - is libiocage that boss-ass Python thing that eventually will (or at least could) replace much of the guts of the current iocage? I recall reading an issue some weeks (months) back where @gronke had posted a nice demo of iocage-style control of jails, using simple Python one-liners. That is/was libiocage?

**Comment by gronke** [comment]
@rexpo exactly this is what went to https://github.com/iocage/libiocage - we want to collaborate to develop missing features and clean the interface before using this in iocage main.

**Comment by skarekrow** [comment]
Indeed! It's matured quite a bit, @gronke has been just hella committed to it.
