### ISSUE TITLE
Bad setting for `jail_zfs_dataset` if `jail_zfs` not set at create time

### ISSUE THREAD

**Issue by cloyce** [iocage/iocage#346]
Make sure to follow and check these boxes before submitting an issue! Thank you.

- [x] Supply `iocage version`
- [x] Supply the commands used, along with any steps to recreate it.
- [x] Provide the output from `iocage`
- [x] Supply what you expected the result or output to be
- [x] Checked that the problem has not already been fixed on `develop` if using the stable release or `master` branch.

This is on current develop:
    
    # ./iocage version
    iocage DEVELOP (2016-02-17)

If you create a jail and enable `jail_zfs` after creation, the ZFS dataset can't be created because the wrong UUID has been baked into the default `jail_zfs_dataset` value:

    # ./iocage create tag=testjail                         
      Successfully created: 32d6437c-f140-11e5-ab92-d05099264f2e (testjail)
    
    # ./iocage set jail_zfs=on testjail
    cannot create 'jpool/iocage/jails/32c0f903-f140-11e5-ab92-d05099264f2e/data': parent does not exist

There's code in `__create_jail` to deal with this if `jail_zfs` is set at creation time, and it works:

    # ./iocage create tag=testjail jail_zfs=on             
      Successfully created: 6cb596c5-f140-11e5-ab92-d05099264f2e (testjail)
    
    # ./iocage get jail_zfs_dataset testjail
    iocage/jails/6cb596c5-f140-11e5-ab92-d05099264f2e/data

    # zfs list -r jpool/iocage/jails/6cb596c5-f140-11e5-ab92-d05099264f2e
    NAME                                                           USED  AVAIL  REFER  MOUNTPOINT
    jpool/iocage/jails/6cb596c5-f140-11e5-ab92-d05099264f2e       4.06M  62.7G    96K  /iocage/jails/6cb596c5-f140-11e5-ab92-d05099264f2e
    jpool/iocage/jails/6cb596c5-f140-11e5-ab92-d05099264f2e/data    96K  62.7G    96K  none
    jpool/iocage/jails/6cb596c5-f140-11e5-ab92-d05099264f2e/root  3.87M  62.7G  3.87M  /iocage/jails/6cb596c5-f140-11e5-ab92-d05099264f2e/root

Sorry I've no patch for this; I noticed it when testing my `jail_zfs_mountpoint` changes in #321.  I tried for about 10 minutes to fix it but didn't even get as far as understanding why the UUIDs differ from the start of the iocage run to the point where the jail is created.

**Comment by skarekrow** [comment]
I actually have this fixed in my local changes, just haven't pushed as there are still some rough edges. I'll push shortly, which may require some TLC to your PR. It shouldn't be too bad though.

**Comment by skarekrow** [comment]
Changes have been pushed.

**Comment by cloyce** [comment]
It's still busted:

    # ./iocage version
    iocage DEVELOP (2016-03-23)
    # ./iocage create tag=testjail  
      Successfully created: fd992fb2-f1d5-11e5-ab92-d05099264f2e (testjail)
    # ./iocage set jail_zfs=on testjail
    cannot create 'jpool/iocage/jails/fd7e471c-f1d5-11e5-ab92-d05099264f2e/data': parent does not exist

**Comment by skarekrow** [comment]
Interesting, thought that was fixed. Fixed it again, will push soon.
