### ISSUE TITLE
iocage crashing 

### ISSUE THREAD

**Issue by akelling** [iocage/iocage#346]
Here is my current setup. I cant even run a iocage list
sharp@bebop ~ $ uname -a
FreeBSD bebop 11.1-RELEASE-p1 FreeBSD 11.1-RELEASE-p1 #0: Wed Aug  9 11:55:48 UTC 2017     root@amd64-builder.daemonology.net:/usr/obj/usr/src/sys/GENERIC  amd64
sharp@bebop ~ $ pkg info py36-iocage-0.9.8.1
py36-iocage-0.9.8.1
Name           : py36-iocage
Version        : 0.9.8.1
Installed on   : Sat Aug  5 16:54:16 2017 MDT
Origin         : sysutils/py3-iocage
Architecture   : FreeBSD:11:*
Prefix         : /usr/local
Categories     : sysutils python
Licenses       : BSD2CLAUSE
Maintainer     : araujo@FreeBSD.org
WWW            : https://github.com/iocage/iocage
Comment        : FreeBSD jail manager written in Python3
Annotations    :
	repo_type      : binary
	repository     : FreeBSD
Flat size      : 682KiB
Description    :
iocage is a jail/container manager amalgamating some of the best
features and technologies the FreeBSD operating system has
to offer. It is geared for ease of use with a simple and easy
to understand command syntax.

WWW: https://github.com/iocage/iocage
sharp@bebop ~ $ iocage list
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/iocage/lib/ioc_json.py", line 251, in json_load
    conf_version = conf["CONFIG_VERSION"]
KeyError: 'CONFIG_VERSION'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/bin/iocage", line 10, in <module>
    sys.exit(cli())
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/iocage/cli/list.py", line 44, in cli
    _list = ioc.IOCage().list(dataset_type, header, _long, _sort)
  File "/usr/local/lib/python3.6/site-packages/iocage/lib/iocage.py", line 68, in __init__
    self.jails, self._paths = self.list("uuid")
  File "/usr/local/lib/python3.6/site-packages/iocage/lib/iocage.py", line 468, in list
    return ioc_list.IOCList(lst_type, header, long, sort).list_datasets()
  File "/usr/local/lib/python3.6/site-packages/iocage/lib/ioc_list.py", line 53, in list_datasets
    conf = iocage.lib.ioc_json.IOCJson(jail).json_load()
  File "/usr/local/lib/python3.6/site-packages/iocage/lib/ioc_json.py", line 256, in json_load
    conf = self.json_check_config(conf, version)
  File "/usr/local/lib/python3.6/site-packages/iocage/lib/ioc_json.py", line 522, in json_check_config
    raise RuntimeError("You need to be root to convert the"
RuntimeError: You need to be root to convert the configurations to the new format!

**Comment by skarekrow** [comment]
Please read the error, run that as `root`

**Comment by akelling** [comment]
Does not matter if I run it as a privileged user or not

sharp@bebop ~ $ su -
Password:
root@bebop:~ # iocage list
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/iocage/lib/ioc_json.py", line 544, in json_check_config
    release = conf["release"]
KeyError: 'release'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/bin/iocage", line 10, in <module>
    sys.exit(cli())
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/iocage/cli/list.py", line 44, in cli
    _list = ioc.IOCage().list(dataset_type, header, _long, _sort)
  File "/usr/local/lib/python3.6/site-packages/iocage/lib/iocage.py", line 68, in __init__
    self.jails, self._paths = self.list("uuid")
  File "/usr/local/lib/python3.6/site-packages/iocage/lib/iocage.py", line 468, in list
    return ioc_list.IOCList(lst_type, header, long, sort).list_datasets()
  File "/usr/local/lib/python3.6/site-packages/iocage/lib/ioc_list.py", line 53, in list_datasets
    conf = iocage.lib.ioc_json.IOCJson(jail).json_load()
  File "/usr/local/lib/python3.6/site-packages/iocage/lib/ioc_json.py", line 256, in json_load
    conf = self.json_check_config(conf, version)
  File "/usr/local/lib/python3.6/site-packages/iocage/lib/ioc_json.py", line 548, in json_check_config
    freebsd_version = f"{iocroot}/releases/{conf['release']}" \
KeyError: 'release'
root@bebop:~ #

**Comment by skarekrow** [comment]
There are a few tickets on that: https://github.com/iocage/iocage/issues?utf8=%E2%9C%93&q=is%3Aissue%20is%3Aclosed%20KeyError%3A%20%27release%27, I haven't been able to reproduce it on the latest code. 

Please update to master, or sit tight for a new release soon (hopefully over the weekend).

**Comment by akelling** [comment]
Thanks for the quick response!!! 

I have two servers that are doing this. iocage worked on a fresh install of 11.0 but when I upgraded to 11.1, it shit the bed. Not sure if the others had the same issue after the upgrade

I would rather work from pkg then doing a git clone of your repo for ease of managing my servers. I look forward the new release in hope of it fixing my issue

**Comment by skarekrow** [comment]
@akelling I totally understand, have you checked for an upgrade to `iocage`? It should exist in ports: http://www.freshports.org/sysutils/py3-iocage/, which should have the aforementioned differences.

**Comment by akelling** [comment]
@skarekrow Yup I checked before creating the ticket.

root@bebop:~ # pkg update && pkg upgrade
Updating FreeBSD repository catalogue...
FreeBSD repository is up to date.
All repositories are up to date.
Updating FreeBSD repository catalogue...
FreeBSD repository is up to date.
All repositories are up to date.
Checking for upgrades (1 candidates): 100%
Processing candidates (1 candidates): 100%
Checking integrity... done (0 conflicting)
Your packages are up to date.

root@bebop:/usr/ports # make search name=iocage
Port:	py36-iocage-0.9.9.1_1

root@bebop:/usr/ports # pkg search py36-iocage
py36-iocage-0.9.8.1            FreeBSD jail manager written in Python3

**Comment by skarekrow** [comment]
Interesting, you must be using `quarterly` in `/etc/pkg/FreeBSD.conf` instead of `latest`.
```
╰─ pkg search py36-iocage
py36-iocage-0.9.9.1_1          FreeBSD jail manager written in Python3
```

**Comment by akelling** [comment]
You are correct! I did not know there was a other tree I could follow for pkg. I will make the change to latest and report back


root@bebop:/usr/ports # cat /etc/pkg/FreeBSD.conf
# $FreeBSD: releng/11.1/etc/pkg/FreeBSD.conf 320745 2017-07-06 17:22:33Z gjb $
#
# To disable this repository, instead of modifying or removing this file,
# create a /usr/local/etc/pkg/repos/FreeBSD.conf file:
#
#   mkdir -p /usr/local/etc/pkg/repos
#   echo "FreeBSD: { enabled: no }" > /usr/local/etc/pkg/repos/FreeBSD.conf
#

FreeBSD: {
  url: "pkg+http://pkg.FreeBSD.org/${ABI}/quarterly",
  mirror_type: "srv",
  signature_type: "fingerprints",
  fingerprints: "/usr/share/keys/pkg",
  enabled: yes
}
root@bebop:/usr/ports #

**Comment by akelling** [comment]
Getting somewhere when I switched to the latest branch of pkg!!!!

root@bebop:~ # pkg search iocage
py36-iocage-0.9.9.1_1          FreeBSD jail manager written in Python3
root@bebop:~ # pkg info py36-iocage
py36-iocage-0.9.9.1_1
Name           : py36-iocage
Version        : 0.9.9.1_1
Installed on   : Thu Aug 24 16:08:30 2017 MDT
Origin         : sysutils/py3-iocage
Architecture   : FreeBSD:11:*
Prefix         : /usr/local
Categories     : sysutils python
Licenses       : BSD2CLAUSE
Maintainer     : araujo@FreeBSD.org
WWW            : https://github.com/iocage/iocage
Comment        : FreeBSD jail manager written in Python3
Annotations    :
	repo_type      : binary
	repository     : FreeBSD
Flat size      : 769KiB
Description    :
iocage is a jail/container manager amalgamating some of the best
features and technologies the FreeBSD operating system has
to offer. It is geared for ease of use with a simple and easy
to understand command syntax.

WWW: https://github.com/iocage/iocage
root@bebop:~ # iocage list
****************root@bebop:~ # pkg search iocage
py36-iocage-0.9.9.1_1          FreeBSD jail manager written in Python3
root@bebop:~ # pkg info py36-iocage
py36-iocage-0.9.9.1_1
Name           : py36-iocage
Version        : 0.9.9.1_1
Installed on   : Thu Aug 24 16:08:30 2017 MDT
Origin         : sysutils/py3-iocage
Architecture   : FreeBSD:11:*
Prefix         : /usr/local
Categories     : sysutils python
Licenses       : BSD2CLAUSE
Maintainer     : araujo@FreeBSD.org
WWW            : https://github.com/iocage/iocage
Comment        : FreeBSD jail manager written in Python3
Annotations    :
	repo_type      : binary
	repository     : FreeBSD
Flat size      : 769KiB
Description    :
iocage is a jail/container manager amalgamating some of the best
features and technologies the FreeBSD operating system has
to offer. It is geared for ease of use with a simple and easy
to understand command syntax.

WWW: https://github.com/iocage/iocage
root@bebop:~ # iocage list
********************************************************************************
fdescfs(5) is not mounted, performance  may suffer. Please run:
mount -t fdescfs fdesc /dev/fd
You can also permanently mount it in /etc/fstab with the following entry:
fdesc /dev/fd  fdescfs  rw  0  0
********************************************************************************

c9e11dd2-1c6a-45ec-8793-1d38272314e3 has a corrupt configuration,please destroy the jail.
****************************************************************
fdescfs(5) is not mounted, performance  may suffer. Please run:
mount -t fdescfs fdesc /dev/fd
You can also permanently mount it in /etc/fstab with the following entry:
fdesc /dev/fd  fdescfs  rw  0  0
********************************************************************************

c9e11dd2-1c6a-45ec-8793-1d38272314e3 has a corrupt configuration,please destroy the jail.

**Comment by akelling** [comment]
The config.json file is completely wiped. I think I can restore it by modifying the another jails config file
