### ISSUE TITLE
Error reading MAC address property when starting jails

### ISSUE THREAD

**Issue by vbachvarov** [iocage/iocage#349]
Dear developers,
I have found a bug in iocage when using network interfaces with names different from "vnet0, ..."
For example you can use "abc" as network interface name. When starting the jails iocage shows error messages (see below).
I found the bug in the "ioc-network" script, function "__validate_mac". In several places the function "__get_jail_prop" is called with property "${nic}_mac", however - this works only when the "nic" has a standard name of vnet0, ... In my case the name is different and this leads to reading a non-supported property which returns an error message instead of MAC address.

iocage version: iocage 1.7.4 (2016/02/17)

Reproducing (with VNET kernel):
  iocage create tag=myjail
  iocage set interfaces=abc:bridge0 myjail
  iocage start

iocage output:
* Starting 0869c23b-f38e-11e5-b5c6-cbbd200c3425 (2016-03-26@21:05:05)
  + Started                  OK
  + Configuring VNETifconfig: interface bridge0 does not exist
[: ERROR:: unexpected operator
ifconfig: can't set link-level netmask or broadcast
[: ERROR:: unexpected operator
ifconfig: can't set link-level netmask or broadcast
ifconfig: interface bridge0 does not exist
         OK
  + Starting services        OK

Expected: No error should be shown. The MAC address should be read from the correct property.

Best Regards,
Vasil

**Comment by skarekrow** [comment]
Please read the error message, this has nothing to do with MAC addresses, your interface does not exist.

**Comment by vbachvarov** [comment]
Hi, skarekrow,
Please take a more detailed look at the source, I have described exactly where the error is. Indeed in the error message I have posted the interface does not exist, however - I was too lazy to create the bridge (this is a second thing which is irrelevant to the error I described).
Independently the MAC setting bug *is* there, just try what I have described and you will be able to reproduce it.
Thanks and Best Regards,
Vasil
