### ISSUE TITLE
Upgrade Guide

### ISSUE THREAD

**Issue by zachfi** [iocage/iocage#350]
Good day,

I'd like to upgrade a handful of jails that were running on the old shell version of iocage.  I'm still using this command, as the package is still installed, but I would like to get closer to mainline iocage now that the python version has taken over.

What is my upgrade path?  May I request a brief procedure about what I need to do in order not to loose my important jails please?

Cheers.

**Comment by skarekrow** [comment]
There isn't an upgrade guide as it's automatic upon any command with iocage as root. 

- Snapshot and backup
- Install new python iocage
- iocage list as root

 you will migrate automatically :)

**Comment by zachfi** [comment]
Thank you.

**Comment by skarekrow** [comment]
If you want to add a more detailed one to the Wiki and PR it to the README, I wouldn't say no :D
