### ISSUE TITLE
Support for FreeBSD 10.3-RELEASE

### ISSUE THREAD

**Issue by WillGreen** [iocage/iocage#351]
Hello,

Apologies if I'm jumping the gun here, but I've been testing FreeBSD 10.3-RELEASE and note that iocage doesn't yet support this. I am concerned this won't be implemented in time for the quarterly package freeze and therefore iocage won't be usable on FreeBSD 10.3 until July.

TIA

Version:
iocage 1.7.4 (2016/02/17) on FreeBSD 10.3-RELEASE

Commands and output:

```
iocage fetch
Supported releases are:
   10.2-RELEASE
    9.3-RELEASE
Please select a release [-]: 
```

Expected:
10.3-RELEASE should be an option.

Looking at https://github.com/iocage/iocage/commits/develop this hasn't been committed yet.

**Comment by urosgruber** [comment]
It's supported. Maybe selected mirror doesn't have 10.3 yet. At least one closest to me doesn't. But after yesterday it's there. Maybe you need the latest devel version from ports?

```
Supported releases are:
  11.0-CURRENT
  10.3-PRERELEASE
  10.2-RELEASE
  9.3-RELEASE
Please select a release [10.3-RELEASE]:
```

**Comment by WillGreen** [comment]
Since the announcement of 10.3-RELEASE I see there's a new announcement on the iocage GitHub:

```
**No longer supported. iocage is being rewritten in a different language. To fetch 10.3-RELEASE or above, supply the release to iocage:
iocage fetch release=10.3-RELEASE
```

However, there's still an error at the end of the fetch: `Failed to build new tree.` Despite this error I'm still able to create jails, but it would be good to know what this failure actually means. I know the message states there's no support, but I hope this is a straightforward question to answer. 

I have included the full output below.

```
# freebsd-version
10.3-RELEASE

# iocage version
iocage 1.7.4 (2016/02/17)

# iocage fetch release=10.3-RELEASE
Extracting: base.txz
Extracting: doc.txz
Extracting: lib32.txz
Extracting: src.txz
* Updating base jail..
Looking up update.FreeBSD.org mirrors... 4 mirrors found.
Fetching metadata signature for 10.3-RELEASE from update4.freebsd.org... done.
Fetching metadata index... done.
Inspecting system... done.
Preparing to download files... done.

No updates needed to update system to 10.3-RELEASE-p0.
No updates are available to install.
Run '/usr/sbin/freebsd-update fetch' first.

Creating basejail ZFS datasets... please wait.
Failed to build new tree.
```

**Comment by skarekrow** [comment]
That's the error output from etcupdate. It's not very helpful, but I have not seen that error on my end.
