### ISSUE TITLE
Migration of tag-based jails to name-based fails, even with no running jails

### ISSUE THREAD

**Issue by asomers** [iocage/iocage#351]
Make sure to follow and check these boxes before submitting an issue! Thank you.

- [x] Supply `iocage --version`
- [x] Supply the commands used, along with any steps to recreate it.
- [x] Provide the output from the command you issued.
- [x] Supply what you expected the result or output to be
- [ ] Checked that the problem has not already been fixed on `master` if using
 a stable release.

I have old tag-based jails.  Since upgrading to iocage 0.9.9.1 I can't start them by name; I must use their UUID.  And the state doesn't display correctly in the output of `iocage list`.  The `iocage migrate` command does nothing.  I don't have any jails running, as shown by `jls`, so this is not a duplicate of #307.

```
> iocage --version
0.9.9.1 08/01/2017
```

Actual commands
```
> iocage list
+-----+----------+-------+--------------+--------------+
| JID |   NAME   | STATE |   RELEASE    |     IP4      |                            
+=====+==========+=======+==============+==============+                            
| -   | bb3a6c15 | down  | 11.1-RELEASE | -            |                            
+-----+----------+-------+--------------+--------------+                            
| -   | buildbot | down  | 11.1-RELEASE | 192.168.0.24 |                            
+-----+----------+-------+--------------+--------------+                            
| -   | cargodev | down  | 11.0-RELEASE | 192.168.0.20 |                            
+-----+----------+-------+--------------+--------------+                            
| -   | fbsd74   | down  | 7.4-RELEASE  | 192.168.0.22 |                            
+-----+----------+-------+--------------+--------------+                            
| -   | rustdev  | down  | 11.0-RELEASE | 192.168.0.18 |                            
+-----+----------+-------+--------------+--------------+                            
| -   | rustup   | down  | 11.0-RELEASE | 192.168.0.23 |                            
+-----+----------+-------+--------------+--------------+
> sudo iocage start rustup
rustup not found!
> sudo iocage migrate
Password:

This will migrate ALL iocage-legacy develop basejails to clonejails, it can take a long time!                                                                           
Please make sure you are not running this on iocage-legacy 1.7.6 basejails.         

Are you sure? [y/N]: y
> sudo iocage start rustup
rustup not found!
```
Expected output: The rustup jail should've started.

**Comment by Quux-NL** [comment]
Had this problem as well. Migration performed by hand eventually fixed this...

Have a look at this thread: https://github.com/iocage/iocage/issues/307

**Comment by ghost** [comment]
Same issue here. `iocage` is broken with no obvious way to fix.

@Quux-NL thanks for the link, I will take a look.

---

Most of my jails seem to have been manually migrated fine. One of them is being problematic (I can't enable the `jailed` option in ZFS for the `root` dataset. I see a message that says `dataset is exported to a local zone` when trying to `zfs mount -a`) I am trying to export the jail, destroy it and then try reimporting.

**Comment by skarekrow** [comment]
@asomers Where you coming from iocage-legacy develop? Otherwise you shouldn't have ran that command.

Can you supply me with:
```
mount
zfs list -r POOL/iocage
jls (not truncated please)
cat /PATH/TO/JAIL/config.json
iocage list -l
```

**Comment by asomers** [comment]
@skarekrow here you go
[351.txt](https://github.com/iocage/iocage/files/1271815/351.txt)

**Comment by Quux-NL** [comment]
Let me just provide an overview of the steps I took to perform this upgrade (from memory):

(in the following steps **UUID** stands for the actual UUID and **NAME** stands for the name of the jail.

1. Stop all jails.
2. Ensure that all jails are actually dead by looking at the output of: `jls -j ioc-UUID` for each jail (**UUID**) you have to convert; this should not show any jails _dying_ anymore (I had to wait several minutes for this to complete, especially with one log-jail where I had to ensure that no other systems where actually logging to this jail anymore).

3. If necessary unmount special fs and ensure that `jailed=off` by issuing the following commands:
`umount -v -t fdescfs /iocage/jails/UUID/root/dev/fd`
`umount -v -t devfs /iocage/jails/UUID/root/dev`
`zfs set jailed=off zroot/iocage/jails/UUID/root/data`

4. Perform the actual rename:
`zfs rename zroot/iocage/jails/UUID zroot/iocage/jails/NAME`

5. And finally edit the `config.json` file in `/iocage/jails/NAME/root/data` so that the **UUID** mentioned there is replaced by the **NAME**.

Then you can restart the jail again and repeat this process for all other jails.

Enjoy!

**Comment by Quux-NL** [comment]
Hi all,

Have a look at https://github.com/iocage/iocage/issues/351 <https://github.com/iocage/iocage/issues/351>. I have included a comment from memory of the steps I took to resolve the issue. Hope this helps.

Ciao,
Hans.

**Comment by ghost** [comment]
My jails are up and running now. I did the `zfs set jailed=off ...`, `zfs rename ...` and `zfs set jailed=on ...` steps but that didn't work for most of my jails.

I ended up exporting and importing most of my jails and now they are all running.

There was one jail that refused to start with an `'ioc-m' jail not found` error or something similar, that jail didn't have much running it it so I just re-created it.

**Comment by skarekrow** [comment]
@asomers Yeah I believe things got into a weird state for you. This shouldn't happen anymore on master afaik, but a reproduction case from you so I can test would be lovely. In the meantime, follow @Quux-NL (excellent) guide to get up and running.

From what I can tell you did this:
- Used iocage-legacy (master not develop)
- Created basejails
- Tried to use 0.9.9.1

Correct?

**Comment by asomers** [comment]
@skarekrow close, but you're missing one step:  Here's what I did:

1. Using iocage-legacy I created some basejails
2. I upgraded to py-iocage and migrated my legacy jails to the new format, with config.json files
3. Upgraded to py-iocage 0.9.9.1 and I can no longer use my jails by name, nor display their UUIDs.

Do you want me to try to reproduce this in a VM?

**Comment by skarekrow** [comment]
@asomers if you want :)

I'll be trying to reproduce it next week from HEAD. Sorry you ran into this :(

**Comment by skarekrow** [comment]
@asomers Hmm this may need you to try to reproduce. I cannot:
```
╰─ iocage_legacy create -b tag="test_base" release="11.0-RELEASE"
╰─ iocage list
Creating zroot/iocage/images
Creating zroot/iocage/log
Creating zroot/iocage/templates
********************************************************************************
Jail: 8e8dc097-9e5c-11e7-b216-17f41be987f6 was renamed to test_base
********************************************************************************

Please issue your command again.
╰─ iocage list
+-----+-----------+-------+--------------+-----+
| JID |   NAME    | STATE |   RELEASE    | IP4 |
+=====+===========+=======+==============+=====+
| -   | test_base | down  | 11.0-RELEASE | -   |
+-----+-----------+-------+--------------+-----+
╰─ iocage get host_hostuuid test_base
test_base
```

**Comment by asomers** [comment]
I originally created the jail with sh-based iocage, before it was renamed iocage-legacy.  I installed py-iocage before UUIDs got deprecated, so I migrated it to a config.json-based jail instead of a ZFS property-based jail.  Then, of course, I tried but failed to migrate to the name-base jails.  So I had two migration steps in my history.  I tried to reproduce it today.  I failed, but what happened instead was worse:
```
# First install iocage 1.7.6
$ iocage fetch release=11.0-RELEASE
$ iocage create -b tag="test_base" release="11.0-RELEASE"
# Then upgrade to py-iocage 0.9
$ iocage activate tank # Not sure why I have to do this again
# iocage list
╒═════╤══════════╤═══════╤═══════════╤═════╕
│ JID │ UUID     │ STATE │ TAG       │ IP4 │
╞═════╪══════════╪═══════╪═══════════╪═════╡
| -   | dcd75f4e | down  | test_base | -   |
+-----+----------+-------+-----------+-----+
# Then upgrade to py36-iocage 0.9.9.1
$ iocage list
********************************************************************************
fdescfs(5) is not mounted, performance  may suffer. Please run:
mount -t fdescfs fdesc /dev/fd
You can also permanently mount it in /etc/fstab with the following entry:
fdesc /dev/fd  fdescfs  rw  0  0
********************************************************************************
                                                                                 
dcd75f4e-a15c-11e7-9fe0-589cfc026a46 has a corrupt configuration,please destroy the jail.
```

**Comment by skarekrow** [comment]
Err that damn bug keeps rearing it's head, and I can't reliably produce it. What does that jails `config.json` look like @asomers? Normally that error happens when you're missing the `release` key in that file, which should never be the case.

**Comment by asomers** [comment]
https://gist.github.com/asomers/c01ad92ccebd93c0da28d825bf9ddeed

**Comment by skarekrow** [comment]
Hmm that's so odd. Just to confirm, that release dataset is mounted where the jail is? IE: `/iocage/releases/11.0-RELEASE`? 

Oh and to answer your activation question, we use a zfs prop instead of a comment like legacy did, this is to ensure you mean to actively use the iocage. Just a small hurdle to protect users.

**Comment by skarekrow** [comment]
@asomers Interestingly I can't reproduce that issue either, even using your config.json everything goes smoothly. I'd suggest making sure you aren't in the jails directories when doing any of these operations.

I believe I fixed the migration issue, I beat it up pretty hard and haven't been able to get it to fail, it doesn't rely on rename anymore. So it's better in this regard. Please let me know if you're able to trigger these bugs again 👍
