### ISSUE TITLE
iocage (0.9.9.2 ALPHA)  -  crash on jail import due to memory exhaustion

### ISSUE THREAD

**Issue by ghost** [iocage/iocage#356]
Make sure to follow and check these boxes before submitting an issue! Thank you.

- [x ] Supply `iocage --version`
- [x] Supply the commands used, along with any steps to recreate it.
- [x ] Provide the output from the command you issued.
- [x] Supply what you expected the result or output to be
- [x ] Checked that the problem has not already been fixed on `master` if using
 a stable release.

Attempting to import  an exported jail completely exhausts the VPS of memory and eventually crashes before completing the import. System stats around the moment of the import crash:

CPU:  0.0% user,  0.0% nice,  7.3% system,  0.2% interrupt, 92.5% idle                 
Mem: 3430M Active, 20K Inact, 483M Wired, 17M Free
ARC: 123M Total, 31M MFU, 71M MRU, 32K Anon, 1602K Header, 20M Other
     59M Compressed, 96M Uncompressed, 1.63:1 Ratio
Swap: 2048M Total, 2048M Used, K Free, 100% Inuse

29104 root             1  20    0  8261M     0K pfault  0   0:37   0.00% <python3.6>

**Comment by skarekrow** [comment]
Ouch that's awful. Thanks for filing this!

**Comment by ghost** [comment]
On the bright the kernel oom killer works flawlessly :p.... Took a quick look and it seems to me the problem could be with the communicate() call in the subprocess module for that function. For arbitrary large data it might not be suitable.

**Comment by skarekrow** [comment]
Yeah that's my thought as well. It's time I revisited this function anyways :)

**Comment by skarekrow** [comment]
@siladi Ok should be solved 👍 , please test and let me know :)

**Comment by ghost** [comment]
Looks good. Thanks.
