### ISSUE TITLE
Upgrade path for existing plugin-type jails

### ISSUE THREAD

**Issue by atl** [iocage/iocage#357]
Version 0.9.8.1 05/23/2017

Commands missing from current version, documentation, and on a quick perusal of the source tree.

I have been successfully running iocage plugin-style jails on FreeNAS-11.0-U2. I would like to update to the latest changes for the plugin, but the following fails:

    # iocage update uuid
    plugin is not a supported jail type.

duplicate of issue first filed here: https://github.com/freenas/iocage-ix-plugins/issues/3

**Comment by atl** [comment]
# iocage -v
    Version 0.9.10 RC


     # iocage update nextcloud
    plugin is not a supported jail type.

FYI, the 0.9.9.2 milestone appears not to be valid.

**Comment by skarekrow** [comment]
Bah, totally right. I forgot about this.

**Comment by schmitmd** [comment]
It doesn't look like this has gotten a look in quite a while.  I'm seeing the same behavior on FreeBSD 11.2 RELEASE/12.0-RELEASE.  Any updates or is this just a FreeNAS gui thing?
