### ISSUE TITLE
"iocage set quota=1gb tag" does nothing

### ISSUE THREAD

**Issue by oliverangelil** [iocage/iocage#36]
- Version 0.9.4 
- Command used: iocage create tag=jail1 ip4_addr="em0|10.0.1.11" --release=11.0-RELEASE  quota=1gb
- Expected result: "zfs list" should show the avail disk space as 1gb

**Comment by skarekrow** [comment]
Currently ZFS properties are not passed through, it's on my TODO :)

Next time please fill out the checkboxes.

Thanks 👍

**Comment by oliverangelil** [comment]
I edited the comment. Thanks. :)

**Comment by oliverangelil** [comment]
The jail also does not boot automatically after a system reboot when the "boot" property is on. I don't know if this has anything to do with zfs.

**Comment by skarekrow** [comment]
Now that one is an easy answer :) You have too old of a version, that feature was added in 0.9.5. So you just have to update your pkg, or install from source and copy the init script to `/usr/local/etc/rc.d/iocage` :)

EDIT: After posting this @molofishy I noticed the port does not bundle the init script. That's an easy fix:

1. `git clone https://github.com/iocage/iocage`
2. `sudo cp iocage/rc.d/iocage /usr/local/etc/iocage`

Make sure you update your pkg first, as the init script will not work without 0.9.5.

**Comment by oliverangelil** [comment]
Thanks. Fyi, I ended up with 0.9.4 since more recent versions are not part of the pkg library. "pkg search iocage" shows py27-iocage-0.9.4 (and I assume using the iocage written is python is the way to go).

**Comment by skarekrow** [comment]
It is indeed the way to go :) 

Interesting freshports shows that 0.9.5 is available. Perhaps you have your `/etc/pkg/FreeBSD.conf` set to quarterly? I haven't confirmed yet on my boxes as I'm on mobile. 

EDIT: My boxes do not show it either. The new ports must not have been built yet :)

**Comment by skarekrow** [comment]
@molofishy Alright this is all in :) Please test and let me know 👍
