### ISSUE TITLE
Update documentation about migrating from ezjail

### ISSUE THREAD

**Issue by mvanbaak** [iocage/iocage#362]
The current document about migrating from ezjail is based on the legacy iocage.

If there's any forum thread or personal gist about it, I can use that to test and document with my setup here.
But for me it's a bit unclear now how to do it and for this I'm still on ezjail on a couple of hosts.

**Comment by skarekrow** [comment]
This was supplied by a user, I swear it was @fliiiix but I may be misremembering. I don't personally use ezjail, but would love to see somebody update the wiki!

**Comment by fliiiix** [comment]
It's true that I migrated my jails form ezjails. But I just reinstalled everything in new iocage jails. Sorry that I can not help more.

**Comment by mvanbaak** [comment]
This has been resolved with the merge of PR #489 

Thanks a lot! I tried it and it worked perfectly.
