### ISSUE TITLE
Removing config.json should trigger a missing/corrupt configuration notification instead of a stacktrace

### ISSUE THREAD

**Issue by kitten77** [iocage/iocage#373]
Make sure to follow and check these boxes before submitting an issue! Thank you.

- [x] Supply `iocage --version`
Version 0.9.9.2 09/30/2017

- [x] Supply the commands used, along with any steps to recreate it.
iocage destroy name
- [x] Provide the output from the command you issued.
root@gaia:/home/muad # iocage destroy www_test

This will destroy jail www_test

Are you sure? [y/N]: y
Traceback (most recent call last):
  File "/usr/local/bin/iocage", line 10, in <module>
    sys.exit(cli())
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/iocage/cli/destroy.py", line 125, in cli
    recursive=recursive)
  File "/usr/local/lib/python3.6/site-packages/iocage/cli/destroy.py", line 47, in child_test
    children = zfs.get_dataset_by_path(path).snapshots_recursive
  File "libzfs.pyx", line 606, in libzfs.ZFS.get_dataset_by_path (libzfs.c:19562)
NameError: name 'zfs' is not defined

- [ ] Supply what you expected the result or output to be

- [ ] Checked that the problem has not already been fixed on `master` if using
 a stable release.

**Comment by skarekrow** [comment]
Which libzfs are you using?

**Comment by kitten77** [comment]
libzfs==1.0
from pip freeze

I also get errors now when i am trying too use iocage list

**Comment by kitten77** [comment]
root@gaia:/home/muad # iocage list
Traceback (most recent call last):
  File "/usr/home/muad/python/webhotell/webhotell_env/bin/iocage", line 10, in <module>
    sys.exit(cli())
  File "/usr/home/muad/python/webhotell/webhotell_env/lib/python3.6/site-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/usr/home/muad/python/webhotell/webhotell_env/lib/python3.6/site-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/usr/home/muad/python/webhotell/webhotell_env/lib/python3.6/site-packages/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/home/muad/python/webhotell/webhotell_env/lib/python3.6/site-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/home/muad/python/webhotell/webhotell_env/lib/python3.6/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/usr/home/muad/python/webhotell/webhotell_env/lib/python3.6/site-packages/iocage/cli/list.py", line 74, in cli
    plugin=plugins, quick=quick)
  File "/usr/home/muad/python/webhotell/webhotell_env/lib/python3.6/site-packages/iocage/lib/iocage.py", line 1141, in list
    exit_on_error=self.exit_on_error).list_datasets()
  File "/usr/home/muad/python/webhotell/webhotell_env/lib/python3.6/site-packages/iocage/lib/ioc_list.py", line 76, in list_datasets
    _all = self.list_all(ds)
  File "/usr/home/muad/python/webhotell/webhotell_env/lib/python3.6/site-packages/iocage/lib/ioc_list.py", line 153, in list_all
    conf = iocage.lib.ioc_json.IOCJson(mountpoint).json_load()
  File "/usr/home/muad/python/webhotell/webhotell_env/lib/python3.6/site-packages/iocage/lib/ioc_json.py", line 231, in json_load
    self.json_convert_from_zfs(full_uuid)
  File "/usr/home/muad/python/webhotell/webhotell_env/lib/python3.6/site-packages/iocage/lib/ioc_json.py", line 105, in json_convert_from_zfs
    props = self.zfs.get_dataset(dataset).properties
  File "libzfs.pyx", line 562, in libzfs.ZFS.get_dataset (libzfs.c:18705)
libzfs.ZFSException: Dataset gaia/iocage/jails/- not found

 root@gaia:/home/muad # zfs list
gaia/iocage/jails                                            2.11T   535G   120K  /iocage/jails

**Comment by skarekrow** [comment]
How did you install libzfs though, which repo?

Can you give me a complete list of steps you used? Specifically `libzfs.ZFSException: Dataset gaia/iocage/jails/- not found` makes me think you came from a legacy setup or something other then a clean one.

As is, I can't replicate :(
```
╰─ iocage --version
Version	0.9.9.2 09/30/2017
╰─ iocage create -n foo -r 11.1-RELEASE
foo successfully created!
╰─ iocage destroy foo

This will destroy jail foo

Are you sure? [y/N]: y
Destroying foo
```

**Comment by kitten77** [comment]
root@gaia:/home/muad/iocage # make install .
echo -e "import os\ntry:\n  if not os.listdir('/usr/src'): exit('/usr/src must be populated!')\nexcept FileNotFoundError:\n  exit('/usr/src must be populated!')" | python3.6
test -d .git && git pull || true
Already up-to-date.
python3.6 -m ensurepip
Requirement already satisfied: setuptools in /usr/local/lib/python3.6/site-packages
Requirement already satisfied: pip in /usr/local/lib/python3.6/site-packages
pip3.6 install -U Cython
Requirement already up-to-date: Cython in /usr/local/lib/python3.6/site-packages
cd py-libzfs && python3.6 setup.py build && python3.6 setup.py install
running build
running build_py
running build_ext
skipping 'libzfs.c' Cython extension (up-to-date)
running install
running build
running build_py
running build_ext
skipping 'libzfs.c' Cython extension (up-to-date)
running install_lib
running install_egg_info
Removing /usr/local/lib/python3.6/site-packages/libzfs-1.0-py3.6.egg-info
Writing /usr/local/lib/python3.6/site-packages/libzfs-1.0-py3.6.egg-info
pkg install -q -y libgit2
The most recent version of packages are already installed
pip3.6 install -U .
Processing /usr/home/muad/iocage
Requirement already up-to-date: click==6.7 in /usr/local/lib/python3.6/site-packages (from iocage==0.9.9.2)
Requirement already up-to-date: texttable==0.9.0 in /usr/local/lib/python3.6/site-packages (from iocage==0.9.9.2)
Requirement already up-to-date: requests==2.17.3 in /usr/local/lib/python3.6/site-packages (from iocage==0.9.9.2)
Requirement already up-to-date: tqdm==4.14.0 in /usr/local/lib/python3.6/site-packages (from iocage==0.9.9.2)
Requirement already up-to-date: coloredlogs==7.0 in /usr/local/lib/python3.6/site-packages (from iocage==0.9.9.2)
Requirement already up-to-date: verboselogs==1.6 in /usr/local/lib/python3.6/site-packages (from iocage==0.9.9.2)
Requirement already up-to-date: pygit2==0.25.1 in /usr/local/lib/python3.6/site-packages (from iocage==0.9.9.2)
Requirement already up-to-date: cffi==1.9.1 in /usr/local/lib/python3.6/site-packages (from iocage==0.9.9.2)
Requirement already up-to-date: libzfs in /usr/local/lib/python3.6/site-packages (from iocage==0.9.9.2)
Requirement already up-to-date: idna<2.6,>=2.5 in /usr/local/lib/python3.6/site-packages (from requests==2.17.3->iocage==0.9.9.2)
Requirement already up-to-date: urllib3<1.22,>=1.21.1 in /usr/local/lib/python3.6/site-packages (from requests==2.17.3->iocage==0.9.9.2)
Requirement already up-to-date: chardet<3.1.0,>=3.0.2 in /usr/local/lib/python3.6/site-packages (from requests==2.17.3->iocage==0.9.9.2)
Requirement already up-to-date: certifi>=2017.4.17 in /usr/local/lib/python3.6/site-packages (from requests==2.17.3->iocage==0.9.9.2)
Requirement already up-to-date: humanfriendly>=3.2 in /usr/local/lib/python3.6/site-packages (from coloredlogs==7.0->iocage==0.9.9.2)
Requirement already up-to-date: six in /usr/local/lib/python3.6/site-packages (from pygit2==0.25.1->iocage==0.9.9.2)
Requirement already up-to-date: pycparser in /usr/local/lib/python3.6/site-packages (from cffi==1.9.1->iocage==0.9.9.2)
Installing collected packages: iocage
  Found existing installation: iocage 0.9.9.2
    Uninstalling iocage-0.9.9.2:
      Successfully uninstalled iocage-0.9.9.2
  Running setup.py install for iocage ... done
Successfully installed iocage-0.9.9.2
`.' is up to date.
root@gaia:/home/muad/iocage # 

git pull . && make install . from the iocage directory

Was working fine until i updated

**Comment by kitten77** [comment]
root@gaia:/home/muad/iocage # make install 
echo -e "import os\ntry:\n  if not os.listdir('/usr/src'): exit('/usr/src must be populated!')\nexcept FileNotFoundError:\n  exit('/usr/src must be populated!')" | python3.6
test -d .git && git pull || true
Already up-to-date.
python3.6 -m ensurepip
Requirement already satisfied: setuptools in /usr/local/lib/python3.6/site-packages
Requirement already satisfied: pip in /usr/local/lib/python3.6/site-packages
pip3.6 install -U Cython
Requirement already up-to-date: Cython in /usr/local/lib/python3.6/site-packages
cd py-libzfs && python3.6 setup.py build && python3.6 setup.py install
running build
running build_py
running build_ext
cythoning libzfs.pyx to libzfs.c
building 'libzfs' extension
creating build
creating build/temp.freebsd-11.0-RELEASE-p9-amd64-3.6
cc -Wno-unused-result -Wsign-compare -Wunreachable-code -DNDEBUG -O2 -pipe -fstack-protector -fno-strict-aliasing -fPIC -I/usr/src/cddl/lib/libumem -I/usr/src/sys/cddl/compat/opensolaris/ -I/usr/src/sys/cddl/compat/opensolaris -I/usr/src/cddl/compat/opensolaris/include -I/usr/src/cddl/compat/opensolaris/lib/libumem -I/usr/src/cddl/contrib/opensolaris/lib/libzpool/common -I/usr/src/sys/cddl/contrib/opensolaris/common/zfs -I/usr/src/sys/cddl/contrib/opensolaris/uts/common/fs/zfs -I/usr/src/sys/cddl/contrib/opensolaris/uts/common/sys -I/usr/src/cddl/contrib/opensolaris/head -I/usr/src/sys/cddl/contrib/opensolaris/uts/common -I/usr/src/cddl/contrib/opensolaris/lib/libnvpair -I/usr/src/cddl/contrib/opensolaris/lib/libuutil/common -I/usr/src/cddl/contrib/opensolaris/lib/libzfs/common -I/usr/src/cddl/contrib/opensolaris/lib/libzfs_core/common -I/usr/local/include/python3.6m -c libzfs.c -o build/temp.freebsd-11.0-RELEASE-p9-amd64-3.6/libzfs.o -DNEED_SOLARIS_BOOLEAN -D_XPG6 -g -O0
libzfs.c:15218:13: warning: code will never be executed [-Wunreachable-code]
  __pyx_r = 0;
            ^
libzfs.c:20150:73: warning: incompatible pointer to integer conversion passing 'PyObject *' (aka 'struct _object *') to parameter of type 'zfs_type_t' [-Wint-conversion]
  __pyx_v_handle = zfs_path_to_zhandle(__pyx_v_self->handle, __pyx_t_1, __pyx_t_2);
                                                                        ^~~~~~~~~
/usr/src/cddl/contrib/opensolaris/lib/libzfs/common/libzfs.h:701:79: note: passing argument to parameter here
extern zfs_handle_t *zfs_path_to_zhandle(libzfs_handle_t *, char *, zfs_type_t);
                                                                              ^
libzfs.c:40272:13: warning: code will never be executed [-Wunreachable-code]
  __pyx_r = 0;
            ^
libzfs.c:54259:74: warning: passing 'const char *' to parameter of type 'char *' discards qualifiers [-Wincompatible-pointer-types-discards-qualifiers]
        __pyx_v_ret = zfs_destroy_snaps(__pyx_v_self->__pyx_base.handle, __pyx_v_c_name, 1);
                                                                         ^~~~~~~~~~~~~~
/usr/src/cddl/contrib/opensolaris/lib/libzfs/common/libzfs.h:564:52: note: passing argument to parameter here
extern int zfs_destroy_snaps(zfs_handle_t *, char *, boolean_t);
                                                   ^
libzfs.c:64273:5: warning: code will never be executed [-Wunreachable-code]
    PyErr_Format(PyExc_ValueError, "Assignment to slice of wrong length, expected %" CYTHON_FORMAT_SSIZE_T "d, got %" CYTHON_FORMAT_SSIZE_T "d", (Py_ssize_t)((ZFS_MAXPROPLEN + 1)), (Py_ssize_t)((ZFS_MAXPROPLEN + 1)));
    ^~~~~~~~~~~~
libzfs.c:64260:5: warning: code will never be executed [-Wunreachable-code]
    PyErr_Format(PyExc_ValueError, "Assignment to slice of wrong length, expected %" CYTHON_FORMAT_SSIZE_T "d, got %" CYTHON_FORMAT_SSIZE_T "d", (Py_ssize_t)((__pyx_e_6libzfs_MAX_DATASET_NAME_LEN + 1)), (Py_ssize_t)((__pyx_e_6libzfs_MAX_DATASET_NAME_LEN + 1)));
    ^~~~~~~~~~~~
libzfs.c:64238:5: warning: code will never be executed [-Wunreachable-code]
    PyErr_Format(PyExc_ValueError, "Assignment to slice of wrong length, expected %" CYTHON_FORMAT_SSIZE_T "d, got %" CYTHON_FORMAT_SSIZE_T "d", (Py_ssize_t)((ZFS_MAXPROPLEN + 1)), (Py_ssize_t)((ZFS_MAXPROPLEN + 1)));
    ^~~~~~~~~~~~
libzfs.c:64823:5: warning: code will never be executed [-Wunreachable-code]
    PyErr_Format(PyExc_ValueError, "Assignment to slice of wrong length, expected %" CYTHON_FORMAT_SSIZE_T "d, got %" CYTHON_FORMAT_SSIZE_T "d", (Py_ssize_t)((ZFS_MAXPROPLEN + 1)), (Py_ssize_t)((ZFS_MAXPROPLEN + 1)));
    ^~~~~~~~~~~~
libzfs.c:64810:5: warning: code will never be executed [-Wunreachable-code]
    PyErr_Format(PyExc_ValueError, "Assignment to slice of wrong length, expected %" CYTHON_FORMAT_SSIZE_T "d, got %" CYTHON_FORMAT_SSIZE_T "d", (Py_ssize_t)((__pyx_e_6libzfs_MAX_DATASET_NAME_LEN + 1)), (Py_ssize_t)((__pyx_e_6libzfs_MAX_DATASET_NAME_LEN + 1)));
    ^~~~~~~~~~~~
libzfs.c:64788:5: warning: code will never be executed [-Wunreachable-code]
    PyErr_Format(PyExc_ValueError, "Assignment to slice of wrong length, expected %" CYTHON_FORMAT_SSIZE_T "d, got %" CYTHON_FORMAT_SSIZE_T "d", (Py_ssize_t)((ZFS_MAXPROPLEN + 1)), (Py_ssize_t)((ZFS_MAXPROPLEN + 1)));
    ^~~~~~~~~~~~
10 warnings generated.
creating build/lib.freebsd-11.0-RELEASE-p9-amd64-3.6
cc -shared -lpthread -L/usr/local/lib -fstack-protector build/temp.freebsd-11.0-RELEASE-p9-amd64-3.6/libzfs.o -L/usr/local/lib -lnvpair -lzfs -lzfs_core -luutil -lgeom -lpython3.6m -o build/lib.freebsd-11.0-RELEASE-p9-amd64-3.6/libzfs.so -g
running install
running build
running build_py
copying converter.html -> build/lib.freebsd-11.0-RELEASE-p9-amd64-3.6
copying nvpair.html -> build/lib.freebsd-11.0-RELEASE-p9-amd64-3.6
copying libzfs.html -> build/lib.freebsd-11.0-RELEASE-p9-amd64-3.6
copying libzfs.c -> build/lib.freebsd-11.0-RELEASE-p9-amd64-3.6
running build_ext
skipping 'libzfs.c' Cython extension (up-to-date)
running install_lib
copying build/lib.freebsd-11.0-RELEASE-p9-amd64-3.6/libzfs.so -> /usr/local/lib/python3.6/site-packages
copying build/lib.freebsd-11.0-RELEASE-p9-amd64-3.6/converter.html -> /usr/local/lib/python3.6/site-packages
copying build/lib.freebsd-11.0-RELEASE-p9-amd64-3.6/libzfs.c -> /usr/local/lib/python3.6/site-packages
copying build/lib.freebsd-11.0-RELEASE-p9-amd64-3.6/libzfs.html -> /usr/local/lib/python3.6/site-packages
copying build/lib.freebsd-11.0-RELEASE-p9-amd64-3.6/nvpair.html -> /usr/local/lib/python3.6/site-packages
running install_egg_info
Removing /usr/local/lib/python3.6/site-packages/libzfs-1.0-py3.6.egg-info
Writing /usr/local/lib/python3.6/site-packages/libzfs-1.0-py3.6.egg-info
pkg install -q -y libgit2
The most recent version of packages are already installed
pip3.6 install -U .
Processing /usr/home/muad/iocage
Requirement already up-to-date: click==6.7 in /usr/local/lib/python3.6/site-packages (from iocage==0.9.9.2)
Requirement already up-to-date: texttable==0.9.0 in /usr/local/lib/python3.6/site-packages (from iocage==0.9.9.2)
Requirement already up-to-date: requests==2.17.3 in /usr/local/lib/python3.6/site-packages (from iocage==0.9.9.2)
Requirement already up-to-date: tqdm==4.14.0 in /usr/local/lib/python3.6/site-packages (from iocage==0.9.9.2)
Requirement already up-to-date: coloredlogs==7.0 in /usr/local/lib/python3.6/site-packages (from iocage==0.9.9.2)
Requirement already up-to-date: verboselogs==1.6 in /usr/local/lib/python3.6/site-packages (from iocage==0.9.9.2)
Requirement already up-to-date: pygit2==0.25.1 in /usr/local/lib/python3.6/site-packages (from iocage==0.9.9.2)
Requirement already up-to-date: cffi==1.9.1 in /usr/local/lib/python3.6/site-packages (from iocage==0.9.9.2)
Requirement already up-to-date: libzfs in /usr/local/lib/python3.6/site-packages (from iocage==0.9.9.2)
Requirement already up-to-date: urllib3<1.22,>=1.21.1 in /usr/local/lib/python3.6/site-packages (from requests==2.17.3->iocage==0.9.9.2)
Requirement already up-to-date: certifi>=2017.4.17 in /usr/local/lib/python3.6/site-packages (from requests==2.17.3->iocage==0.9.9.2)
Requirement already up-to-date: idna<2.6,>=2.5 in /usr/local/lib/python3.6/site-packages (from requests==2.17.3->iocage==0.9.9.2)
Requirement already up-to-date: chardet<3.1.0,>=3.0.2 in /usr/local/lib/python3.6/site-packages (from requests==2.17.3->iocage==0.9.9.2)
Requirement already up-to-date: humanfriendly>=3.2 in /usr/local/lib/python3.6/site-packages (from coloredlogs==7.0->iocage==0.9.9.2)
Requirement already up-to-date: six in /usr/local/lib/python3.6/site-packages (from pygit2==0.25.1->iocage==0.9.9.2)
Requirement already up-to-date: pycparser in /usr/local/lib/python3.6/site-packages (from cffi==1.9.1->iocage==0.9.9.2)
Installing collected packages: iocage
  Found existing installation: iocage 0.9.9.2
    Uninstalling iocage-0.9.9.2:
      Successfully uninstalled iocage-0.9.9.2
  Running setup.py install for iocage ... done
Successfully installed iocage-0.9.9.2
root@gaia:/home/muad/iocage # iocage list
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/iocage/lib/ioc_json.py", line 204, in json_load
    with open(self.location + "/config.json", "r") as conf:
FileNotFoundError: [Errno 2] No such file or directory: '/iocage/jails/www_test/config.json'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/bin/iocage", line 10, in <module>
    sys.exit(cli())
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/iocage/cli/list.py", line 74, in cli
    plugin=plugins, quick=quick)
  File "/usr/local/lib/python3.6/site-packages/iocage/lib/iocage.py", line 1141, in list
    exit_on_error=self.exit_on_error).list_datasets()
  File "/usr/local/lib/python3.6/site-packages/iocage/lib/ioc_list.py", line 76, in list_datasets
    _all = self.list_all(ds)
  File "/usr/local/lib/python3.6/site-packages/iocage/lib/ioc_list.py", line 153, in list_all
    conf = iocage.lib.ioc_json.IOCJson(mountpoint).json_load()
  File "/usr/local/lib/python3.6/site-packages/iocage/lib/ioc_json.py", line 231, in json_load
    self.json_convert_from_zfs(full_uuid)
  File "/usr/local/lib/python3.6/site-packages/iocage/lib/ioc_json.py", line 105, in json_convert_from_zfs
    props = self.zfs.get_dataset(dataset).properties
  File "libzfs.pyx", line 567, in libzfs.ZFS.get_dataset
libzfs.ZFSException: Dataset gaia/iocage/jails/- not found
root@gaia:/home/muad/iocage # 

Did a rm -rf py-libzfs and a new install with make install, still the same

**Comment by kitten77** [comment]
found it, if you delete jails/jail/config.json you can recreate it.
Had too manually umount all the test jails and destroy them from the zfs datasets too get it up and running again, it was a really newbie error from my side that triggered it. 
rm -rf /iocage/jails/www_test*
I am guessing if you put a new dataset into jails without having config.json it will also crash badly, what if iocage checks for the config and if it dosen't find it drop it? or list it as corrupt?

**Comment by skarekrow** [comment]
Odd! That functionality does exist and should be catching this. Thanks for following up! I’ll try to make this more robust, it dovetails nicely with the other refactoring I have to do.

**Comment by kitten77** [comment]
no problem. Iocage has become really good too work with, makes creating and destroying jails a childs play. specially like the change you did on the uuid and jail dirs

**Comment by skarekrow** [comment]
Thanks @kitten77 <3
