### ISSUE TITLE
What is host_hostname used for?

### ISSUE THREAD

**Issue by dlangille** [iocage/iocage#374]
$ iocage --version
Version	0.9.5 2017/02/15

After creating and starting a jail, I see host_hostname set in /etc/rc.conf within the jail.

I expected hostname=the tag value I get the jail at creation

The assigned value is jail_uuid

What use is variable?

Should it be hostname instead?

code search for that: https://github.com/iocage/iocage/search?utf8=%E2%9C%93&q=host_hostname&type=

**Comment by skarekrow** [comment]
It works the way you expect in the latest version. Please upgrade :)

**Comment by dlangille** [comment]
OK, let's see what breaks with the python 3.6 upgrade.  ;)

**Comment by skarekrow** [comment]
;)

**Comment by dlangille** [comment]
Done.  Details at https://gist.github.com/dlangille/142607fabf5ba64ff84f13e4910817d9

Hard start, then got it working just fine.
