### ISSUE TITLE
(jail) is running, all jails must be stopped before iocage will continue migration

### ISSUE THREAD

**Issue by ghost** [iocage/iocage#378]
Make sure to follow and check these boxes before submitting an issue! Thank you.

- [x] Supply `iocage --version`
Version 0.9.9.2 09/30/2017 (fb641a22f1ab798122fb995c52ff28afcc092dff)

- [x] Supply the commands used, along with any steps to recreate it.

```
root@beastie:~/src/iocage # jls
   373                  a811d40c-ee75-11e5-bdde-0cc47 /iocage/jails/a811d40c-ee75-11e5-bdde-0cc47a6bbf34/root

root@beastie:~/src/iocage # jexec 373 /bin/sh /etc/rc.shutdown
.
Terminated


root@beastie:~/src/iocage # iocage list
********************************************************************************
fdescfs(5) is not mounted, performance may suffer. Please run:
mount -t fdescfs null /dev/fd
You can also permanently mount it in /etc/fstab with the following entry:
fdescfs /dev/fd  fdescfs  rw  0  0
********************************************************************************

a811d40c-ee75-11e5-bdde-0cc47a6bbf34 (plex) is running, all jails must be stopped before iocage will continue migration
```
- [x] Provide the output from the command you issued.
- [x] Supply what you expected the result or output to be
jail stopped and upgrade/migration to continue

- [x] Checked that the problem has not already been fixed on `master` if using
 a stable release.

**Comment by skarekrow** [comment]
You should use `iocage stop` as there may be dangling mounts. But in this case I suspect you need to now `jail -r JID`
