### ISSUE TITLE
Cannot fetch 11.1-RELEASE - Too many failed verifications!

### ISSUE THREAD

**Issue by unti1x** [iocage/iocage#381]
Make sure to follow and check these boxes before submitting an issue! Thank you.

- [x] Supply `iocage --version`
    - Version	0.9.9.2 09/30/2017
- [x] Supply the commands used, along with any steps to recreate it.
    - `iocage fetch --release=11.1-RELEASE`
    - `iocage fetch -h --server=http://mirror.yandex.ru --root-dir=freebsd/releases/amd64 --release=11.1-RELEASE`
- [x] Provide the output from the command you issued.
```
Fetching: 11.1-RELEASE

base.txz missing, will try to redownload!
lib32.txz missing, will try to redownload!
doc.txz missing, will try to redownload!
Downloading: base.txz: 100% 3.02Mbit/s Elapsed: 00:34 Remaining: 00:00          
Downloading: lib32.txz: 100% 1.76Mbit/s Elapsed: 00:10 Remaining: 00:00         
Downloading: doc.txz: 100% 661Kbit/s Elapsed: 00:02 Remaining: 00:00            
Too many failed verifications!
```
- [x] Supply what you expected the result or output to be
Obviously, expected it installed properly. It works fine with 11.0, but 11.1 fails.
- [x] Checked that the problem has not already been fixed on `master` if using
 a stable release.

**Comment by skarekrow** [comment]
Can you try fetching this from the default sever? My suspicion is that you have wrong hashes inside the MANIFEST for your txz’s

**Comment by unti1x** [comment]
Default server doesn't work too, so I tried yandex mirror. It also didn't help. MANIFEST files are the same.

**Comment by frzb** [comment]
Please verify that you have an up-to-date root certificate package installed.

After installing a current one with:

```
# pkg install ca_root_nss-3.32.1
```

For me this issue went away.

**Comment by unti1x** [comment]
```
The most recent version of packages are already installed
```

**Comment by ghost** [comment]
I've seen this issue too. I destroyed the zfs dataset (I am using defaults) and refetched which worked for me.

**Comment by ghost** [comment]
```
root@beastie:/usr/home/voltagex # pkg install ca_root_nss-3.32.1
Updating FreeBSD repository catalogue...
Fetching meta.txz: 100%    944 B   0.9kB/s    00:01
Fetching packagesite.txz: 100%    6 MiB   1.0MB/s    00:06
Processing entries: 100%
FreeBSD repository update completed. 26974 packages processed.
All repositories are up to date.
Checking integrity... done (0 conflicting)
The most recent version of packages are already installed
root@beastie:/usr/home/voltagex # iocage fetch
[0] 9.3-RELEASE (EOL)
[1] 10.1-RELEASE (EOL)
[2] 10.2-RELEASE (EOL)
[3] 10.3-RELEASE
[4] 10.4-RELEASE
[5] 11.0-RELEASE
[6] 11.1-RELEASE

Type the number of the desired RELEASE
Press [Enter] to fetch the default selection: (11.0-RELEASE)
Type EXIT to quit: 6
Fetching: 11.1-RELEASE

base.txz missing, will try to redownload!
lib32.txz missing, will try to redownload!
doc.txz missing, will try to redownload!
Downloading: base.txz: 100% 1.68Mbit/s Elapsed: 01:02 Remaining: 00:00
Downloading: lib32.txz: 100% 685Kbit/s Elapsed: 00:26 Remaining: 00:00
Downloading: doc.txz: 100% 205Kbit/s Elapsed: 00:06 Remaining: 00:00
Too many failed verifications!

```

iocage fetch -r 11.0-RELEASE works fine.

**Comment by skarekrow** [comment]
@voltagex Try `iocage destroy -d -r 11.1-RELEASE` and then fetch again.

**Comment by unti1x** [comment]
Thanks. Destroying of dataset worked for me.

**Comment by skarekrow** [comment]
Great!

**Comment by fbruetting** [comment]
Just had the same issue. Could you implement a fix which solves this automatically, or make a suggestion, that the user should destroy it with the above command? This would avoid some search for new users, as we don’t know that parts of unsuccessful downloads are saved, though. :)

Root of that issue was having some corrupted download due to some old versions of several packages after upgrading to 11.1 (which caused some backtraces appearing). Having then upgraded these packages led to above mentioned error.

**Comment by gthank** [comment]
```
# freebsd-version
11.1-RELEASE-p6

# iocage --version
Version	0.9.10 2017/12/22

# iocage destroy -d -r 11.1-RELEASE

This will destroy RELEASE: 11.1-RELEASE

Are you sure? [y/N]: y
Partial UUID/NAME supplied, cannot check for dependant jails.

Proceed? [y/N]: y
Destroying RELEASE dataset: 11.1-RELEASE
Destroying RELEASE download dataset: 11.1-RELEASE

# iocage fetch --release=11.1-RELEASE
Fetching: 11.1-RELEASE

base.txz missing, will try to redownload!
lib32.txz missing, will try to redownload!
doc.txz missing, will try to redownload!
src.txz missing, will try to redownload!
Downloading : base.txz [####################] 100%  6.83Mbit/s
Downloading : lib32.txz [####################] 100%  7.01Mbit/s
Downloading : doc.txz [####################] 100%  6.77Mbit/s
Downloading : src.txz [####################] 100%  6.92Mbit/s
 6.92Mbit/sToo many failed verifications!
```

I was expecting this to properly fetch the release. The host is an 11.1-RELEASE box (as seen above) that was originally an `11.0-RELEASE` box that I manually upgraded around the time 11.0 was EOL'd. I initially started on the binary pkg, but it wasn't working, even after manually downgrading `tqdm`. At that point, I uninstalled the pkg and installed the port. That got me past the `KeyError`, but now I'm stuck here. As you can see, I tried the workaround of explicitly deleting the release and trying to fetch a fresh a copy.

The end goal of all this work is actually to upgrade a running jail (or three) from `11.0-RELEASE` to `11.1-RELEASE`.

**Comment by tehfink** [comment]
Getting the same error on a fresh install of 11.1…
