### ISSUE TITLE
iocage fetch from mirror fails without a good error message

### ISSUE THREAD

**Issue by ghost** [iocage/iocage#386]
- [x] Supply `iocage --version`
Version 0.9.9.2 09/30/2017

- [x] Supply the commands used, along with any steps to recreate it.
- [x] Provide the output from the command you issued.

```
root@beastie:/usr/home/voltagex # iocage fetch -s mirror.internode.on.net

Type the number of the desired RELEASE
Press [Enter] to fetch the default selection: (11.0-RELEASE)
Type EXIT to quit: [enter]
Please select an item!

```

Same error if I append -d pub, so I'm assuming the command is supposed to be `iocage fetch -s mirror.internode.on.net -d /pub/freebsd`

- [x] Supply what you expected the result or output to be
Download the default release from the selected mirror

- [x] Checked that the problem has not already been fixed on `master` if using
 a stable release.

**Comment by skarekrow** [comment]
So the directory you want to point to is whichever is holding the RELEASEs you want, so if on the server `/foo/bar`'s contents are `11.0-RELEASE, 11.1-RELEASE` that is what you would use for `-d`.

`iocage fetch -s mirror.internode.on.net -d /foo/bar` for that example
