### ISSUE TITLE
How do I rename a jail?

### ISSUE THREAD

**Issue by ghost** [iocage/iocage#387]
Make sure to follow and check these boxes before submitting an issue! Thank you.

- [x] Supply `iocage --version`
Version 0.9.9.2 09/30/2017

- [x] Supply the commands used, along with any steps to recreate it.
- [x] Provide the output from the command you issued.

```
root@beastie:/usr/home/voltagex # iocage list
+-----+----------+-------+--------------+------------+
| JID |   NAME   | STATE |   RELEASE    |    IP4     |
+=====+==========+=======+==============+============+
| -   | 2ef966f8 | down  | 11.0-RELEASE | -          |
+-----+----------+-------+--------------+------------+

root@beastie:/usr/home/voltagex # iocage set tag=downloads 2ef966f8
tag is not a valid property!
root@beastie:/usr/home/voltagex # iocage set name=downloads 2ef966f8
name is not a valid property!
```
- [x] Supply what you expected the result or output to be

Able to rename or tag the jail - given that the creation parameter is --name and another jail shows tag and name properties, this error doesn't make a lot of sense

- [x] Checked that the problem has not already been fixed on `master` if using
 a stable release.

**Comment by skarekrow** [comment]
Just type `iocage` ;) `iocage rename` is a subcommand, it's even easier then set!
