### ISSUE TITLE
What is the "data" zfs filesystem for? + snapshotting them

### ISSUE THREAD

**Issue by stratacast** [iocage/iocage#388]
- [ ] Supply `iocage --version` 0.9.9.2

After using iocage for a short period of time, I see that "data" neither has a mountpoint or seems to be in use. Is there a reason for that? I am wondering primarily because I'm trying to set up a non-root user to take regular snapshots of my iocage zpool and only on these "data" datasets, I cannot take snapshots unless I am root or use sudo. So what can I do with these datasets? Right now they really just appear to be getting in the way for me

**Comment by skarekrow** [comment]
They were originally intended for users who wanted an easy dataset for zfs jailed datasets. The current iocage does not automatically create these, and should create them if needed. So feel free to nuke those!
