### ISSUE TITLE
iocage upgrade results in "No updates are available to install" being printed infinitely

### ISSUE THREAD

**Issue by lukaszczerpak** [iocage/iocage#397]
- [x] Supply `iocage --version`

`Version	0.9.9.2 09/30/2017`

- [x] Supply the commands used, along with any steps to recreate it.

```
» iocage create -n upgtest1 -r 10.3-RELEASE ip4_addr="lo1|192.168.x.y/24"
» iocage set host_hostname=upgtest1 upgtest1
» iocage set allow_raw_sockets=1 upgtest1
» iocage upgrade -r 11.1-RELEASE upgtest1
```

Upgrade results in the same error for new and already existing jails.

- [x] Provide the output from the command you issued.

```
/var/yp/Makefile.dist
To install the downloaded upgrades, run "/tmp/tmpdqbsb20z install".
Installing updates...
Kernel updates have been installed.  Please reboot and run
"/tmp/tmpdqbsb20z install" again to finish installing updates.
Installing updates...
Completing this upgrade requires removing old shared object files.
Please rebuild all installed 3rd party software (e.g., programs
installed from the ports tree) and then run "/tmp/tmpdqbsb20z install"
again to finish installing updates.
Installing updates... done.
No updates are available to install.
Run '/tmp/tmpdqbsb20z fetch' first.
No updates are available to install.
Run '/tmp/tmpdqbsb20z fetch' first.
No updates are available to install.
Run '/tmp/tmpdqbsb20z fetch' first.
...
No updates are available to install.
Run '/tmp/tmpdqbsb20z fetch' first.
```

The last two lines are being repeated in sort of infinite loop.

- [x] Supply what you expected the result or output to be

Upgraded jail.

- [x] Checked that the problem has not already been fixed on `master` if using
 a stable release.

I haven't checked that, but I also didn't find any evidence of such problem appearing to others.

**Comment by skarekrow** [comment]
Odd, I've never seen this. The routine continues until `freebsd-update` is normally done, but clearly it's not exiting the way I normally expect. I'll try to replicate this or make the routine a bit smarter.

**Comment by lukaszczerpak** [comment]
Ok, thanks! Let me know if any extra debugging/information would be needed to make your life easier ;)

**Comment by skarekrow** [comment]
https://github.com/freebsd/freebsd/commit/4c961de5c58afded8c457d94ca0970c767c9db67#diff-4c6ad711dde27ce73583d13acd0677ec This was upstream :D Will fix

**Comment by skarekrow** [comment]
@lukaszczerpak Fixed! Will be in the next release :)

**Comment by lukaszczerpak** [comment]
@skarekrow thank you!
