### ISSUE TITLE
don't fetch 9.3-10.2 

### ISSUE THREAD

**Issue by jungle-boogie** [iocage/iocage#4]
Hello,

9.3 and 10.1, 10.2-relases are no longer supported. Should iocage still support them during a fetch?
https://www.freebsd.org/security/security.html#sup

```
% sudo iocage fetch
[0] 9.3-RELEASE
[1] 10.1-RELEASE
[2] 10.2-RELEASE
[3] 10.3-RELEASE
[4] 11.0-RELEASE
```

**Comment by skarekrow** [comment]
Instead of the legacy iocage's approach of a hardcoded list, I actually scrape the FTP/HTTP server supplied and present that as a list. So as long as they are on the server, they are fetchable :) I won't tell the user what they can or can't use for a RELEASE. I trust they know why they are selecting it. Maybe I should add a `(EOL)` indicator next to each EOL RELEASE though?

What do you think?

**Comment by jungle-boogie** [comment]
Hi @skarekrow,

Ah, now that I peaked at your lib for fetch, I see what you're doing. I do like your idea of not hard coding it. The EOL tag is good, too, but does that mean you would need to maintain a list of EOL releases? Obviously once it's not listed on the download page, you could remove the EOL from your code.

In case you didn't know, FreeBSD has a TLS download page:
https://download.freebsd.org/ftp/releases/

Don't know if you want to use that or keep it http.

**Comment by skarekrow** [comment]
Well the user can specify their own FTP or HTTP server. Not just the official mirror, so I'll have to find some way to hopefully scrape that information so I don't have to update it each time. Thanks for the TLS mirror. I support `basic` and `digest` auth methods for user HTTPS but I totally forgot to make the default mirror TLS heh. Will add shortly.

**Comment by skarekrow** [comment]
@jungle-boogie Added both of the things you brought up.

```
 bschneider@pie  ~  sudo iocage fetch -h
[0] 9.3-RELEASE (EOL)
[1] 10.1-RELEASE (EOL)
[2] 10.2-RELEASE (EOL)
[3] 10.3-RELEASE
[4] 11.0-RELEASE

Which release do you want to fetch? (EXIT) EXIT
```

So we should now be good to go on that front.

**Comment by jungle-boogie** [comment]
Nice, very good job!
