### ISSUE TITLE
VNET jail gets IPv6 address that I didn't ask for

### ISSUE THREAD

**Issue by rexpo** [iocage/iocage#401]
My VNET jail is set up as bridged to the only NIC in the host. Both the host's and the jail's NICs are set up to use DHCP from the same DHCP server, in the same subnet. (The "problem" also occurs if I bridge to other NICs/VLANs on other subnets).

The host gets only an IPv4 address on its NIC (which seems reasonable, as I skipped the "Do you want to configure IPv6 on this interface" during initial install of the OS), but the jail gets both an IPv4 and an IPv6 address on its `vnet0` NIC.

(Note that in all cases, the loopback adapter gets its IPv6 address, but that's not the issue here)

I haven't had time to play much with the ip6 iocage attributes, but will include them here in case there is something obvious that I'm missing (they are just the defaults):

```
defaultrouter6:none
ip6:new
ip6_addr:none
ip6_saddrsel:1
```

Make sure to follow and check these boxes before submitting an issue! Thank you.

- [X] Supply `iocage --version`

Version 0.9.10 RC (from commit: 9c217ff)

- [X] Supply the commands used, along with any steps to recreate it.

Create a VNET jail with DHCP on, fire it up, attach to the console, and check the interface configuration:

```
iocage create --name ipv6test --release 10.3-RELEASE vnet=on bpf=yes dhcp=on interfaces="vnet0:bridge0"
iocage start ipv6test
iocage console ipv6test
ifconfig
```

- [X] Provide the output from the command you issued.

```
lo0: flags=8049<UP,LOOPBACK,RUNNING,MULTICAST> metric 0 mtu 16384
        options=600003<RXCSUM,TXCSUM,RXCSUM_IPV6,TXCSUM_IPV6>
        inet6 ::1 prefixlen 128
        inet6 fe80::1%lo0 prefixlen 64 scopeid 0x1
        inet 127.0.0.1 netmask 0xff000000
        nd6 options=21<PERFORMNUD,AUTO_LINKLOCAL>
vnet0: flags=8843<UP,BROADCAST,RUNNING,SIMPLEX,MULTICAST> metric 0 mtu 1500
        options=8<VLAN_MTU>
        ether 02:ff:60:2b:61:5e
        inet6 fe80::ff:60ff:fe2b:615e%vnet0 prefixlen 64 scopeid 0x2
        inet 10.1.1.229 netmask 0xffffffc0 broadcast 10.1.1.255
        nd6 options=21<PERFORMNUD,AUTO_LINKLOCAL>
        media: Ethernet 10Gbase-T (10Gbase-T <full-duplex>)
        status: active
```

- [X] Supply what you expected the result or output to be

I expect to not see the `inet6` line on the `vnet0` NIC:

```
lo0: flags=8049<UP,LOOPBACK,RUNNING,MULTICAST> metric 0 mtu 16384
        options=600003<RXCSUM,TXCSUM,RXCSUM_IPV6,TXCSUM_IPV6>
        inet6 ::1 prefixlen 128
        inet6 fe80::1%lo0 prefixlen 64 scopeid 0x1
        inet 127.0.0.1 netmask 0xff000000
        nd6 options=21<PERFORMNUD,AUTO_LINKLOCAL>
vnet0: flags=8843<UP,BROADCAST,RUNNING,SIMPLEX,MULTICAST> metric 0 mtu 1500
        options=8<VLAN_MTU>
        ether 02:ff:60:2b:61:5e
        inet 10.1.1.229 netmask 0xffffffc0 broadcast 10.1.1.255
        nd6 options=21<PERFORMNUD,AUTO_LINKLOCAL>
        media: Ethernet 10Gbase-T (10Gbase-T <full-duplex>)
        status: active
```

- [ ] Checked that the problem has not already been fixed on `master` if using
 a stable release.

(I'm using the latest version of `master`)

**Comment by asomers** [comment]
Any address beginning with `fe80:` is a link-local address.  It can only be used to communicate with other hosts on the same subnet.  In IPv6, each interface is required to have a link-local address and they're usually assigned automatically.  It doesn't hurt anything to have it, but if you want to be rid of it, you can probably do so by setting the following in the jail's rc.conf:
```sh
ipv6_activate_all_interfaces="NO"
ifconfig_vnet0_ipv6="ifdisabled"
```

**Comment by skarekrow** [comment]
@rexpo I should ask, did this cause you any issues? Like @asomers said we used these so the jail is compliant in both schemes without a ton of headaches. It *should* be harmless to any operations, so we opted to do this instead of just disabling ipv6 entirely.

**Comment by rexpo** [comment]
Sorry about the radio silence for so long, I've been swamped at work and am only just starting to get my head above water.

The issue arose while trying to use `portdowngrade` inside a jail. It depends on Subversion, which in turn depends on `devel/apr1`, which pukes while trying to use the jail's IPv6 address (which isn't "connected" to anything), rather than gracefully failing over to the jail's IPv4 address (which is properly set up with complete Internet access).

It's been a while, but if I recall correctly, I could install FreeBSD on a new bare metal system, explicitly choose to not configure IPv6 in the installer, and then it was possible to use `portdowngrade` without problems.

I guess I was hoping that telling `iocage` to disable IPv6 would result in either disabling it completely, or at least configuring only the IPv6 loopback address, but no other IPv6 addresses.

I haven't had time to test @asomers suggestion of editing the `rc.conf` inside the jail, but if that works, then I don't mind the extra overhead of having to do this on a problem jail once in a while

*Yes, `portdowngrade` is a stupid example, since it is no longer supported, plus `poudriere` does a much better job. This probably has low impact for most ports, I'm guessing*

**Comment by skarekrow** [comment]
Yeah this has low impact for a far reaching solution of changing the default rc.conf that many users may end up depending on. I'll close this since editing rc.conf should resolve any of these issues, as that's all iocage is adding to the jail in this case anyways :)
