### ISSUE TITLE
Feature request: JSON output for read operations

### ISSUE THREAD

**Issue by zachfi** [iocage/iocage#402]
Hi, for many years now, I have wanted to be able to read the list of jails and their attributes from JSON.  This comes up again, because the parsing of the command line output has changed, and it has perhaps yet to stabilize.  I would like to ensure an integration component I work on will not break when another column is added to an output, or when the IP format changes, or other such items.

This is an issue on all versions of iocage.
I would expect `iocage list --json` to return a hash keyed by jail identifier, or name, or some other unique key.  `iocage get all myjail --json` should return a hash keyed by attribute name and valued by attribute value.

JSON output for these two interfaces would help enable simpler, more consistent, and forward-thinking integration without worrying if the output of a command changed column width, for example.

Make sure to follow and check these boxes before submitting an issue! Thank you.

- [x] Supply `iocage --version`
- [x] Supply the commands used, along with any steps to recreate it.
- [x] Provide the output from the command you issued.
- [x] Supply what you expected the result or output to be
- [x] Checked that the problem has not already been fixed on `master` if using
 a stable release.

**Comment by rwestlund** [comment]
@xaque208 Can't you just read `/iocage/jails/$JAIL/config.json`?  Sounds like all you want is to have iocage cat that file at you.

**Comment by zachfi** [comment]
@rwestlund Thanks for the pointer.  I didn't know that file existed, and I've not made the transition to pyiocage yet, so it wasn't present on the jails I do have running.

Looking over the config, there is not a notion of which keys set in there are available for setting through `iocage set`.  So I think what I'm after here is to have iocage give me all the properties that are available from the perspective of iocage.  What I don't want to know about is the internal data structures of the configuration in the case that it changes.  I want a consistent interface that I can rely upon, and that iocage the project can amend to without having to make updates to the integration.

So the `config.json` is close, but not quite what I'm after.

Also, sorry for the delay on coming back to this, I must have just missed the update.  I'm keen to see this as a feature, so anything I can do to help here.

**Comment by zachfi** [comment]
Any other questions I can answer here?  I can cheer if that's helpful.

**Comment by skarekrow** [comment]
Ok so just to confirm, it's not ALL read operations, but you just want a json list of the settable keys that a user can use?

**Comment by zachfi** [comment]
Any structured data would work.  A hash with the default values might also be good instead of a list.  Then I'd be able to compare values in the case that the defaults had changed.

For the jails, a list of jail hashes would be fine, or just one large hash keyed by UUID.  Either way can be parsed and used as long as the data comes back parseable.  Like a local API.
