### ISSUE TITLE
Auto-rename on upgrade missed fstab entries

### ISSUE THREAD

**Issue by atl** [iocage/iocage#405]
Make sure to follow and check these boxes before submitting an issue! Thank you.

- [x] Supply `iocage --version`
Version 0.9.10 RC
- [x] Supply the commands used, along with any steps to recreate it.
- [x] Provide the output from the command you issued.

> iocage list -l

********************************************************************************
Jail: df4ee431 was renamed to torrent
********************************************************************************

> iocage start --rc

  Starting torrent
mount: /mnt/iocage/jails/df4ee431: No such file or directory
jail: /sbin/mount -t nullfs -o rw /mnt/snooker/data/shared /mnt/iocage/jails/df4ee431/root/mnt/shared: failed

- [x] Supply what you expected the result or output to be

I expected the startup to proceed without issue.

I found this after upgrading to FreeNAS 11.1-RC1 and tried starting my (iocage) plugins and hand-tweaked jails. I can hand-edit these fstab entries and get going but:

I expected a few things that I found missing on this release:

- not to write changes to the system on what I expect to be a read-only, status command (`iocage list`)
- an explanation and perhaps rationale of the changes to the system 
- the automatic changes to be complete (not leave the jail in an un-start-able state due to not touching the fstab

I know I'm on the bleeding edge, user-wise, and I'm pretty sure I can recover from here, but I regret not snapshotting *everything*, and not receiving any warning before the automatic changes began.

**Comment by skarekrow** [comment]
This *should* have renamed the fstab entries. But I might be thinking of something else. You're absolutely right on the readonly operation. I will have it ask before it continues on these operations.

Thanks!

**Comment by atl** [comment]
Good news, as expected, editing the fstab entries in the expected way enabled my jails to come up.
