### ISSUE TITLE
dataset mountpoints not OK after update from iocage_legacy

### ISSUE THREAD

**Issue by netchild** [iocage/iocage#409]
Hi,

- [x] Supply `iocage --version`

0.9.9.2

- [x] Supply what you expected the result or output to be

After an updatefrom iocage_legac and fixing the issue of the content of the dataset property not being renamed (see previous issue): the mountpoints of the renamed datasets are not pointing to where the shall point to. Example: /iocage/jails/xxx/data/ports was pointing inside the jails to /iocage/jails/xxx/data/ports instead of the previous mountpoint /usr/ports. The same is true for all datasets below .../data. I would have expected that the mountpoints inside the jail are kept.

(Yes, I changed the mountpoints after starting the jails inside the jail as they shall be after detecting the issue.) 

Bye,
Alexander.

**Comment by reelsense** [comment]
I have about 40 iocage_legacy jails I need to migrate. Thank you for reporting this. Did you upgrade in place or import exported jail images?

**Comment by netchild** [comment]
I did an in-place upgrade.

**Comment by skarekrow** [comment]
I believe this was due to how we specified mountpoints during the dataset check. That has changed in 1.0 RELEASE, so closing as it should be resolved.
