### ISSUE TITLE
py-libzfs missing

### ISSUE THREAD

**Issue by kitten77** [iocage/iocage#410]
[webhotell] root@gaia:/home/muad/python/iocage # make install
echo -e "import os\ntry:\n  if not os.listdir('/usr/src'): exit('/usr/src must be populated!')\nexcept FileNotFoundError:\n  exit('/usr/src must be populated!')" | python3.6
test -d .git && git pull || true
Already up-to-date.
python3.6 -m ensurepip
Requirement already satisfied: setuptools in /usr/home/muad/virtualenv/webhotell/lib/python3.6/site-packages
Requirement already satisfied: pip in /usr/home/muad/virtualenv/webhotell/lib/python3.6/site-packages
pip3.6 install -U Cython
Requirement already up-to-date: Cython in /usr/home/muad/virtualenv/webhotell/lib/python3.6/site-packages
cd py-libzfs && python3.6 setup.py build && python3.6 setup.py install
python3.6: can't open file 'setup.py': [Errno 2] No such file or directory
*** Error code 2

Stop.
make: stopped in /usr/home/muad/python/iocage
#[webhotell] root@gaia:/home/muad/python/iocage # cd py-libzfs/
#[webhotell] root@gaia:/home/muad/python/iocage/py-libzfs # ls
#[webhotell] root@gaia:/home/muad/python/iocage/py-libzfs # cd ..
#[webhotell] root@gaia:/home/muad/python/iocage # git pull .
From .
 * branch            HEAD       -> FETCH_HEAD
Already up-to-date.
[webhotell] root@gaia:/home/muad/python/iocage # make install .
echo -e "import os\ntry:\n  if not os.listdir('/usr/src'): exit('/usr/src must be populated!')\nexcept FileNotFoundError:\n  exit('/usr/src must be populated!')" | python3.6
test -d .git && git pull || true
Already up-to-date.
python3.6 -m ensurepip
Requirement already satisfied: setuptools in /usr/home/muad/virtualenv/webhotell/lib/python3.6/site-packages
Requirement already satisfied: pip in /usr/home/muad/virtualenv/webhotell/lib/python3.6/site-packages
pip3.6 install -U Cython
Requirement already up-to-date: Cython in /usr/home/muad/virtualenv/webhotell/lib/python3.6/site-packages
cd py-libzfs && python3.6 setup.py build && python3.6 setup.py install
python3.6: can't open file 'setup.py': [Errno 2] No such file or directory
*** Error code 2

[webhotell] root@gaia:/home/muad/python/iocage # git clone https://github.com/jceel/py-libzfs.git
Cloning into 'py-libzfs'...
remote: Counting objects: 983, done.
remote: Total 983 (delta 0), reused 0 (delta 0), pack-reused 983
Receiving objects: 100% (983/983), 353.82 KiB | 584.00 KiB/s, done.
Resolving deltas: 100% (633/633), done.
[webhotell] root@gaia:/home/muad/python/iocage # make install .
echo -e "import os\ntry:\n  if not os.listdir('/usr/src'): exit('/usr/src must be populated!')\nexcept FileNotFoundError:\n  exit('/usr/src must be populated!')" | python3.6
test -d .git && git pull || true
Already up-to-date.
python3.6 -m ensurepip
Requirement already satisfied: setuptools in /usr/home/muad/virtualenv/webhotell/lib/python3.6/site-packages
Requirement already satisfied: pip in /usr/home/muad/virtualenv/webhotell/lib/python3.6/site-packages
pip3.6 install -U Cython
Requirement already up-to-date: Cython in /usr/home/muad/virtualenv/webhotell/lib/python3.6/site-packages
cd py-libzfs && python3.6 setup.py build && python3.6 setup.py install
running build
running build_py
running build_ext

**Comment by asomers** [comment]
This probably means that you didn't use the `--recursive` flag to `git clone`.  Either blow away your repo and reclone it, or do `git submodule init py-libzfs update py-libzfs`.
