### ISSUE TITLE
clonejail is not a supported jail type.

### ISSUE THREAD

**Issue by jeremyandrews** [iocage/iocage#413]
Make sure to follow and check these boxes before submitting an issue! Thank you.

- [X] Supply `iocage --version`

Version	0.9.9.2 09/30/2017

- [X] Supply the commands used, along with any steps to recreate it.

I migrated my iocage legacy jails by running 'iocage list' over and over.
When done, I was unable to start any of them due to the following error:
`clonejail is not a supported jail type.`

I manually resolved this by editing `config.json`, changing the following line:
`    "type": "clonejail",`
to instead be:
`    "type": "jail",`

- [X] Provide the output from the command you issued.

`# iocage start plex`
`clonejail is not a supported jail type.`

- [X] Supply what you expected the result or output to be

`* Starting plex`
`  + Started OK`
`  + Starting services OK`

- [ ] Checked that the problem has not already been fixed on `master` if using
 a stable release.

**Comment by skarekrow** [comment]
Don't change your jail type, as that's for internal bookkeeping. I can't remember why I did not support that type of jail, I'll have to investigate and see why.

**Comment by jeremyandrews** [comment]
My decision to change the jail type came from looking at these code snippets where it only supports 'jail' and 'plugin' as jail types:

- https://github.com/iocage/iocage/blob/08c0ca95bb1716b4a68e13f7021588b6e513c260/iocage/lib/iocage.py#L283
- https://github.com/iocage/iocage/blob/1a6c93b40742f726fbbc7abc9e760349d6b40e87/iocage/lib/ioc_exec.py#L86

I had a rough upgrade from `iocage_legacy` which could have put me in an unexpected state. (Part of the problem I ran into in is that the latest pkg is `0.9.9.1` but one or more important bug fixes for upgrading from legacy are in `0.9.9.2` -- I didn't realize at first that the pkg is out of date and first tried with the older release.)
