### ISSUE TITLE
Wrong error message when creating from template

### ISSUE THREAD

**Issue by rexpo** [iocage/iocage#414]
Create a jail. Create a template. Then try to create a jail from that template, with the same name as the first jail.

Should get a *jail already exists* error, but instead get a *template not found* error.

- [x] Supply `iocage --version`

Version 0.9.10 RC (08c0ca9)

- [x] Supply the commands used, along with any steps to recreate it.

Set the stage:

```
iocage create --name sally --release 9.3-RELEASE
iocage create --name thetemplate --release 9.3-RELEASE
iocage set template=yes thetemplate
```

Prove that my template works:

```
iocage create --name jenny --template thetemplate
```

Prove that the *jail already exists* error message works:

```
iocage create --name sally --release 9.3-RELEASE
```

Finally, the provoke the wrong *template not found* error message:

```
iocage create --name sally --template thetemplate
```

Just for kicks, list my templates:

```
iocage list -t
```

- [x] Provide the output from the command you issued.

```
Template: thetemplate not found!
Created Templates:
  oc-9_0_1
iocage list -t
+-----+-------------+-------+-------------+-----+
| JID |    NAME     | STATE |   RELEASE   | IP4 |
+=====+=============+=======+=============+=====+
| -   | oc-9_0_1    | down  | 9.3-RELEASE | -   |
+-----+-------------+-------+-------------+-----+
| -   | thetemplate | down  | 9.3-RELEASE | -   |
+-----+-------------+-------+-------------+-----+
```

- [x] Supply what you expected the result or output to be

```
Jail: sally already exists!
```

**Comment by rexpo** [comment]
In fact it seems that the error message will always be *template not found* when we are creating from a template and something goes wrong. For example, create from a "defective" template (where I forgot to set up networking before converting to template), and tell it to install a few packages during creation:

```
iocage create --name owncloud2 --template oc-9_0_1 --pkglist owncloud-packages.json vnet=on bpf=yes dhcp=on interfaces="vnet0:bridge20" host_hostname=owncloud2
owncloud2 successfully created!
Testing SRV response to FreeBSD
jexec: execvp: drill: No such file or directory
Template: oc-9_0_1 not found!
Created Templates:
  oc-9_0_1
```

A bit of an obscure error condition to hit there, not sure how much effort you want to put in to that, but I mention it in case it gives clues to help fixing the original problem of the incorrect error message.

**Comment by skarekrow** [comment]
Yeah this was an early try except clause that I suspect grew larger then intended. Will check it out, thanks!
