### ISSUE TITLE
Feature: Create iocages jails from a CSV file

### ISSUE THREAD

**Issue by akelling** [iocage/iocage#418]
I would like to see a feature where I can create multiple jails from a CSV file. The names of the jail, the ip,  from a template, and on boot being the big ones to get started. From an enterprise standpoint I would like to have cpu, io, and memory restrictions. Really all the options that are there during the creation of a jail as supported would be the end game of this csv.

**Comment by rwestlund** [comment]
Two easy solutions come to mind:
1. Use iocage/libiocage and write your logic in a short python script.
2. Write a really quick shell script to iterate over your CSV file and call iocage directly.

**Comment by akelling** [comment]
And destroy with CSV I am looking for IAC (Infrastructure As Code)

**Comment by akelling** [comment]
rwestlund I already thought of the bash wrapper idea the other night when I had the CSV feature idea. Really I think would a huge advantage if iocage had it baked in which is why I took time out of my day to write this request instead of writing the wrapper. I am an enterprise admin and want to make other admin's life's easier and not have to always reinvent the wheel.

**Comment by skarekrow** [comment]
Not on the plate for 1.0 or anything immediate, but this could be interesting. I'm hoping to tack on json input as well. CSV shouldn't get all the fun!
