### ISSUE TITLE
error on `iocage stop` on a long shutdown time

### ISSUE THREAD

**Issue by lukaszczerpak** [iocage/iocage#42]
iocage version: 0.9.6 (current master)

I have a jail which starts very very slowly (need to figure out, but it's not iocage issue) and also shutting it down takes ages. It causes the new iocage to throw the following error which was never the case when I was using the old version:

```
root@server ~ » iocage start mail-solr
* Starting 34f25ce3-7ff0-11e6-952f-003048f8f8e6 (mail-solr)
  + Started OK
  + Starting services OK
root@server ~ » iocage stop mail-solr
* Stopping 34f25ce3-7ff0-11e6-952f-003048f8f8e6 (mail-solr)
Traceback (most recent call last):
  File "/usr/local/bin/iocage", line 11, in <module>
    load_entry_point('iocage==0.9.6', 'console_scripts', 'iocage')()
  File "/usr/local/lib/python3.5/site-packages/iocage/main.py", line 92, in main
    cli(obj=MODULES)
  File "/usr/local/lib/python3.5/site-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.5/site-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.5/site-packages/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.5/site-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.5/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python3.5/site-packages/iocage/cli/stop.py", line 88, in stop_cmd
    IOCStop(uuid, tag, path, conf)
  File "/usr/local/lib/python3.5/site-packages/iocage/lib/ioc_stop.py", line 27, in __init__
    self.__stop_jail__()
  File "/usr/local/lib/python3.5/site-packages/iocage/lib/ioc_stop.py", line 105, in __stop_jail__
    exec_stop, stdout=f, stderr=PIPE)
  File "/usr/local/lib/python3.5/subprocess.py", line 271, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['jexec', 'ioc-34f25ce3-7ff0-11e6-952f-003048f8f8e6', '/bin/sh', '/etc/rc.shutdown']' returned non-zero exit status -9
```

When I execute the same stop command after a while I get the jail stopped. My gut feeling is that long shutdown time causes timeout in iocage and this is manifested by throwing the error.

**Comment by skarekrow** [comment]
I actually think this is because I must not be handling the exit code, will check this out.

Thanks!

**Comment by skarekrow** [comment]
Any reproducable usecase you can provide would also help 👍

**Comment by lukaszczerpak** [comment]
Simply add `sleep 300` to any rc script ;) after 2-3mins (didn't measure carefully) you will get this error.

**Comment by skarekrow** [comment]
Ha! Easy enough to test then.

**Comment by lukaszczerpak** [comment]
There is one interesting observation - the issue occurs for `mail-solr` jail only. More, if I run `jexec <JID> /bin/sh /etc/rc.shutdown` then `solr` service is taken down within 3-4s, whereas same command executed by iocage results in timeout...
Not sure how to track it down - any hints much appreciated :)

**Comment by lukaszczerpak** [comment]
I figured this out. When iocage shuts down a jail, it first clears networking and then stops services. Solr unfortunately is not able to shut down without networking. Would it be possible to execute `rc.shutdown` first and then clear networking?

EDIT: I tried to work around by using `exec_prestop` but didn't seem to work (not implemented yet?):

```
» iocage set exec_prestop="/usr/sbin/service solr stop" mail-solr
```

**Comment by skarekrow** [comment]
I'll look into it. I believe that's how we did it last time but perhaps that is not the case. I don't imagine doing this will cause any issues and in fact may be the better way of doing things. 

If you ever find yourself at BSDCan I owe you a beer for all this testing  ;)

**Comment by skarekrow** [comment]
So it turns out I was doing this out of order, d'oh! As for `exec_prestop`, yes that is not implemented quite yet. The initial support is there, I just haven't had time to finish it quite yet.


EDIT: Please test and let me know if this solves it for you 👍

**Comment by lukaszczerpak** [comment]
Thanks a ton! Works like a charm:))))

**Comment by skarekrow** [comment]
Awesome!
