### ISSUE TITLE
Modifying templates

### ISSUE THREAD

**Issue by abelbabel** [iocage/iocage#422]
Hi,

I want to modify an existing template by copying/editing some files in it. This is not possible due to template related ZFSs are mounted read-only. Converting template back to a jail using

`iocage set template=no TEMPLATE`

fails with "Device busy" error even if I manually umount all related ZFSs. The problem seems to be that I already have a cloned running jail and the "zfs rename" process wants to umount the ZFS belonging to that jail.

It would be nice to have a feature that re-mounts template ZFSs read-write for the purpose of editing them without doing an unnecessary and costly conversion back to a jail again.

Furthermore, the documentation only states that the difference between jails and templates is that "templates are not started by iocage". It would be convenient to mention mount type related informations as well.

I'm using iocage Version 0.9.9.2 09/30/2017.

Regards,
abelbabel

**Comment by skarekrow** [comment]
Duplicate request of #417
