### ISSUE TITLE
Feature: do not fetch an already fetched release again by default

### ISSUE THREAD

**Issue by abelbabel** [iocage/iocage#423]
Hi,

it would be nice if iocage would not attempt to fetch an already fetched release again by default. If this behaviour is desired (which I assume is not in most cases), it can be accomplished by an additionally provided command-line parameter/force-flag.

Kind regards,
abelbabel

**Comment by skarekrow** [comment]
This is the default behavior in iocage.

**Comment by abelbabel** [comment]
Ah, sorry. I misinterpretted the long period of time between issuing the command

`iocage fetch --release 11.1-RELEASE`

and its return.
What the command does (according to its output) is:
Extracting .txz-packages and
Updating the release

So my feature request would be to avoid reextracting and reupdating the release by default if it already exists.

**Comment by abelbabel** [comment]
Can someone (me?) reopen this issue with a modified subject? Or should I create a new issue?
