### ISSUE TITLE
Missing feature: like in legacy: release=xxx

### ISSUE THREAD

**Issue by netchild** [iocage/iocage#425]
Hi,

- [x] Supply `iocage --version`

Latest from ports tree:
Version 0.9.9.2 09/30/2017

I updated from iocage_legacy, and now I try to match what I did in the past with the recent iocage version.

I updated my jails by creating my own content in pool/iocage/base/xxx-RELEASE. I did that from source (-current). Here is the script I used for that:
---snip---
#!/bin/sh

cd /usr/src

POOLNAME=mpool
SRC_REV=r$(svnliteversion)
IOCAGE_BASE=""

echo creating new ZFS datasets for ${SRC_REV} basejail
zfs create -o compression=lz4 ${POOLNAME}/iocage/base/${SRC_REV}-RELEASE
zfs create -o compression=lz4 ${POOLNAME}/iocage/base/${SRC_REV}-RELEASE/root
zfs create -o compression=lz4 ${POOLNAME}/iocage/base/${SRC_REV}-RELEASE/root/bin
zfs create -o compression=lz4 ${POOLNAME}/iocage/base/${SRC_REV}-RELEASE/root/boot
zfs create -o compression=lz4 ${POOLNAME}/iocage/base/${SRC_REV}-RELEASE/root/lib
zfs create -o compression=lz4 ${POOLNAME}/iocage/base/${SRC_REV}-RELEASE/root/libexec
zfs create -o compression=lz4 ${POOLNAME}/iocage/base/${SRC_REV}-RELEASE/root/rescue
zfs create -o compression=lz4 ${POOLNAME}/iocage/base/${SRC_REV}-RELEASE/root/sbin
zfs create -o compression=lz4 ${POOLNAME}/iocage/base/${SRC_REV}-RELEASE/root/usr
zfs create -o compression=lz4 ${POOLNAME}/iocage/base/${SRC_REV}-RELEASE/root/usr/bin
zfs create -o compression=lz4 ${POOLNAME}/iocage/base/${SRC_REV}-RELEASE/root/usr/include
zfs create -o compression=lz4 ${POOLNAME}/iocage/base/${SRC_REV}-RELEASE/root/usr/lib
zfs create -o compression=lz4 ${POOLNAME}/iocage/base/${SRC_REV}-RELEASE/root/usr/lib32
zfs create -o compression=lz4 ${POOLNAME}/iocage/base/${SRC_REV}-RELEASE/root/usr/libdata
zfs create -o compression=lz4 ${POOLNAME}/iocage/base/${SRC_REV}-RELEASE/root/usr/libexec
zfs create -o compression=lz4 ${POOLNAME}/iocage/base/${SRC_REV}-RELEASE/root/usr/sbin
zfs create -o compression=lz4 ${POOLNAME}/iocage/base/${SRC_REV}-RELEASE/root/usr/share
zfs create -o compression=lz4 ${POOLNAME}/iocage/base/${SRC_REV}-RELEASE/root/usr/src

echo installing ${SRC_REV} basejail
make -i installworld DESTDIR=${IOCAGE_BASE}/iocage/base/${SRC_REV}-RELEASE/root > iocage_installworld_base.log 2>&1
cp -pv ${IOCAGE_BASE}/iocage/base/${SRC_REV}-RELEASE/root/usr/sbin/chown ${IOCAGE_BASE}/iocage/base/${SRC_REV}-RELEASE/root/usr/bin/chgrp
make distribution DESTDIR=${IOCAGE_BASE}/iocage/base/${SRC_REV}-RELEASE/root >> iocage_installworld_base.log 2>&1

echo creating new ZFS datasets for ${SRC_REV} release
zfs create -o compression=lz4 ${POOLNAME}/iocage/releases/${SRC_REV}-RELEASE
zfs create -o compression=lz4 ${POOLNAME}/iocage/releases/${SRC_REV}-RELEASE/root

echo installing ${SRC_REV} release
make installworld DESTDIR=${IOCAGE_BASE}/iocage/releases/${SRC_REV}-RELEASE/root > iocage_installworld_release.log 2>&1
make distribution DESTDIR=${IOCAGE_BASE}/iocage/releases/${SRC_REV}-RELEASE/root >> iocage_installworld_release.log 2>&1

echo setting default iocage release
iocage set release=${SRC_REV}-RELEASE default

for jail in $(iocage list | awk '{print $4}' | tail +2); do   ## new iocage = iocage list -h |awk {'print $2}'
        echo setting new release for ${jail}
        iocage set release=${SRC_REV}-RELEASE ${jail}
done

echo for jail in /iocage/jails/\*/root\; do mergemaster -U -D \$\{jail\}\; done
---snip---

Setting the release doesn't work anymore.

On every restart of the jails they were re-cloned from the base/xxx-RELEASE. Re-cloning on every start is too long, so it would make sense if it would only be re-cloned on start if release and cloned_release don't match (and I want to be able to shoot into my foot, so please don't check if it is a downgrade, or at least allow to disable the check with an option).

Any other way of doing something like this is off course welcome. My requirements are: I prepare something in pool/iocage/base or pool/iocage/releases, and I can switch from one to another by set+restart or some similar way.

Bonus points if I don't need to reverse-engineer the layout in pool/iocage/base or can even provide my own (e.g. for each dataset in base/XXX-RELEASE/*, iocage creates the corresponding cloned directories in the jail -- in this case I could even create a pure linux userland in a jail).

**Comment by skarekrow** [comment]
The support to update basejails is on GitHub, and could make your life much easier since it's just `iocage update JAIL`, but that would require you to manually recreate this as new basejails. I'll think about adding release= back in for the older basejail type you have here.

**Comment by netchild** [comment]
How would I migrate to new basejails? Creating a new jail, installing all I need and copy over the data? If yes, then support for release= would be great (and saving time). As the jails contain datasets like in pool/iocage/base/xxx-RELEASE, I could also imagine to just destroy and clone myself, but this defeats the purpose of having a tool like iocage...

**Comment by netchild** [comment]
Hi,
any news on this? The type of the jails is now "jail". iocage is at version 0.9.10.  The datasets look like this:
```
mpool/iocage/jails/mailgate
mpool/iocage/jails/mailgate/data
mpool/iocage/jails/mailgate/data/ports
mpool/iocage/jails/mailgate/root
mpool/iocage/jails/mailgate/root/bin
mpool/iocage/jails/mailgate/root/boot
mpool/iocage/jails/mailgate/root/lib
mpool/iocage/jails/mailgate/root/libexec
mpool/iocage/jails/mailgate/root/rescue
mpool/iocage/jails/mailgate/root/sbin
mpool/iocage/jails/mailgate/root/usr
mpool/iocage/jails/mailgate/root/usr/bin
mpool/iocage/jails/mailgate/root/usr/include
mpool/iocage/jails/mailgate/root/usr/lib
mpool/iocage/jails/mailgate/root/usr/lib32
mpool/iocage/jails/mailgate/root/usr/libdata
mpool/iocage/jails/mailgate/root/usr/libexec
mpool/iocage/jails/mailgate/root/usr/sbin
mpool/iocage/jails/mailgate/root/usr/share
mpool/iocage/jails/mailgate/root/usr/src
```
This matches the structure I have in mpool/iocage/base/....
I could now destroy each dataset in the jails by hand and clone from a new iocage/base, but it would be good if "iocage set release=xxx" would do the trick (ideally once by checking "zfs get origin" of the dataset, and not at each start).

Bye,
Alexander.
