### ISSUE TITLE
What can be cleaned up after update from legacy?

### ISSUE THREAD

**Issue by netchild** [iocage/iocage#426]
Hi,

after update from legacy, I see pool/iocage/.defaults and defaults.json. Is it correct that defaults.json is the new way? If yes, can the .defaults dataset be removed?

Bye,
Alexander.

**Comment by skarekrow** [comment]
Correct, the .defaults dataset can be removed if you have no desire to go backwards.

The rest of the stuff that you won't need that is left behind is mainly the ZFS properties on the jails, and the base/* datasets, but if you have created legacy basejails, I suggest keeping those.
