### ISSUE TITLE
inconsistent getlogin() from iocage

### ISSUE THREAD

**Issue by capsterx** [iocage/iocage#427]
iocage --version
Version 0.9.9.2 09/30/2017

When running 'iocage console' it changes getlogin() for the current user, but not just inside the jail.  If you just use exec, it does not change it, which causes problems for me for code that does something like:
    my $login = getlogin || getpwuid($<) || "....";
and then looks up $login, which does not exist in the jail because it's my login user outside the jail

sudo iocage create -n test -r 11.0-RELEASE vnet=on bpf=yes dhcp=on
sudo iocage start test
\# I found this in a program that was in perl, so that's what I used, 
\# but any program that calls getlogin() should be the same
sudo iocage exec test pkg bootstrap
sudo iocage exec test pkg install perl5
sudo iocage exec test -- "perl -e 'print(getlogin)'"
\> myloginuser
perl -e 'print(getlogin)'
\> myloginuser
id
\> uid=10011(myloginuser) gid=10011(myloginuser) groups=10011(myloginuser),0(wheel)
sudo iocage exec test -- id
> uid=0(root) gid=0(wheel) groups=0(wheel),5(operator)

\# run a console, which I assume calls setlogin()
echo "exit" | sudo iocage console test
sudo iocage exec test -- "perl -e 'print(getlogin)'"
\> root
perl -e 'print(getlogin)'
\> root

**Comment by skarekrow** [comment]
Have you tried using the `-U` and `-u` flags for `exec`? That should solve your inconsistency.

**Comment by capsterx** [comment]
[myloginuser@host ~]$ sudo iocage exec -u root test "perl -e 'print(getlogin)'"
myloginuser
[myloginuser@host ~]$ sudo iocage exec -U root test "perl -e 'print(getlogin)'"
myloginuser
