### ISSUE TITLE
Feature: do not re-extract and re-update an already extracted and updated release

### ISSUE THREAD

**Issue by abelbabel** [iocage/iocage#428]
Hi,

an already fetched RELEASE will be re-extracted and re-updated by default when doing

`iocage fetch --release RELEASE`

according to its output. My feature request would be to avoid this behavior by default.

Regards,
abelbabel

**Comment by skarekrow** [comment]
What would you rather see? Currently iocage is not idempotent.

**Comment by abelbabel** [comment]
It's not about the output, but about the operations in background. I would expect the "fetch" command not to do anything if there already is a zfs related to that release. Of course, these operations should be "force-able". I'm not exactly demanding "idempotence", but it's close to the direction I have in mind.

The background is that I write an ansible role to prepare a FreeBSD host for being a iocage-jail-host. Since there is no iocage-module in ansible, I use the "command"- or "shell"-module with iocage commands on the the remote site. It causes worries if a re-play of this role takes several seconds while nothing has changed ... and this is caused by "iocage fetch ..."
