### ISSUE TITLE
hostname is not set properly for old iocage_legacy master jails.

### ISSUE THREAD

**Issue by lukaszczerpak** [iocage/iocage#43]
iocage version: 0.9.6 (current master)

It looks that hostname is never set on jail boot to the value defined in hostname property:

```
root@server ~ » iocage get hostname db
db
root@server ~ » iocage exec db hostname
a07a28ae-d4f1-11e5-b13a-003048f8f8e6
root@server ~ » iocage exec db "cat /etc/rc.conf | grep hostname"
hostname="db"
```

Not sure if I missed something or it's a bug?

**Comment by skarekrow** [comment]
The property is `host_hostname`. The old iocage had a bug where we had duplicate variables, so it's a no-op now.

**Comment by lukaszczerpak** [comment]
Ok. `host_hostname` works fine - maybe this should be documented as I wasn't able to find this information anywhere.

**Comment by skarekrow** [comment]
All in due time! ;) The docs team at iX will be adding documentation to this, so don't feel bad that you missed it or anything. Right now a lot of things are hard to know, especially relating to properties.

`iocage COMMAND --help` helps a bit, but it's far from ideal. This will be solved Soon™ :D

**Comment by lukaszczerpak** [comment]
I checked how it was in the old version and IMHO the migration didn't do it well.

The old environment:

```
frodong# iocage get host_hostname db
a07a28ae-d4f1-11e5-b13a-003048f8f8e6
frodong# iocage get hostname db
db
frodong# iocage exec db hostname
db
```

The new migrated:

```
root@server ~ » iocage get host_hostname db
a07a28ae-d4f1-11e5-b13a-003048f8f8e6
root@server ~ » iocage get hostname db
db
root@server ~ » iocage exec db hostname
a07a28ae-d4f1-11e5-b13a-003048f8f8e6
```

**Comment by skarekrow** [comment]
Can you paste the jail's `rc.conf` too please? I handle this in the migration but it must not have set properly or something.

**Comment by lukaszczerpak** [comment]
In both cases it's `hostname="a07a28ae-d4f1-11e5-b13a-003048f8f8e6"` - so in the old iocage and right after the migration. 
What I shared before `hostname=db` was after manually updating `rc.conf` so please don't be confused.

**Comment by skarekrow** [comment]
Oh phew! Ok, then everything is working as intended. I just forgot to migrate the old property. Will fix :)

**Comment by lukaszczerpak** [comment]
Thank you! :)

**Comment by skarekrow** [comment]
Alright @lukaszczerpak it's been a bit, but I got around to this one, please let me know if it works for you 👍
