### ISSUE TITLE
jail start on firewalled interface might result in inaccessible jail even if it should be accessible

### ISSUE THREAD

**Issue by abelbabel** [iocage/iocage#432]
Hi,

if there is a firewall rule that restricts interface access, like (in pf):

```
block all
pass in on $external_interface from <some-servers> to $external_interface keep state
```

and you start a jail on $external_interface, the jail might be inaccessible from \<some-servers\>, because iocage creates the IP on jail start and the firewall (pf) does not "know" that this IP is related to $external_interface. `pf reload` is needed to make the jail accessible ...

To avoid this problem iocage could automatically reload the firewall rules or at least provide some informations for the user if it realizes that there could be a problem ...

For problem analyzation if pf is used the output of ``pfctl -sr`` or a related command might be useful.

Regards,
abelbabel

**Comment by skarekrow** [comment]
Everybody likes a different firewall, as iocage is a jail manager, any firewall operations it might use would be very basic for the plugins to nat network for ease of use through anchors.

Reloading a firewall is way out of scope for this project. I can imagine the myriad of ways things can go wrong ;)

**Comment by abelbabel** [comment]
OK, but maybe iocage can give a hint/some information, if it realizes that a firewall is activated?

**Comment by skarekrow** [comment]
The admin should know if a firewall is active, as that gives a false sense of security from iocage's POV. You could have a firewall in front of the host for instance.
