### ISSUE TITLE
ImportError: Shared object "libgit2.so.25" not found, required by "_pygit2.so" 

### ISSUE THREAD

**Issue by kitten77** [iocage/iocage#437]
root@gaia:/home/muad # iocage clone AkvariumNorge
chroot: /bin/sh: No such file or directory <-- huh??? 
f74f1f78-6acd-4950-8370-11482393e2b0 successfully cloned!
root@gaia:/home/muad # iocage -v
Version 0.9.9.2 09/30/2017
root@gaia:/home/muad # cd python/
dir_walker/        django_greenhouse/ idea/              ipv6/              master.zip         pigpio-master/     template_launcher/ tux_upload*        watcher/           webhotell_req.txt  
django/            greenhouse/        iocage/            jail_mngr/         organizer/         suorganizer/       tux_hotell/        tuxlab/            webhotell/         
root@gaia:/home/muad # cd python/iocage/
root@gaia:/home/muad/python/iocage # source ../../virtualenv/webhotell/bin/activate.csh 
[webhotell] root@gaia:/home/muad/python/iocage # make install
echo -e "import os\ntry:\n  if not os.listdir('/usr/src'): exit('/usr/src must be populated!')\nexcept FileNotFoundError:\n  exit('/usr/src must be populated!')" | python3.6
test -d .git && git pull || true
remote: Counting objects: 50, done.
remote: Compressing objects: 100% (6/6), done.
remote: Total 50 (delta 41), reused 47 (delta 41), pack-reused 3
Unpacking objects: 100% (50/50), done.
From https://github.com/iocage/iocage
   3274e18..7783dd6  master              -> origin/master
   3274e18..7783dd6  freenas/11.0-stable -> origin/freenas/11.0-stable
   3274e18..7783dd6  freenas/11.1-stable -> origin/freenas/11.1-stable
   3274e18..7783dd6  freenas/master      -> origin/freenas/master
   3274e18..d8aa944  rework-lib          -> origin/rework-lib
Updating 3274e18..7783dd6
Fast-forward
 iocage/cli/upgrade.py     |   1 -
 iocage/lib/ioc_fetch.py   |  16 +++++++++++-----
 iocage/lib/ioc_json.py    |   2 +-
 iocage/lib/ioc_list.py    |  61 +++++++++++++++++++++++++++++++++++++++++++++----------------
 iocage/lib/ioc_upgrade.py | 130 ++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++--
 iocage/lib/iocage.py      |  85 ++++++++++++++++++++++++++++++++++++++++++++++++++++++-------------------------------
 6 files changed, 239 insertions(+), 56 deletions(-)
python3.6 -m ensurepip
Requirement already satisfied: setuptools in /usr/home/muad/virtualenv/webhotell/lib/python3.6/site-packages
Requirement already satisfied: pip in /usr/home/muad/virtualenv/webhotell/lib/python3.6/site-packages
pip3.6 install -U Cython
Requirement already up-to-date: Cython in /usr/home/muad/virtualenv/webhotell/lib/python3.6/site-packages
cd py-libzfs && python3.6 setup.py build && python3.6 setup.py install
running build
running build_py
running build_ext
skipping 'libzfs.c' Cython extension (up-to-date)
running install
running build
running build_py
running build_ext
skipping 'libzfs.c' Cython extension (up-to-date)
running install_lib
running install_egg_info
Removing /usr/home/muad/virtualenv/webhotell/lib/python3.6/site-packages/libzfs-1.0-py3.6.egg-info
Writing /usr/home/muad/virtualenv/webhotell/lib/python3.6/site-packages/libzfs-1.0-py3.6.egg-info
pkg install -q -y libgit2
New version of pkg detected; it needs to be installed first.
pip3.6 install -U .
Processing /usr/home/muad/python/iocage
Requirement already up-to-date: click==6.7 in /usr/home/muad/virtualenv/webhotell/lib/python3.6/site-packages (from iocage==0.9.10rc0)
Requirement already up-to-date: texttable==0.9.0 in /usr/home/muad/virtualenv/webhotell/lib/python3.6/site-packages (from iocage==0.9.10rc0)
Requirement already up-to-date: requests==2.17.3 in /usr/home/muad/virtualenv/webhotell/lib/python3.6/site-packages (from iocage==0.9.10rc0)
Requirement already up-to-date: coloredlogs==7.0 in /usr/home/muad/virtualenv/webhotell/lib/python3.6/site-packages (from iocage==0.9.10rc0)
Requirement already up-to-date: verboselogs==1.6 in /usr/home/muad/virtualenv/webhotell/lib/python3.6/site-packages (from iocage==0.9.10rc0)
Requirement already up-to-date: pygit2==0.25.1 in /usr/home/muad/virtualenv/webhotell/lib/python3.6/site-packages (from iocage==0.9.10rc0)
Requirement already up-to-date: cffi==1.9.1 in /usr/home/muad/virtualenv/webhotell/lib/python3.6/site-packages (from iocage==0.9.10rc0)
Requirement already up-to-date: libzfs in /usr/home/muad/virtualenv/webhotell/lib/python3.6/site-packages (from iocage==0.9.10rc0)
Requirement already up-to-date: urllib3<1.22,>=1.21.1 in /usr/home/muad/virtualenv/webhotell/lib/python3.6/site-packages (from requests==2.17.3->iocage==0.9.10rc0)
Requirement already up-to-date: idna<2.6,>=2.5 in /usr/home/muad/virtualenv/webhotell/lib/python3.6/site-packages (from requests==2.17.3->iocage==0.9.10rc0)
Requirement already up-to-date: chardet<3.1.0,>=3.0.2 in /usr/home/muad/virtualenv/webhotell/lib/python3.6/site-packages (from requests==2.17.3->iocage==0.9.10rc0)
Requirement already up-to-date: certifi>=2017.4.17 in /usr/home/muad/virtualenv/webhotell/lib/python3.6/site-packages (from requests==2.17.3->iocage==0.9.10rc0)
Requirement already up-to-date: humanfriendly>=3.2 in /usr/home/muad/virtualenv/webhotell/lib/python3.6/site-packages (from coloredlogs==7.0->iocage==0.9.10rc0)
Requirement already up-to-date: six in /usr/home/muad/virtualenv/webhotell/lib/python3.6/site-packages (from pygit2==0.25.1->iocage==0.9.10rc0)
Requirement already up-to-date: pycparser in /usr/home/muad/virtualenv/webhotell/lib/python3.6/site-packages (from cffi==1.9.1->iocage==0.9.10rc0)
Installing collected packages: iocage
  Found existing installation: iocage 0.9.10rc0
    Uninstalling iocage-0.9.10rc0:
      Not removing or modifying (outside of prefix):
      /usr/local/share/zsh/site-functions/_iocage
      /usr/local/etc/rc.d/iocage
      /usr/local/man/man8/iocage.8.gz
      Successfully uninstalled iocage-0.9.10rc0
  Running setup.py install for iocage ... done
Successfully installed iocage-0.9.10rc0
-- KABOOM ¤#"%#"% thank god it is holiday soon... 
[webhotell] root@gaia:/home/muad/python/iocage # iocage -v
Traceback (most recent call last):
  File "/usr/home/muad/virtualenv/webhotell/bin/iocage", line 6, in <module>
    from iocage.main import cli
  File "/usr/home/muad/virtualenv/webhotell/lib/python3.6/site-packages/iocage/main.py", line 33, in <module>
    import iocage.lib.ioc_check as ioc_check
  File "/usr/home/muad/virtualenv/webhotell/lib/python3.6/site-packages/iocage/lib/ioc_check.py", line 30, in <module>
    import iocage.lib.ioc_common
File "/usr/home/muad/virtualenv/webhotell/lib/python3.6/site-packages/iocage/lib/ioc_common.py", line 35, in <module>
    import pygit2
  File "/usr/home/muad/virtualenv/webhotell/lib/python3.6/site-packages/pygit2/__init__.py", line 32, in <module>
    from _pygit2 import *
#gaia.g.l9.1 ImportError: Shared object "libgit2.so.25" not found, required by "_pygit2.so"
[webhotell] root@gaia:/home/muad/python/iocage#

**Comment by kitten77** [comment]
[webhotell] root@gaia:/home/muad/python/iocage # pip install pygit2 -U
Collecting pygit2
  Downloading pygit2-0.26.2.tar.gz (460kB)
    100% |################################| 471kB 2.7MB/s 
Collecting cffi (from pygit2)
  Downloading cffi-1.11.2.tar.gz (435kB)
    100% |################################| 440kB 2.9MB/s 
Requirement already up-to-date: six in /usr/home/muad/virtualenv/webhotell/lib/python3.6/site-packages (from pygit2)
Requirement already up-to-date: pycparser in /usr/home/muad/virtualenv/webhotell/lib/python3.6/site-packages (from cffi->pygit2)
Installing collected packages: cffi, pygit2
  Found existing installation: cffi 1.9.1
    Uninstalling cffi-1.9.1:
      Successfully uninstalled cffi-1.9.1
  Running setup.py install for cffi ... done
  Found existing installation: pygit2 0.25.1
    Uninstalling pygit2-0.25.1:
      Successfully uninstalled pygit2-0.25.1
  Running setup.py install for pygit2 ... done
Successfully installed cffi-1.11.2 pygit2-0.26.2
[webhotell] root@gaia:/home/muad/python/iocage # iocage -v
Version 0.9.10 RC

**Comment by skarekrow** [comment]
This looks like a host issue with a corrupt pygit2 installation, not an iocage bug.

As for the /bin/sh thing, I suspect you don't have some datasets mounted.
