### ISSUE TITLE
"iocage update" does unexpected pattern matching on jail name

### ISSUE THREAD

**Issue by abelbabel** [iocage/iocage#438]
Hi,

with iocage 0.9.9.2 09/30/2017

`iocage update test`

complains about multiple jails and exits without performing an update of jail "test" if there are for example jails with the names "test", "test1" and "test2". Updating of jail "test" is impossible this way.

Regards,
abelbabel

**Comment by skarekrow** [comment]
Duplicate of https://github.com/iocage/iocage/issues/419

**Comment by abelbabel** [comment]
Whoops. The first time I didn't search for an existing issue before creating a new issue and ... hit ... duplicate ... Sorry!
