### ISSUE TITLE
"iocage create" fails with non-sense error when creating jail with existing name

### ISSUE THREAD

**Issue by abelbabel** [iocage/iocage#439]
Hi,

with iocage 0.9.9.2 09/30/2017 the following might happen:

```
# iocage create -n test -t template
test successfully created!
# iocage create -n test -t template
Template: template not found!
Created Templates:
  template
```

The error message should be different; like: "jail test already exists" ...

Regards,
abelbabel

**Comment by skarekrow** [comment]
Duplicate of https://github.com/iocage/iocage/issues/414

Please search :)

**Comment by abelbabel** [comment]
Sorry for the duplicates!
