### ISSUE TITLE
Question: What is `config.json` file for?

### ISSUE THREAD

**Issue by lukaszczerpak** [iocage/iocage#44]
iocage version: 0.9.6 (current master)

I noticed that during the migration from the old iocage, every jail got `config.json` file created. But as per my tests, the file is ignored by the new iocage and zfs properties are used to store/read the configuration.

Can the file be deleted or it's needed for something else?

**Comment by skarekrow** [comment]
No that is the actual jail configuration now. We use a JSON file instead of the ZFS props. The properties had the downside of being quite slow with the number we added. If you delete that, it will recreate it based on your ZFS props.

**Comment by lukaszczerpak** [comment]
Thanks! That's all clear now :)

**Comment by skarekrow** [comment]
Awesome!
