### ISSUE TITLE
Error building iocage :  "You need a compatible libgit2 version (v0.25.x)" 

### ISSUE THREAD

**Issue by cneira** [iocage/iocage#444]
I'm trying to build iocage from master but the version of libgit2 in 11.1-RELEASE  is the following. 

-  libgit2-0.26.0                 Portable, pure C implementation of the Git core

So when trying to build iocage it errors out.

```bash
src/types.h:36:2: error: You need a compatible libgit2 version (v0.25.x)
    #error You need a compatible libgit2 version (v0.25.x)
     ^
    1 error generated.
    error: command 'cc' failed with exit status 1

    ----------------------------------------
  Rolling back uninstall of pygit2
Command "/usr/local/bin/python3.6 -u -c "import setuptools, tokenize;__file__='/tmp/pip-build-hnv5u2q1/pygit2/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-1e6j74sa-record/install-record.txt --single-version-externally-managed --compile" failed with error code 1 in /tmp/pip-build-hnv5u2q1/pygit2/
```

**Comment by skarekrow** [comment]
The version in 11.1-RELEASE will always be changing as the port gets bumped. So you can do `pip3.6 install pygit2==0.26.0` and iocage will use that, or you can build the older version on your machine. I plan on ripping out the libgit2 stuff, so bear with me on this ;)
