### ISSUE TITLE
Does order of ip addresses in ip4_addr matter?

### ISSUE THREAD

**Issue by lukaszczerpak** [iocage/iocage#45]
iocage version: 0.9.6 (current master)

One of my jails has two ipv4 addresses assigned:

```
iocage set ip4_addr="lo1|192.168.10.10/24,lo1|192.168.10.20/24" mail
```

The order in the configuration can be different, but in the jails' system order is always the same (`192.168.10.20` is always listed first):

```
root@mail:~ # ifconfig
lo1: flags=8049<UP,LOOPBACK,RUNNING,MULTICAST> metric 0 mtu 16384
        options=600003<RXCSUM,TXCSUM,RXCSUM_IPV6,TXCSUM_IPV6>
        inet 192.168.10.20 netmask 0xffffff00
        inet 192.168.10.10 netmask 0xffffff00
```

Is it possible to enforce which one is primary (or default for local connections)?

In the previous version order in the system was the same like in the configuration.

EDIT: The reason of asking about this is that in my DMZ only one of those ip addresses is allowed to connect to other services like databases. If order of ip addresses changes in the system, then it brea ks all the communication.

**Comment by skarekrow** [comment]
Hmm, can you paste the `ifconfig` from the old jail to illustrate what you're describing? I'm not aware of a way to set a primary IP when dealing with aliases like this. There shouldn't be a difference as the same method to assign IP addresses is used (sending it to `jail` to deal with)

**Comment by lukaszczerpak** [comment]
Now I don't have an access to the old system as both production and lab are migrated. But I will try to reproduce it tomorrow. 

It's not copy/paste, but it was like this:

```
root@mail:~ # ifconfig
lo1: flags=8049<UP,LOOPBACK,RUNNING,MULTICAST> metric 0 mtu 16384
        options=600003<RXCSUM,TXCSUM,RXCSUM_IPV6,TXCSUM_IPV6>
        inet 192.168.10.10 netmask 0xffffff00
        inet 192.168.10.20 netmask 0xffffff00
```

**Comment by lukaszczerpak** [comment]
@on the new system I tried to use different ordering but always ended up with the same (wrong one). After setting `ip4_addr` many many times to different combinations, I got it finally working. I know that it sounds weird, maybe I should restart the machine and start from scratch. 
I will test it tomorrow.

**Comment by skarekrow** [comment]
Ok, was just making sure we're on the same page. So you're saying that the first IP is what the jail is using by default? And the configuration order does not matter, `20` will always be first?

Interesting as like I said there truly shouldn't be a difference.

Haha as I typed this I see your new comment, I will wait for tomorrow to see what you have to say, then dive in and see what exactly is going on if there is something.

**Comment by lukaszczerpak** [comment]
I've tested it multiple times with different order and wasn't able to reproduce the issue I outlined yesterday. Maybe my system just had to be restarted ;) All works as expected for now. Sorry for a confusion.

**Comment by skarekrow** [comment]
Ha! Well at least this is documented for any person in the future.
