### ISSUE TITLE
ZFS datasets mounted to incorrect location

### ISSUE THREAD

**Issue by johnramsden** [iocage/iocage#453]
When I set up jailed datasets on FreeNAS, and mount the jail data sets inside of my created jail, I'm able to create and manage them, but they are mounted to the wrong location. For whatever reason they are being mounted with a parent ```/mnt``` directory. I have not experienced this behavior when using Iocage cage on regular FreeBSD.

- [x] iocage --version: Version 0.9.10 RC

- [x] Output from the commands issued:

Outside jail:

```
[root@host]#  iocage set jail_zfs=on jail_zfs_dataset=data/unifi jail_zfs_mountpoint='none' unifi
Property: jail_zfs has been updated to on    
Property: jail_zfs_dataset has been updated to data/unifi                                  
Property: jail_zfs_mountpoint has been updated to none
```

Inside jail:

```
[root@unifi]#  zfs create -o mountpoint=/usr/local/share/java/unifi tank/data/unifi/data
[root@unifi]#  zfs mount                                                                   
tank/iocage/jails/unifi/root    /                                                          
tank/data/unifi/data            /mnt/usr/local/share/java/unifi
```

- [x] Expected output

I would have expected my data set to be mounted to the location specified by the `mountpoint` property inside of the jail.

**Comment by skarekrow** [comment]
This is because FreeNAS uses an altroot for the zpool import. So that will always be prepended.

**Comment by johnramsden** [comment]
@skarekrow That puts the datasets in the wrong place inside the jail though. Is there a workaround to put the datasets in the correct place?

**Comment by skarekrow** [comment]
I'll peek to see if there's anything we can do , but I don't think there is :(

**Comment by johnramsden** [comment]
@skarekrow That would be great. nullfs mounts for now I guess.

**Comment by skarekrow** [comment]
I cannot find a way to not apply the altroot to a jailed dataset with zfs. I'll keep this open for a little bit to see if I can poke some people who might have an idea.

**Comment by drphilth** [comment]
Just a note that this breaks poudriere in a jail on FreeNAS - poudriere is able to successfully create a zfs dataset but it ends up mounted in an unexpected location (extra /mnt/ prepended) so the tool fails.

**Comment by vongrippen** [comment]
A workaround that I've been using for this is to export, then reimport my zpool without the altroot. It doesn't seem to cause any issues with FreeNAS (provided you don't have any datasets with mountpoints that overlap the system) and solves my poudriere problems.

All it takes is:
`zpool export tank`
`zpool import tank`

**Comment by ohmantics** [comment]
This is still a problem with FreeNAS 11.3-U5.

**Comment by sonicaj** [comment]
@ohmantics can you please create an issue at https://jira.ixsystems.com ? And please attach a debug of the system as well ( System -> Advanced ). Thank you
