### ISSUE TITLE
Cannot upgrade a 11.0 jail to 11.1-RELEASE

### ISSUE THREAD

**Issue by billybigrigger** [iocage/iocage#454]
Version 0.9.9.2 09/30/2017

iocage clone mail --name mail-test1
iocage upgrade -r 11.1-RELEASE mail-test1

then i get this output that just endlessly loops...

No updates are available to install.
Run '/tmp/tmpkqnbjb0l fetch' first.

maybe iocage tries to update pkgs first? in which it would fail because 11.0 is EOL?

**Comment by skarekrow** [comment]
Old bug :)

Duplicate of https://github.com/iocage/iocage/issues/397

**Comment by billybigrigger** [comment]
so what is a guy to do? the latest pkg available in 11.1-RELEASE is 0.9.9.2
