### ISSUE TITLE
Wrong frame/line generation at narrow terminal sizes

### ISSUE THREAD

**Issue by fbruetting** [iocage/iocage#458]
- v0.9.9.1

When I hit `iocage list` on a narrow termanal, I get the following result. My Terminal (Tilix) doesn’t make linefeeds and instead wraps around – is there still a way to detect this and configure the frames/lines appropriately?

Btw: Do you like to change `IP4` to `IPv4`? ^^

```
# iocage list
**********************************************************************
**********
fdescfs(5) is not mounted, performance  may suffer. Please run:
mount -t fdescfs fdesc /dev/fd
You can also permanently mount it in /etc/fstab with the following ent
ry:
fdesc /dev/fd  fdescfs  rw  0  0
**********************************************************************
**********

+-----+------+-------+---------+-----+
| JID | NAME | STATE | RELEASE | IP4 |
+=====+======+=======+=========+=====+
+-----+------+-------+---------+-----+
```

**Comment by skarekrow** [comment]
I can look into it :)

As for the IP4 to IPv4, it's like that for legacy reasons and the fact that our properties are ip4.addr and ip6.addr. The v is just an extra character we don't quite need ;)
