### ISSUE TITLE
fetch: Just download necessary parts of FreeBSD

### ISSUE THREAD

**Issue by fbruetting** [iocage/iocage#459]
I haven’t installed `doc` nor `src` on my host machine. Still `iocage` downloads these parts, but then remarks:

```
* Updating 11.1-RELEASE to the latest patch level...
src component not installed, skipped
[…]
doc component not installed, skipped
````

Would be cool if those won’t get downloaded in the first place (and get installed, as soon as they’re required).

And a big thanks for your work on iocage!

**Comment by skarekrow** [comment]
This is odd as both doc and src should be downloaded when you fetch a RELEASE. The docs package is incredibly small, and quite useful. src is required for basejails and such. On a modern system the cost of these are usually negligible.

**Comment by fbruetting** [comment]
So this would/could lead to issues, if I use base jails? If yes, will I get prompted because of this, or do the jails directly run into problems?

Regarding the space… on my vServer I don’t have that much diskspace, so I’d rather like to use it for actual data when I don’t need doc/src really. :)

**Comment by fbruetting** [comment]
In [this tutorial](https://dan.langille.org/2015/03/07/getting-started-with-iocage-for-jails-on-freebsd/) you actually see, that src wasn’t downloaded by iocage two years ago… I guess it adapted the system settings back then.

**Comment by skarekrow** [comment]
That is a very old version linked there, src.txz is required if you want to be able to upgrade your basejail.

**Comment by skarekrow** [comment]
Here I already implemented this and forgot :D

`iocage fetch -F foo.txz -F bar.txz` and you'll only grab foo and bar.txz from the server. So you will manually have to do this for each RELEASE you fetch as the default is to grab doc and src.
