### ISSUE TITLE
How to install from source?

### ISSUE THREAD

**Issue by oliverangelil** [iocage/iocage#46]
Apologies for the noob question. As a noob, I usually install packages with "pkg install <name>". It was easy to install it with `pkg install py27-iocage-0.9.4` on Freebsd V12. But for some reason there are no python iocages in pkg on FreeBSD V11 (also after updating pkg with `pkg update`)

To try to install 0.9.6 from source I first got the stuff from githup:
`git clone https://github.com/iocage/iocage`

Then I thought I would go into iocage/doc and run:
`make install clean` because there is a "Makefile" in there. But this didn't work, with the error: 
> make: don't know how to make install. Stop

Maybe you could add a line to the README.md on how to install it from source; or just let me know here ;)

Thanks.

**Comment by tykling** [comment]
just install the port: https://www.freebsd.org/doc/handbook/ports-using.html
basically run portsnap fetch extract, go into /usr/ports/sysutils/py-iocage and run "make install clean"

**Comment by jungle-boogie** [comment]
```
If cloning the repo directly:

cd into the cloned directory and run pip3 install . as root.
To install subsequent updates: git pull and pip3 install -U .
```

**Comment by skarekrow** [comment]
It's on the `README` ;)

But you will need to install `python36` with `pkg` and then run `python-3.6 -m ensurepip` to get `pip3`. 

I manually symlink 3.6 to `python3` so I don't have to type that each time. 

Hope that helps, I'll close this but feel free to continue asking.
