### ISSUE TITLE
Proper way to "rebase" jails?

### ISSUE THREAD

**Issue by fengsi** [iocage/iocage#461]
I noticed that all my previous basejails were converted to clones with the "basejail" flag.  If I understand correctly, the "basejail" flag tells iocage to mount `fstab` using nullfs, replacing certain structure (e.g., sys binaries). But essentially, except for the `basejail` flag, a basejail is no different than a cloned jail.  This approach is different from that of old iocage.

These basejails were cloned from `POOL/iocage/base/11.0-RELEASE@jailname`.  The `base` seems to be the old structure.  All new releases are now under `POOL/iocage/releases/`.

I was wondering, is there a proper way to somehow "rebase" those clones?  I'd like to "rebase" my basejails to `POOL/iocage/releases/11.1-RELEASE`, and then destroy `POOL/iocage/base/11.0-RELEASE`.

Not sure if that's possible?

**Comment by fengsi** [comment]
So I was able to rename the dataset from `POOL/iocage/base/11.0-RELEASE` to `POOL/iocage/releases/11.0-RELEASE`.  Not sure how to "rebase" the snapshot of each jail though.

**Comment by skarekrow** [comment]
It's not possible. But also not required unless you wish to destroy the old RELEASE. I have some ideas to make this better, so I'll add this as an enhancement to see if they pan out. 

But if you don't care about keeping the old RELEASE dataset around, simply issuing `iocage upgrade` will allow your basejails to inherit from the new release.

**Comment by fengsi** [comment]
Yeah, they are now all upgraded to `11.1-RELEASE`.  I do seek a way to destroy the old `11.0-RELEASE` dataset, and I don't mind "rebasing" it myself, but it seems to be a limitation of `zfs`?  I didn't find anything about `zfs` rebase.

Ideally, I'd like to:
1. make a snapshot of the jail, say `POOL/iocage/jails/foo@now`, which was inherited from say `POOL/iocage/releases/11.0-RELEASE@foo`
2. make a snapshot of the latest `RELEASE` dataset, say `POOL/iocage/releases/11.1-RELEASE@foo`
3. "rebase" it just like git: `zfs rebase POOL/iocage/jails/foo@now POOL/iocage/releases/11.1-RELEASE@foo`
4. destroy `POOL/iocage/releases/11.0-RELEASE`
5. destroy `POOL/iocage/jails/foo@now`

**Comment by gronke** [comment]
The idea of rebasing ZFS does not work because the two release datasets were created independently. The jail is literally cloned from the release, so destroying the origin would also affect the jails created from it.

The rsync `--compare-dest` option can resolve this problem. When a new jail  is created from release `11.1-RELEASE` the difference between the old jail and its origin snapshot can be transferred to the new jail.

**Comment by fengsi** [comment]
@gronke thanks for the info!  The solution you proposed is exactly what I'm looking for.
@skarekrow would it be possible to automate above process and make it into a "rebase" command or something?

Another issue I had was migrating jails between hosts.  It is common to have multiple jails created (cloned) at different times, w/ parents at different release patches.  It doesn't seem to be a problem locally, but when migrating jails to another host, their parents are also transferred and recreated when necessary.  Their parents share the same dataset name, while at different snapshots.  This leads to conflict.  I was able to manually make it work eventually, but it was nightmare, especially when you have a deadline to migrate.  I'd hope that the "rebase" feature might make it easier to migrate between hosts.

**Comment by gronke** [comment]
@fengsi it is not a requirement that a jail has an origin dataset. If you decide to move it to another host, just create a new jail with the same name and rsync the content of `config.json`, `fstab` and `root/` over to the new one. Usually the export/import feature can be used for this.
