### ISSUE TITLE
Upgraded to 9.10 and can't stop or list jails

### ISSUE THREAD

**Issue by billybigrigger** [iocage/iocage#462]
Make sure to follow and check these boxes before submitting an issue! Thank you.

- [x] Supply `iocage --version`
- [ ] Supply the commands used, along with any steps to recreate it.
- [ ] Provide the output from the command you issued.
- [ ] Supply what you expected the result or output to be
- [ ] Checked that the problem has not already been fixed on `master` if using
 a stable release.

**Comment by reelsense** [comment]
Please write a comment or question in the comment box.

**Comment by skarekrow** [comment]
Without a traceback or any information at all, this can't be fixed. I'm not psychic ;)
