### ISSUE TITLE
A template by that name already exists

### ISSUE THREAD

**Issue by francisco1844** [iocage/iocage#467]
Make sure to follow and check these boxes before submitting an issue! Thank you.

- [x] Supply `iocage --version`

Version 0.9.10 2017/12/22

- [x] Supply the commands used, along with any steps to recreate it.
iocate stop template_jail
iocage set template=yes template_jail <-- get the error

- [x] Provide the output from the command you issued.
A template by that name already exists

- [x] Supply what you expected the result or output to be
Expected jail to become a template.

- [x] Checked that the problem has not already been fixed on `master` if using
 a stable release.

Asked in google group and Brandon recommended to try a reboot to see if that fixed the issue. Reboot did not help.

https://groups.google.com/forum/#!topic/iocage/S7E_TNJyvBM

Additional info:
I had a working template which I wanted to upgrade so I made the template a normal jail. The update failed[1] so I tried to set template flag for the jail, but it failed complained that the template already exited.

iocage set template=no template_jail
iocate start template_jail
iocage update  template_jail <-- failed.. so let's mark it back as a template [1]
iocate stop template_jail
iocage set template=yes template_jail <-- get the error
A template by that name already exists

#iocage list
+-----+---------------+-------+--------------+-----------------+
| JID |     NAME      | STATE |   RELEASE    |       IP4       |
+=====+===============+=======+==============+=================+
+-----+---------------+-------+--------------+-----------------+
| -   | template_jail | down  | 11.1-RELEASE | IP HERE         |
+-----+---------------+-------+--------------+-----------------+

#iocage set template=yes template_jail
A template by that name already exists!

#iocage list -t
+-----+------+-------+---------+-----+
| JID | NAME | STATE | RELEASE | IP4 |
+=====+======+=======+=========+=====+
+-----+------+-------+---------+-----+ <--- nothing listed. No templates

Don't see how converting jail to template is failing since there is no other template, with that name or otherwise.

[1] After upgrading to version Version 0.9.10 that issue was resolved

**Comment by francisco1844** [comment]
What I am experiencing sounds a lot like [issue 452](https://github.com/iocage/iocage/issues/452), but not quite sure if same issue. I don't get a python crash as in that ticket, but the error at the end is the same:
A template by that name already exists!

**Comment by francisco1844** [comment]
Looked at other tickets. It also seems like [issue 417](https://github.com/iocage/iocage/issues/417) may also be related.

Potentially [issue 422](https://github.com/iocage/iocage/issues/422) may also be related.

**Comment by skarekrow** [comment]
This does look related to #452 so I'll mark this as a dupe
