### ISSUE TITLE
Creating 32-bit jails?

### ISSUE THREAD

**Issue by asomers** [iocage/iocage#469]
Is there a recommended way to create a 32-bit jail on a 64-bit host?  By that, I mean a jail with an i386 world using an amd64 host.  I could probably do it by creating an empty jail and then doing an installworld into it, but that would be a pain.  It would be easier if iocage could use the i386 release files directly.

**Comment by skarekrow** [comment]
Not currently, but I can add support to `create` and `fetch` for this.

**Comment by ipadalko** [comment]
Hi! I would vote for this enhancement. It would be very useful for testing 32bit applications. 
Could you, please, implement this?
