### ISSUE TITLE
Errors with 'iocage exec' vs. 'jexec'

### ISSUE THREAD

**Issue by tehfink** [iocage/iocage#475]
Sorry if this has been already addressed, but I couldn't find anything aside from:
https://github.com/iocage/iocage/issues/17

Using the iocage pkg:
```
iocage --version
Version 0.9.10 2017/12/22
```
Using a brand new jail, this doesn't work:
```
# iocage exec crt openssl dhparam -out test.pem 1024
jexec: t: no such user
True
```
But this does:
```
# jexec 3 openssl dhparam -out test.pem 1024
Generating DH parameters, 1024 bit long safe prime, generator 2
This is going to take a long time
...........................................+..................................................................................+.......................................................................................+............................................................+....+............................+..............+............+......+............................+....................+.+........................................................+.........+............................................+..................+.........................................................................+................+.......................+.........+............+.....+....................................................+....+.................+.......................................+......................................................................+....................................................................................+..........+...........................................................+......................................................++*++*++*
```

**Comment by skarekrow** [comment]
So the issue here is that `exec` has a `-u` flag, and thus sees this as a param :)

So like most unix utilities, this is how you avoid that - `iocage exec foo -- openssl dhparam -out test.pem 1024`

**Comment by tehfink** [comment]
Thanks! Do you think this is a good topic for the docs? Had I seen it, it would have saved some time that went to writing a script to parse `jls` in order to use `jexec` instead…

**Comment by skarekrow** [comment]
Perhaps, this is a pretty standard thing to do with most cli utilities, but I suppose it can slip the mind when you're in "Get it done" mode :D

I'll assign this to @Mrt134 to include in the `exec` portion 👍

**Comment by gronke** [comment]
Another option is to enforce the exec flags before specifying the jail, so that only flags before the jail name modify the exec behavior and everything else is passed to jexec.

```iocage exec -u myuser <JAIL> <COMMAND>```
