### ISSUE TITLE
Jail already exists but iocage list doesn't show it

### ISSUE THREAD

**Issue by ghost** [iocage/iocage#477]
Make sure to follow and check these boxes before submitting an issue! Thank you.

- [x] Supply `iocage --version`
1.0 ALPHA (d93a100f37695709909969a8819eceaa5e351bcc)

- [x] Supply the commands used, along with any steps to recreate it.
Migrate a legacy jail
Rename jail
Delete jail
Try to create a new jail with the same name

```
root@beastie:~/src/iocage # iocage create -r 11.1-RELEASE --name sab ; iocage list
Jail: sab already exists!
+-----+------+-------+--------------+------------+
| JID | NAME | STATE |   RELEASE    |    IP4     |
+=====+======+=======+==============+============+
| 18  | plex | up    | 11.0-RELEASE | 10.1.1.252 |
+-----+------+-------+--------------+------------+
```

- [x] Provide the output from the command you issued.
- [x] Supply what you expected the result or output to be
Jail created successfully
- [x] Checked that the problem has not already been fixed on `master` if using
 a stable release.

**Comment by kitten77** [comment]
I have seen this before, you have had a sab jail installed once and the delete command leaves a zfs mount.
root@beastie# zfs list |grep sab 

If I am correct the sab will show up there ?

**Comment by skarekrow** [comment]
This may have been fixed by https://github.com/iocage/iocage/commit/54cb6089a24c8b8b00169b874411e4e141d83efc @voltageex can you confirm?

**Comment by ghost** [comment]
I'm sorry - to fix the other issue I had, I went back to the ports version.

**Comment by skarekrow** [comment]
No problem! I'll close this out as a bug that's fixed until proven otherwise:D
