### ISSUE TITLE
Missing most commands - only migrate and snapremove are available

### ISSUE THREAD

**Issue by ghost** [iocage/iocage#478]
Make sure to follow and check these boxes before submitting an issue! Thank you.

- [x] Supply `iocage --version`
- [x] Supply the commands used, along with any steps to recreate it.
- [x] Provide the output from the command you issued.
- [x] Supply what you expected the result or output to be
- [x] Checked that the problem has not already been fixed on `master` if using
 a stable release.

This seems similar to #177 

```
root@beastie:~/src/iocage # git log
commit d93a100f37695709909969a8819eceaa5e351bcc
```

```
Installing collected packages: iocage
  Running setup.py install for iocage ... done
Successfully installed iocage-1.0a0
root@beastie:~/src/iocage #
root@beastie:~/src/iocage # iocage
Usage: iocage [OPTIONS] COMMAND [ARGS]...

  A jail manager.

Options:
  -v, --version  Display iocage's version and exit.
  -f, --force    Allow iocage to rename datasets.
  --help         Show this message and exit.

Commands:
  migrate     Migrate all iocage_legacy develop basejails...
  snapremove  Remove specified snapshot of a jail.
```

**Comment by skarekrow** [comment]
Same answer too :(

How did you install this? It looks to be a corrupt install.

**Comment by ghost** [comment]
make install from a git clone. make uninstall isn't helping.

**Comment by skarekrow** [comment]
Try doing a `pip3.6 uninstall iocage` and make sure it's not also installed via pkg.
