### ISSUE TITLE
freebsd upgrade -r 11.1-RELEASE

### ISSUE THREAD

**Issue by kitten77** [iocage/iocage#479]
root@gaia:/home/muad/python/iocage # iocage --version
Version 1.0 ALPHA

root@gaia:/home/muad/python/iocage # iocage upgrade -r 11.1-RELEASE thunderdome
Traceback (most recent call last):
  File "/usr/local/bin/iocage", line 10, in <module>
    sys.exit(cli())
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/iocage/cli/upgrade.py", line 39, in cli
    ioc.IOCage(jail=jail, skip_jails=True).upgrade(release)
  File "/usr/local/lib/python3.6/site-packages/iocage/lib/iocage.py", line 1793, in upgrade
    conf, release, root_path).upgrade_basejail()
  File "/usr/local/lib/python3.6/site-packages/iocage/lib/ioc_upgrade.py", line 216, in upgrade_basejail
    silent=True).json_set_value(f"release={new_release}")
  File "/usr/local/lib/python3.6/site-packages/iocage/lib/ioc_json.py", line 723, in json_set_value
    value, conf = self.json_check_prop(key, value, conf)
TypeError: 'NoneType' object is not iterable

**Comment by skarekrow** [comment]
Hey Kitten :)

I need more details then this unfortunately. It seems you're using basejails, but from that error I cannot tell which kind. How/when was the jail created, along with what does `mount` show

**Comment by kitten77** [comment]
long time no see :) 

Sure I will find how it is being created and mount 
[10:20:16 30/01-18] jails info: adding thunderdome
[10:20:16 30/01-18] jails command: : iocage create -b -r 11.0-RELEASE -n thunderdome  ip6_addr=XX:XX:XX:XX host_hostname=thunderdome boot=on
[10:20:20 30/01-18] jails out: thunderdome successfully created!
root@gaia:/home/muad # mount |grep thunderdome
gaia/iocage/jails/thunderdome on /iocage/jails/thunderdome (zfs, local, noatime, nfsv4acls)
gaia/iocage/jails/thunderdome/root on /iocage/jails/thunderdome/root (zfs, local, noatime, nfsv4acls)
/iocage/releases/11.1-RELEASE/root/bin on /iocage/jails/thunderdome/root/bin (nullfs, local, read-only)
/iocage/releases/11.1-RELEASE/root/boot on /iocage/jails/thunderdome/root/boot (nullfs, local, read-only)
/iocage/releases/11.1-RELEASE/root/lib on /iocage/jails/thunderdome/root/lib (nullfs, local, read-only)
/iocage/releases/11.1-RELEASE/root/libexec on /iocage/jails/thunderdome/root/libexec (nullfs, local, read-only)
/iocage/releases/11.1-RELEASE/root/rescue on /iocage/jails/thunderdome/root/rescue (nullfs, local, read-only)
/iocage/releases/11.1-RELEASE/root/sbin on /iocage/jails/thunderdome/root/sbin (nullfs, local, read-only)
/iocage/releases/11.1-RELEASE/root/usr/bin on /iocage/jails/thunderdome/root/usr/bin (nullfs, local, read-only)
/iocage/releases/11.1-RELEASE/root/usr/include on /iocage/jails/thunderdome/root/usr/include (nullfs, local, read-only)
/iocage/releases/11.1-RELEASE/root/usr/lib on /iocage/jails/thunderdome/root/usr/lib (nullfs, local, read-only)
/iocage/releases/11.1-RELEASE/root/usr/libexec on /iocage/jails/thunderdome/root/usr/libexec (nullfs, local, read-only)
/iocage/releases/11.1-RELEASE/root/usr/sbin on /iocage/jails/thunderdome/root/usr/sbin (nullfs, local, read-only)
/iocage/releases/11.1-RELEASE/root/usr/share on /iocage/jails/thunderdome/root/usr/share (nullfs, local, read-only)
/iocage/releases/11.1-RELEASE/root/usr/libdata on /iocage/jails/thunderdome/root/usr/libdata (nullfs, local, read-only)
/iocage/releases/11.1-RELEASE/root/usr/lib32 on /iocage/jails/thunderdome/root/usr/lib32 (nullfs, local, read-only)
devfs on /iocage/jails/thunderdome/root/dev (devfs, local, multilabel)
fdescfs on /iocage/jails/thunderdome/root/dev/fd (fdescfs)

root@gaia#iocage list 
| 26  | thunderdome   | up    | 11.0-RELEASE | 10.0.1.16 |

root@thunderdome:/ # uname -a
FreeBSD thunderdome 11.1-RELEASE-p4 FreeBSD 11.1-RELEASE-p4 #0: Tue Nov 14 06:12:40 UTC 2017     root@amd64-builder.daemonology.net:/usr/obj/usr/src/sys/GENERIC  amd64

looks like the jail has been upgraded but has failed, I can try recreating the error on a different jail if needed?

**Comment by skarekrow** [comment]
No shouldn't be necessary. I'll see if I can recreate on my end.

**Comment by skarekrow** [comment]
Hey Kitten :)

This shouldn't be a problem on 1.0 RELEASE anymore, have you been able to upgrade your iocage and see if it's still a problem?

**Comment by kitten77** [comment]
Sorry I can't, I have powered down the server and deleted it.
