### ISSUE TITLE
iocage paths vs. mount

### ISSUE THREAD

**Issue by jhriggs** [iocage/iocage#48]
So, as I have started to use iocage more and more, I am starting to run up against a brick wall with some of the paths. Specifically, `mount` fails with mountpoint names > 88 characters. So, if I try to mount zfs or null file systems inside an iocage jail, I get failures depending on paths and names. For example:

```
# zfs create foo/my.too-long.mountpoint.name
cannot mount 'foo/my.too-long.mountpoint.name': File name too long
filesystem successfully created, but not mounted
```

```
# zfs get mountpoint foo/my.too-long.mountpoint.name
NAME                             PROPERTY    VALUE                                                                                        SOURCE
foo/my.too-long.mountpoint.name  mountpoint  /iocage/jails/2c03abc0-c99b-11e4-a062-9193e3f0746d/root/mnt/foo/my.too-long.mountpoint.name  inherited from foo
```

This particular mountpoint is 91 characters. See https://bugs.freebsd.org/bugzilla/show_bug.cgi?id=161481 and https://bugs.freebsd.org/bugzilla/show_bug.cgi?id=167105 for FreeBSD bug reports.

Unfortunately, I don't have any good answers as to the fix for this (until the 88-char limit gets lifted), so I am opening this for discussion. #9 could be a possibility (specifying a custom UUID...which may not be a UUID, but rather a name/tag/hostname/etc.). Or, mounting the jail file system at a different/shorter path would be an option, but I'm not sure what that looks like. One other thought I have had is doing something similar to how github has a short version of the commit ID, but again, I don't know exactly how that would work in this context.

Any thoughts or ideas?

**Comment by skarekrow** [comment]
Yes. I was thinking that FreeBSD should fix this. Anything we do is just a
hack around the real issue. I'd rather not waste time trying to solve this
when it's not really our issue.  Once they do fix it, this just results in
wasted time.

**Comment by jhriggs** [comment]
I agree that it needs to be fixed in the OS, but in the meantime (the bug has been open since 2011), there is no good workaround for iocage users who may bump into this.

**Comment by skarekrow** [comment]
As @pannon stated in issue #32, it doesn't affect the actual running of the jails. So I haven't been motivated enough to do anything about it, I'm not sure what his feelings are. I suspect the same.

**Comment by pannon** [comment]
We have the state of the art 128bit ZFS filesystem in FreeBSD and it is crippled by this legacy limit in certain cases. Both Illumos and Linux comes with much higher limits. Since there is quite a bit of us now running into this particular problem - maybe a good time to resurrect that bug thread and push for a change?!

Sooner or later ZFS users will run into this limit in the future.

For the interim I will try to commit a change which will allow the user to workaround this issue bu running `iocage set mountpoint=/iocage/jails/my_short_UUID` .

If you execute this now it will modify all mounts for the jail - but it will fail to start.

Leaving this manual override to the user will be a workaround and allow for an informed decision, while still preserving the ability to change back and forth between full and short UUID's as desired.

Let me know if this seems OK or if you guys have a better solution.

**Comment by jhriggs** [comment]
That sounds reasonable to me and will buy us a little bit of time until FreeBSD hopefully addresses the issue. Of course, `2c03abc0-c99b-11e4-a062-9193e3f0746d` vs. `somejail` is only buying us a couple dozen bytes, but it's better than nothing. Thanks, guys. Let me know if/how I can help.

**Comment by pannon** [comment]
OK, this should work now (need a lot of testing) to get things started, I have modified `start` `stop` and `list` sub-commands to support short paths. That should be enough to get things tested and start hammering out other functions.

**Comment by pannon** [comment]
Modified further functions and short paths should work now with all actions. See output of `jls` below.

To use the short path:
- create jail `iocage -c create tag=short-test` (`-c` is a clone)
- get the current mount `iocage get mountpoint short-test`
- run `iocage set mountpoint=/iocage/jails/myshortpath short-test`
- start jail `iocage start short-test`

```
   JID  IP Address      Hostname                      Path
    32  -               03e05f65-cb43-11e4-87ea-90b8d /iocage/jails/03e05f65/root
    33  -               9cd7f088-ca71-11e4-87ea-90b8d /iocage/jails/9cd7f088-ca71-11e4-87ea-90b8d01b7245/root
    34  -               da2e66fd-ca76-11e4-87ea-90b8d /iocage/jails/da2e66fd-ca76-11e4-87ea-90b8d01b7245/root
    35  -               ec7b167c-cb42-11e4-87ea-90b8d /iocage/jails/ec7b167c/root
```

**Comment by pannon** [comment]
@jhriggs @skarekrow @dlangille lastest version in develop branch has added support for short paths now.

You can set a global default for all newly created jails:
`iocage set hack88=1 default`

Or, truncate the mountpoint of an existing jail by issuing:
`iocage set hack88=1 UUID|TAG`

To restore the full path, issue:
`iocage set hack88=0 UUID|TAG`

Also, the jails will automatically truncate/restore their paths/mountpoints on startup.
`iocage start myhackedjail` - will spit out an INFO message is such action is executed.

This will resolve all issues around ZFS snapshot diving and long paths for all affected users.

**Comment by dlangille** [comment]
+1

**Comment by dlangille** [comment]
Is a release imminent?

**Comment by pannon** [comment]
Yes, hopefully merge in the next 2 days and tag a release in master. This will be 1.6.0.
