### ISSUE TITLE
Gentler update path from legacy

### ISSUE THREAD

**Issue by rpepr** [iocage/iocage#480]
iocage commit d93a100f37695709909969a8819eceaa5e351bcc

Updating from legacy has multiple problems. iocage list asks for iocage -f list which crashes, but only after extensive changes to the jails leaving them in an unusable condition. On server 1 with 7 jails I had to zfs destroy the wreckage of my jails and rebuild them by hand. On server 2 with 17 jails I had sufficient backups to restore the jails and revert to iocage_legacy. 

I'd like to propose an alternative migration path. Instead of trying to convert all of the legacy jails automatically, what about renaming the legacy iocage data set and mount point to something like tank/iocage_legacy /iocage_legacy. The legacy iocage program and perhaps libraries and rc scripts would have to be renamed as well to not collide with the new iocage. Once all the legacy material is renamed py36-iocage can be installed and the process of converting jails can proceed as slowly or quickly as the user needs. This sort of migration worked well for my transition from warden to iocage and would provide a safe if slow path through the iocage upgrade.

**Comment by skarekrow** [comment]
I agree. To be honest I did it still the start thinking it would be fairly foolproof. It has definitely been a PITA. 

That being said, I'm not sure if I'll be implementing this ticket as @gronke will be doing amore graceful approach to legacy support. I'll keep this open just in case, as one can never tell the future. 

I'm sorry to hear you've had such a catastrophic failure with it though :( if you'd like to file tickets on those failures I'll try to fix anything I can reproduce.

**Comment by gronke** [comment]
@rpepr I'm sorry to hear that! As @skarekrow mentioned I'm working on https://github.com/iocage/libiocage that follows a different approach towards "legacy" jails. In the current state of the project there is no automated migration step. The style your jails are configured does not need to be changed to be managed with libiocage, thus the datasets are not touched (unless you intend to modify jails).

Now that you've tested your backup capabilities, would you give `ioc` a shot? There are several appliances that run "legacy" jails with it, but feedback is highly welcome! Maybe a good start is to use `ioc list` or `ioc get all <JAIL>` to see that your previous configuration is properly read.
