### ISSUE TITLE
iocage get type returning jail instead of basejail

### ISSUE THREAD

**Issue by a-stjohn** [iocage/iocage#483]
Make sure to follow and check these boxes before submitting an issue! Thank you.

- [x] Supply `iocage --version` 
Version 1.0 ALPHA
- [x] Supply the commands used, along with any steps to recreate it.
Currently I'm working on changing up some of the documentation based on the most recent change log.
I'm trying to create a basejail to double check that you can update/upgrade a basejail. I run 
```
# iocage create -b -r 10.4-RELEASE -n basetestjail
```
and creates jail successfully .

Following current docs for upgrading a base jail I then run
```
# iocage get type basetestjail
```
and it returns **jail**
- [x] Supply what you expected the result or output to be
According to the docs it should return **base jail**. Perhaps **jails** is in fact what is supposed to be returned. However, I'm ignorant when it comes to this and I only have the docs to go off of.

I did go ahead a pursue the update and upgrade commands, and they worked as expected. I'm just unsure if it's an actual base jail.

**Comment by skarekrow** [comment]
`iocage get basejail` will return `yes/no` :)
