### ISSUE TITLE
Provide Jail-Specific Environment Variables for `exec_{pre,post}{start,stop}` Commands

### ISSUE THREAD

**Issue by 0xf10e** [iocage/iocage#494]
Make sure to follow and check these boxes before submitting an issue! Thank you.

- [x] Supply `iocage --version`
- [ ] Supply the commands used, along with any steps to recreate it.
- [ ] Provide the output from the command you issued.
- [ ] Supply what you expected the result or output to be
- [x] Checked that the problem has not already been fixed on `master` if using
 a stable release.

----
As came up in #342: It would be useful to have environment variables containing things like the jail's ID, jailname or hostname available for commands which are run on the host system via the `exec_{pre,post}{start,stop}` properties. My current usecase would be(/was*) to pass a NIC over to a VIMAGE-enabled jail by running `ifconfig em3 vnet $JID` on the host as `exec_poststart` command.

I gave it a [quick shot](https://github.com/iocage/iocage/compare/master...0xf10e:envs_for_exec_cmds) (based on c9e7d9d1227b1f) but for some reason 
the environment of the `exec_poststart` command get's pruned 
to this:
```
MAIL=/var/mail/root
PATH=/sbin:/bin:/usr/sbin:/usr/bin:/usr/local/sbin:/usr/local/bin:/root/bin
PWD=/root
TERM=screen
USER=root
HOME=/root
SHELL=/bin/csh
BLOCKSIZE=K
```

When running `sh -c env` (in case it's `/bin/sh`'s fault) via 
`subprocess.Popen` in the Python Interpreter on the host 
I can adjust the env just fine:
```
>>> env_dict = os.environ.copy()
>>> env_dict.update({"JAILNAME": "foobar", "JID": "123"})
>>> su.Popen(["/bin/sh", "-c", "env"], env=env_dict) 
<subprocess.Popen object at 0x801b215f8>
>>> JAILNAME=foobar
VENDOR=amd
LOGNAME=root
JID=123
PAGER=more
OSTYPE=FreeBSD
MACHTYPE=x86_64
MAIL=/var/mail/root
PATH=/sbin:/bin:/usr/sbin:/usr/bin:/usr/local/sbin:/usr/local/bin:/root/bin
EDITOR=vi
HOST=halium
REMOTEHOST=xyz
PWD=/root
GROUP=wheel
TERM=screen
USER=root
HOME=/root
TMUX_PANE=%0
HOSTTYPE=FreeBSD
SHELL=/bin/csh
TMUX=/tmp/tmux-0/default,62619,0
BLOCKSIZE=K
SHLVL=1

>>> 
>>> su.Popen(["sh", "-c",  "echo $JID"], env=env_dict)
<subprocess.Popen object at 0x801b21550>
>>> 123
```

I wondered if maybe `jail(8)` strips the path but apparently it does not:
```
root@halium:~ # env JAILNAME=fw122-test jail -c path=/iocage/jails/fw122/root vnet=1 \
exec.prestart='env > /root/poststart_env_$JAILNAME; (ifconfig em3 vnet $JID; ifconfig em4 vnet $JID) 2> /root/poststart_stderr_$JAILNAME'
jail: /bin/sh -c env > /root/poststart_env_$JAILNAME; (ifconfig em3 vnet $JID; ifconfig em4 vnet $JID) 2> /root/poststart_stderr_$JAILNAME: failed
root@halium:~ # cat /root/poststart_env_fw122-test                                                                                                                
VENDOR=amd
JAILNAME=fw122-test
LOGNAME=root
PAGER=more
OSTYPE=FreeBSD
MACHTYPE=x86_64
MAIL=/var/mail/root
PATH=/sbin:/bin:/usr/sbin:/usr/bin:/usr/local/sbin:/usr/local/bin:/root/bin
EDITOR=vi
HOST=halium
[...]
root@halium:~ # cat /root/poststart_stderr_fw122-test
ifconfig: 'vnet' requires argument
ifconfig: 'vnet' requires argument
```
(Note there now actually was a file with `$JAILNAME` in its name created!)

When I pass only some envs to `su.Popen` in `iocage/lib/ioc_start.py`
and there is no `PATH` it won't find `jail` but when I pass a modified
`PATH` it doesn't use it either:
```
root@halium:~/iocage.git # git diff iocage/lib/ioc_start.py
diff --git a/iocage/lib/ioc_start.py b/iocage/lib/ioc_start.py
index c736027..7a7fdfe 100644
--- a/iocage/lib/ioc_start.py
+++ b/iocage/lib/ioc_start.py
@@ -260,11 +260,14 @@ class IOCStart(object):
 
         # Get jail ID and environment to pass to exec_p* commands:
         _, jid = iocage.lib.ioc_list.IOCList().list_get_jid(self.uuid)
-        env_dict = os.environ.copy()
-        env_dict.update({"JID": f"{jid}",
+        #env_dict = os.environ.copy()
+        env_dict = {"JID": f"{jid}",
                          "HOSTNAME": f"{host_hostname}",
                          "JAILNAME": f"ioc-{self.uuid}",
-                         "UUID": f"{self.uuid}"})
+                         "UUID": f"{self.uuid}",
+                         "PATH": "/bin:/usr/sbin:/usr/bin:/usr/local/bin:/usr/xdg4/sbin",
+                         "EDITOR": "emacs",
+                         "MACHTYPE": "arm64",}
 
         start = su.Popen([x for x in ["jail", "-c"] + net +
                           [f"name=ioc-{self.uuid}",
root@halium:~/iocage.git # make install && iocage restart fw122
[.......]
* Starting fw122
  + Start FAILED
jail: /bin/sh -c env > /root/poststart_env_$JAILNAME; (ifconfig em3 vnet $JID; ifconfig em4 vnet $JID) 2> /root/poststart_stderr_$JAILNAME: failed

root@halium:~/iocage.git # cat /root/poststart_env_
MAIL=/var/mail/root
PATH=/sbin:/bin:/usr/sbin:/usr/bin:/usr/local/sbin:/usr/local/bin:/root/bin
PWD=/root
USER=root
HOME=/root
SHELL=/bin/csh
BLOCKSIZE=K
```
--------------
  *) I've just found this snippet in [`jail(8)`'s manpage](https://www.freebsd.org/cgi/man.cgi?query=jail&sektion=8&manpath=FreeBSD+11.1-stable):
  >     vnet.interface
  >            A network interface to give to a vnet-enabled jail after is it
  >           created.  The interface will automatically be released when the
  >            jail is removed.
  Implementing a new `vnet_interfaces`-property might be an easier option for my usecase...

**Comment by skarekrow** [comment]
So your usecase is handled in https://github.com/iocage/iocage/commit/d0abb296c376b22f140ffe126b9f6ae631dfe979, I tried some stuff with this environment, and I just can't see a way to implement this without allowing arbitrary execution and allowing your command in `exec_poststart`.  I suggest you put your `exec_poststart` command in a script, as that will execute with the correct environment.

Example:
```
root@freenas:~ # cat test.py
#!/usr/local/bin/python3.6
import subprocess as su
import os

env_dict = {
        **os.environ,
        "FOO": "BAR",
}
cmd = ["/bin/sh", "-c", "/root/testenv.sh"]

su.Popen(cmd, stdout=su.PIPE, stderr=su.PIPE, env=env_dict).communicate()
root@freenas:~ # cat testenv.sh 
#!/bin/sh
env > /root/poststart_env
root@freenas:~ # rm ./poststart_env ; ./test.py ; cat ./poststart_env
VENDOR=amd
SSH_CLIENT=-----
LOGNAME=root
LANG=en_US.UTF-8
PAGER=more
OSTYPE=FreeBSD
MACHTYPE=x86_64
MAIL=/var/mail/root
PATH=/sbin:/bin:/usr/sbin:/usr/bin:/usr/local/sbin:/usr/local/bin:/root/bin
EDITOR=vi
FOO=BAR
HOST=freenas.local
REMOTEHOST=----
PWD=/root
GROUP=wheel
TERM=xterm-256color
SSH_TTY=/dev/pts/1
USER=root
HOME=/root
SSH_CONNECTION=-----
SHELL=/bin/csh
HOSTTYPE=FreeBSD
MM_CHARSET=UTF-8
BLOCKSIZE=K
SHLVL=1
```

**Comment by 0xf10e** [comment]
Am 23. Februar 2018 20:32:14 MEZ schrieb Brandon Schneider <notifications@github.com>:
>So your usecase is handled in
>https://github.com/iocage/iocage/commit/d0abb296c376b22f140ffe126b9f6ae631dfe979,

Sweeet, that was fast!
Thank you very much, Sir! :+1:

>I tried some stuff with this environment, and I just can't see a way to
>implement this without allowing arbitrary execution and allowing your
>command in `exec_poststart`.  I suggest you put your `exec_poststart`
>command in a script, as that will execute with the correct environment.
>
>Example:
>[…]

Thx for the example, I'll test this next week
