### ISSUE TITLE
My copy of iocage in FreeBSD is missing 'promote' is it safe to do zfs promote?

### ISSUE THREAD

**Issue by clickbg** [iocage/iocage#513]
Hi,

I am using iocage on FreeBSD 11 from package - py36-iocage-0.9.10.
I've create a few jails from a template, but now I want to be able to change the template.
Sometime ago in the old version of iocage there was a promote command, there isn't such in the new one.
Is is safe if I do zfs promote? Will update/upgrade work afterwards? What are the possible issues that I might hit? 

Thanks!

**Comment by skarekrow** [comment]
Just use `iocage set template=no TEMPLATE` to change it back to a jail :) Anything created from that template was only a snapshot, so these changes won't propogate. You would have had to destroy them or made them basejails instead.

If they were a basejail, make sure to change it back to a template again or update the jail's required fstab :+1:
