### ISSUE TITLE
SSH to host instead of jail

### ISSUE THREAD

**Issue by src386** [iocage/iocage#519]
Dear iocage maintainer:

    root@iocagehost:~ # iocage --version
    Version	0.9.10 2017/12/22

    root@iocagehost:~ # iocage create -r 11.1-RELEASE --name myjail boot=on
    root@iocagehost:~ # iocage set ip4_addr="vtnet0|192.168.0.91/24" myjail
    root@iocagehost:~ # iocage restart myjail
    root@iocagehost:~ # iocage list
    +-----+---------+-------+--------------+--------------+
    | JID |  NAME   | STATE |   RELEASE    |     IP4      |
    +=====+=========+=======+==============+==============+
    | 3   | myjail | up    | 11.1-RELEASE | 192.168.0.91 |
    +-----+---------+-------+--------------+--------------+

    root@iocagehost:~ # ssh root@192.168.0.91
    Password for root@iocagehost:

As you can see, 192.168.0.91:22 points to the host and not to the jail. This happens when **sshd** is stopped in _myjail_. Is it the normal behavior?

Note: I run FreeBSD in a KVM virtual machine, don't know if that matters (promiscous network?).

**Comment by skarekrow** [comment]
Yes that is a side effect of the shared networking you used. If you don't want that behavior, have sshd on the host listen only on it's IP or use vnet for the jail.
