### ISSUE TITLE
Do not add default gw to bridge on iocage start

### ISSUE THREAD

**Issue by ole-db** [iocage/iocage#521]
Make sure to follow and check these boxes before submitting an issue! Thank you.

- [x] Supply `iocage --version`
Version	0.9.10 2017/12/22

if I start a Jail with vnet Interface the interface with the default route on it ( in my case `em0`) is automatically added to the bridge.

In my point of view, this makes sense in some special setups. There are many setups, where you don't want to have this as a standard behaviour. Or need a way to deactivate.

https://github.com/iocage/iocage/blob/1908813cbd01c6770ced228f4c20c8ba80f3dad9/iocage/lib/ioc_start.py#L605-L615

**Comment by gronke** [comment]
> if I start a Jail with vnet Interface the interface with the default route on it ( in my case em0) is automatically added to the bridge.

This is a security risk and should not be done by iocage. One can end up exposing critical infrastructure to the public by accident or getting a root server banned for ARPing on the uplink interface.

At the most this action should only be performed when users opt-in to use it, but I'm in favor of printing a warning message instead that may suggests the command to execute to the device.

**Comment by skarekrow** [comment]
I'd be willing to accept a PR, but this was the previous behavior in iocage-legacy and is ported as a POLA type approach. That being said, this is a very common requirement. You cannot add the vnet interfaces to a bridge without having a host interface for them to route packets out.

I'd be willing to see a more concrete example of what you think it should do instead, but I'm not able to dedicate any time to implementing anything currently.

**Comment by ole-db** [comment]
Ok. Bridging all vnet interfaces whit the host interface can be used in very simple setups, I agree. But only in Setups where all Jails are in the same Layer2 subnet with the host. But in all my personal use cases this is not true. Let me give you two examples:

1.
At many cheap hosting providers you can rent a server with only one IPv4 address. If you need more Addresses you can rent several /2x networks. These networks are routed to your server. In this case it makes no sense to add your host interface to the bridge. Only vnet interfaces are member of the bridge and you set `sysctl net.inet.ip.forwarding=1`

2.
Your hosting server and your Jails are in different vlans. in this case you want to add the vlan interface of your jails network to the bridge.

my suggestion is to delete line 605 to line 615. In my opinion iocage should not do this network setup. This should be placed in /etc/rc.conf 

I could make a PR, but at first I have to figure out how to make multiple PR in one project. sorry I am new to github ;-)

**Comment by skarekrow** [comment]
Valid points! Though for point 2 you would also need your host interface
added to the bridge for packets to leave the vlan iirc--
- Brandon

**Comment by ole-db** [comment]
> Valid points! Though for point 2 you would also need your host interface added to the bridge for packets to leave the vlan iirc--

Ah, sorry the example was underspecified. The jails have an own default GW in the Vlan.
Also in example 1. I put an IP Address on the bridge, which is the default GW for the Jails in this subnet.

**Comment by gronke** [comment]
Thanks to @ole-db this issue is gone!

**Comment by ole-db** [comment]
Hi,

ok the lib has changed completely. And again, iocage is adding host interfaces to the bridge. Even if 'vnet_default_interface' is set to 'none'.

This is a very bad behaviour:

If you have a Host with a vlan-Interface  (with no ip configured on it) and your jails live inside this vlan. You don't want iocage to add a interface to this bridge.

You could argue, that one could simply set 'vnet_default_interface' to '<vlan-interface>'. But here are two scenarios where this is not a solution:

1. Multi-Host enviroment
You have multiple Hosts with different network controllers. And you want to easily migrate jails between them. Than you don't want to change the 'vnet_default_interface' every time from 'em0.4000' to 'rt0.4000' or 'em0.4000' to 'em2.4000'.

2. Jail only network
You have a Inter-Jail Network without uplink. how to handle this?

I think there are other examples where you don't want iocage to add anything else than the vnet-interface to the bridge.

In my opinion iocage shouldn't be responsible for this kind of network-setup. My suggestion:
* If 'vnet_default_interface' is set  to 'auto' iocage has the old behaviour
* if  'vnet_default_interface' is set  to 'none' iocage just adds the vnet interface

**Comment by ole-db** [comment]
PS: please reopen this issue

**Comment by gronke** [comment]
> This is a very bad behaviour

Aye, iocage should not mess with bridges at all.

> If you have a Host with a vlan-Interface (with no ip configured on it) and your jails live inside this vlan. You don't want iocage to add a interface to this bridge.

It defeats the security model of VNET. @skarekrow this is a serious security thread and needs to be mitigated. IMO it is not acceptable that iocage does create, destroy or alter any network bridge (that is connected to existing interfaces) on the host system.

@foo2342 FYI

**Comment by skarekrow** [comment]
@gronke We disagree. This is very much so in iocage's camp to do this. If users have to create their own bridges and bridge their own interfaces when specified clearly to iocage, then why use iocage?

It does things automatically for the 99%, the 1% cannot dictate the direction of the project. However we should always make sure there's an out to any automatic behavior like this so those that are in the 1% (ole-db here) can do what they need to with the project, they don't need it to handle the tasks.

iocage isn't just an advanced admin tool, it's meant for absolute beginners to hide all the complexity and to scale up to the advanced user. This does not defeat the model of VNET, VNET is a virtual stack, that doesn't become any less true when bridged.

Please let's not blast things as serious when they are most certainly *not*.

**Comment by amarshall** [comment]
I think this was resolved by #655?

**Comment by skarekrow** [comment]
Yes it was @amarshall, thanks!
