### ISSUE TITLE
Release-patchlevel not updated after running "iocage update"

### ISSUE THREAD

**Issue by jsegaert** [iocage/iocage#536]
Make sure to follow and check these boxes before submitting an issue! Thank you.

- [X] Supply `iocage --version`
Version	1.0 ALPHA
Latest commit from master

- [X] Supply the commands used, along with any steps to recreate it.
### Create jail
sudo iocage create -n foo -r latest ip4_addr="wlan0|192.168.0.210"
### All three commands show 11.1-RELEASE-p6
sudo iocage exec foo freebsd-version
sudo iocage get release foo
iocage list -l
### Upgrade jail to latest patch level (in this case 11.1-RELEASE-p9)
sudo iocage update foo
sudo iocage restart foo

- [X] Provide the output from the command you issued.
### The command below now shows 11.1-RELEASE-p9 as expected
sudo iocage exec foo freebsd-version
### Unfortunately the two commands still show 11.1-RELEASE-p6
sudo iocage get release foo
iocage list -l

- [X] Supply what you expected the result or output to be
I was expecting to consistently see release 11.1-RELEASE-p9 

- [X] Checked that the problem has not already been fixed on `master` if using
 a stable release.

**Comment by skarekrow** [comment]
Closed by https://github.com/iocage/iocage/commit/07a28152a6f18a24d48ba3f2f634d7d6b4bfc3c1. Yikes that was some delay!
