### ISSUE TITLE
ip4_autostart, ip4_autoend, ip4_autosubnet missing properties

### ISSUE THREAD

**Issue by vin047** [iocage/iocage#539]
I noticed that these properties are no longer available on the new rewrite of iocage. Are they going to be implemented in future? What other workarounds are available currently to automatically assign an unused IP address based on a given network interface, range, and subnet?

Version 0.9.10 2017/12/22
command: `iocage create -r 11.1-RELEASE -n test ip4_autostart="22" default`
output: `ip4_autostart is not a valid property!`

**Comment by skarekrow** [comment]
There is no immediate plans, but they are still nice to have. We may do it again.
