### ISSUE TITLE
Post-stop script with arguments: "Running poststop WARNING. Script is not executable!"

### ISSUE THREAD

**Issue by serge-vk** [iocage/iocage#540]
I am not sure if it is a feature or a bug, but I used scripts with arguments running legacy_iocage 1.7.6 and just discovered they don't work after updating to the Ports version of iocage today.
- [x] Supply `iocage --version`
Version	0.9.10 2017/12/22
- [x] Supply the commands used, along with any steps to recreate it.
```
iocage set exec_poststop="/path/script.sh argument" jailtag
iocage start jailtag
iocage stop jailtag
```
- [x] Provide the output from the command you issued.
```
* Stopping Ports
  + Running prestop OK
  + Stopping services OK
  + Removing jail process OK
  + Running poststop WARNING
Script is not executable!
```
- [x] Supply what you expected the result or output to be
```
* Stopping Ports
  + Running prestop OK
  + Stopping services OK
  + Removing jail process OK
  + Running poststop OK
```
- [x] Checked that the problem has not already been fixed on `master` if using
 a stable release.

Script arguments don't work since [/iocage/lib/ioc_stop.py](https://github.com/iocage/iocage/blob/599c2ea1978a8676a626a4c8c1ec4e8ec2922170/iocage/lib/ioc_stop.py) calls `os.access('/path/script.sh argument', os.X_OK)` always returning `False` even if the script itself is executable. I think that using arguments is legitimate (and `jail` command has no issues with them, of course) and would suggest stripping everything after a space in the call to `os.access` to check executability of the supplied script.

On a related note, I also find that  [/iocage/lib/ioc_start.py](https://github.com/iocage/iocage/blob/599c2ea1978a8676a626a4c8c1ec4e8ec2922170/iocage/lib/ioc_start.py) has no checks at all on provided `exec_prestart` and `exec_poststart` paths. Therefore, scripts with arguments run just fine. This, however, seems inconsistent with the `exec_prestop` and `exec_poststop` coding.

**Comment by serge-vk** [comment]
I tinkered a bit with the code, and as a quick fix, I edited these lines:
https://github.com/iocage/iocage/blob/599c2ea1978a8676a626a4c8c1ec4e8ec2922170/iocage/lib/ioc_stop.py#L66-L67
to:
```python
        elif os.access(script[0].split(maxsplit=1)[0], os.X_OK): 
            script = ["/bin/sh", "-c", script[0]]
```
Scripts with arguments work now, but I also noticed that any output is treated as a WARNING. This might not be necessarily so. My post-stop scripts generate output in any case.
By the way any output generated by pre/post-start commands is currently gobbled up, but it looks like that code (similar to pre/post-stop) simply has not yet been finished.

**Comment by gronke** [comment]
Instead of `.split(maxsplit=1)` shlex should be used for this task:

```
>>> a = "/tmp/foo\ bar.sh --flag -f"
>>> shlex.split(a)[0]
'/tmp/foo bar.sh'
>>> a.split(maxsplit=1)[0]
'/tmp/foo\\'
```

**Comment by serge-vk** [comment]
Thank you for pointing this out. I have no experience in Python, so I did not even know `shlex` existed. In that case, it might be also necessary to do another split of `shlex.split(a)[0]` because calling something like `os.access('/tmp/foo bar', os.X_OK)` will always return `False`.

**Comment by gronke** [comment]
`os.access('/tmp/foo bar', os.X_OK)` returns True if the file exists and is executable:

```
sh-3.2$ touch /tmp/foo\ bar
sh-3.2$ chmod a+x /tmp/foo\ bar
sh-3.2$ python3.6
Python 3.6.4 (default, Mar 19 2018, 14:34:58) 
[GCC 4.2.1 Compatible Apple LLVM 9.0.0 (clang-900.0.39.2)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import os
>>> os.access('/tmp/foo bar', os.X_OK)
True
>>> 
```

**Comment by serge-vk** [comment]
Yes, you are right! That would be a strange file name, but it is legal and it works. Thanks :)

**Comment by skarekrow** [comment]
Same as #611
