### ISSUE TITLE
Creating a jail from a template does not work

### ISSUE THREAD

**Issue by DeeeeLAN** [iocage/iocage#558]
Make sure to follow and check these boxes before submitting an issue! Thank you.

- [x] Supply `iocage --version`
```
# iocage --version
Version	1.0 ALPHA
```

- [x] Supply the commands used, along with any steps to recreate it.
    - I created a jail named template and set it as a template, then called
```
# iocage create -t template -n testjail
```

- [x] Provide the output from the command you issued.
```
Traceback (most recent call last):
  File "/usr/local/bin/iocage", line 10, in <module>
    sys.exit(cli())
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/iocage/cli/create.py", line 103, in cli
    elif release.lower() == "latest":
AttributeError: 'NoneType' object has no attribute 'lower'
```

- [x] Supply what you expected the result or output to be
    - I expected a new jail to be created, modeled after my template
- [ ] Checked that the problem has not already been fixed on `master` if using
 a stable release.

**Comment by jsegaert** [comment]
Are you sure this is still an issue in **master**?  I cannot reproduce this and suspect this is closely related to issue #507 that was already solved by PR #508

**Comment by DeeeeLAN** [comment]
@jsegaert sorry, I guess I wasn't paying enough attention to that last bullet point. FreeNAS supplies version 1.0 ALPHA with their version 11.1-U4. I do not believe I will be able to test with master, but if it is resolved, then I can submit a bug ticket there to have them update the version, once there is a new iocage release.

**Comment by skarekrow** [comment]
@jsegaert is correct, I do think they're the same bug. 

@avidmills it will be updated in the newer releases :) no worries on making a ticket.
