### ISSUE TITLE
"iocage list" passes truncated UUID to "jls", gets incorrect status

### ISSUE THREAD

**Issue by anmnz** [iocage/iocage#565]
For a jail without a custom name, `iocage list` (without `-l`) truncates the jail UUID for display.

Unfortunately, it also uses the truncated UUID, instead of the original UUID, to construct the `jls` command that finds the jail ID. Thus `iocage list` reports incorrect jail state and networking information, where `iocage list -l` gets it right.

The bug is in function `list_all()` in [`ioc_list.py` (current `master` branch)](https://github.com/iocage/iocage/blob/master/iocage/lib/ioc_list.py). When not using `-l` the UUID is modified in-place at [line 163](https://github.com/iocage/iocage/blob/master/iocage/lib/ioc_list.py#L163), but then at [line 194](https://github.com/iocage/iocage/blob/master/iocage/lib/ioc_list.py#L194) the modified UUID is passed to `list_get_jid()`.

- [x] Supply `iocage --version`
`Version 1.0 ALPHA`

- [x] Supply the commands used, along with any steps to recreate it.
```
# start from a clean setup with "iocage clean -af"
iocage fetch -r 11.1-RELEASE
iocage create -r 11.1-RELEASE vnet=on dhcp=on allow_raw_sockets=1 boot=on bpf=yes
iocage list
iocage list -l
```

- [x] Provide the output from the command you issued.
Output from `iocage list` followed by `iocage list -l`:
```
$ iocage list
+-----+----------+-------+--------------+------+
| JID |   NAME   | STATE |   RELEASE    | IP4  |
+=====+==========+=======+==============+======+
| -   | a76bb1bf | down  | 11.1-RELEASE | DHCP |
+-----+----------+-------+--------------+------+
$ iocage list -l
+-----+--------------------------------------+------+-------+------+------------------+-----------------------------------------+-----+----------+
| JID |                 NAME                 | BOOT | STATE | TYPE |     RELEASE      |                   IP4                   | IP6 | TEMPLATE |
+=====+======================================+======+=======+======+==================+=========================================+=====+==========+
| 8   | a76bb1bf-d9de-440c-b443-7dd7d845dee7 | on   | up    | jail | 11.1-RELEASE-p10 | DHCP (running -- address requires root) | -   | -        |
+-----+--------------------------------------+------+-------+------+------------------+-----------------------------------------+-----+----------+
$
```

- [x] Supply what you expected the result or output to be
`iocage list` and `iocage list -l` should provide consistent output, but they disagree about whether the jail is up.

- [x] Checked that the problem has not already been fixed on `master` if using
 a stable release.

**Comment by skarekrow** [comment]
Closed by #572
