### ISSUE TITLE
Starting a jail that is already running exits with code 1

### ISSUE THREAD

**Issue by thnee** [iocage/iocage#569]
Starting a jail that is already running exits with code `1`, I think it should exit with code `0`.

This is especially relevant when building some kind of automation around iocage, where you would have a wrapper function that always assumes that a non-zero exit code means error and aborts. Currently, this requires having to put in a special case in the code just for this case.

## Version

```
$ iocage --version
Version	0.9.10 2017/12/22
```

## Example output

Starting a jail that is already running, observe how the exit code is `1`, indicating an error, this is not expected.

```
$ sudo iocage start hehe
hehe is already running!
$ echo $?
1
```

For comparison, stopping a jail that is not running works fine, the exit code is `0`, this is expected.

```
$ sudo iocage stop hehe
hehe is not running!
$ echo $?
0
```

## Checklist

- [x] Supply `iocage --version`
- [x] Supply the commands used, along with any steps to recreate it.
- [x] Provide the output from the command you issued.
- [x] Supply what you expected the result or output to be
- [ ] Checked that the problem has not already been fixed on `master` if using
 a stable release.

I have tried to look at the code in master vs the code for 0.9.10 but cannot discern what exactly causes this behavior.

**Comment by skarekrow** [comment]
Currently iocage is not idempotent, but I'll mark this as an enhancement if others see value in it. The exit is coming from ioc_common in the logit method.

**Comment by gronke** [comment]
> Starting a jail that is already running exits with code 1, I think it should exit with code 0.

That is exactly what I would expect from the command. The command was not executed successfully, so that the exit code should be > 0.

> This is especially relevant when building some kind of automation around iocage, where you would have a wrapper function that always assumes that a non-zero exit code means error and aborts. 

You can wrap the command error while iocage keeps differentiating between successful and failed commands in its exit code.

> Currently, this requires having to put in a special case in the code just for this case.

Both methods shown here seem to be reasonable overhead in an automation script for doing that:

```sh
set +e
iocage start myjail 2>&1
set -e
```

or

```sh
iocage start myjail 2>&1 || true
```
