### ISSUE TITLE
Create empty jails

### ISSUE THREAD

**Issue by joachimmathes** [iocage/iocage#57]
Will there be an implementation of the former `iocage create -e` to create an empty jail?

I checked iocage version 0.9.6 (https://github.com/iocage/iocage/commit/be33344b7d1b6ddb8311e528223609556570293d) and it seems to be not implemented, yet.

Best
Jo

**Comment by skarekrow** [comment]
I just haven't gotten around to it :)

Will be easy enough to implement 👍

**Comment by skarekrow** [comment]
Alright @joachimmathes all done, test and let me know how much stuff breaks ;)

**Comment by joachimmathes** [comment]
That was fast! Thank you very much @skarekrow ! I'm going to test it and let you know, if it works.
