### ISSUE TITLE
iocage upgrade download only once

### ISSUE THREAD

**Issue by stratacast** [iocage/iocage#581]
Make sure to follow and check these boxes before submitting an issue! Thank you.

Having it be the season for upgrading from 11.1 to 11.2, I began upgrading my jails (iocage version 0.9.10) and found that each upgrade meant downloading the proper FreeBSD files each time, which is time consuming as well as data hungry. I'm fine having to upgrade each one individually, but is it possible to at least have iocage check to see if there's an existing copy of the data necessary to do an upgrade instead of fetching it each time?

**Comment by skarekrow** [comment]
Unfortunately the fetched release isn't what's used for upgrading. Each jail is independent, which means an independent operation like any other server. So in this case, https://forums.freebsd.org/threads/freebsd-update-mirror.59777/post-343180 would be a pretty good idea
