### ISSUE TITLE
iocage list - proposal

### ISSUE THREAD

**Issue by yerrysherry** [iocage/iocage#585]
Hallo,

- [ ] Supply `iocage --version`
iocage --version
Version	1.0 ALPHA

It would be nice to list the headers you want, something like:

iocage list -r 'host_hostname,priority,state,boot,compression'
-r or --report

Now, we need to do:
iocage get priority JAIL

and supper cool would be:

iocage list -r 'host_hostname,priority,boot,compression' -q 'state=up,priority<50,host_hostname="www-*"'
-q or --query

Then you do not need any more the -q or -l option.

(I know the option -r,-q is already used.)

Regards,
Gerrit

**Comment by gronke** [comment]
Hi @yerrysherry! The libiocage CLI tool `ioc` implements this option as `-o/--output` option where you can, just like in your example, provide a comma separated list of keys. You may select any jail config property or jail attribute.

From [libiocage/iocage/cli/list.py#L60](https://github.com/iocage/libiocage/blob/31509a6d4559e34627a599bd16de80c9e59f7ee0/iocage/cli/list.py#L60):

```python3
@click.option("--output", "-o", default=None)
```

**Comment by yerrysherry** [comment]
Thx @gronke , I check the libiocage tool.
