### ISSUE TITLE
iocage build crash with 11.2 sources

### ISSUE THREAD

**Issue by Mitchou** [iocage/iocage#587]
Hi,

- [ ] Supply `iocage --version`
Version	1.0 ALPHA

% sudo svn info /usr/src
Chemin : /usr/src
Chemin racine de la copie de travail : /usr/src
URL : https://svn.freebsd.org/base/releng/11.2
Relative URL: ^/releng/11.2
Racine du dépôt : https://svn.freebsd.org/base
UUID du dépôt : ccf9f872-aa2e-dd11-9fc8-001c23d0bc1f
Révision : 336600
Type de nœud : répertoire
Tâche programmée : normale
Auteur de la dernière modification : gjb
Révision de la dernière modification : 335510
Date de la dernière modification: 2018-06-22 00:59:49 +0200 (ven. 22 juin 2018)

- [ ] Supply the commands used, along with any steps to recreate it.
%sudo make install
- [ ] Provide the output from the command you issued.
echo -e "import os\ntry:\n  if not os.listdir('"/usr/src"'): exit('"/usr/src" must be populated!')\nexcept FileNotFoundError:\n  exit('"/usr/src" must be populated!')" | python3.6
test -d .git && git pull || true
Déjà à jour.
test -d .git && git submodule init py-libzfs && git submodule update py-libzfs || true
python3.6 -m ensurepip
Requirement already satisfied: setuptools in /usr/local/lib/python3.6/site-packages
Requirement already satisfied: pip in /usr/local/lib/python3.6/site-packages
export FREEBSD_SRC="/usr/src" && cd py-libzfs && python3.6 setup.py build && python3.6 setup.py install
WARNING: '' not a valid package name; please use only .-separated package names in setup.py
running build
running build_py
running build_ext
skipping 'libzfs.c' Cython extension (up-to-date)
building 'libzfs' extension
cc -Wno-unused-result -Wsign-compare -Wunreachable-code -DNDEBUG -O2 -pipe -fstack-protector -fno-strict-aliasing -fPIC -I/usr/src/cddl/lib/libumem -I/usr/src/sys/cddl/compat/opensolaris/ -I/usr/src/sys/cddl/compat/opensolaris -I/usr/src/cddl/compat/opensolaris/include -I/usr/src/cddl/compat/opensolaris/lib/libumem -I/usr/src/cddl/contrib/opensolaris/lib/libzpool/common -I/usr/src/sys/cddl/contrib/opensolaris/common/zfs -I/usr/src/sys/cddl/contrib/opensolaris/uts/common/fs/zfs -I/usr/src/sys/cddl/contrib/opensolaris/uts/common/sys -I/usr/src/cddl/contrib/opensolaris/head -I/usr/src/sys/cddl/contrib/opensolaris/uts/common -I/usr/src/cddl/contrib/opensolaris/lib/libnvpair -I/usr/src/cddl/contrib/opensolaris/lib/libuutil/common -I/usr/src/cddl/contrib/opensolaris/lib/libzfs/common -I/usr/src/cddl/contrib/opensolaris/lib/libzfs_core/common -I/usr/local/include/python3.6m -c libzfs.c -o build/temp.freebsd-11.2-RELEASE-amd64-3.6/libzfs.o -DNEED_SOLARIS_BOOLEAN -D_XPG6 -g -O0
libzfs.c:15235:13: warning: code will never be executed [-Wunreachable-code]
  __pyx_r = 0;
            ^
libzfs.c:20167:73: warning: incompatible pointer to integer conversion passing 'PyObject *' (aka 'struct _object *') to parameter of type 'zfs_type_t'
      [-Wint-conversion]
  __pyx_v_handle = zfs_path_to_zhandle(__pyx_v_self->handle, __pyx_t_1, __pyx_t_2);
                                                                        ^~~~~~~~~
/usr/src/cddl/contrib/opensolaris/lib/libzfs/common/libzfs.h:731:79: note: passing argument to parameter here
extern zfs_handle_t *zfs_path_to_zhandle(libzfs_handle_t *, char *, zfs_type_t);
                                                                              ^
libzfs.c:40326:13: warning: code will never be executed [-Wunreachable-code]
  __pyx_r = 0;
            ^
libzfs.c:45012:71: error: too few arguments to function call, expected 3, have 2
        __pyx_v_ret = zpool_scan(__pyx_v_self->handle, POOL_SCAN_SCRUB);
                      ~~~~~~~~~~                                      ^
/usr/src/cddl/contrib/opensolaris/lib/libzfs/common/libzfs.h:264:1: note: 'zpool_scan' declared here
extern int zpool_scan(zpool_handle_t *, pool_scan_func_t, pool_scrub_cmd_t);
^
libzfs.c:45207:70: error: too few arguments to function call, expected 3, have 2
        __pyx_v_ret = zpool_scan(__pyx_v_self->handle, POOL_SCAN_NONE);
                      ~~~~~~~~~~                                     ^
/usr/src/cddl/contrib/opensolaris/lib/libzfs/common/libzfs.h:264:1: note: 'zpool_scan' declared here
extern int zpool_scan(zpool_handle_t *, pool_scan_func_t, pool_scrub_cmd_t);
^
libzfs.c:51253:89: error: too few arguments to function call, expected 4, have 3
        __pyx_v_ret = lzc_send_space(__pyx_v_c_name, __pyx_v_cfromname, (&__pyx_v_space));
                      ~~~~~~~~~~~~~~                                                    ^
/usr/src/cddl/contrib/opensolaris/lib/libzfs_core/common/libzfs_core.h:75:1: note: 'lzc_send_space' declared here
int lzc_send_space(const char *, const char *, enum lzc_send_flags, uint64_t *);
^
libzfs.c:54313:74: warning: passing 'const char *' to parameter of type 'char *' discards qualifiers
      [-Wincompatible-pointer-types-discards-qualifiers]
        __pyx_v_ret = zfs_destroy_snaps(__pyx_v_self->__pyx_base.handle, __pyx_v_c_name, 1);
                                                                         ^~~~~~~~~~~~~~
/usr/src/cddl/contrib/opensolaris/lib/libzfs/common/libzfs.h:591:52: note: passing argument to parameter here
extern int zfs_destroy_snaps(zfs_handle_t *, char *, boolean_t);
                                                   ^
4 warnings and 3 errors generated.
error: command 'cc' failed with exit status 1
*** Error code 1

Stop.
make: stopped in /usr/home/user/iocage

- [ ] Supply what you expected the result or output to be
Successful build
- [ ] Checked that the problem has not already been fixed on `master` if using
 a stable release.
Nothing in GitHub Issue

**Comment by skarekrow** [comment]
This is an upstream py-libzfs failure, please report that there :)
