### ISSUE TITLE
Docs out of date

### ISSUE THREAD

**Issue by mcarlton00** [iocage/iocage#598]
https://iocage.readthedocs.io/en/latest/ is still reporting that the latest is version 0.9.9.2 built on 09/30/2017, while it looks like the current version is 0.9.10.  There's been a lot of PRs and commits cleaning up and making things easier to understand, it'd be nice to have the official docs reflect the new status rather than digging through the repo

**Comment by Mrt134** [comment]
So far, it looks like Read the Docs isn't grabbing and updating from the source files in the /doc/ directory. Can you check your Read the Docs Account/Settings and see if there is some kind of error, @skarekrow ?

**Comment by skarekrow** [comment]
Fixed :) Thanks for the report!
