### ISSUE TITLE
Can't modify template while other jails are running

### ISSUE THREAD

**Issue by tehfink** [iocage/iocage#60]
Trying to change the template value on a template jail, while a jail based on it is running, results in an error:
```bash
# iocage set template=no template-01
ERROR: cannot unmount '/iocage/jails/762c9987-184b-43da-a0ff-915acc0789ec/root': Device busy
```
Apparently, one must first stop *all* jails created from the template, in order to make changes to the template. I realize this is probably reasonable, but it should perhaps be noted here:
https://github.com/iocage/iocage/blob/3f441b72430c1cb9e1fa993f70ea14d6cf9629e2/doc/source/templates.rst

```bash
# iocage version
Usage: iocage [OPTIONS] COMMAND [ARGS]...

Error: No such command "version".

# git log
commit fa2dbc74281c1daee8d069d27c74c6780bcddefd
Author: Brandon Schneider <brandonschneider89@gmail.com>
Date:   Wed Mar 1 20:56:44 2017 -0600

    Support empty jail creation with `iocage create -e`
    Closes #57
…
```

**Comment by skarekrow** [comment]
Those docs are old and will be replaced in their entirety sooner then later ;) 

So I check to make sure the template isn't running when you convert THAT template, but totally spaced checking for its children. 

Will add this to the pile!


Thanks :+1:

**Comment by skarekrow** [comment]
Alright all fixed, thanks again 👍
