### ISSUE TITLE
Default selection does not work for `iocage fetch`

### ISSUE THREAD

**Issue by 2bithacker** [iocage/iocage#600]
When performing an `iocage fetch` command, a list of releases is given and the prompt indicates that pressing enter will use a default selection, however pressing enter fails with an error that no selection was made.

```
$ iocage --version
Version 0.9.10 2017/12/22

$ sudo iocage fetch
[0] 9.3-RELEASE (EOL)
[1] 10.1-RELEASE (EOL)
[2] 10.2-RELEASE (EOL)
[3] 10.3-RELEASE (EOL)
[4] 10.4-RELEASE
[5] 11.0-RELEASE (EOL)
[6] 11.1-RELEASE
[7] 11.2-RELEASE

Type the number of the desired RELEASE
Press [Enter] to fetch the default selection: (11.2)
Type EXIT to quit: 
Please select an item!
```

I expected the fetch to use the default selection (11.2) and continue working.

**Comment by jsegaert** [comment]
I cannot reproduce this on master; I suppose this was fixed already.

**Comment by skarekrow** [comment]
This was indeed fixed already in master some time ago.
