### ISSUE TITLE
Jail fails to start when depends jail is already running

### ISSUE THREAD

**Issue by davefullard** [iocage/iocage#608]
Make sure to follow and check these boxes before submitting an issue! Thank you.

- [X] Supply `iocage --version`
- [X] Supply the commands used, along with any steps to recreate it.
- [X] Provide the output from the command you issued.
- [X] Supply what you expected the result or output to be
- [X] Checked that the problem has not already been fixed on `master` if using
 a stable release.

### Version
Version 0.9.10 2017/12/22

### Commands used and output
```
[dave@tardis ~]$ sudo iocage set depends="pgsql" nextcloud
Property: depends has been updated to pgsql
[dave@tardis ~]$ sudo iocage start nextcloud
pgsql is already running!
[dave@tardis ~]$
```

### Expected output
```
[dave@tardis ~]$ sudo iocage start nextcloud
* Starting nextcloud
  + Started OK
  + Starting services OK
```

No previous bug has been filed.

**Comment by skarekrow** [comment]
Closed by #622
