### ISSUE TITLE
Jail starts after creation. Why?

### ISSUE THREAD

**Issue by ole-db** [iocage/iocage#609]
Hi,

- [ ] Supply `iocage --version`
master branch

After creation of a jail it starts automatically. The expected behaviour would be that you have to start it manually. 

Is this a required feature?
If yes, how to create a jail without auto start?

**Comment by skarekrow** [comment]
What command did you issue? If you supplied boot=on, that is the expected behavior.

**Comment by ole-db** [comment]
I'm sorry, you are right. I created it with boot=on. But:

`Auto-boot

Make sure :command:`iocage_enable="YES"` is set in :file:`/etc/rc.conf`.

To enable a jail to auto-boot during a system boot, simply run:

:samp:`# iocage set boot=on UUID|NAME`

.. index:: Boot Priority`

https://github.com/iocage/iocage/blob/master/doc/source/advanced-use.rst#auto-boot

This talks about start on boot, not on creation. I think this are different cases start on boot and start on creation.

**Comment by skarekrow** [comment]
Yeah we should clarify this more @Mrt134
