### ISSUE TITLE
iocage environment cleaning issue?

### ISSUE THREAD

**Issue by agshekeloh** [iocage/iocage#610]
Make sure to follow and check these boxes before submitting an issue! Thank you.

- [ ] Supply `iocage --version`

storm~;iocage -v
Version 1.0 ALPHA 1

Just ran "make install" to grab latest

- [ ] Supply the commands used, along with any steps to recreate it.

My understanding: exec_clean=1 should purge the environment. Even if I'm backwards, one of these commands below should return nothing.

storm~;iocage get -rh exec_clean
www2    1
www1    0

storm~;iocage exec www1 env | grep SSH
SSH_CLIENT=203.0.113.70 59076 22
SSH_AUTH_SOCK=/tmp/ssh-ZfvZOatcsu/agent.60492
SSH_TTY=/dev/pts/2
SSH_CONNECTION=203.0.113.70 59076 203.0.113.50 22

storm~;iocage exec www2 env | grep SSH
SSH_CLIENT=203.0.113.70 59076 22
SSH_AUTH_SOCK=/tmp/ssh-ZfvZOatcsu/agent.60492
SSH_TTY=/dev/pts/2
SSH_CONNECTION=203.0.113.70 59076 203.0.113.50 22

- [ ] Supply what you expected the result or output to be

I expected one or the other of these to not match my host's shell's SSH environment.

- [ ] Checked that the problem has not already been fixed on `master` if using
 a stable release.

Updated right before verifying.

**Comment by skarekrow** [comment]
Seems to be an upstream issue:
```
root@freenas:~ # jail -c ip4.saddrsel=1 ip4=new ip6.saddrsel=1 ip6=new name=ioc-foo host.domainname=none host.hostname=foo path=/mnt/iocage/jails/foo/root securelevel=2 host.hostuuid=foo devfs_ruleset=4 enforce_statfs=2 children.max=0 allow.set_hostname=1 allow.sysvipc=0 sysvmsg=new sysvsem=new sysvshm=new allow.raw_sockets=0 allow.chflags=0 allow.mount=0 allow.mount.devfs=0 allow.mount.nullfs=0 allow.mount.procfs=0 allow.mount.tmpfs=0 allow.mount.zfs=0 allow.quotas=0 allow.socket_af=0 exec.prestart=/usr/bin/true exec.poststart=/usr/bin/true exec.prestop=/usr/bin/true exec.stop="/bin/sh /etc/rc.shutdown" exec.clean=0 exec.timeout=60 stop.timeout=30 mount.fstab="/mnt/iocage/jails/foo/fstab" mount.devfs=1 mount.fdescfs=1 allow.dying exec.consolelog="/mnt/iocage/log/ioc-foo-console.log" persist
root@freenas:~ # jls
   JID  IP Address      Hostname                      Path
     6                  foo                           /mnt/iocage/jails/foo/root
root@freenas:~ # jexec 6 env | grep SSH
SSH_CLIENT=192.168.122.1 48540 22
SSH_CONNECTION=192.168.122.1 48540 192.168.122.111 22
SSH_TTY=/dev/pts/1
root@freenas:~ # jail -r 6
root@freenas:~ # jail -c ip4.saddrsel=1 ip4=new ip6.saddrsel=1 ip6=new name=ioc-foo host.domainname=none host.hostname=foo path=/mnt/iocage/jails/foo/root securelevel=2 host.hostuuid=foo devfs_ruleset=4 enforce_statfs=2 children.max=0 allow.set_hostname=1 allow.sysvipc=0 sysvmsg=new sysvsem=new sysvshm=new allow.raw_sockets=0 allow.chflags=0 allow.mount=0 allow.mount.devfs=0 allow.mount.nullfs=0 allow.mount.procfs=0 allow.mount.tmpfs=0 allow.mount.zfs=0 allow.quotas=0 allow.socket_af=0 exec.prestart=/usr/bin/true exec.poststart=/usr/bin/true exec.prestop=/usr/bin/true exec.stop="/bin/sh /etc/rc.shutdown" exec.clean=1 exec.timeout=60 stop.timeout=30 mount.fstab="/mnt/iocage/jails/foo/fstab" mount.devfs=1 mount.fdescfs=1 allow.dying exec.consolelog="/mnt/iocage/log/ioc-foo-console.log" persist
root@freenas:~ # jls
   JID  IP Address      Hostname                      Path
     7                  foo                           /mnt/iocage/jails/foo/root
root@freenas:~ # jexec 7 env | grep SSH                                                                                                                                                                                                                  SSH_CLIENT=192.168.122.1 48540 22
SSH_CONNECTION=192.168.122.1 48540 192.168.122.111 22
SSH_TTY=/dev/pts/1
```

**Comment by agshekeloh** [comment]
Just realized that ten seconds ago, thanks.

I'll go poke current@, closing.

**Comment by skarekrow** [comment]
Thanks! I was going to bug somebody, but it's more fun if you do.

**Comment by gronke** [comment]
FYI: libiocage entirely skips exec_clean. Insead the environment variables are explicitly stated in the `subprocess.Popen()` call by passing them as `env` argument. This was done because iocage jail configuration properties are passed to `exec_*` hooks and exec_clean which exec_clean=1 would have prevented. The effect is the same!

https://github.com/iocage/libiocage/blob/1528af01491df18090903e1ddb3593b82fdd35ee/iocage/Jail.py#L2005-L2008

**Comment by skarekrow** [comment]
iocage will manually honor this.
