### ISSUE TITLE
Feature request: make rc.conf-creation more flexible

### ISSUE THREAD

**Issue by abelbabel** [iocage/iocage#615]
Hi,

when using

`iocage create ...`

iocage creates a `rc.conf`-file with more-or-less useful defaults. It would be better if

1. `rc.conf-`content would not be hard coded in

  https://github.com/iocage/iocage/blob/master/iocage_lib/ioc_create.py

`create_rc() `at the end

2. `rc.conf`-content would be variable.

Therefore it might be a good idea, if a default `rc.conf` file from e.g. `/iocage/` would be copied into the jail to be created. This file can be changed by users before calling `iocage create`.

Regards,
abelbabel

**Comment by skarekrow** [comment]
This *should* work with templates how you suggest, have you tried using those?

**Comment by abelbabel** [comment]
Yes.

Since iocage allows creation of jails without using templates this won't address people not willing to use templates and still being able to be more flexible.

Furthermore it would be an enhancement when using templates since you won't need to modify the rc.conf of a template jail on each template creation when it gets a proper default rc.conf from the beginning ...

**Comment by gronke** [comment]
My opinion on this topic is that iocage should not manipulate the jails `/etc/rc.conf` file. Instead you will find libiocage disabling sendmail and syslog in the releases `rc.conf` when initially fetching the release. Users may alter this file to set a different default for jails that are newly created from that release.

When scripting with Python, users of libiocage may use the jail objects [RCConf class](https://github.com/iocage/libiocage/blob/master/iocage/Config/Jail/File/RCConf.py) instance. It inherits from [ConfigFile](https://github.com/iocage/libiocage/blob/master/iocage/Config/Jail/File/__init__.py#L65) where you can find the public methods to work with a `Jail.rc_conf` property.

**Comment by skarekrow** [comment]
> My opinion on this topic is that iocage should not manipulate the jails `/etc/rc.conf` file. Instead you will find libiocage disabling sendmail and syslog in the releases `rc.conf` when initially fetching the release. Users may alter this file to set a different default for jails that are newly created from that release.
> 
> When scripting with Python, users of libiocage may use the jail objects [RCConf class](https://github.com/iocage/libiocage/blob/master/iocage/Config/Jail/File/RCConf.py) instance. It inherits from [ConfigFile](https://github.com/iocage/libiocage/blob/master/iocage/Config/Jail/File/__init__.py#L65) where you can find the public methods to work with a `Jail.rc_conf` property.

The same end result ;) Just approached from different directions.

**Comment by sipnek** [comment]
Also, there is a deprecated option in [iocage_lib/ioc_create.py](https://github.com/iocage/iocage/search?q=sendmail&unscoped_q=sendmail):
sendmail_enable="NONE"

According to the manual it should now read:
sendmail_enable="NO"
