### ISSUE TITLE
Cut a release or coordinate a sysutils/iocage-devel port

### ISSUE THREAD

**Issue by sporkman** [iocage/iocage#628]
I just started evaluating iocage alongside CBSD and noticed that I'm working with code that's nearly a year old. Would you folks consider either cutting a new release and pushing that into the ports tree, or if you're nervous about the influx of people reporting new bugs, perhaps revive the iocage-devel port?

I can't help but feel getting more casual users into the mix wouldn't be good for surfacing bugs (and fixes).

**Comment by kpfleming** [comment]
This can be closed, as ```sysutils/iocage-devel``` exists.
