### ISSUE TITLE
http_proxy support?

### ISSUE THREAD

**Issue by kairu0** [iocage/iocage#64]
Hello,

I have set http_proxy and HTTP_PROXY environment variables and am launching "iocage fetch", but the command does not seem to be using my proxy setting.

> requests.exceptions.ConnectionError: HTTPSConnectionPool(host='www.freebsd.org', port=443): Max retries exceeded with url: /security/unsupported.html (Caused by NewConnectionError('<requests.packages.urllib3.connection.VerifiedHTTPSConnection object at 0x805b89150>: Failed to establish a new connection: [Errno 65] No route to host',))

May I confirm if this is supported?

**Comment by skarekrow** [comment]
It is not supported currently, but this could possibly be added. I don't use proxies, so this isn't something I'll be coming around to very soon, sorry about that!

**Comment by kairu0** [comment]
No problem. I just have my jail hosts' management IPs on secured VLANs where NAT is not permitted.

**Comment by skarekrow** [comment]
Ah! Well thankfully I don't do any magic with fetching. So you can manually create the dataset (`POOL/iocage/releases/RELEASE` and `POOL/iocage/releases/RELEASE/root`) and extract the files there. Or you can create the `POOL/iocage/download/RELEASE` dataset and drop those txz files there and it will use them.

ANNNND you can use the file mode if you already have them and don't want to create any datasets yourself :D

Hopefully that's not too big of a PITA in the meantime.

Thanks for the issue 👍

**Comment by skarekrow** [comment]
OK, adding this support looks fairly easy, I'll add it shortly if you can be a guinea pig and tell me if it works?

**Comment by skarekrow** [comment]
Perhaps this doesn't require any additions from me, their documentation ([requests](http://docs.python-requests.org/en/latest/user/advanced/#proxies)) states that it honors env variables. Is your proxy an HTTPS one?

**Comment by kairu0** [comment]
Happy to test. My proxy is plain http. I have tried setting http_proxy, HTTP_PROXY, but it doesn't seem to honor them.

**Comment by skarekrow** [comment]
That may be the issue, as this is trying to connect to the HTTPS version of FreeBSD to parse the EOL status of releases. Line 72 in `lib/ioc_fetch`. I could try changing that to HTTP by default, but then somebody with a HTTPS proxy might complain :D

You can try changing that line in yours and letting me know.

EDIT: It seems it forcefully redirects to HTTPS. Perhaps commenting out line 132 and supplying a empty list `eol = []` may prove a better option entirely.

**Comment by skarekrow** [comment]
Ok! So instead of you having to monkey around, I have added the `-NE` option to fetching, which I *think* should resolve your issues.
