### ISSUE TITLE
Install requirements with Makefile

### ISSUE THREAD

**Issue by merkleID** [iocage/iocage#652]
Hi,
had this issue today

```sh-session 
root@fbsd:~/git/iocage # make install
echo -e "import os\ntry:\n  if not os.listdir('"/usr/src"'): exit('"/usr/src" must be populated!')\nexcept FileNotFoundError:\n  exit('"/usr/src" must be populated!')" | python3
/bin/sh: python3: not found
*** Error code 127

Stop.
make: stopped in /root/git/iocage
root@fbsd:~/git/iocage # freebsd-version
11.2-RELEASE-p4
root@fbsd:~/git/iocage #
```

**Comment by skarekrow** [comment]
You need to install python3 :)

**Comment by merkleID** [comment]
Python3.6 IS installed as I followed all the instructions.
Maybe iocage is wrong searching it?

**Comment by gronke** [comment]
> Maybe iocage is wrong searching it?

iocage is not searching for it. It assumes that python3 symlinks to the right version of Python 3, which is not the case on my HardenedBSD hosts, but on FreeBSD.

**Comment by merkleID** [comment]
I'm not a python expert, so I symlinked python3 to python3.6 and it worked.
After that, compilation was ok but everytime I typed 'iocage' I got  'click module' not found as answer.
I gave up and I installed the ports version.

**Comment by gronke** [comment]
> I'm not a python expert, so I symlinked python3 to python3.6 and it worked.

Glad to hear you could resolve the first issue locally. I wonder why the Makefile of iocage does not install requirements from `requirements.txt`.

@lucaonelogin could you check if it works after running `python3.6 -m pip install -Ur requirements.txt` from the source directory? Probably the dependency was already installed by installing the port, but you could check anyway :)

**Comment by merkleID** [comment]
Here's the output:

root@fbsd:~/git/iocage # python3.6 -m pip install -Ur requirements.txt
Collecting click>=6.7 (from -r requirements.txt (line 1))
  Downloading https://files.pythonhosted.org/packages/fa/37/45185cb5abbc30d7257104c434fe0b07e5a195a6847506c074527aa599ec/Click-7.0-py2.py3-none-any.whl (81kB)
    100% |################################| 81kB 2.2MB/s
Requirement already up-to-date: texttable>=1.2.1 in /usr/local/lib/python3.6/site-packages (from -r requirements.txt (line 2)) (1.4.0)
Collecting requests>=2.18.4 (from -r requirements.txt (line 3))
  Downloading https://files.pythonhosted.org/packages/65/47/7e02164a2a3db50ed6d8a6ab1d6d60b69c4c3fdf57a284257925dfc12bda/requests-2.19.1-py2.py3-none-any.whl (91kB)
    100% |################################| 92kB 3.8MB/s
Requirement already up-to-date: coloredlogs>=9.0 in /usr/local/lib/python3.6/site-packages (from -r requirements.txt (line 4)) (10.0)
Requirement already up-to-date: dulwich>=0.18.6 in /usr/local/lib/python3.6/site-packages (from -r requirements.txt (line 5)) (0.19.6)
Requirement already up-to-date: netifaces>=0.10.6 in /usr/local/lib/python3.6/site-packages (from -r requirements.txt (line 6)) (0.10.7)
Requirement already satisfied, skipping upgrade: idna<2.8,>=2.5 in /usr/local/lib/python3.6/site-packages (from requests>=2.18.4->-r requirements.txt (line 3)) (2.7)
Requirement already satisfied, skipping upgrade: chardet<3.1.0,>=3.0.2 in /usr/local/lib/python3.6/site-packages (from requests>=2.18.4->-r requirements.txt (line 3)) (3.0.4)
Requirement already satisfied, skipping upgrade: urllib3<1.24,>=1.21.1 in /usr/local/lib/python3.6/site-packages (from requests>=2.18.4->-r requirements.txt (line 3)) (1.23)
Requirement already satisfied, skipping upgrade: certifi>=2017.4.17 in /usr/local/lib/python3.6/site-packages (from requests>=2.18.4->-r requirements.txt (line 3)) (2018.8.24)
Requirement already satisfied, skipping upgrade: humanfriendly>=4.7 in /usr/local/lib/python3.6/site-packages (from coloredlogs>=9.0->-r requirements.txt (line 4)) (4.16.1)
iocage 0.9.10 has requirement click==6.7, but you'll have click 7.0 which is incompatible.
iocage 0.9.10 has requirement coloredlogs==7.0, but you'll have coloredlogs 10.0 which is incompatible.
iocage 0.9.10 has requirement requests==2.17.3, but you'll have requests 2.19.1 which is incompatible.
iocage 0.9.10 has requirement texttable==0.9.0, but you'll have texttable 1.4.0 which is incompatible.
Installing collected packages: click, requests
  Found existing installation: click 6.7
    Uninstalling click-6.7:
      Successfully uninstalled click-6.7
  Found existing installation: requests 2.18.4
    Uninstalling requests-2.18.4:
      Successfully uninstalled requests-2.18.4
Successfully installed click-7.0 requests-2.19.1

**Comment by skarekrow** [comment]
> > Maybe iocage is wrong searching it?
> 
> iocage is not searching for it. It assumes that python3 symlinks to the right version of Python 3, which is not the case on my HardenedBSD hosts, but on FreeBSD.

Not the case as of Oct 5, closing again.

**Comment by skarekrow** [comment]
Reopened as we should be installing those, I thought they already were.
