### ISSUE TITLE
Jail won't start. Gets allow_mlock error

### ISSUE THREAD

**Issue by olejak** [iocage/iocage#657]
Make sure to follow and check these boxes before submitting an issue! Thank you.

- [x] Supply `iocage --version`
- [x] Supply the commands used, along with any steps to recreate it.
- [x] Provide the output from the command you issued.
- [x] Supply what you expected the result or output to be
- [x] Checked that the problem has not already been fixed on `master` if using
 a stable release.

Installed from github:

```
pkg install python36 git-lite libgit2 cython3 py36-pip
git clone --recursive https://github.com/iocage/iocage
make install
```

```
iocage --version
Version 1.0 ALPHA 1
```

```
# iocage fetch
[0] 9.3-RELEASE (EOL)
[1] 10.1-RELEASE (EOL)
[2] 10.2-RELEASE (EOL)
[3] 10.3-RELEASE (EOL)
[4] 10.4-RELEASE
[5] 11.0-RELEASE (EOL)
[6] 11.1-RELEASE (EOL)
[7] 11.2-RELEASE

Type the number of the desired RELEASE
Press [Enter] to fetch the default selection: (Not a RELEASE)
Type EXIT to quit: 7
```

```
# iocage create -r 11.2-RELEASE -n test
test successfully created!
```

***
```
# iocage start test
* Starting test
  + Start FAILED
jail: unknown parameter: allow.mlock
```

I would expect the jail to start

```
# uname -a
FreeBSD frank 12.0-CURRENT FreeBSD 12.0-CURRENT #0 7ad4fada6(HEAD): Thu Aug  2 11:37:15 EDT 2018     root@hydra:/usr/obj/root/jenkins/workspace/TrueOS_-_Stable_-_Complete/TrueOS_Stable/amd64.amd64/sys/GENERIC  amd64
```

```
freebsd-version -ku
12.0-CURRENT
12.0-CURRENT
```

Dosn't see to be fixed in this combination of TrueOS and iocage. [Please look here](https://groups.google.com/forum/#!topic/iocage/6Eh_9-cHRFQ)

**Comment by skarekrow** [comment]
@olejak Do you still experience this on 1.0 RELEASE and an upgraded TrueOS?

**Comment by sonicaj** [comment]
ping @olejak

**Comment by sonicaj** [comment]
Please confirm if the issue exists on latest master

**Comment by olejak** [comment]
I can’t replicere the issue. Must have been solved in latest master. Great work!
