### ISSUE TITLE
allow attaching metadata to a jail

### ISSUE THREAD

**Issue by Licenser** [iocage/iocage#66]
In addition to the 'vetted' properties that can be attached to a jail it would be really nice if something like metadata (i.e. custom tags?) could be attached to it.

Perhaps something like:

```
iocage create metadata.my_key=1 metadata.other_key=2 ...
```

**Comment by kevinmeziere** [comment]
metadata.my_key is a bit of a smartos vmadm'ism. There are existing issues with how vmadm handles this sort of thing, mainly having keys of depth >1 or lists. IMO a "metadata" field that was just a string would work better. The user or application that was r/w to the field could put json in there if it chooses and later parse it out. Over all a simpler implementation and less places for errors to creep in.

**Comment by skarekrow** [comment]
We used to have a `comment` property that served this purpose, and I totally forgot to port. It would only accept strings, I can add that back in shortly :)
