### ISSUE TITLE
vnet and mtu != 1500

### ISSUE THREAD

**Issue by ole-db** [iocage/iocage#661]
version: last master from github

I have a bridge with Vlan Interace as member. vlan interface ande bridge mtu is set to 1400. On jail start vnet interface mtu is set to 1400. But inside jail, the mtu is set to 1500.

```
Host # ifconfig 
(...)
bridge0: flags=8843<UP,BROADCAST,RUNNING,SIMPLEX,MULTICAST> metric 0 mtu 1400
(...)
em0.4000: flags=8943<UP,BROADCAST,RUNNING,PROMISC,SIMPLEX,MULTICAST> metric 0 mtu 1400
(...)
vnet0:17: flags=8943<UP,BROADCAST,RUNNING,PROMISC,SIMPLEX,MULTICAST> metric 0 mtu 1400
(...)

Jail # ifconfig epair0b
epair0b: flags=8843<UP,BROADCAST,RUNNING,SIMPLEX,MULTICAST> metric 0 mtu 1500
(...)
```

This results in connection Problems. I have to set mtu by hand:
```
Jail # ifconfig epair0b mtu 1400
```

Is this the expected behaviour?

**Comment by skarekrow** [comment]
No, it should be setting it. Line 1023-1024 of ioc_start.py must not be working as intended.

**Comment by bartekrutkowski** [comment]
@skarekrow there's no lines 1023-1024 in ioc_start.py?

**Comment by skarekrow** [comment]
@bartekrutkowski Things move as development happens ;) https://github.com/iocage/iocage/blob/master/iocage_lib/ioc_start.py#L990
