### ISSUE TITLE
Can't use 'clear' command or use nano over ssh

### ISSUE THREAD

**Issue by bcampen** [iocage/iocage#665]
With the update to FreeNAS 11.2, in none of my iocage jails I am able to call the 'clear' command over ssh. When I try to open nano inside of a jail, I only get one line with the controls at the bottom, but can't edit anything.

- Version 1.0 ALPHA 1
- When I open nano, the only thing I see is this (one line):
`^X Exit          ^R Read File     ^\ Replace       ^U Uncut Text    ^T To Spell      ^_ Go To Line    M-E Redo         M-6 Copy Text    ^Q Where Was     M-W Next`

**Comment by skarekrow** [comment]
This isn't an issue in master, the branch in FreeNAS 11.2 RC1 is behind, being tracked in https://redmine.ixsystems.com/issues/52237
