### ISSUE TITLE
Filesystem layout

### ISSUE THREAD

**Issue by ankerstal** [iocage/iocage#671]
Hi!

Im using iocage ` Version 0.9.10 2017/12/22` and would like to change the filesystem layout for my jails. I would for example like to have:
- /
- /var
- /tmp
- /usr 
and so on. 

Is this possible using the current version of iocage?

**Comment by gronke** [comment]
@ankerstal I do not understand what you intend to do. Can you please elaborate?

**Comment by ankerstal** [comment]
Hi,

I want to have different filesystems for differnet mountpoints. (So I can have different quotas for /var and /tmp for example)

**Comment by skarekrow** [comment]
Currently this isn't possible, and I'm not sure how we can cleanly do this at jail creation time. The closes you will get is the old basejails, but that doesn't quite do what you want here. You're better off not using iocage if you need your jails to be created to those specifications.
