### ISSUE TITLE
DHCP for IPv4 and rtadv for IPV6 don't work at the same time

### ISSUE THREAD

**Issue by chrisb86** [iocage/iocage#674]
Make sure to follow and check these boxes before submitting an issue! Thank you.

iocage Version 0.9.10 2017/12/22
FreeBSD 11.2-RELEASE.

I try to create a jail that get's its ip4_addr from DHCP and and the ip6_addr via router advertisement.

I create the jail like that:
```
iocage create -r 11.2-RELEASE -n basic\
  boot=off\
  allow_raw_sockets=1 \
  vnet=on\
  bpf=yes\
  dhcp=on\
  defaultrouter=192.168.178.1\
  defaultrouter6="2003:cb:af28:e201::dead:beef"\
  ip6_addr="vnet0|accept_rtadv"
```
When I start the jail, it get's an IPv4 address but no IPv6 address. Even if I run _service rtsold restart_.

When I set _dhcp=off_ and run _service rtsold restart_ it get's an IPv6 address.
It seems that the DHCP option for IPv4 addresses somehow blocks the router advertisement.

**Comment by chrisb86** [comment]
The fact that rtsold is not startet at the startup uf the jail even if I put it in the rc.conf of the jail is another point that maybe should be addressed in another issue.

**Comment by skarekrow** [comment]
This should all work in master.
