### ISSUE TITLE
Iocage not starting on boot

### ISSUE THREAD

**Issue by ddavtian** [iocage/iocage#676]
I can't seem to be able to get a newly created jail to start on boot. I have done the following on creating an iocage based jail. It creates and starts just fine, but on a system reboot it doesn't come up automatically. I need to manually start them up. Any help is very much appreciated.

**Versions**

`FreeNAS-11.2-RC1`
`Version	1.0 ALPHA 1`

**Commands**

```
iocage create -n dave -r 11.2-RELEASE ip4_addr="vnet0|192.168.1.100/24" defaultrouter="192.168.1.1" vnet="on" allow_raw_sockets="1" boot="on"
dave successfully created!
* Starting dave
  + Started OK
  + Configuring VNET OK
  + Starting services OK
```
I have also added the following `rc.conf `tunable but had no success.

`iocage_enable=YES`

**Comment by skarekrow** [comment]
This is actually a freenas specific issue as the iocage rc file isn’t used on boot. It should be working the way you’re using it, so if you could file an issue over there that would be appreciated so we can fix it in the freenas tracker.

**Comment by ddavtian** [comment]
@skarekrow thank you, reported: `https://redmine.ixsystems.com/issues/56247`
