### ISSUE TITLE
Creating a DHCP 10.3-RELEASE jail in iocage is unable to start. 

### ISSUE THREAD

**Issue by jaxjexjox** [iocage/iocage#678]
.....Make sure to follow and check these boxes before submitting an issue! Thank you....

If I create a brand new jail, from standard jail creation template in FreeNAS 11.2 RC1 but stipulate the 10.3-RELEASE build (yes, it's downloaded into iocage/releases) - then start the jail, it fails (error below)

I've tested across multiple machines, they've said the problem should be reported here.

oot@freenas:~ # iocage --version
Version 1.0 ALPHA 1
root@freenas:~ # uname -r
11.2-STABLE

```

> root@freenasnew[~]# iocage list
> +-----+-------------+-------+--------------+------+
> | JID |    NAME     | STATE |   RELEASE    | IP4  |
> +=====+=============+=======+==============+======+
> | 1   | sabnzbdtest | up    | 11.2-RELEASE | DHCP |
> +-----+-------------+-------+--------------+------+
> | -   | sickrage_1  | down  | 10.3-RELEASE | DHCP |
> +-----+-------------+-------+--------------+------+
> root@freenasnew[~]# iocage start sickrage_1
> * Starting sickrage_1
>   + Started OK
>   + Configuring VNET OK
**> ifconfig: illegal option -- f**
> usage: ifconfig [-L] [-C] [-g groupname] interface address_family [address [dest_address]]
>                 [parameters]
>        ifconfig interface create
>        ifconfig -a [-L] [-C] [-g groupname] [-d] [-m] [-u] [-v] [address_family]
>        ifconfig -l [-d] [-u] [address_family]
>        ifconfig [-L] [-C] [-g groupname] [-d] [-m] [-u] [-v]
> Traceback (most recent call last):
>   File "/usr/local/bin/iocage", line 10, in <module>
>     sys.exit(cli())
>   File "/usr/local/lib/python3.6/site-packages/click/core.py", line 722, in __call__
>     return self.main(*args, **kwargs)
>   File "/usr/local/lib/python3.6/site-packages/click/core.py", line 697, in main
>     rv = self.invoke(ctx)
>   File "/usr/local/lib/python3.6/site-packages/click/core.py", line 1066, in invoke
>     return _process_result(sub_ctx.command.invoke(sub_ctx))
>   File "/usr/local/lib/python3.6/site-packages/click/core.py", line 895, in invoke
>     return ctx.invoke(self.callback, **ctx.params)
>   File "/usr/local/lib/python3.6/site-packages/click/core.py", line 535, in invoke
>     return callback(*args, **kwargs)
>   File "/usr/local/lib/python3.6/site-packages/iocage_cli/start.py", line 54, in cli
>     ioc.IOCage(jail=jail, rc=rc).start()
>   File "/usr/local/lib/python3.6/site-packages/iocage_lib/iocage.py", line 1628, in start
>     callback=self.callback
>   File "/usr/local/lib/python3.6/site-packages/iocage_lib/ioc_start.py", line 66, in __init__
>     self.__start_jail__()
**>   File "/usr/local/lib/python3.6/site-packages/iocage_lib/ioc_start.py", line 467, in __start_jail__
>     "message": "  + Acquiring DHCP address: FAILED," 
> UnboundLocalError: local variable 'addr' referenced before assignment**
> root@freenasnew[~]# 
```

- [ ] Supply what you expected the result or output to be
To successfully start a jail.

- [ ] Checked that the problem has not already been fixed on `master` if using
 a stable release.

I am unable to do this due to lack of skill. I am using FreeNAS 11.2 RC-1, which I believe is FreeBSD 11.2.

**Comment by jaxjexjox** [comment]
Note, if I go in and edit the jail and turn it into a static IP, it will start. But the stock jail creation template (via UI, I admit) will result in a poorly formed DHCP jail that won't start.

If someone smart there, can tell me a command to type, which will produce a list of DETAILED, all flags configured for a jail in the CLI, I'll gladly run this, against said, new broken jail and provide you the flags.
(Obviously "iocage list" provides only a basic piece of information against a jail)

It may be possible, that the FreeNAS UI is submitting the jail creation to iocage in the backend and stipulating some kind of badly designed jail?

Don't ask why I need 10.3, it's complicated and dumb, regardless, you'd think this would work, yeah?

**Comment by jaxjexjox** [comment]
ALSO! :   I have tried this command from the CLI

root@freenasnew[~]#  iocage create dhcp=on --release 10.3-RELEASE --name "dhcptest" bpf=yes vnet=on

Still produces the same error, sorry.
Here is the iocage get all listing:
```


root@freenasnew[~]# iocage get all dhcptest
CONFIG_VERSION:14
allow_chflags:0
allow_mlock:0
allow_mount:0
allow_mount_devfs:0
allow_mount_nullfs:0
allow_mount_procfs:0
allow_mount_tmpfs:0
allow_mount_zfs:0
allow_quotas:0
allow_raw_sockets:0
allow_set_hostname:1
allow_socket_af:0
allow_sysvipc:0
allow_tun:0
available:readonly
basejail:no
boot:off
bpf:yes
children_max:0
cloned_release:10.3-RELEASE
comment:none
compression:lz4
compressratio:readonly
coredumpsize:off
count:1
cpuset:off
cputime:off
datasize:off
dedup:off
defaultrouter:none
defaultrouter6:none
depends:none
devfs_ruleset:4
dhcp:on
enforce_statfs:2
exec_clean:1
exec_fib:0
exec_jail_user:root
exec_poststart:/usr/bin/true
exec_poststop:/usr/bin/true
exec_prestart:/usr/bin/true
exec_prestop:/usr/bin/true
exec_start:/bin/sh /etc/rc
exec_stop:/bin/sh /etc/rc.shutdown
exec_system_jail_user:0
exec_system_user:root
exec_timeout:60
host_domainname:none
host_hostname:dhcptest
host_hostuuid:dhcptest
host_time:yes
hostid:ae655685-da88-11e8-a238-ac1f6b4876f4
hostid_strict_check:off
interfaces:vnet0:bridge0
ip4:new
ip4_addr:none
ip4_saddrsel:1
ip6:new
ip6_addr:none
ip6_saddrsel:1
jail_zfs:off
jail_zfs_dataset:iocage/jails/dhcptest/data
jail_zfs_mountpoint:none
last_started:none
login_flags:-f root
mac_prefix:02ff60
maxproc:off
memorylocked:off
memoryuse:off
mount_devfs:1
mount_fdescfs:1
mount_linprocfs:0
mount_procfs:0
mountpoint:readonly
msgqqueued:off
msgqsize:off
nmsgq:off
notes:none
nsemop:off
nshm:off
nthr:off
openfiles:off
origin:readonly
owner:root
pcpu:off
priority:99
pseudoterminals:off
quota:none
release:10.3-RELEASE-p29
reservation:none
resolver:/etc/resolv.conf
rlimits:off
securelevel:2
shmsize:off
stacksize:off
state:down
stop_timeout:30
swapuse:off
sync_state:none
sync_target:none
sync_tgt_zpool:none
sysvmsg:new
sysvsem:new
sysvshm:new
template:no
type:jail
used:readonly
vmemoryuse:off
vnet:on
vnet0_mac:02ff603414cf 02ff603414d0
vnet1_mac:none
vnet2_mac:none
vnet3_mac:none
vnet_default_interface:none
vnet_interfaces:none
wallclock:off
root@freenasnew[~]#
```

**Comment by jaxjexjox** [comment]
Final comment, I apologise if this is working as intended, but one would think, the ability to pull down an old release, would allow you to still use it reliably.  Thanks.

**Comment by skarekrow** [comment]
You can use old ones just fine, but in this particular case a bad option gets sent to ifconfig. I’m not sure this isn’t much a priority as 10.3 is EOL but we should handle this better. 

Thanks for the bug!

**Comment by jaxjexjox** [comment]
Thanks, I wasn't sure if I was doing something wrong or if FreeNAS UI was pushing something incorrectly.
Fix at your leisure, obviously1


I'm very new to all this and more a windows guy, can you test something for me, totally separate which I've encountered. (I can't figure out how to test on my FreeBSD VM, I'm not smart enough to make a zpool)

Just make a jail with a name of "jailname_1"
then, 
iocage export jailname_1
iocage destroy jailname_1
iocage import jailname_1

Need to know if I've found a FreeNAS bug or a FreeBSD bug (it breaks here)

**Comment by skarekrow** [comment]
This is actually filed in freenas already as
https://redmine.ixsystems.com/issues/56211

**Comment by jaxjexjox** [comment]
Sure, that's me, what I want to know, is this fault in iocage or just
freenas?

I'm not smart enough to test on freebsd standalone

**Comment by skarekrow** [comment]
Ah Disk! Got used to seeing you by name there. It’s an iocage bug. Just a
bad split on the name most likely.

**Comment by jaxjexjox** [comment]
Wait so it is in bsd and therefore I need to wait for it to be fixed up
there, before it's pulled down into FreeNAS? :(


It's always best to stop using the same name across services, the internet
has lost its anonymity!

**Comment by skarekrow** [comment]
FreeNAS is FreeBSD :) as for waiting, when I get the bug fixed I will be
putting it into freenas for whatever release gets it. Likely 11.2-U1 at
this point. But I’ll talk to William (my lead there) and see if we can get
it prioritized as this would break plugin export and imports.

**Comment by jaxjexjox** [comment]
Thanks for the help as usual.
Josh kinda offered me a job a while back, until he realised I was in
Australia.  I offered to work remotely dead cheap to learn, but sadly no
bite.

Thanks again

**Comment by skarekrow** [comment]
No problem! That’s too bad, Josh was a great guy to work with. Thanks for
all the good tickets, we’ve found a lot of issues because of your
assistance :)

**Comment by jaxjexjox** [comment]
Eventually I'll get on the payroll :)
No problems, I'll keep testing!

**Comment by skarekrow** [comment]
This all works thanks to #515 which you'll see in 11.3
