### ISSUE TITLE
Feature - iocage used for resource managment. 

### ISSUE THREAD

**Issue by pr1ntf** [iocage/iocage#68]
In large environments, it's easy to lose track of resources fast. 

I know iocage df has come in handy many times, but RAM usage stats and possibly even CPU core.

'iocage inuse --all' would be cool. 
Or even 'iocage top'?

**Comment by skarekrow** [comment]
+1. Could be a fun thing to hack on? *nudge nudge wink win*

**Comment by pannon** [comment]
@pr1ntf @skarekrow there is a new `top` sub command now to display jail processes for a give jail with top. Also `iocage inuse` with no arguments will dump a CSV of all running jails and all resource values.
Then you can use something like `iocage inuse|cut -f2 -f3 -d,` to display certain fields only.

**Comment by skarekrow** [comment]
Nice! I'm going to close this now since everything is all done.
