### ISSUE TITLE
allow_mount should be set automatically

### ISSUE THREAD

**Issue by asomers** [iocage/iocage#680]
The `allow_mount` jail parameter functions as a master valve for all of the other `allow_mount_*` parameters.  I don't think it makes sense to expose it in iocage, since it's redundant with the others, and those all default to off.  It would be better usability-wise if iocage would automatically set `allow_mount` to the OR of all other `allow_mount` parameters.

**Comment by skarekrow** [comment]
How can I set it to the OR of all others if they only set one? I agree it does seem redundant and I could simply enable it if any of those are enabled.

**Comment by asomers** [comment]
If the user only sets one, then you should use the defaults for the others, right?  They all default to off.  So I think `allow_mount` should be set if any of the other parameters is set.

**Comment by skarekrow** [comment]
Seems reasonable to me.
