### ISSUE TITLE
"iocage list -r" not showing all releases

### ISSUE THREAD

**Issue by agshekeloh** [iocage/iocage#687]
storm~;iocage --version
Version 1.0 RC 2018/11
storm~;uname -a
FreeBSD storm 13.0-CURRENT FreeBSD 13.0-CURRENT r340361 GENERIC  amd64

Existing releases:

storm~;iocage list -r
+---------------+
| Bases fetched |
+===============+
| 9.3-RELEASE   |
+---------------+
| 10.1-RELEASE  |
+---------------+
| 10.4-RELEASE  |
+---------------+
| 11.1-RELEASE  |
+---------------+
| 11.2-LOCAL    |
+---------------+
| 12.0-ALPHA2   |
+---------------+

11.2-LOCAL is a locally butchered version of 11.2, not 11.2-R.

Ran:
storm~;iocage fetch -r 11.2-RELEASE
Fetching: 11.2-RELEASE

Extracting: base.txz...
Extracting: lib32.txz...
Extracting: doc.txz...
Extracting: src.txz...

* Updating 11.2-RELEASE to the latest patch level...
Looking up update.FreeBSD.org mirrors... 2 mirrors found.
Fetching metadata signature for 11.2-RELEASE from update4.freebsd.org... done.
Fetching metadata index... done.
Fetching 2 metadata patches.. done.
Applying metadata patches... done.
Inspecting system... done.
Preparing to download files... done.
Fetching 14 patches.....10.. done.
Applying patches... done.

The following files will be updated as part of updating to 11.2-RELEASE-p4:
/bin/freebsd-version
/usr/bin/gprof
/usr/include/netinet6/in6.h
/usr/include/netinet6/ip6_var.h
/usr/include/x86/specialreg.h
/usr/sbin/wpa_supplicant
/usr/share/man/man4/inet.4.gz
/usr/share/man/man4/inet6.4.gz
/usr/share/man/man4/tcp.4.gz
/usr/share/man/mandoc.db
/usr/src/contrib/wpa/src/rsn_supp/wpa.c
/usr/src/share/man/man4/inet.4
/usr/src/share/man/man4/inet6.4
/usr/src/share/man/man4/tcp.4
/usr/src/sys/amd64/amd64/fpu.c
/usr/src/sys/amd64/amd64/machdep.c
/usr/src/sys/amd64/amd64/pmap.c
/usr/src/sys/amd64/vmm/intel/vmx.c
/usr/src/sys/amd64/vmm/intel/vmx_genassym.c
/usr/src/sys/amd64/vmm/intel/vmx_support.S
/usr/src/sys/conf/newvers.sh
/usr/src/sys/i386/i386/machdep.c
/usr/src/sys/i386/isa/npx.c
/usr/src/sys/kern/imgact_elf.c
/usr/src/sys/kern/kern_context.c
/usr/src/sys/kern/vfs_syscalls.c
/usr/src/sys/kern/vfs_vnops.c
/usr/src/sys/netinet/ip_reass.c
/usr/src/sys/netinet/tcp_reass.c
/usr/src/sys/netinet/tcp_usrreq.c
/usr/src/sys/netinet6/frag6.c
/usr/src/sys/netinet6/in6.h
/usr/src/sys/netinet6/in6_proto.c
/usr/src/sys/netinet6/ip6_var.h
/usr/src/sys/netinet6/sctp6_usrreq.c
/usr/src/sys/netinet6/udp6_usrreq.c
/usr/src/sys/x86/include/specialreg.h
Installing updates... done.

Great! I now have an unbutchered 11.2-RELEASE, right? But it's not showing up as a release.

storm~;iocage list -r
+---------------+
| Bases fetched |
+===============+
| 9.3-RELEASE   |
+---------------+
| 10.1-RELEASE  |
+---------------+
| 10.4-RELEASE  |
+---------------+
| 11.1-RELEASE  |
+---------------+
| 11.2-LOCAL    |
+---------------+
| 12.0-ALPHA2   |
+---------------+

But I can *use* 11.2-RELEASE as a base, even though it's invisible.

storm~;iocage create -r 11.2-RELEASE -b -n dns3
dns3 successfully created!

I also see:

storm~;ls /iocage/download/
10.1-RELEASE    11.1-RELEASE    11.2-RELEASE    9.3-RELEASE
10.4-RELEASE    11.2-LOCAL      12.0-ALPHA2
storm~;ls /iocage/releases/
10.1-RELEASE    11.1-RELEASE    11.2-RELEASE    9.3-RELEASE
10.4-RELEASE    11.2-LOCAL      12.0-ALPHA2

So, it appears that 11.2-RELEASE exists but simply doesn't appear in "iocage list -r".

**Comment by skarekrow** [comment]
Thanks Michael :+1:
