### ISSUE TITLE
allow_mount_fusefs requires fuse.ko to be loaded

### ISSUE THREAD

**Issue by overhacked** [iocage/iocage#688]
Make sure to follow and check these boxes before submitting an issue! Thank you.

- [X] Supply `iocage --version`
- [X] Supply the commands used, along with any steps to recreate it.
- [X] Provide the output from the command you issued.
- [X] Supply what you expected the result or output to be
- [X] Checked that the problem has not already been fixed on `master` if using
 a stable release.

## Install details
- iocage version 1.0 RC 2018/11 (iocage@b3da684ef538d3719d40435d9bdc67eb84bc6a4a)
- FreeBSD 12.0-BETA4

## Steps to reproduce
1. Reboot system _without_ `fuse.ko` loaded.
1. Install iocage HEAD on FreeBSD 12.0 or later (BETA4 at time of report)
1. Create a jail with option `allow_mount_fusefs=1`
1. Start jail

### Expected result
```console
* Starting 73b38dad-6bda-4006-be52-b00c896ebc57                                
  + Started OK
  + Starting services OK
```

### Actual result
```console
* Starting 73b38dad-6bda-4006-be52-b00c896ebc57                                
  + Start FAILED
jail: unknown parameter: allow.mount.fusefs                                    
```

## Commands and output
```console
root@freebsd:~ # iocage create -r 11.2-RELEASE allow_mount_fusefs=1            
73b38dad-6bda-4006-be52-b00c896ebc57 successfully created!                     
root@freebsd:~ # iocage start 73b38d
* Starting 73b38dad-6bda-4006-be52-b00c896ebc57                                
  + Start FAILED
jail: unknown parameter: allow.mount.fusefs                                    

root@freebsd:~ # kldstat
Id Refs Address                Size Name                                       
 1   27 0xffffffff80200000  243cc98 kernel                                     
 2    1 0xffffffff8263d000    22988 if_ena.ko                                  
 3    1 0xffffffff82819000     2678 intpm.ko                                   
 4    1 0xffffffff8281c000      b10 smbus.ko                                   
 5    1 0xffffffff8281d000      acf mac_ntpd.ko                                
 6    1 0xffffffff8281e000   247d20 zfs.ko                                     
 7    1 0xffffffff82a66000     7628 opensolaris.ko                             
 8    1 0xffffffff82a6e000     19e0 fdescfs.ko                                 
 9    1 0xffffffff82a70000     27b0 nullfs.ko                                  
10    1 0xffffffff82a73000     81b0 tmpfs.ko                                   
root@freebsd:~ # kldload fuse.ko
root@freebsd:~ # iocage start 73b38d
* Starting 73b38dad-6bda-4006-be52-b00c896ebc57                                
  + Started OK
  + Starting services OK
root@freebsd:~ #
```

**Comment by skarekrow** [comment]
@asomers Think you can knock this bug out?

**Comment by asomers** [comment]
Done!  This is actually a bug in FreeBSD.  It's already fixed, and will be included in 12.0-RELEASE.

https://svnweb.freebsd.org/base?view=revision&revision=340314
https://svnweb.freebsd.org/changeset/base/340462

**Comment by skarekrow** [comment]
Wonderful! Thanks!

**Comment by overhacked** [comment]
Incredible response time! :star: :fire: Thanks, all!

**Comment by overhacked** [comment]
@asomers, I read through the upstream changes, and I see that libjail loads the filesystem kernel module if allow.mount.«_filesystem name_» is specified. Doesn't this result in all the filesystem modules getting loaded the first time iocage starts a jail? In [`ioc_start.py`](https://github.com/iocage/iocage/blob/master/iocage_lib/ioc_start.py#L332), `__start_jail__()` puts all the parameters on the jail command line whether they are set default or not.

That's not necessarily a bug, but maybe an undesirable side-effect, especially if someone has compiled a custom kernel and disabled one of the filesystems that iocage has a parameter for. Do you think it's worth opening another issue to discuss? This is not something that currently affects me, as I'm running a stock kernel.

**Comment by asomers** [comment]
Yeah, I think that would be a good enhancement.
