### ISSUE TITLE
`devfs_ruleset` property is not set correclty for VNET DHCP jails

### ISSUE THREAD

**Issue by mike-pt** [iocage/iocage#694]
I know this seems similar to a older issues but its not exactly the same.

What I'm seeing is that we do create devfs_ruleset 5 and when setting vnet=on dhcp=on  we are even adding bpf...

The problem is the jail is created with the wrong ruleset
```
iocage get web-nginx | grep rule
devfs_ruleset:4
```

This is using "iocage-devel" port

```
iocage --version
Version 1.0 ALPHA 1
```
We created rule 5 but we tell new jails to use rule 4... 

- [x] Supply `iocage --version`
- [x] Supply the commands used, along with any steps to recreate it.
- [x] Provide the output from the command you issued.
- [x] Supply what you expected the result or output to be
- [x] Checked that the problem has not already been fixed on `master` if using
 a stable release.

**Comment by skarekrow** [comment]
I can understand the confusion here, but the devfs_ruleset being 4 is actually a placeholder for iocage. If it's not 4, it will use whatever is specified. But if it *is* 4, it will generate a jail specific devfs_ruleset and add the rules to it. You can use `jls -n` to see the ruleset.

I'm going to mark this as an enhancment so you can see the right rule with get if the jail is running or when you start the jail it should show it.

**Comment by dlangille** [comment]
I was just about to raise an issue for this after I noticed this:

```
$ sudo iocage start pg93
* Starting pg93
  + Started OK
  + Using devfs_ruleset: 14
  + Starting services OK

$ sudo iocage ge get devfs_ruleset pg93
4

$ cat /iocage/jails/pg93/config.json
{
    "allow_raw_sockets": "1",
    "allow_sysvipc": "1",
    "devfs_ruleset": "4",
    "host_hostname": "pg93.int.unixathome.org",
    "host_hostuuid": "pg93",
    "ip4_addr": "10.55.0.106",
    "jail_zfs_dataset": "iocage/jails/pg93/data",
    "last_started": "2018-12-22 02:07:47",
    "release": "11.2-RELEASE-p7"
}
```

I was confused.
