### ISSUE TITLE
FR: Add support for netgraph (via jng script) 

### ISSUE THREAD

**Issue by mike-pt** [iocage/iocage#695]
Feel free to close if this is a never going to happen kind of thing :)

I've been given a try to iocage recently and I've had no luck so far with dhcp+vnet

However jails.conf and  the jng script provided by freebsd have been working great so far (https://github.com/freebsd/freebsd/blob/master/share/examples/jails/jail.xxx.conf).

It doesn't seem like I have any option to force iocage to use it cause I can't set:
```
# netgraph
	vnet.interface = "ng0_xxx";		# vnet interface(s)
	exec.prestart += "jng bridge xxx em0";	# bridge interface(s)
       exec.poststop += "jng shutdown xxx"; # destroy interface(s)
```

**Comment by skarekrow** [comment]
This is not something I personally have any experience with, so it will have to be implemented by somebody else. Currently iocage creates epairs, the vnet nic you specify with `vnet_default_interface` is just the bridge member iocage will use.

**Comment by mike-pt** [comment]
And that's working fine for DHCP and having pf inside a jail i.e. ? my experience with that wasn't not the best, but maybe I need to try again with 12.0

I think for now if we allows setting `exec.prestart` it would help use alternatives... but ofc the code would have to have some conditionals so it doesn't execute the rest based on vnet_default_interface... and we also need `vnet.interface` for that matter....

**Comment by skarekrow** [comment]
It should work just fine yes. You can already set `exec_prestart` (I encourage you to read the manpage :P). If you set vnet_default_interface to none iocage will not handle the bridging. But it will still create the member interfaces as epairs. That code will need to be extended to support netgraph.

**Comment by mike-pt** [comment]
ah.. yes the man page does offer more help than the online documentation.... I have some reading to do then :D

**Comment by skarekrow** [comment]
If you ever feel the itch to send a PR, docs are a lovely way to contribute :D

**Comment by mike-pt** [comment]
Maybe if I find some time on weekends 😄 btw I noticed the mailing list (linked in the README) doesn't have much activate since 2017... Is that still o good place to place generic questions about implementation on certain environments etc? I.E. this weekend I was playing with with iocage on azure there's some ideas/things I found I would love to discuss, but GHIs are probably not the best place for that

**Comment by skarekrow** [comment]
:D Yep that's a good place to do it. Usually if I find time I'll reply, or a couple users. But it's a pretty low traffic list. Most people just use iocage, and if they hit something bug me here. But more activity could generate fun discussions from other users. I'm always fascinated by the use cases people find.
