### ISSUE TITLE
Enhancement: list base jails

### ISSUE THREAD

**Issue by agshekeloh** [iocage/iocage#696]
In today's iocage-current, there's no way to list "all base jails," or even "flag a jail as a base jail in iocage -l" Brandon suggested I file an enhancement request. I see a couple places where base jail info would be useful.

"iocage list -l" shows templates, but not bases. Base jails based on templates their template, which is true but implies it's a template-based jail. Adding a "base" column here would be useful.

You could add "iocage list -B" to see base jails, modeled after "list -t" with columns like:

JID
NAME
STATE
BASE
IP4

(Not sure we need IP4 there, but if we're modeling after 'list -t' presumably you had reasons and let's be consistent.)

**Comment by skarekrow** [comment]
Closed by https://github.com/iocage/iocage/commit/da4fec1c93a9d314da7ccefd6fe963a30b1b718f

**Comment by skarekrow** [comment]
```
root@freenas[~]# /root/iocage/iocage list -B                         
+-----+------+-------+--------------+-----+
| JID | NAME | STATE |   RELEASE    | IP4 |
+=====+======+=======+==============+=====+
| -   | bar  | down  | 11.2-RELEASE | -   |
+-----+------+-------+--------------+-----+
root@freenas[~]# /root/iocage/iocage list -Bq                        
+------+------+
| NAME | IP4  |
+======+======+
| bar  | none |
+------+------+
```
This will list basejails like normal jails are listed, but only bases are included
