### ISSUE TITLE
pkglist is not a valid property

### ISSUE THREAD

**Issue by mike-pt** [iocage/iocage#697]
`version 0.9.10 2017/12/22`

cmd: `sudo iocage create -r 12.0-RC1 -n mariadb ip4_addr='hn0|172.16.1.6' ip6_addr=none boot=on host_hostname='mariadb.example.local' template='no' bpf='yes' pkglist='/iocage/pkglist-mariadb.json' defaultrouter='172.16.1.1'`

output: pkglist is not a valid property!

I tried to do a quick search on the code and It seems we accept the `--pkglist` parameter but not the property, however the man page does state this is a valid property:

```
     pkglist=[none | path-to-file]
                   A json file listing one package per entry.  Packages are
                   automatically installed when a jail is created.  Works only
                   in combination with the create subcommand.

                   Default: none

                   Source: local
```

- [x] Supply `iocage --version`
- [x] Supply the commands used, along with any steps to recreate it.
- [x] Provide the output from the command you issued.
- [x] Supply what you expected the result or output to be
- [ ] Checked that the problem has not already been fixed on `master` if using
 a stable release.

**Comment by skarekrow** [comment]
It's `--pkglist`, that man page is very old. The current one in master doesn't have this issue.

**Comment by mike-pt** [comment]
Ah ok thanks, I was using this from the ansible role actually and we are supposed to pass pkglist in the properties.... but I'll open a GHI on their repo as this should be easy to fix
