### ISSUE TITLE
importing jails with sequential names breaks.

### ISSUE THREAD

**Issue by jaxjexjox** [iocage/iocage#698]
Make sure to follow and check these boxes before submitting an issue! Thank you.

- [ ] Supply `iocage --version`

1.0 Alpha 1

- [ ] Supply the commands used, along with any steps to recreate it.

iocage export qbittorrent
iocage export qbittorrent1
iocage export qbittorrent2
iocage destroy qbittorrent
iocage destroy qbittorrent1
iocage destroy qbittorrent2
iocage import qbittorrent
iocage import qbittorrent1
iocage import qbittorrent2

I also tried iocage import "qbittorrent"

- [ ] Provide the output from the command you issued.

root@freenasnew[/mnt/SSD/iocage/images]# iocage import qbittorrent
Multiple images found for qbittorrent:
  qbittorrent1_2018-11-28.zip
  qbittorrent2_2018-11-28.zip
  qbittorrent_2018-11-28.zip

- [ ] Supply what you expected the result or output to be

Import correctly

- [ ] Checked that the problem has not already been fixed on `master` if using
 a stable release.

I'm not that smart fellas.
Yeah I can fix this by simply not putting the sequential files in the directory until I import.
I can also fix this by renaming my first jail to qbittorrentoriginal for example.

NOTE:!

Yes, the 3 jails are infact different in content, it's not multiple backups of the same jail.

**Comment by skarekrow** [comment]
Hello! This has already been fixed in master. You can install the `iocage-devel` port to test that out.

```
root@freenas[~]# /root/iocage/iocage create -n bar1 -r 11.2-RELEASE
bar1 successfully created!
root@freenas[~]# /root/iocage/iocage create -n bar2 -r 11.2-RELEASE
bar2 successfully created!
root@freenas[~]# /root/iocage/iocage create -n bar3 -r 11.2-RELEASE
bar3 successfully created!
root@freenas[~]# /root/iocage/iocage export bar1
Exporting dataset: foo/iocage/jails/bar1
Exporting dataset: foo/iocage/jails/bar1/root

Preparing zip file: /mnt/foo/iocage/images/bar1_2018-11-21.zip.

Exported: /mnt/foo/iocage/images/bar1_2018-11-21.zip
root@freenas[~]# /root/iocage/iocage export bar2
Exporting dataset: foo/iocage/jails/bar2
Exporting dataset: foo/iocage/jails/bar2/root

Preparing zip file: /mnt/foo/iocage/images/bar2_2018-11-21.zip.

Exported: /mnt/foo/iocage/images/bar2_2018-11-21.zip
root@freenas[~]# /root/iocage/iocage export bar3
Exporting dataset: foo/iocage/jails/bar3
Exporting dataset: foo/iocage/jails/bar3/root

Preparing zip file: /mnt/foo/iocage/images/bar3_2018-11-21.zip.

Exported: /mnt/foo/iocage/images/bar3_2018-11-21.zip
root@freenas[~]# /root/iocage/iocage destroy -f bar1 bar2 bar3
Destroying bar1
Destroying bar2
Destroying bar3
root@freenas[~]# /root/iocage/iocage import bar1
Importing dataset: bar1
Importing dataset: bar1/root

Imported: bar1
```

**Comment by jaxjexjox** [comment]
Hey in the interest of saving time.

Is this one for you?

https://redmine.ixsystems.com/issues/71038

**Comment by skarekrow** [comment]
Nope, that is a UI display issue, it looks to have been assigned :)

**Comment by jaxjexjox** [comment]
Ok sorry to badger you Brandon, thanks.
