### ISSUE TITLE
[Low priority] Is the zip process at the end of iocage export, multithreaded?

### ISSUE THREAD

**Issue by jaxjexjox** [iocage/iocage#699]
Subject covers all elements.   It is a little slow on an 8 core machine and I'm seeing the htop processor usage, as quite low.

Understandably, I suspect if it's not multi-threaded, it may be out of the hands of the iocage team.  Is there any plans for mult-threaded code in such compression tool (assuming it's not?)

**Comment by skarekrow** [comment]
Unfortunately it's single threaded, that's up to the upstream on improving that. If anybody has any way of doing so, I'd accept a PR!

**Comment by jaxjexjox** [comment]
Who do I hassle and how do I go about it.  It's 2019 in about 32 days and I
have cores coming out of my........

**Comment by skarekrow** [comment]
https://github.com/python/cpython/blob/master/Lib/zipfile.py these guys :)
