### ISSUE TITLE
Improvements for formating in the readme

### ISSUE THREAD

**Issue by Licenser** [iocage/iocage#70]
Having the shell commands in their own lines might come in handy for lazy copy & paste people like me.

Instead of
```
- cd into the cloned directory and run `pip3
install .` as root.
```

something like:
   
    - cd into the cloned directory and run as root:
    ```
    pip3 install .
    ```

I'm happy to make a PR with changes like that if there is interest in merging it :)

**Comment by skarekrow** [comment]
Closed with https://github.com/iocage/iocage/commit/bb3565fcffc0526139f1cc1cc75cd900b3ccd869

Heh, didn't think about that!

Thanks 👍
