### ISSUE TITLE
Iocage devel version doesn't work at all

### ISSUE THREAD

**Issue by bartekrutkowski** [iocage/iocage#705]
Make sure to follow and check these boxes before submitting an issue! Thank you.

- [x] Supply `iocage --version`

The package installed is py36-iocage-devel-1.0.0.20181026,1 (however, `iocage --version` doesn't work) on FreeBSD 11.2-RELEASE

- [x] Supply the commands used, along with any steps to recreate it.

Any of `iocage --version`, `iocage list` or any other iocage command.

- [x] Provide the output from the command you issued.

```
root@somehost:~ # iocage --version
Traceback (most recent call last):
  File "/usr/local/bin/iocage", line 6, in <module>
    from iocage_cli import cli
  File "/usr/local/lib/python3.6/site-packages/iocage_cli/__init__.py", line 37, in <module>
    import iocage_lib.ioc_check as ioc_check
  File "/usr/local/lib/python3.6/site-packages/iocage_lib/ioc_check.py", line 29, in <module>
    import iocage_lib.ioc_json
  File "/usr/local/lib/python3.6/site-packages/iocage_lib/ioc_json.py", line 37, in <module>
    import iocage_lib.ioc_create
  File "/usr/local/lib/python3.6/site-packages/iocage_lib/ioc_create.py", line 43, in <module>
    import dns.resolver
ModuleNotFoundError: No module named 'dns'
```

- [x] Supply what you expected the result or output to be

For the above command iocage version number being returned, for other commands their respective actions executed.

- [x] Checked that the problem has not already been fixed on `master` if using
 a stable release.

This is the latest devel version of the package built out of the `master` branch.

**Comment by skarekrow** [comment]
These sorts of things should be emailed to the maintainer. But the issue if you install from the git repo itself is a dupe of https://github.com/iocage/iocage/issues/652
