### ISSUE TITLE
make a note about UTF8 in the README

### ISSUE THREAD

**Issue by Licenser** [iocage/iocage#71]
This is a bit related to #69 for seasoned BSDlers this might be a obvious situation but it can easiely lead to frustrations for newcommers.

Perhaps simple note to make sure the `~/.login_conf` is set as below would help? (it would have helped me ;))
```
me:\
        :charset=UTF-8:\
        :lang=en_US.UTF-8:\
        :setenv=LC_COLLATE=C:
```

**Comment by skarekrow** [comment]
Closed by https://github.com/iocage/iocage/commit/bb3565fcffc0526139f1cc1cc75cd900b3ccd869

Another thing I totally spaced on adding to the README.

Thanks!
