### ISSUE TITLE
iocage should not start services in the jail on behalf of the admin

### ISSUE THREAD

**Issue by pmhausen** [iocage/iocage#711]
Make sure to follow and check these boxes before submitting an issue! Thank you.

- [x] Supply `iocage --version`
Version	1.0 ALPHA 1 (FreeNAS 11.2-RELEASE)
- [x] Supply the commands used, along with any steps to recreate it.
Create jail with IPv6 autoconfiguration and VNET. Intentionally remove `rtsold_enable` entry from `/etc/rc.conf`in the jail. Restart jail.
```
root@freenas-pmh:~ # iocage console cloud
root@cloud:~ # service rtsold status
Cannot 'status' rtsold. Set rtsold_enable to YES in /etc/rc.conf or use 'onestatus' instead of 'status'.
root@cloud:~ # ps awux|grep rtsold
root       94984  0.0  0.0    6312   2056  -  IsJ  14:36   0:00.00 /usr/sbin/rtsold -a
root        6518  0.0  0.0    6660   2464  2  S+J  16:17   0:00.00 grep rtsold
```
- [x] Provide the output from the command you issued.
See above.
- [x] Supply what you expected the result or output to be
iocage should not start rtsold if the admin explicitly disabled in inside the jail - big POLA violation. It is of course great to provide reasonable defaults, but after jail creation iocage should not mess with things *inside* *ever*
- [ ] Checked that the problem has not already been fixed on `master` if using
 a stable release.

Kind regards
Patrick

**Comment by pmhausen** [comment]
https://redmine.ixsystems.com/issues/62547

**Comment by skarekrow** [comment]
iocage doesn't actually read the rc.conf file for this entry. Perhaps it should, but if you disable that property, iocage won't start the service for you ;)

I don't see that as a POLA violation, if it *didn't* start, I would see that as one. You are explicitly asking iocage to autoconfigure ipv6. It's doing exactly that.

As for messing with things inside, it's running rtsold on the interface. iocage has to set up the vnet interfaces inside the jail ;) But nothing user created is touched in this process. If we *did* read rc.conf, that would change user data as otherwise that property is meaningless.

**Comment by pmhausen** [comment]
Hi Brandon,
> I don't see that as a POLA violation, if it didn't start, I would see that as one. You are explicitly asking iocage to autoconfigure ipv6. It's doing exactly that.

rtsold is not mandatory for IPv6 autoconfiguration, that’s why I don’t want to run it ;-)

Shall we turn the bug report into a feature request to make rtsold a separate option?

Kind regards,
Patrick
-- 
punkt.de GmbH			Internet - Dienstleistungen - Beratung
Kaiserallee 13a			Tel.: 0721 9109-0 Fax: -100
76133 Karlsruhe			info@punkt.de	http://punkt.de
AG Mannheim 108285		Gf: Juergen Egeling

**Comment by skarekrow** [comment]
> Hi Brandon,
> I don't see that as a POLA violation, if it didn't start, I would see that as one. You are explicitly asking iocage to autoconfigure ipv6. It's doing exactly that.
> rtsold is not mandatory for IPv6 autoconfiguration, that’s why I don’t want to run it ;-) Shall we turn the bug report into a feature request to make rtsold a separate option? Kind regards, Patrick -- punkt.de GmbH	Internet - Dienstleistungen - Beratung Kaiserallee 13a	Tel.: 0721 9109-0 Fax: -100 76133 Karlsruhe	info@punkt.de	http://punkt.de AG Mannheim 108285	Gf: Juergen Egeling

That may be true ;) But as far as iocage is concerned, ipv6 autoconfiguration == slaac. If a feature request were to come in, iocage would need to be extended to support other ipv6 auto configuration methods.

Right now the cli syntax is `ip6_addr=NIC|accept_rtadv`, so it's not quite like the dhcp property.

**Comment by pmhausen** [comment]
Hi!

> That may be true ;) But as far as iocage is concerned, ipv6 autoconfiguration == slaac.
> 

Yes, and SLAAC does not mandate rtsold ;-)
If it is needed, an entry in rc.conf will start it.

> Right now the cli syntax is ip6_addr=NIC|accept_rtadv, so it's not quite like the dhcp property

And the only way to make it work at least on FreeNAS is to put

	ifconfig_epair0b_ipv6="inet6 accept_rtadv auto_linklocal“

into rc.conf.

If I am not mistaken, you currently start it from iocage by some means
independent from the jails inner rc scripts? This leads to the situation
that even with

	rtsold_enable="YES"

the pid file is not created properly, so service rtsold status, service rtsold stop|restart|…
all fail. Try it. ;-)

So … IMHO iocage should create the rtsold_enable entry on jail creation if autoconfiguration
is asked for and leave it to the discretion of the admin to remove that entry …

Kind regards
Patrick
-- 
punkt.de GmbH			Internet - Dienstleistungen - Beratung
Kaiserallee 13a			Tel.: 0721 9109-0 Fax: -100
76133 Karlsruhe			info@punkt.de	http://punkt.de
AG Mannheim 108285		Gf: Juergen Egeling

**Comment by skarekrow** [comment]
Well from my POV iocage is meant to manage these things, so if it's missing from the rc.conf, and the autoconfigure property is still set, it makes sense to reset it to enable imo.

If the user wants it disabled, they can disable that property and iocage will disable the rc.conf entry.

I'm marking this as reopened to I can track why I did it the way I did ;)

**Comment by pmhausen** [comment]
OK :)

I'd like to be able to set accept_rtadv and auto_linklocal for the interface but not start anything else ...

Kind regards
Patrick

**Comment by skarekrow** [comment]
Sounds acceptable to me! Problem is, I no longer have IPv6 capable testing around, so I'll mark this as an enhancement, as right now hardcoding rtsold is probably not the greatest thing for 100%, but I do think it covers the majority.

Hopefully a PR can come along to fit all the usecases

**Comment by skarekrow** [comment]
@pmhausen So rtsold is now an optional property, additional ipv6 autoconfiguration methods will have to be a PR from somebody else :)

Hopefully this solves your issue!
