### ISSUE TITLE
cage is missing it's configuration

### ISSUE THREAD

**Issue by dBitech** [iocage/iocage#712]
In confirming my issue was resolved on my other issue report, I had run a:

```
root@quad:/usr/jails # iocage create -r 11.2-RELEASE -n boom
Missing default rc.conf, creating it
boom successfully created!
root@quad:/usr/jails # iocage destroy boom

This will destroy jail boom

Are you sure? [y/N]: y
Destroying boom
root@quad:/usr/jails
```
but now when I try and use my cages I cannot.

```
root@quad:/usr/jails # iocage list
getlost is missing it's configuration, please destroy this jail and recreate it.
debjail is missing it's configuration, please destroy this jail and recreate it.
kafka is missing it's configuration, please destroy this jail and recreate it.
gitrdone is missing it's configuration, please destroy this jail and recreate it.
mqtt is missing it's configuration, please destroy this jail and recreate it.
grafana is missing it's configuration, please destroy this jail and recreate it.
+-----+--------------+---------+---------+-----+
| JID |     NAME     |  STATE  | RELEASE | IP4 |
+=====+==============+=========+=========+=====+
| -   | debjail      | CORRUPT | N/A     | N/A |
+-----+--------------+---------+---------+-----+
| -   | getlost      | CORRUPT | N/A     | N/A |
+-----+--------------+---------+---------+-----+
| -   | gitrdone     | CORRUPT | N/A     | N/A |
+-----+--------------+---------+---------+-----+
| -   | grafana      | CORRUPT | N/A     | N/A |
+-----+--------------+---------+---------+-----+
| -   | kafka        | CORRUPT | N/A     | N/A |
+-----+--------------+---------+---------+-----+
| -   | mqtt         | CORRUPT | N/A     | N/A |
+-----+--------------+---------+---------+-----+
```

**Comment by skarekrow** [comment]
I believe this is a regression in the default config commit. Will try to see what can be done next week.

**Comment by dBitech** [comment]
So I did a bit of investigating on this, and unfortunately I did not capture any logs etc.  But the gist of it is that somehow during the upgrades, I ended up with zfs mounts for /iocage/jails/<jailname> that contained no files.  these mounts were overlayed ontop of /iocage/jails/<jailname>/root   this accounts for the "configuration not found". rebooting the host restored ll of the mountpoints, and things are working again as I'd expect.

**Comment by skarekrow** [comment]
That would make sense with the other issue you had. Try to remove the hardcoded mounts with zfs, iocage defaults to `/POOL/iocage` now as it's mount to avoid these issues like you had.

Reopen if you stumble into this though :+1:

**Comment by H3rmit** [comment]
> 
> 
> So I did a bit of investigating on this, and unfortunately I did not capture any logs etc. But the gist of it is that somehow during the upgrades, I ended up with zfs mounts for /iocage/jails/ that contained no files. these mounts were overlayed ontop of /iocage/jails//root this accounts for the "configuration not found". rebooting the host restored ll of the mountpoints, and things are working again as I'd expect.

im having the same problem but im new to all of this. how to i reboot the host?
