### ISSUE TITLE
iocage fetch 12.0-RELEASE fails verification

### ISSUE THREAD

**Issue by wohali** [iocage/iocage#715]
- [X] Supply `iocage --version`

```
$ iocage --version
Version 0.9.10 2017/12/22
```

- [X] Supply the commands used, along with any steps to recreate it.
- [X] Provide the output from the command you issued.

```
# iocage destroy -d -r 12.0-RELEASE

This will destroy RELEASE: 12.0-RELEASE

Are you sure? [y/N]: y
Destroying RELEASE dataset: 12.0-RELEASE
Destroying RELEASE download dataset: 12.0-RELEASE
# iocage fetch --release=12.0-RELEASE
Fetching: 12.0-RELEASE

Downloading : MANIFEST [####################] 100% 0Mbit/s
Downloading : base.txz [####################] 100%  11.7Mbit/ss
Downloading : lib32.txz [####################] 100%  12.71Mbit/s
Downloading : doc.txz [####################] 100%
Downloading : src.txz [####################] 100%  11.87Mbit/s
 11.86Mbit/sExtracting: base.txz...
Extracting: lib32.txz...
doc.txz missing, will try to redownload!
Downloading : doc.txz [####################] 100%
 0Mbit/sExtracting: base.txz...
Extracting: lib32.txz...
Too many failed verifications!
```

- [X] Supply what you expected the result or output to be

Should have been able to download it just fine...unless I jumped the gun? https://www.freebsd.org/releases/12.0R/schedule.html suggests that the RELEASE builds were done on the 7th, and `iocage fetch` shows `12.0-RELEASE` for download, so...

- [X] Checked that the problem has not already been fixed on `master` if using
 a stable release.

**Comment by skarekrow** [comment]
I don't currently have a 12.0-RELEASE box, but can you install the iocage-devel port and try? This was reported a few times in the past and I couldn't reproduce.

Make sure you `iocage destroy -rd 12.0-RELEASE` first.

**Comment by wohali** [comment]
```
# uname -a
FreeBSD freebsd11 12.0-RELEASE FreeBSD 12.0-RELEASE r341666 GENERIC  amd64
# iocage --version
Version 1.0 RC 2018/11
# iocage destroy -rd 12.0-RELEASE
Default configuration missing, creating one

This will destroy RELEASE: 12.0-RELEASE

Are you sure? [y/N]: y
Partial UUID/NAME supplied, cannot check for dependant jails.

Proceed? [y/N]: y
Destroying RELEASE dataset: 12.0-RELEASE
Destroying RELEASE download dataset: 12.0-RELEASE
# iocage fetch --release=12.0-RELEASE
Fetching: 12.0-RELEASE

Downloading : MANIFEST [####################] 100%
Downloading : base.txz [####################] 100%
Downloading : lib32.txz [####################] 100%
Downloading : doc.txz [####################] 100%
Downloading : src.txz [####################] 100%
Extracting: base.txz...
Extracting: lib32.txz...
doc.txz missing, will try to redownload!
Downloading : doc.txz [####################] 100%
Extracting: base.txz...
Extracting: lib32.txz...
Too many failed verifications!
# ls -la /iocage/download/12.0-RELEASE/
total 734042
drwxr-xr-x  2 root  wheel          7 Dec 11 13:26 .
drwxr-xr-x  3 root  wheel          3 Dec 11 13:26 ..
-rw-r--r--  1 root  wheel       1045 Dec 11 13:26 MANIFEST
-rw-r--r--  1 root  wheel  154325028 Dec 11 13:26 base.txz
-rw-r--r--  1 root  wheel        180 Dec 11 13:28 doc.txz
-rw-r--r--  1 root  wheel   61684984 Dec 11 13:26 lib32.txz
-rw-r--r--  1 root  wheel  159564768 Dec 11 13:27 src.txz
# tar tfz /iocage/download/12.0-RELEASE/doc.txz
./
# grep doc /iocage/download/12.0-RELEASE/MANIFEST
#
```

Hmmmmm.

**Comment by skarekrow** [comment]
I wonder if it's that same damn heisenbug. Some users reported this around 11.2-RELEASE as well. Haven't been able to reproduce it reliably on any of my machines.

**Comment by wohali** [comment]
If there's anything more I can do, let me know - this is blocking Apache CouchDB's CI machinery right now, so I have nothing but time for this issue. (And lunch, which I'm heading off to now.)

**Comment by wohali** [comment]
oh, before I go: if there is any sort of debug/verbose mode I can enable that will help debug the issue with more logging, let me know. Didn't see anything obvious.

**Comment by skarekrow** [comment]
Not yet, it's YAN that I hope to get added some day. But ENOTIME. Let's pop this convo over to #381, I think it's the empty MANIFEST again. Can you paste the contents of that in that issue please?

**Comment by skarekrow** [comment]
I meant #472 :D

**Comment by wohali** [comment]
It's not empty, but ok

**Comment by yzgyyang** [comment]
I am having the same problem on 12.0-RELEASE while fetching 12.0-RELEASE. I fixed it by

```
iocage fetch -F base.txz -F lib32.txz -F src.txz -r 12.0-RELEASE
```

although it seems to fail at `Extracting: lib32.txz...` for me as well.

**Comment by dlangille** [comment]
Same issue here. Reproducible. https://twitter.com/DLangille/status/1072879121879977984

**Comment by Eresia999** [comment]
Same problem whit iocage 0.9.10 and FreeBSD 12 fresh install

**Comment by skarekrow** [comment]
Anyone finding this issue in the meantime, please follow my advice here: https://github.com/iocage/iocage/issues/472#issuecomment-446707693

iocage-devel will have these changes ASAP, and a new tagged release for iocage stable is incoming shortly!
