### ISSUE TITLE
VNET jails network interfaces naming convention causes `netif` issues

### ISSUE THREAD

**Issue by bartekrutkowski** [iocage/iocage#717]
Make sure to follow and check these boxes before submitting an issue! Thank you.

- [x] Supply `iocage --version`

`Version	0.9.10 2017/12/22` on `FreeBSD 12.0-RELEASE r341666`

- [x] Supply the commands used, along with any steps to recreate it.

After creating few jails using VNET for networking, I have issued `service netif start` to bring up required network bridges, interfaces and so on. This service is also being started by the system on boot, so starting it manually isn't the issue here. Doing so causes a long stream of errors due to the naming convention iocage uses, especially due to the `:` sign in the `vnet0:x` naming format.

- [x] Provide the output from the command you issued.

```
root@somehost:~ # service netif start
eval: ${ifconfig_vnet0:3...}: Bad substitution
eval: ${ifconfig_vnet0:4...}: Bad substitution
eval: ${ifconfig_vnet0:5...}: Bad substitution
eval: ${ifconfig_vnet0:6...}: Bad substitution
eval: ${ifconfig_vnet0:7...}: Bad substitution
eval: ${ifconfig_vnet0:8...}: Bad substitution
eval: ${ifconfig_vnet0:9...}: Bad substitution
(and more)
```

- [x] Supply what you expected the result or output to be

Service netif started properly and all required and configured interfaces being up. Iocage should adhere to naming conventions expected by the system services.

- [x] Checked that the problem has not already been fixed on `master` if using
 a stable release.

No. The iocage-devel package is broken and doesn't work, again. But unless the naming convention changed in devel version, the bug will be there too.

**Comment by skarekrow** [comment]
This seems like a netif bug if it's having trouble with the naming scheme. ifconfig accepts it as a valid name, and it serves a purpose for iocage. iocage doesn't put the vnet interfaces in rc.conf, so this "bug" doesn't occur during startup.

> No. The iocage-devel package is broken and doesn't work, again. But unless the naming convention changed in devel version, the bug will be there too.

Did you file a bug on FreeBSD so the port can be updated? Broken doesn't mean much without the *why* ;)

What naming scheme would you suggest?

**Comment by skarekrow** [comment]
Perhaps iocage can simply do interface_JID instead of :, marking as bug.

**Comment by bartekrutkowski** [comment]
@skarekrow I personally don't have a preference, I'm simply suggesting that iocage could try and use something that doesn't trigger bugs in the OS services; cleary using `:` does. We don't know if it's a bug or a design, but we could easily fix it migrating from `vnetX:Y` scheme into something like `vnetX.Y` (vnet0.1, vnet0.2, vnet0.3, vnet1.1, vnet1.2, vnet1.3 and so on) or `vnetXY` (vnet01, vnet02, vnet03, vnet11, vnet12, vnet13 and so on). There's plenty of options :)
