### ISSUE TITLE
Feature request: JSON output of ioc_list for iocage_lib

### ISSUE THREAD

**Issue by himrock922** [iocage/iocage#719]
Hi. I  developing of jail hosting system via Django.
Could you add the function of rendering by the json file that output of result of  a `list_all_quick` function of `iocage_lib/ioc_list.py`?

```
from django.shortcuts import render
from django.http import HttpResponse
from iocage_lib import iocage

def index(request):
    jail = iocage.ioc_list.IOCList()
    print(jail.list_datasets())
    return HttpResponse(jail.list_datasets())
```

The above is  sample code by Django.
Make sure to follow and check these boxes before submitting an issue! Thank you.

- [ ] Supply `iocage --version`
- [ ] Supply the commands used, along with any steps to recreate it.
- [ ] Provide the output from the command you issued.
- [ ] Supply what you expected the result or output to be
- [ ] Checked that the problem has not already been fixed on `master` if using
 a stable release.

**Comment by skarekrow** [comment]
iocage currently doesn't return a lot of json. ` iocage_lib.ioc_json.IOCJson(path).json_get_value('all')` Will get you a verbose list for each jail in json. 

As a workaround you can supply `hdr=False` to ioc_list, and that will give you a list of lists:
```
[['foo', 'DHCP'], ['bar', 'none'], ['baz', 'none']]
```

**Comment by himrock922** [comment]
Hi @skarekrow.
Thanks for reply.

```
As a workaround you can supply hdr=False to ioc_list, and that will give you a list of lists:

[['foo', 'DHCP'], ['bar', 'none'], ['baz', 'none']]
```

All right! I'll try development continue with data array.

Also, Thanks you for issue that attach "enhancement" label.
If possible, I would like to that develops it.

**Comment by gronke** [comment]
Hi @himrock922, you might want to try [libiocage](https://github.com/iocage/libiocage/):

```python3
>>> import iocage
>>> jail = iocage.Jail("test")
>>> jail.config  
{
    "basejail": "yes",
    "id": "test",
    "release": "12.0-RELEASE"
}
>>> jail.config.all_properties
['allow_chflags', 'allow_mount', 'allow_mount_devfs', 'allow_mount_fdescfs', 'allow_mount_nullfs', 'allow_mount_procfs', 'allow_mount_tmpfs', 'allow_mount_zfs', 'allow_quotas', 'allow_raw_sockets', 'allow_set_hostname', 'allow_socket_af', 'allow_sysvipc', 'basejail', 'basejail_type', 'boot', 'children_max', 'clonejail', 'coredumpsize', 'cputime', 'datasize', 'defaultrouter', 'defaultrouter6', 'depends', 'devfs_ruleset', 'enforce_statfs', 'exec_clean', 'exec_created', 'exec_fib', 'exec_jail_user', 'exec_poststart', 'exec_poststop', 'exec_prestart', 'exec_prestop', 'exec_start', 'exec_stop', 'exec_timeout', 'host_domainname', 'host_hostname', 'host_hostuuid', 'id', 'interfaces', 'ip4', 'ip4_addr', 'ip4_saddrsel', 'ip6', 'ip6_addr', 'ip6_saddrsel', 'jail_zfs', 'jail_zfs_dataset', 'legacy', 'mac_prefix', 'maxproc', 'memorylocked', 'memoryuse', 'mount_devfs', 'mount_fdescfs', 'mount_procfs', 'msgqqueued', 'msgqsize', 'nmsgq', 'nsem', 'nsemop', 'nshm', 'nthr', 'openfiles', 'pcpu', 'priority', 'provisioning.method', 'provisioning.rev', 'provisioning.source', 'pseudoterminals', 'readbps', 'readiops', 'release', 'resolver', 'rlimits', 'securelevel', 'shmsize', 'stacksize', 'stop_timeout', 'swapuse', 'sysvmsg', 'sysvsem', 'sysvshm', 'tags', 'template', 'vmemoryuse', 'vnet', 'vnet_interfaces', 'wallclock', 'writebps', 'writeiops']
>>> jail.config["vnet"] = True
>>> jail.config
{
    "basejail": "yes",
    "id": "test",
    "release": "12.0-RELEASE",
    "vnet": "yes"
}
>>> jail.save()
```
 
There is also a handbook for library usage: https://iocage.io/handbook/

**Comment by himrock922** [comment]
Hi @gronke.
Thanks for reply.

> you might want to try libiocage:

I did try `libiocage`.

```python
from django.shortcuts import render
from django.template import loader
from django.http import HttpResponse

import iocage
def index(request):
    jails = iocage.Jails('myjail')
    print(jails.config)
```

* result
```json
{
    "CONFIG_VERSION": "15",
    "allow_chflags": "0",
    "allow_mlock": "0",
    "allow_mount": "0",
    "allow_mount_devfs": "0",
    "allow_mount_fusefs": "0",
    "allow_mount_nullfs": "0",
    "allow_mount_procfs": "0",
    "allow_mount_tmpfs": "0",
    "allow_mount_zfs": "0",
    "allow_quotas": "0",
    "allow_raw_sockets": "0",
    "allow_set_hostname": "1",
    "allow_socket_af": "0",
    "allow_sysvipc": "0",
    "allow_tun": "0",
    "available": "readonly",
    "basejail": "no",
    "boot": "no",
    "bpf": "no",
    "children_max": "0",
    "cloned_release": "11.2-RELEASE-p4",
    "comment": "none",
    "compression": "lz4",
    "compressratio": "readonly",
    "coredumpsize": "off:deny",
    "count": "1",
    "cpuset": "no",
    "cputime": "off:deny",
    "datasize": "off:deny",
    "dedup": "no",
    "defaultrouter": "none",
    "defaultrouter6": "none",
    "depends": "none",
    "devfs_ruleset": "4",
    "dhcp": "no",
...etc
```

Very Good! This result was that as my request.
But... I have one worry.

https://github.com/iocage/libiocage/

> Latest News (September 22nd, 2018)
> Progress towards the transition of python-iocage using libiocage has been made. Recent changes to both projects ensure compatibility running on the same host, so that it is now possible to partially utilize libiocage in iocage until a full migration is performed. Because some changes to the command line arguments and the script output will occur, @skarekrow will continue to maintain the current implementation until users had time to follow the deprecation warnings and suggestions.

Since above notice I did read, I decided `https://github.com/iocage/iocage` repository used.
If my case, should I use libiocage?

Best Regards.

**Comment by igalic** [comment]
@himrock922 as you can see from some of the (merged) pull requests, we're working towards getting libiocage into iocage.

That the output of command-line utilities might change, shouldn't affect you, since you would be directly consuming the library.

**Comment by himrock922** [comment]
Hi, @igalic.
Thanks for reply.

> That the output of command-line utilities might change, shouldn't affect you, since you would be directly consuming the library.

All right!
Anyway... I am to use `https://github.com/iocage/iocage` repository only.
I will try it.

Thanks!

**Comment by himrock922** [comment]
Hi All.

After going through my thought, I decided both use.

```
from iocage_lib import iocage as iocage_lib
import iocage
def index(request):
    jails = iocage_lib.ioc_list.IOCList(hdr=False)
    return render(request, 'jails/index.html', {'jails': jails.list_datasets()})

def detail(request, jail_name):
    jail = iocage.Jail(jail_name)
    return  render(request, 'jails/detail.html', {'jail': jail.config})
```

* index page
![fireshot capture 17 - jail list - http___133 242 137 151_8080_jails_](https://user-images.githubusercontent.com/4998536/50095069-f5c13100-0257-11e9-967c-6cb7b8e572b8.png)

* detail page
![fireshot capture 16 - jail info - http___133 242 137 151_8080_jails_myjail_](https://user-images.githubusercontent.com/4998536/50095052-eb9f3280-0257-11e9-8fe7-be6e0e51ac87.png)

If I have trouble,  I consult.
Next, I will develop jail console via VNC on WebSocket.
Thanks!

**Comment by gronke** [comment]
@himrock922 FYI you can easily get a list of Jails from libiocage:

```python-console
>>> import iocage
>>> [dict(JID=x.jid,NAME=x.name,STATE=("up" if x.running else "down"),IP4=str(x.config["ip4_addr"])) for x in iocage.Jails()]
[{'JID': None, 'NAME': 'test', 'STATE': 'down', 'IP4': 'vnet0|192.168.2.2/24'}, {'JID': None, 'NAME': 'test2', 'STATE': 'down', 'IP4': ''}]
```

Or in a better readable form

```python3
import iocage
jails = iocage.Jails()
results = []
for jail in jails:
    results.append(
        dict(
            JID=jail.jid,
            NAME=jail.name,
            STATE=("up" if jail.running else "down"),
            IP4=[str(x) for x in jail.config["ip4_addr"].networks]
        )
    )

import json
output = json.dumps(results, indent=2)

print(output)
```

```console
$ python3.6 iocage-jail-list-json.py
[
  {
    "JID": null,
    "NAME": "test",
    "STATE": "down",
    "IP4": [
      "192.168.2.2/24"
    ]
  },
  {
    "JID": null,
    "NAME": "test2",
    "STATE": "down",
    "IP4": []
  }
]
```

**Comment by himrock922** [comment]
@gronke 
Thanks for reply!
When refactoring, I do improvement it.
