### ISSUE TITLE
License violation in regards to code I have contributed

### ISSUE THREAD

**Issue by grobe0ba** [iocage/iocage#75]
I have noted that you are continuing to use code that I have contributed, whilst intentionally purging the history of the merged pull requests, removing my username from the CREDITS file, and squashing the commits under the identity of another username.
This code is under my copyright, and contributed as such, under it's own licensing terms, not property of yourself, your other contributors, or this project.

Some of the code that I am referring to has been re-committed as commit 7d9ee0e6f692a54ca42af369e34de861676927a4, and originally presented in a pull request to the now non-existent iocage/iocage-org repository. Along with this segment of code, you are also using code I presented in pull request #64. That code has also been squashed into the aforementioned commit.

While I regret my loss of manners when separating myself from your project, I do wish the best for your project, as it is an immensely useful tool.

I would ask that you restore the original history of the pull request merges, as well as re-add me to the CREDITS file, to maintain your license to use this code, else I will have no choice but to file a DMCA takedown request.

**Comment by pannon** [comment]
@grobe0ba this project is under the BSD license and specifically under Copyright (C) 2014 Peter Toth (pannon) - for details see below attached copy. Committers contributing to this project are covered by this license. You can not re-license your contributed one liners under your own terms.

As for the CREDITS file - we give credits to contributors who truly add value to our project and share our values. AND we reserve the right to decide who we give credit and why.

We had to "trash" most of your commits except two minor ones (even these needed attention) as the quality was appalling. This has been pointed out to you a number of times. The big PR changes you've tried to force upon us were cosmetic white spaces and silly quotation changes - with no added IP whatsoever.

Finally you are a known troll to both the OpenBSD and FreeBSD community and you've been banned from numerous mailing lists, IRC channels and so forth in the past. (one interesting reference resembling this case https://www.mail-archive.com/tech@openbsd.org/msg20661.html) 

For these reasons we came to the conclusion to protect our project and name from your destructive actions and appalling behavior. Furthermore delete the development branch and start over clean.

For reference your latest [abusive comment and poor behavior] (https://github.com/iocage/iocage/pull/73)

We wish you all the best in your future "positive" endeavors.

The license:

```

# Copyright (C) 2014 Peter Toth (pannon)
# All rights reserved
#
# Redistribution and use in source and binary forms, with or without
# modification, are permitted providing that the following conditions
# are met:
# 1. Redistributions of source code must retain the above copyright
#    notice, this list of conditions and the following disclaimer.
# 2. Redistributions in binary form must reproduce the above copyright
#    notice, this list of conditions and the following disclaimer in the
#    documentation and/or other materials provided with the distribution.
#
# THIS SOFTWARE IS PROVIDED BY THE AUTHOR ``AS IS'' AND ANY EXPRESS OR
# IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED
# WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE
# ARE DISCLAIMED.  IN NO EVENT SHALL THE AUTHOR BE LIABLE FOR ANY
# DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL
# DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS
# OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION)
# HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT,
# STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING
# IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE
# POSSIBILITY OF SUCH DAMAGE.

```
