### ISSUE TITLE
DHCP failure leaks unused vnet interface

### ISSUE THREAD

**Issue by ohmantics** [iocage/iocage#757]
If a DHCP-based jail fails to acquire an address, it leaves behind the vnet0:n interface that was created when it is auto-stopped.

Make sure to follow and check these boxes before submitting an issue! Thank you.

- [X] Supply `iocage --version`

```Version	1.0 ALPHA 1```

- [X] Supply the commands used, along with any steps to recreate it.

```iocage start foo```

- [X] Provide the output from the command you issued.
```
* Starting foo
  + Started OK
  + Configuring VNET OK
  + Acquiring DHCP address: FAILED, address received: 0.0.0.0/8

Stopped foo due to DHCP failure
```
- [X] Supply what you expected the result or output to be

Expected that the created vnet0:2 interface is destroyed during failure handling.

- [ ] Checked that the problem has not already been fixed on `master` if using
 a stable release.

(Sorry, don't want to goof up my FreeNAS with custom stuff just yet.)

**Comment by skarekrow** [comment]
This *should* clean up nicely in 1.0. I'll throw an investigating label on this until we know for sure.

**Comment by skarekrow** [comment]
Confirmed this is now cleaning up properly in 1.0.

Thanks!
