### ISSUE TITLE
iocage vs iocage-develp | start

### ISSUE THREAD

**Issue by zenny** [iocage/iocage#76]
iocage-develop reports VNETroute as bad keyword:

# ./iocage start 3d
* Starting 3d4c116a-d1b4-11e4-8c1e-55ff3853a5bc (webserver-template)
  + Started                  OK
  + Configuring VNETroute: bad keyword: 
route: usage: route [-46dnqtv] command [[modifiers] args]
         OK
  + Starting services        OK

Whereas the default iocage does not report any warnings:

# iocage start 3d
* Starting 3d4c116a-d1b4-11e4-8c1e-55ff3853a5bc (webserver-template)
  + Started                  OK
  + Configuring VNET         OK
  + Starting services        OK

**Comment by pannon** [comment]
Thanks Zenny! This is a fallout from a recent ip6 commit. Will be fixing this.

**Comment by pannon** [comment]
@zenny I can't reproduce this on 10.1-RELEASE-p9 with VNET. Please can you confirm what is your release? Also paste a dump of `iocage get all UUID` if you can.

**Comment by zenny** [comment]
# ./iocage get all 3d
interfaces:vnet0:bridge0,vnet1:bridge1
vnet:on
host_hostname:3d4c116a-d1b4-11e4-8c1e-55ff3853a5bc
hostname:3d4c116a-d1b4-11e4-8c1e-55ff3853a5bc
ip4_addr:none
ip4_saddrsel:1
ip4:new
ip6_addr:none
ip6_saddrsel:1
ip6:new
defaultrouter:none
defaultrouter6:-
exec_fib:0
devfs_ruleset:4
mount_devfs:1
exec_start:/bin/sh /etc/rc
exec_stop:/bin/sh /etc/rc.shutdown
exec_prestart:/usr/bin/true
exec_prestop:/usr/bin/true
exec_poststop:/usr/bin/true
exec_poststart:/usr/bin/true
exec_clean:1
exec_timeout:60
stop_timeout:30
exec_jail_user:root
exec_system_jail_user:0
exec_system_user:root
mount_fdescfs:1
mount_procfs:0
enforce_statfs:2
children_max:0
login_flags:-f root
securelevel:2
allow_set_hostname:1
allow_sysvipc:0
allow_raw_sockets:0
allow_chflags:0
allow_mount:0
allow_mount_devfs:0
allow_mount_nullfs:0
allow_mount_procfs:0
allow_mount_tmpfs:0
allow_mount_zfs:0
allow_quotas:0
allow_socket_af:0
host_hostuuid:3d4c116a-d1b4-11e4-8c1e-55ff3853a5bc
memoryuse:8G:log
memorylocked:off
vmemoryuse:off
maxproc:off
cputime:off
pcpu:off
datasize:off
stacksize:off
coredumpsize:off
openfiles:off
pseudoterminals:off
swapuse:off
nthr:off
msgqqueued:off
msgqsize:off
nmsgq:off
nsemop:off
nshm:off
shmsize:off
wallclock:off
tag:webserver-template
template:no
rlimits:off
boot:off
notes:none
owner:root
priority:99
last_started:2015-04-24_21:29:49
type:jail
hostid:b7b09ae3-1d3d-c643-5cae-65adaff3f68c
cpuset:off
jail_zfs:off
jail_zfs_dataset:iocage/jails/3d4c116a-d1b4-11e4-8c1e-55ff3853a5bc/root/data
release:10.1-RELEASE
hack88:-
sync_stat:-
sync_target:none
sync_tgt_zpool:none

**Comment by pannon** [comment]
I can see the issue, it is definitely IP6 related. The jail was created with an older iocage where the defaultrouter6 was not implemented - so the property now shows a "-" istead of the keyword "none".

As a workaround try this:
`iocage set defaultrouter6=none UUID`

Regardless this needs fixing and it is a bug. Will be patching this soon.

Thanks for testing!
