### ISSUE TITLE
pcpu values mismatch between implementation and docs

### ISSUE THREAD

**Issue by Licenser** [iocage/iocage#76]
according to the docs [1] pcpu follows the same rules as memory, however the implementation expects `on` or `off`.

```
ERROR: 100: deny is not a valid value for pcpu.
Value must be off or on
```

http://iocage.readthedocs.io/en/latest/advanced-use.html#limit-cpu-use-by

**Comment by skarekrow** [comment]
To be honest, the rcctl stuff hasn't been heavily looked at yet as I haven't had time to come around and add support for it. Those docs are for the old iocage.

**Comment by Licenser** [comment]
that does explain it :D

**Comment by skarekrow** [comment]
:D But it's still good to have these documented.
