### ISSUE TITLE
enhancement request: base jail option to nullmount /usr/local and /var/db/pkg read-only

### ISSUE THREAD

**Issue by agshekeloh** [iocage/iocage#764]
Brandon suggested I file an enhancement request. Here it is.

storm~;iocage -v
Version 1.0 RELEASE 2018/12
storm~;uname -a
FreeBSD storm 13.0-CURRENT FreeBSD 13.0-CURRENT r342545 GENERIC  amd64
storm~;

When using base jails, I often want to share /usr/local from the origin jail to the derived jail. It seems that could be a command-line option to toggle on and off.

**Comment by agshekeloh** [comment]
Also an option to mount /usr/src would be useful.

It's specifically useful for running mergemaster across version upgrades.

**Comment by igalic** [comment]
what's wrong with using `iocage fstab` for that?

**Comment by agshekeloh** [comment]
sure you can do this with raw fstab.

But these are really common cases for many base jail users. It becomes more important when you try to rebase a base jail, as per my other enhancement request.

**Comment by gronke** [comment]
> what's wrong with using iocage fstab for that?

Yes, mountpoints should be handled by fstab.

> When using base jails, I often want to share /usr/local from the origin jail to the derived jail. It seems that could be a command-line option to toggle on and off.

This is an edge case, that needs to be used wisely. Doing it with an fstab command is more intuitive than giving it an extra option. libiocages ioc command does it as follows

```
ioc fstab add /usr/local <JAIL> -rw
```

**Comment by skarekrow** [comment]
This will be handled if those directories exist automatically instead of a flag. It makes a lot of sense these two directories would be shared.
