### ISSUE TITLE
enhancement request: "iocage rebase" for base jails.

### ISSUE THREAD

**Issue by agshekeloh** [iocage/iocage#765]
Brandon suggested I file an enhancement request. Here it is.

storm~;iocage -v
Version 1.0 RELEASE 2018/12
storm~;uname -a
FreeBSD storm 13.0-CURRENT FreeBSD 13.0-CURRENT r342545 GENERIC  amd64
storm~;

When using base jails, I might want to move a base jail from one origin jail to another. Think, say, PHP upgrades when you're sharing /usr/local, or moving to a new FreeBSD version. I could sed the jail's fstab, but it seems that should be inside iocage.

The obvious command name is "iocage rebase", but nothing good comes from a rebase. ;-)

**Comment by netchild** [comment]
Related to #461 and #425?
