### ISSUE TITLE
"iocage rename" crash, cannot delete

### ISSUE THREAD

**Issue by agshekeloh** [iocage/iocage#768]
<pre>Get errors when renaming a jail. This jail is a clone, but it happens with "iocage create" jails as well.

storm/iocage/jails;freebsd-version
13.0-CURRENT
storm/iocage/jails;iocage -v
Version 1.0 RELEASE 2018/12

storm/iocage/jails;iocage list -h
-       dns3    down    11.2-RELEASE    203.0.113.243
-       dns4    down    11.2-RELEASE    203.0.113.244
-       e7cc061b        down    10.4-RELEASE    203.0.113.234
3       squid1  up      12.0-ALPHA2     203.0.113.240
2       wdb1    up      11.1-RELEASE    203.0.113.236
1       wdb2    up      11.2-RELEASE    203.0.113.237
-       www1    down    10.4-RELEASE    203.0.113.234
-       www2    down    10.4-RELEASE    203.0.113.235

storm/iocage/jails;iocage rename www2 www4
cannot rename 'iocage/iocage@www2': dataset does not exist
Traceback (most recent call last):
  File "/usr/local/bin/iocage", line 10, in <module>
    sys.exit(cli())
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/iocage_cli/rename.py", line 39, in cli
    ioc.IOCage(jail=jail).rename(new_name)
  File "/usr/local/lib/python3.6/site-packages/iocage_lib/iocage.py", line 1344, in rename
    "zfs", "rename", "-r", f"{self.pool}/iocage@{uuid}", f"@{new_name}"
  File "/usr/local/lib/python3.6/subprocess.py", line 291, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['zfs', 'rename', '-r', 'iocage/iocage@www2', '@www4']' returned non-zero exit status 1.

But the dataset moves:

storm/iocage/jails;zfs list -r iocage/iocage/jails
NAME                              USED  AVAIL  REFER  MOUNTPOINT
iocage/iocage/jails              1.54G   886G    96K  /iocage/jails
iocage/iocage/jails/dns3         9.62M   886G    96K  /iocage/jails/dns3
iocage/iocage/jails/dns3/root    9.53M   886G   672M  /iocage/jails/dns3/root
iocage/iocage/jails/dns4         25.2M   886G    96K  /iocage/jails/dns4
iocage/iocage/jails/dns4/root    25.1M   886G  1.00G  /iocage/jails/dns4/root
iocage/iocage/jails/squid1       19.3M   886G    92K  /iocage/jails/squid1
iocage/iocage/jails/squid1/root  19.2M   886G  1.19G  /iocage/jails/squid1/root
iocage/iocage/jails/wdb1         17.0M   886G    92K  /iocage/jails/wdb1
iocage/iocage/jails/wdb1/root    16.8M   886G   987M  /iocage/jails/wdb1/root
iocage/iocage/jails/wdb2         18.8M   886G    92K  /iocage/jails/wdb2
iocage/iocage/jails/wdb2/root    18.6M   886G   977M  /iocage/jails/wdb2/root
iocage/iocage/jails/www1         1.45G   886G    92K  /iocage/jails/www1
iocage/iocage/jails/www1/root    1.45G   886G  1.61G  /iocage/jails/www1/root
iocage/iocage/jails/www3          404K   886G    92K  /iocage/jails/www3
iocage/iocage/jails/www3/root     344K   886G  1.61G  /iocage/jails/www3/root
iocage/iocage/jails/www4          404K   886G    92K  /iocage/jails/www4
iocage/iocage/jails/www4/root     344K   886G  1.61G  /iocage/jails/www4/root

Seeing as -n sets hostname in /etc/rc.conf with commands like clone and create, I would expect rename to do the same. That doesn't happen, but I suspect we just don't get that far.

A jail I've attempted to rename cannot be destroyed.

storm/iocage/jails;iocage destroy www2

This will destroy jail www2

Are you sure? [y/N]: y
Partial UUID/NAME supplied, cannot check for dependant jails.

Proceed? [y/N]: y
jail 'www2' not found!
storm/iocage/jails;
</pre>

**Comment by agshekeloh** [comment]
edited to remove auto-markdown daftness

**Comment by skarekrow** [comment]
Fixed by https://github.com/iocage/iocage/pull/824
