### ISSUE TITLE
hang on iocage list

### ISSUE THREAD

**Issue by antxxxx** [iocage/iocage#772]
I am encountering a strange issue where iocage list hangs. This is on latest iocage version from freebsd ports

```
iocage --version
Version 1.0 RELEASE 2018/12
```

I am a long time iocage user (from back when it was all shell commands) so it may be that some of my jails have been upgraded incorrectly or have strange properties.   

The problem seems to be in iocage_lib/ioc_list.py on line 242

```
                jail_root = self.zfs.get_dataset(f"{jail.name}/root")
```

What is weird is if i put a line afterwards with ```print ("")``` in it, then everything works fine (albeit with extra lines outputted)

**Comment by antxxxx** [comment]
Oh - I forgot to mention - this is on freebsd 12.0

**Comment by skarekrow** [comment]
This may be the same issue as https://github.com/iocage/iocage/issues/766, have you tried out that PR to see?

**Comment by antxxxx** [comment]
Thanks - its the same issue. I have upgraded py-netifaces to latest port version and it all works now

**Comment by skarekrow** [comment]
Awesome, great to hear!
