### ISSUE TITLE
"iocage fstab -r" destroys base jail

### ISSUE THREAD

**Issue by agshekeloh** [iocage/iocage#779]
<pre>
storm~;iocage --version
Version 1.0 RELEASE 2018/12
storm~;uname -a
FreeBSD storm 13.0-CURRENT FreeBSD 13.0-CURRENT r342739 GENERIC  amd64

Just did "make install" from source this morning.

Here's a jail's fstab:

storm~;iocage fstab -l dns3
+-------+--------------------------------------------------------------------------------------------------+
| INDEX |                                           FSTAB ENTRY                                            |
+=======+==================================================================================================+
| 0     | /iocage/releases/11.2-RELEASE/root/bin /iocage/jails/dns3/root/bin nullfs ro 0 0                 |
+-------+--------------------------------------------------------------------------------------------------+
| 1     | /iocage/releases/11.2-RELEASE/root/boot /iocage/jails/dns3/root/boot nullfs ro 0 0               |
+-------+--------------------------------------------------------------------------------------------------+
| 2     | /iocage/releases/11.2-RELEASE/root/lib /iocage/jails/dns3/root/lib nullfs ro 0 0                 |
+-------+--------------------------------------------------------------------------------------------------+
| 3     | /iocage/releases/11.2-RELEASE/root/libexec /iocage/jails/dns3/root/libexec nullfs ro 0 0         |
+-------+--------------------------------------------------------------------------------------------------+
| 4     | /iocage/releases/11.2-RELEASE/root/rescue /iocage/jails/dns3/root/rescue nullfs ro 0 0           |
+-------+--------------------------------------------------------------------------------------------------+
| 5     | /iocage/releases/11.2-RELEASE/root/sbin /iocage/jails/dns3/root/sbin nullfs ro 0 0               |
+-------+--------------------------------------------------------------------------------------------------+
| 6     | /iocage/releases/11.2-RELEASE/root/usr/bin /iocage/jails/dns3/root/usr/bin nullfs ro 0 0         |
+-------+--------------------------------------------------------------------------------------------------+
| 7     | /iocage/releases/11.2-RELEASE/root/usr/include /iocage/jails/dns3/root/usr/include nullfs ro 0 0 |
+-------+--------------------------------------------------------------------------------------------------+
| 8     | /iocage/releases/11.2-RELEASE/root/usr/lib /iocage/jails/dns3/root/usr/lib nullfs ro 0 0         |
+-------+--------------------------------------------------------------------------------------------------+
| 9     | /iocage/releases/11.2-RELEASE/root/usr/libexec /iocage/jails/dns3/root/usr/libexec nullfs ro 0 0 |
+-------+--------------------------------------------------------------------------------------------------+
| 10    | /iocage/releases/11.2-RELEASE/root/usr/sbin /iocage/jails/dns3/root/usr/sbin nullfs ro 0 0       |
+-------+--------------------------------------------------------------------------------------------------+
| 11    | /iocage/releases/11.2-RELEASE/root/usr/share /iocage/jails/dns3/root/usr/share nullfs ro 0 0     |
+-------+--------------------------------------------------------------------------------------------------+
| 12    | /iocage/releases/11.2-RELEASE/root/usr/libdata /iocage/jails/dns3/root/usr/libdata nullfs ro 0 0 |
+-------+--------------------------------------------------------------------------------------------------+
| 13    | /iocage/releases/11.2-RELEASE/root/usr/lib32 /iocage/jails/dns3/root/usr/lib32 nullfs ro 0 0     |
+-------+--------------------------------------------------------------------------------------------------+
| 14    | /iocage/releases/11.2-RELEASE/root/usr/src/ /iocage/jails/dns3/root/usr/src/ nullfs ro 0 0       |
+-------+--------------------------------------------------------------------------------------------------+

All good, right? Let's remove entry 14, and only entry 14.

storm~;iocage fstab -r dns3 14
Successfully removed mount from dns3's fstab

I would expect to have the usual base jail nullfs mounts after moving the /usr/src fstab entry, but:

storm~;iocage fstab -l dns3
+-------+----------------------------------------------------------------------------------+
| INDEX |                                   FSTAB ENTRY                                    |
+=======+==================================================================================+
| 0     | /iocage/releases/11.2-RELEASE/root/bin /iocage/jails/dns3/root/bin nullfs ro 0 0 |
+-------+----------------------------------------------------------------------------------+

This don't look right. Or am I misunderstanding?

Thanks!

**Comment by skarekrow** [comment]
Your markdown leaves me confused lol. This seems like a big bug where it's removing the last entry and not putting the rest back.

**Comment by agshekeloh** [comment]
No markdown, I'm all plain text now. :-)

And yes, it looked like a big bug to me... big enough I was hoping for pebcak. Enjoy!
