### ISSUE TITLE
Enhancement Request: option to "regenerate mac" on clone

### ISSUE THREAD

**Issue by qubitrenegade** [iocage/iocage#783]
- [x] Supply `iocage --version`

```
root@freenas # iocage --version                                     
Version 1.0 ALPHA 1
```

- [x] Supply the commands used, along with any steps to recreate it.

```# assumes jail created named "test"
iocage create --name test --release 11.2-RELEASE vnet=on dhcp=on bpf=yes 
iocage start test
iocage stop test
iocage clone test --name clone
iocage get vnet0_mac clone
iocage set vnet0_mac="02ff60ae1b76 02ff60ae1b77" clone
iocage start clone
```

- [x] Provide the output from the command you issued.

```
root@freenas[~]# iocage create --name test --release 11.2-RELEASE vnet=on dhcp=on bpf=yes 
test successfully created!
root@freenas[~]# iocage get vnet0_mac test                                               
none
root@freenas[~]# iocage start test
* Starting test
  + Started OK
  + Configuring VNET OK
  + DHCP Address: 192.168.0.40/24
  + Starting services OK
root@freenas[~]# iocage get vnet0_mac test
02ff60ae1b75 02ff60ae1b76
root@freenas[~]# iocage stop test
* Stopping test
  + Running prestop OK
  + Stopping services OK
  + Tearing down VNET OK
  + Removing devfs_ruleset: 13 OK
  + Removing jail process OK
  + Running poststop OK
root@freenas[~]# iocage clone test --name clone
clone successfully cloned!
root@freenas[~]# iocage get vnet0_mac clone
02ff60ae1b75 02ff60ae1b76
root@freenas[~]# iocage start clone
* Starting clone
  + Started OK
  + Configuring VNET OK
  + DHCP Address: 192.168.0.40/24
  + Starting services OK
root@freenas[~]# iocage stop clone
* Stopping clone
  + Running prestop OK
  + Stopping services OK
  + Tearing down VNET OK
  + Removing devfs_ruleset: 13 OK
  + Removing jail process OK
  + Running poststop OK
root@freenas[~]# iocage set vnet0_mac="02ff60ae1b76 02ff60ae1b77"
You must specify a jail!
root@freenas[~]# iocage set vnet0_mac="02ff60ae1b76 02ff60ae1b77" clone
Property: vnet0_mac has been updated to 02ff60ae1b76 02ff60ae1b77
root@freenas[~]# iocage start clone
* Starting clone
  + Started OK
  + Configuring VNET OK
  + DHCP Address: 192.168.0.41/24
  + Starting services OK
```

- [x] Supply what you expected the result or output to be

It would be nice if the was an easy way to regenerate the MAC/HW address of a jail when cloning it, e.g.: `iocage clone test --name clone --regenerate-mac` so that when booting the new jail it is able to be identified on the network as a separate device, and in the case of DHCP pull a new IP address.

It appears that the MAC is generated on the initial boot of the jail.  Perhaps there's a way to set it to "none"?

- [x] Checked that the problem has not already been fixed on `master` if using
 a stable release.

The documentation doesn't seem to talk about "Regenerating" the mac, only about explicitly setting it.  While this works, I'd really like to have the MAC address generated for me as it appears to have something to do with the hostname? (I deleted and recreated the `test` jail and it always gets the same MAC) 

The other issue 557 about cloning doesn't apply here and 757 about DHCP is similar but unrelated.

Thanks!

**Comment by qubitrenegade** [comment]
Ok, so this totally works to regenerate the MAC

```
iocage set vnet0_mac="none" clone
```

Full Output:

```root@freenas[~]# iocage set vnet0_mac="none" clone                                       
Property: vnet0_mac has been updated to none
root@freenas[~]# iocage get vnet0_mac clone
none
root@freenas[~]# iocage start clone
* Starting clone
  + Started OK
  + Configuring VNET OK
  + DHCP Address: 192.168.0.42/24
  + Starting services OK
root@freenas[~]# iocage get vnet0_mac clone       
02ff60218fbc 02ff60218fbd
```

**Comment by skarekrow** [comment]
Currently this is by design as I didn't want a clone to not be a clone in too many regards. Unless others agree they would expect the mac address to change?

I figured it was better to not surprise as a clone should be seen as a complete copy. I can add a flag for this however.

**Comment by qubitrenegade** [comment]
I think we're in agreement.  I think there are plenty of use cases where you'd want to have an identical copy, but thinking from an automation perspective, it would be really nice to be able to `iocage clone --new-mac` (I'm terrible at naming things...) and have a "ready to use" clone.

Thanks!
-Q
