### ISSUE TITLE
Can not destroy old unused release.

### ISSUE THREAD

**Issue by jdakhayman** [iocage/iocage#787]
Make sure to follow and check these boxes before submitting an issue! Thank you.

- [x ] Supply `iocage --version`
``
Version 1.0 RELEASE 2018/12

- [x ] Supply the commands used, along with any steps to recreate it.
 iocage destroy -d -r 11.1-RELEASE

- [x ] Provide the output from the command you issued.

This will destroy RELEASE: 11.1-RELEASE

Are you sure? [y/N]: y

11.1-RELEASE has dependent jails (who may also have dependents), use --recursive to destroy:
  webhost

- [x ] Supply what you expected the result or output to be.

To remove the old release without 

My jail has been upgraded to the latest 11.2-RELEASE p-6 patch level. I do not want to destroy my jail, just the old release that isn't supported any more and to free up space.

- [X ] Checked that the problem has not already been fixed on `master` if using
 a stable release.

Still does it using master as well.

**Comment by skarekrow** [comment]
That's unfortunately not possible as that jail is a child of that old release forever. If you don't want that to be the case, create a basejail or thickjail.
