### ISSUE TITLE
Optimize command output for easy human parsing

### ISSUE THREAD

**Issue by kairu0** [iocage/iocage#79]
I am using iocage 2.1.0.

This is a feature request for your consideration. Many commands that I frequently type return a message that requires parsing a wordy English sentence when a shorter message would probably suffice.

e.g.
> # iocage set host_hostname=XYZ XYZ
> Property: tag has been updated to XYZ

A return like "OK: tag updated to XYZ" would show the result more readily "OK" which would help non-English speakers and also speed up administration for everyone.

Another example: 
> # iocage create -r 10.3-RELEASE
> 1a440e3d-d89a-49ea-ba1f-3753e16c3322 (2017-03-21@23:45:19:814736) successfully created!

My eyes must wander about 50 characters through machine code to the right until I see "successfully".

Something like:
> OK: Created jail 1a440e3d-d89a-49ea-ba1f-3753e16c3322 (tag = 2017-03-21@23:45:19:814736)

Might be easier for everyone to parse.

Just a suggestion for your consideration.

**Comment by skarekrow** [comment]
You have `iocell`'s version and mine confused ;)

My thinking is that unless you see `ERROR:`, `WARNING:` that everything is indeed OK.

That being said, I'm open to improvements. A PR is welcome, but I just simply don't have the time right now to go through all the messages and update it to something shorter.

I'll leave this open as a Help Wanted for a little while, and hopefully someone comes along and helps :)

**Comment by kairu0** [comment]
Oops! In my defense, I am actually presently cutting over some jails from iocell to iocage, which is why I had the iocell package version on my box to be parsed hehehe

> My thinking is that unless you see ERROR:, WARNING: that everything is indeed OK.

Good to know.

**Comment by skarekrow** [comment]
Haha it's ok, I figured. Had to give you a *bit* of a hard time though!

**Comment by skarekrow** [comment]
I think with the colors that have been pushed, this issue is largely solved. You don't even need to read the text at that point :D
