### ISSUE TITLE
Creating a basejail creates snapshots on RELEASE's it doesn't use.

### ISSUE THREAD

**Issue by skarekrow** [iocage/iocage#79]
Creating a basejail results in a snapshot being recursively created for all RELEASE's and child datasets below them.

**Comment by pannon** [comment]
Yes this is expected, a feature of basejails.

**Comment by pannon** [comment]
Correction: yes this is a bug. It is fixed now. Will be pushing soon.

**Comment by skarekrow** [comment]
This is not fixed actually. Still occurs.

**Comment by pannon** [comment]
It is using it - just look at the destroy function for basejails. This is to avoid RELEASE switching issues.

**Comment by skarekrow** [comment]
That is unnecessarily cluttering the snapshot list in zfs. If we have many RELEASEs fetched, and many jails, the list gets very, very large. What RELEASE switching are we doing? We cannot downgrade to an earlier RELEASE easily and we are upgrading otherwise. So it doesn't make sense for it to have snapshots on the older RELEASES it will never use.

**Comment by pannon** [comment]
That snapshot is recreated every time a basejail is started. There is no downside to this. This way we can re-clone no matter what the RELEASE is and blow away the snapshots recursively without issues. Also doing expensive lookups are avoided this way as we always know where to delete the "top" snapshot.

It makes a lot of sense doing it this way. ZFS snapshots do not consume extra space on base RELEASE datasets as those are pretty much static.

Also, this snapshot is only created on base/RELEASE (which is static) and not on normal RELEASEs.

**Comment by skarekrow** [comment]
The downside is all the snapshots cluttering up the list. I know it's on
base  but that's irrelevant where it is. I agreeing the benefits but
cosmetically it is very annoying.
