### ISSUE TITLE
Creation of .defaults file with custom $iocroot broken in develop. 

### ISSUE THREAD

**Issue by pr1ntf** [iocage/iocage#80]
I have iocroot=/buttpool/iocage set
See here: https://github.com/iocage/iocage/blob/develop/lib/ioc-info#L385

Below is the error when running iocage fetch. Fetch will run fine. 
Creating a new jail seems to be broken as well. 

    root@butts:~/iocage # ./iocage fetch
      INFO: Creating buttpool/buttpool/iocage/.defaults.
    cannot create 'buttpool/buttpool/iocage/.defaults': parent does not exist

**Comment by pr1ntf** [comment]
iocage create is definatly broken in this case. Hangs for two minutes then all sorts of zfs set prop errors.

**Comment by pr1ntf** [comment]
After trying to create a jail, I get this when running iocage list

    root@butts:~/iocage # ./iocage list
      INFO: Creating buttpool/buttpool/iocage/.defaults.
    cannot create 'buttpool/buttpool/iocage/.defaults': parent does not exist
    JID   UUID                                  BOOT  STATE  TAG
    -     -  -     down   -

**Comment by pannon** [comment]
@pr1ntf the ZFS filesystem hierarchy seems odd. The script was designed to work with `poolname/iocroot`  and not `poolname/something/iocroot`.

**Comment by pr1ntf** [comment]
I went back and destroyed the pool, created it again, and pulled down the latest git snap of develop. I did no editing any of the iocage files. I named the pool 'iocage.'

Running 'iocage fetch' still returns the error:

    root@butts:~/iocage # ./iocage fetch
      INFO: Creating iocage/iocage/.defaults.
    cannot create 'iocage/iocage/.defaults': parent does not exist
    Supported releases are: 
       10.1-RELEASE
        9.3-RELEASE
    Please select a release [10.1-RELEASE]: ^C
    root@butts:~/iocage # uname -a
    FreeBSD butts 10.1-RELEASE-p9 FreeBSD 10.1-RELEASE-p9 #0: Wed Apr 29 22:39:37 MDT 2015 root@butts:/usr/obj/usr/src/sys/BUTTKERN  amd64
    root@butts:~/iocage # zfs list
    NAME     USED  AVAIL  REFER  MOUNTPOINT
    iocage  59.5K  5.78G    19K  /iocage
    root@butts:~/iocage # zpool list
    NAME     SIZE  ALLOC   FREE   FRAG  EXPANDSZ    CAP  DEDUP  HEALTH  ALTROOT
    iocage  5.97G    70K  5.97G     0%         -     0%  1.00x  ONLINE  -
    root@butts:~/iocage # 


Can you see anything I am dong wrong here?

**Comment by pr1ntf** [comment]
I guess that is expected behavior. After the first fetch is run, and the first jail is created, .default is there. 

See GIST: https://gist.github.com/pr1ntf/383f3f6d07bdc4322a3e

I'll take a look into the $iocroot issue in the mean time. 
I would still like if I could have a hierarchy of different virtualization solutions on the same pool. 
I am also pretty new to ZFS and may just be using it wrong.

**Comment by pannon** [comment]
@pr1ntf different hierarchy is not required as all iocage related stuff is already stored under pool/iocage top level ZFS filesystem. You don't need to specify anything else than a poolname at the initial setup.

Your issue might be the `comment` variable on your pool. Try resetting it with `zpool set comment='' poolname` then blow away iocage with `zfs destroy -r pool/iocage` and rerun retest develop version (should be all good). 

As for supporting custom depth ZFS filesystems is a can of worms and not

**Comment by pr1ntf** [comment]
Patch is working. Thanks, @pannon !!!
