### ISSUE TITLE
iocage fstab -R "Destination: ... already exists"

### ISSUE THREAD

**Issue by agshekeloh** [iocage/iocage#801]
<pre>

Built iocage today:

storm~;iocage --version
Version 1.1 PRERELEASE 2019/01
storm~;freebsd-version
13.0-CURRENT
storm~;uname -a
FreeBSD storm 13.0-CURRENT FreeBSD 13.0-CURRENT r342739 GENERIC  amd64
storm~;

I have this:

storm/etc;iocage fstab -lh www1
0       /usr/local/scripts /iocage/jails/www1/root/usr/local/scripts nullfs ro 0 0

Want to replace this entry, so:

storm/etc;iocage fstab -R 0 www1 /usr/local/jail-scripts /usr/local/scripts nullfs ro 0 0
Destination: /iocage/jails/www1/root/usr/local/scripts already exists!

Entry is not replaced.

storm/etc;iocage fstab -lh www1
0       /usr/local/scripts /iocage/jails/www1/root/usr/local/scripts nullfs ro 0 0

**Comment by skarekrow** [comment]
You're holding it wrong :P Swap the two.

Adding bug though as iocage should create the destination if it can.

EDIT: Ignore me, I see a different issue here.
