### ISSUE TITLE
"iocage fstab" vs md and tmpfs filesystems

### ISSUE THREAD

**Issue by agshekeloh** [iocage/iocage#806]
<pre> Not sure if a bug or enhancement. I have a jail that needs a memory filesystem in its fstab.

storm~;iocage --version
Version 1.1 PRERELEASE 2019/01
storm~;freebsd-version
13.0-CURRENT
storm~;uname -a
FreeBSD storm 13.0-CURRENT FreeBSD 13.0-CURRENT r342739 GENERIC  amd64

Try to add different memory filesystems to the jail's fstab:

storm~;iocage fstab -a www2 md /tmp mfs rw,-s1g 0 0
Source: md does not exist!
Source: md must use an absolute path!
storm~;iocage fstab -a www2 tmpfs /tmp tmpfs rw,size=1g,mode=1777 0 0
Source: tmpfs does not exist!
Source: tmpfs must use an absolute path!

I'd expect the jail to get a memory filesystem.

Guessing we're tripping over some sort of sanity check here.

**Comment by skarekrow** [comment]
It should allow for different filesystems here, so bug it is :)
