### ISSUE TITLE
can no longer start jails with plain IP in ip4_addr

### ISSUE THREAD

**Issue by agshekeloh** [iocage/iocage#807]
<pre>
Today's iocage, yesterday's -current.  I could start jails last week, but not today.

storm~;iocage --version
Version 1.1 PRERELEASE 2019/01
storm~;uname -a
FreeBSD storm 13.0-CURRENT FreeBSD 13.0-CURRENT r343023 GENERIC  amd64

Have a few jails on this host:

storm~;iocage get -r ip4_addr
+-------------+----------------------+
|    NAME     |   PROP - ip4_addr    |
+=============+======================+
| dns3        | none                 |
+-------------+----------------------+
| dns4        | 203.0.113.244        |
+-------------+----------------------+
| dnstemplate | 203.0.113.245        |
+-------------+----------------------+
| squid1      | 203.0.113.240        |
+-------------+----------------------+
| wdb2        | 203.0.113.237        |
+-------------+----------------------+
| www1        | em1|203.0.113.234    |
+-------------+----------------------+
| www2        | em1|203.0.113.235/24 |
+-------------+----------------------+

When I try to start any of the jails that have a naked IP address in ip4_addr, it will not start:

storm~;iocage start dns4
Traceback (most recent call last):
  File "/usr/local/bin/iocage", line 10, in <module>
    sys.exit(cli())
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/iocage_cli/start.py", line 60, in cli
    ioc.IOCage(jail=jail, rc=rc).start(ignore_exception=ignore)
  File "/usr/local/lib/python3.6/site-packages/iocage_lib/iocage.py", line 1782, in start
    suppress_exception=ignore_exception
  File "/usr/local/lib/python3.6/site-packages/iocage_lib/ioc_start.py", line 76, in __init__
    raise e
  File "/usr/local/lib/python3.6/site-packages/iocage_lib/ioc_start.py", line 73, in __init__
    self.__start_jail__()
  File "/usr/local/lib/python3.6/site-packages/iocage_lib/ioc_start.py", line 287, in __start_jail__
    ip4_addr = self.check_aliases(ip4_addr)
  File "/usr/local/lib/python3.6/site-packages/iocage_lib/ioc_start.py", line 686, in check_aliases
    for address in netifaces.ifaddresses(interface)[inet_mode]:
KeyError: 2

Note that the IP addresses are already on the proper NIC.

I can stop and restart the jails with ip4_addr="nic|ip-address" without trouble.

If I try to specify a NIC with the address:

storm~;iocage set dns4 ip4_addr="em1|203.0.113.244"
dns4 is is missing a value!
storm~;iocage set dns4 ip4_addr="em1|203.0.113.244/24"
dns4 is is missing a value!

It was happy last week, so this is at least a behavior change. Or iocage tolerated my incorrect behavior until now.

**Comment by agshekeloh** [comment]
<pre>A simpler test, with a known OK jail.

storm~;iocage destroy dns3

This will destroy jail dns3

Are you sure? [y/N]: y
Destroying dns3
storm~;iocage create -r 11.2-RELEASE -b -n dns3 ip4_addr="203.0.113.243"
dns3 successfully created!
storm~;iocage start dns3
Traceback (most recent call last):
  File "/usr/local/bin/iocage", line 10, in <module>
    sys.exit(cli())
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/iocage_cli/start.py", line 60, in cli
    ioc.IOCage(jail=jail, rc=rc).start(ignore_exception=ignore)
  File "/usr/local/lib/python3.6/site-packages/iocage_lib/iocage.py", line 1782, in start
    suppress_exception=ignore_exception
  File "/usr/local/lib/python3.6/site-packages/iocage_lib/ioc_start.py", line 76, in __init__
    raise e
  File "/usr/local/lib/python3.6/site-packages/iocage_lib/ioc_start.py", line 73, in __init__
    self.__start_jail__()
  File "/usr/local/lib/python3.6/site-packages/iocage_lib/ioc_start.py", line 287, in __start_jail__
    ip4_addr = self.check_aliases(ip4_addr)
  File "/usr/local/lib/python3.6/site-packages/iocage_lib/ioc_start.py", line 686, in check_aliases
    for address in netifaces.ifaddresses(interface)[inet_mode]:
KeyError: 2
storm~;iocage destroy dns3

This will destroy jail dns3

Are you sure? [y/N]: y
Destroying dns3
storm~;iocage create -r 11.2-RELEASE -b -n dns3 ip4_addr="em1|203.0.113.243"
dns3 successfully created!
storm~;iocage start dns3
* Starting dns3
  + Started OK
  + Using devfs_ruleset: 16
  + Starting services OK
  + Executing poststart OK

**Comment by sonicaj** [comment]
Thank you for letting us know more about this. Can you please share output of ifconfig ? You can perhaps mask the sensitive information like mac addr etc ? I am more inclined to believe that something in your network configuration changed. This is a valid bug however which needs to be fixed but it would be awesome if we could know the exact source which triggered it. Thanks again!

**Comment by agshekeloh** [comment]
storm~;ifconfig
em0: flags=8802<BROADCAST,SIMPLEX,MULTICAST> metric 0 mtu 1500
        options=81249b<RXCSUM,TXCSUM,VLAN_MTU,VLAN_HWTAGGING,VLAN_HWCSUM,LRO,WOL_MAGIC,VLAN_HWFILTER>
        ether 00:25:90:db:d5:94
        media: Ethernet autoselect (1000baseT <full-duplex>)
        status: active
        nd6 options=29<PERFORMNUD,IFDISABLED,AUTO_LINKLOCAL>
em1: flags=8843<UP,BROADCAST,RUNNING,SIMPLEX,MULTICAST> metric 0 mtu 1500
        options=81249b<RXCSUM,TXCSUM,VLAN_MTU,VLAN_HWTAGGING,VLAN_HWCSUM,LRO,WOL_MAGIC,VLAN_HWFILTER>
        ether 00:25:90:db:d5:95
        inet 203.0.113.50 netmask 0xffffff00 broadcast 203.0.113.255
        inet 203.0.113.231 netmask 0xffffffff broadcast 203.0.113.231
        inet 203.0.113.232 netmask 0xffffffff broadcast 203.0.113.232
        inet 203.0.113.233 netmask 0xffffffff broadcast 203.0.113.233
        inet 203.0.113.236 netmask 0xffffffff broadcast 203.0.113.236
        inet 203.0.113.237 netmask 0xffffffff broadcast 203.0.113.237
        inet 203.0.113.238 netmask 0xffffffff broadcast 203.0.113.238
        inet 203.0.113.239 netmask 0xffffffff broadcast 203.0.113.239
        inet 203.0.113.240 netmask 0xffffffff broadcast 203.0.113.240
        inet 203.0.113.241 netmask 0xffffffff broadcast 203.0.113.241
        inet 203.0.113.242 netmask 0xffffffff broadcast 203.0.113.242
        inet 203.0.113.244 netmask 0xffffffff broadcast 203.0.113.244
        inet 203.0.113.245 netmask 0xffffffff broadcast 203.0.113.245
        inet 203.0.113.246 netmask 0xffffffff broadcast 203.0.113.246
        inet 203.0.113.221 netmask 0xffffffff broadcast 203.0.113.221
        inet 203.0.113.222 netmask 0xffffffff broadcast 203.0.113.222
        inet 203.0.113.223 netmask 0xffffffff broadcast 203.0.113.223
        inet 203.0.113.224 netmask 0xffffffff broadcast 203.0.113.224
        inet 203.0.113.225 netmask 0xffffffff broadcast 203.0.113.225
        inet 203.0.113.226 netmask 0xffffffff broadcast 203.0.113.226
        inet 203.0.113.227 netmask 0xffffffff broadcast 203.0.113.227
        inet 203.0.113.243 netmask 0xffffffff broadcast 203.0.113.243
        inet 203.0.113.234 netmask 0xffffffff broadcast 203.0.113.234
        inet 203.0.113.235 netmask 0xffffff00 broadcast 203.0.113.255
        media: Ethernet autoselect (1000baseT <full-duplex>)
        status: active
        nd6 options=29<PERFORMNUD,IFDISABLED,AUTO_LINKLOCAL>
lo0: flags=8049<UP,LOOPBACK,RUNNING,MULTICAST> metric 0 mtu 16384
        options=680003<RXCSUM,TXCSUM,LINKSTATE,RXCSUM_IPV6,TXCSUM_IPV6>
        inet6 ::1 prefixlen 128
        inet6 fe80::1%lo0 prefixlen 64 scopeid 0x3
        inet 127.0.0.1 netmask 0xff000000
        groups: lo
        nd6 options=21<PERFORMNUD,AUTO_LINKLOCAL>

I should add: the host wasn't rebooted between iocage updates.

I booted, started my jails, all was good. A few days passed, I updated iocage a couple times, all seemed good until I restarted a jail.

I want to say "I don't see how the network could have changed" but we're talking computers here. ;-)

**Comment by agshekeloh** [comment]
also, rc.conf:

storm~;grep ifconfig /etc/rc.conf
#ifconfig_em0="inet 198.51.100.50/24"
#ifconfig_em0="up"
#ifconfig_em0_2="198.22.65.236/28"
#ifconfig_em0_3="198.51.100.50/24"
ifconfig_em1="inet 203.0.113.50/24"
ifconfig_em1_alias0="inet 203.0.113.231/32"
ifconfig_em1_alias1="inet 203.0.113.232/32"
ifconfig_em1_alias2="inet 203.0.113.233/32"
ifconfig_em1_alias3="inet 203.0.113.234/32"
ifconfig_em1_alias4="inet 203.0.113.235/32"
ifconfig_em1_alias5="inet 203.0.113.236/32"
ifconfig_em1_alias6="inet 203.0.113.237/32"
ifconfig_em1_alias7="inet 203.0.113.238/32"
ifconfig_em1_alias8="inet 203.0.113.239/32"
ifconfig_em1_alias9="inet 203.0.113.240/32"
ifconfig_em1_alias10="inet 203.0.113.241/32"
ifconfig_em1_alias11="inet 203.0.113.242/32"
ifconfig_em1_alias12="inet 203.0.113.243/32"
ifconfig_em1_alias13="inet 203.0.113.244/32"
ifconfig_em1_alias14="inet 203.0.113.245/32"
ifconfig_em1_alias15="inet 203.0.113.246/32"
ifconfig_em1_alias16="inet 203.0.113.221/32"
ifconfig_em1_alias17="inet 203.0.113.222/32"
ifconfig_em1_alias18="inet 203.0.113.223/32"
ifconfig_em1_alias19="inet 203.0.113.224/32"
ifconfig_em1_alias20="inet 203.0.113.225/32"
ifconfig_em1_alias21="inet 203.0.113.226/32"
ifconfig_em1_alias22="inet 203.0.113.227/32"

**Comment by sonicaj** [comment]
So this issue is fixed in the above referenced commit. Thanks again ;)
