### ISSUE TITLE
Can't re-use jail names when creating with a template

### ISSUE THREAD

**Issue by kchiem** [iocage/iocage#809]
Make sure to follow and check these boxes before submitting an issue! Thank you.

- [x] Supply `iocage --version`

# iocage --version
Version	1.0 RELEASE 2018/12

- [x] Supply the commands used, along with any steps to recreate it.
- [x] Provide the output from the command you issued.
- [x] Supply what you expected the result or output to be
- [x] Checked that the problem has not already been fixed on `master` if using
 a stable release.

# iocage create -t base -n foo
foo successfully created!

# iocage destroy foo

This will destroy jail foo

Are you sure? [y/N]: y
Destroying foo

# iocage create -t base -n foo
Template: foo not found!

**Comment by gronke** [comment]
Why does the error message say `Template: foo not found!`? **foo** is the name of the jail to be created, not a template.

**Comment by smortex** [comment]
Workaround: remove existing ZFS snapshot manually:

```sh-session
romain@zappy ~ % sudo iocage create -t puppet5 -n puppet 'ip4_addr=wlan0|192.168.1.209'
Template: puppet not found!
romain@zappy ~ % zfs list -t snapshot
NAME                                              USED  AVAIL  REFER  MOUNTPOINT
zroot/iocage/releases/11.2-RELEASE/root@puppet5      0      -  1022M  -
zroot/iocage/templates/puppet5@puppet                0      -    92K  -
zroot/iocage/templates/puppet5@puppetdb              0      -    92K  -
zroot/iocage/templates/puppet5@node1                 0      -    92K  -
zroot/iocage/templates/puppet5@node2                 0      -    92K  -
romain@zappy ~ % sudo zfs destroy zroot/iocage/templates/puppet5@puppet
romain@zappy ~ % sudo iocage create -t puppet5 -n puppet 'ip4_addr=wlan0|192.168.1.209'
puppet successfully created!
```
