### ISSUE TITLE
Set MAC of VNET epair

### ISSUE THREAD

**Issue by kev009** [iocage/iocage#81]
I use bridged networking like this:

```
ifconfig_cxl0="up"
ifconfig_vlan1="vlan 1 vlandev cxl0 up"
ifconfig_vlan1010="vlan 1010 vlandev cxl0 up"
ifconfig_vlan1011="vlan 1011 vlandev cxl0 up"
ifconfig_bridge1="inet 10.10.9.56/24 addm vlan1 description vlan1 up"
ifconfig_bridge1010="inet 10.10.10.56/24 addm vlan1010 description vlan1010 up"
ifconfig_bridge1011="inet 10.10.11.56/24 addm vlan1011 description vlan1011 up"

iocage create interfaces=vnet0:bridge1 ip4_addr=vnet0|10.10.9.57
```

That works great.  Problem is, when I add another iocage host to the same network segment, MAC collisions are very easy to trigger.

I uniqify the bridge MACs on the host with start_if scripts like:
```
# cat /etc/start_if.bridge1
ifconfig bridge1 ether 02:f2:8f:44:15:00
```

I need to uniqify the VNET jail's mac.  It would be cool to have an iocage parameter to set the MAC of the epair.  I can do it with 'ifconfig ether' or start_if scripts within the jail.

**Comment by kev009** [comment]
Also on the FreeBSD side this is an insecure isolation point since root user of the VNET jail can take over other MACs on the network?

**Comment by skarekrow** [comment]
I agree this would be a nice enhancement. As far as the insecure isolation point, I don't believe so. They cannot change their interface inside the jail. So this would be the root user of the host machine making these collisions.

**Comment by robertbarabas** [comment]
I concur with the previous as I just hit the same issue in our environment. :)

We are using unique IPs so I'm planning to hash my "unique 32 bits" and use in a MAC. I will likely store it as a custom property with the jail to tie it to the instance (the jail instance might be zfs sent to another host on occasion).

**Comment by pannon** [comment]
I think we could add a mac address property for that and store it for the jail just like any other properties. Might be wort to raise an issue at FreeBSD.org for VNET/epair.

**Comment by pannon** [comment]
also found this one liner to generate MACs `env LC_ALL=C tr -c -d '0123456789abcdef' < /dev/urandom | head -c 12 | sed 's!^M$!!;s!\-!!g;s!\.!!g;s!\(..\)!\1:!g;s!:$!!'`

Anyone has a comment on this? We could utilize this to some extent and randomize MACs.

Source: https://forums.freebsd.org/threads/randomizing-mac-at-boot.30603/

**Comment by pannon** [comment]
FreeBSD seem to have a registered prefix of `58-9C-FC`, check this http://standards-oui.ieee.org/oui.txt 
we could use that prefix and generate the rest.

**Comment by skarekrow** [comment]
Doesn't /dev/urandom only have so much entropy to spare? It's also
incredibly expensive. Maybe it would be better to use /dev/random? Also
that sed command...is something else haha.

**Comment by pr1ntf** [comment]
I like keeping the standard prefix. 
That one liner is pretty awesome, but I think it would be better to try and simplify? (Like just pulling the first however many characters match 0-9 and A-F from /dev/urandom)
But as Brandon, said, that can be heavy. 
As far as I know, /dev/urandom pulls direct from the entropy pool in FreeBSD. Might be mistaken. 

I had never even thought of mac address collisions until this. 
I'm all for setting a random MAC at jail creation time.

**Comment by pannon** [comment]
Anyone volunteering for the MAC generation part ;) ? I will take the custom property integration!

**Comment by robertbarabas** [comment]
I am going to take a stab at it. 

As far as the MAC goes, vnet(9) seems to use 02:ff:60 as its OUI. That OUI seems to be unregistered/unclaimed. As far as randomness goes, we have a fairly limited pool here. We have 3 bytes available to us, the non-OUI octets. The pool is actually a half of this as each pair will consume two addresses from the pool. That leaves us with about ~8M combinations. 

Instead of randomness I would prefer an algorithm that yields usable pairs as the default values for vnet and also make the corresponding jail/iocage argument manually settable so one can easily manually assign / override.

**Comment by robertbarabas** [comment]
I take that back, the OUIs are different in the jailhost and in the jail. So that leaves us with 3 bytes / ~16M of space.

**Comment by pannon** [comment]
@robertbarabas that would be much appreciated. I will prepare the property handling.

**Comment by skarekrow** [comment]
Yes, thanks @robertbarabas. I'm interested to see how you approach this.

**Comment by pannon** [comment]
Just pushed the support for mac properties. Have moved most of the mac generation magic out to a separate function. We have a new property per interface called `vnet*_mac` which expects 2 mac addresses separated by a comma example `02ff60E06C8D,02ff60E06C8E`. The first field is for epair_a the second for epair_b.

Things are automated and should not require fiddling manually with saved properties - unless testing.

A quick breakdown how this should work:
1. when the jail is first started with vnet generate all mac addresses
2. save these macs out to the mac property into ZFS
3. when the jail is started check for existing mac if found use it - if not generate one and save

Please feel free to comment before this gets any further.

**Comment by pannon** [comment]
Closing this, will be merged to master soon.
