### ISSUE TITLE
log commands executed for iocage

### ISSUE THREAD

**Issue by Licenser** [iocage/iocage#81]
How do you feel about every command being executed to be logged in /var/log/iocage

that way it'd be easier to retrace steps / issues?

**Comment by skarekrow** [comment]
Right now it's an all or nothing task that you can change with the environment variable `IOCAGE_LOGFILE`, so you can have it write to a file instead. I'd be very happy to get a PR where it does both.

**Comment by Licenser** [comment]
I'll have a PR later today :)

**Comment by Licenser** [comment]
quick q: Any favourite logging library/

**Comment by skarekrow** [comment]
Just been using the standard `logging` one, I have no favorites :D

**Comment by Licenser** [comment]
Okay reading up a bit on it, quick approach to see if you're ok with that:

1) add a 'logfile' logger that writes to /var/log/iocage.log
2) abstract the current log calls into ioc_logging.py so they:
  * do the current log
  * also write for to the logfile logger

sounds good?

**Comment by skarekrow** [comment]
Sounds great to me!

So this would allow the user to have a constant log to `/var/log/iocage.log` and also be able to specify another custom log or `stdout` via the `IOCAGE_LOGFILE` mechanism that is already in place?

**Comment by Licenser** [comment]
Awesome :)!

And yes that was the thought, it'd not surprise people by changing the behaviour but extend it to with a static file.

**Comment by skarekrow** [comment]
Great! Very excited to see it :D

**Comment by Licenser** [comment]
This is getting a bit out of hand, for some reason it seems like ALL the output is presented as log. Which seems rather wrong to me. i.e. the table for `iocage list` results in:

```
2017-03-22 18:27:04,603 /usr/local/lib/python3.6/site-packages/iocage/cli/list.py [3024]: INFO +-----+----------+-------+----------------------------+--------------+---------------+
| JID |   UUID   | STATE |            TAG             |   RELEASE    |      IP4      |
+=====+==========+=======+============================+==============+===============+
| 1   | 05a94226 | up    | 2017-03-22@02:17:22:761479 | 11.0-RELEASE | 192.168.1.210 |
+-----+----------+-------+----------------------------+--------------+---------------+
```

Now this feels like re-writing a whole lot of the code to get that changed so before I jump into that I'd like to know what you think is the best approach.

To me those things don't belong in a log file, I'd personally change all the log.info's there into something like printf? But that feels like quite the big change in design.

**Comment by skarekrow** [comment]
They were originally just `prints` but I was told that a lib shouldn't print ha. So I went and made them log instead, but the issue ofc is that it's a ginormous amount of stuff to rewrite so that the cli handles all the logging and the lib only passes objects. 

So ideally we change the libs to only return objects and such and the cli logs those. Which is why this was near the very bottom of my TODO :D

**Comment by Licenser** [comment]
So the basic problem is that the whole lib design kind of needs to be rewritten from what I gather? :(

**Comment by skarekrow** [comment]
In a rough sense yes if we want good logs in two locations. Otherwise it would be a mirror. I'm not sure how much I would have to rewrite to get that behavior, but it's not trivial for sure. I viewed it as a cosmetic thing, as it was mostly born out of how I thought about things (coming from a shell background instead of python, so no OO for me :D). The user isn't aware where the messages are coming from, so it didn't seem too pressing.

Now that you mention having a log, which sounds great, it seems more important.

**Comment by Licenser** [comment]
I think it gets ugly when logging and user output got mixed. 'a library should not print' makes sense if it's used as a stand lone library, but sadly 'a log is not for user output' also makes sense. I think the current state is commonly described in english as being stuck between a rock and a hard place :/

**Comment by skarekrow** [comment]
That is the correct idiom yes. The situation is ugly for sure. The idea is for iocage to have a standalone library, as we will be using it on FreeNAS as such. It's going to be some effort for sure :(

**Comment by Licenser** [comment]
For reference I'll attach a log from vmadm the way to log JOSN is arguable horrible but the content and detail of logging is excellent.

It really helps tracking down problems :)

[1490329793643-043047-vmadm.txt](https://github.com/iocage/iocage/files/866886/1490329793643-043047-vmadm.txt)

**Comment by skarekrow** [comment]
I'm going to close this as the general idea is done. But the logging will need to be continually refined. But atleast we have a logfile and stdout/stderr. That's progress :D
