### ISSUE TITLE
iocage devfs_ruleset doesn't mention that rule 4 isn't devfs.rules rule 4

### ISSUE THREAD

**Issue by agshekeloh** [iocage/iocage#812]
<pre>storm~;uname -a
FreeBSD storm 13.0-CURRENT FreeBSD 13.0-CURRENT r343023 GENERIC  amd64
storm~;iocage --version
Version 1.1 PRERELEASE 2019/01

A note in iocage(8) that says something like "The default iocage ruleset is hard-coded into iocage, and cannot be altered by devfs.conf; make a whole new ruleset and assign devfs_ruleset to that ruleset" would have saved me much frustration.

Why?

I wanted to change the default rules for my jails.

devfs_ruleset says the jails use ruleset 4. I overrode ruleset 4 in /etc/devfs.conf.

No change on the jails.

There's a ruleset 5 in /etc/devfs.conf, placed by iocage. According to devfs_ruleset it's not used, but it matches the devices actually in my jail. Edited that, no joy.

Beat my head against devfs for a while, trying to figure out where these rules were coming from. Finally, in desperation, I read the source.

Ideally I'd ask that you change the default iocage devfs ruleset to something that's not used in the base system to completely avoid this confusion, but I understand that's not going to happen, so please at least document it to save users the pain. Thank you.

**Comment by skarekrow** [comment]
We spoke about this in DM's and I agree. Documenting it is the best approach as '4' is a placeholder which tells iocage there is no user specified devfs_ruleset and to make one. The ruleset 5 you see is likely an old remnant of how iocage used to do things with a static ruleset. Same reason these docs are behind :)
