### ISSUE TITLE
Is it possible to release smaller bug fixes sooner?

### ISSUE THREAD

**Issue by billybigrigger** [iocage/iocage#819]
stuck with 1.0 RELEASE and waiting for a new iocage cage release a month later just to get some bugfixes so i can upgrade the 20+ jails i have stuck on 11.2, also allow.vmm was added since 1.0

is there anyway that you can push these fixes/features in smaller updates ie 1.0.1 more frequently?

**Comment by skarekrow** [comment]
1.1 will be this week, it's only been a few weeks. You can always use GitHub if the wait is too long, but we want stability when we release a new version, or the best we can get to that.
