### ISSUE TITLE
Setting a quota too small for the release leads to pain and agony

### ISSUE THREAD

**Issue by Licenser** [iocage/iocage#82]
This is the cause for #80 

User error part: Setting the quota to '10' assuming 10 means 10 GB

It would probably be good to:

1) validate here (not sure against what?)
2) clean up afterwards if things go bad.

```
cannot set property for 'zroot/iocage/jails/051036d8-6b9e-4a41-bde3-4141dc427c95': size is less than current used or reserved space
Traceback (most recent call last):
  File "/usr/local/bin/iocage", line 10, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.6/site-packages/iocage/main.py", line 94, in main
    cli(obj=MODULES)
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/iocage/cli/create.py", line 95, in create_cmd
    basejail=basejail, empty=empty).create_jail()
  File "/usr/local/lib/python3.6/site-packages/iocage/lib/ioc_create.py", line 152, in create_jail
    iocjson.json_check_prop(key, value, config)
  File "/usr/local/lib/python3.6/site-packages/iocage/lib/ioc_json.py", line 629, in json_check_prop
    f"{pool}/iocage/{_type}/{uuid}"])
  File "/usr/local/lib/python3.6/site-packages/iocage/lib/ioc_common.py", line 191, in checkoutput
    out = check_output(*args, **kwargs).decode("utf-8")
  File "/usr/local/lib/python3.6/subprocess.py", line 336, in check_output
    **kwargs).stdout
  File "/usr/local/lib/python3.6/subprocess.py", line 418, in run
    output=stdout, stderr=stderr)
subprocess.CalledProcessError: Command '['zfs', 'set', 'quota=10', 'zroot/iocage/jails/051036d8-6b9e-4a41-bde3-4141dc427c95']' returned non-zero exit status 1.
[root@fifo-bsd ~/iocage]#
```

**Comment by skarekrow** [comment]
This seems to have happened after the initial jail creation?

It would be hard for me to catch this I think as like you said what do I validate that against? But then again I might be missing something. I'll close this as a `wontfix` but if you have any ideas I'm all ears.

**Comment by Licenser** [comment]
Even if it's not checked (and I don't have a good plan either) quota=10 should **not** result in iocage becoming globally unusable leaving the system with a half broken jail.

**Comment by skarekrow** [comment]
Well I can't go against the user. They're setting a size too small for the configuration file to be written. That's going to cause issues.

**Comment by skarekrow** [comment]
I'm actually going to reopen this as I think we can atleast try to prevent a bit of foot shooting on iocage's side, unless they go above us to `zfs`.

**Comment by Licenser** [comment]
The issue is not that the jail doesn't work, that is expected (in a way) but that it does make iocage unusable afterwards and not for this one rail but gobally totally breaks iocage any `iocage ...` command crashes after this. Go give the command a try.

**Comment by skarekrow** [comment]
Yeah this would cause issues parsing the configuration which would cause `iocage list` to barf. It's going to be requiring a change here and a change like I suggested in #80. I'll work on this to atleast give a nice error.

**Comment by Licenser** [comment]
How about on a failed create just destroying the zone cleanly? That way even if someone silly like me passes quota=10  the worst they get is 'your creation failed!'

**Comment by skarekrow** [comment]
I'm going to do three things I think here:
- Check for M, G, T suffix on quota. That should alone be enough to stop foot shooting after creation.
- Have a graceful failure for missing config.json that something like this could cause during creation
- Check if I can catch this during creation and then destroy the jail before more damage happens.

Sound good?

**Comment by Licenser** [comment]
sounds awesome :D I like the cehck for suffix, it forces people to think about what they're doing ;)

**Comment by skarekrow** [comment]
:D Great, will proceed on this line of thinking then. Let's hope that keeps most the dragons away!
