### ISSUE TITLE
corrupt configurations since 1.1 upgrade

### ISSUE THREAD

**Issue by dBitech** [iocage/iocage#832]
I just upgraded from 1.0.0.20181219,1 to 1.1-RELEASE

root@quad:/ # iocage --version
Version 1.1 RELEASE 2019/01

Every one of my jails is now complaining that its missing the configuration, and I need to destroy/recreate it.

frex:
root@quad:/ # iocage console mqtt
mqtt is missing it's configuration, please destroy this jail and recreate it.

or 

root@quad:/ # iocage list
mqtt is missing it's configuration, please destroy this jail and recreate it.
plex is missing it's configuration, please destroy this jail and recreate it.
+-----+--------------+---------+---------+-----+
| JID |     NAME     |  STATE  | RELEASE | IP4 |
+=====+==============+=========+=========+=====+
| -   | mqtt         | CORRUPT | N/A     | N/A |
+-----+--------------+---------+---------+-----+
| -   | plex         | CORRUPT | N/A     | N/A |
+-----+--------------+---------+---------+-----+

**Comment by dgeo** [comment]
Had the same symptom here, corrected by removing 'tag' from config.json . Hope this can help...

**Comment by skarekrow** [comment]
Interesting, @dBitech does this solve it for you as well? Can you post these jails config.jsons?

**Comment by dBitech** [comment]
there were no "tag" in the configurations I could find.   A reboot of the host seemed to have corrected the issue.

**Comment by skarekrow** [comment]
Great, I tried adding tag myself and it didn't trigger the behavior. Thanks for replying back!

**Comment by pludi** [comment]
Had the same issue.

1.  One workaround is `service iocage restart`, no need to restart the whole host
2.  Before the restart all `config.json` had `"CONFIG_VERSION": "16"`, now it's `"CONFIG_VERSION": "17"` (didn't check for any other differences)

*Might* be that simply updating the `CONFIG_VERSION` in the `.json`s could be enough.
