### ISSUE TITLE
"iocage create" crash

### ISSUE THREAD

**Issue by agshekeloh** [iocage/iocage#841]
<pre>

Today's iocage, yesterday's -current and packages

storm~;iocage --version
Version 1.1 RELEASE 2019/01
storm~;uname -a
FreeBSD storm 13.0-CURRENT FreeBSD 13.0-CURRENT r343578 GENERIC  amd64

storm~;iocage create -n squid1 -r 12.0-RELEASE
Traceback (most recent call last):
  File "/usr/local/bin/iocage", line 10, in <module>
    sys.exit(cli())
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/iocage_cli/create.py", line 182, in cli
    thickconfig=thickconfig)
  File "/usr/local/lib/python3.6/site-packages/iocage_lib/iocage.py", line 646, in create
    thickconfig=thickconfig
  File "/usr/local/lib/python3.6/site-packages/iocage_lib/ioc_create.py", line 92, in create_jail
    return self._create_jail(jail_uuid, location)
  File "/usr/local/lib/python3.6/site-packages/iocage_lib/ioc_create.py", line 175, in _create_jail
    self.release
  File "/usr/local/lib/python3.6/site-packages/iocage_lib/ioc_common.py", line 899, in get_jail_freebsd_version
    for line in r:
  File "/usr/local/lib/python3.6/encodings/ascii.py", line 26, in decode
    return codecs.ascii_decode(input, self.errors)[0]
UnicodeDecodeError: 'ascii' codec can't decode byte 0xc3 in position 47: ordinal not in range(128)

Expected output? "Here's your jail."

**Comment by skarekrow** [comment]
What does your env and locale look like?

**Comment by agshekeloh** [comment]
storm~;env
HOME=/home/mwlucas
PATH=/sbin:/bin:/usr/sbin:/usr/bin:/usr/local/sbin:/usr/local/bin:/home/mwlucas/bin
TERM=xterm
LC_COLLATE=C
LANG=en_US.UTF-8
SSH_AUTH_SOCK=/tmp/ssh-9HXeRFFFdR/agent.2352
SSH_CLIENT=203.0.113.65 6424 22
SSH_CONNECTION=203.0.113.65 6424 203.0.113.50 22
SSH_TTY=/dev/pts/1
LC_CTYPE=en_US.ISO-8859-1
MAIL=/var/mail/root
LOGNAME=root
USER=root
SHELL=/bin/csh
SUDO_COMMAND=/usr/bin/su -m
SUDO_USER=mwlucas
SUDO_UID=1001
SUDO_GID=1001
HOSTTYPE=FreeBSD
VENDOR=amd
OSTYPE=FreeBSD
MACHTYPE=x86_64
SHLVL=1
PWD=/home/mwlucas
GROUP=wheel
HOST=storm
REMOTEHOST=203.0.113.65
EDITOR=emacs
PAGER=less
BLOCKSIZE=K
IRCNICK=mwlucas
IRCNAME=Michael W Lucas
IRCSERVER=irc.arcti.ca
crt=24
storm~;locale
LANG=en_US.UTF-8
LC_CTYPE="C"
LC_COLLATE=C
LC_TIME="C"
LC_NUMERIC="C"
LC_MONETARY="C"
LC_MESSAGES="C"
LC_ALL=
storm~;

**Comment by igalic** [comment]
iocage requires UTF8 as system locale.

**Comment by skarekrow** [comment]
It looks like he has that set, it could be a regression from https://github.com/iocage/iocage/pull/840

**Comment by agshekeloh** [comment]
Grabbed the 1.1 tarball, extracted, make install, and:

storm~/iocage-1.1;iocage create -n squid1 -r 12.0-release
squid1 successfully created!

**Comment by sonicaj** [comment]
Just to confirm @agshekeloh, the problem does not exist in the latest iocage version for you ? I haven't had the time to look into this yet, will do so later today hopefully

**Comment by agshekeloh** [comment]
correct.

**Comment by sonicaj** [comment]
I think it is safe to close this issue then. If you have any concerns, please feel free to re open it or comment, and we will have it sorted out ;) Thank you for the feedback ;)

**Comment by agshekeloh** [comment]
I  think I was unclear sorry.

The problem is not in the latest iocage RELEASE. Brandon asked me to test that.

It IS in the latest iocage "git pull"

**Comment by sonicaj** [comment]
Uh oh, my bad. Thank you for letting me know. Will have this sorted soon ;)

**Comment by agshekeloh** [comment]
no worries, all good. :-)

**Comment by agshekeloh** [comment]
This appears to have fixed the problem. Not sure what my locale tripped, but your big hammer solved it just fine. :-)

**Comment by sonicaj** [comment]
@agshekeloh it was not your locale at all ;)

**Comment by sonicaj** [comment]
I should add almost :D
