### ISSUE TITLE
Fetch ignores the release option and prompts for user input

### ISSUE THREAD

**Issue by sheldonwjones** [iocage/iocage#85]
Iocage fetch release=10.1-RELEASE doesn’t accept the release argument. It prompts for a user selection with or without the release option. Is there a way to script the fetch process?

**Comment by skarekrow** [comment]
The ```release=``` option preselects the release in question, but it does wait for user input. Currently we do not have it scriptable. But this one is easily worked around with an echo!

Example:
```echo | iocage fetch release=10.1-RELEASE``` 

That will solve the issue for the interim.

**Comment by sheldonwjones** [comment]
That works, thank you for the quick response.

**Comment by skarekrow** [comment]
No problem! Leave the issue open though, as we will be looking at doing it the right way and not the echo hack.

**Comment by sheldonwjones** [comment]
I'm looking forward to the improvements. It would be great if we could also specify the pool. Something like iocage fetch release=10.1-RELEASE pool=jails.

**Comment by pr1ntf** [comment]
+1 that idea.

**Comment by skarekrow** [comment]
Currently we don't have plans to support multiple pools. That may change in the future, and if it does it's reasonable to assume fetch would get that support.

**Comment by pr1ntf** [comment]
I think he meant making it easier to script an install, not multiple pools. 
At least that's what I was +1ing.

**Comment by skarekrow** [comment]
After having talked with @pr1ntf I think I misunderstood. You are talking on a fresh install where iocage has not been told it has a pool for use?

**Comment by sheldonwjones** [comment]
I'm using ansible to bootstrap my jailer hosts. Basically what ansible is doing is pkg install iocage. Then running iocage fetch to get the jail environment up and running. The hosts already have zpool created but iocage asks which pool to use.

**Comment by skarekrow** [comment]
Right, then I did misinterpret this. Using the echo trick with fetch should also select the default pool iocage locates. If you need a different one then ```zpool set comment=iocage POOL``` should work fine for you. I'll look into adding a ```pool``` command so you don't have to use that hack as well.

**Comment by pannon** [comment]
@sheldonwjones iocage is just looking for the pool `comment` property. If it is set to `iocage` as @skarekrow detailed it wont prompt for selection. We will add a headless pool activation soon.

**Comment by robertbarabas** [comment]
FYI, you can also create the pool with an Ansible ZFS task in the interim
which would preempt the issue.
~

R.

**Comment by pannon** [comment]
@sheldonwjones have pushed a zpool activation function just now. Hope it helps you simplify things with automation.
