### ISSUE TITLE
enhancement request: exec.created

### ISSUE THREAD

**Issue by agshekeloh** [iocage/iocage#855]
```
storm~;iocage --version
Version 1.2 BETA
storm~;uname -a
FreeBSD storm 13.0-CURRENT FreeBSD 13.0-CURRENT r343907 GENERIC  amd64
```
jail(8) supports exec.created. Iocage doesn't have this parameter. It would be useful for, among other things, truly jailing ZFS datasets.

**Comment by laidback01** [comment]
12.0-CURRENT doesn't seem to have exec.created in jail.  can't find it in the man page, and can't run iocage created jails at the moment.

**Comment by laidback01** [comment]
I am using GhostBSD, based upon 12.0-CURRENT.  Changing line 311 in /usr/local/lib/python3.6/site-packages/iocage_lib/ioc_start.py   to   if userland_version < 12.1:  allows me to skip out on using exec.created.   I installed iocage via the "Using GitHub" method of installation.  iocage --version yields 1.2 RC

**Comment by skarekrow** [comment]
@ericbsd ^ Is there something different with 12-CURRENT in GhostBSD?

**Comment by laidback01** [comment]
I appended to this ticket because it was the link that duckduckgo took me to first - regarding exec.created.  So, the note is to help potentially other people with a similar problem. As to differences, I am sure, but limited experience with GhostBSD prevents identification, apologies.

**Comment by ericbsd** [comment]
@laidback01 I would recommend you to reinstall GhostBSD to 19.04 which is base on CURRENT-13 and more stable than 18.12. GhostBSD base on 12-CURRENT is starting to be old and we did not upgrade any software for a while because of compatibility issues. See https://www.ghostbsd.org/19.04_release_announcement

**Comment by laidback01** [comment]
fair enough, thanks
