### ISSUE TITLE
Don't start a jail on calling "iocage console" if it is not running already

### ISSUE THREAD

**Issue by Corvan** [iocage/iocage#856]
Hey guys,

minor remark: similarly to this, iocage should IMHO *not* silently start a jail that is offline when I issue `iocage console foo` ...
Suggestion: error message "jail is down, use -f to force-start" or similar.

Kind regards,
Patrick

_Originally posted by @pmhausen in https://github.com/iocage/iocage/pull/831#issuecomment-460938232_

**Comment by skarekrow** [comment]
So the current behavior of exec and console do this, as I found it to be an inconvenience that if the jail wasn't running, my command still was not fired off. Changing that now could be a POLA violation as users may be abusing this for their own things, but I'm up for a discussion on why this is annoying behavior.

**Comment by igalic** [comment]
n.b.: in `ioc` we have a `-s` option for `console` and `provision` subcommands

**Comment by pmhausen** [comment]
OK, complete story ... :-)

I wanted to do `iocage chroot` into a shutdown jail. I use this frequently to do things like `pkg install` and similar with the hosts networking. Preparing "template" jails and stuff.
I got the error message that `iocage chroot` was deprecated and I should use `iocage console`.
Thinking, "hey, they merged the functions" I used `iocage console` when to my great surprise (think POLA) the jail was started ...

Kind regards
Patrick

**Comment by skarekrow** [comment]
Fair enough :) Will implement this

**Comment by jsegaert** [comment]
There's another occurrence where it may auto-start a jail, i.e. when getting a plugin property:
`iocage get -P <property> <jail>`

**Comment by skarekrow** [comment]
@jsegaert Great catch as always, this is addressed in #878 :+1:
