### ISSUE TITLE
Capitalize N when asking for confirmation for destroy command

### ISSUE THREAD

**Issue by penetal** [iocage/iocage#86]
I think its customary to have the default option be the capitalized one when asking y/n questions, since the default is no it should be y/N instead of the current Y/n.

This might also mean that the yes answer shouldn't require the "y" to be capitalized?

**Comment by skarekrow** [comment]
I agree. Committing a change for this shortly.

**Comment by skarekrow** [comment]
Actually turns out there might be a bug, this will take more time then I have currently to look at. Will try to look at it more in the coming days. Maybe a week. Thanks for bringing this up!
