### ISSUE TITLE
Setting host_hostname does not set the hostname in the jail

### ISSUE THREAD

**Issue by hxw** [iocage/iocage#87]
the following command did not set the hostname correctly:
```
iocage iocage clone templateone tag=jail-one host_hostname="jail-one"  boot=on
```
The PROPERTIES section of the nam page implies this this the way to set the jail's hostname

Runing a "get all" shows host_hostname was set correctly but the rc.conf hostname was still the uuid value,  Looking through the script I see that the rc.conf hostname will always be set to uuid on creation and that host_hostname did not appear to be used.

I see that there is another property "hostname" that the jexec uses to set host.hostname..
The  allow_set_hostname parameter defaults to on so the rc.conf value takes precedence over the jexec parameter..
(hope that is clear)

My work around: (set hostname property and disable allow_set_hostname)
```
iocage iocage clone templateone tag=jail-one hostname="jail-one"  allow_set_hostname="0" boot=on
```

I am not sure if the work around is the correct behaviour and just the man page needs changing to reflect this *or* the man page is right and the script should be updating the jail's rc.conf in the create and set commands.

**Comment by hxw** [comment]
This is: iocage-1.5.1 on: 10.1-RELEASE-p10

**Comment by pannon** [comment]
@hxw thanks for reporting this. I think moving forward we should just default to `allow_set_hostname="0"`. That way the hostname is always set to the value controlled by iocage. Additionally if someone has a desire to set the hostname in rc.conf it will be possible by setting `allow_set_hostname="1"` as you stated previously.

Let me know what you think.

Also, starting with version 1.6 we have global defaults too, so in this case you could set a global default with: `iocage set allow_set_hostname=0 default` - this will be applied to all newly created jails.

**Comment by skarekrow** [comment]
Changed in commit 7969377.

**Comment by hxw** [comment]
Thanks for looking at this,  just one question:  will i need to set just hostname or host_hostname or perhaps both?

(Currently I ignore host_hostname)

**Comment by pannon** [comment]
@hxw just `iocage set hostname=foo UUID` and jail restart should be sufficient. For apps to be able to resolve the IP/interface internally in the jail you will still need an IP address record in the jail's `/etc/hosts` file.

**Comment by hxw** [comment]
@pannon thanks, I am confused as to whether I should be using `host_hostname` as the man page says or `hostname` which does work, though the iocage script also sets `host_hostname`.

**Comment by pannon** [comment]
@hxw sorry for the confusion, basically `iocage set hostname=foo` sets the `host_hostname` parameter for the `jail(8)` utility. So when you fire up the jail  `host_hostname` is populated with `foo`, which in turn sets the hostname inside the jail.

As far as I see there are two ways to set hostnames:
1. set  `allow_set_hostname=0` and use `iocage set hostname=foo UUID` - no other action should be required.
2. set  `allow_set_hostname=1` and set the hostname inside the jail's `/etc/rc.conf` `hostname="foo"`
