### ISSUE TITLE
Display version of installed jail on list 

### ISSUE THREAD

**Issue by tstauffe** [iocage/iocage#88]
A feature request if possible, display the version(freebsd-version -u)  on iocage list screen. Listing them means I don't have to remember which ones I've updated. Unless you have a better idea. Thanks.

**Comment by pr1ntf** [comment]
To save real estate in the console, I think this should be a switch, but I'm on board.

**Comment by pannon** [comment]
@tstauffe you should be able to examine this with `iocage show release`

**Comment by tstauffe** [comment]
@pannon `iocage show release` will give me the release version but not the patch level that `freebsd-version` does. If I'm updating 10-15 jails remembering which ones I've updated already becomes very repetitive having to check each one before updating. Maybe I need to find a better way for management.

**Comment by larsengels** [comment]
You can try this, works only with running jails:
```
for j in $(iocage list | awk '{if (NR!=1) {print $NF}}'); do printf "$j: %s\n" $(iocage exec $j freebsd-version -u) ;done
´´´

**Comment by pannon** [comment]
@tstauffe we already have an `iocage exec` sub-command, what if we added support to run exec on all jails - ie. `iocage exec ALL uname -r`?

That way you could examine anything (almost like `salt '*' cmd.run`)

**Comment by pannon** [comment]
@larsengels already beaten me by 1 minute :)

**Comment by tstauffe** [comment]
@pannon `iocage exec <UUID> uname -r` works for a single jail but I get unexpected operator with the ALL argument I'm currently using `iocage list | grep -v UUID | grep -v ' off ' | awk '{print $1}' | xargs -I {} sh -c 'iocage exec {} freebsd-version'` but it's really slow due to not storing the results and executing on each jail this is pretty much the same as @larsengels

**Comment by pannon** [comment]
@tstauffe `ALL` is not supported yet - was just asking whether you would be happy with that option, so we could add it in the next few days.
