### ISSUE TITLE
Error: No such command "start" after "service iocage start"

### ISSUE THREAD

**Issue by saper** [iocage/iocage#890]
Make sure to follow and check these boxes before submitting an issue! Thank you.

Running 12.0-RELEASE

- [X] Supply `iocage --version`

      Version	1.2 BETA

     (git a09857be4f3ef411d0ffd08d4b49fb7267ae7cf8)

- [X] Supply the commands used, along with any steps to recreate it.

      service iocage start

- [X] Provide the output from the command you issued.

````
* [I|O|C] starting jails... 
Usage: iocage [OPTIONS] COMMAND [ARGS]...
Try "iocage --help" for help.

Error: No such command "start".

````     

- [X] Supply what you expected the result or output to be

````
* [I|O|C] starting jails... 
````

- [X] Checked that the problem has not already been fixed on `master` if using
 a stable release.

Running master

Funny enough, `/usr/local/etc/rc.d/iocage start` works as expected, but it fails at boot with the error message above.

**Comment by saper** [comment]
Easier to reproduce:

````
# env -i HOME=/ PATH=/sbin:/bin:/usr/sbin:/usr/bin /usr/local/bin/iocage start --rc
Usage: iocage [OPTIONS] COMMAND [ARGS]...
Try "iocage --help" for help.

Error: No such command "start".
````

also

````
env -i HOME=/ PATH=/sbin:/bin:/usr/sbin:/usr/bin /usr/local/bin/python3.6 /usr/local/bin/iocage start --rc
````
````

**Comment by saper** [comment]
Adding `/usr/local/bin` to the `$PATH` fixes the problem:

````
# env -i HOME=/ PATH=/sbin:/bin:/usr/sbin:/usr/bin:/usr/local/bin /usr/local/bin/python3.6 
Python 3.6.7 (default, Feb  7 2019, 01:15:51) 
[GCC 4.2.1 Compatible FreeBSD Clang 6.0.1 (tags/RELEASE_601/final 335540)] on freebsd12
Type "help", "copyright", "credits" or "license" for more information.
>>> import sys; sys.argv=['/usr/local/bin/iocage', 'start', '--rc']
>>> from iocage_cli import cli; cli()
````

(terminates succesfully)

vs

````
# env -i HOME=/ PATH=/sbin:/bin:/usr/sbin:/usr/bin /usr/local/bin/python3.6
Python 3.6.7 (default, Feb  7 2019, 01:15:51) 
[GCC 4.2.1 Compatible FreeBSD Clang 6.0.1 (tags/RELEASE_601/final 335540)] on freebsd12
Type "help", "copyright", "credits" or "license" for more information.
>>> import sys; sys.argv=['/usr/local/bin/iocage', 'start', '--rc']
>>> from iocage_cli import cli; cli()
Usage: iocage [OPTIONS] COMMAND [ARGS]...
Try "iocage --help" for help.

Error: No such command "start".
````

**Comment by dlangille** [comment]
I just built and installed head. 

```
# env -i HOME=/ PATH=/sbin:/bin:/usr/sbin:/usr/bin:/usr/local/bin /usr/local/bin/python3.6 
Python 3.6.8 (default, Mar 28 2019, 04:22:21) 
[GCC 4.2.1 Compatible FreeBSD Clang 6.0.0 (tags/RELEASE_600/final 326565)] on freebsd11
Type "help", "copyright", "credits" or "license" for more information.
>>> import sys; sys.argv=['/usr/local/bin/iocage', 'start', '--rc']
>>> from iocage_cli import cli; cli()
Usage: iocage [OPTIONS] COMMAND [ARGS]...
Try "iocage --help" for help.

Error: No such command "start".

```

**Comment by dlangille** [comment]
"solution": install git

**Comment by maurizio-emmex** [comment]
> "solution": install git

Thank you dlangille,
`# pkg install git`
works for me.

**Comment by dlangille** [comment]
I'm using git-lite, just because.  Glad it solves it for you too.

**Comment by mike-pt** [comment]
`"service iocage start`still fails but I can see the subcomands not on iocage help (after installing git-lie) 

` /usr/local/bin/iocage start --rc`does work for starting all jails with `boot` but not from the rc.d file

**Comment by drjohnnyfever1** [comment]
I add `export PATH=/usr/local/bin:$PATH` to rc.d/iocage right before `start_cmd="iocage_start"` and it fixes it for me. I don't know if it is considered appropriate to export a PATH var in an rc script.
