### ISSUE TITLE
freebsd-update not found for basejail

### ISSUE THREAD

**Issue by utrenkner** [iocage/iocage#893]
- [x] Supply `iocage --version`: Version 1.1 RELEASE 2019/0
- [x] Supply the commands used, along with any steps to recreate it: ``iocage start wordpress``
- [x] Provide the output from the command you issued: ``freebsd-version could not be found at /iocage/jails/wordpress/root/bin/freebsd-version``
- [x] Supply what you expected the result or output to be: Jail should be started
- [ ] Checked that the problem has not already been fixed on `master` if using
 a stable release: I did not - but I could find neither a related issue, nor a related commit...

The system is a HardenedBSD Server running 11.2. The jail(s) are basejails based on /iocage/releases/11-STABLE/root. As usual, I manually updated this base via ``hbsd-update -n -r /iocage/releases/11-STABLE/root`` (the ``-r`` in hbsd-update is like ``-b`` in freebsd-update...). Trying to start the jails after that, I got the above mentioned message and none of the jails started.

This update procedure has worked for 2+ years. It is the first time I experience this problem.

I was able to solve the problem via a dirty hack: I copied ``/iocage/releases/11-STABLE/root/bin/freebsd-version`` to ``/iocage/jails/wordpress/root/bin/freebsd-version``. It seems as if iocage was trying to check for the existence of this file before the base jails were cloned from the base...

**Comment by sonicaj** [comment]
@utrenkner i believe this issue has been fixed. Can you please confirm in latest master ?

**Comment by DaffyDuke** [comment]
Same problem here. And I had to fix network default interface too as described here : https://redmine.ixsystems.com/issues/81075
