### ISSUE TITLE
--help should work before activate

### ISSUE THREAD

**Issue by okapia** [iocage/iocage#9]
# iocage activate --help
    Creating --help/iocage
    invalid option '-'

There seems to be a lack of error checking there, first that the argument is the name of a ZFS pool and whether the name is valid.
And --help for any other command prints an error about no pool being active for iocage usage. Would be nice if the help could be shown regardless.

**Comment by skarekrow** [comment]
Interesting issue. I agree I wish I could show help and still do the missing dataset check I do. I'll think about this and see if there's another way I can approach it.

**Comment by skarekrow** [comment]
Once I added the skip check for `--help`, this bug disappeared. It's weird it existed as I do check for the pools existence.

Fixed now though!

Thanks for the report :)
