### ISSUE TITLE
Documentation bug: VNET networking with VLANs

### ISSUE THREAD

**Issue by pmhausen** [iocage/iocage#901]
https://iocage.readthedocs.io/en/latest/networking.html#vimage-vnet
> If using VLAN interfaces for the jail host, add the VLAN interface AND parent interface of the VLAN as bridge members.

Sorry, but this is plain wrong. If there are issues that can be "fixed" this way in certain circumstances, please provide an example and I will try my best to help sort it out.

Kind regards,
Patrick

**Comment by nathanjrobertson** [comment]
I've found that having the parent interface as a member of the bridge actually causes the networking not to work on 12.0-RELEASE. It actually makes no sense that the parent interface should be a member of the bridge, and it appears that's the way 12.0 has gone.

My jails hosted on VLANs don't work unless I remove the parent interface from the bridge manually after starting the jail. eg.

> root@HOST:~ # iocage start test2
> root@HOST:~ # ifconfig bridge4 deletem igb0

The interfaces end up looking like:

> root@HOST:~ # ifconfig bridge4
> bridge4: flags=8843<UP,BROADCAST,RUNNING,SIMPLEX,MULTICAST> metric 0 mtu 1500
>         ether XXXX
>         id 00:00:00:00:00:00 priority 32768 hellotime 2 fwddelay 15
>         maxage 20 holdcnt 6 proto rstp maxaddr 2000 timeout 1200
>         root id 00:00:00:00:00:00 priority 32768 ifcost 0 port 0
>         member: vnet0.7 flags=143<LEARNING,DISCOVER,AUTOEDGE,AUTOPTP>
>                 ifmaxaddr 0 port 6 priority 128 path cost 2000
>         member: vlan4 flags=143<LEARNING,DISCOVER,AUTOEDGE,AUTOPTP>
>                 ifmaxaddr 0 port 4 priority 128 path cost 20000
>         groups: bridge
>         nd6 options=9<PERFORMNUD,IFDISABLED>
> root@dk-hyp3:~ #`

Before the delete, no traffic gets through. After, everything works well. To stop iocage from creating that extra parent interface, I added the "vnet_default_interface=none" parameter.

**Comment by dgeo** [comment]
Le 12 avril 2019 03:28:37 GMT+02:00, nathanjrobertson <notifications@github.com> a écrit :
>I've found that having the parent interface as a member of the bridge
>actually causes the networking not to work on 12.0-RELEASE. It actually
>makes no sense that the parent interface should be a member of the
>bridge, and it appears that's the way 12.0 has gone.
>
>My jails hosted on VLANs don't work unless I remove the parent
>interface from the bridge manually after starting the jail. eg.
>
>`# iocage start test2
># ifconfig bridge4 deletem igb0`
>
>The interfaces end up looking like:
>
>`root@HOST:~ # ifconfig bridge4
>bridge4: flags=8843<UP,BROADCAST,RUNNING,SIMPLEX,MULTICAST> metric 0
>mtu 1500
>        ether XXXX
>        id 00:00:00:00:00:00 priority 32768 hellotime 2 fwddelay 15
>        maxage 20 holdcnt 6 proto rstp maxaddr 2000 timeout 1200
>        root id 00:00:00:00:00:00 priority 32768 ifcost 0 port 0
>        member: vnet0.7 flags=143<LEARNING,DISCOVER,AUTOEDGE,AUTOPTP>
>                ifmaxaddr 0 port 6 priority 128 path cost 2000
>        member: vlan4 flags=143<LEARNING,DISCOVER,AUTOEDGE,AUTOPTP>
>                ifmaxaddr 0 port 4 priority 128 path cost 20000
>        groups: bridge
>        nd6 options=9<PERFORMNUD,IFDISABLED>
>root@dk-hyp3:~ #`
>
>Before the delete, no traffic gets through. After, everything works
>well.

I never used this trick and have dozen jails working with vnet
-- 
geoffroy desvernay (mobile)
