### ISSUE TITLE
[FEATURE] Please report DHCP IP, not just DHCP in iocage list table.

### ISSUE THREAD

**Issue by jaxjexjox** [iocage/iocage#908]
Make sure to follow and check these boxes before submitting an issue! Thank you.

As seen here:
https://redmine.ixsystems.com/issues/71038#note-14

- [x] Supply `iocage --version`
FreeNAS 11.2-U3
- [x] Supply the commands used, along with any steps to recreate it.
iocage list
- [x] Provide the output from the command you issued.
Table of jails
- [x] Supply what you expected the result or output to be
Table of jails with DHCP entries having the IP address included within the table
- [x] Checked that the problem has not already been fixed on `master` if using
 a stable release.
I am unable to do this, due to being a simpleton, my apologies.

**Comment by skarekrow** [comment]
This is cut short to keep the list at a sane number of characters for shorter terminals. The -l flag should satisfy you ;)
