### ISSUE TITLE
Dual stack jails don't work on vnet

### ISSUE THREAD

**Issue by clinta** [iocage/iocage#93]
Tested on master commit 3229b930a6. V6 and V4 both work, but when combined, only v4 works.

```
[root@server] /usr/home/clint/iocage# iocage create -r 11.0-RELEASE tag=v6 vnet=on interfaces="vnet0:bridge0" ip6_addr="vnet0|2601:XXXX:XXXX:XXXX::36/64"
 45792ef5-e4c2-4e1c-b22d-c6dfcb41064e (v6) successfully created!
[root@server] /usr/home/clint/iocage# iocage start v6
 * Starting 45792ef5-e4c2-4e1c-b22d-c6dfcb41064e (v6)
   + Started OK
   + Starting services OK


[root@server] /usr/home/clint/iocage# ping6 -c 1 2601:XXXX:XXXX:XXXX::36
PING6(56=40+8+8 bytes) 2601:XXXX:XXXX:XXXX::20 --> 2601:XXXX:XXXX:XXXX::36
16 bytes from 2601:XXXX:XXXX:XXXX::36, icmp_seq=0 hlim=64 time=0.120 ms

--- 2601:XXXX:XXXX:XXXX::36 ping6 statistics ---
1 packets transmitted, 1 packets received, 0.0% packet loss
round-trip min/avg/max/std-dev = 0.120/0.120/0.120/0.000 ms


[root@server] /usr/home/clint/iocage# iocage create -r 11.0-RELEASE tag=dual vnet=on interfaces="vnet0:bridge0" ip6_addr="vnet0|2601:XXXX:XXXX:XXXX::37/64" ip4_addr="vnet0|192.168.10.37/24" 
 55f4fb53-aac1-405f-a5d9-dfc80fe2cb5d (dual) successfully created!


[root@server] /usr/home/clint/iocage# iocage start dual
 * Starting 55f4fb53-aac1-405f-a5d9-dfc80fe2cb5d (dual)
   + Started OK
   + Starting services OK


[root@server] /usr/home/clint/iocage# ping -c 1 192.168.10.37
PING 192.168.10.37 (192.168.10.37): 56 data bytes
64 bytes from 192.168.10.37: icmp_seq=0 ttl=64 time=0.064 ms

--- 192.168.10.37 ping statistics ---
1 packets transmitted, 1 packets received, 0.0% packet loss
round-trip min/avg/max/stddev = 0.064/0.064/0.064/0.000 ms


[root@server] /usr/home/clint/iocage# ping6 -c 1 2601:XXXX:XXXX:XXXX::37
PING6(56=40+8+8 bytes) 2601:XXXX:XXXX:XXXX::20 --> 2601:XXXX:XXXX:XXXX::37

--- 2601:XXXX:XXXX:XXXX::37 ping6 statistics ---
1 packets transmitted, 0 packets received, 100.0% packet loss
```

**Comment by clinta** [comment]
The ipv6 address is never added to the dual jail.

```
[root@server] /usr/home/clint/iocage# iocage exec dual ifconfig
 lo0: flags=8049<UP,LOOPBACK,RUNNING,MULTICAST> metric 0 mtu 16384
	options=600003<RXCSUM,TXCSUM,RXCSUM_IPV6,TXCSUM_IPV6>
	inet6 ::1 prefixlen 128 
	inet6 fe80::1%lo0 prefixlen 64 scopeid 0x1 
	inet 127.0.0.1 netmask 0xff000000 
	nd6 options=21<PERFORMNUD,AUTO_LINKLOCAL>
	groups: lo 
vnet0: flags=8843<UP,BROADCAST,RUNNING,SIMPLEX,MULTICAST> metric 0 mtu 1500
	options=8<VLAN_MTU>
	ether 02:ff:60:00:00:05
	inet6 fe80::ff:60ff:fe00:5%vnet0 prefixlen 64 scopeid 0x2 
	inet 192.168.10.37 netmask 0xffffff00 broadcast 192.168.10.255 
	nd6 options=21<PERFORMNUD,AUTO_LINKLOCAL>
	media: Ethernet 10Gbase-T (10Gbase-T <full-duplex>)
	status: active
	groups: epair 
```

**Comment by skarekrow** [comment]
Are you able to replicate this on shared IP jails as well? I'll try to investigate it this week, but from memory the code should be adding *both*. Perhaps I missed something.

**Comment by clinta** [comment]
Nope, this does not happen on shared IP jails. Both addresses are added just fine without vnet.

**Comment by skarekrow** [comment]
Alright, appreciate the testing!

Here's to hoping it's a dumb one line fix and not something deeper.

**Comment by clinta** [comment]
It looks like the problem is [here](https://github.com/iocage/iocage/blob/44c2471a899ad79adc746c22d6d983c8b4a9c6c3/iocage/lib/ioc_start.py#L373)

That whole try block runs successfully to set one ip, but when it is called again from this [loop](https://github.com/iocage/iocage/blob/44c2471a899ad79adc746c22d6d983c8b4a9c6c3/iocage/lib/ioc_start.py#L327), it throws an error and is caught, and the commands below which add the second IP are never run.

**Comment by skarekrow** [comment]
Yeah that's where I was going to look, the issue being the error isn't actually used once it's caught. I don't have a VNET instance running, otherwise I'd quickly dive in and fix this (Since VNET takes my box every couple starts, it's hard to test with) so it may be a bit.

My suspicion is [here](https://github.com/iocage/iocage/blob/44c2471a899ad79adc746c22d6d983c8b4a9c6c3/iocage/lib/ioc_start.py#L388) as I'm willing to bet the bridge issue is still rearing it's head in some form.

**Comment by bravesirrobin81** [comment]
I think I've got a partial fix for this locally. Only supports one IP4 + one IP6 address per interface. Also needs tests. You could try master from here: https://github.com/bravesirrobin81/iocage

I should have some time later this week to finish this up. 

Edit: just noticed that #94 is  a PR for basically the same thing.
