### ISSUE TITLE
iocage promote command does not work

### ISSUE THREAD

**Issue by Oriann** [iocage/iocage#939]
Using iocage in FreeNAS ver. 11.2-U4
-problem: iocage promote command does not work
-steps to recreate issue:
`iocage clone jail1 --name jail-test`
`iocage promote jail-test`
output: Error: No such command "promote"

In advanced docs this is written as a function that may work.
Is there still problem with it or function isnt fully implemented ?
https://iocage.readthedocs.io/en/latest/advanced-use.html

**Comment by skarekrow** [comment]
There’s is a warning on that very page explaining that ;)

It is not added yet.

**Comment by Oriann** [comment]
Ok thanks for answer
I look forward to implementation :)

**Comment by denigmus** [comment]
Is is still not implemented or just missed in port's version of iocage? and what will be workaround?
