### ISSUE TITLE
Iocage needs .json extension on pkg files for create command

### ISSUE THREAD

**Issue by darkfiberiru** [iocage/iocage#949]
- [ x] Supply `iocage --version`
Version	FreeNAS 11.2-U4
- [x] Supply the commands used, along with any steps to recreate it.
iocage create -n sharknet${i} -r 11.2-RELEASE -p /tmp/sharknet-pkgs vnet=on \
    devfs_ruleset=2  ip4_addr="vnet0|${extip},vnet1|${intip}" interfaces="vnet0:bridge255,vnet1:bridge${i}"  \
	defaultrouter="${extdefault}" vnet_default_interface="${extinterface}"
- [ ] Provide the output from the command you issued.
- [x] Supply what you expected the result or output to be
Pkg's are added to jail. No need to add .json to file. 
Alternatively document this more clearly.
- [x] Checked that the problem has not already been fixed on `master` if using
 a stable release.
@skarekrow Told me so :D

**Comment by skarekrow** [comment]
:D
