### ISSUE TITLE
Poststop

### ISSUE THREAD

**Issue by kairu0** [iocage/iocage#95]
iocage 0.9.5_1

> # TODO: Prestop findscript

I would like to use Prestop functionality but found this in the source code. Do you have any expectation of completing this code soon?

**Comment by skarekrow** [comment]
Yeah. I expect to have it done in a month or so. Which I hope to be completed by version 1.0.

**Comment by newmikeorder** [comment]
I notice the subject is Poststop, but the message is Prestop.  Will both be covered in the enhancement?  I used poststop a lot in the old shell iocage, because I wanted the jail stopped before running certain commands.  Thank you.

**Comment by skarekrow** [comment]
Yeah they're going to use the same base mechanism. So both will be added.

**Comment by skarekrow** [comment]
All done guys, please test 👍

**Comment by newmikeorder** [comment]
So I finally got a free cycles to test and installed the latest version from ports Version 0.9.7 2017/03/08.
And the post stop does not seem to be working.  If I run the stop script manually it does.  Even if I execute manually an iocage get exec_poststop <jailname> it returns the right script.

Should this be working in this version or do I need to do the git direct method of updating?

**Comment by skarekrow** [comment]
Yes you require the git repo. None of the fixes are in a release.
