### ISSUE TITLE
tests directory

### ISSUE THREAD

**Issue by dbaio** [iocage/iocage#962]
Hi.

Please, remove the `tests` directory of the distribution, it conflicts with other packages.

Thank you!

**Comment by skarekrow** [comment]
Tests should already be excluded in master, what conflicts are you noting?

**Comment by dbaio** [comment]
Hum, great that this change is already in the master, I didn't check it.
I noticed this issue in `iocage-1.1`, the current version in FreeBSD ports, which was released before this change.

**Comment by skarekrow** [comment]
👍 Thanks for reporting!
