### ISSUE TITLE
Failure in 'iocage upgrade ALL': "Host: 11.2 is not greater than target: 12.0"

### ISSUE THREAD

**Issue by adam12b1** [iocage/iocage#971]
Running iocage v1.1 release 2019/01.

We're just making the journey from ezjail (without even ZFS!) to iocage, and are mostly very impressed, but having trouble figuring out how to achieve the same kind of basejail functionality we're accustomed to. The docs are, ahem, extremely minimalist in this area, and no amount of internetting has turned up the answers.

It really comes down to this one tantalizing sentence in the [main doc](https://iocage.readthedocs.io/en/latest/jailtypes.html#basejail): 

> They are ideal for environments where immediate patching or upgrading of multiple jails is required.

That is what we require (we run hundreds of jails on a single machine and need to update or upgrade them all at once), but it's not what we see iocage doing - especially with upgrades. 

With patch or minor-level updates, since all the jails are nullfs mounting the same X-RELEASE datasets, they would in fact all see the new versions show up immediately. But with upgrades, there's a new X-RELEASE dataset created, and only by running `iocage upgrade JAIL` for every single basejail would you see their mounts in `fstab` (or their "release" line in `config.json`) updated to the new version. (In fact `config.json` also would need editing for all jails even with updates, suggesting you'd still need to run an `iocage update JAIL` for every basejail.) Both the `update` and `upgrade` commands require a UUID or jailname argument, which seems incompatible with the idea of updating/upgrading them all at once.

We must be missing something here, but cannot figure it out. Any help appreciated!

**Comment by skarekrow** [comment]
You’re close! With upgrades basejails get moved to the new release via nullfs mounts, that release is updated to the latest patch level, and then etcupdate is ran to bring configuration forward. 

So upgrade ALL or update ALL (assuming all are basejails ofc) should give you the bulk methods you’re looking for.

**Comment by adam12b1** [comment]
Ah, jailname = ALL! Of course. Already knew that for start/stop/restart commands, but hadn't thought of trying it with the update/upgrade commands. Thanks for the quick response.

And now tested successfully with a simple `iocage update ALL`... but we've seen some strange behavior with the upgrade command, have to test some more tomorrow.

**Comment by sonicaj** [comment]
@adam12b1 please feel free to post here the strange behaviour you have been seeing and we'll do our best to walk you through it. Thank you!

**Comment by adam12b1** [comment]
Okay, here's what we're seeing with `iocage upgrade ALL`:
```
host# freebsd-version
12.0-RELEASE-p6
host# iocage upgrade ALL -r 12.0-RELEASE

jail1 successfully upgraded from 11.2-RELEASE-p10 to 12.0-RELEASE-p6!
Please reboot the jail and inspect.
Remove the snapshot: ioc_upgrade_2019-06-28 if everything is OK

Host: 11.2 is not greater than target: 12.0
This is unsupported.
host#
```
It upgrades one of the basejails, but then fails with this error that we've seen before when we attempted to upgrade iocage to a more recent OS than the host - but clearly in this case the error is somehow erroneous itself.

We then find that we _can_ re-run the upgrade command with each jail's name in turn, and they run just fine, and all seems well in the end. So we could trivially script a loop ourselves, but the problem is time: it's taking nearly 2 minutes for each run on one jail, which means hours for the whole set.

Is there something that can get fixed here so we can get the total jails upgrade time down to approximately the same as upgrading one system? Or are we looking for something beyond what iocage basejails are even intended to provide?

**Comment by adam12b1** [comment]
Any chance of a fix on the `iocage upgrade ALL` command upgrading only one basejail and then exiting with `Host: 11.2 is not greater than target: 12.0` (when the host OS is in fact at 12.0)?

**Comment by adam12b1** [comment]
Update on this issue: `iocage upgrade ALL` fails in the same way regardless of whether the jails in question are basejails or normal standalone jails. It upgrades one jail, then fails on the rest:
```
# iocage upgrade -r 12.0-RELEASE ALL
[...]
test3 successfully upgraded from 11.2-RELEASE-p12 to 12.0-RELEASE-p9!

Host: 11.2 is not greater than target: 12.0
This is unsupported.
```

**Comment by java4devgmail** [comment]
Hello

I see that there is still no solution to this problem.
I am getting thew same error as well.

Kind Regards
Nikolas

**Comment by adam12b1** [comment]
FWIW I've just edited the subject on this issue, since at this point it's really come down to this one narrow problem: `iocage upgrade ALL` fails with the incorrect error that the host's OS version is not greater than the target's. (But `iocage update ALL` works fine.)

Hoping somebody's able to take a look at that sometime soon... thanks!

**Comment by adam12b1** [comment]
Reporting back here with good news: This bug was apparently fixed (sorry I haven't quite done the research), as current version of iocage shows no sign of it. We can now run both `iocage update ALL` and `iocage upgrade ALL` successfully, no mysterious errors. Thank you! Closing issue.
