### ISSUE TITLE
Import error

### ISSUE THREAD

**Issue by pos42** [iocage/iocage#976]
Hi

16:26:27 huey:/usr/ports # iocage -v
Version	1.1 RELEASE 2019/01

16:19:49 huey:/usr/ports # iocage import WEB                   
Multiple images found for WEB:
  WEB_2019-06-07.zip
  WEB_2019-06-29.zip
16:20:01 huey:/usr/ports # iocage import WEB WEB_2019-06-29
Usage: iocage import [OPTIONS] JAIL
Try "iocage import --help" for help.

Error: Got unexpected extra argument (WEB_2019-06-29)
16:20:12 huey:/usr/ports # iocage import WEB WEB_2019-06-29.zip
Usage: iocage import [OPTIONS] JAIL
Try "iocage import --help" for help.

Error: Got unexpected extra argument (WEB_2019-06-29.zip)

Only if I remove one image from the filesystem it works by using...

16:23:01 huey:/usr/ports # iocage import WEB                                   
Importing dataset: WEB
Importing dataset: WEB/root

Imported: WEB
16:24:45 huey:/usr/ports # 

Is there a bug of feature that I cannot specify what image to import?

Tnx
/P

**Comment by sonicaj** [comment]
Hello @pos42, so first `iocage import` expects one jail argument only, you were supplying 2. Secondly, iocage performs a greedy match which might seem confusing but is for the ease of the end user. Say i have an image named `hello123456789`, so if i type only `hello`, it will still work. Now this raises a potential issue when multiple images are found with the name provided as in your case. You should use the complete jail name and it will work just fine.

**Comment by pos42** [comment]
?

The jail name is "WEB".  No more. No less. 

You say: 
>  Now this raises a potential issue when multiple images are found with the name provided as in your case.You should use the complete jail name and it will work just fine.

You actually mean I should use the complete image name? NOT the jail name... Right?

you mean I in the above case could write:
 iocage import WEB_2019-06-29
As this makes the image unique?

**Comment by sonicaj** [comment]
Actually i think i know what went wrong here. So you had 2 compressed files all starting with `WEB` which i assume is your jail name. Now if multiple copies exist, we can't on our own determine which image you want to use for importing, so typing just `WEB` is not enough in this case. In this case you have to pass on the complete image name ( without .zip ) and your jail should import successfully.

**Comment by pos42** [comment]
>  So you had 2 compressed files all starting with WEB which i assume is your jail name.
That is correct.

I get it. The one thing I have not tested :) I think that the man page could be a little bit clearer. Especially if you have more than one image to chose from, which I guess it not that unusual. 

PS
I could of course have read the source before posting :)

/Peo

**Comment by pos42** [comment]
B t w...

Is it normal that every import seems to generate a new extra devfs?

If I destroy a jail (iocage destroy --recursive WEB) and re-import the old export, it seems an extra devfs i created for every import.

```
11:42:15 huey:~ # df -h|grep WEB
devfs                                      1.0K    1.0K      0B   100%    /iocage/jails/WEB/root/dev
devfs                                      1.0K    1.0K      0B   100%    /iocage/jails/WEB/root/dev
devfs                                      1.0K    1.0K      0B   100%    /iocage/jails/WEB/root/dev
devfs                                      1.0K    1.0K      0B   100%    /iocage/jails/WEB/root/dev
zroot/iocage/jails/WEB                     4.2G     92K    4.2G     0%    /iocage/jails/WEB
zroot/iocage/jails/WEB/root                4.9G    661M    4.2G    13%    /iocage/jails/WEB/root
devfs                                      1.0K    1.0K      0B   100%    /iocage/jails/WEB/root/dev
fdescfs                                    1.0K    1.0K      0B   100%    /iocage/jails/WEB/root/dev/fd
11:42:19 huey:~ # 
```
