### ISSUE TITLE
How to use basejails?

### ISSUE THREAD

**Issue by Nachtschatten** [iocage/iocage#978]
- [x] Supply `iocage --version`
`Version 1.1 RELEASE 2019/01`

I'm just starting out with jails and iocage. I wanted to try out what you can do with basejails. E.g. can I keep an up-to-date ports tree in a central place and have "child jails" use that? Can I maybe even install and update packages in a central place?

Reading the documentation, I created a basejail with:

`$ iocage create -n base -r LATEST -b`

but then what? How do I create a child jail that inherits from `base`? This doesn't work:

```bash
$ iocage create -n child -r base
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/iocage_cli/create.py", line 128, in cli
    ioc_common.check_release_newer(release)
  File "/usr/local/lib/python3.6/site-packages/iocage_lib/ioc_common.py", line 717, in check_release_newer
    r_float = float(str(release).rsplit("-")[0])
ValueError: could not convert string to float: 'base'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/bin/iocage", line 10, in <module>
    sys.exit(cli())
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 717, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 1137, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/iocage_cli/create.py", line 134, in cli
    _release = ioc_common.get_jail_freebsd_version(path, release)
  File "/usr/local/lib/python3.6/site-packages/iocage_lib/ioc_common.py", line 898, in get_jail_freebsd_version
    with open(f'{path}/bin/freebsd-version', 'r') as r:
FileNotFoundError: [Errno 2] No such file or directory: '/zroot/iocage/releases/base/root/bin/freebsd-version'
```

Neither does

```bash
$ iocage create -n child -b base
Must supply either --template (-t) or --release (-r)!
```

Nor does

```bash
$ iocage create -n child -t base
Template: base not found!
```

Trying to provide `base` as an argument doesn't seem the way to do it. Why not? My next clue from the documentation:
> Basejails in iocage are mounts in a jail fstab that are mounted at jail startup.

I originally thought this was some implementation detail I don't need to care about. But perhaps I need to create a "child jail" without reference to `base` and add _something_ to the child's fstab. What exactly, though? Does iocage provide some automatisms to "connect" `base` and child jail, or will I have to figure out the correct paths for fstab myself?

I'm lost at this point. Please, can somebody shed light on this? Thank you in advance.

**Comment by jhfoo** [comment]
Did you read the [docs](https://iocage.readthedocs.io/en/latest/jailtypes.html?highlight=template#template) to create basejail as a template?

Just tried templates: works as expected.

Hint:
~~~
iocage set template=yes basejail
iocage create -t basejail -n child
~~~

**Comment by Nachtschatten** [comment]
Thanks, I'll play around with templates. And sorry for the late reply.
Yes, I read that page. Maybe I misunderstood. This is what I gathered from the description:

- A basejail shares resources with its children. If I install new software in the basejail, it's available in its children.
- A template doesn't share resources, each copy is independent. If I install new software in the original template, existing copies aren't affected. New ones are, though.

I'm somewhat confused. Is my understanding correct? Why would I need to mark a basejail as template explicitely as you suggested? If that's required for basejails to work, why isn't that set automatically?

**Comment by skarekrow** [comment]
Your understanding is correct. You should be able to do `iocage create -n name -r BASE` IIRC

**Comment by jhfoo** [comment]
This sentence highlights a unique feature of base jails quite well: They are ideal for environments where immediate patching or upgrading of multiple jails is required. ([source](https://iocage.readthedocs.io/en/latest/jailtypes.html)).

**Comment by Nachtschatten** [comment]
@jhfoo yes, that's exactly what I want. However, you suggested creating my basejail as template.

I tried that. As expected, updating/adding packages in the basejail has no effect on an already created childjail. This is not what I want, so I'm puzzled why you suggested it.

**Comment by Nachtschatten** [comment]
@skarekrow cool! However, that command is _not_ working. I get the same error as in my original posting. I retraced my original steps like this:

```
$ uname -v
FreeBSD 12.1-RELEASE-p3 GENERIC
$ iocage --version
Version 1.2
$ iocage create -n basejail -r LATEST -b
basejail successfully created!
$ iocage create -n childjail -r basejail
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/iocage_cli/create.py", line 167, in cli
    ioc_common.check_release_newer(release)
  File "/usr/local/lib/python3.7/site-packages/iocage_lib/ioc_common.py", line 722, in check_release_newer
    r_float = float(str(release).rsplit("-")[0])
ValueError: could not convert string to float: 'basejail'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/bin/iocage", line 10, in <module>
    sys.exit(cli())
  File "/usr/local/lib/python3.7/site-packages/click/core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/click/core.py", line 717, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.7/site-packages/click/core.py", line 1137, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.7/site-packages/click/core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.7/site-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/iocage_cli/create.py", line 173, in cli
    _release = ioc_common.get_jail_freebsd_version(path, release)
  File "/usr/local/lib/python3.7/site-packages/iocage_lib/ioc_common.py", line 928, in get_jail_freebsd_version
    f'{path}/bin/freebsd-version', mode='r', encoding='utf-8'
FileNotFoundError: [Errno 2] No such file or directory: '/zroot/iocage/releases/basejail/root/bin/freebsd-version'
```

As I understand that trace, iocage tries to interpret the _-r basejail_ argument as version number (which makes sense, it's the release version parameter after all), and doesn't interpret it as name of an existing jail.
I don't think the other options of _iocage create_ make sense here, so I'm still lost on how to create a child jail.

**Comment by skarekrow** [comment]
Sorry @Nachtschatten I should have been more clear. @jhfoo has this correct. You create a base from a RELEASE (as you surmised by the exception) or a template. In this case a basejail you can see as the "client" and the RELEASE/template as the "server".

So if you wanted to use a custom jail that all inherit from, you would create a template from a jail you wished to be the base for everything and then create basejails from that template. Basejails themselves have very little unique data and instead rely on nullfs mounts from their source. In this case, a template or RELEASE.

**Comment by Nachtschatten** [comment]
@skarekrow oof, thanks. So _base_-jails don't actually serve as _base_ for jails but as _derived_ ones. I know naming is one of the hardest problems in computer science, but how did the name end up that backwards?
That aside, I'm admittedly a newbie to FreeBSD and need to learn more. And now the part "basejails ... are mounts in a jail fstab" starts making sense. Still, I think this technical description doesn't express the _intent_ very well. OTOH...

> In this case a basejail you can see as the "client" and the RELEASE/template as the "server".

... was eye-opening. I can't thank you enough. May I suggest that you add it to the documentation? Maybe even use a more fitting name at a later time, when backwards-compatibility is not an issue?

I do have one more question about basejail usage, though. The docs explain the jail types and [how to alter templates](https://iocage.readthedocs.io/en/latest/templates.html#using-templates). I'm still struggling with the "final step", how to apply changes to the template ("server") after the fact.

Let's say I created a template ("iocage create -n originaljail -r LATEST" + "iocage set template=yes originaljail") and derived a basejail from it ("iocage create -n derivedjail -t originaljail -b").

Then I discover the fish shell and like it so much that I want it in all my jails. Maybe I can install it in _originaljail_ once, and all other jails (including _derivedjail_) have it.

I've tried converting _originaljail_ back to a regular jail (_set template=no_), installing fish, and converting it to a template again. After that, fish still wasn't available in _derivedjail_.

But [the docs](https://iocage.readthedocs.io/en/latest/templates.html#using-templates) tell me: Since there is _derivedjail_ based on template _originaljail_, I should have created a new template from the existing one. And the docs end there. In other words, fish won't be available in _derivedjail_ because its template is unaltered. What do I need to do next? Can I point _derivedjail_ to the altered template, maybe using _iocage fstab_?

**Comment by skarekrow** [comment]
Naming is hard, yes :D however these is term makes sense I think if you look at it a bit differently. 

Think of it as a *shared*base jail. They all share a common "base" with their few unique features layered on top. As for how you're creating them, you're doing everything right! `/usr/local/bin` isn't shared by default, so yes you would use `iocage fstab -e` or `iocage fstab -a` to add `/usr/local/bin`to your new basejail pointing to the template. It will be the same format as the rest, so it should be very simple to do.

Good luck 👍

**Comment by java4devgmail** [comment]
Hello
I read this thread and the documentation but I dont understand how to create a list of jails that can all be updated by updating the base jail.
What are the commands to execute?
Say that I want to create jail1 jail2 jail3
`iocage create -b -r 14.0-RELEASE --name jail-base boot=on jail_zfs=on  notes="base jail for all jails" `
then what?
After  reading the thread above, making the jail-base as template and creating all the jails from there is not the solution as the user [Nachtschatten](https://github.com/Nachtschatten) mentions so how do we create the children jails?
and after I create the jails how do we update them all . Do we only update the jail-base?

Kind Regards
Nikolas
