### ISSUE TITLE
iocage set exec_fib not actually changing the jails fib 

### ISSUE THREAD

**Issue by sazaro** [iocage/iocage#98]
Iocage Version	0.9.5 2017/02/15
FreeBSD version 11.0-p8
Iocage jails versions FreeBSD 11.0-RELEASE-p8

I am making a jail with the intention if putting this jail on fib 1. I am using the command 
# iocage set exec_fib=1 myjail
Property: exec_fib has been updated to 1

I verified that there was no other fib settings and this was correct using 
# iocage get all myjail | grep fib
exec_fib:1

When I enter the jail I am not on the correct fib as I can verify checking with sysctl
# sysctl -a | grep net.my_fib
net.my_fibnum: 0

I should instead see that it is on fib 1. 

My results are the same no matter whether I restart the jail or manually stop/start it and re-enter. 
In the deprecated version of iocage, setting the fib number indeed worked. I am trying to migrate my jails to the new iocage and the fib features are not working.

**Comment by skarekrow** [comment]
That is because they are not in yet :)

**Comment by sazaro** [comment]
Do you know when it is planned to be added? The port for sysutils/iocage says it is scheduled to be removed on or after 2017-04-01. Is there any alternative way to make the jail run in another fib while still using py27-iocage?

Cheers

**Comment by skarekrow** [comment]
I'll try to get it in today, but no promises :D

You can try `setfib FIB iocage foo bar baz` and see if that works, but I don't believe it will. 

EDIT: Busy day, won't be this week. Should be fairly trivial to add, so I'll look into it next week or so. Will be done before `1.0`.

**Comment by sazaro** [comment]
Thanks! :)

**Comment by skarekrow** [comment]
Alrigth @sazaro, all done. Test away and lemme know 👍
