### ISSUE TITLE
iocage snapremove - cannot execute when jails exist with common prefix 

### ISSUE THREAD

**Issue by sahlawat** [iocage/iocage#982]
root@nas /mnt/data/a/jails-maint # iocage --version
Version	FreeNAS 11.2-U4
root@nas /mnt/data/a/jails-maint # iocage snaplist ldap
+---------------------------------+-----------------------+-------+-------+
|              NAME               |        CREATED        | RSIZE | USED  |
+=================================+=======================+=======+=======+
| ioc_update_11.2-RELEASE-p2      | Thu Jul  4 23:39 2019 | 140K  | 81.4K |
+---------------------------------+-----------------------+-------+-------+
| ioc_update_11.2-RELEASE-p2/root | Thu Jul  4 23:39 2019 | 1.32G | 9.60M |
+---------------------------------+-----------------------+-------+-------+
root@nas /mnt/data/a/jails-maint # iocage snaplist ldap-mgr
+---------------------------------+-----------------------+-------+-------+
|              NAME               |        CREATED        | RSIZE | USED  |
+=================================+=======================+=======+=======+
| ioc_update_11.2-RELEASE-p2      | Thu Jul  4 23:40 2019 | 140K  | 0     |
+---------------------------------+-----------------------+-------+-------+
| ioc_update_11.2-RELEASE-p2/root | Thu Jul  4 23:40 2019 | 1.50G | 9.56M |
+---------------------------------+-----------------------+-------+-------+
root@nas /mnt/data/a/jails-maint # iocage snapremove -n ALL ldap
Multiple jails found for ldap:
  ldap (/mnt/iocage/jails/ldap)
  ldap-mgr (/mnt/iocage/jails/ldap-mgr)

similar to https://github.com/iocage/iocage/issues/419

workaround is to use "zfs destroy" to delete the snapshots

Make sure to follow and check these boxes before submitting an issue! Thank you.

- [X] Supply `iocage --version`
- [X] Supply the commands used, along with any steps to recreate it.
- [X] Provide the output from the command you issued.
- [X] Supply what you expected the result or output to be
- [X] Checked that the problem has not already been fixed on `master` if using
 a stable release.

**Comment by sonicaj** [comment]
@sahlawat for destroying a snapshot, you have to specify the snapshot name. `ALL` doesn't work in this case. Now there are two jails `ldap` and `ldap-mgr`, when you specify to destroy any snapshot for a jail, it is understandable iocage will be confused which jail are you referring to. Now this is a bug that `ldap` is a complete name which iocage should recognize and it does in latest `master`.
I would strongly advise you to update your machine to latest FN version. Closing this issue as it doesn't exist in master, if you face this in latest FN version, please leave a comment here or open a new issue. Thank you!
