### ISSUE TITLE
iocage list -l : does not show the new RELEASE patch information after jail is updated

### ISSUE THREAD

**Issue by sahlawat** [iocage/iocage#983]
root@nas /mnt/data/a/jails-maint # iocage --version
Version	FreeNAS 11.2-U4

run "iocage list -l" and observe the RELEASE version
root@nas /mnt/data/a/jails-maint # iocage list -l
+-----+-------------+------+-------+------+-----------------+-----------------------+-------------------------------+----------+
| JID |    NAME     | BOOT | STATE | TYPE |     RELEASE     |          IP4          |              IP6              | TEMPLATE |
+=====+=============+======+=======+======+=================+=======================+===============================+==========+
| 76  | ldap        | on   | up    | jail | 11.2-RELEASE-p2 | vnet0|192.168.0.13/24 | vnet0|2603:xxxx:e1::13/64 | -        |
+-----+-------------+------+-------+------+-----------------+-----------------------+-------------------------------+----------+
| 88  | ldap-mgr    | on   | up    | jail | 11.2-RELEASE-p2 | vnet0|192.168.0.14/24 | vnet0|2603:xxxx:e1::14/64 | -        |

perform jail updates:
iocage update ldap
iocage update ldap-mgr

run "iocage list -l" and the RELEASE version is still the previous version. Even after multiple updates the RELEASE version shows the RELEASE version when the jail was created.

"iocage update" command also uses this field to create its snapshots and we end up with incorrectly named snapshots.

running iocage fetch and then creating a new jail correctly changes the RELEASE version information for that jail in the iocage list -l output

Make sure to follow and check these boxes before submitting an issue! Thank you.

- [X] Supply `iocage --version`
- [X] Supply the commands used, along with any steps to recreate it.
- [X] Provide the output from the command you issued.
- [X] Supply what you expected the result or output to be
- [X] Checked that the problem has not already been fixed on `master` if using
 a stable release.

**Comment by sonicaj** [comment]
@sahlawat thank you for reporting this. We have introduced some changes recently which would hopefully make sure that this doesn't happen in latest master. I noticed you are on FreeNAS. Can you please create a ticket on Jira from there and attach a debug ( this is a must please as i require insight into the jails/host etc. It can be easily created by going to system->advanced->save debug ). I'll make sure that this has been fixed and is no longer an issue. Closing this here in favor of the Jira ticket.
Cheers !
