### ISSUE TITLE
upgrade --release generates huge number of manual merges

### ISSUE THREAD

**Issue by dlangille** [iocage/iocage#993]
- py36-iocage-devel-1.0.0.20190616,1
- [ ] Supply the commands used, along with any steps to recreate it.
- [dan@zuul:~] $ time sudo iocage upgrade --release 12.0-RELEASE beta.bsdcan.org

This is upgrading from 11.2 to 12.0.

There was a large number of prompts like this:

```
The following file could not be merged automatically: /etc/defaults/periodic.conf
```

The frustrating part is it's mostly FreeBSD $Id$ values such as this:

```
<<<<<<< current version
# $FreeBSD: releng/10.2/etc/defaults/periodic.conf 282243 2015-04-29 18:57:19Z jhb $
=======
# $FreeBSD: releng/12.0/usr.sbin/periodic/periodic.conf 337648 2018-08-11 17:11:08Z brd $
>>>>>>> 12.0-RELEASE
#
```

This didn't happen on previous upgrades from 11.2 to 12.0

Could the be I'm using `iocage-devel`?

**Comment by sonicaj** [comment]
@dlangille iocage-devel does not change internals of a jail. So FreeBSD itself is taking care of these bits.

**Comment by dlangille** [comment]
For the record, the issue is visible within the paste diff.

That's comparing 10.2 against 12.0

Conclusion: `mergemaster` was never done on this jail after the upgrade from 10.2 to 11.x

Proposed solution: run `mergemaster` based on 11.2 source before upgrading the jails to 12.0
